"use client";

// Payroll — an extensive front-end payroll workspace for a UK children's-activity
// provider. Employees (the REAL team from Team & invites, plus anyone added by
// hand — pay details per person), pay runs paid from contracts or APPROVED
// timesheets (clock in/out) with approved leave applied, ESTIMATED PAYE /
// National Insurance / pension / net, branded payslips, and accounting
// integrations (QuickBooks / Xero / Sage). All figures are estimates for
// planning — real RTI/HMRC filing, exact tax codes and the live accounting
// sync are the backend/integration piece (Amir). Pay details, adjustments and
// every approved run live on the server (/api/payroll); the demo cast and the
// browser stores are for the guided tour (demo mode) only.
import { dateLocale as dl, currentLocaleCode } from "@/lib/i18n/format";
import { isRTL } from "@/lib/i18n/config";
import { tNow, useI18n } from "@/lib/i18n/provider";
import { pickPlural } from "@/lib/i18n/plural";
import { Rich } from "@/components/i18n/Rich";
import { KIND_KEY } from "@/features/holiday/kindKeys";
import { useEffect, useMemo, useState } from "react";
import { Button, Card, Input, Select } from "@/components/ui";
import { CollapsibleStats, LIGHT_PALETTE, PageHero } from "@/components/OperatorPage";
import { useSettings } from "@/lib/settings";
import { get as apiGet, isDemoMode, patch as apiPatch, post as apiPost, put as apiPut } from "@/lib/api";
import { DEMO_STAFF } from "@/features/learning/credentials";
import { useTeam, type TeamMember } from "@/features/team/useTeam";
import { fetchOnboarding } from "@/features/team/onboardStore";
import { loadAbsences as loadHolidayAbsences, loadProfiles as loadHolidayProfiles } from "@/features/holiday/data";
import { hhmm, loadClockSettings } from "@/features/timeclock/data";
import { isoDate, KIND_META, type AbsenceKind } from "@/lib/holiday";
import { csvCell } from "@/lib/csv";
import { AccountingIntegrations } from "./AccountingIntegrations";
import {
  type AdjItem, type Adjust, type ClockRec, type Emp, type Freq, type LeaveAbsence, type LeaveSum, type Line, type SickPay, type TimesheetSum,
  computeLine, employmentShare, grossMonthly, leaveForPeriod, PPY, FREQ_LABEL, r2, staffSlug, timesheetHours, clockPayHours, londonMs, ukShiftHours,
} from "./payCalc";
export type { AdjItem, Adjust, Freq, Line } from "./payCalc";

const gbp = (n: number) => "£" + (n || 0).toLocaleString(dl(), { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const gbp0 = (n: number) => "£" + Math.round(n || 0).toLocaleString(dl());
const escH = (s: unknown = "") => String(s ?? "").replace(/[<>&"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" }[c] as string));
const errMsg = (e: unknown) => (e instanceof Error ? e.message : tNow("p8wf.noConnection"));
// Display helpers (module level, so they read the language the picker is on via tNow). Stored values stay English.
const daysOf = (n: number) => pickPlural(tNow, currentLocaleCode(), "p8wf.prDays", n);
const kindLc = (k: string) => { const key = KIND_KEY[k as AbsenceKind]; return (key ? tNow(key) : k).toLocaleLowerCase(dl()); };
const leaveLabel = (lv: LeaveSum) => Object.entries(lv.byKind).map(([k, d]) => pickPlural(tNow, currentLocaleCode(), "p8wf.prDayKind", d, { kind: kindLc(k) })).join(" · ");
// The CSV export is an interchange file for accountants: it keeps the English wording whatever the UI language.
const leaveLabelEn = (lv: LeaveSum) => Object.entries(lv.byKind).map(([k, d]) => `${d} day${d === 1 ? "" : "s"} ${(KIND_META[k as AbsenceKind]?.label ?? k).toLowerCase()}`).join(" · ");
/** Canonical frequency label ("Weekly"...) -> the active language. */
const freqName = (label: string) => { const k = ({ Weekly: "prFreqWeekly", Fortnightly: "prFreqFortnightly", "4-weekly": "prFreqFourweekly", Monthly: "prFreqMonthly" } as Record<string, string>)[label]; return k ? tNow("p8wf." + k) : label; };
/** Pay-run lines carry English labels generated by the calc engine (id "__holpay"...); show them in the active language, leave typed labels alone. */
const adjLabel = (x: AdjItem, fallback: string) => {
  const dayN = /(\d+) day/.exec(x.label); const hrs = /× ([\d.]+)h$/.exec(x.label);
  if (x.id === "__holpay") return tNow("p8wf.prAdjHolRolled");
  if (x.id === "__leavepay" && dayN && hrs) return tNow("p8wf.prAdjLeavePay", { days: daysOf(Number(dayN[1])), h: hrs[1] });
  if (x.id === "__sickpay" && dayN && hrs) return tNow("p8wf.prAdjSickPay", { days: daysOf(Number(dayN[1])), h: hrs[1] });
  if (x.id === "__studentloan") { const pl = /Plan (\d+)/.exec(x.label); if (x.label === "Postgraduate loan") return tNow("p8wf.prPostgrad"); if (pl) return tNow("p8wf.prStudentLoanItem", { plan: tNow("p8wf.prPlanN", { n: pl[1] }) }); }
  return x.label || fallback;
};

export interface PayRun { id: string; period: string; paidOn: string; lines: Line[]; status: "draft" | "approved"; hoursBasis?: "contracted" | "rota" | "timesheet"; freq?: Freq; window?: { start: string; end: string }; createdAt?: string; publishedAt?: string | null; accounting?: { provider?: string; status?: string; journalId?: string; error?: string } }
export const PAYROLL_RUNS_KEY = "aos.payroll.runs.v1";

// Standalone payslip window — shared by the operator Payroll view and the staff
// My-payslips view. YTD is summed from every run the employee appears in.
export function openPayslip(l: Line, period: string, paidOn: string, provider: string, runs: PayRun[]) {
  if (typeof window === "undefined") return;
  const paid = new Date(`${paidOn}T12:00:00`); const mo = paid.getMonth();
  const taxMonth = ((mo - 3 + 12) % 12) + 1; const taxYearStart = mo >= 3 ? paid.getFullYear() : paid.getFullYear() - 1;
  // YTD = this tax year's runs up to and including this one (not every run ever)
  const tyFrom = `${taxYearStart}-04-06`;
  const ytdL = runs.filter((r) => r.status !== "draft" && r.paidOn >= tyFrom && r.paidOn <= paidOn).flatMap((r) => r.lines).filter((x) => x.id === l.id);
  const ytd = (k: keyof Line) => ytdL.reduce((a, x) => a + (typeof x[k] === "number" ? (x[k] as number) : 0), 0);
  const ty = `${taxYearStart}/${String((taxYearStart + 1) % 100).padStart(2, "0")}`;
  const tr = tNow; const loc = currentLocaleCode();
  const freqLabel = l.freqLabel || "Monthly";
  const taxWeek = Math.min(53, Math.max(1, Math.floor((Date.UTC(paid.getFullYear(), paid.getMonth(), paid.getDate()) - Date.UTC(taxYearStart, 3, 6)) / (7 * 86400000)) + 1));
  const taxPeriod = freqLabel === "Weekly" ? tr("p8wf.prTaxWeek", { n: taxWeek, ty }) : freqLabel === "Monthly" ? tr("p8wf.prTaxMonth", { n: taxMonth, ty }) : tr("p8wf.prTaxOther", { freq: freqName(freqLabel), ty });
  // Inline break-inside, not a class — this payslip is fully standalone HTML
  // opened via window.open()+document.write(), so it never gets app/globals.css.
  const row = (k: string, v: string, strong = false) => `<tr style="break-inside:avoid;page-break-inside:avoid"><td>${escH(k)}</td><td style="text-align:end${strong ? ";font-weight:800" : ""}">${escH(v)}</td></tr>`;
  const basePay = l.basePayM ?? l.grossM;
  const unpaidM = l.unpaidLeaveM || 0, sickM = l.sickLeaveM || 0, lv = l.leave;
  const plural = daysOf;
  // unpaid leave: off the salary as its own line; for hourly staff the hours are already net of it
  const baseRow = l.basis === "hour"
    ? row(tr(l.hoursFrom === "timesheet" ? "p8wf.prBasicHrsTs" : "p8wf.prBasicHrs", { hrs: l.hoursM, rate: l.rate.toFixed(2) }), gbp(basePay)) + (unpaidM > 0 && lv ? row(tr("p8wf.prUnpaidHrs", { days: plural(lv.unpaidDays), hrs: r2(unpaidM / (l.rate || 1)) }), "—") : "") + (sickM > 0 && lv ? row(tr("p8wf.prSickHrs", { days: plural(lv.sickDays), hrs: r2(sickM / (l.rate || 1)) }), "—") : "")
    : row(tr("p8wf.prSalary"), gbp(basePay + unpaidM + sickM)) + (unpaidM > 0 && lv ? row(tr("p8wf.prUnpaidDays", { days: plural(lv.unpaidDays) }), "−" + gbp(unpaidM)) : "") + (sickM > 0 && lv ? row(tr("p8wf.prSickSspRow", { days: plural(lv.sickDays) }), "−" + gbp(sickM)) : "");
  const pays = baseRow + (l.additions || []).map((x) => row(adjLabel(x, tr("p8wf.prAddition")), gbp(x.amount))).join("");
  const leaveMeta = lv && Object.keys(lv.byKind).length ? `<div style="grid-column:1/-1">${escH(tr("p8wf.prLeaveMeta"))} · <b>${escH(leaveLabel(lv))}</b></div>` : "";
  const statNote = lv && (lv.sickDays || lv.statutoryDays) ? ` <b>${escH(tr("p8wf.prStatNote", { list: [lv.sickDays ? `${tr("p8wf.prStatSick", { days: plural(lv.sickDays) })}${l.sickPay === "ssp" ? tr("p8wf.prStatSickSsp") : l.sickPay === "full" ? tr("p8wf.prStatSickFull") : ""}` : "", lv.statutoryDays ? tr("p8wf.prStatLeave", { days: plural(lv.statutoryDays) }) : ""].filter(Boolean).join(tr("p8wf.prAndJoin")) }))}</b>` : "";
  const deds = row(tr("p8wf.prPayeEst"), gbp(l.payeM)) + row(tr("p8wf.prEeNiEst"), gbp(l.eeNiM)) + row(tr("p8wf.prPensionAuto"), gbp(l.eePenM)) + (l.deductions || []).map((x) => row(adjLabel(x, tr("p8wf.prDeduction")), gbp(x.amount))).join("");
  const html = `<!doctype html><html lang="${loc}" dir="${isRTL(loc) ? "rtl" : "ltr"}"><head><meta charset="utf-8"><title>${escH(tr("p8wf.prSlipTitle", { name: l.name }))}</title><style>body{font-family:-apple-system,'Segoe UI',Arial,sans-serif;color:#1a1c2b;max-width:660px;margin:0 auto;padding:40px}h1{font-size:20px;margin:0}.tag{display:inline-block;background:#fdf3e0;color:#8a5a09;border-radius:99px;padding:2px 9px;font-size:10.5px;font-weight:800;margin-bottom:6px}.sub{color:#6b7086;font-size:12px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:2px 18px;font-size:12px;color:#4a4763;margin:14px 0;border-top:1px solid #e5e7f0;padding-top:12px}.meta b{color:#1a1c2b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:16px 0}h3{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#3557b7;border-bottom:1px solid #e5e7f0;padding-bottom:4px}table{width:100%;border-collapse:collapse;font-size:13px}td{padding:5px 0;border-top:1px solid #eef1f7}.net{background:#eef4fd;border-radius:10px;padding:14px;margin-top:14px;display:flex;justify-content:space-between;align-items:center}.net b{font-size:22px;color:#1d3a8f}.est{font-size:11px;color:#8a92a8;margin-top:14px}@media print{body{padding:0}}</style></head><body>
    <div style="display:flex;justify-content:space-between;align-items:flex-start"><div><span class="tag">${escH(tr("p8wf.prSlipTag"))}</span><h1>${escH(provider)}</h1><div class="sub">${escH(tr("p8wf.prSlipSub", { period, date: paid.toLocaleDateString(dl(), { day: "numeric", month: "short", year: "numeric" }) }))}</div></div><div style="text-align:end"><div style="font-weight:800">${escH(l.name)}</div><div class="sub">${escH(l.role)} · ${escH(l.op)}</div></div></div>
    <div class="meta"><div>${escH(tr("p8wf.prTaxCode"))} · <b>${escH(l.taxCode)}</b></div><div>${escH(tr("p8wf.prNiCat"))} · <b>${escH(l.niCat)}</b></div><div>${escH(tr("p8wf.prTaxPeriod"))} · <b>${escH(taxPeriod)}</b></div><div>${escH(tr("p8wf.prFrequency"))} · <b>${escH(freqName(freqLabel))}</b></div>${leaveMeta}</div>
    <div class="grid"><div><h3>${escH(tr("p8wf.prPayments"))}</h3><table>${pays}${(l.additions || []).length || ((unpaidM > 0 || sickM > 0) && l.basis === "year") ? row(tr("p8wf.prGrossPay"), gbp(l.grossM), true) : ""}</table></div><div><h3>${escH(tr("p8wf.prDeductionsH"))}</h3><table>${deds}</table></div></div>
    <div class="net"><span>${escH(tr("p8wf.prNetBacs"))}</span><b>${gbp(l.netM)}</b></div>
    <div class="grid"><div><h3>${escH(tr("p8wf.prYtd", { ty }))}</h3><table>${row(tr("p8wf.prGross"), gbp(ytd("grossM")))}${row(tr("p8wf.prPaye"), gbp(ytd("payeM")))}${row(tr("p8wf.prEeNi"), gbp(ytd("eeNiM")))}${row(tr("p8wf.prPension"), gbp(ytd("eePenM")))}${row(tr("p8wf.prNet"), gbp(ytd("netM")), true)}</table></div><div><h3>${escH(tr("p8wf.prEmployerCosts"))}</h3><table>${row(tr("p8wf.prErNi"), gbp(l.erNiM))}${row(tr("p8wf.prErPension"), gbp(l.erPenM))}${row(tr("p8wf.prTotalCost"), gbp(l.grossM + l.erNiM + l.erPenM), true)}</table></div></div>
    <div class="est">${escH(tr("p8wf.prSlipEst", { code: l.taxCode }))}${statNote}</div>
    <script>window.onload=function(){setTimeout(function(){window.print()},400)}</script></body></html>`;
  const w = window.open(); if (w) { w.document.write(html); w.document.close(); }
}
// Browser stores — the guided tour (demo mode) only; a real account's payroll is on the server.
const readLocal = <T,>(k: string): T | null => { try { return JSON.parse(localStorage.getItem(k) || "null") as T | null; } catch { return null; } };
const EKEY = "aos.payroll.employees.v2"; // v2 — added weeks/year, stable ids
const RKEY = PAYROLL_RUNS_KEY;
const IKEY = "aos.payroll.integrations.v1";
const ADJKEY = "aos.payroll.adjust.v1"; // period -> empId -> per-run Adjust

const DEMO_PAY: Record<string, Partial<Emp>> = {
  "Marcus Bell": { basis: "year", rate: 26000, hpw: 40, pension: true },
  "Jess Patel": { basis: "hour", rate: 13.5, hpw: 22, pension: true },
  "Aisha Rahman": { basis: "hour", rate: 14.25, hpw: 30, pension: true },
  "Tom Lewis": { basis: "hour", rate: 12.5, hpw: 16, pension: false },
  "Priya Khan": { basis: "hour", rate: 12.5, hpw: 18, pension: true },
  "Dan Reed": { basis: "year", rate: 31000, hpw: 40, pension: true },
};

type OnbRec = { staff: string; values: Record<string, { v?: string } | undefined> };
// pay/hours captured in a person's onboarding record ("payRate" field), if any
function onboardingPay(recs: OnbRec[], name: string): { basis: "hour" | "year"; rate: number; hpw?: number } | null {
  const rec = recs.find((r) => (r.staff || "").trim().toLowerCase() === name.trim().toLowerCase());
  try {
    const p = JSON.parse(rec?.values?.payRate?.v || "null");
    const rate = p?.amount ? parseFloat(String(p.amount).replace(/[£,]/g, "")) : NaN;
    if (!(rate > 0)) return null;
    return { basis: p.basis === "year" ? "year" : "hour", rate, hpw: parseFloat(p.hpw) || undefined };
  } catch { return null; }
}

// Demo mode (guided tour) only: the demo cast.
function seedEmployees(): Emp[] {
  let onb: OnbRec[] = [];
  try { onb = JSON.parse(localStorage.getItem("aos.team.onboardrecords.v1") || "[]"); } catch { /* ignore */ }
  return DEMO_STAFF.map((s) => {
    const d = DEMO_PAY[s.name] ?? { basis: "hour", rate: 12.5, hpw: 20, pension: true };
    const p = onboardingPay(onb, s.name);
    const basis = p?.basis ?? (d.basis as "hour" | "year"), rate = p?.rate ?? (d.rate as number), hpw = p?.hpw ?? (d.hpw as number);
    const id = typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : "emp_" + s.name.replace(/\s/g, "");
    return { id, name: s.name, role: s.role, op: s.op, basis, rate, hpw, weeks: basis === "hour" ? 45 : 52, taxCode: "1257L", niCat: "A", pension: d.pension ?? true };
  });
}

// A real team member with no pay details saved yet: whatever onboarding (or
// the Schedule's rate) already knows; hourly, paid from approved timesheets.
// Rate 0 = "needs pay details" (shown on the row) — never a made-up figure.
function defaultEmp(t: TeamMember, onb: OnbRec[], rotaRate?: number): Emp {
  const p = onboardingPay(onb, t.name);
  const basis = p?.basis ?? "hour";
  return { id: staffSlug(t.name), name: t.name, role: t.role || "", op: t.op || "", basis, rate: p?.rate ?? rotaRate ?? 0, hpw: p?.hpw ?? 0, weeks: 52, taxCode: "1257L", niCat: "A", pension: true, paidFrom: basis === "hour" ? "timesheet" : "contracted", source: "team" };
}
// "rota" was the old name of the timesheet source; salaried staff are always contracted
const sourceOf = (e: Emp): "contracted" | "timesheet" => (e.basis === "year" ? "contracted" : e.paidFrom === "rota" || e.paidFrom === "timesheet" ? "timesheet" : "contracted");

// ── Demo mode: hours from the Schedule's browser store ──────────────────────
// The guided tour has no server, so there its "timesheet" hours are the demo
// rota's clocked in/out (aos.rota.v5): prefers real check-in/out (in/out) over
// planned start/end and subtracts an unpaid break. Matched by name. A real
// account is paid from its APPROVED server timesheets (/api/payroll/timesheets).
const ROTA_KEY = "aos.rota.v5";
const rhm = (t: string) => { const [h, m] = (t || "0:0").split(":").map(Number); return (h || 0) * 60 + (m || 0); };
// (londonMs — UK wall-clock time → real instant, d16s7 — now lives in payCalc.)
/** Hours for a shift: clocked in/out over planned, overnight shifts wrap past
 *  midnight (they paid 0h), and the break is only taken off when breaks are
 *  unpaid (Setup → Scheduling; it was always taken off — d16s3). */
const shiftHours = (s: { date?: string; start: string; end: string; in?: string; out?: string; clockedBreakMin?: number; brk?: { from: string; to: string } }, breakPaid = false) => {
  const a = s.in || s.start, b = s.out || s.end;
  let gross = s.date ? (londonMs(s.date, b) - londonMs(s.date, a)) / 60000 : rhm(b) - rhm(a);
  if (gross < 0) gross += 24 * 60; // finished after midnight
  // A clocked-out shift carries the break actually taken; otherwise the planned one.
  const brk = breakPaid ? 0 : s.out && typeof s.clockedBreakMin === "number" ? s.clockedBreakMin : s.brk ? Math.max(0, rhm(s.brk.to) - rhm(s.brk.from)) : 0;
  return Math.max(0, gross - brk) / 60;
};
// rostered hours per staff member for shifts whose date falls in [startISO, endISO]
function rotaHoursForRange(startISO: string, endISO: string, breakPaid = false): { byName: Record<string, number>; rateByName: Record<string, number>; hasData: boolean } {
  const byName: Record<string, number> = {}; const rateByName: Record<string, number> = {};
  if (typeof window === "undefined") return { byName, rateByName, hasData: false };
  let store: { staff?: { id: string; name: string; rate?: number }[]; shifts?: { staffId: string | null; date: string; start: string; end: string; in?: string; out?: string; clockedBreakMin?: number; brk?: { from: string; to: string } }[] } | null = null;
  try { store = JSON.parse(localStorage.getItem(ROTA_KEY) || "null"); } catch { /* ignore */ }
  if (!store || !Array.isArray(store.shifts) || !Array.isArray(store.staff)) return { byName, rateByName, hasData: false };
  const idToName: Record<string, string> = {};
  store.staff.forEach((s) => { const nm = (s.name || "").trim().toLowerCase(); idToName[s.id] = s.name; if (nm && s.rate) rateByName[nm] = s.rate; });
  for (const sh of store.shifts) {
    if (!sh.staffId || !sh.date || sh.date < startISO || sh.date > endISO) continue;
    const nm = (idToName[sh.staffId] || "").trim().toLowerCase();
    if (nm) byName[nm] = (byName[nm] || 0) + shiftHours(sh, breakPaid);
  }
  return { byName, rateByName, hasData: store.shifts.length > 0 };
}

// The pay period for an anchor date at a given frequency: monthly = calendar
// month; weekly/fortnightly/4-weekly = a window ending on the anchor's Sunday.
// LOCAL calendar date — toISOString() is UTC, which moved every window a day
// early east of GMT (and in BST at midnight): September ran 31 Aug – 29 Sep.
const isoD = isoDate;
const fmtD = (d: Date) => d.toLocaleDateString(dl(), { day: "numeric", month: "short", year: "numeric" });
// The period LABEL is stored on the run and used as the key for per-run adjustments and duplicate-run detection, so it must not change
// with the UI language: it is always built in UK English (en-GB). `display` is the same period in the active language, for the screen.
const fmtDKey = (d: Date) => d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
const monthLabelKey = (d: Date) => d.toLocaleDateString("en-GB", { month: "long", year: "numeric" });
function periodWindow(anchor: Date, freq: Freq): { start: string; end: string; label: string; display: string; paidOn: string } {
  if (freq === "monthly") {
    const s = new Date(anchor.getFullYear(), anchor.getMonth(), 1);
    const e = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0);
    return { start: isoD(s), end: isoD(e), label: monthLabelKey(anchor), display: monthLabel(anchor), paidOn: isoD(e) };
  }
  const days = freq === "weekly" ? 7 : freq === "fortnightly" ? 14 : 28;
  const end = new Date(anchor); end.setDate(end.getDate() + ((7 - end.getDay()) % 7)); // this week's Sunday
  const start = new Date(end); start.setDate(start.getDate() - (days - 1));
  const label = `${FREQ_LABEL[freq]} · ${fmtDKey(start)} – ${fmtDKey(end)}`;
  const display = `${freqName(FREQ_LABEL[freq])} · ${fmtD(start)} – ${fmtD(end)}`;
  return { start: isoD(start), end: isoD(end), label, display, paidOn: isoD(end) };
}
// step the anchor one whole period forward (+1) or back (−1)
function stepAnchor(anchor: Date, freq: Freq, dir: number): Date {
  const d = new Date(anchor);
  if (freq === "monthly") d.setMonth(d.getMonth() + dir);
  else d.setDate(d.getDate() + dir * (freq === "weekly" ? 7 : freq === "fortnightly" ? 14 : 28));
  return d;
}

const monthLabel = (d: Date) => d.toLocaleDateString(dl(), { month: "long", year: "numeric" });
const INTEGRATIONS = [
  { id: "quickbooks", name: "QuickBooks", icon: "🟢", blurb: "p8wf.prBlurbQb" },
  { id: "xero", name: "Xero", icon: "🔵", blurb: "p8wf.prBlurbXero" },
  { id: "sage", name: "Sage", icon: "🟩", blurb: "p8wf.prBlurbSage" },
];

export function PayrollApp() {
  const { t, locale } = useI18n();
  const { settings } = useSettings();
  const provider = settings.providerName || settings.billing?.businessName || t("p8wf.prYourCompany");
  const demo = isDemoMode();
  const team = useTeam(); // the REAL team (joined staff, own franchise); the demo cast only in demo mode
  const [tab, setTab] = useState<"overview" | "employees" | "run" | "payslips" | "integrations">("overview");
  // pay details saved per person (server; demo: this browser). null = not loaded yet
  const [stored, setStored] = useState<Emp[] | null>(() => (demo ? (readLocal<Emp[]>(EKEY)?.length ? readLocal<Emp[]>(EKEY) : seedEmployees()) : null));
  const [loadErr, setLoadErr] = useState<string | null>(null);
  const [runs, setRuns] = useState<PayRun[]>(() => (demo ? readLocal<PayRun[]>(RKEY) ?? [] : []));
  const [conn, setConn] = useState<Record<string, boolean>>(() => readLocal<Record<string, boolean>>(IKEY) ?? {});
  const [edit, setEdit] = useState<{ emp: Emp; isNew?: boolean } | null>(null);
  const [adjEmp, setAdjEmp] = useState<Emp | null>(null); // employee whose pay-run adjustments are being edited
  const [toast, setToast] = useState<string | null>(null);
  const [freq, setFreq] = useState<Freq>("monthly");
  const [anchor, setAnchor] = useState<Date>(() => new Date());
  const [adjust, setAdjust] = useState<Record<string, Record<string, Adjust>>>(() => (demo ? readLocal<Record<string, Record<string, Adjust>>>(ADJKEY) ?? {} : {})); // period -> empId -> Adjust
  const [onb, setOnb] = useState<OnbRec[]>([]);
  const [rotaStore, setRotaStore] = useState<{ staff?: { id: string; name: string; rate?: number }[]; shifts?: { staffId: string | null; date: string; start: string; end: string }[] } | null>(null);
  const [absences, setAbsences] = useState<LeaveAbsence[]>(() => { try { return demo ? loadHolidayAbsences() : []; } catch { return []; } });
  const [profiles, setProfiles] = useState<{ id: string; name: string; holidayPay?: string }[]>(() => { try { return demo ? loadHolidayProfiles() : []; } catch { return []; } });
  const [clock, setClock] = useState<ClockRec[]>([]); // this period's timesheets (server)
  const [sickPay, setSickPay] = useState<SickPay>("full"); // company sick-pay rule (server; demo: this page only)
  const [clockTick, setClockTick] = useState(0);
  const [busy, setBusy] = useState(false);
  useEffect(() => {
    if (demo) return; // the tour reads this browser's stores (initial state above)
    apiGet<{ employees: Emp[] | null; adjust: Record<string, Record<string, Adjust>>; runs: PayRun[]; settings?: { sickPay?: SickPay } }>("/api/payroll")
      .then((r) => { setStored(r?.employees ?? []); setAdjust(r?.adjust ?? {}); setRuns(r?.runs ?? []); setSickPay(r?.settings?.sickPay === "ssp" ? "ssp" : "full"); })
      .catch((e) => setLoadErr(t("p8wf.prLoadErr", { err: errMsg(e) })));
    apiGet<{ absences: LeaveAbsence[]; profiles: { id: string; name: string; holidayPay?: string }[] }>("/api/leave").then((r) => { setAbsences(r?.absences ?? []); setProfiles(r?.profiles ?? []); }).catch(() => {});
    apiGet<{ staff: { id: string; name: string; rate?: number }[]; shifts: { staffId: string | null; date: string; start: string; end: string }[] }>("/api/rota").then((r) => setRotaStore(r)).catch(() => {});
    fetchOnboarding().then((r) => setOnb((r?.records ?? []) as OnbRec[])).catch(() => {});
  }, [demo]);
  const loaded = stored !== null;
  const flash = (m: string) => { setToast(m); setTimeout(() => setToast(null), 3200); };
  void locale;
  const cleanEmp = (e: Emp): Emp => ({ id: e.id, name: e.name, role: e.role || "", op: e.op || "", basis: e.basis, rate: Math.max(0, Number(e.rate) || 0), hpw: Math.min(100, Math.max(0, Number(e.hpw) || 0)), weeks: Math.min(53, Math.max(1, Number(e.weeks) || 52)), taxCode: (e.taxCode || "1257L").trim(), niCat: e.niCat || "A", pension: !!e.pension, ...(e.paidFrom ? { paidFrom: e.paidFrom === "rota" ? "timesheet" : e.paidFrom } : {}), ...(e.source ? { source: e.source } : {}), ...(e.startDate ? { startDate: e.startDate } : {}), ...(e.leaveDate ? { leaveDate: e.leaveDate } : {}), ...(e.studentLoanPlan && e.studentLoanPlan !== "none" ? { studentLoanPlan: e.studentLoanPlan } : {}), ...(e.director ? { director: true } : {}), ...(e.taxRegime && e.taxRegime !== "uk" ? { taxRegime: e.taxRegime } : {}) });
  const saveEmps = (next: Emp[]) => {
    if (demo) { setStored(next); try { localStorage.setItem(EKEY, JSON.stringify(next)); } catch { /* ignore */ } return; }
    if (!loaded) { flash(t("p8wf.prStillLoading")); return; }
    const prev = stored; setStored(next);
    apiPut("/api/payroll/employees", { employees: next.map(cleanEmp) }).catch((e) => { setStored(prev); flash(t("p8wf.prNotSaved", { err: errMsg(e) })); });
  };
  const saveSickPay = (v: SickPay) => {
    if (v === sickPay) return;
    const prev = sickPay; setSickPay(v);
    if (demo) return;
    apiPut("/api/payroll/settings", { sickPay: v }).then(() => flash(t(v === "ssp" ? "p8wf.prSickSspMsg" : "p8wf.prSickFullMsg"))).catch((e) => { setSickPay(prev); flash(t("p8wf.prNotSaved", { err: errMsg(e) })); });
  };
  const saveConn = (c: Record<string, boolean>) => { setConn(c); try { localStorage.setItem(IKEY, JSON.stringify(c)); } catch { /* ignore */ } };
  const saveAdjust = (a: Record<string, Record<string, Adjust>>, periodKey: string) => {
    setAdjust(a);
    if (demo) { try { localStorage.setItem(ADJKEY, JSON.stringify(a)); } catch { /* ignore */ } return; }
    apiPut("/api/payroll/adjust", { period: periodKey, adjust: a[periodKey] ?? null }).catch((e) => flash(t("p8wf.prAdjNotSaved", { err: errMsg(e) })));
  };

  // the pay period (window + label) for the chosen frequency & anchor date
  const win = useMemo(() => periodWindow(anchor, freq), [anchor, freq]);
  const period = win.label; // canonical (stored / keyed); `periodD` is what the screen shows
  const periodD = win.display;
  const fq = freqName(FREQ_LABEL[freq]);
  // this period's timesheets, from the server (every device's clockings)
  useEffect(() => {
    if (demo) return;
    let live = true;
    apiGet<ClockRec[]>(`/api/payroll/timesheets?from=${win.start}&to=${win.end}`).then((r) => { if (live) setClock(r ?? []); }).catch(() => { if (live) setClock([]); });
    return () => { live = false; };
  }, [demo, win.start, win.end, clockTick]);

  // Employees: everyone on the real team (their saved pay details, or what
  // onboarding / the Schedule already knows), then anyone added by hand or no
  // longer on the team (a leaver can still need a final pay run).
  const teamIds = useMemo(() => new Set(team.map((t) => staffSlug(t.name))), [team]);
  const rotaRateByKey = useMemo(() => { const m: Record<string, number> = {}; for (const s of rotaStore?.staff ?? []) if (s.name && s.rate) m[staffSlug(s.name)] = s.rate; return m; }, [rotaStore]);
  const emps: Emp[] = useMemo(() => {
    if (demo) return stored ?? [];
    const byId = new Map((stored ?? []).map((e) => [e.id, e]));
    const out: Emp[] = []; const seen = new Set<string>();
    for (const t of team) {
      const id = staffSlug(t.name); if (!id || seen.has(id)) continue; seen.add(id);
      const s = byId.get(id);
      out.push(s ? { ...s, name: t.name, role: s.role || t.role || "", source: "team" } : defaultEmp(t, onb, rotaRateByKey[id]));
    }
    for (const e of stored ?? []) if (!seen.has(e.id)) { seen.add(e.id); out.push(e); }
    return out;
  }, [demo, stored, team, onb, rotaRateByKey]);
  const tagOf = (e: Emp): string | null => (demo ? null : e.source === "manual" ? t("p8wf.prTagHand") : !teamIds.has(e.id) ? t("p8wf.prTagNotTeam") : null);

  // hours: approved timesheets (server) — the demo's are its browser rota
  const breakPaid = settings.scheduling?.breakPaid === "paid";
  const rota = useMemo(() => (demo ? rotaHoursForRange(win.start, win.end, breakPaid) : { byName: {} as Record<string, number>, rateByName: {}, hasData: false }), [demo, win.start, win.end, tab, breakPaid]);
  const clockPol = useMemo(() => loadClockSettings(), [tab]); // the Timesheets screen's pay policy (grace, rounding, overtime)
  // scheduled hours per person per day — the Timesheets screen's "Sched" (their
  // shift's end − start, in real time so the night the clocks change counts — d16s7)
  const schedMap = useMemo(() => {
    const idTo: Record<string, string> = {}; for (const s of rotaStore?.staff ?? []) idTo[s.id] = staffSlug(s.name || "");
    const m: Record<string, number> = {};
    for (const sh of rotaStore?.shifts ?? []) { if (!sh.staffId || !idTo[sh.staffId]) continue; const k = `${idTo[sh.staffId]}|${sh.date}`; if (!(k in m)) m[k] = ukShiftHours(sh.date, sh.start, sh.end); }
    return m;
  }, [rotaStore]);
  const schedFor = (e: Emp) => (day: string) => schedMap[`${staffSlug(e.name)}|${day}`] ?? 0;
  const tsFor = (e: Emp): TimesheetSum => {
    if (demo) { const h = rota.byName[e.name.trim().toLowerCase()]; return { approvedH: r2(h ?? 0), pendingH: 0, openDays: 0, overtimeUnpaidH: 0, days: h != null ? 1 : 0 }; }
    return timesheetHours(clock, staffSlug(e.name), schedFor(e), clockPol, breakPaid);
  };
  const tsRowsFor = (e: Emp) => clock.filter((r) => r.id === staffSlug(e.name) && r.clockInAt).sort((a, b) => a.day.localeCompare(b.day)).map((rec) => ({ rec, ...clockPayHours(rec, schedFor(e)(rec.day), clockPol, breakPaid) }));
  const setTimesheet = (rec: ClockRec, patch: Record<string, unknown>, msg: string) => {
    apiPatch(`/api/timeclock/${encodeURIComponent(rec.id)}?day=${rec.day}`, patch).then(() => { setClockTick((n) => n + 1); flash(msg); }).catch((e) => flash(t("p8wf.prTsNotUpdated", { err: errMsg(e) })));
  };

  // approved leave this period (the holiday planner). Rolled-up staff (holiday
  // INCLUDED IN PAY at 12.07%) get the separate 12.07% line instead of paid leave.
  const rolledUpKeys = useMemo(() => new Set(profiles.filter((p) => p.holidayPay === "rolled-up").flatMap((p) => [p.id, staffSlug(p.name || "")])), [profiles]);
  const isRolledUp = (e: Emp) => rolledUpKeys.has(staffSlug(e.name));
  const leaveOf = (e: Emp) => leaveForPeriod(absences, staffSlug(e.name), win.start, win.end, { rolledUp: isRolledUp(e) });

  // each hourly employee is paid from contracted hours OR approved timesheets
  // (their own setting); salaried staff are always contracted
  const empSource = sourceOf;
  const setSource = (id: string, src: "contracted" | "timesheet") => saveEmps(emps.map((x) => (x.id === id ? { ...x, paidFrom: src } : x)));
  const bulkSource = (src: "contracted" | "timesheet") => saveEmps(emps.map((x) => (x.basis === "hour" ? { ...x, paidFrom: src } : x)));
  const periodAdj = adjust[period] || {};
  const adjOf = (id: string): Adjust | undefined => periodAdj[id];
  // One person's line: a manual per-run hours override wins, else approved
  // timesheet hours if paid from timesheets, else contracted (less unpaid leave).
  const lineFor = (e: Emp, a: Adjust | undefined = adjOf(e.id)): Line => {
    const src = empSource(e);
    const manualH = a?.hours != null && e.basis === "hour";
    const hours = manualH ? (a!.hours as number) : e.basis === "hour" && src === "timesheet" ? tsFor(e).approvedH : undefined;
    const hoursFrom = e.basis !== "hour" ? undefined : manualH ? "manual" : src === "timesheet" ? "timesheet" : "contracted";
    return computeLine(e, { hours, taxCode: a?.taxCode, niCat: a?.niCat, additions: a?.additions, deductions: a?.deductions, override: a?.override, rolledUp: isRolledUp(e), hoursFrom, leave: leaveOf(e), sickPay, share: employmentShare(e, win.start, win.end).share }, freq);
  };
  // Who is on THIS run: a leaver drops out after their last day, a new starter only from their first (part-period = pro-rata)
  const payEmps = emps.filter((e) => employmentShare(e, win.start, win.end).employed);
  const notInRun = emps.filter((e) => !employmentShare(e, win.start, win.end).employed);
  const lines = payEmps.map((e) => lineFor(e));
  const isAdjusted = (e: Emp) => { const a = adjOf(e.id); return !!a && (a.hours != null || !!a.taxCode || !!a.niCat || !!(a.additions?.length) || !!(a.deductions?.length) || a.override?.paye != null || a.override?.eeNi != null || a.override?.eePen != null); };
  const tsEmps = payEmps.filter((e) => empSource(e) === "timesheet");
  const tsSum: Record<string, TimesheetSum> = Object.fromEntries(tsEmps.map((e) => [e.id, tsFor(e)]));
  const zeroHourNames = tsEmps.filter((e) => adjOf(e.id)?.hours == null && !(tsSum[e.id].approvedH > 0)).map((e) => e.name);
  const pendingEmps = tsEmps.filter((e) => tsSum[e.id].pendingH > 0 || tsSum[e.id].openDays > 0);
  const noRateNames = payEmps.filter((e) => !(e.rate > 0)).map((e) => e.name);
  const setEmpAdjust = (id: string, a: Adjust | null) => { const next = { ...adjust, [period]: { ...periodAdj } }; if (a) next[period][id] = a; else delete next[period][id]; if (Object.keys(next[period]).length === 0) delete next[period]; saveAdjust(next, period); };
  const totalGross = lines.reduce((a, l) => a + l.grossM, 0);
  const totalNet = lines.reduce((a, l) => a + l.netM, 0);
  const totalErCost = lines.reduce((a, l) => a + l.grossM + l.erNiM + l.erPenM, 0);
  const totalPaye = lines.reduce((a, l) => a + l.payeM, 0);
  const nextPay = new Date(`${win.paidOn}T00:00:00`);

  const runPayroll = async () => {
    if (!loaded || !lines.length) { flash(t(loaded ? "p8wf.prNoEmpToPay" : "p8wf.prStillLoadingShort")); return; }
    if (noRateNames.length && !window.confirm(t("p8wf.prConfirmNoRate", { names: noRateNames.join(", ") }))) return;
    if (zeroHourNames.length && !window.confirm(t("p8wf.prConfirmZero", { n: zeroHourNames.length, period: periodD, names: zeroHourNames.join(", ") }))) return;
    if (pendingEmps.length && !window.confirm(t("p8wf.prConfirmPending", { period: periodD, list: pendingEmps.map((e) => tsSum[e.id].openDays ? pickPlural(t, locale, "p8wf.prPendOpen", tsSum[e.id].openDays, { name: e.name, h: tsSum[e.id].pendingH }) : `${e.name} ${t("p8wf.hrsUnit", { n: tsSum[e.id].pendingH })}`).join(", ") }))) return;
    const dup = runs.some((r) => r.period === period);
    if (dup && !window.confirm(t("p8wf.prConfirmDup", { period: periodD }))) return;
    const body = { period, paidOn: win.paidOn, lines, hoursBasis: (tsEmps.length ? "timesheet" : "contracted") as PayRun["hoursBasis"], freq, window: { start: win.start, end: win.end } };
    if (demo) {
      const next = [{ id: "pr_" + new Date().getTime().toString(36), status: "approved" as const, ...body }, ...runs];
      setRuns(next); try { localStorage.setItem(RKEY, JSON.stringify(next)); } catch { /* ignore */ }
    } else {
      setBusy(true);
      try { const run = await apiPost<PayRun>("/api/payroll/runs", dup ? { ...body, allowDuplicate: true } : body); setRuns((rs) => [run, ...rs]); } // never delete a prior run — versioned history
      catch (e) { flash(t("p8wf.prNotSaved", { err: errMsg(e) })); return; }
      finally { setBusy(false); }
    }
    flash(`${pickPlural(t, locale, "p8wf.prRunDone", lines.length, { period: periodD, net: gbp0(totalNet), freq: fq })}${demo ? "" : t("p8wf.prRunDoneHint")}`);
    setTab("payslips");
  };
  // Segregation of duties (server-enforced): a run is created as a draft and
  // must be approved by someone OTHER than whoever created it before it can
  // be published to staff.
  const approveRun = async (r: PayRun) => {
    if (!window.confirm(t("p8wf.prConfirmApprove", { period: r.period }))) return;
    try {
      const run = await apiPost<PayRun>(`/api/payroll/runs/${encodeURIComponent(r.id)}/approve`, {});
      setRuns((rs) => rs.map((x) => (x.id === r.id ? { ...x, status: run.status } : x)));
      flash(t("p8wf.prRunApproved"));
    } catch (e) { flash(`⚠ ${errMsg(e)}`); }
  };
  // Real accounting connections (live accounts only): which providers are connected, and posting an approved run's wages journal.
  const [acctConn, setAcctConn] = useState<Record<string, { connected: boolean }>>({});
  const [posting, setPosting] = useState<string | null>(null);
  useEffect(() => { if (demo || tab !== "payslips") return; apiGet<Record<string, { connected: boolean }>>("/api/accounting/connections").then(setAcctConn).catch(() => setAcctConn({})); }, [demo, tab]);
  const ACCT_NAME: Record<string, string> = { quickbooks: "QuickBooks Online", xero: "Xero", sage: "Sage" };
  const postToAccounting = async (r: PayRun, provider: string) => {
    if (!window.confirm(t("p8wf.prConfirmPost", { period: r.period, provider: ACCT_NAME[provider] }))) return;
    setPosting(r.id);
    try {
      const res = await apiPost<{ provider: string; journalId: string; status: string }>(`/api/accounting/post/${encodeURIComponent(r.id)}?provider=${provider}`, {});
      setRuns((rs) => rs.map((x) => (x.id === r.id ? { ...x, accounting: { provider: res.provider, journalId: res.journalId, status: res.status } } : x)));
      flash(t("p8wf.prJournalPosted", { provider: ACCT_NAME[provider] }));
    } catch (e) { flash(`⚠ ${errMsg(e)}`); }
    finally { setPosting(null); }
  };
  const acctBtn = (r: PayRun) => {
    if (r.accounting?.status === "posted") return <span data-testid="acct-posted" className="ms-auto rounded-full bg-[#e6f4ea] px-2 py-0.5 text-[10px] font-bold text-[#0f7a43]">{t("p8wf.prPostedTo", { provider: ACCT_NAME[r.accounting.provider ?? ""] ?? t("p8wf.prAcctFallback") })}</span>;
    const ready = Object.keys(ACCT_NAME).filter((p) => acctConn[p]?.connected);
    if (!ready.length) return <button type="button" onClick={() => setTab("integrations")} className="ms-auto text-[11px] font-bold text-[var(--ink-3)] hover:text-[#1d3a8f]">{t("p8wf.prConnectAcct")}</button>;
    return <span className="ms-auto flex items-center gap-1.5">{ready.map((p) => <button key={p} type="button" disabled={posting === r.id} onClick={() => postToAccounting(r, p)} className="rounded-full border border-[var(--line)] px-2.5 py-0.5 text-[11px] font-bold text-[#1d3a8f] hover:border-[#1d3a8f] disabled:opacity-50">{posting === r.id ? t("p8wf.prPosting") : t("p8wf.prPostTo", { provider: ACCT_NAME[p] })}</button>)}</span>;
  };
  const publishRun = async (r: PayRun, on: boolean) => {
    if (on && !window.confirm(t("p8wf.prConfirmPublish", { period: r.period, n: r.lines.length }))) return;
    try {
      const res = await apiPost<{ publishedAt: string | null }>(`/api/payroll/runs/${encodeURIComponent(r.id)}/publish`, { published: on });
      setRuns((rs) => rs.map((x) => (x.id === r.id ? { ...x, publishedAt: res.publishedAt } : x)));
      flash(t(on ? "p8wf.prPublished" : "p8wf.prUnpublished"));
    } catch (e) { flash(`⚠ ${errMsg(e)}`); }
  };

  const showPayslip = (l: Line, period: string, paidOn: string) => openPayslip(l, period, paidOn, provider, runs);

  const exportCsv = () => {
    // guard against CSV/formula injection: shared lib/csv (quotes, neutralises leading = + - @ tab CR)
    const cell = (x: string | number) => csvCell(typeof x === "number" ? x.toFixed(2) : x);
    const rows = [["Employee", "Role", "Location", "Frequency", "Period", "Hours", "Hours basis", "Leave", "Base pay", "Unpaid leave", "Sick leave deducted (SSP only)", "Additions", "Deductions", "Tax code", "NI cat", "Gross", "PAYE", "EE NI", "Pension", "Net", "ER NI", "ER Pension"], ...lines.map((l) => [l.name, l.role, l.op, FREQ_LABEL[freq], period, l.basis === "year" ? "" : l.hoursM, l.basis === "year" ? "salary" : l.hoursFrom ?? "contracted", l.leave ? leaveLabelEn(l.leave) : "", l.basePayM, l.unpaidLeaveM ?? 0, l.sickLeaveM ?? 0, l.addM, l.dedM, l.taxCode, l.niCat, l.grossM, l.payeM, l.eeNiM, l.eePenM, l.netM, l.erNiM, l.erPenM])];
    const csv = rows.map((r) => r.map(cell).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
    const a = document.createElement("a"); a.href = url; a.download = `payroll-${monthLabelKey(new Date())}.csv`; a.click(); URL.revokeObjectURL(url);
  };

  const tile = (label: string, value: string, sub: string, grad: string) => (
    <div className="rounded-2xl p-4 text-white shadow-[0_18px_40px_-26px_rgba(16,32,90,.6)]" style={{ background: grad }}>
      <div className="text-[11px] font-bold uppercase tracking-wide text-white/85">{label}</div>
      <div className="mt-1 text-[26px] font-extrabold leading-none tabular-nums" style={{ fontFamily: "var(--ff-display)" }}>{value}</div>
      <div className="mt-1 text-[11.5px] text-white/85">{sub}</div>
    </div>
  );
  const chip = (text: string, tone: string, title?: string) => <span title={title} className={`rounded-full px-1.5 py-0.5 text-[9.5px] font-bold align-middle ${tone}`}>{text}</span>;

  return (
    <div className="-m-3 min-h-[calc(100vh-3.5rem)] p-3 sm:-m-5 sm:p-5" style={LIGHT_PALETTE}>
      <PageHero title={t("p8wf.prTitle")} icon="💷" lede={t("p8wf.prLede")} />
      {loadErr && <div className="mb-3 rounded-xl bg-[#fdecec] px-3 py-2 text-[12.5px] font-semibold text-[#c0392b]">⚠ {loadErr}</div>}

      <div className="mb-3 inline-flex flex-wrap gap-0.5 rounded-full border border-[var(--line)] bg-[var(--panel)] p-0.5">
        {([["overview", t("p8wf.prTabOverview")], ["employees", t("p8wf.prTabEmployees")], ["run", t("p8wf.prTabRun")], ["payslips", t("p8wf.prTabPayslips")], ["integrations", t("p8wf.prTabIntegrations")]] as const).map(([k, l]) => (
          <button key={k} type="button" onClick={() => setTab(k)} className={"rounded-full px-3.5 py-1.5 text-[12.5px] font-bold transition-colors " + (tab === k ? "bg-white text-[#1d3a8f] shadow-sm" : "text-[var(--ink-3)] hover:text-[var(--ink-2)]")}>{l}</button>
        ))}
      </div>

      {tab === "overview" && (<>
        <CollapsibleStats id="payroll">
        <div className="grid grid-cols-2 gap-2.5 lg:grid-cols-4">
          {tile(t(freq === "monthly" ? "p8wf.prTileGrossMonth" : "p8wf.prTileGrossPeriod"), gbp0(totalGross), t("p8wf.prTileGrossSub", { n: payEmps.length, freq: fq }), "linear-gradient(135deg,#1d3a8f,#3f7ae0)")}
          {tile(t("p8wf.prTileNet"), gbp0(totalNet), t("p8wf.prTileNetSub"), "linear-gradient(135deg,#166534,#37b26a)")}
          {tile(t("p8wf.prTileHmrc"), gbp0(totalPaye + lines.reduce((a, l) => a + l.eeNiM + l.erNiM, 0)), t("p8wf.prTileHmrcSub"), "linear-gradient(135deg,#9d174d,#f43f5e)")}
          {tile(t("p8wf.prTileEr"), gbp0(totalErCost), t("p8wf.prTileErSub"), "linear-gradient(135deg,#334155,#64748b)")}
        </div>
        </CollapsibleStats>
        <Card className="p-4">
          <div className="flex flex-wrap items-center gap-2"><div><div className="text-[13.5px] font-extrabold text-[var(--ink)]">{t("p8wf.prNextPayDay")}</div><div className="text-[12px] text-[var(--ink-3)]">{nextPay.toLocaleDateString(dl(), { weekday: "long", day: "numeric", month: "long" })} · {fq} · {periodD}</div></div><Button variant="primary" className="ms-auto" onClick={() => setTab("run")}>{t("p8wf.prRunPayrollBtn")}</Button></div>
          {runs.length > 0 && <div className="mt-3 border-t border-[var(--line)] pt-3"><div className="mb-1.5 text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prRecentRuns")}</div>{runs.slice(0, 3).map((r) => <div key={r.id} className="flex items-center gap-2 py-1 text-[12.5px]"><span className="font-bold text-[var(--ink)]">{r.period}</span><span className="text-[var(--ink-3)]">{t("p8wf.prRunSummary", { n: r.lines.length, net: gbp0(r.lines.reduce((a, l) => a + l.netM, 0)) })}</span><span className="ms-auto rounded-full bg-[#e6f4ea] px-2 py-0.5 text-[10px] font-bold text-[#0f7a43]">{r.publishedAt ? t("p8wf.prPublishedLc") : r.status === "approved" ? t("p8wf.prApprovedLc") : r.status === "draft" ? t("p8wf.prDraftLc") : r.status}</span></div>)}</div>}
        </Card>
      </>)}

      {tab === "employees" && (
        <Card className="p-4">
          <div className="mb-2 flex flex-wrap items-center gap-2"><div className="text-[12px] text-[var(--ink-3)]">{t(demo ? "p8wf.prEmpHelpDemo" : "p8wf.prEmpHelpLive")} {t("p8wf.prEmpHmrc")}</div><Button className="ms-auto" onClick={() => setEdit({ emp: { id: "", name: "", role: "", op: "", basis: "hour", rate: 0, hpw: 0, weeks: 52, taxCode: "1257L", niCat: "A", pension: true, paidFrom: "contracted", source: "manual" }, isNew: true })}>{t("p8wf.prAddEmp")}</Button></div>
          {!loaded && !loadErr && <div className="p-4 text-center text-[12.5px] text-[var(--ink-3)]">{t("p8wf.prLoadingPayroll")}</div>}
          {loaded && emps.length === 0 && <div className="rounded-xl bg-[var(--panel)] p-5 text-center text-[12.5px] text-[var(--ink-3)]"><Rich text={t("p8wf.prNoStaffYet")} /></div>}
          {emps.length > 0 && <div className="overflow-x-auto rounded-xl border border-[var(--line)]">
            <table className="w-full text-[13px]"><thead><tr className="bg-[var(--panel)] text-start text-[10px] uppercase tracking-wide text-[var(--ink-3)]"><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThEmployee")}</th><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThBasis")}</th><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThRate")}</th><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThHrsWk")}</th><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThPaidFrom")}</th><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThGrossMo")}</th><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThTaxCode")}</th><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prPension")}</th><th className="px-3 py-2.5"></th></tr></thead>
              <tbody>{emps.map((e) => { const tag = tagOf(e); return (
                <tr key={e.id} className="border-t border-[var(--line-2,#eef2f8)]"><td className="px-3 py-2.5 font-bold text-[var(--ink)]">{e.name}<span className="ms-1 text-[10.5px] font-normal text-[var(--ink-3)]">{e.role}</span>{tag && <span className="ms-1.5">{chip(tag, "bg-[#eef1f6] text-[#64748b]")}</span>}{!(e.rate > 0) && <span className="ms-1.5">{chip(t("p8wf.prNeedsPay"), "bg-[#fdf3e0] text-[#8a5a09]")}</span>}</td><td className="px-3 py-2.5 text-[var(--ink-2)]">{e.basis === "year" ? t("p8wf.prBasisSalary") : t("p8wf.prBasisHourly")}</td><td className="px-3 py-2.5 tabular-nums text-[var(--ink-2)]">{e.basis === "year" ? t("p8wf.prPerYr", { amt: gbp0(e.rate) }) : t("p8wf.prPerHr", { amt: e.rate.toFixed(2) })}</td><td className="px-3 py-2.5 tabular-nums text-[var(--ink-2)]">{e.basis === "year" ? "—" : e.hpw}</td><td className="px-3 py-2.5 text-[12px] text-[var(--ink-2)]">{e.basis === "year" ? t("p8wf.prBasisSalary") : empSource(e) === "timesheet" ? t("p8wf.prSrcTimesheets") : t("p8wf.prSrcContract")}</td><td className="px-3 py-2.5 font-bold tabular-nums text-[var(--ink)]">{e.basis === "hour" && empSource(e) === "timesheet" ? <span className="font-normal text-[var(--ink-3)]">{t("p8wf.prByHours")}</span> : gbp0(grossMonthly(e))}</td><td className="px-3 py-2.5 tabular-nums text-[var(--ink-2)]">{e.taxCode}</td><td className="px-3 py-2.5">{e.pension ? <span className="rounded-full bg-[#e6f4ea] px-2 py-0.5 text-[10px] font-bold text-[#0f7a43]">{t("p8wf.prEnrolled")}</span> : <span className="rounded-full bg-[#eef1f6] px-2 py-0.5 text-[10px] font-bold text-[#64748b]">{t("p8wf.prOptedOut")}</span>}</td><td className="px-3 py-2.5 text-end"><button type="button" onClick={() => setEdit({ emp: e })} className="text-[12px] font-bold text-[#1d3a8f] hover:underline">{t("p8wf.prEdit")}</button></td></tr>
              ); })}</tbody>
            </table>
          </div>}
        </Card>
      )}

      {tab === "run" && (
        <Card className="p-4">
          <div className="mb-3 flex flex-wrap items-center gap-2"><div><div className="text-[14px] font-extrabold text-[var(--ink)]">{t("p8wf.prRunTitle")}</div><div className="text-[12px] text-[var(--ink-3)]">{t("p8wf.prRunLede")}</div></div><div className="ms-auto flex gap-2"><Button onClick={exportCsv}>{t("p8wf.prExportCsv")}</Button><Button variant="primary" onClick={runPayroll} disabled={busy || !loaded}>{busy ? t("p8wf.prSaving") : t("p8wf.prCreateRun")}</Button></div></div>

          {/* Frequency + period picker */}
          <div className="mb-3 flex flex-wrap items-center gap-3 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-3">
            <div className="flex items-center gap-2"><span className="text-[11px] font-extrabold uppercase tracking-wide text-[var(--ink-3)]">{t("p8wf.prFrequency")}</span>
              <div className="inline-flex overflow-hidden rounded-lg border border-[var(--line)]">
                {(["weekly", "fortnightly", "fourweekly", "monthly"] as Freq[]).map((f) => (
                  <button key={f} type="button" onClick={() => setFreq(f)} className={`px-2.5 py-1.5 text-[11.5px] font-bold ${freq === f ? "bg-[#1d3a8f] text-white" : "bg-white text-[var(--ink-2)] hover:bg-[#f2f5fb]"}`}>{freqName(FREQ_LABEL[f])}</button>
                ))}
              </div>
            </div>
            <div className="flex items-center gap-1.5"><span className="text-[11px] font-extrabold uppercase tracking-wide text-[var(--ink-3)]">{t("p8wf.prPeriod")}</span>
              <button type="button" onClick={() => setAnchor(stepAnchor(anchor, freq, -1))} className="rounded-lg border border-[var(--line)] px-2 py-1 text-[13px] font-bold text-[var(--ink-2)] hover:border-[#1d3a8f]">{isRTL(locale) ? "›" : "‹"}</button>
              <span className="min-w-[150px] text-center text-[12.5px] font-bold text-[var(--ink)]">{periodD}</span>
              <button type="button" onClick={() => setAnchor(stepAnchor(anchor, freq, 1))} className="rounded-lg border border-[var(--line)] px-2 py-1 text-[13px] font-bold text-[var(--ink-2)] hover:border-[#1d3a8f]">{isRTL(locale) ? "‹" : "›"}</button>
              <button type="button" onClick={() => setAnchor(new Date())} className="ms-1 text-[11px] font-bold text-[#1d3a8f] hover:underline">{t("p7tc.todayLbl")}</button>
            </div>
            <span className="text-[11px] text-[var(--ink-3)]">{t("p8wf.prPaidOn", { date: nextPay.toLocaleDateString(dl(), { weekday: "short", day: "numeric", month: "short" }) })}</span>
          </div>

          {/* Per-employee hours source — mix contracted (e.g. admin) and approved timesheets (clock in/out) */}
          <div className="mb-3 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-3">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-[11px] font-extrabold uppercase tracking-wide text-[var(--ink-3)]">{t("p8wf.prHourlyPaidFrom")}</span>
              <span className="text-[11.5px] text-[var(--ink-3)]">{t("p8wf.prSetPerPerson")}</span>
              <button type="button" onClick={() => bulkSource("contracted")} className="rounded-full border border-[var(--line)] px-2.5 py-0.5 text-[11px] font-bold text-[var(--ink-2)] hover:border-[#1d3a8f]">{t("p8wf.prContracted")}</button>
              <button type="button" onClick={() => bulkSource("timesheet")} className="rounded-full border border-[var(--line)] px-2.5 py-0.5 text-[11px] font-bold text-[var(--ink-2)] hover:border-[#1d3a8f]">{t("p8wf.prApprovedTs")}</button>
            </div>
            {/* Company sick-pay rule (s13-pay3) */}
            <div className="mt-2 flex flex-wrap items-center gap-2 border-t border-[var(--line)] pt-2">
              <span className="text-[11px] font-extrabold uppercase tracking-wide text-[var(--ink-3)]">{t("p8wf.prSickPayLbl")}</span>
              <div className="inline-flex overflow-hidden rounded-lg border border-[var(--line)]">
                {([["full", t("p8wf.prOptSickFull")], ["ssp", t("p8wf.prOptSickSsp")]] as [SickPay, string][]).map(([v, label]) => (
                  <button key={v} type="button" onClick={() => saveSickPay(v)} className={`px-2.5 py-1.5 text-[11.5px] font-bold ${sickPay === v ? "bg-[#1d3a8f] text-white" : "bg-white text-[var(--ink-2)] hover:bg-[#f2f5fb]"}`}>{label}{v === "full" ? t("p8wf.prDefaultTag") : ""}</button>
                ))}
              </div>
              <span className="text-[11.5px] text-[var(--ink-3)]">{t(sickPay === "ssp" ? "p8wf.prSickHelpSsp" : "p8wf.prSickHelpFull")}</span>
            </div>
            {demo && tsEmps.length > 0 && !rota.hasData && <div className="mt-2 rounded-lg bg-[#fdf3e0] px-3 py-2 text-[11.5px] font-semibold text-[#8a5a09]">{t("p8wf.prDemoNoClock", { period: periodD })}</div>}
            {tsEmps.length > 0 && (() => { const totH = tsEmps.reduce((n, e) => n + tsSum[e.id].approvedH, 0); const totW = tsEmps.reduce((n, e) => n + tsSum[e.id].approvedH * e.rate, 0); return <div className="mt-2 rounded-lg bg-[#eef4fd] px-3 py-2 text-[11.5px] font-semibold text-[#1d3a8f]"><Rich text={t(demo ? "p8wf.prFromSched" : "p8wf.prFromTs", { period: periodD, hrs: t("p8wf.hrsUnit", { n: r2(totH) }), n: tsEmps.length, amt: gbp0(totW) })} /></div>; })()}
            {pendingEmps.length > 0 && <div className="mt-2 rounded-lg bg-[#fdf3e0] px-3 py-2 text-[11.5px] font-semibold text-[#8a5a09]"><Rich text={t("p8wf.prPendBanner", { list: pendingEmps.map((e) => `${e.name} ${t("p8wf.hrsUnit", { n: tsSum[e.id].pendingH })}${tsSum[e.id].openDays ? pickPlural(t, locale, "p8wf.prPendItemOpen", tsSum[e.id].openDays) : ""}`).join(", ") })} /></div>}
            {tsEmps.length > 0 && zeroHourNames.length > 0 && <div className="mt-2 rounded-lg bg-[#fdf3e0] px-3 py-2 text-[11.5px] font-semibold text-[#8a5a09]">{t("p8wf.prZeroBanner", { names: zeroHourNames.join(", ") })}</div>}
            {notInRun.length > 0 && <div data-testid="not-in-run" className="mt-2 rounded-lg bg-[var(--panel)] px-3 py-2 text-[11.5px] font-semibold text-[var(--ink-3)]">{t("p8wf.prNotInRun", { period: periodD, list: notInRun.map((e) => `${e.name} (${e.startDate && e.startDate > win.end ? t("p8wf.prStartsOn", { date: e.startDate }) : t("p8wf.prLeftOn", { date: e.leaveDate ?? "" })})`).join(", ") })}</div>}
            {noRateNames.length > 0 && <div className="mt-2 rounded-lg bg-[#fdf3e0] px-3 py-2 text-[11.5px] font-semibold text-[#8a5a09]">{(() => { const [a, b] = t("p8wf.prNoRateBanner", { names: noRateNames.join(", "), link: "\u0000" }).split("\u0000"); return <>{a}<button type="button" onClick={() => setTab("employees")} className="underline">{t("p8wf.prEmployeesWord")}</button>{b}</>; })()}</div>}
          </div>

          <div className="mb-2 text-[11.5px] text-[var(--ink-3)]"><Rich text={t("p8wf.prEditHelp")} /></div>
          <div className="overflow-x-auto rounded-xl border border-[var(--line)]">
            <table className="w-full text-[12.5px]"><thead><tr className="bg-[var(--panel)] text-start text-[10px] uppercase tracking-wide text-[var(--ink-3)]"><th className="px-3 py-2.5 font-extrabold">{t("p8wf.prThEmployee")}</th><th className="px-3 py-2.5 text-end font-extrabold">{t("p8wf.prThHours")}</th><th className="px-3 py-2.5 text-end font-extrabold">{t("p8wf.prGross")}</th><th className="px-3 py-2.5 text-end font-extrabold">{t("p8wf.prPaye")}</th><th className="px-3 py-2.5 text-end font-extrabold">NI</th><th className="px-3 py-2.5 text-end font-extrabold">{t("p8wf.prPension")}</th><th className="px-3 py-2.5 text-end font-extrabold">{t("p8wf.prNet")}</th><th className="px-3 py-2.5 text-end font-extrabold">{t("p8wf.prThErCost")}</th><th className="px-3 py-2.5 text-end font-extrabold"></th></tr></thead>
              <tbody>{lines.map((l, i) => { const e = payEmps[i]; const ts = tsSum[e.id]; const lv = l.leave; const man = (on: boolean) => on ? <sup className="ms-0.5 text-[8px] font-black text-[#b45309]" title={t("p8wf.prManualOverride")}>M</sup> : null; return (
                <tr key={l.id} className="border-t border-[var(--line-2,#eef2f8)]">
                  <td className="px-3 py-2 font-bold text-[var(--ink)]">{l.name}{isAdjusted(e) && <span className="ms-1.5">{chip(t("p8wf.prChipAdjusted"), "bg-[#fdf3e0] text-[#8a5a09]")}</span>}{l.proRata != null && <span className="ms-1.5">{chip(t("p8wf.prChipProRata", { pct: Math.round(l.proRata * 100) }), "bg-[#eef4fd] text-[#1d3a8f]", e.startDate && e.startDate > win.start ? t("p8wf.prTipStarted", { date: e.startDate }) : t("p8wf.prTipLeft", { date: e.leaveDate ?? "" }))}</span>}{isRolledUp(e) && <span className="ms-1.5">{chip(t("p8wf.prChipRolled"), "bg-[#eef1f6] text-[#64748b]", t("p8wf.prTipRolled"))}</span>}
                    {(l.addM > 0 || l.dedM > 0) && <div className="mt-0.5 text-[10px] font-semibold text-[var(--ink-3)]">{l.addM > 0 && <span className="text-[#0f7a43]">{t("p8wf.prAdditionsLine", { amt: gbp(l.addM) })}</span>}{l.addM > 0 && l.dedM > 0 && " · "}{l.dedM > 0 && <span className="text-[#c0392b]">{t("p8wf.prDeductionsLine", { amt: gbp(l.dedM) })}</span>}</div>}
                    {lv && <div className="mt-0.5 flex flex-wrap items-center gap-1 text-[10px] font-semibold">{Object.entries(lv.byKind).map(([k, d]) => <span key={k} className="rounded-full bg-[#eef4fd] px-1.5 py-0.5 text-[#1d3a8f]">{KIND_META[k as AbsenceKind]?.icon ?? "🗓️"} {t("p8wf.prDaysAbbr", { n: d })} {kindLc(k)}</span>)}{(l.unpaidLeaveM ?? 0) > 0 && <span className="text-[#c0392b]">{t("p8wf.prUnpaidLine", { amt: gbp(l.unpaidLeaveM ?? 0) })}</span>}{(l.sickLeaveM ?? 0) > 0 && <span className="text-[#c0392b]">{t("p8wf.prSickLine", { amt: gbp(l.sickLeaveM ?? 0) })}</span>}</div>}
                    {lv && lv.paidDays > 0 && l.hoursFrom === "timesheet" && !(e.hpw > 0) && !isRolledUp(e) && <div className="mt-0.5 text-[10px] font-bold text-[#b45309]">{t("p8wf.prWarnPaidLeave", { n: lv.paidDays })}</div>}
                    {lv && lv.sickDays > 0 && (sickPay === "ssp"
                      ? <div className="mt-0.5 text-[10px] font-bold text-[#b45309]">{t(l.hoursFrom === "manual" ? "p8wf.prSspHand" : l.hoursFrom === "timesheet" ? "p8wf.prSspNotClocked" : "p8wf.prSspDeducted", { n: lv.sickDays })}</div>
                      : l.hoursFrom === "timesheet" && !(e.hpw > 0)
                        ? <div className="mt-0.5 text-[10px] font-bold text-[#b45309]">{t("p8wf.prSickNotValued", { n: lv.sickDays })}</div>
                        : <div className="mt-0.5 text-[10px] font-semibold text-[#0f7a43]">{t(l.hoursFrom === "timesheet" ? "p8wf.prSickFullTs" : l.hoursFrom === "manual" ? "p8wf.prSickFullHand" : "p8wf.prSickFullPlain", { n: lv.sickDays })}</div>)}
                    {lv && lv.statutoryDays > 0 && <div className="mt-0.5 text-[10px] font-bold text-[#b45309]">{t(l.hoursFrom === "timesheet" ? "p8wf.prStatWarnTs" : "p8wf.prStatWarnKeep", { n: lv.statutoryDays })}</div>}
                    {ts && l.hoursFrom === "timesheet" && (ts.pendingH > 0 || ts.openDays > 0 || ts.overtimeUnpaidH > 0) && <div className="mt-0.5 text-[10px] font-semibold text-[#8a5a09]">{[ts.pendingH > 0 ? t("p8wf.prTsPending", { h: ts.pendingH }) : "", ts.openDays > 0 ? pickPlural(t, locale, "p8wf.prTsOpen", ts.openDays) : "", ts.overtimeUnpaidH > 0 ? t("p8wf.prTsOt", { h: ts.overtimeUnpaidH }) : ""].filter(Boolean).join(" · ")}</div>}
                  </td>
                  <td className="px-3 py-2 text-end tabular-nums text-[var(--ink-2)]">{l.basis === "year" ? <span className="text-[var(--ink-3)]">{t("p8wf.prBasisSalary")}</span> : <div className="flex items-center justify-end gap-1.5">{adjOf(e.id)?.hours != null && <span className="rounded bg-[#fdf3e0] px-1 py-0.5 text-[9.5px] font-bold text-[#8a5a09]" title={t("p8wf.prManualHours")}>{t("p8wf.prManual")}</span>}<span>{t("p8wf.hrsUnit", { n: l.hoursM })}</span><button type="button" onClick={() => setSource(e.id, empSource(e) === "timesheet" ? "contracted" : "timesheet")} title={t("p8wf.prSwitchTip")} className={`rounded px-1 py-0.5 text-[9.5px] font-bold ${empSource(e) === "timesheet" ? "bg-[#e7edfb] text-[#1d3a8f]" : "bg-[#eef1f6] text-[#64748b]"}`}>{empSource(e) === "timesheet" ? t("p8wf.prTsSwitch") : t("p8wf.prContractSwitch")}</button></div>}</td>
                  <td className="px-3 py-2 text-end tabular-nums">{gbp(l.grossM)}</td>
                  <td className="px-3 py-2 text-end tabular-nums text-[#c0392b]">{gbp(l.payeM)}{man(l.manual.paye)}</td>
                  <td className="px-3 py-2 text-end tabular-nums text-[#c0392b]">{gbp(l.eeNiM)}{man(l.manual.eeNi)}</td>
                  <td className="px-3 py-2 text-end tabular-nums text-[#c0392b]">{gbp(l.eePenM)}{man(l.manual.eePen)}</td>
                  <td className="px-3 py-2 text-end font-extrabold tabular-nums text-[#0f7a43]">{gbp(l.netM)}</td>
                  <td className="px-3 py-2 text-end tabular-nums text-[var(--ink-3)]">{gbp(l.grossM + l.erNiM + l.erPenM)}</td>
                  <td className="px-3 py-2 text-end"><button type="button" onClick={() => setAdjEmp(e)} className="rounded-lg border border-[var(--line)] px-2.5 py-1 text-[11.5px] font-bold text-[#1d3a8f] hover:border-[#1d3a8f]">{t("p8wf.prEditBtn")}</button></td>
                </tr>
              ); })}
              {lines.length === 0 && <tr><td colSpan={9} className="px-3 py-6 text-center text-[12.5px] text-[var(--ink-3)]">{loaded ? t("p8wf.prNoEmployeesRun") : t("dashboard.loading")}</td></tr>}
              <tr className="border-t-2 border-[var(--line)] bg-[var(--panel)] font-extrabold"><td className="px-3 py-2.5">{t("p8wf.prTotals")}</td><td className="px-3 py-2.5 text-end tabular-nums text-[var(--ink-3)]">{t("p8wf.hrsUnit", { n: lines.filter((l) => l.basis === "hour").reduce((a, l) => a + l.hoursM, 0).toFixed(1) })}</td><td className="px-3 py-2.5 text-end tabular-nums">{gbp(totalGross)}</td><td className="px-3 py-2.5 text-end tabular-nums">{gbp(totalPaye)}</td><td className="px-3 py-2.5 text-end tabular-nums">{gbp(lines.reduce((a, l) => a + l.eeNiM, 0))}</td><td className="px-3 py-2.5 text-end tabular-nums">{gbp(lines.reduce((a, l) => a + l.eePenM, 0))}</td><td className="px-3 py-2.5 text-end tabular-nums text-[#0f7a43]">{gbp(totalNet)}</td><td className="px-3 py-2.5 text-end tabular-nums">{gbp(totalErCost)}</td><td></td></tr></tbody>
            </table>
          </div>
        </Card>
      )}

      {tab === "payslips" && (
        <Card className="p-4">
          {runs.length === 0 ? <div className="p-6 text-center text-[13px] text-[var(--ink-3)]"><Rich text={t("p8wf.prNoRunsYet")} /></div> : (
            <div className="space-y-4">{runs.map((r) => (
              <div key={r.id} data-ui="card" data-testid="pay-run">
                <div className="mb-1.5 flex flex-wrap items-center gap-2"><span className="text-[13.5px] font-extrabold text-[var(--ink)]">{r.period}</span>{!demo && (r.status === "approved" ? chip(t("p8wf.prChipApproved"), "bg-[#e6f4ea] text-[#0f7a43]") : chip(t("p8wf.prChipDraft"), "bg-[#fdf3e0] text-[#8a5a09]"))}<span className="text-[11.5px] text-[var(--ink-3)]">{t("p8wf.prPaidNet", { date: new Date(`${r.paidOn}T12:00:00`).toLocaleDateString(dl(), { day: "numeric", month: "short", year: "numeric" }), net: gbp0(r.lines.reduce((a, l) => a + l.netM, 0)) })}</span>
                  {!demo && r.status === "approved" && acctBtn(r)}
                  {!demo && (r.status !== "approved"
                    ? <button type="button" onClick={() => approveRun(r)} className="ms-auto rounded-full border border-[var(--line)] px-2.5 py-0.5 text-[11px] font-bold text-[#b9770e] hover:border-[#b9770e]">{t("p8wf.prApproveRun")}</button>
                    : (r.publishedAt
                      ? <span className="ms-auto flex items-center gap-2"><span className="rounded-full bg-[#e6f4ea] px-2 py-0.5 text-[10px] font-bold text-[#0f7a43]">{t("p8wf.prPublishedToStaff")}</span><button type="button" onClick={() => publishRun(r, false)} className="text-[11px] font-bold text-[var(--ink-3)] hover:text-[#c0392b]">{t("p8wf.prUnpublish")}</button></span>
                      : <button type="button" onClick={() => publishRun(r, true)} className="ms-auto rounded-full border border-[var(--line)] px-2.5 py-0.5 text-[11px] font-bold text-[#1d3a8f] hover:border-[#1d3a8f]">{t("p8wf.prPublishToStaff")}</button>))}
                </div>
                <div className="grid gap-1.5 sm:grid-cols-2">{r.lines.map((l) => (
                  <button key={l.id} type="button" onClick={() => showPayslip(l, r.period, r.paidOn)} className="flex items-center gap-2 rounded-lg border border-[var(--line)] px-3 py-2 text-start hover:border-[#1d3a8f]"><span className="text-[12.5px] font-bold text-[var(--ink)]">{l.name}</span><span className="text-[11px] text-[var(--ink-3)]">{l.role}</span><span className="ms-auto text-[12px] font-extrabold tabular-nums text-[#0f7a43]">{gbp(l.netM)}</span><span className="text-[11px] font-bold text-[#1d3a8f]">{t("p8wf.prPayslipBtn")}</span></button>
                ))}</div>
              </div>
            ))}</div>
          )}
        </Card>
      )}

      {tab === "integrations" && !demo && <AccountingIntegrations />}
      {tab === "integrations" && demo && (
        <Card className="p-4">
          <div className="mb-3 text-[12px] text-[var(--ink-3)]">{t("p8wf.prIntroDemo")}</div>
          <div className="grid gap-2.5 sm:grid-cols-3">
            {INTEGRATIONS.map((i) => { const on = !!conn[i.id]; return (
              <div key={i.id} className="rounded-2xl border border-[var(--line)] p-4">
                <div className="mb-1 flex items-center gap-2"><span className="text-[22px]">{i.icon}</span><span className="text-[14px] font-extrabold text-[var(--ink)]">{i.name}</span>{on && <span className="ms-auto rounded-full bg-[#e6f4ea] px-2 py-0.5 text-[10px] font-bold text-[#0f7a43]">{t("p8wf.prConnected")}</span>}</div>
                <div className="mb-3 text-[11.5px] leading-relaxed text-[var(--ink-3)]">{t(i.blurb)}</div>
                {on ? <div className="flex flex-wrap gap-2"><Button onClick={() => flash(t("p8wf.prPostedDemo", { month: monthLabel(new Date()), name: i.name }))}>{t("p8wf.prPostJournal")}</Button><button type="button" onClick={() => saveConn({ ...conn, [i.id]: false })} className="text-[11.5px] font-bold text-[var(--ink-3)] hover:text-[#c0392b]">{t("p8wf.prDisconnect")}</button></div> : <Button variant="primary" onClick={() => { saveConn({ ...conn, [i.id]: true }); flash(t("p8wf.prConnectedDemo", { name: i.name })); }}>{t("p8wf.prConnectName", { name: i.name })}</Button>}
              </div>
            ); })}
          </div>
          <p className="mt-3 text-[11px] text-[var(--ink-3)]">{(() => { const [a, b] = t("p8wf.prOrExport", { link: "\u0000" }).split("\u0000"); return <>{a}<button type="button" onClick={exportCsv} className="font-bold text-[#1d3a8f] underline">{t("p8wf.prExportCsvLink")}</button>{b}</>; })()}</p>
        </Card>
      )}

      {edit && <EmpEditor emp={edit.emp} isNew={edit.isNew} canRemove={!demo && !edit.isNew && (edit.emp.source === "manual" || !teamIds.has(edit.emp.id))} takenIds={new Set(emps.map((x) => x.id))}
        onSave={(e) => { saveEmps(edit.isNew ? [...emps, e] : emps.map((x) => (x.id === e.id ? e : x))); setEdit(null); }}
        onRemove={() => { if (window.confirm(t("p8wf.prConfirmRemove", { name: edit.emp.name }))) { saveEmps(emps.filter((x) => x.id !== edit.emp.id)); setEdit(null); } }}
        onClose={() => setEdit(null)} />}
      {adjEmp && <RunAdjust emp={adjEmp} period={periodD} freq={freq} value={adjOf(adjEmp.id)} preview={(a) => lineFor(adjEmp, a)} ts={empSource(adjEmp) === "timesheet" ? tsSum[adjEmp.id] ?? tsFor(adjEmp) : undefined} tsRows={demo ? [] : tsRowsFor(adjEmp)} hoursSource={empSource(adjEmp)} onTimesheet={setTimesheet} onSave={(a) => { setEmpAdjust(adjEmp.id, a); setAdjEmp(null); }} onClose={() => setAdjEmp(null)} />}
      {toast && <div className="fixed bottom-5 left-1/2 z-[150] max-w-[92vw] -translate-x-1/2 rounded-2xl bg-[#111634] px-4 py-2.5 text-center text-[12.5px] font-bold text-white shadow-xl">{toast}</div>}
      <p className="mt-4 text-[11px] text-[var(--ink-3)]"><Rich text={t("p8wf.prFooterNote")} /></p>
    </div>
  );
}

function EmpEditor({ emp, isNew, canRemove, takenIds, onSave, onRemove, onClose }: { emp: Emp; isNew?: boolean; canRemove?: boolean; takenIds: Set<string>; onSave: (e: Emp) => void; onRemove: () => void; onClose: () => void }) {
  const { t } = useI18n();
  const [e, setE] = useState<Emp>(emp);
  const [err, setErr] = useState<string | null>(null);
  const save = () => {
    if (e.startDate && e.leaveDate && e.leaveDate < e.startDate) { setErr(t("p8wf.prErrLeaveBefore")); return; }
    if (isNew) {
      const name = e.name.trim(); const id = staffSlug(name);
      if (!name) { setErr(t("p8wf.prErrName")); return; }
      if (takenIds.has(id)) { setErr(t("p8wf.prErrTaken", { name })); return; }
      onSave({ ...e, name, id, source: "manual" }); return;
    }
    onSave(e);
  };
  return (
    <div className="fixed inset-0 z-[140] flex items-start justify-center overflow-y-auto bg-black/45 p-4 pt-[8vh]" onClick={onClose} style={LIGHT_PALETTE}>
      <div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl" onClick={(ev) => ev.stopPropagation()}>
        <div className="mb-3 flex items-center gap-2"><h3 className="text-[15px] font-extrabold text-[var(--ink)]">{isNew ? t("p8wf.prAddEmployeeH") : e.name}</h3><button type="button" onClick={onClose} className="ms-auto text-[18px] text-[var(--ink-3)]">×</button></div>
        <div className="grid gap-2.5">
          {isNew && <>
            <div className="rounded-lg bg-[var(--panel)] px-3 py-2 text-[11.5px] text-[var(--ink-3)]"><Rich text={t("p8wf.prNewEmpNote")} /></div>
            <div className="grid grid-cols-2 gap-2">
              <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prFullName")}</span><Input value={e.name} onChange={(ev) => { setE({ ...e, name: ev.target.value }); setErr(null); }} className="w-full" /></label>
              <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prRole")}</span><Input value={e.role} onChange={(ev) => setE({ ...e, role: ev.target.value })} className="w-full" /></label>
            </div>
          </>}
          <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prPayBasis")}</span><Select value={e.basis} onChange={(ev) => setE({ ...e, basis: ev.target.value as "hour" | "year" })} className="w-full"><option value="hour">{t("p8wf.prOptHourly")}</option><option value="year">{t("p8wf.prOptSalary")}</option></Select></label>
          <div className="grid grid-cols-2 gap-2">
            <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{e.basis === "year" ? t("p8wf.prSalaryYr") : t("p8wf.prRateHr")}</span><Input inputMode="decimal" value={String(e.rate)} onChange={(ev) => setE({ ...e, rate: parseFloat(ev.target.value) || 0 })} className="w-full" /></label>
            <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prHoursWeek")}</span><Input inputMode="decimal" value={String(e.hpw)} onChange={(ev) => setE({ ...e, hpw: parseFloat(ev.target.value) || 0 })} disabled={e.basis === "year"} className="w-full" /></label>
          </div>
          {e.basis === "hour" && <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prWeeksYear")} <span className="normal-case text-[var(--ink-3)]">{t("p8wf.prWeeksHint")}</span></span><Input inputMode="decimal" value={String(e.weeks)} onChange={(ev) => setE({ ...e, weeks: parseFloat(ev.target.value) || 52 })} className="w-full" /></label>}
          {e.basis === "hour" && <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prPaidFromLbl")} <span className="normal-case text-[var(--ink-3)]">{t("p8wf.prPaidFromHint")}</span></span><Select value={sourceOf(e)} onChange={(ev) => setE({ ...e, paidFrom: ev.target.value as "contracted" | "timesheet" })} className="w-full"><option value="contracted">{t("p8wf.prOptContracted")}</option><option value="timesheet">{t("p8wf.prOptTimesheet")}</option></Select><span className="mt-1 block text-[10.5px] text-[var(--ink-3)]">{t("p8wf.prHoursValuesLeave")}</span></label>}
          <div className="grid grid-cols-2 gap-2">
            <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prTaxCode")}</span><Input value={e.taxCode} onChange={(ev) => setE({ ...e, taxCode: ev.target.value })} className="w-full" /></label>
            <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prNiCat")}</span><Select value={e.niCat} onChange={(ev) => setE({ ...e, niCat: ev.target.value })} className="w-full">{["A", "B", "C", "H", "J", "M", "V", "Z"].map((c) => <option key={c} value={c}>{c}</option>)}</Select></label>
          </div>
          <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prStudentLoan")} <span className="normal-case text-[var(--ink-3)]">{t("p8wf.prStudentHint")}</span></span><Select value={e.studentLoanPlan || "none"} onChange={(ev) => setE({ ...e, studentLoanPlan: ev.target.value as Emp["studentLoanPlan"] })} className="w-full"><option value="none">{t("p8wf.prNone")}</option><option value="plan1">{t("p8wf.prPlanN", { n: 1 })}</option><option value="plan2">{t("p8wf.prPlanN", { n: 2 })}</option><option value="plan4">{t("p8wf.prPlanN", { n: 4 })}</option><option value="plan5">{t("p8wf.prPlanN", { n: 5 })}</option><option value="postgrad">{t("p8wf.prPostgrad")}</option></Select></label>
          <div className="grid grid-cols-2 gap-2">
            <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prStartDate")}</span><Input type="date" data-testid="emp-start" value={e.startDate || ""} onChange={(ev) => { setE({ ...e, startDate: ev.target.value || undefined }); setErr(null); }} className="w-full" /></label>
            <label className="block"><span className="mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]">{t("p8wf.prLeavingDate")}</span><Input type="date" data-testid="emp-leave" value={e.leaveDate || ""} onChange={(ev) => { setE({ ...e, leaveDate: ev.target.value || null }); setErr(null); }} className="w-full" /></label>
            <div className="col-span-2 -mt-1 text-[10.5px] text-[var(--ink-3)]">{t("p8wf.prDatesHint")}</div>
          </div>
          <label className="flex cursor-pointer items-center gap-2 rounded-lg bg-[var(--panel)] px-3 py-2"><input type="checkbox" checked={e.pension} onChange={(ev) => setE({ ...e, pension: ev.target.checked })} className="h-4 w-4 accent-[#1d3a8f]" /><span className="text-[12.5px] font-bold text-[var(--ink)]">{t("p8wf.prEnrolledPension")}</span></label>
          <div className="rounded-lg bg-[#eef4fd] px-3 py-2 text-[12px] font-semibold text-[#1d3a8f]">{e.basis === "hour" && sourceOf(e) === "timesheet" ? t("p8wf.prPaidForTs", { rate: (e.rate || 0).toFixed(2) }) : t("p8wf.prEstGross", { amt: gbp0(grossMonthly(e)) })}</div>
          {err && <div className="rounded-lg bg-[#fdecec] px-3 py-2 text-[12px] font-semibold text-[#c0392b]">{err}</div>}
        </div>
        <div className="mt-3 flex items-center gap-2">{canRemove && <button type="button" onClick={onRemove} className="text-[12px] font-bold text-[var(--ink-3)] hover:text-[#c0392b]">{t("p8wf.prRemoveFromPayroll")}</button>}<div className="ms-auto flex gap-2"><Button onClick={onClose}>{t("common.cancel")}</Button><Button variant="primary" onClick={save}>{isNew ? t("p8wf.prAddBtn") : t("common.save")}</Button></div></div>
      </div>
    </div>
  );
}

// Per-run adjustments for one employee: hours / tax code / NI / additions /
// deductions / manual PAYE-NI-pension overrides. Everything editable; net always
// recalculates. Saves to the period's adjustment store, not the master record.
type TsRow = { rec: ClockRec; payH: number; workedH: number; overtimeUnpaidH: number };
function RunAdjust({ emp, period, freq, value, preview, ts, tsRows, hoursSource, onTimesheet, onSave, onClose }: { emp: Emp; period: string; freq: Freq; value?: Adjust; preview: (a: Adjust) => Line; ts?: TimesheetSum; tsRows: TsRow[]; hoursSource: "contracted" | "timesheet"; onTimesheet: (rec: ClockRec, patch: Record<string, unknown>, msg: string) => void; onSave: (a: Adjust | null) => void; onClose: () => void }) {
  const { t, locale } = useI18n();
  const [d, setD] = useState<Adjust>(() => ({ hours: value?.hours ?? null, taxCode: value?.taxCode ?? "", niCat: value?.niCat ?? "", additions: value?.additions ? value.additions.map((x) => ({ ...x })) : [], deductions: value?.deductions ? value.deductions.map((x) => ({ ...x })) : [], override: { paye: value?.override?.paye ?? null, eeNi: value?.override?.eeNi ?? null, eePen: value?.override?.eePen ?? null } }));
  const [showManual, setShowManual] = useState(!!(value?.override && (value.override.paye != null || value.override.eeNi != null || value.override.eePen != null)));
  const contracted = emp.basis === "hour" ? r2(emp.hpw * (emp.weeks || 52) / PPY[freq]) : 0;
  const sourceHours = hoursSource === "timesheet" ? (ts?.approvedH ?? 0) : contracted;
  const num = (s: string) => { const n = parseFloat(s); return Number.isNaN(n) ? 0 : n; };

  // the same calculation as the pay-run row (timesheets, leave, rolled-up) with this draft applied
  const pl = preview({ hours: d.hours, taxCode: d.taxCode || undefined, niCat: d.niCat || undefined, additions: d.additions, deductions: d.deductions, override: d.override });

  const setItems = (key: "additions" | "deductions", items: AdjItem[]) => setD({ ...d, [key]: items });
  const addItem = (key: "additions" | "deductions", label = "") => setItems(key, [...(d[key] || []), { id: crypto.randomUUID(), label, amount: 0 }]);
  const editItem = (key: "additions" | "deductions", id: string, patch: Partial<AdjItem>) => setItems(key, (d[key] || []).map((x) => (x.id === id ? { ...x, ...patch } : x)));
  const delItem = (key: "additions" | "deductions", id: string) => setItems(key, (d[key] || []).filter((x) => x.id !== id));

  const save = () => {
    const additions = (d.additions || []).filter((x) => (x.label || "").trim() || x.amount);
    const deductions = (d.deductions || []).filter((x) => (x.label || "").trim() || x.amount);
    const ov = { paye: d.override?.paye ?? undefined, eeNi: d.override?.eeNi ?? undefined, eePen: d.override?.eePen ?? undefined };
    const clean: Adjust = { hours: d.hours != null ? d.hours : undefined, taxCode: (d.taxCode || "").trim() || undefined, niCat: d.niCat || undefined, additions, deductions, override: ov };
    const empty = clean.hours == null && !clean.taxCode && !clean.niCat && !additions.length && !deductions.length && ov.paye == null && ov.eeNi == null && ov.eePen == null;
    onSave(empty ? null : clean);
  };

  const lbl = "mb-1 block text-[11px] font-extrabold uppercase text-[var(--ink-3)]";
  const itemRows = (key: "additions" | "deductions", title: string, presets: string[], tone: string) => (
    <div>
      <div className="mb-1 flex items-center gap-2"><span className={lbl + " mb-0"}>{title}</span><button type="button" onClick={() => addItem(key)} className="text-[11px] font-bold text-[#1d3a8f] hover:underline">{t("p8wf.prAddSmall")}</button></div>
      {(d[key] || []).map((x) => (
        <div key={x.id} className="mb-1.5 flex items-center gap-1.5">
          <Input value={x.label} placeholder={t("p8wf.prLabelPh")} onChange={(ev) => editItem(key, x.id, { label: ev.target.value })} className="flex-1" list={`preset-${key}`} />
          <span className="text-[var(--ink-3)]">£</span>
          <Input inputMode="decimal" value={x.amount ? String(x.amount) : ""} placeholder="0.00" onChange={(ev) => editItem(key, x.id, { amount: num(ev.target.value) })} className="w-24" />
          <button type="button" onClick={() => delItem(key, x.id)} className="px-1 text-[16px] text-[var(--ink-3)] hover:text-[#c0392b]">×</button>
        </div>
      ))}
      <datalist id={`preset-${key}`}>{presets.map((p) => <option key={p} value={p} />)}</datalist>
      <div className="flex flex-wrap gap-1">{presets.map((p) => <button key={p} type="button" onClick={() => addItem(key, p)} className={`rounded-full border px-2 py-0.5 text-[10.5px] font-semibold ${tone}`}>+ {p}</button>)}</div>
    </div>
  );

  return (
    <div className="fixed inset-0 z-[140] flex items-start justify-center overflow-y-auto bg-black/45 p-4 pt-[6vh]" onClick={onClose} style={LIGHT_PALETTE}>
      <div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl" onClick={(ev) => ev.stopPropagation()}>
        <div className="mb-1 flex items-center gap-2"><h3 className="text-[15px] font-extrabold text-[var(--ink)]">{emp.name}</h3><span className="text-[12px] text-[var(--ink-3)]">{t("p8wf.prPayRunSuffix", { period })}</span><button type="button" onClick={onClose} className="ms-auto text-[18px] text-[var(--ink-3)]">×</button></div>
        <div className="mb-3 text-[11px] text-[var(--ink-3)]">{t("p8wf.prAdjNote")}</div>
        <div className="grid gap-3">
          {emp.basis === "hour" ? (
            <label className="block"><span className={lbl}>{t("p8wf.prHoursPeriod")}</span>
              <Input inputMode="decimal" value={d.hours != null ? String(d.hours) : ""} placeholder={t("p8wf.prHoursPh", { n: sourceHours, src: t(hoursSource === "timesheet" ? "p8wf.prSrcApprovedTsLc" : "p8wf.prSrcContractLc") })} onChange={(ev) => setD({ ...d, hours: ev.target.value.trim() === "" ? null : num(ev.target.value) })} className="w-full" />
              <span className="mt-1 block text-[10.5px] text-[var(--ink-3)]"><Rich text={t("p8wf.prHoursHelp", { ts: ts ? t("p8wf.hrsUnit", { n: ts.approvedH }) : "—", pend: ts && ts.pendingH > 0 ? t("p8wf.prPendAwait", { h: t("p8wf.hrsUnit", { n: ts.pendingH }) }) : "", c: t("p8wf.hrsUnit", { n: contracted }), src: t(hoursSource === "timesheet" ? "p8wf.prSrcApprovedTsLc" : "p8wf.prSrcContractLc"), less: hoursSource === "contracted" && pl.leave?.unpaidDays ? t("p8wf.prLessUnpaid") : "" })} /></span>
            </label>
          ) : <div className="rounded-lg bg-[var(--panel)] px-3 py-2 text-[12px] text-[var(--ink-3)]">{t("p8wf.prSalariedBase", { amt: gbp0(emp.rate / PPY[freq]), freq: freqName(FREQ_LABEL[freq]).toLocaleLowerCase(dl()) })}</div>}
          {tsRows.length > 0 && (
            <div>
              <span className={lbl}>{t("p8wf.prTsThisPeriod")}</span>
              <div className="max-h-44 overflow-y-auto rounded-lg border border-[var(--line)]">
                {tsRows.map(({ rec, payH, workedH, overtimeUnpaidH }) => (
                  <div key={rec.day} className="flex flex-wrap items-center gap-1.5 border-t border-[var(--line-2,#eef2f8)] px-2.5 py-1.5 text-[11.5px] first:border-t-0">
                    <span className="w-[74px] font-bold text-[var(--ink)]">{new Date(`${rec.day}T12:00:00`).toLocaleDateString(dl(), { weekday: "short", day: "numeric", month: "short" })}</span>
                    <span className="text-[var(--ink-3)]">{hhmm(rec.clockInAt)}–{rec.clockOutAt ? hhmm(rec.clockOutAt) : "…"}{rec.breakMs ? t("p8wf.prBreakMin", { n: Math.round(rec.breakMs / 60000) }) : ""} · {t("p8wf.prWorkedH", { h: t("p8wf.hrsUnit", { n: workedH }) })}</span>
                    <span className="font-bold tabular-nums text-[var(--ink)]">{t("p8wf.prPayHrs", { h: t("p8wf.hrsUnit", { n: payH }) })}</span>
                    <span className="ms-auto flex items-center gap-1.5">
                      {!rec.clockOutAt ? <span className="rounded-full bg-[#fdf3e0] px-1.5 py-0.5 text-[9.5px] font-bold text-[#8a5a09]">{t("p8wf.prNotClockedOut")}</span>
                        : rec.approved ? <span className="rounded-full bg-[#e6f4ea] px-1.5 py-0.5 text-[9.5px] font-bold text-[#0f7a43]">{t("p8wf.tsApprovedBadge")}</span>
                        : <button type="button" onClick={() => onTimesheet(rec, { approved: true }, t("p8wf.prTsApprovedMsg", { day: rec.day, h: t("p8wf.hrsUnit", { n: payH }) }))} className="rounded-full border border-[var(--line)] px-2 py-0.5 text-[10.5px] font-bold text-[#1d3a8f] hover:border-[#1d3a8f]">{t("p8wf.tsApproveBtn")}</button>}
                      {overtimeUnpaidH > 0 && <button type="button" title={t("p8wf.prOtTip")} onClick={() => onTimesheet(rec, { payBasis: "actual", editNote: "Overtime approved from Payroll" }, t("p8wf.prOtPayMsg", { day: rec.day, h: t("p8wf.hrsUnit", { n: overtimeUnpaidH }) }))} className="rounded-full border border-[#bfe3cd] px-2 py-0.5 text-[10.5px] font-bold text-[#0f7a43] hover:bg-[#eafaf0]">{t("p8wf.prPayOt", { h: t("p8wf.hrsUnit", { n: overtimeUnpaidH }) })}</button>}
                    </span>
                  </div>
                ))}
              </div>
              <span className="mt-1 block text-[10.5px] text-[var(--ink-3)]">{t("p8wf.prTsPolicyNote")}</span>
            </div>
          )}
          {pl.leave && (
            <div className="rounded-lg bg-[#eef4fd] px-3 py-2 text-[11.5px] text-[#1d3a8f]">
              <b>{t("p8wf.prLeaveThisPeriod")}</b> {leaveLabel(pl.leave)}.
              {pl.leave.unpaidDays > 0 && <>{t("p8wf.prAdjUnpaid", { n: pl.leave.unpaidDays, rest: pl.unpaidLeaveM ? t("p8wf.prAdjUnpaidAmt", { amt: gbp(pl.unpaidLeaveM) }) : hoursSource === "timesheet" || d.hours != null ? t("p8wf.prAdjUnpaidNotClocked") : "" })}</>}
              {pl.leave.paidDays > 0 && <>{t("p8wf.prAdjPaid", { n: pl.leave.paidDays, how: t(pl.hoursFrom === "timesheet" ? "p8wf.prAddedNormal" : "p8wf.prInContracted") })}</>}
              {pl.leave.sickDays > 0 && (pl.sickPay === "ssp"
                ? <b className="block text-[#b45309]">{t("p8wf.prAdjSickSsp", { n: pl.leave.sickDays, how: pl.sickLeaveM ? t("p8wf.prAdjSickDed", { amt: gbp(pl.sickLeaveM) }) : t("p8wf.prAdjSickNotPaid") })}</b>
                : <>{t("p8wf.prAdjSickFull", { n: pl.leave.sickDays, how: t(pl.hoursFrom === "timesheet" ? "p8wf.prAddedNormalSp" : "p8wf.prAlreadyInSp") })}</>)}
              {pl.leave.statutoryDays > 0 && <b className="block text-[#b45309]">{t("p8wf.prAdjStat")}</b>}
            </div>
          )}
          <div className="grid grid-cols-2 gap-2">
            <label className="block"><span className={lbl}>{t("p8wf.prTaxCodeRun")}</span><Input value={d.taxCode} placeholder={emp.taxCode} onChange={(ev) => setD({ ...d, taxCode: ev.target.value })} className="w-full" /></label>
            <label className="block"><span className={lbl}>{t("p8wf.prNiCat")}</span><Select value={d.niCat || ""} onChange={(ev) => setD({ ...d, niCat: ev.target.value })} className="w-full"><option value="">{t("p8wf.prDefaultOpt", { cat: emp.niCat })}</option>{["A", "B", "C", "H", "J", "M", "V", "Z"].map((c) => <option key={c} value={c}>{c}</option>)}</Select></label>
          </div>
          {itemRows("additions", t("p8wf.prAdditionsTitle"), [t("p8wf.prPrOvertime"), t("p8wf.prPrBonus"), t("p8wf.prPrHolidayPay"), t("p8wf.prPrBackpay")], "border-[#bfe3cd] text-[#0f7a43] hover:bg-[#eafaf0]")}
          {itemRows("deductions", t("p8wf.prDeductionsTitle"), [t("p8wf.prPrAdvance"), t("p8wf.prPrSacrifice"), t("p8wf.prPrOther")], "border-[#f0cfcf] text-[#c0392b] hover:bg-[#fdeeee]")}
          <div>
            <button type="button" onClick={() => setShowManual((s) => !s)} className="text-[11.5px] font-bold text-[#1d3a8f] hover:underline">{showManual ? "▾" : (isRTL(locale) ? "◂" : "▸")} {t("p8wf.prManualToggle")}</button>
            {showManual && (
              <div className="mt-2 grid grid-cols-3 gap-2 rounded-lg bg-[var(--panel)] p-2.5">
                {([["paye", t("p8wf.prPaye"), pl.payeM], ["eeNi", t("p8wf.prEeNi"), pl.eeNiM], ["eePen", t("p8wf.prPension"), pl.eePenM]] as const).map(([k, label, auto]) => (
                  <label key={k} className="block"><span className={lbl}>{label}</span><Input inputMode="decimal" value={d.override?.[k] != null ? String(d.override?.[k]) : ""} placeholder={t("p8wf.prAutoPh", { n: auto.toFixed(2) })} onChange={(ev) => setD({ ...d, override: { ...d.override, [k]: ev.target.value.trim() === "" ? null : num(ev.target.value) } })} className="w-full" /></label>
                ))}
                <span className="col-span-3 text-[10.5px] text-[var(--ink-3)]">{t("p8wf.prBlankAuto")}</span>
              </div>
            )}
          </div>
          {/* live preview */}
          <div className="rounded-xl border border-[var(--line)] bg-[#f7f9fd] p-3 text-[12px]">
            <div className="mb-1 text-[10px] font-extrabold uppercase tracking-wide text-[var(--ink-3)]">{t("p8wf.prThisRun")}</div>
            <div className="grid grid-cols-2 gap-x-4 gap-y-0.5">
              <span className="text-[var(--ink-3)]">{t("p8wf.prGross")}</span><span className="text-end font-bold tabular-nums">{gbp(pl.grossM)}</span>
              <span className="text-[var(--ink-3)]">{t("p8wf.prPaye")}</span><span className="text-end tabular-nums text-[#c0392b]">−{gbp(pl.payeM)}</span>
              <span className="text-[var(--ink-3)]">{t("p8wf.prEeNi")}</span><span className="text-end tabular-nums text-[#c0392b]">−{gbp(pl.eeNiM)}</span>
              <span className="text-[var(--ink-3)]">{t("p8wf.prPension")}</span><span className="text-end tabular-nums text-[#c0392b]">−{gbp(pl.eePenM)}</span>
              {pl.dedM > 0 && <><span className="text-[var(--ink-3)]">{t("p8wf.prOtherDeductions")}</span><span className="text-end tabular-nums text-[#c0392b]">−{gbp(pl.dedM)}</span></>}
              <span className="font-extrabold text-[var(--ink)]">{t("p8wf.prNetPay")}</span><span className="text-end font-extrabold tabular-nums text-[#0f7a43]">{gbp(pl.netM)}</span>
            </div>
          </div>
        </div>
        <div className="mt-3 flex items-center gap-2"><button type="button" onClick={() => onSave(null)} className="text-[12px] font-bold text-[var(--ink-3)] hover:text-[#c0392b]">{t("p8wf.prResetDefault")}</button><div className="ms-auto flex gap-2"><Button onClick={onClose}>{t("common.cancel")}</Button><Button variant="primary" onClick={save}>{t("p8wf.prSaveAdjustments")}</Button></div></div>
      </div>
    </div>
  );
}
