// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/angleExplorer.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* angleExplorer — drag rays / corners: measure with a live protractor; angles on a line, at a point, in a triangle and a quadrilateral */
(function(){
  const CX=180, CY=180, R=128, D=Math.PI/180, COL=["#3b5bdb","#ff5a3c","#137a4a","#8a5a00"];
  const MODES={measure:"Measure",line:"On a line",point:"Round a point",tri:"Triangle",quad:"Quadrilateral"};
  const NOTE={measure:"Drag the blue ray. Watch the reading and the name of the angle.",line:"Angles on a straight line add up to 180°. Drag the ray.",point:"Angles around a point add up to 360°. Drag the rays.",tri:"Drag the corners. The three angles in a triangle always add up to 180°.",quad:"Drag the corners. The four angles in a quadrilateral always add up to 360°."};
  const pol=(a,r,cx=CX,cy=CY)=>[cx+r*Math.cos(a*D),cy-r*Math.sin(a*D)];
  const nm=a=>a===0||a===360?"full turn / zero":a<90?"acute":a===90?"right angle":a<180?"obtuse":a===180?"straight line":a<360?"reflex":"full turn";
  const rnd=(arr,tot)=>{ const r=arr.map(Math.round), d=tot-r.reduce((s,v)=>s+v,0); if(d){ let m=0; arr.forEach((v,i)=>{ if(v>arr[m]) m=i; }); r[m]+=d; } return r; };
  const arc=(a1,a2,r,cx=CX,cy=CY)=>{ const s=pol(a1,r,cx,cy), e=pol(a2,r,cx,cy); return `M${s[0]} ${s[1]}A${r} ${r} 0 ${(a2-a1)%360>180?1:0} 0 ${e[0]} ${e[1]}`; };
  const wedge=(a1,a2,r,c,cx=CX,cy=CY)=>`<path d="M${cx} ${cy}L${pol(a1,r,cx,cy).join(" ")}${arc(a1,a2,r,cx,cy).replace(/^M[^A]*/,"")}Z" fill="${c}" fill-opacity=".2" stroke="${c}" stroke-width="2"/>`;
  const seg=(p,q,e)=>{ const c=(a,b,d)=>(b[0]-a[0])*(d[1]-a[1])-(b[1]-a[1])*(d[0]-a[0]); return c(p,q,e[0])*c(p,q,e[1])<0&&c(e[0],e[1],p)*c(e[0],e[1],q)<0; };
  const simple=v=>{ const n=v.length; for(let i=0;i<n;i++) for(let j=i+2;j<n;j++){ if(i===0&&j===n-1) continue; if(seg(v[i],v[(i+1)%n],[v[j],v[(j+1)%n]])) return false; } return true; };
  WIDGETS.angleExplorer={title:"Explore angles",intro:"Drag a ray or a corner and read the angle. What always stays the same?",
  html(){ return `<div class="explore" id="anw"><div class="row" style="justify-content:center;margin-bottom:8px" id="anm">${Object.keys(MODES).map(k=>`<button class="btn ghost pr fk" data-m="${k}">${MODES[k]}</button>`).join("")}</div>
    <svg id="ans" viewBox="0 0 360 360" role="img" aria-label="Angle explorer" style="touch-action:none;max-width:420px;margin:0 auto;user-select:none"><g id="and"></g></svg>
    <div style="text-align:center;margin:8px 0 2px"><span class="big" id="anbig" style="font-size:40px"></span> <span class="tag" id="antag" style="vertical-align:middle"></span></div>
    <p class="small" id="ansay" style="text-align:center;margin:4px 0 0"></p></div>`; },
  init(){
    const svg=$("#ans"), dyn=$("#and"); let mode="measure", th=50, ln=65, pr=[40,150,255], tri=[[70,270],[290,270],[200,90]], quad=[[70,280],[290,280],[260,100],[110,140]], drag=null, mv=0;
    const ang=(pts)=>{ const n=pts.length; let ar=0; pts.forEach((p,i)=>{ const q=pts[(i+1)%n]; ar+=p[0]*(-q[1])-q[0]*(-p[1]); }); const ccw=ar>0, m=x=>((x%360)+360)%360;
      return pts.map((p,i)=>{ const a=pts[(i+1)%n], b=pts[(i+n-1)%n], ta=Math.atan2(p[1]-a[1],a[0]-p[0])/D, tb=Math.atan2(p[1]-b[1],b[0]-p[0])/D; return ccw?{s:ta,v:m(tb-ta)}:{s:tb,v:m(ta-tb)}; }); };
    const ticks=(full)=>{ let h=`<circle cx="${CX}" cy="${CY}" r="${R+22}" fill="#fff" stroke="#cfd8ff"/>`; for(let a=0;a<360;a+=5){ if(!full&&a>180) break; const big=a%30===0, p1=pol(a,R+(big?8:a%10===0?12:15)), p2=pol(a,R+20); h+=`<line x1="${p1[0]}" y1="${p1[1]}" x2="${p2[0]}" y2="${p2[1]}" stroke="#7b83a3" stroke-width="${big?1.6:1}"/>`; if(a%30===0){ const t=pol(a,R-4); h+=`<text x="${t[0]}" y="${t[1]+3.5}" font-size="9" font-weight="800" fill="#7b83a3" text-anchor="middle">${a}</text>`; } } return h; };
    const handle=(a,c,id,r=R)=>{ const p=pol(a,r); return `<line x1="${CX}" y1="${CY}" x2="${p[0]}" y2="${p[1]}" stroke="${c}" stroke-width="4" stroke-linecap="round"/><circle data-h="${id}" cx="${p[0]}" cy="${p[1]}" r="12" fill="${c}" stroke="#fff" stroke-width="3" style="cursor:grab"/>`; };
    const draw=()=>{
      let h="", big="", tag="", say=NOTE[mode];
      if(mode==="measure"){ h=ticks(true)+wedge(0,th,R-30,COL[0])+`<line x1="${CX}" y1="${CY}" x2="${CX+R}" y2="${CY}" stroke="#141a33" stroke-width="4" stroke-linecap="round"/>`+handle(th,COL[0],"th")+`<circle cx="${CX}" cy="${CY}" r="5" fill="#141a33"/>`; big=th+"°"; tag=nm(th); }
      else if(mode==="line"){ const a=ln,b=180-ln; h=ticks(false)+`<line x1="${CX-R-20}" y1="${CY}" x2="${CX+R+20}" y2="${CY}" stroke="#141a33" stroke-width="4" stroke-linecap="round"/>`+wedge(0,a,R-30,COL[0])+wedge(a,180,R-30,COL[1])+handle(a,"#141a33","ln")+`<text x="${pol(a/2,R*.55)[0]}" y="${pol(a/2,R*.55)[1]+5}" text-anchor="middle" font-size="17" font-weight="900" fill="${COL[0]}">${a}°</text><text x="${pol((a+180)/2,R*.55)[0]}" y="${pol((a+180)/2,R*.55)[1]+5}" text-anchor="middle" font-size="17" font-weight="900" fill="#c2410c">${b}°</text>`; big=`${a}° + ${b}° = 180°`; tag="straight line"; }
      else if(mode==="point"){ const s=[...pr].sort((x,y)=>x-y), gaps=s.map((v,i)=>((s[(i+1)%3]-v)+360)%360||360); const rg=rnd(gaps,360);
        h=ticks(true); s.forEach((v,i)=>{ h+=wedge(v,v+gaps[i],R-30,COL[i]); const m=pol(v+gaps[i]/2,R*.55); h+=`<text x="${m[0]}" y="${m[1]+5}" text-anchor="middle" font-size="17" font-weight="900" fill="${COL[i]}">${rg[i]}°</text>`; }); pr.forEach((v,i)=>h+=handle(v,"#141a33","p"+i)); big=rg.join("° + ")+"° = 360°"; tag="full turn"; }
      else { const pts=mode==="tri"?tri:quad, ag=ang(pts), an=ag.map(q=>q.v), tot=mode==="tri"?180:360, ra=rnd(an,tot), n=pts.length;
        h=`<rect x="6" y="6" width="348" height="348" rx="14" fill="#fff" stroke="#cfd8ff"/><polygon points="${pts.map(p=>p.join(",")).join(" ")}" fill="#3b5bdb" fill-opacity=".14" stroke="#1e3a8a" stroke-width="3" stroke-linejoin="round"/>`;
        pts.forEach((p,i)=>{ const span=an[i], st=ag[i].s;
          h+=`<path d="${arc(st,st+span,26,p[0],p[1])}" fill="none" stroke="${COL[i%4]}" stroke-width="5"/>`; const m=pol(st+span/2,46,p[0],p[1]); h+=`<text x="${m[0]}" y="${m[1]+4}" text-anchor="middle" font-size="14" font-weight="900" fill="${COL[i%4]}" stroke="#fff" stroke-width="3" paint-order="stroke">${ra[i]}°</text>`; });
        pts.forEach((p,i)=>h+=`<circle data-h="v${i}" cx="${p[0]}" cy="${p[1]}" r="11" fill="#1e3a8a" stroke="#fff" stroke-width="3" style="cursor:grab"/>`);
        big=ra.join("° + ")+"° = "+tot+"°"; tag=n+" corners"; }
      dyn.innerHTML=h; $("#anbig").textContent=big; $("#antag").textContent=tag; $("#ansay").textContent=say;
      $("#anbig").style.fontSize=big.length>18?"22px":big.length>10?"30px":"40px"; $("#antag").style.display=mode==="tri"||mode==="quad"?"none":"";
    };
    const pos=e=>{ const q=svg.createSVGPoint(); q.x=e.clientX; q.y=e.clientY; return q.matrixTransform(svg.getScreenCTM().inverse()); };
    const ang0=r=>{ let a=Math.atan2(CY-r.y,r.x-CX)/D; if(a<0) a+=360; return a; };
    const snap=a=>{ for(const m of [0,90,180,270,360]) if(Math.abs(a-m)<2.5) return m%360; return Math.round(a)%360; };
    svg.addEventListener("pointerdown",e=>{ const h=e.target.dataset&&e.target.dataset.h; if(!h) return; drag=h; svg.setPointerCapture(e.pointerId); e.preventDefault(); });
    svg.addEventListener("pointermove",e=>{ if(!drag) return; const r=pos(e);
      if(drag==="th") th=snap(ang0(r)); else if(drag==="ln"){ ln=Math.max(1,Math.min(179,snap(r.y>CY?(r.x>CX?1:179):ang0(r)))); } else if(drag[0]==="p") pr[+drag[1]]=snap(ang0(r));
      else { const i=+drag.slice(1), a=mode==="tri"?tri:quad, np=[Math.max(14,Math.min(346,Math.round(r.x))),Math.max(14,Math.min(346,Math.round(r.y)))], old=a[i]; a[i]=np; if(!simple(a)||a.some((q,j)=>j!==i&&Math.hypot(q[0]-np[0],q[1]-np[1])<24)) a[i]=old; }
      if(++mv===6) addXP(2); draw(); });
    const up=()=>{ drag=null; }; svg.addEventListener("pointerup",up); svg.addEventListener("pointercancel",up);
    $("#anm").querySelectorAll(".pr").forEach(b=>b.onclick=()=>{ mode=b.dataset.m; sel(); draw(); });
    const sel=()=>$("#anm").querySelectorAll(".pr").forEach(b=>b.classList.toggle("sel",b.dataset.m===mode)); sel(); draw();
  }};
})();

  }).call(globalThis);
}
