// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/areaPerimeter.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* areaPerimeter — paint squares on a grid: live area (squares inside) and perimeter (edges round the outside) */
(function(){
  const W=12, H=8, S=28, OX=12, OY=12;
  const PRE={rect:{n:"4 × 3 rectangle",c:[[1,1],[4,3]]},L:{n:"L-shape",c:[[1,1],[1,2],[1,3],[1,4],[2,4],[3,4],[4,4]]}};
  WIDGETS.areaPerimeter={title:"Area and perimeter builder",intro:"Paint squares on the grid. Area counts the squares inside; perimeter counts the edges round the outside. Can you change one and keep the other?",
  html(){ return `<div class="explore" id="apw"><svg id="aps" viewBox="0 0 360 248" role="img" aria-label="Grid to paint squares on" style="touch-action:none;user-select:none"><rect x="4" y="4" width="352" height="240" rx="12" fill="#fff" stroke="#cfd8ff"/><g id="apc"></g><g id="apl"></g></svg>
    <div class="row spread" style="margin:10px 0 4px"><div class="row" style="gap:18px"><span class="small">Area<br><span class="stat" id="apa" style="font-size:28px;color:#3b5bdb">0</span> <span class="small">squares</span></span><span class="small">Perimeter<br><span class="stat" id="apper" style="font-size:28px;color:#c2410c">0</span> <span class="small">edges</span></span></div>
    <div class="row"><button class="btn ghost pr" data-a="rect">4×3</button><button class="btn ghost pr" data-a="L">L-shape</button><button class="btn ghost pr" data-a="clear">Clear</button><button class="btn pr" data-a="chal" style="box-shadow:0 3px 0 #0f2260">Challenge me</button></div></div>
    <p class="small" id="apsay" style="margin:8px 0 0;font-weight:800;color:var(--brand)"></p></div>`; },
  init(){
    const svg=$("#aps"), cells=new Set(), key=(x,y)=>x+","+y; let paint=true, down=false, goal=0, edits=0;
    const has=(x,y)=>cells.has(key(x,y));
    let g=""; for(let x=0;x<=W;x++) g+=`<line x1="${OX+x*S}" y1="${OY}" x2="${OX+x*S}" y2="${OY+H*S}" stroke="#dfe3f1"/>`; for(let y=0;y<=H;y++) g+=`<line x1="${OX}" y1="${OY+y*S}" x2="${OX+W*S}" y2="${OY+y*S}" stroke="#dfe3f1"/>`; $("#apc").innerHTML=g;
    const minP=a=>2*Math.ceil(2*Math.sqrt(a));
    const draw=()=>{
      let h="", edges="", per=0;
      cells.forEach(k=>{ const [x,y]=k.split(",").map(Number); h+=`<rect x="${OX+x*S+1}" y="${OY+y*S+1}" width="${S-2}" height="${S-2}" rx="4" fill="#3b5bdb" fill-opacity=".35"/>`;
        [[0,-1,OX+x*S,OY+y*S,OX+x*S+S,OY+y*S],[0,1,OX+x*S,OY+y*S+S,OX+x*S+S,OY+y*S+S],[-1,0,OX+x*S,OY+y*S,OX+x*S,OY+y*S+S],[1,0,OX+x*S+S,OY+y*S,OX+x*S+S,OY+y*S+S]].forEach(([dx,dy,a,b,c,d])=>{ if(!has(x+dx,y+dy)){ per++; edges+=`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}"/>`; } }); });
      h+=`<g stroke="#ff5a3c" stroke-width="4" stroke-linecap="round">${edges}</g>`;
      $("#apl").innerHTML=h; const a=cells.size; $("#apa").textContent=a; $("#apper").textContent=per;
      let t=a?"":"Tap or drag on the grid to paint squares. Tap a painted square to rub it out.";
      if(a){ const xs=[...cells].map(k=>+k.split(",")[0]), ys=[...cells].map(k=>+k.split(",")[1]), w=Math.max(...xs)-Math.min(...xs)+1, hh=Math.max(...ys)-Math.min(...ys)+1;
        t=w*hh===a?`A rectangle: ${w} × ${hh} = ${a} squares, perimeter 2 × (${w} + ${hh}) = ${per}.`:`Count the orange edges: perimeter ${per}. Squares: ${a}.`; }
      if(goal){ const ok=a===goal; t=`Challenge: fill exactly ${goal} squares with the smallest perimeter you can. `+(ok?(per===minP(goal)?"✓ That is the smallest possible perimeter!":`You have ${goal} squares and perimeter ${per}. Can you get it lower?`):`You have ${a} so far.`); }
      $("#apsay").textContent=t;
    };
    const cell=e=>{ const q=svg.createSVGPoint(); q.x=e.clientX; q.y=e.clientY; const r=q.matrixTransform(svg.getScreenCTM().inverse()); const x=Math.floor((r.x-OX)/S), y=Math.floor((r.y-OY)/S); return x>=0&&y>=0&&x<W&&y<H?[x,y]:null; };
    const apply=c=>{ if(!c) return; const k=key(c[0],c[1]); if(paint!==cells.has(k)){ paint?cells.add(k):cells.delete(k); if(++edits===5) addXP(2); draw(); } };
    svg.addEventListener("pointerdown",e=>{ const c=cell(e); if(!c) return; down=true; paint=!has(c[0],c[1]); svg.setPointerCapture(e.pointerId); e.preventDefault(); apply(c); });
    svg.addEventListener("pointermove",e=>{ if(down) apply(cell(e)); });
    const up=()=>{ down=false; }; svg.addEventListener("pointerup",up); svg.addEventListener("pointercancel",up);
    $("#apw").querySelectorAll(".pr").forEach(b=>b.onclick=()=>{ const a=b.dataset.a; if(a==="clear"){ cells.clear(); goal=0; } else if(a==="chal"){ cells.clear(); goal=6+Math.floor(Math.random()*9); } else { cells.clear(); goal=0; const p=PRE[a]; if(a==="rect"){ for(let x=p.c[0][0];x<=p.c[1][0];x++) for(let y=p.c[0][1];y<=p.c[1][1];y++) cells.add(key(x,y)); } else p.c.forEach(c=>cells.add(key(c[0],c[1]))); } draw(); });
    draw();
  }};
})();

  }).call(globalThis);
}
