// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/arrayBuilder.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* arrayBuilder — drag the corner to build an array; rows x columns, times tables, area, partitioned multiplication */
(function(){
const css=`<style>
#ar .ar-wrap{touch-action:none;user-select:none}
#ar .ar-dot{transition:fill .25s,r .2s}
#ar .chip{border:2px solid var(--line);background:#fff;border-radius:99px;padding:5px 12px;font-weight:800;font-size:13px;color:var(--ink2)}
#ar .chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
#ar .ar-turn{transition:transform .5s cubic-bezier(.3,.8,.3,1);transform-origin:center}
</style>`;
WIDGETS.arrayBuilder={
 title:"Build an array",
 intro:"Drag the corner handle to change the rows and columns. Tap a row to skip count along it. Try turning the array or splitting it.",
 html(){return css+`<div class="explore" id="ar">
 <div class="row spread" style="margin-bottom:8px"><div class="row"><button class="chip on" data-k="dots">Dots</button><button class="chip" data-k="area">Area squares</button></div>
 <div class="row"><button class="btn ghost st" id="ar-turn">↻ Turn</button><span class="small">Split</span><button class="btn ghost st" data-s="-">−</button><button class="btn ghost st" data-s="+">+</button></div></div>
 <svg class="ar-wrap" id="ar-svg" viewBox="0 0 340 270" role="img" aria-label="array"></svg>
 <div class="eq stat" id="ar-eq" style="text-align:center;font-size:18px;margin-top:6px"></div>
 <p class="small" id="ar-say" style="text-align:center;margin:6px 0 0"></p></div>`},
 init(){
  const svg=$("#ar-svg"),NS="http://www.w3.org/2000/svg";const box=$("#ar");
  let R=3,C=5,split=0,kind="dots",turned=false,skip=-1;const MAX=12,W=340,H=270,PAD=14;
  const el=(t,a,p)=>{const e=document.createElementNS(NS,t);for(const k in a)e.setAttribute(k,a[k]);(p||svg).appendChild(e);return e};
  const ROWC=["#3b5bdb","#4c7cf0"];
  function draw(){
   svg.innerHTML="";const r=turned?C:R,c=turned?R:C;
   const cell=Math.min((W-2*PAD-16)/MAX,(H-2*PAD-16)/MAX);const x0=PAD,y0=PAD;
   el("rect",{x:x0,y:y0,width:MAX*cell,height:MAX*cell,rx:8,fill:"#fff",stroke:"#dfe3f1","stroke-width":1.5});
   const sp=Math.min(split,c-1);
   for(let i=0;i<r;i++){for(let j=0;j<c;j++){const gx=x0+j*cell+(j>=c-sp?4:0)*0,cx=x0+(j+.5)*cell,cy=y0+(i+.5)*cell;
     const fill=(skip===i)?"#e8590c":(j>=c-sp?"#e8590c88":ROWC[0]);
     if(kind==="dots")el("circle",{cx,cy,r:cell*.36,fill:skip===i?"#e8590c":(j>=c-sp&&sp>0?"#f08c3a":"#3b5bdb"),class:"ar-dot"});
     else el("rect",{x:x0+j*cell+1,y:y0+i*cell+1,width:cell-2,height:cell-2,rx:3,fill:skip===i?"#e8590c":(j>=c-sp&&sp>0?"#f08c3a":"#4c7cf0"),"fill-opacity":.9})}}
   if(sp>0){const lx=x0+(c-sp)*cell;el("line",{x1:lx,x2:lx,y1:y0-4,y2:y0+r*cell+4,stroke:"#1e3a8a","stroke-width":2.5,"stroke-dasharray":"5 4"})}
   // row skip-count labels
   for(let i=0;i<r;i++){const t=el("text",{x:x0+c*cell+6,y:y0+(i+.5)*cell+4,"font-size":Math.min(11,cell*.5),"font-weight":800,fill:skip===i?"#c2410c":"#7b83a3"});t.textContent=(i+1)*c;t.style.cursor="pointer"}
   // handle
   const hx=x0+c*cell,hy=y0+r*cell;const h=el("g",{style:"cursor:nwse-resize"});el("circle",{cx:hx,cy:hy,r:15,fill:"#ffd43b","fill-opacity":.35},h);el("circle",{cx:hx,cy:hy,r:6,fill:"#ffd43b",stroke:"#1e3a8a","stroke-width":2.5},h);h.dataset.h=1;
   const tot=r*c;
   const eq=$("#ar-eq");eq.innerHTML=sp>0?`${r} × ${c-sp} + ${r} × ${sp} = ${r*(c-sp)} + ${r*sp} = ${tot}`:`${r} × ${c} = ${tot}`;
   $("#ar-say").textContent=skip>=0?`Counting the ${c}s: ${[...Array(skip+1)].map((_,i)=>(i+1)*c).join(", ")}`:`${r} rows of ${c}. Turn it: ${c} rows of ${r} — same total, ${c} × ${r} = ${tot}.`;
   if(kind==="area")$("#ar-say").textContent+=`  Area = ${c} cm × ${r} cm = ${tot} cm².`;
   svg.dataset.rc=r+","+c;
  }
  let dragging=false;
  const pt=e=>{const b=svg.getBoundingClientRect();return{x:(e.clientX-b.left)/b.width*W,y:(e.clientY-b.top)/b.height*H}};
  svg.addEventListener("pointerdown",e=>{const p=pt(e);const cell=Math.min((W-2*PAD-16)/MAX,(H-2*PAD-16)/MAX);
   const r=turned?C:R,c=turned?R:C;const hx=PAD+c*cell,hy=PAD+r*cell;
   if(Math.hypot(p.x-hx,p.y-hy)<26){dragging=true;svg.setPointerCapture(e.pointerId);skip=-1;return}
   const i=Math.floor((p.y-PAD)/cell);if(i>=0&&i<r&&p.x<PAD+c*cell+40){skip=skip===i?-1:i;if(skip>=0)addXP(0);draw()}});
  svg.addEventListener("pointermove",e=>{if(!dragging)return;const p=pt(e);const cell=Math.min((W-2*PAD-16)/MAX,(H-2*PAD-16)/MAX);
   const c=Math.max(1,Math.min(MAX,Math.round((p.x-PAD)/cell))),r=Math.max(1,Math.min(MAX,Math.round((p.y-PAD)/cell)));
   if(turned){if(R!==c||C!==r){R=c;C=r;draw()}}else if(R!==r||C!==c){R=r;C=c;draw()}});
  svg.addEventListener("pointerup",()=>{if(dragging){dragging=false;addXP(1)}});
  $("#ar-turn").onclick=()=>{ [R,C]=[C,R];svg.style.transition="transform .45s";svg.style.transform="rotate(4deg) scale(.96)";setTimeout(()=>{svg.style.transform="";draw()},window.matchMedia("(prefers-reduced-motion: reduce)").matches?0:220);skip=-1};
  box.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>{split=Math.max(0,Math.min(C-1,split+(b.dataset.s==="+"?1:-1)));draw()});
  box.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{kind=b.dataset.k;box.querySelectorAll("[data-k]").forEach(x=>x.classList.toggle("on",x===b));draw()});
  draw();
 }};
})();

  }).call(globalThis);
}
