// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/atomBuilder.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Atom builder: choose protons, neutrons and electrons (elements 1-20). Shows the element, mass number, charge, isotopes/ions and electronic structure (2,8,8,2 filling). */
WIDGETS.atomBuilder = {
  title: "Build an atom",
  intro: "Add protons, neutrons and electrons, or tap an element. What decides which element you have? What makes it an ion or an isotope?",
  html() {
    const c = (k, lab, col) => `<div class="row" style="justify-content:space-between;background:#fff;border:2px solid var(--line);border-radius:12px;padding:4px 10px"><span style="font-weight:800;color:${col}">${lab}</span><span class="row" style="gap:6px"><button class="btn ghost st" data-c="${k}-" aria-label="fewer ${lab}">−</button><b class="stat" id="ab${k}" style="min-width:26px;text-align:center"></b><button class="btn ghost st" data-c="${k}+" aria-label="more ${lab}">+</button></span></div>`;
    return `<div class="explore" id="ab"><div style="display:flex;flex-wrap:wrap;gap:10px;align-items:center;justify-content:center"><svg id="abs" viewBox="0 0 300 300" style="max-width:290px;flex:1 1 230px" role="img" aria-label="An atom with a nucleus and electron shells"></svg>
    <div style="flex:1 1 200px;display:grid;gap:8px">${c("p", "Protons (+)", "#c2255c")}${c("n", "Neutrons (0)", "#4a5275")}${c("e", "Electrons (−)", "#1c7ed6")}
      <div id="abI" style="background:#fff;border:2px solid var(--line);border-radius:12px;padding:8px 12px;font-size:14px"></div></div></div>
    <div class="small" style="margin:8px 0 4px;text-align:center">Or choose an element:</div><div class="row" style="justify-content:center;gap:5px" id="abT"></div>
    <p class="small" id="abSay" style="margin:8px 0 0;text-align:center"></p></div>`;
  },
  init() {
    const svg = $("#abs"), rm = matchMedia("(prefers-reduced-motion: reduce)").matches, D = Math.PI / 180;
    const EL = "H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca".split(" "), NM = "Hydrogen,Helium,Lithium,Beryllium,Boron,Carbon,Nitrogen,Oxygen,Fluorine,Neon,Sodium,Magnesium,Aluminium,Silicon,Phosphorus,Sulfur,Chlorine,Argon,Potassium,Calcium".split(","), MA = [1, 4, 7, 9, 11, 12, 14, 16, 19, 20, 23, 24, 27, 28, 31, 32, 35, 40, 39, 40];
    const S = { p: 6, n: 6, e: 6 }, CAP = [2, 8, 8, 2], RAD = [54, 80, 106, 132];
    const shells = e => { const r = []; let left = e; CAP.forEach(c => { const k = Math.min(c, left); r.push(k); left -= k; }); return r; };
    let ph = 0, last = performance.now(), touched = 0;
    const draw = () => {
      const sh = shells(S.e); let s = "";
      RAD.forEach((r, i) => { if (sh[i] > 0 || (i < 3 && S.e > 0 && i === sh.findIndex(x => x === 0))) s += `<circle cx="150" cy="150" r="${r}" fill="none" stroke="#c9d2ea" stroke-width="2"/>`; });
      const N = S.p + S.n;
      // interleave protons and neutrons in the nucleus so they mix
      const kinds = []; let pp = S.p, nn = S.n; for (let i = 0; i < N; i++) { if ((i % 2 === 0 && pp > 0) || nn === 0) { kinds.push("p"); pp--; } else { kinds.push("n"); nn--; } }
      kinds.forEach((k, i) => { const r = 5.3 * Math.sqrt(i + .6), a = i * 137.5 * D; s += `<circle cx="${(150 + r * Math.cos(a)).toFixed(1)}" cy="${(150 + r * Math.sin(a)).toFixed(1)}" r="5.6" fill="${k === "p" ? "#e64980" : "#adb5bd"}" stroke="#fff" stroke-width="1"/>`; });
      sh.forEach((c, i) => { for (let j = 0; j < c; j++) { const a = (ph * (1 - i * .18) * (i % 2 ? -1 : 1) + j * 360 / c + i * 20) * D; s += `<circle cx="${(150 + RAD[i] * Math.cos(a)).toFixed(1)}" cy="${(150 + RAD[i] * Math.sin(a)).toFixed(1)}" r="6" fill="#339af0" stroke="#fff" stroke-width="1.5"/>`; } });
      svg.innerHTML = s;
    };
    const info = () => {
      const p = S.p, nm = NM[p - 1], ch = p - S.e, mass = p + S.n, sh = shells(S.e).filter(x => x > 0).join(",") || "none";
      $("#abp").textContent = S.p; $("#abn").textContent = S.n; $("#abe").textContent = S.e;
      const iso = S.n !== MA[p - 1] - p;
      $("#abI").innerHTML = `<b style="font-size:17px;color:var(--brand)">${nm} (${EL[p - 1]})</b><br>Atomic number (protons): <b>${p}</b><br>Mass number (protons + neutrons): <b>${mass}</b><br>Charge: <b>${ch === 0 ? "0 (neutral atom)" : (ch > 0 ? "+" : "−") + Math.abs(ch) + " (ion)"}</b><br>Electronic structure: <b>${sh}</b>`;
      $("#abSay").textContent = ch !== 0 ? (ch > 0 ? "Fewer electrons than protons, so it is a positive ion." : "More electrons than protons, so it is a negative ion.") + " Changing the number of electrons never changes the element."
        : iso ? "Same number of protons but a different number of neutrons: this is an isotope of " + nm.toLowerCase() + ". It is still " + nm.toLowerCase() + "." : "A neutral atom has equal numbers of protons and electrons. Change the number of PROTONS to make a different element.";
      document.querySelectorAll("#abT button").forEach(b => b.style.outline = +b.dataset.z === p ? "3px solid var(--brand2)" : "");
    };
    $("#abT").innerHTML = EL.map((e, i) => `<button class="btn ghost st" style="min-width:36px;padding:4px 6px" data-z="${i + 1}" aria-label="${NM[i]}">${e}</button>`).join("");
    document.querySelectorAll("#abT button").forEach(b => b.onclick = () => { const z = +b.dataset.z; S.p = z; S.e = z; S.n = MA[z - 1] - z; info(); draw(); addXP(1); });
    document.querySelectorAll("#ab [data-c]").forEach(b => b.onclick = () => { const k = b.dataset.c[0], d = b.dataset.c[1] === "+" ? 1 : -1; const lim = { p: [1, 20], n: [0, 24], e: [0, 20] }[k]; S[k] = Math.max(lim[0], Math.min(lim[1], S[k] + d)); if (++touched === 8) addXP(2); info(); draw(); });
    const step = now => { if (!document.body.contains(svg)) return; const dt = (now - last) / 1000; last = now; if (!rm) { ph += dt * 40; draw(); } requestAnimationFrame(step); };
    info(); draw(); requestAnimationFrame(step);
  },
};

  }).call(globalThis);
}
