// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/averagesDots.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* averagesDots — dot plot: drag dots left/right, tap to add, drag down to remove; live mean, median, mode and range */
(function(){
  const X=v=>30+v*30, AY=165, R=11, MAXN=14, TOP=["#3b5bdb","#ff5a3c","#137a4a","#8b5cf6"];
  const f1=v=>Math.round(v*100)/100;
  WIDGETS.averagesDots={title:"Mean, median, mode and range",intro:"Drag the dots along the line, tap the line to add one, drag a dot down to remove it. Which average moves most? Which stays put?",
  html(){ return `<div class="explore" id="avw"><svg id="avs" viewBox="0 0 360 256" role="img" aria-label="Dot plot on a number line from 0 to 10" style="touch-action:none;user-select:none;background:#fff;border-radius:12px;border:2px solid #cfd8ff"><g id="avd"></g></svg>
    <div class="row" style="margin:10px 0;justify-content:center;gap:8px" id="avc"></div>
    <p class="small" id="avsay" style="text-align:center;margin:4px 0 0"></p>
    <div class="row" style="justify-content:center;margin-top:8px"><button class="btn ghost pr" data-a="rand">Shuffle data</button><button class="btn ghost pr" data-a="out">Add an outlier</button><button class="btn ghost pr" data-a="reset">Reset</button></div></div>`; },
  init(){
    const svg=$("#avs"), dyn=$("#avd"), START=[2,3,3,5,7]; let vals=START.slice(), drag=-1, ghost=null, show={mean:true,median:true,mode:true,range:true}, mv=0;
    const order=()=>vals.map((v,i)=>i).sort((a,b)=>vals[a]-vals[b]||a-b);
    const stats=()=>{ const s=vals.slice().sort((a,b)=>a-b), n=s.length, sum=s.reduce((a,b)=>a+b,0), mean=sum/n, med=n%2?s[(n-1)/2]:(s[n/2-1]+s[n/2])/2, fr={}; s.forEach(v=>fr[v]=(fr[v]||0)+1); const mf=Math.max(...Object.values(fr)), modes=mf>1?Object.keys(fr).filter(k=>fr[k]===mf).map(Number):[];
      return {s,n,sum,mean,med,modes,mf,range:s[n-1]-s[0]}; };
    const draw=()=>{
      const st=stats(); let h=""; const pos={};
      for(let v=0;v<=10;v++){ h+=`<line x1="${X(v)}" y1="${AY}" x2="${X(v)}" y2="${AY+6}" stroke="#7b83a3" stroke-width="2"/><text x="${X(v)}" y="${AY+21}" text-anchor="middle" font-size="12" font-weight="800" fill="#4a5275">${v}</text>`; }
      h+=`<line x1="18" y1="${AY}" x2="342" y2="${AY}" stroke="#141a33" stroke-width="3" stroke-linecap="round"/>`;
      if(show.range){ const a=X(st.s[0]),b=X(st.s[st.n-1]); h+=`<path d="M${a} ${AY+62}V${AY+68}H${b}V${AY+62}" fill="none" stroke="${TOP[3]}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/><text x="${(a+b)/2}" y="${AY+83}" text-anchor="middle" font-size="11" font-weight="900" fill="${TOP[3]}">range ${st.range}</text>`; }
      if(show.mode) st.modes.forEach(m=>h+=`<rect x="${X(m)-16}" y="${AY-(st.mf-1)*Math.min(2*R+1,(AY-40)/st.mf)-2*R-6}" width="32" height="${(st.mf-1)*Math.min(2*R+1,(AY-40)/st.mf)+2*R+6}" rx="10" fill="${TOP[2]}" fill-opacity=".14" stroke="${TOP[2]}" stroke-dasharray="4 3"/>`);
      if(show.median){ const a=st.med; h+=`<line x1="${X(a)}" y1="14" x2="${X(a)}" y2="${AY}" stroke="${TOP[1]}" stroke-width="2.5" stroke-dasharray="6 4"/><text x="${X(a)}" y="11" text-anchor="middle" font-size="11" font-weight="900" fill="${TOP[1]}">median ${f1(a)}</text>`; }
      if(show.mean){ const m=X(st.mean); h+=`<polygon points="${m},${AY+27} ${m-9},${AY+41} ${m+9},${AY+41}" fill="${TOP[0]}" stroke="#fff" stroke-width="2"/><text x="${m}" y="${AY+54}" text-anchor="middle" font-size="11" font-weight="900" fill="${TOP[0]}">mean ${f1(st.mean)}</text>`; }
      const cnt={}, mxs=st.mf, sp=Math.min(2*R+1,(AY-40)/mxs); order().forEach(i=>{ const v=vals[i]; cnt[v]=(cnt[v]||0)+1; const cy=AY-R-2-(cnt[v]-1)*sp; pos[i]=[X(v),cy]; });
      vals.forEach((v,i)=>{ const p=i===drag&&ghost?ghost:pos[i]; const rm=i===drag&&ghost&&ghost[1]>AY+18; h+=`<circle class="avdot" data-i="${i}" cx="${p[0]}" cy="${p[1]}" r="${R}" fill="${rm?"#b3261e":"#3b5bdb"}" fill-opacity="${i===drag?.7:1}" stroke="#fff" stroke-width="2.5" style="cursor:grab"/>`; });
      if(vals.length===0) h+=""; dyn.innerHTML=h;
      const chip=(k,c,t,d)=>`<button class="btn ghost fk${show[k]?" sel":""}" data-k="${k}" style="border-color:${show[k]?c:""};text-align:left"><b style="color:${c}">${t}</b><br><span class="stat" style="font-size:15px">${d}</span></button>`;
      $("#avc").innerHTML=chip("mean",TOP[0],"Mean",f1(st.mean))+chip("median",TOP[1],"Median",f1(st.med))+chip("mode",TOP[2],"Mode",st.modes.length?st.modes.join(", "):"none")+chip("range",TOP[3],"Range",st.range);
      $("#avc").querySelectorAll("button").forEach(b=>b.onclick=()=>{ show[b.dataset.k]=!show[b.dataset.k]; draw(); });
      $("#avsay").innerHTML=`Data in order: ${st.s.map((v,i)=>{ const mid=st.n%2?i===(st.n-1)/2:i===st.n/2-1||i===st.n/2; return mid?`<b style="color:${TOP[1]}">${v}</b>`:v; }).join(", ")}<br>Mean = ${st.sum} ÷ ${st.n} = ${f1(st.mean)} · Range = ${st.s[st.n-1]} − ${st.s[0]} = ${st.range}`;
    };
    const pos=e=>{ const q=svg.createSVGPoint(); q.x=e.clientX; q.y=e.clientY; return q.matrixTransform(svg.getScreenCTM().inverse()); };
    const col=x=>Math.max(0,Math.min(10,Math.round((x-30)/30)));
    svg.addEventListener("pointerdown",e=>{ const d=e.target.closest(".avdot"), r=pos(e); svg.setPointerCapture(e.pointerId); e.preventDefault();
      if(d){ drag=+d.dataset.i; ghost=[X(vals[drag]),r.y]; } else if(r.y<AY+8&&vals.length<MAXN){ vals.push(col(r.x)); if(++mv===3) addXP(2); draw(); } });
    svg.addEventListener("pointermove",e=>{ if(drag<0) return; const r=pos(e); vals[drag]=col(r.x); ghost=[Math.max(18,Math.min(342,r.x)),r.y]; if(r.y<AY-5) ghost=null; if(++mv===6) addXP(2); draw(); });
    const up=e=>{ if(drag<0) return; const r=pos(e); if(r.y>AY+18&&vals.length>3) vals.splice(drag,1); drag=-1; ghost=null; draw(); };
    svg.addEventListener("pointerup",up); svg.addEventListener("pointercancel",up);
    $("#avw").querySelectorAll(".pr").forEach(b=>b.onclick=()=>{ const a=b.dataset.a; if(a==="reset") vals=START.slice(); else if(a==="rand"){ const n=5+Math.floor(Math.random()*5); vals=[...Array(n)].map(()=>1+Math.floor(Math.random()*8)); } else if(vals.length<MAXN) vals.push(10); draw(); });
    draw();
  }};
})();

  }).call(globalThis);
}
