// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/cellExplorer.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Cell explorer: animal, plant and bacterial cells. Tap a part to see its job; "Challenge me" asks you to find parts from their jobs. */
WIDGETS.cellExplorer = {
  title: "Explore inside a cell",
  intro: "Pick a type of cell and tap its parts to find out what each one does. Then try the challenge!",
  html() {
    return `<div class="explore" id="ce"><div class="row" style="justify-content:center;margin-bottom:8px"><button class="btn st" data-k="animal">Animal cell</button><button class="btn ghost st" data-k="plant">Plant cell</button><button class="btn ghost st" data-k="bact">Bacterium</button></div>
    <svg id="ces" viewBox="0 0 600 290" role="img" aria-label="A cell diagram. Tap a part to learn about it."></svg>
    <div id="ceI" style="min-height:74px;border-radius:12px;background:#fff;border:2px solid var(--line);padding:10px 14px;margin-top:8px"></div>
    <div class="row spread" style="margin-top:8px"><span class="small" id="ceSc"></span><button class="btn ghost st" id="ceCh">Challenge me</button></div></div>`;
  },
  init() {
    const svg = $("#ces"), info = $("#ceI");
    const J = { // name, job (own words, GCSE level)
      nucleus: ["Nucleus", "Contains the cell's DNA (genetic material), which controls the activities of the cell.", "contains the DNA that controls the cell"],
      cyto: ["Cytoplasm", "A jelly-like substance where most of the chemical reactions in the cell happen.", "is the jelly-like part where most chemical reactions happen"],
      memb: ["Cell membrane", "Controls which substances move into and out of the cell.", "controls what goes into and out of the cell"],
      mito: ["Mitochondria", "Where aerobic respiration happens, releasing the energy the cell needs.", "is where respiration releases energy"],
      ribo: ["Ribosomes", "Where proteins are made (protein synthesis).", "is where proteins are made"],
      wall: ["Cell wall", "Strengthens the cell and supports it. In plant cells it is made of cellulose.", "strengthens and supports the cell"],
      vac: ["Permanent vacuole", "Filled with cell sap. It helps keep the cell firm, supporting the plant.", "is filled with cell sap"],
      chlo: ["Chloroplasts", "Contain chlorophyll and are where photosynthesis takes place.", "is where photosynthesis happens"],
      dna: ["Circular DNA loop", "The bacterium's genetic material floats free in the cytoplasm. There is no nucleus.", "holds the bacterium's DNA as a loop"],
      plas: ["Plasmids", "Small extra rings of DNA that carry a few extra genes.", "carries small extra rings of DNA"],
      flag: ["Flagellum", "A whip-like tail that spins to move the bacterium along.", "spins like a tail to move the bacterium"],
    };
    const T = {
      animal: { note: "Animal cells have a nucleus but no cell wall, chloroplasts or permanent vacuole.", parts: ["nucleus", "cyto", "memb", "mito", "ribo"] },
      plant: { note: "Plant cells have everything an animal cell has, plus a cell wall, chloroplasts and a permanent vacuole.", parts: ["wall", "memb", "nucleus", "vac", "chlo", "mito", "ribo", "cyto"] },
      bact: { note: "Bacteria are prokaryotes: tiny cells with no nucleus. The DNA is a loop in the cytoplasm.", parts: ["wall", "memb", "cyto", "dna", "plas", "ribo", "flag"] },
    };
    let kind = "animal", sel = null, ch = null, score = 0;
    const shapes = { // each returns svg for that part (hit area = data-p)
      animal: { memb: `<ellipse cx="300" cy="145" rx="235" ry="125" fill="none" stroke="#e8590c" stroke-width="7"/>`, nucleus: `<circle cx="285" cy="140" r="62" fill="#c9d4ff" stroke="#3b5bdb" stroke-width="5"/><circle cx="285" cy="140" r="17" fill="#3b5bdb"/>`,
        mito: [[135, 105, 20], [430, 200, 340], [410, 90, 60]].map(([x, y, r]) => `<g transform="translate(${x} ${y}) rotate(${r})"><ellipse rx="30" ry="14" fill="#ffb066" stroke="#c2410c" stroke-width="3"/><path d="M-18 0q6 -8 12 0t12 0t12 0" fill="none" stroke="#c2410c" stroke-width="2"/></g>`).join(""),
        ribo: [[190, 210], [230, 65], [370, 60], [470, 150], [200, 165], [365, 215], [155, 150], [345, 105]].map(([x, y]) => `<circle cx="${x}" cy="${y}" r="5" fill="#7048e8"/>`).join("") },
      plant: { wall: `<rect x="40" y="15" width="520" height="260" rx="30" fill="none" stroke="#2f9e44" stroke-width="14"/>`, memb: `<rect x="54" y="29" width="492" height="232" rx="22" fill="none" stroke="#e8590c" stroke-width="4" stroke-dasharray="2 0"/>`,
        vac: `<rect x="215" y="55" width="220" height="170" rx="60" fill="#d0ebff" stroke="#1c7ed6" stroke-width="4"/>`, nucleus: `<circle cx="110" cy="140" r="38" fill="#c9d4ff" stroke="#3b5bdb" stroke-width="4"/><circle cx="110" cy="140" r="11" fill="#3b5bdb"/>`,
        chlo: [[150, 62, 10], [470, 70, -10], [490, 195, 30], [170, 228, 0], [330, 245, 0]].map(([x, y, r]) => `<g transform="translate(${x} ${y}) rotate(${r})"><ellipse rx="26" ry="14" fill="#69db7c" stroke="#2b8a3e" stroke-width="3"/><path d="M-14 -3h28M-14 3h28" stroke="#2b8a3e" stroke-width="2"/></g>`).join(""),
        mito: [[105, 225, 20], [480, 130, 80]].map(([x, y, r]) => `<g transform="translate(${x} ${y}) rotate(${r})"><ellipse rx="24" ry="11" fill="#ffb066" stroke="#c2410c" stroke-width="3"/></g>`).join(""),
        ribo: [[75, 85], [190, 105], [455, 240], [520, 90], [190, 190], [440, 45]].map(([x, y]) => `<circle cx="${x}" cy="${y}" r="5" fill="#7048e8"/>`).join("") },
      bact: { wall: `<rect x="70" y="60" width="440" height="170" rx="85" fill="none" stroke="#7048e8" stroke-width="13"/>`, memb: `<rect x="83" y="73" width="414" height="144" rx="72" fill="none" stroke="#e8590c" stroke-width="4"/>`,
        flag: `<path d="M508 145q30 -30 45 0t45 0" fill="none" stroke="#141a33" stroke-width="6" stroke-linecap="round" transform="translate(-10 0)"/>`, dna: `<path d="M200 150q-10 -55 55 -55t80 25q45 25 -5 62q-50 30 -95 8t-35 -40z" fill="none" stroke="#3b5bdb" stroke-width="6" stroke-linejoin="round"/>`,
        plas: [[140, 170], [415, 105], [430, 185]].map(([x, y]) => `<circle cx="${x}" cy="${y}" r="13" fill="none" stroke="#c2255c" stroke-width="5"/>`).join(""), ribo: [[160, 105], [250, 190], [340, 90], [470, 145], [150, 200], [380, 205], [270, 90]].map(([x, y]) => `<circle cx="${x}" cy="${y}" r="5" fill="#7048e8"/>`).join("") },
    };
    const cyto = () => kind === "animal" ? `<ellipse cx="300" cy="145" rx="235" ry="125" fill="#fff0ec"/>` : kind === "plant" ? `<rect x="40" y="15" width="520" height="260" rx="30" fill="#eaf7e4"/>` : `<rect x="70" y="60" width="440" height="170" rx="85" fill="#f6efff"/>`;
    const showInfo = () => {
      if (ch) info.innerHTML = `<b>Challenge:</b> which part ${J[ch.pick][2]}? <span class="small">Tap it in the cell.</span>${ch.msg ? `<div class="small" style="color:${ch.ok ? "var(--ok)" : "var(--bad)"};margin-top:4px"><b>${ch.msg}</b></div>` : ""}`;
      else if (sel) { const f = ["animal", "plant", "bact"].filter(k => T[k].parts.includes(sel)).map(k => ({ animal: "animal cells", plant: "plant cells", bact: "bacteria" }[k])); info.innerHTML = `<b style="color:var(--brand)">${J[sel][0]}</b><div>${J[sel][1]}</div><div class="small">Found in: ${f.join(", ")}</div>`; }
      else info.innerHTML = `<div>${T[kind].note}</div><div class="small">Tap a part of the cell to find out what it does.</div>`;
      $("#ceSc").textContent = score ? "Challenge score: " + score : "";
    };
    const draw = () => {
      let s = `<g data-p="cyto" style="cursor:pointer" tabindex="0" role="button" aria-label="Cytoplasm">${cyto()}</g>`;
      T[kind].parts.filter(p => p !== "cyto").forEach(p => { const on = sel === p; s += `<g data-p="${p}" tabindex="0" role="button" aria-label="${ch ? "Cell part" : J[p][0]}" style="cursor:pointer;${on ? "filter:drop-shadow(0 0 7px #f08c00)" : ""}" opacity="${sel && !on && !ch ? .5 : 1}">${shapes[kind][p]}</g>`; });
      svg.innerHTML = s;
      svg.querySelectorAll("[data-p]").forEach(g => { const f = () => pick(g.dataset.p); g.onclick = f; g.onkeydown = e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); f(); } }; });
      document.querySelectorAll("#ce [data-k]").forEach(b => b.className = "btn st" + (b.dataset.k === kind ? "" : " ghost"));
      showInfo();
    };
    const ask = () => { const c = T[kind].parts.filter(p => !ch || p !== ch.pick); ch = { pick: c[Math.floor(Math.random() * c.length)], msg: ch && ch.msg || "" }; };
    const pick = p => {
      if (!ch) { sel = p; draw(); return; }
      if (p === ch.pick) { const nm = J[p][0]; score++; addXP(2); ask(); ch.msg = "Yes, that was the " + nm.toLowerCase() + "! Next one:"; ch.ok = true; }
      else { ch.msg = "Not that one, try again."; ch.ok = false; }
      draw();
    };
    document.querySelectorAll("#ce [data-k]").forEach(b => b.onclick = () => { kind = b.dataset.k; sel = null; ch = null; $("#ceCh").textContent = "Challenge me"; draw(); });
    $("#ceCh").onclick = () => { if (ch) { ch = null; $("#ceCh").textContent = "Challenge me"; } else { sel = null; ask(); ch.msg = ""; $("#ceCh").textContent = "Stop challenge"; } draw(); };
    draw();
  },
};

  }).call(globalThis);
}
