// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/circuitBuilder.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Circuit builder: cells, bulbs, switch; series vs parallel. Idealised: each cell 1.5 V, each bulb a fixed 6 ohm resistor. */
WIDGETS.circuitBuilder = {
  title: "Build a circuit",
  intro: "Add cells and bulbs, flip between series and parallel, click the switch, and tap a bulb to unscrew it. What happens to the brightness?",
  html() {
    return `<div class="explore" id="cb"><svg id="cbs" viewBox="0 0 600 250" role="img" aria-label="A circuit with cells, a switch and bulbs. Moving dots show the current."></svg>
    <div class="row" style="justify-content:center;margin:8px 0"><button class="btn st" id="cbSer">Series</button><button class="btn ghost st" id="cbPar">Parallel</button>
     <span class="small">Cells</span><button class="btn ghost st" data-c="c-" aria-label="fewer cells">−</button><b class="stat" id="cbNc">1</b><button class="btn ghost st" data-c="c+" aria-label="more cells">+</button>
     <span class="small">Bulbs</span><button class="btn ghost st" data-c="b-" aria-label="fewer bulbs">−</button><b class="stat" id="cbNb">2</b><button class="btn ghost st" data-c="b+" aria-label="more bulbs">+</button></div>
    <div class="row spread" style="gap:6px"><span class="small">Current from the cells <b class="stat" id="cbI"></b></span><span class="small">Voltage across each bulb <b class="stat" id="cbV"></b></span><span class="small">Total resistance <b class="stat" id="cbR"></b></span></div>
    <p class="small" id="cbSay" style="margin:8px 0 0"></p></div>`;
  },
  init() {
    const svg = $("#cbs"), rm = matchMedia("(prefers-reduced-motion: reduce)").matches, NS = "http://www.w3.org/2000/svg";
    const S = { par: false, nc: 1, nb: 2, sw: true, out: [false, false, false] }, RB = 6, VC = 1.5, ns = (t, a, c) => `<${t} ${a}>${c || ""}</${t}>`;
    let paths = [], raf = 0, last = performance.now();
    const bx = () => S.par ? { 1: [330], 2: [260, 420], 3: [210, 330, 450] }[S.nb] : { 1: [330], 2: [270, 410], 3: [230, 340, 450] }[S.nb];
    const model = () => {
      const V = VC * S.nc, xs = bx(), on = S.out.slice(0, S.nb).map(o => !o);
      let I, Vb, Rt, bulbI;
      if (!S.par) { const ok = S.sw && on.every(Boolean); Rt = RB * S.nb; I = ok ? V / Rt : 0; Vb = ok ? V / S.nb : 0; bulbI = on.map(() => I); }
      else { const k = on.filter(Boolean).length; Rt = k ? RB / k : Infinity; bulbI = on.map(o => (S.sw && o ? V / RB : 0)); I = bulbI.reduce((a, b) => a + b, 0); Vb = S.sw ? V : 0; }
      return { V, xs, on, I, Vb, Rt, bulbI };
    };
    const P = (pts, I) => paths.push({ pts, I, ph: 0 });
    const build = m => {
      paths = []; const xs = m.xs, T = 50, B = 210;
      if (!S.par) P([[50, 100], [50, T], [550, T], [550, B], [50, B], [50, 160]], m.I);
      else {
        const rem = i => m.bulbI.slice(i).reduce((a, b) => a + b, 0), n = xs.length;
        P([[50, 100], [50, T], [xs[0], T]], m.I); P([[xs[0], B], [50, B], [50, 160]], m.I);
        xs.forEach((x, i) => { P([[x, T], [x, B]], m.bulbI[i]); if (i < n - 1) { P([[x, T], [xs[i + 1], T]], rem(i + 1)); P([[xs[i + 1], B], [x, B]], rem(i + 1)); } });
      }
    };
    const wire = m => paths.map(p => `<polyline points="${p.pts.map(q => q.join(",")).join(" ")}" fill="none" stroke="#4a5275" stroke-width="4" stroke-linejoin="round"/>`).join("");
    const bulb = (x, y, i, m) => {
      const b = Math.min(1, m.bulbI[i] * m.bulbI[i] * RB / ((VC / RB) * (VC / RB) * RB)), gone = m.xs && S.out[i];
      const glow = b > 0 ? `<circle cx="${x}" cy="${y}" r="${30 + b * 12}" fill="url(#cbg)" opacity="${.15 + .85 * b}"/>` : "";
      const body = gone ? `<circle cx="${x}" cy="${y}" r="18" fill="#fff" stroke="#b3261e" stroke-width="3" stroke-dasharray="4 5"/><text x="${x}" y="${y + 4}" text-anchor="middle" font-size="10" font-weight="800" fill="#b3261e">gone</text>`
        : `<circle cx="${x}" cy="${y}" r="18" fill="${b > 0 ? `rgb(255,${245 - (1 - b) * 20},${180 + (1 - b) * 60})` : "#fff"}" stroke="#141a33" stroke-width="3"/><path d="M${x - 12.7} ${y - 12.7}L${x + 12.7} ${y + 12.7}M${x + 12.7} ${y - 12.7}L${x - 12.7} ${y + 12.7}" stroke="#141a33" stroke-width="2.5"/>`;
      return `${glow}<g class="cbb" data-i="${i}" tabindex="0" role="button" aria-label="Bulb ${i + 1}. Activate to ${gone ? "screw it back in" : "unscrew it"}" style="cursor:pointer">${body}<rect x="${x - 26}" y="${y - 26}" width="52" height="52" fill="transparent"/></g><text x="${x}" y="${y + 40}" text-anchor="middle" font-size="11" font-weight="800" fill="#7b83a3">${gone ? "tap to fit" : b > 0 ? m.bulbI[i].toFixed(2) + " A" : "off"}</text>`;
    };
    const battery = () => { // cells drawn as long (+) then short (-) plates, stacked; + at the top
      let s = `<rect x="32" y="${130 - S.nc * 12 - 6}" width="36" height="${S.nc * 24 + 12}" rx="6" fill="#fff"/>`;
      for (let i = 0; i < S.nc; i++) { const y = 130 - S.nc * 12 + i * 24 + 6; s += `<line x1="36" y1="${y}" x2="64" y2="${y}" stroke="#141a33" stroke-width="3"/><line x1="43" y1="${y + 12}" x2="57" y2="${y + 12}" stroke="#141a33" stroke-width="7"/>`; }
      return s + `<text x="78" y="${130 - S.nc * 12 + 4}" font-size="15" font-weight="900" fill="#b3261e">+</text><text x="78" y="${130 + S.nc * 12 + 6}" font-size="17" font-weight="900" fill="#3b5bdb">−</text><text x="96" y="134" font-size="11" font-weight="800" fill="#7b83a3">${(VC * S.nc).toFixed(1)} V</text>`;
    };
    const sw = () => { const x = S.par ? 110 : 130, y = 50; return `<g id="cbSw" tabindex="0" role="button" aria-label="Switch, currently ${S.sw ? "closed" : "open"}. Activate to toggle" style="cursor:pointer"><rect x="${x - 30}" y="${y - 12}" width="60" height="24" fill="#f5f6fc"/><circle cx="${x - 20}" cy="${y}" r="4.5" fill="#141a33"/><circle cx="${x + 20}" cy="${y}" r="4.5" fill="#141a33"/><line x1="${x - 20}" y1="${y}" x2="${S.sw ? x + 16 : x + 10}" y2="${S.sw ? y : y - 22}" stroke="#141a33" stroke-width="4" stroke-linecap="round"/><rect x="${x - 34}" y="${y - 30}" width="68" height="46" fill="transparent"/></g><text x="${x}" y="${y + 30}" text-anchor="middle" font-size="11" font-weight="800" fill="${S.sw ? "#137a4a" : "#b3261e"}">switch ${S.sw ? "closed" : "open"}</text>`; };
    const draw = () => {
      const m = model(); build(m);
      const parts = [`<defs><radialGradient id="cbg"><stop offset="0" stop-color="#ffe066" stop-opacity=".95"/><stop offset="1" stop-color="#ffe066" stop-opacity="0"/></radialGradient></defs>`, wire(m), `<g id="cbd"></g>`];
      // bulb backgrounds hide the wire behind them
      m.xs.forEach((x, i) => { const y = S.par ? 130 : 50; parts.push(`<rect x="${S.par ? x - 22 : x - 22}" y="${y - 22}" width="44" height="44" fill="#f7f9ff"/>`); parts.push(bulb(x, y, i, m)); });
      parts.push(battery(), sw());
      svg.innerHTML = parts.join(""); $("#cbNc").textContent = S.nc; $("#cbNb").textContent = S.nb;
      $("#cbI").textContent = m.I.toFixed(2) + " A"; $("#cbV").textContent = m.Vb.toFixed(2) + " V"; $("#cbR").textContent = isFinite(m.Rt) ? +m.Rt.toFixed(2) + " Ω" : "∞";
      const anyOut = S.out.slice(0, S.nb).some(Boolean);
      $("#cbSay").textContent = !S.sw ? "The switch is open, so the circuit is broken. There is no complete loop, so no current flows and the bulbs are off."
        : !S.par ? (anyOut ? "One bulb has been removed from the series loop, so the circuit is broken and every bulb goes out." : "Series: there is only one loop, so the current is the same everywhere. The cell's voltage is shared between the bulbs, so more bulbs means dimmer bulbs. Total resistance = " + S.nb + " × 6 Ω.")
        : (anyOut ? "Parallel: the other bulbs are still lit because each has its own complete loop back to the cell." : "Parallel: each bulb is connected straight across the cells, so each gets the full voltage and stays just as bright. The current splits between the branches and adds up again. Adding branches lowers the total resistance.");
      const on = svg.querySelectorAll(".cbb");
      on.forEach(g => { const f = () => { S.out[+g.dataset.i] = !S.out[+g.dataset.i]; draw(); addXP(1); }; g.onclick = f; g.onkeydown = e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); f(); } }; });
      const s = $("#cbSw", svg); const f = () => { S.sw = !S.sw; draw(); addXP(1); }; s.onclick = f; s.onkeydown = e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); f(); } };
      $("#cbSer").className = "btn st" + (S.par ? " ghost" : ""); $("#cbPar").className = "btn st" + (S.par ? "" : " ghost");
    };
    $("#cbSer").onclick = () => { S.par = false; draw(); }; $("#cbPar").onclick = () => { S.par = true; draw(); };
    document.querySelectorAll("#cb [data-c]").forEach(b => b.onclick = () => { const c = b.dataset.c; if (c === "c-") S.nc = Math.max(1, S.nc - 1); if (c === "c+") S.nc = Math.min(3, S.nc + 1); if (c === "b-") S.nb = Math.max(1, S.nb - 1); if (c === "b+") S.nb = Math.min(3, S.nb + 1); draw(); });
    const dots = () => {
      const g = $("#cbd", svg); if (!g) return; let s = "";
      for (const p of paths) {
        if (p.I <= 0) continue; const seg = [], L = []; let tot = 0;
        for (let i = 0; i < p.pts.length - 1; i++) { const d = Math.hypot(p.pts[i + 1][0] - p.pts[i][0], p.pts[i + 1][1] - p.pts[i][1]); seg.push(d); tot += d; }
        for (let d = (p.ph % 22); d < tot; d += 22) { let r = d, i = 0; while (i < seg.length - 1 && r > seg[i]) { r -= seg[i]; i++; } const a = p.pts[i], b = p.pts[i + 1], t = r / seg[i]; s += `<circle cx="${(a[0] + (b[0] - a[0]) * t).toFixed(1)}" cy="${(a[1] + (b[1] - a[1]) * t).toFixed(1)}" r="4.5" fill="#f08c00" stroke="#fff" stroke-width="1.5"/>`; }
      }
      g.innerHTML = s;
    };
    const step = now => { if (!document.body.contains(svg)) return; const dt = Math.min(.05, (now - last) / 1000); last = now; if (!rm) for (const p of paths) p.ph += p.I * 160 * dt; dots(); raf = requestAnimationFrame(step); };
    draw(); raf = requestAnimationFrame(step);
  },
};

  }).call(globalThis);
}
