// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/coordGrid.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* coordGrid — four-quadrant coordinate grid: drag the corners, read live coordinates, translate the shape */
(function(){
  const RM=matchMedia("(prefers-reduced-motion: reduce)").matches, N=6, C=26, O=180, X=x=>O+x*C, Y=y=>O-y*C;
  const SH={triangle:[[1,1],[4,1],[2,4]],rectangle:[[1,1],[5,1],[5,3],[1,3]],arrow:[[-4,-1],[-1,-1],[-1,-3],[2,0],[-1,3],[-1,1],[-4,1]]};
  const L="ABCDEFG";
  WIDGETS.coordGrid={title:"Coordinates on a grid",intro:"Drag the corners of the shape. Read each coordinate: across first, then up. Then translate it!",
  html(){ return `<div class="explore" id="cgw">
    <svg id="cgs" viewBox="0 0 360 360" role="img" aria-label="Four quadrant coordinate grid with a draggable shape" style="touch-action:none;max-width:420px;margin:0 auto;user-select:none">
      <rect x="6" y="6" width="348" height="348" rx="14" fill="#fff" stroke="#cfd8ff"/>
      <g id="cgg"></g><g id="cgd"></g></svg>
    <div class="row" style="justify-content:center;margin:10px 0 4px" id="cgsh">${Object.keys(SH).map(k=>`<button class="btn ghost pr" data-k="${k}">${k}</button>`).join("")}</div>
    <div class="row spread" style="margin:8px 0"><div class="row"><span class="small">Move right</span><button class="btn ghost st" data-s="x-" aria-label="less right">−</button><span class="stat" id="cgtx">3</span><button class="btn ghost st" data-s="x+" aria-label="more right">+</button></div>
    <div class="row"><span class="small">Move up</span><button class="btn ghost st" data-s="y-" aria-label="less up">−</button><span class="stat" id="cgty">2</span><button class="btn ghost st" data-s="y+" aria-label="more up">+</button></div>
    <button class="btn" id="cgplay">▶ Slide it</button></div>
    <p class="small" id="cgsay" style="margin:6px 0 8px;font-weight:800;color:var(--brand)"></p><div class="row" id="cgchips" style="gap:6px"></div>
    <p class="small" style="margin:8px 0 0" id="cgcur">Move over the grid to read any point.</p></div>`; },
  init(){
    const svg=$("#cgs"), dyn=$("#cgd"); let pts=SH.triangle.map(p=>p.slice()), tx=3, ty=2, k=1, drag=-1, cur=null, raf=0, moved=0;
    let g=""; for(let i=-N;i<=N;i++){ g+=`<line x1="${X(i)}" y1="${Y(-N)}" x2="${X(i)}" y2="${Y(N)}" stroke="${i?"#e3e8fb":"#141a33"}" stroke-width="${i?1:2}"/><line x1="${X(-N)}" y1="${Y(i)}" x2="${X(N)}" y2="${Y(i)}" stroke="${i?"#e3e8fb":"#141a33"}" stroke-width="${i?1:2}"/>`;
      if(i&&i%2===0) g+=`<text x="${X(i)}" y="${Y(0)+13}" font-size="10" font-weight="800" text-anchor="middle" fill="#7b83a3">${i}</text><text x="${X(0)-5}" y="${Y(i)+3.5}" font-size="10" font-weight="800" text-anchor="end" fill="#7b83a3">${i}</text>`; }
    g+=`<text x="${X(N)+1}" y="${Y(0)-6}" font-size="12" font-weight="900" fill="#3b5bdb" text-anchor="end">x</text><text x="${X(0)+8}" y="${Y(N)+12}" font-size="12" font-weight="900" fill="#3b5bdb">y</text>`;
    [["II",-N/2,N/2],["I",N/2,N/2],["III",-N/2,-N/2],["IV",N/2,-N/2]].forEach(([t,a,b])=>g+=`<text x="${X(a)}" y="${Y(b)}" font-size="34" font-weight="900" text-anchor="middle" fill="#3b5bdb" opacity=".07">${t}</text>`);
    $("#cgg").innerHTML=g;
    const say=()=>{ const a=tx?`${Math.abs(tx)} ${tx>0?"right":"left"}`:"", b=ty?`${Math.abs(ty)} ${ty>0?"up":"down"}`:""; $("#cgtx").textContent=tx; $("#cgty").textContent=ty; $("#cgsay").textContent="Translation: "+([a,b].filter(Boolean).join(", ")||"no movement")+"  =  vector ("+tx+", "+ty+")"; };
    const poly=(ps,st)=>`<polygon points="${ps.map(p=>X(p[0])+","+Y(p[1])).join(" ")}" ${st}/>`;
    const fit=()=>{ const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]); tx=Math.max(-N-Math.min(...xs),Math.min(N-Math.max(...xs),tx)); ty=Math.max(-N-Math.min(...ys),Math.min(N-Math.max(...ys),ty)); say(); };
    const draw=()=>{ fit();
      const im=pts.map(p=>[p[0]+tx*k,p[1]+ty*k]);
      let h=poly(im,'fill="#ff5a3c" fill-opacity=".16" stroke="#ff5a3c" stroke-width="2.5" stroke-dasharray="6 4" stroke-linejoin="round"');
      if(tx||ty) h+=pts.map((p,i)=>`<line x1="${X(p[0])}" y1="${Y(p[1])}" x2="${X(im[i][0])}" y2="${Y(im[i][1])}" stroke="#ff5a3c" stroke-width="1" opacity=".45"/>`).join("");
      h+=poly(pts,'fill="#3b5bdb" fill-opacity=".22" stroke="#1e3a8a" stroke-width="3" stroke-linejoin="round"');
      pts.forEach((p,i)=>{ h+=`<circle class="cgv" data-i="${i}" cx="${X(p[0])}" cy="${Y(p[1])}" r="${drag===i?11:9}" fill="#1e3a8a" stroke="#fff" stroke-width="3" style="cursor:grab" tabindex="0" role="slider" aria-label="Corner ${L[i]} at ${p[0]}, ${p[1]}"/><text x="${X(p[0])}" y="${Y(p[1])+4}" font-size="10" font-weight="900" fill="#fff" text-anchor="middle" pointer-events="none">${L[i]}</text>`; });
      if(cur) h+=`<g pointer-events="none"><circle cx="${X(cur[0])}" cy="${Y(cur[1])}" r="5" fill="none" stroke="#141a33" stroke-width="2"/></g>`;
      dyn.innerHTML=h;
      $("#cgchips").innerHTML=pts.map((p,i)=>`<span class="pill" style="background:#fff;border:2px solid #cfd8ff;font-weight:800">${L[i]} <span class="stat" style="font-size:15px">(${p[0]}, ${p[1]})</span>${tx||ty?` → <span style="color:#c2410c">${L[i]}′ (${p[0]+tx}, ${p[1]+ty})</span>`:""}</span>`).join("");
      $("#cgcur").textContent=cur?`Pointer at (${cur[0]}, ${cur[1]}) — ${cur[0]===0&&cur[1]===0?"the origin":cur[0]===0||cur[1]===0?"on an axis":"quadrant "+(cur[0]>0?(cur[1]>0?"I":"IV"):(cur[1]>0?"II":"III"))}`:"Move over the grid to read any point.";
    };
    const pos=e=>{ const q=svg.createSVGPoint(); q.x=e.clientX; q.y=e.clientY; const r=q.matrixTransform(svg.getScreenCTM().inverse()); return [Math.max(-N,Math.min(N,Math.round((r.x-O)/C))),Math.max(-N,Math.min(N,Math.round((O-r.y)/C)))]; };
    svg.addEventListener("pointerdown",e=>{ const v=e.target.closest(".cgv"); if(!v) return; drag=+v.dataset.i; svg.setPointerCapture(e.pointerId); e.preventDefault(); draw(); });
    svg.addEventListener("pointermove",e=>{ const p=pos(e); cur=p; if(drag>=0&&(pts[drag][0]!==p[0]||pts[drag][1]!==p[1])){ pts[drag]=p; moved++; if(moved===4) addXP(2); } draw(); });
    const up=()=>{ if(drag>=0){ drag=-1; draw(); } }; svg.addEventListener("pointerup",up); svg.addEventListener("pointercancel",up);
    svg.addEventListener("pointerleave",()=>{ if(drag<0){ cur=null; draw(); } });
    svg.addEventListener("keydown",e=>{ const v=e.target.closest(".cgv"); const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,1],ArrowDown:[0,-1]}[e.key]; if(!v||!d) return; e.preventDefault(); const i=+v.dataset.i; pts[i]=[Math.max(-N,Math.min(N,pts[i][0]+d[0])),Math.max(-N,Math.min(N,pts[i][1]+d[1]))]; draw(); const n=svg.querySelector(`.cgv[data-i="${i}"]`); if(n) n.focus(); });
    const play=()=>{ cancelAnimationFrame(raf); if(RM){ k=1; draw(); return; } const t0=performance.now(); const st=n=>{ const t=Math.min(1,(n-t0)/900); k=t*t*(3-2*t); draw(); if(t<1) raf=requestAnimationFrame(st); }; raf=requestAnimationFrame(st); };
    $("#cgw").querySelectorAll(".st").forEach(b=>b.onclick=()=>{ const s=b.dataset.s; if(s==="x-")tx=tx-1; if(s==="x+")tx=tx+1; if(s==="y-")ty=ty-1; if(s==="y+")ty=ty+1; play(); });
    $("#cgw").querySelectorAll("#cgsh .pr").forEach(b=>b.onclick=()=>{ pts=SH[b.dataset.k].map(p=>p.slice()); draw(); });
    $("#cgplay").onclick=()=>{ addXP(1); k=0; play(); };
    say(); draw();
  }};
})();

  }).call(globalThis);
}
