// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/equationBalancer.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Chemical equation balancer: set the big numbers (coefficients) and watch the atom tally and the molecules on each side. */
WIDGETS.equationBalancer = {
  title: "Balance the equation",
  intro: "Change the big numbers in front of each formula until every element has the same number of atoms on both sides. You cannot change the small numbers!",
  html() {
    return `<div class="explore" id="eb"><div class="row" style="justify-content:center;gap:6px;margin-bottom:8px" id="ebR"></div>
    <div id="ebW" class="small" style="text-align:center;margin-bottom:6px"></div>
    <div id="ebE" class="row" style="justify-content:center;gap:6px 4px;font-size:19px;font-weight:800"></div>
    <div style="display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:stretch;margin:10px 0"><div id="ebL" style="background:#fff;border:2px solid var(--line);border-radius:12px;padding:6px;display:flex;flex-wrap:wrap;gap:4px;align-content:flex-start;min-height:80px"></div><div style="align-self:center;font-size:24px;font-weight:900;color:var(--brand)">→</div><div id="ebP" style="background:#fff;border:2px solid var(--line);border-radius:12px;padding:6px;display:flex;flex-wrap:wrap;gap:4px;align-content:flex-start;min-height:80px"></div></div>
    <div id="ebT" class="row" style="justify-content:center;gap:8px"></div><p class="small" id="ebSay" style="margin:8px 0 0;text-align:center"></p></div>`;
  },
  init() {
    const COL = { H: ["#f1f3f5", "#868e96"], O: ["#ff8787", "#c92a2a"], C: ["#868e96", "#343a40"], N: ["#748ffc", "#364fc7"], Mg: ["#69db7c", "#2b8a3e"], Na: ["#da77f2", "#862e9c"], Cl: ["#a9e34b", "#5c940d"], Al: ["#ced4da", "#495057"], Fe: ["#ffa94d", "#d9480f"], Ca: ["#63e6be", "#087f5b"] };
    const R = [
      { w: "hydrogen + oxygen → water", l: ["H2", "O2"], r: ["H2O"], k: [2, 1, 2] }, { w: "nitrogen + hydrogen → ammonia", l: ["N2", "H2"], r: ["NH3"], k: [1, 3, 2] },
      { w: "methane + oxygen → carbon dioxide + water", l: ["CH4", "O2"], r: ["CO2", "H2O"], k: [1, 2, 1, 2] }, { w: "magnesium + oxygen → magnesium oxide", l: ["Mg", "O2"], r: ["MgO"], k: [2, 1, 2] },
      { w: "sodium + chlorine → sodium chloride", l: ["Na", "Cl2"], r: ["NaCl"], k: [2, 1, 2] }, { w: "magnesium + hydrochloric acid → magnesium chloride + hydrogen", l: ["Mg", "HCl"], r: ["MgCl2", "H2"], k: [1, 2, 1, 1] },
      { w: "aluminium + oxygen → aluminium oxide", l: ["Al", "O2"], r: ["Al2O3"], k: [4, 3, 2] }, { w: "iron(III) oxide + carbon monoxide → iron + carbon dioxide", l: ["Fe2O3", "CO"], r: ["Fe", "CO2"], k: [1, 3, 2, 3] },
      { w: "calcium carbonate + hydrochloric acid → calcium chloride + water + carbon dioxide", l: ["CaCO3", "HCl"], r: ["CaCl2", "H2O", "CO2"], k: [1, 2, 1, 1, 1] },
    ];
    const parse = f => { const m = {}; for (const [, e, n] of f.matchAll(/([A-Z][a-z]?)(\d*)/g)) m[e] = (m[e] || 0) + (+n || 1); return m; };
    const sub = f => f.replace(/(\d+)/g, "<sub>$1</sub>");
    const mol = f => { const c = parse(f), at = []; Object.entries(c).forEach(([e, n]) => { for (let i = 0; i < n; i++) at.push(e); }); const cen = at.length > 2 ? Object.keys(c).find(e => c[e] === 1) : null, pos = [];
      if (cen) { pos.push([0, 0, cen]); const o = at.filter(e => e !== cen); o.forEach((e, i) => { const a = i / o.length * 6.283 - 1.2; pos.push([Math.cos(a) * 12, Math.sin(a) * 12, e]); }); }
      else if (at.length === 1) pos.push([0, 0, at[0]]); else if (at.length === 2) pos.push([-8, 0, at[0]], [8, 0, at[1]]); else at.forEach((e, i) => { const a = i / at.length * 6.283; pos.push([Math.cos(a) * 12, Math.sin(a) * 12, e]); });
      return `<svg style="width:38px;height:38px" width="38" height="38" viewBox="-22 -22 44 44" aria-hidden="true">${pos.map(([x, y, e]) => `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${e === "H" ? 6 : 8}" fill="${COL[e][0]}" stroke="${COL[e][1]}" stroke-width="1.6"/>`).join("")}</svg>`; };
    let ri = 0, K = [], done = {};
    const all = () => [...R[ri].l, ...R[ri].r];
    const tally = () => { const L = {}, P = {}; R[ri].l.forEach((f, i) => Object.entries(parse(f)).forEach(([e, n]) => L[e] = (L[e] || 0) + n * K[i])); R[ri].r.forEach((f, j) => Object.entries(parse(f)).forEach(([e, n]) => P[e] = (P[e] || 0) + n * K[R[ri].l.length + j])); return [L, P]; };
    const draw = () => {
      const q = R[ri], nl = q.l.length, sp = all();
      $("#ebW").textContent = q.w;
      const cell = (f, i) => `<span class="row" style="gap:3px;flex-wrap:nowrap"><button class="btn ghost st" data-i="${i}" data-d="-1" aria-label="decrease number in front of ${f}" style="padding:2px 9px">−</button><b class="stat" style="min-width:16px;text-align:center;font-size:22px">${K[i]}</b><button class="btn ghost st" data-i="${i}" data-d="1" aria-label="increase number in front of ${f}" style="padding:2px 9px">+</button><span>${sub(f)}</span></span>`;
      $("#ebE").innerHTML = q.l.map((f, i) => cell(f, i)).join('<span style="color:var(--ink3)">+</span>') + '<span style="color:var(--brand);margin:0 4px">→</span>' + q.r.map((f, j) => cell(f, nl + j)).join('<span style="color:var(--ink3)">+</span>');
      const side = (arr, off) => arr.map((f, i) => Array.from({ length: K[off + i] }, () => mol(f)).join("")).join("");
      $("#ebL").innerHTML = side(q.l, 0) || '<span class="small">nothing here</span>'; $("#ebP").innerHTML = side(q.r, nl) || '<span class="small">nothing here</span>';
      const [L, P] = tally(), els = [...new Set([...Object.keys(L), ...Object.keys(P)])]; let ok = true;
      $("#ebT").innerHTML = els.map(e => { const a = L[e] || 0, b = P[e] || 0, g = a === b; if (!g) ok = false; return `<span style="display:inline-flex;gap:6px;align-items:center;background:${g ? "var(--ok-soft)" : "var(--bad-soft)"};border:2px solid ${g ? "var(--ok)" : "var(--bad)"};border-radius:10px;padding:2px 10px;font-weight:800"><svg style="width:16px;height:16px;flex:none" width="16" height="16" viewBox="-8 -8 16 16"><circle r="7" fill="${COL[e][0]}" stroke="${COL[e][1]}" stroke-width="1.5"/></svg>${e}: ${a} → ${b} ${g ? "✓" : "✗"}</span>`; }).join("");
      const gd = K.reduce((a, b) => gcd(a, b)), zero = K.some(k => k === 0);
      $("#ebSay").textContent = zero ? "Every formula needs at least 1 in front of it: the substances are all needed." : ok ? (gd > 1 ? "Balanced, but the numbers can be made smaller. Divide them all by " + gd + " to get the simplest whole numbers." : "Balanced! The same atoms are on both sides, because atoms are never created or destroyed in a reaction (conservation of mass).") : "Not balanced yet. Look at the red tally boxes: which element has too many or too few atoms on one side?";
      if (ok && !zero && gd === 1 && !done[ri]) { done[ri] = 1; addXP(3); }
      $("#ebR").innerHTML = R.map((r, i) => `<button class="btn st${i === ri ? "" : " ghost"}" data-r="${i}">${done[i] ? "✓ " : ""}${i + 1}</button>`).join("");
      document.querySelectorAll("#eb [data-d]").forEach(b => b.onclick = () => { K[+b.dataset.i] = Math.max(0, Math.min(6, K[+b.dataset.i] + +b.dataset.d)); draw(); });
      document.querySelectorAll("#eb [data-r]").forEach(b => b.onclick = () => { ri = +b.dataset.r; K = all().map(() => 1); draw(); });
    };
    K = all().map(() => 1); draw();
  },
};

  }).call(globalThis);
}
