// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/foodWeb.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Food web: build a food chain, or remove an organism and predict what happens to the others. Arrows point from the food to the eater (direction of energy transfer). */
WIDGETS.foodWeb = {
  title: "Food chains and webs",
  intro: "Build a food chain by tapping organisms from the producer upwards. Then switch mode and see what happens when one organism disappears.",
  html() {
    return `<div class="explore" id="fw"><div class="row" style="justify-content:center;margin-bottom:6px"><button class="btn st" data-m="chain">Build a food chain</button><button class="btn ghost st" data-m="gone">What if it disappears?</button></div>
    <svg id="fws" viewBox="0 0 480 340" role="img" aria-label="A meadow food web. Arrows point from the food to the animal that eats it."></svg>
    <div id="fwI" style="min-height:58px;background:#fff;border:2px solid var(--line);border-radius:12px;padding:8px 12px;margin-top:6px"></div>
    <div class="row spread" style="margin-top:6px"><span class="small">Arrows show the flow of energy: they point from the food to the eater.</span><button class="btn ghost st" id="fwR">Reset</button></div></div>`;
  },
  init() {
    const svg = $("#fws"), info = $("#fwI");
    const O = { grass: ["🌱", "Grass", 140, 292, 0], clover: ["☘️", "Clover", 340, 292, 0], hopper: ["🦗", "Grasshopper", 75, 205, 1], rabbit: ["🐇", "Rabbit", 330, 205, 1], frog: ["🐸", "Frog", 190, 122, 2], fox: ["🦊", "Fox", 95, 38, 3], hawk: ["🦅", "Hawk", 385, 38, 3] };
    const E = [["grass", "hopper"], ["grass", "rabbit"], ["clover", "rabbit"], ["hopper", "frog"], ["frog", "fox"], ["frog", "hawk"], ["rabbit", "fox"], ["rabbit", "hawk"]]; // [food, eater]
    const LV = ["producer", "primary consumer", "secondary consumer", "tertiary consumer"];
    let mode = "chain", chain = [], gone = null, msg = "", done = 0;
    const eaters = k => E.filter(e => e[0] === k).map(e => e[1]), foods = k => E.filter(e => e[1] === k).map(e => e[0]);
    const effects = r => { // direct effects are strong (1); knock-on effects are weak (0.5) and never override a direct one
      const v = {}; foods(r).forEach(p => v[p] = 1); eaters(r).forEach(p => v[p] = -1);
      const d = { ...v }; Object.keys(d).forEach(a => { const sg = d[a] > 0 ? 1 : -1; foods(a).forEach(b => { if (b !== r && d[b] === undefined) v[b] = (v[b] || 0) - sg * .5; }); eaters(a).forEach(c => { if (c !== r && d[c] === undefined) v[c] = (v[c] || 0) + sg * .5; }); });
      Object.keys(v).forEach(k => { if (d[k] === undefined) v[k] = Math.abs(v[k]) < .5 ? 0 : Math.sign(v[k]) * .5; }); delete v[r]; return v; };
    const arrows = () => E.map(([a, b]) => { const A = O[a], B = O[b], dx = B[2] - A[2], dy = B[3] - A[3], L = Math.hypot(dx, dy), ux = dx / L, uy = dy / L, x1 = A[2] + ux * 28, y1 = A[3] + uy * 28, x2 = B[2] - ux * 32, y2 = B[3] - uy * 32;
      const on = mode === "chain" && chain.includes(a) && chain[chain.indexOf(a) + 1] === b, dead = mode === "gone" && gone && (a === gone || b === gone), c = on ? "#e8590c" : dead ? "#c9cee0" : "#7b83a3";
      return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${c}" stroke-width="${on ? 5 : 3}" stroke-linecap="round"/><path d="M${x2} ${y2}l${-ux * 12 - uy * 7} ${-uy * 12 + ux * 7}M${x2} ${y2}l${-ux * 12 + uy * 7} ${-uy * 12 - ux * 7}" stroke="${c}" stroke-width="${on ? 5 : 3}" stroke-linecap="round"/>`; }).join("");
    const draw = () => {
      const ef = gone ? effects(gone) : {}; let s = arrows();
      Object.entries(O).forEach(([k, [em, nm, x, y]]) => {
        const sel = mode === "chain" && chain.includes(k), isGone = gone === k, e = ef[k], next = mode === "chain" && chain.length && eaters(chain[chain.length - 1]).includes(k);
        s += `<g data-k="${k}" tabindex="0" role="button" aria-label="${nm}" style="cursor:pointer" opacity="${isGone ? .35 : 1}"><circle cx="${x}" cy="${y}" r="29" fill="${sel ? "#fff1d6" : "#fff"}" stroke="${sel ? "#e8590c" : next ? "#137a4a" : "#98a3c7"}" stroke-width="${sel || next ? 5 : 3}"${next ? ' stroke-dasharray="6 5"' : ""}/><text x="${x}" y="${y + 11}" text-anchor="middle" font-size="31">${em}</text><text x="${x}" y="${y + 47}" text-anchor="middle" font-size="14" font-weight="800" fill="#141a33">${nm}</text>${isGone ? `<path d="M${x - 20} ${y - 20}L${x + 20} ${y + 20}M${x + 20} ${y - 20}L${x - 20} ${y + 20}" stroke="#b3261e" stroke-width="6" stroke-linecap="round"/>` : ""}</g>`;
        if (e !== undefined) { const strong = Math.abs(e) >= 1; s += `<g pointer-events="none"><circle cx="${x + 26}" cy="${y - 24}" r="14" fill="${e > 0 ? "#137a4a" : e < 0 ? "#b3261e" : "#7b83a3"}" opacity="${strong ? 1 : .6}"/><text x="${x + 26}" y="${y - 19}" text-anchor="middle" font-size="15" font-weight="900" fill="#fff">${e > 0 ? "▲" : e < 0 ? "▼" : "?"}</text></g>`; }
      });
      svg.innerHTML = s;
      svg.querySelectorAll("[data-k]").forEach(g => { const f = () => tap(g.dataset.k); g.onclick = f; g.onkeydown = e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); f(); } }; });
      document.querySelectorAll("#fw [data-m]").forEach(b => b.className = "btn st" + (b.dataset.m === mode ? "" : " ghost"));
      if (mode === "chain") info.innerHTML = chain.length ? `<div style="font-weight:800">${chain.map(k => O[k][1]).join(" → ")}</div><div class="small">${chain.map((k, i) => O[k][1] + " = " + LV[i]).join(" · ")}</div>${msg ? `<div class="small" style="color:var(--brand);font-weight:800">${msg}</div>` : ""}` : `<div>Tap a <b>producer</b> (a plant) to start your food chain.</div>${msg ? `<div class="small" style="color:var(--bad)">${msg}</div>` : ""}`;
      else if (gone) { const nm = (f) => Object.entries(ef).filter(([, v]) => f(v)).map(([k]) => O[k][1]), up = nm(v => v >= 1), dn = nm(v => v <= -1), mu = nm(v => v > 0 && v < 1), md = nm(v => v < 0 && v > -1);
        info.innerHTML = `<div><b>${O[gone][1]}</b> has disappeared.</div>${up.length ? `<div class="small"><b style="color:var(--ok)">▲ likely to increase:</b> ${up.join(", ")} (fewer of them are eaten, or there is less competition)</div>` : ""}${dn.length ? `<div class="small"><b style="color:var(--bad)">▼ likely to decrease:</b> ${dn.join(", ")} (they lose a food source, or lose food they used to have)</div>` : ""}${mu.length || md.length ? `<div class="small">Knock-on effects (fainter badges), which may also happen: ${mu.length ? mu.join(", ") + " ▲" : ""}${mu.length && md.length ? "; " : ""}${md.length ? md.join(", ") + " ▼" : ""}</div>` : ""}<div class="small">Real ecosystems are complicated, so these are the likely first changes.</div>`; }
      else info.innerHTML = `<div>Tap an organism to remove it, then see which populations rise (▲) or fall (▼).</div>`;
    };
    const tap = k => {
      if (mode === "gone") { gone = gone === k ? null : k; if (gone) addXP(1); draw(); return; }
      msg = "";
      if (!chain.length) { if (O[k][4] === 0) chain = [k]; else msg = "A food chain starts with a producer: a plant that makes its own food."; }
      else { const last = chain[chain.length - 1]; if (k === last) chain.pop(); else if (eaters(last).includes(k)) { chain.push(k); if (!eaters(k).length) { msg = "Complete! " + O[k][1] + " is at the top: nothing in this web eats it (an apex predator)."; done++; addXP(3); } } else msg = O[k][1] + " does not eat " + O[last][1] + ". Tap one of the dashed green circles."; }
      draw();
    };
    document.querySelectorAll("#fw [data-m]").forEach(b => b.onclick = () => { mode = b.dataset.m; chain = []; gone = null; msg = ""; draw(); });
    $("#fwR").onclick = () => { chain = []; gone = null; msg = ""; draw(); };
    draw();
  },
};

  }).call(globalThis);
}
