// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/forceMotion.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Forces and motion: resultant force, F = m a, and a live speed-time graph (constant friction or air resistance / terminal velocity) */
WIDGETS.forceMotion = {
  title: "Push, resist, accelerate",
  intro: "Drag the force arrows (or use the sliders). Find out what balanced and unbalanced forces do to the speed of the trolley.",
  html() {
    return `<div class="explore" id="fm"><svg id="fms" viewBox="0 0 600 270" style="touch-action:none;user-select:none" role="img" aria-label="A trolley with a forward push arrow and a backward resistive force arrow, above a speed-time graph"></svg>
    <div class="row spread" style="margin-top:8px"><label class="small" style="flex:1;min-width:130px">Push <b class="stat" id="fmFv">4 N</b><input type="range" id="fmF" min="0" max="10" value="4" style="width:100%;accent-color:var(--brand)"></label>
      <label class="small" style="flex:1;min-width:130px"><span id="fmBn">Friction</span> <b class="stat" id="fmBv">2 N</b><input type="range" id="fmB" min="0" max="10" value="2" style="width:100%;accent-color:var(--brand)"></label></div>
    <div class="row" style="justify-content:center;margin:8px 0"><span class="small">Mass</span><button class="btn st" data-m="1">1 kg</button><button class="btn ghost st" data-m="2">2 kg</button><button class="btn ghost st" data-m="5">5 kg</button>
      <button class="btn ghost st" id="fmMode">Friction: constant</button><button class="btn ghost st" id="fmRun" style="display:none">Run 1 s</button><button class="btn ghost st" id="fmRst">Reset</button></div>
    <div class="row spread"><span class="small">Resultant force <b class="stat" id="fmR">2 N →</b></span><span class="small">Acceleration <b class="stat" id="fmA"></b></span><span class="small">Speed <b class="stat" id="fmS">0.0 m/s</b></span></div>
    <p class="small" id="fmSay" style="margin:8px 0 0"></p></div>`;
  },
  init() {
    const svg = $("#fms"), rm = matchMedia("(prefers-reduced-motion: reduce)").matches, KPX = 13, X0 = 385, X1 = 215;
    const S = { F: 4, B: 2, m: 1, air: false, v: 0, t: 0, ground: 0, pts: [[0, 0]], acc: 0 };
    let raf = 0, last = performance.now(), acc = 0;
    const back = v => S.air ? S.B * (v / 10) ** 2 : S.B; // air: B is the drag force at 10 m/s
    const force = () => { // returns resultant (N), taking static-friction behaviour into account
      if (S.air) return S.F - back(S.v);
      if (S.v <= 0.0001) return Math.max(0, S.F - S.B) * (S.F > S.B ? 1 : 0);
      return S.F - S.B;
    };
    const sim = dt => {
      const n = Math.ceil(dt / .01); const h = dt / n;
      for (let i = 0; i < n; i++) { const R = force(); const a = R / S.m; const v2 = S.v + a * h; S.acc = a; if (!S.air && S.v > 0 && v2 < 0) S.v = 0; else S.v = Math.max(0, v2); S.t += h; S.ground += S.v * h; if (S.t - S.pts[S.pts.length - 1][0] >= .049) S.pts.push([S.t, S.v]); }
      if (S.pts.length > 900) S.pts.splice(0, 100);
    };
    const arrow = (x1, x2, y, col, id) => { const d = Math.sign(x2 - x1) || 1, L = Math.abs(x2 - x1); if (L < 3) return `<circle cx="${x1}" cy="${y}" r="5" fill="${col}"/>`; return `<g id="${id}" style="cursor:ew-resize"><line x1="${x1}" y1="${y}" x2="${x2 - d * 12}" y2="${y}" stroke="${col}" stroke-width="9" stroke-linecap="round"/><path d="M${x2} ${y}L${x2 - d * 22} ${y - 15}L${x2 - d * 22} ${y + 15}Z" fill="${col}"/><circle cx="${x2 - d * 6}" cy="${y}" r="20" fill="transparent"/></g>`; };
    const draw = () => {
      const ms = (S.ground * 30) % 60, w = 60 + S.m * 12, hx = 300 - w / 2;
      let g = `<rect x="0" y="0" width="600" height="150" fill="#eef4ff"/><rect x="0" y="118" width="600" height="32" fill="#c9d2ea"/>`;
      for (let x = -60 + (-ms); x < 640; x += 60) g += `<rect x="${x}" y="130" width="28" height="5" rx="2" fill="#98a3c7"/>`;
      g += `<rect x="${hx}" y="${86 - S.m * 2}" width="${w}" height="${30 + S.m * 2}" rx="8" fill="#3b5bdb" stroke="#1e3a8a" stroke-width="3"/><text x="300" y="${106}" text-anchor="middle" font-size="15" font-weight="900" fill="#fff">${S.m} kg</text><circle cx="${hx + 16}" cy="118" r="9" fill="#141a33"/><circle cx="${hx + w - 16}" cy="118" r="9" fill="#141a33"/>`;
      const fx = hx + w + 4, bx = hx - 4, fl = S.F * KPX, bl = back(S.v) * KPX;
      g += arrow(fx, fx + fl, 70, "#137a4a", "fmAf") + arrow(bx, bx - bl, 70, "#b3261e", "fmAb");
      g += `<text x="${fx + Math.max(fl, 30) / 2}" y="52" text-anchor="middle" font-size="12" font-weight="800" fill="#137a4a">push ${S.F} N</text><text x="${bx - Math.max(bl, 30) / 2}" y="52" text-anchor="middle" font-size="12" font-weight="800" fill="#b3261e">${S.air ? "air resistance" : "friction"} ${+back(S.v).toFixed(1)} N</text>`;
      // speed-time graph
      const gx = 44, gy = 168, gw = 530, gh = 90, tmax = Math.max(12, S.t + 1), t0 = Math.max(0, S.t - 12), win = S.pts.filter(p => p[0] >= t0);
      const vmax = Math.max(5, Math.ceil(Math.max(...win.map(p => p[1]), S.v) / 5) * 5);
      g += `<line x1="${gx}" y1="${gy}" x2="${gx}" y2="${gy + gh}" stroke="#141a33" stroke-width="2"/><line x1="${gx}" y1="${gy + gh}" x2="${gx + gw}" y2="${gy + gh}" stroke="#141a33" stroke-width="2"/>`;
      g += `<text x="${gx - 6}" y="${gy + 8}" text-anchor="end" font-size="11" fill="#4a5275">${vmax}</text><text x="${gx - 6}" y="${gy + gh + 4}" text-anchor="end" font-size="11" fill="#4a5275">0</text><text x="12" y="${gy + gh / 2}" font-size="11" font-weight="800" fill="#4a5275" transform="rotate(-90 12 ${gy + gh / 2})" text-anchor="middle">speed (m/s)</text><text x="${gx + gw / 2}" y="${gy + gh + 16}" text-anchor="middle" font-size="11" font-weight="800" fill="#4a5275">time (s)</text>`;
      if (win.length > 1) g += `<polyline fill="none" stroke="#e8590c" stroke-width="3" stroke-linejoin="round" points="${win.map(p => (gx + (p[0] - t0) / Math.max(12, S.t - t0) * gw).toFixed(1) + "," + (gy + gh - p[1] / vmax * gh).toFixed(1)).join(" ")}"/>`;
      svg.innerHTML = g;
      const R = force(), st = Math.abs(R) < .005;
      $("#fmR").textContent = st ? "0 N (balanced)" : (+R.toFixed(2)) + " N " + (R > 0 ? "→" : "←"); $("#fmA").textContent = (+(R / S.m).toFixed(2)) + " m/s²"; $("#fmS").textContent = S.v.toFixed(1) + " m/s";
      $("#fmSay").textContent = st && S.v < .05 ? "Balanced forces and the trolley is at rest, so it stays at rest." : st ? "Balanced forces, so no resultant force and no acceleration. The trolley keeps moving at a constant speed." : R > 0 ? "Unbalanced: the resultant force is forwards, so the trolley speeds up. Resultant force = mass × acceleration, so a heavier trolley accelerates less." : "Unbalanced: the resultant force is backwards, so the trolley slows down.";
      if (S.air && st && S.v > .5) $("#fmSay").textContent += " The speed has stopped rising: this is the terminal velocity.";
    };
    const sync = () => { $("#fmFv").textContent = S.F + " N"; $("#fmBv").textContent = S.B + " N"; $("#fmF").value = S.F; $("#fmB").value = S.B; $("#fmBn").textContent = S.air ? "Air resistance at 10 m/s" : "Friction"; $("#fmMode").textContent = S.air ? "Resistance: air (grows with speed)" : "Friction: constant"; document.querySelectorAll("#fm [data-m]").forEach(b => b.className = "btn st" + (+b.dataset.m === S.m ? "" : " ghost")); };
    $("#fmF").oninput = e => { S.F = +e.target.value; sync(); draw(); }; $("#fmB").oninput = e => { S.B = +e.target.value; sync(); draw(); };
    document.querySelectorAll("#fm [data-m]").forEach(b => b.onclick = () => { S.m = +b.dataset.m; sync(); draw(); });
    $("#fmMode").onclick = () => { S.air = !S.air; sync(); draw(); };
    $("#fmRst").onclick = () => { S.v = 0; S.t = 0; S.ground = 0; S.pts = [[0, 0]]; draw(); };
    $("#fmRun").onclick = () => { for (let i = 0; i < 4; i++) sim(.25); draw(); addXP(1); };
    if (rm) $("#fmRun").style.display = "";
    let drag = null;
    svg.onpointerdown = e => { const g = e.target.closest("#fmAf,#fmAb"); if (!g) return; drag = g.id; svg.setPointerCapture(e.pointerId); };
    svg.onpointermove = e => { if (!drag) return; const pt = svg.createSVGPoint(); pt.x = e.clientX; pt.y = e.clientY; const x = pt.matrixTransform(svg.getScreenCTM().inverse()).x, w = 60 + S.m * 12, hx = 300 - w / 2;
      if (drag === "fmAf") S.F = Math.max(0, Math.min(10, Math.round((x - (hx + w + 4)) / KPX))); else S.B = Math.max(0, Math.min(10, Math.round(((hx - 4) - x) / KPX))); sync(); draw(); };
    svg.onpointerup = svg.onpointercancel = () => { if (drag) addXP(1); drag = null; };
    const step = now => { if (!document.body.contains(svg)) return; const dt = Math.min(.05, (now - last) / 1000); last = now; if (!rm) { sim(dt); draw(); } raf = requestAnimationFrame(step); };
    sync(); draw(); raf = requestAnimationFrame(step);
  },
};

  }).call(globalThis);
}
