// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/functionMachine.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* functionMachine — numbers travel in → rule → out; build a table, or hide the rule and guess it */
(function(){
const css=`<style>
#fm .fm-stage{position:relative;height:120px;overflow:hidden}
#fm .fm-belt{position:absolute;left:0;right:0;top:78px;height:10px;background:repeating-linear-gradient(90deg,#9fb0ff 0 14px,#cfd8ff 14px 28px);border-radius:5px}
#fm .fm-mach{position:absolute;left:50%;top:22px;width:130px;margin-left:-65px;height:80px;background:var(--brand);border-radius:16px;color:#fff;display:grid;place-items:center;font-weight:900;font-size:22px;box-shadow:0 5px 0 #0f2260;z-index:2}
#fm .fm-mach small{position:absolute;top:-16px;font-size:10px;letter-spacing:.08em;color:var(--ink3)}
#fm .fm-mach.run{animation:fmshake .12s 4}
@keyframes fmshake{50%{transform:translateY(2px) rotate(-1deg)}}
#fm .fm-num{position:absolute;top:46px;width:44px;height:40px;margin-left:-22px;border-radius:10px;background:#fff;border:3px solid var(--brand2);display:grid;place-items:center;font-weight:900;font-size:17px;color:var(--brand);z-index:3}
#fm .fm-num.out{background:#ffd43b;border-color:#b58900;color:#5a4300}
#fm .fm-tab{width:100%;border-collapse:collapse;margin-top:10px;text-align:center;font-weight:800}
#fm .fm-tab td,#fm .fm-tab th{border:2px solid #cfd8ff;background:#fff;padding:5px 2px;font-size:14px}
#fm .fm-tab th{background:var(--brand-soft);color:var(--brand);font-size:11px;width:60px}
#fm .fm-tab td.q{color:var(--ink3)}
#fm .chip{border:2px solid var(--line);background:#fff;border-radius:99px;padding:5px 12px;font-weight:800;font-size:13px;color:var(--ink2)}
#fm .chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
#fm input[type=range]{width:100%;accent-color:var(--brand2)}
</style>`;
const RULES=[{t:"+ 5",f:x=>x+5},{t:"× 3",f:x=>x*3},{t:"− 2",f:x=>x-2},{t:"× 2 + 1",f:x=>2*x+1},{t:"× 4 − 3",f:x=>4*x-3},{t:"n²",f:x=>x*x},{t:"÷ 2",f:x=>x/2}];
WIDGETS.functionMachine={
 title:"Function machine",
 intro:"Pick a rule, choose an input and send it through the machine. Fill the table, then hide the rule and see if you can work it out.",
 html(){return css+`<div class="explore" id="fm">
 <div class="row" style="margin-bottom:8px"><span class="small">Rule</span>${RULES.map((r,i)=>`<button class="chip${i?"":" on"}" data-r="${i}">${r.t}</button>`).join("")}</div>
 <div class="row spread" style="margin-bottom:4px"><span class="small">Input: <span class="stat" id="fm-in">4</span></span><label class="switch"><input type="checkbox" id="fm-hide"> Hide the rule</label></div>
 <input type="range" id="fm-rng" min="0" max="20" value="4" aria-label="input number">
 <div class="fm-stage" id="fm-st"><div class="fm-belt"></div><div class="fm-mach" id="fm-m"><small>RULE</small><span id="fm-rule"></span></div></div>
 <div class="row" style="justify-content:center"><button class="btn" id="fm-go">Send it through ▶</button><button class="btn ghost" id="fm-clr">Clear table</button></div>
 <table class="fm-tab" id="fm-tab"></table>
 <p class="small" id="fm-say" style="text-align:center;margin:10px 0 0"></p></div>`},
 init(){
  const box=$("#fm"),st=$("#fm-st");let ri=0,inp=4,rows=[],busy=false;const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;
  const R=()=>RULES[ri];const fmt=v=>Number.isInteger(v)?v:+v.toFixed(2);
  function table(){const hide=$("#fm-hide").checked;
   $("#fm-tab").innerHTML=`<tr><th>Input</th>${rows.map(r=>`<td>${r.i}</td>`).join("")||"<td class='q'>—</td>"}</tr><tr><th>Output</th>${rows.map(r=>`<td>${fmt(r.o)}</td>`).join("")||"<td class='q'>—</td>"}</tr>`;
   $("#fm-rule").textContent=hide?"?":R().t.replace("n²","n × n");
   $("#fm-say").textContent=hide?(rows.length<2?"Send a few numbers through and look for the pattern in the table.":"What is the machine doing to every input? Untick 'Hide the rule' to check."):rows.length?`Every input goes through “${R().t}”.`:"Send a number through the machine.";}
  function go(){if(busy)return;busy=true;const i=inp,o=R().f(i);const box0=st.getBoundingClientRect().width;
   const a=document.createElement("div");a.className="fm-num";a.textContent=i;st.appendChild(a);
   const m=$("#fm-m"),W=st.clientWidth;
   const finish=()=>{a.remove();b.remove();rows=[...rows.filter(r=>r.i!==i),{i,o}].sort((x,y)=>x.i-y.i).slice(-6);busy=false;table();addXP(rows.length>=3?1:0)};
   const b=document.createElement("div");b.className="fm-num out";b.textContent=fmt(o);b.style.opacity=0;st.appendChild(b);
   if(reduce){a.style.left="20%";b.style.left="80%";b.style.opacity=1;setTimeout(finish,300);return}
   const T=1500;const t0=performance.now();m.classList.add("run");
   const tick=now=>{const t=Math.min(1,(now-t0)/T);
    if(t<.45){a.style.left=(-10+ (t/.45)*(50+10))+"%";a.style.opacity=1;b.style.opacity=0}
    else if(t<.55){const s=1-(t-.45)/.1;a.style.left="50%";a.style.transform=`scale(${s})`;a.style.opacity=s;b.style.opacity=0}
    else{a.style.opacity=0;const u=(t-.55)/.45;b.style.left=(50+u*60)+"%";b.style.opacity=Math.min(1,u*4);b.style.transform=`scale(${.6+.4*Math.min(1,u*3)})`}
    if(t<1)requestAnimationFrame(tick);else{m.classList.remove("run");finish()}};
   requestAnimationFrame(tick)}
  box.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{ri=+b.dataset.r;rows=[];box.querySelectorAll("[data-r]").forEach(x=>x.classList.toggle("on",x===b));table()});
  $("#fm-rng").oninput=e=>{inp=+e.target.value;$("#fm-in").textContent=inp};
  $("#fm-go").onclick=go;$("#fm-clr").onclick=()=>{rows=[];table()};$("#fm-hide").onchange=table;
  table();
 }};
})();

  }).call(globalThis);
}
