// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langSounds.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langSounds — sound explorer (tap a spelling, hear example words, slow or normal) + a "which one did you hear?" minimal-pair game. */
(function(){
const H=()=>WIDGETS._lang;
const S=s=>s.split(";").map(x=>{const p=x.split("|");return{sp:p[0],tip:p[1],w:p[2].split(",")}});
const SND={
fr:S("ou|Like “oo” in “food”.|rouge,jour;u|Round your lips as for “oo”, but say “ee”.|tu,rue;on|Nasal: air goes through the nose, and you don't say the n.|bon,maison;an / en|Nasal “ah”: again no n sound.|dans,enfant;in / ain|Nasal, like the “e” in “bed” said through the nose.|matin,pain;eu|Round your lips and say “uh”.|deux,peu;oi|Sounds like “wa”.|moi,trois;ch|Like “sh”.|chat,chien;j / ge / gi|Like the “s” in “measure”.|jaune,orange;gn|Like “ny” in “canyon”.|montagne,espagnol;é|A tight, closed “ay” sound.|été,écoute;è / ê|More open, like “e” in “bed”.|mère,fête;qu|Just a “k” — the u is silent.|qui,quatre;h|Always silent.|hôtel,homme;final letters|The last consonant is usually silent (t, d, s, x).|petit,grand,vous;liaison|A silent final s links to the next vowel and sounds like z.|les amis,vous avez"),
es:S("vowels a e i o u|Five short, pure vowels. Say each the same way every time, with no gliding.|casa,mesa,sí,sol,uno;j / ge / gi|A strong “h” from the back of the throat.|jugar,gente,jirafa;ll|Like “y” in “yes” in most places.|calle,llave;ñ|Like “ny” in “canyon”.|niño,España;h|Always silent.|hola,hombre;qu|Just a “k” — the u is silent.|queso,quince;gu (before e / i)|A hard “g” — the u is silent.|guerra,guitarra;c (before e / i) and z|In Spain like “th” in “think”.|cine,zapato;v and b|The SAME sound in Spanish, a soft “b”.|vaca,barco;r and rr|Single r is a quick tap — rr and a word-initial r are rolled.|pero,perro,rojo;ch|Like “ch” in “chip”.|chico,leche;d between vowels|Soft, like “th” in “this”.|nada,todo"),
de:S("ä|Like “e” in “bed” (longer in Mädchen).|Mädchen,Käse;ö|Round your lips and say “e”.|schön,Öl;ü|Round your lips as for “oo” and say “ee”.|Tür,müde;ie|A long “ee”.|Brief,Liebe;ei|Like “eye”.|nein,Eis;eu / äu|Like “oy” in “boy”.|neun,Häuser;ch after e, i|A soft hiss made with your tongue high in the mouth.|ich,Milch;ch after a, o, u|Made further back in the throat, like clearing it gently.|Buch,acht;sch|Like “sh”.|Schule,Fisch;sp / st at the start|Sounds like “shp” and “sht”.|Sport,Stuhl;z|Like “ts” in “cats”.|Zeit,Zimmer;w|Sounds like English “v”.|Wasser,Wein;v|Usually sounds like “f”.|Vater,Vogel;s before a vowel|Sounds like “z”.|Sonne,sieben;ß|A sharp “ss”.|Straße,heiß;j|Sounds like English “y”.|ja,Junge")};
const PAIRS={fr:[["tu","tout"],["rue","roue"],["du","doux"],["vu","vous"]],es:[["pero","perro"],["caro","carro"],["pena","peña"]],de:[["schon","schön"],["Bruder","Brüder"],["Mutter","Mütter"]]};
const css=`<style>
#lgs .sg{display:grid;grid-template-columns:repeat(auto-fill,minmax(96px,1fr));gap:8px;margin:10px 0}
#lgs .sg button{border:2px solid var(--line);background:#fff;border-radius:12px;padding:10px 4px;font-weight:900;font-size:19px;color:var(--brand);min-height:52px}
#lgs .sg button.on{background:var(--brand-soft);border-color:var(--brand2)}
#lgs .det{background:#fff;border:2px solid var(--line);border-radius:14px;padding:12px;text-align:center;min-height:120px}
#lgs .det h4{margin:0;font-size:30px;color:var(--brand)}#lgs .wl{display:flex;gap:8px;flex-wrap:wrap;justify-content:center;margin-top:8px}
#lgs .wl button{border:2px solid var(--brand2);background:var(--brand-soft);color:var(--brand);border-radius:99px;padding:8px 14px;font-weight:800;font-size:17px}
#lgs .wl button.pl{animation:lgpop .4s}
#lgs .gm{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}#lgs .gm button{border:2px solid var(--line);background:#fff;border-radius:12px;padding:12px;font-weight:800;font-size:20px;color:var(--ink)}
#lgs .gm button.ok{background:var(--ok-soft);border-color:var(--ok);color:var(--ok)}#lgs .gm button.no{background:var(--bad-soft);border-color:var(--bad);color:var(--bad)}
</style>`;
WIDGETS.langSounds={
 title:"Sound explorer",
 intro:"Tap a spelling to see how it sounds, then tap the example words to hear them. Try the slow button, then the listening game below.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgs"><div class="lg-chips" style="justify-content:flex-end"><button class="lg-chip" id="lgs-sl" aria-pressed="false">🐢 Slow</button></div><div class="sg" id="lgs-g"></div>
 <div class="det" id="lgs-d"></div><div class="lg-msg" id="lgs-msg" hidden></div>
 <hr style="border:0;border-top:2px dashed var(--line);margin:16px 0"><div style="font-weight:800;text-align:center">🎧 Which word did you hear?</div><div class="gm" id="lgs-gm"></div><div class="lg-fb" id="lgs-fb" aria-live="polite"></div>
 <div class="row" style="justify-content:center;gap:8px"><button class="btn ghost" id="lgs-r">🔊 Play again</button><button class="btn" id="lgs-n">New pair</button></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),D=SND[lang],P=PAIRS[lang];let si=0,slow=false,pair=null,target=null,answered=false,score=0,rounds=0;
  const say=(w)=>H_.speak(w,{slow,msg:$("#lgs-msg")});
  function show(){$("#lgs-g").innerHTML=D.map((d,i)=>`<button class="${i===si?"on":""}" data-i="${i}">${esc(d.sp)}</button>`).join("");
    const d=D[si];$("#lgs-d").innerHTML=`<h4>${esc(d.sp)}</h4><div class="small" style="margin-top:4px">${esc(d.tip)}</div><div class="wl">${d.w.map((w,k)=>`<button data-w="${esc(w)}">🔊 ${esc(w)}</button>`).join("")}</div>`}
  function round(auto){pair=P[Math.random()*P.length|0];target=Math.random()<.5?0:1;answered=false;$("#lgs-fb").textContent="";
    const ord=shuffle([0,1]);$("#lgs-gm").innerHTML=ord.map(k=>`<button data-k="${k}">${esc(pair[k])}</button>`).join("");if(auto)say(pair[target])}
  $("#lgs").addEventListener("click",e=>{
    const g=e.target.closest("#lgs-g [data-i]"),w=e.target.closest("#lgs-d [data-w]"),k=e.target.closest("#lgs-gm [data-k]");
    if(g){si=+g.dataset.i;show();say(D[si].w[0])}
    else if(w){w.classList.remove("pl");void w.offsetWidth;w.classList.add("pl");say(w.dataset.w)}
    else if(k&&!answered){answered=true;const ok=+k.dataset.k===target;k.classList.add(ok?"ok":"no");if(!ok)$("#lgs-gm").querySelector(`[data-k="${target}"]`).classList.add("ok");
      rounds++;if(ok){score++;addXP(2)}$("#lgs-fb").innerHTML=ok?`<span class="lg-ok">Yes — ${esc(pair[target])}! (${score} / ${rounds})</span>`:`<span class="lg-no">It was ${esc(pair[target])}, not ${esc(pair[1-target])}. (${score} / ${rounds})</span>`}
  });
  $("#lgs-sl").onclick=()=>{slow=!slow;$("#lgs-sl").classList.toggle("on",slow);$("#lgs-sl").setAttribute("aria-pressed",slow)};
  $("#lgs-r").onclick=()=>say(pair[target]);$("#lgs-n").onclick=()=>round(true);
  show();round(false);
 }};
})();

  }).call(globalThis);
}
