// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langCore.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langCore — shared helpers for the language widgets (French / Spanish / German):
   speech (with graceful fallback), tap-or-drag tiles, the accent/special-character bar, a small verified vocab bank.
   Exposes WIDGETS._accentBar(inputEl) and WIDGETS._lang. Also auto-attaches the accent bar to quiz text inputs in language lessons. */
(function(){
const LANGS={French:"fr",Spanish:"es",German:"de"};
const VL={fr:"fr-FR",es:"es-ES",de:"de-DE"};
const NAME={fr:"French",es:"Spanish",de:"German"};
const LG=()=>LANGS[(typeof L!=="undefined"&&L.subject)||""]||"fr";
const reduce=()=>matchMedia("(prefers-reduced-motion: reduce)").matches;

/* ---------- speech ---------- */
let voices=[];const loadV=()=>{try{voices=speechSynthesis.getVoices()||[]}catch(e){voices=[]}};
if("speechSynthesis" in window){loadV();try{speechSynthesis.addEventListener("voiceschanged",loadV)}catch(e){}}
const voiceFor=l=>voices.find(v=>v.lang.replace("_","-").toLowerCase()===VL[l].toLowerCase())||voices.find(v=>v.lang.toLowerCase().startsWith(l));
const canSpeak=l=>"speechSynthesis" in window&&(voices.length===0||!!voiceFor(l));
function speak(text,o={}){
  const l=o.lang||LG(),msg=o.msg;
  const fail=()=>{if(msg){msg.className="lg-msg";msg.textContent=`No ${NAME[l]} voice is available on this device, so there is no sound. Read it aloud yourself, then check the spelling.`;msg.hidden=false}return false};
  if(!canSpeak(l))return fail();
  try{
    speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=VL[l];const v=voiceFor(l);if(v)u.voice=v;u.rate=o.slow?.55:.9;
    u.onerror=e=>{if(e&&e.error&&e.error!=="canceled"&&e.error!=="interrupted")fail()};if(o.onend)u.onend=o.onend;
    speechSynthesis.speak(u);if(msg)msg.hidden=true;return true;
  }catch(e){return fail()}
}
const norm=s=>String(s).toLowerCase().replace(/[’]/g,"'").replace(/[.,;:!?¿¡"()]/g,"").replace(/\s+/g," ").trim();
const flat=s=>norm(s).normalize("NFD").replace(/[̀-ͯ]/g,"");

/* ---------- tap-or-drag tiles ---------- */
/* o={tile:'.lg-tile',slot:'.lg-slot',drop:(tileEl,slotEl)=>void}. A tile can be dragged (pointer) or tapped then a slot tapped. */
function drag(root,o){
  let sel=null,swallow=false;
  const clear=()=>{if(sel)sel.classList.remove("lg-sel");sel=null};
  root.addEventListener("click",e=>{
    if(swallow){swallow=false;return}
    const t=e.target.closest(o.tile),s=e.target.closest(o.slot);
    if(t&&root.contains(t)&&!t.classList.contains("lg-used")&&!t.disabled){if(sel===t){clear();return}clear();sel=t;t.classList.add("lg-sel");return}
    if(s&&sel){const tt=sel;clear();o.drop(tt,s)}
  });
  root.addEventListener("pointerdown",e=>{
    const t=e.target.closest(o.tile);if(!t||t.classList.contains("lg-used")||t.disabled||(e.button&&e.button!==0))return;
    const x0=e.clientX,y0=e.clientY;let g=null,moved=false;
    const mv=ev=>{
      if(!moved&&Math.hypot(ev.clientX-x0,ev.clientY-y0)<7)return;
      if(!moved){moved=true;clear();g=t.cloneNode(true);g.className+=" lg-ghost";g.removeAttribute("id");document.body.appendChild(g);t.classList.add("lg-lift")}
      g.style.left=ev.clientX-g.offsetWidth/2+"px";g.style.top=ev.clientY-g.offsetHeight/2+"px";
    };
    const up=ev=>{
      document.removeEventListener("pointermove",mv);document.removeEventListener("pointerup",up);document.removeEventListener("pointercancel",up);
      t.classList.remove("lg-lift");
      if(moved){
        swallow=true;setTimeout(()=>swallow=false,0);
        g.style.display="none";const el=document.elementFromPoint(ev.clientX,ev.clientY);g.remove();
        const s=el&&el.closest(o.slot);if(s&&root.contains(s))o.drop(t,s);
      }
    };
    document.addEventListener("pointermove",mv);document.addEventListener("pointerup",up);document.addEventListener("pointercancel",up);
  });
  return {clear};
}

/* ---------- accent / special character bar ---------- */
const ACC={fr:"é è ê ë à â ç î ï ô û ù ü œ".split(" "),es:"á é í ó ú ñ ü ¿ ¡".split(" "),de:"ä ö ü ß".split(" ")};
function accentBar(inp,lang){
  if(!inp||inp.dataset.lgBar)return;inp.dataset.lgBar="1";lang=lang||LG();
  const bar=document.createElement("div");bar.className="lg-acc";bar.setAttribute("role","group");bar.setAttribute("aria-label","Special characters");
  let up=false;const btns=[];
  const put=c=>{const s=inp.selectionStart==null?inp.value.length:inp.selectionStart,e=inp.selectionEnd==null?s:inp.selectionEnd;
    inp.value=inp.value.slice(0,s)+c+inp.value.slice(e);inp.focus();try{inp.setSelectionRange(s+c.length,s+c.length)}catch(x){}inp.dispatchEvent(new Event("input",{bubbles:true}))};
  ACC[lang].forEach(c=>{const b=document.createElement("button");b.type="button";b.textContent=c;b.setAttribute("aria-label","insert "+c);
    b.onmousedown=e=>e.preventDefault();b.onclick=()=>put(up?c.toUpperCase():c);btns.push([b,c]);bar.appendChild(b)});
  {const sh=document.createElement("button");sh.type="button";sh.textContent="⇧";sh.className="sh";sh.setAttribute("aria-label","capital letters");sh.setAttribute("aria-pressed","false");
    sh.onmousedown=e=>e.preventDefault();sh.onclick=()=>{up=!up;sh.setAttribute("aria-pressed",up);sh.classList.toggle("on",up);btns.forEach(([b,c])=>{if(/[¿¡ß]/.test(c))return;b.textContent=up?c.toUpperCase():c})};bar.appendChild(sh)}
  inp.insertAdjacentElement("afterend",bar);
}
/* auto-attach to every text input in a language lesson (quiz "type your answer", widgets) */
if(LANGS[(typeof L!=="undefined"&&L.subject)||""]){
  let q=0;const scan=()=>{q=0;document.querySelectorAll('input.txt:not([data-lg-bar]):not([data-lg-nobar]),input[type=text]:not([data-lg-bar]):not([data-lg-nobar])').forEach(i=>accentBar(i))};
  new MutationObserver(()=>{if(!q)q=requestAnimationFrame(scan)}).observe(document.body,{childList:true,subtree:true});
}

/* ---------- shared CSS ---------- */
const CSS=`<style>
.lg .lg-chips{display:flex;flex-wrap:wrap;gap:6px;align-items:center}
.lg .lg-chip{border:2px solid var(--line);background:#fff;color:var(--ink2);border-radius:99px;padding:6px 12px;font-weight:800;font-size:14px;min-height:36px}
.lg .lg-chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
.lg .lg-tile{touch-action:none;user-select:none;-webkit-user-select:none;border:2px solid var(--line);background:#fff;border-radius:12px;padding:8px 12px;font-weight:800;font-size:16px;box-shadow:0 3px 0 var(--line);cursor:grab;color:var(--ink);min-height:40px}
.lg .lg-tile.lg-sel{border-color:var(--brand2);background:var(--brand-soft);transform:translateY(-2px)}
.lg .lg-tile.lg-used{opacity:.22;pointer-events:none}.lg .lg-tile.lg-lift{opacity:.4}
.lg-ghost{position:fixed!important;z-index:90;pointer-events:none;box-shadow:0 10px 24px rgba(20,26,51,.3)!important;transform:rotate(-3deg) scale(1.06)}
.lg .lg-slot{min-width:60px;min-height:40px;border:2px dashed #b8c4ff;border-radius:10px;display:inline-flex;align-items:center;justify-content:center;background:#fff;font-weight:900;padding:0 8px;color:var(--ink);vertical-align:middle}
.lg .lg-slot.full{border-style:solid;border-color:var(--ok);background:var(--ok-soft)}
.lg .lg-stem{color:var(--brand2);font-weight:900}.lg .lg-end{color:#b45309;background:#fff1de;border-radius:6px;padding:0 3px;font-weight:900}
.lg .lg-aux{color:var(--ok);font-weight:900}
.lg .lg-bad{animation:lgshake .4s}@keyframes lgshake{25%{transform:translateX(-6px)}75%{transform:translateX(6px)}}
.lg .lg-pop{animation:lgpop .5s cubic-bezier(.3,1.5,.5,1)}@keyframes lgpop{from{transform:scale(.3);opacity:0}to{transform:scale(1);opacity:1}}
.lg .lg-spk{border:2px solid var(--line);background:#fff;border-radius:99px;min-width:38px;height:38px;font-size:16px;padding:0 10px;font-weight:800;color:var(--brand)}
.lg .lg-msg{font-size:13px;color:var(--warn);background:var(--warn-soft);border-radius:10px;padding:8px 10px;margin-top:8px}
.lg .lg-fb{min-height:24px;font-weight:800;margin-top:8px;text-align:center}
.lg .lg-ok{color:var(--ok)}.lg .lg-no{color:var(--bad)}
.lg-acc{display:flex;flex-wrap:wrap;gap:4px;margin:6px 0}.lg-acc button{min-width:34px;height:36px;border:2px solid var(--line);background:#fff;border-radius:8px;font-weight:800;font-size:16px;color:var(--ink)}
.lg-acc button.on{background:var(--brand-soft);border-color:var(--brand2)}
.lg .lg-in{width:100%;border:2px solid var(--line);border-radius:12px;padding:10px 12px;font:inherit;font-weight:700;font-size:17px;background:#fff;color:var(--ink)}
@media(prefers-reduced-motion:reduce){.lg .lg-bad,.lg .lg-pop{animation:none}}
</style>`;

/* ---------- vocab bank (small, high-frequency, verified). "target|English" ---------- */
const V=(name,s)=>({name,words:s.split(";").map(x=>{const[a,b]=x.split("|");return[a.trim(),b.trim()]})});
const VOC={
fr:[V("Greetings","bonjour|hello, good day;salut|hi, bye (informal);au revoir|goodbye;merci|thank you;s'il vous plaît|please;oui|yes;non|no;ça va ?|how are you?"),
    V("Family","la mère|mother;le père|father;la sœur|sister;le frère|brother;la grand-mère|grandmother;le grand-père|grandfather;l'oncle|uncle;la tante|aunt"),
    V("School","l'école|school;la classe|class;le professeur|teacher;le livre|book;le cahier|exercise book;le stylo|pen;la trousse|pencil case;le cartable|school bag"),
    V("Colours","rouge|red;bleu|blue;vert|green;jaune|yellow;noir|black;blanc|white;gris|grey;rose|pink"),
    V("Days","lundi|Monday;mardi|Tuesday;mercredi|Wednesday;jeudi|Thursday;vendredi|Friday;samedi|Saturday;dimanche|Sunday;aujourd'hui|today"),
    V("Food & drink","le pain|bread;le fromage|cheese;le lait|milk;le café|coffee;la pomme|apple;le gâteau|cake;le jus d'orange|orange juice;l'eau|water")],
es:[V("Greetings","hola|hello;adiós|goodbye;buenos días|good morning;buenas noches|good night;gracias|thank you;por favor|please;sí|yes;¿qué tal?|how are you?"),
    V("Family","la madre|mother;el padre|father;la hermana|sister;el hermano|brother;la abuela|grandmother;el abuelo|grandfather;el tío|uncle;la tía|aunt"),
    V("School","el colegio|school;la clase|class;el profesor|teacher;el libro|book;el cuaderno|exercise book;el bolígrafo|pen;el estuche|pencil case;la mochila|school bag"),
    V("Colours","rojo|red;azul|blue;verde|green;amarillo|yellow;negro|black;blanco|white;gris|grey;rosa|pink"),
    V("Days","lunes|Monday;martes|Tuesday;miércoles|Wednesday;jueves|Thursday;viernes|Friday;sábado|Saturday;domingo|Sunday;hoy|today"),
    V("Food & drink","el pan|bread;el queso|cheese;la leche|milk;el café|coffee;la manzana|apple;la tarta|cake;el zumo de naranja|orange juice;el helado|ice cream")],
de:[V("Greetings","Hallo|hello;Guten Morgen|good morning;Guten Tag|good day, hello;Gute Nacht|good night;Tschüss|bye;Danke|thank you;Bitte|please, you're welcome;Wie geht's?|how are you?"),
    V("Family","die Mutter|mother;der Vater|father;die Schwester|sister;der Bruder|brother;die Oma|grandma;der Opa|grandad;der Onkel|uncle;die Tante|aunt"),
    V("School","die Schule|school;die Klasse|class;der Lehrer|teacher (male);das Buch|book;das Heft|exercise book;der Kuli|pen;das Mäppchen|pencil case;die Schultasche|school bag"),
    V("Colours","rot|red;blau|blue;grün|green;gelb|yellow;schwarz|black;weiß|white;grau|grey;rosa|pink"),
    V("Days","Montag|Monday;Dienstag|Tuesday;Mittwoch|Wednesday;Donnerstag|Thursday;Freitag|Friday;Samstag|Saturday;Sonntag|Sunday;heute|today"),
    V("Food & drink","das Brot|bread;der Käse|cheese;die Milch|milk;der Kaffee|coffee;der Apfel|apple;der Kuchen|cake;der Orangensaft|orange juice;das Wasser|water")]
};

const R=(a)=>a[Math.floor(Math.random()*a.length)];
WIDGETS._accentBar=accentBar;
WIDGETS._lang={LG,VL,NAME,speak,canSpeak,norm,flat,drag,CSS,VOC,R,reduce,accentBar};
})();

  }).call(globalThis);
}
