// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langOrder.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langOrder — word-order builder: tap or drag word tiles into the sentence. French/Spanish adjective position, negation and questions; German verb-second, negation and verb-at-the-end. */
(function(){
const H=()=>WIDGETS._lang;
const I=s=>s.split(";").map(x=>{const p=x.split("|");return{en:p[1],ok:p[0].split("/")}});
const CATS={
fr:[{n:"Adjectives",tip:"Most French adjectives go AFTER the noun. A few short, common ones (grand, petit, beau, bon, nouveau, jeune, vieux) go BEFORE it.",
     items:I("J'ai un chat noir|I have a black cat;Elle habite dans une grande maison|She lives in a big house;Il a un livre intéressant|He has an interesting book;Voici une petite fille|Here is a little girl;Nous avons une voiture rouge|We have a red car;Ils ont un nouveau professeur|They have a new teacher")},
    {n:"Negation",tip:"ne goes before the verb and pas after it: je ne parle pas. Before a vowel, ne becomes n'. After pas, un/une/du/des become de: je n'ai pas de frère.",
     items:I("Je ne parle pas anglais|I don't speak English;Il n'aime pas le sport|He doesn't like sport;Elle ne joue pas au football|She doesn't play football;Nous ne mangeons pas de viande|We don't eat meat;Tu n'as pas de frère|You don't have a brother;Ils ne sont pas contents|They are not happy")},
    {n:"Questions",tip:"Est-ce que goes at the start and the rest stays in normal order. Question words (où, comment, qu'est-ce que) usually come first.",
     items:I("Est-ce que tu aimes le chocolat|Do you like chocolate?;Où est-ce que tu habites|Where do you live?;Qu'est-ce que tu fais|What are you doing?;Est-ce que vous avez un chien|Do you have a dog?;Comment est-ce qu'il s'appelle|What is he called?")}],
es:[{n:"Adjectives",tip:"Most Spanish adjectives go AFTER the noun and agree with it: un gato negro, una casa grande.",
     items:I("Tengo un gato negro|I have a black cat;Vivo en una casa grande|I live in a big house;Mi hermana tiene el pelo largo|My sister has long hair;Tenemos un perro pequeño|We have a small dog;Es una chica simpática|She is a nice girl;Compro una mochila azul|I buy a blue school bag")},
    {n:"Negation",tip:"Put no straight before the verb: no hablo. There is no second word like French pas. With gustar: no me gusta.",
     items:I("No hablo inglés|I don't speak English;Mi hermano no come pescado|My brother doesn't eat fish;No tengo hermanos|I don't have siblings;Ellas no viven aquí|They (f) don't live here;No me gusta el fútbol|I don't like football;Yo no bailo|I don't dance")},
    {n:"Questions",tip:"Spanish questions have ¿ at the start and ? at the end (not shown in the tiles). The question word comes first; the verb comes before the subject.",
     items:I("Dónde vives|Where do you live?;Cuántos años tienes|How old are you?;Cómo te llamas|What are you called?;Qué haces los sábados|What do you do on Saturdays?;Vives en Madrid|Do you live in Madrid?;Cuándo es tu cumpleaños|When is your birthday?")}],
de:[{n:"Verb 2nd",tip:"The verb is always the SECOND idea in a statement. If you start with time or place, the subject moves after the verb: Heute gehe ich … (not Heute ich gehe).",
     items:I("Ich gehe heute ins Kino/Heute gehe ich ins Kino|I go to the cinema today;Wir spielen am Samstag Fußball/Am Samstag spielen wir Fußball|We play football on Saturday;Meine Schwester wohnt jetzt in Berlin/Jetzt wohnt meine Schwester in Berlin|My sister lives in Berlin now;Ich esse in der Schule einen Apfel/In der Schule esse ich einen Apfel|I eat an apple at school;Morgen gehen wir in den Park/Wir gehen morgen in den Park|Tomorrow we are going to the park;Er liest oft Bücher/Oft liest er Bücher|He often reads books")},
    {n:"Negation",tip:"kein negates a noun with ein/no article (kein Auto, keinen Bruder). nicht negates everything else and often sits near the end, before a place or an adjective.",
     items:I("Ich habe keinen Bruder|I don't have a brother;Er kommt heute nicht|He isn't coming today;Wir gehen nicht ins Kino|We are not going to the cinema;Sie hat kein Auto|She doesn't have a car;Ich mag den Film nicht|I don't like the film;Ich mache keine Hausaufgaben|I'm not doing homework")},
    {n:"Verb at the end",tip:"After weil and dass the verb goes to the END. With a modal (kann, will, muss) or the perfect tense, the second verb (infinitive or participle) also goes to the end.",
     items:I("Ich lerne Deutsch, weil es Spaß macht|I learn German because it is fun;Ich bleibe zu Hause, weil ich müde bin|I'm staying home because I'm tired;Er sagt, dass er Hunger hat|He says that he is hungry;Ich kann heute Tennis spielen|I can play tennis today;Wir wollen morgen ins Kino gehen|We want to go to the cinema tomorrow;Sie hat gestern Fußball gespielt|She played football yesterday")}]};
const css=`<style>
#lgo .ans{min-height:58px;border:3px dashed #b8c4ff;border-radius:14px;background:#fff;padding:8px;display:flex;flex-wrap:wrap;gap:6px;align-items:center}
#lgo .ans.ok{border:3px solid var(--ok);background:var(--ok-soft)}
#lgo .pl{border:2px solid var(--brand2);background:var(--brand-soft);color:var(--brand);border-radius:10px;padding:6px 10px;font-weight:800;font-size:16px;min-height:38px}
#lgo .pl.right{border-color:var(--ok);background:var(--ok-soft);color:var(--ok)}#lgo .pl.wrong{border-color:#e8a13a;background:var(--warn-soft);color:var(--warn)}
#lgo .pool{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;padding:10px;background:#eef1ff;border-radius:12px;min-height:56px;margin-top:10px}
#lgo .en{font-weight:800;color:var(--ink2);text-align:center;margin:8px 0}
</style>`;
WIDGETS.langOrder={CATS,
 title:"Word-order workshop",
 intro:"Build the sentence: tap words (or drag them) into the box in the right order. Tap a placed word to take it back.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgo"><div class="lg-chips" id="lgo-c" style="justify-content:center"></div><div class="en" id="lgo-en"></div><div class="ans" id="lgo-a" role="button" tabindex="0" aria-label="sentence"></div>
 <div class="pool" id="lgo-p"></div><div class="lg-fb" id="lgo-fb" aria-live="polite"></div><div class="lg-msg" id="lgo-msg" hidden></div>
 <div class="row" style="justify-content:center;gap:8px;margin-top:8px"><button class="btn" id="lgo-chk">Check</button><button class="btn ghost" id="lgo-hear">🔊</button><button class="btn ghost" id="lgo-next">Next sentence</button></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),cats=CATS[lang];let ci=0,ii=0,placed=[],toks=[],done=false;const box=$("#lgo");
  const item=()=>cats[ci].items[ii%cats[ci].items.length],text=()=>placed.map(i=>toks[i]).join(" ");
  function load(){const it=item();toks=it.ok[0].split(" ");placed=[];done=false;
    let order=shuffle(toks.map((_,i)=>i));if(order.every((v,i)=>v===i))order.reverse();
    $("#lgo-c").innerHTML=cats.map((c,i)=>`<button class="lg-chip ${i===ci?"on":""}" data-ci="${i}">${esc(c.n)}</button>`).join("");
    $("#lgo-en").textContent="“"+it.en+"”";
    $("#lgo-p").innerHTML=order.map(i=>`<button class="lg-tile" data-i="${i}">${esc(toks[i])}</button>`).join("");
    $("#lgo-fb").innerHTML=`<span class="small" style="font-weight:600">${esc(cats[ci].tip)}</span>`;draw()}
  function draw(cls=[]){$("#lgo-a").className="ans"+(done?" ok":"");$("#lgo-a").innerHTML=placed.length?placed.map((i,k)=>`<button class="pl ${cls[k]||""}" data-i="${i}">${esc(toks[i])}</button>`).join(""):`<span class="small">Your sentence goes here…</span>`;
    box.querySelectorAll("#lgo-p .lg-tile").forEach(t=>{const u=placed.includes(+t.dataset.i);t.classList.toggle("lg-used",u);t.disabled=u})}
  const add=t=>{if(done)return;placed.push(+t.dataset.i);draw();$("#lgo-fb").textContent=""};
  H_.drag(box,{tile:".lg-tile",slot:".ans",tap:add,drop:add});
  $("#lgo-a").addEventListener("click",e=>{const b=e.target.closest(".pl");if(b&&!done){placed.splice(placed.indexOf(+b.dataset.i),1);draw()}});
  box.addEventListener("click",e=>{const c=e.target.closest("[data-ci]");if(c){ci=+c.dataset.ci;ii=0;load()}});
  $("#lgo-chk").onclick=()=>{
    if(done||!placed.length)return;const it=item(),mine=H_.norm(text()),hit=it.ok.find(o=>H_.norm(o)===mine);
    if(hit){done=true;draw();$("#lgo-fb").innerHTML=`<span class="lg-ok">Yes! ${esc(hit)}</span>${it.ok.length>1?`<br><span class="small">Also correct: ${esc(it.ok.filter(o=>o!==hit).join("  /  "))}</span>`:""}`;addXP(3);H_.speak(hit,{msg:$("#lgo-msg")})}
    else{const sc=a=>placed.filter((i,k)=>H_.norm(toks[i])===H_.norm(a[k]||"")).length,ref=it.ok.map(o=>o.split(" ")).sort((a,b)=>sc(b)-sc(a))[0];draw(placed.map((i,k)=>H_.norm(toks[i])===H_.norm(ref[k])?"right":"wrong"));$("#lgo-a").classList.add("lg-bad");
      $("#lgo-fb").innerHTML=`<span class="lg-no">${placed.length<toks.length?"Not finished yet — use every word.":"Not quite. Green words are already in the right place; orange ones need to move."}</span>`}
  };
  $("#lgo-hear").onclick=()=>H_.speak(done?text():item().ok[0],{msg:$("#lgo-msg")});
  $("#lgo-next").onclick=()=>{ii++;load()};load();
 }};
})();

  }).call(globalThis);
}
