// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langNegate.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langNegate — say NO: watch ne … pas / no / nicht / kein slot into a sentence. + = new word, ~ = word that changed. */
(function(){
const H=()=>WIDGETS._lang;
const S=s=>s.split(";").map(x=>{const p=x.split("|");return{p:p[0],n:p[1],en:p[2],enn:p[3],why:p[4]}});
const D={
fr:S("Je parle français|Je +ne parle +pas français|I speak French|I don't speak French|ne goes before the verb, pas goes after it.;Elle joue au tennis|Elle +ne joue +pas au tennis|She plays tennis|She doesn't play tennis|The verb is wrapped: ne + verb + pas.;Il aime le chocolat|Il ~n'aime +pas le chocolat|He likes chocolate|He doesn't like chocolate|Before a vowel sound ne becomes n'.;J'ai un frère|~Je ~n'ai +pas ~de frère|I have a brother|I don't have a brother|After pas, un / une / du / des change to de (d' before a vowel).;Nous mangeons du pain|Nous +ne mangeons +pas ~de pain|We eat bread|We don't eat bread|du becomes de after pas.;Il y a un chat|Il ~n'y a +pas ~de chat|There is a cat|There isn't a cat|il y a  →  il n'y a pas de.;Ils sont contents|Ils +ne sont +pas contents|They are happy|They are not happy|être works the same way: ne sont pas."),
es:S("Yo hablo inglés|Yo +no hablo inglés|I speak English|I don't speak English|Just put no directly before the verb.;Mi hermano come pescado|Mi hermano +no come pescado|My brother eats fish|My brother doesn't eat fish|There is no second word, unlike French pas.;Ellas viven aquí|Ellas +no viven aquí|They (f) live here|They (f) don't live here|no + verb, whoever the subject is.;A mí me gusta el fútbol|A mí +no me gusta el fútbol|I like football|I don't like football|With gustar, no goes before me: no me gusta.;Nosotros bailamos|Nosotros +no bailamos|We dance|We don't dance|no + verb again.;Yo tengo algo|Yo +no tengo ~nada|I have something|I have nothing|Spanish uses a double negative: no … nada, no … nunca."),
de:S("Ich habe einen Bruder|Ich habe ~keinen Bruder|I have a brother|I don't have a brother|kein replaces ein for nouns: einen Bruder → keinen Bruder.;Sie hat ein Auto|Sie hat ~kein Auto|She has a car|She doesn't have a car|ein Auto → kein Auto (kein takes the same endings as ein).;Ich mache Hausaufgaben|Ich mache +keine Hausaufgaben|I do homework|I'm not doing homework|No article at all? Use kein-: keine Hausaufgaben.;Er kommt heute|Er kommt heute +nicht|He comes today|He isn't coming today|nicht often goes at the end of the sentence.;Ich mag den Film|Ich mag den Film +nicht|I like the film|I don't like the film|With der / die / das nouns use nicht, not kein.;Wir gehen ins Kino|Wir gehen +nicht ins Kino|We go to the cinema|We aren't going to the cinema|nicht goes before a place or direction.;Das Wetter ist schön|Das Wetter ist +nicht schön|The weather is nice|The weather isn't nice|nicht goes before an adjective.")};
const css=`<style>
#lgn .ns{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;align-items:center;font-size:24px;font-weight:800;margin:16px 0 6px;min-height:52px}
#lgn .nw{padding:4px 8px;border-radius:10px;background:#fff;border:2px solid var(--line)}
#lgn .nw.new{background:#fff1de;border-color:#e8a13a;color:#b45309;animation:lgpop .55s cubic-bezier(.3,1.5,.5,1)}
#lgn .nw.chg{background:var(--brand-soft);border-color:var(--brand2);color:var(--brand);animation:lgflash .8s}
@keyframes lgflash{0%{transform:scale(1.25)}100%{transform:scale(1)}}
#lgn .sw{position:relative;width:96px;height:44px;border-radius:99px;border:0;background:#c5cbe3;transition:background .25s;padding:0}
#lgn .sw i{position:absolute;top:4px;left:4px;width:36px;height:36px;border-radius:50%;background:#fff;transition:transform .3s cubic-bezier(.3,1.4,.5,1);display:flex;align-items:center;justify-content:center;font-style:normal;font-size:19px}
#lgn .sw.on{background:var(--bad)}#lgn .sw.on i{transform:translateX(52px)}
#lgn .why{background:var(--warn-soft);border-radius:10px;padding:8px 12px;text-align:center;font-weight:700;color:var(--warn);min-height:38px}
@media(max-width:420px){#lgn .ns{font-size:19px;gap:6px}}
</style>`;
WIDGETS.langNegate={D,
 title:"Say it in the negative",
 intro:"Flip the switch to turn the sentence negative and watch which words move in. Orange = new word, blue = a word that changed.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgn"><div class="lg-chips" id="lgn-c" style="justify-content:center"></div>
 <div class="row" style="justify-content:center;gap:10px;margin-top:10px"><span class="small" style="font-weight:800">Positive</span><button class="sw" id="lgn-sw" role="switch" aria-checked="false" aria-label="make negative"><i>🙂</i></button><span class="small" style="font-weight:800">Negative</span></div>
 <div class="ns" id="lgn-s" aria-live="polite"></div><div class="lg-fb small" id="lgn-en" style="font-weight:600"></div><div class="why" id="lgn-w"></div><div class="lg-msg" id="lgn-msg" hidden></div>
 <div class="row" style="justify-content:center;gap:8px;margin-top:10px"><button class="btn ghost" id="lgn-hear">🔊 Hear it</button><button class="btn ghost" id="lgn-next">Next sentence</button></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),list=D[lang];let i=0,neg=false,seen=new Set();const sw=$("#lgn-sw");
  const plain=t=>t.replace(/^[+~]/,"");
  function draw(){
    const it=list[i];$("#lgn-c").innerHTML=list.map((x,k)=>`<button class="lg-chip ${k===i?"on":""}" data-k="${k}">${esc(x.p.split(" ").slice(0,3).join(" "))}…</button>`).join("");
    const toks=(neg?it.n:it.p).split(" ");
    $("#lgn-s").innerHTML=toks.map(t=>`<span class="nw ${t[0]==="+"?"new":t[0]==="~"?"chg":""}">${esc(plain(t))}</span>`).join("");
    $("#lgn-en").textContent="“"+(neg?it.enn:it.en)+"”";$("#lgn-w").textContent=neg?it.why:"Now flip the switch…";
    sw.classList.toggle("on",neg);sw.setAttribute("aria-checked",neg);sw.firstChild.textContent=neg?"🙅":"🙂";
  }
  $("#lgn-c").onclick=e=>{const b=e.target.closest("[data-k]");if(b){i=+b.dataset.k;neg=false;draw()}};
  sw.onclick=()=>{neg=!neg;draw();if(neg&&!seen.has(i)){seen.add(i);addXP(2)}};
  $("#lgn-hear").onclick=()=>H_.speak(plain(list[i][neg?"n":"p"]).split(" ").map(plain).join(" "),{msg:$("#lgn-msg")});
  $("#lgn-next").onclick=()=>{i=(i+1)%list.length;neg=false;draw()};draw();
 }};
})();

  }).call(globalThis);
}
