// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langVerbs.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langVerbs — verb table builder: pick a verb + tense, drag the endings (or forms) onto each person. Stem = blue, ending = orange.
   French / Spanish / German, from a small hand-checked table. Language comes from L.subject. */
(function(){
const H=()=>WIDGETS._lang;
const sp=s=>s.split(",");
const reg=(st,e,post="")=>sp(e).map(x=>[st,x,post]);            // stem + endings
const whole=(f,post="")=>sp(f).map(x=>["",x,post]);              // whole irregular forms
const P=s=>s.includes(":")?reg(s.split(":")[0],s.split(":")[1]):whole(s); // "parl:e,es,…" or "suis,es,…"
const aux=(a,pp)=>sp(a).map((x,i)=>["",x," "+(Array.isArray(pp)?pp[i]:pp)]);
const PRON={fr:["je","tu","il / elle","nous","vous","ils / elles"],es:["yo","tú","él / ella","nosotros","vosotros","ellos / ellas"],de:["ich","du","er / sie / es","wir","ihr","sie / Sie"]};
const TN={pres:"Present",imp:"Imperfect",perf:"Perfect",pret:"Preterite",impf:"Simple past",fut:"Going to / will",cont:"Right now (-ing)"};

/* ---- French ---- */
const FR=[];const FIMP="ais,ais,ait,ions,iez,aient",FAV="ai,as,a,avons,avez,ont",FET="suis,es,est,sommes,êtes,sont";
const fr=(inf,en,pres,imp,pp,ax)=>FR.push({inf,en,T:{pres:P(pres),imp:reg(imp,FIMP),
  perf:ax==="e"?sp(FET).map((a,i)=>["",a," "+pp+(i>2?"s":"")]):aux(FAV,pp),fut:aux("vais,vas,va,allons,allez,vont",inf)},
  note:{perf:ax==="e"?"With aller, venir, sortir the participle agrees with the subject: elle est allée, ils sont allés.":"",fut:"aller + infinitive: the infinitive never changes."}});
fr("parler","to speak","parl:e,es,e,ons,ez,ent","parl","parlé");fr("jouer","to play","jou:e,es,e,ons,ez,ent","jou","joué");
fr("aimer","to like, love","aim:e,es,e,ons,ez,ent","aim","aimé");fr("habiter","to live","habit:e,es,e,ons,ez,ent","habit","habité");
fr("finir","to finish","fin:is,is,it,issons,issez,issent","finiss","fini");fr("choisir","to choose","chois:is,is,it,issons,issez,issent","choisiss","choisi");
fr("vendre","to sell","vend:s,s,,ons,ez,ent","vend","vendu");fr("entendre","to hear","entend:s,s,,ons,ez,ent","entend","entendu");
fr("être","to be","suis,es,est,sommes,êtes,sont","ét","été");fr("avoir","to have","ai,as,a,avons,avez,ont","av","eu");
fr("aller","to go","vais,vas,va,allons,allez,vont","all","allé","e");fr("faire","to do, make","fais,fais,fait,faisons,faites,font","fais","fait");
fr("prendre","to take","prends,prends,prend,prenons,prenez,prennent","pren","pris");fr("vouloir","to want","veux,veux,veut,voulons,voulez,veulent","voul","voulu");
fr("pouvoir","to be able to","peux,peux,peut,pouvons,pouvez,peuvent","pouv","pu");fr("venir","to come","viens,viens,vient,venons,venez,viennent","ven","venu","e");
fr("sortir","to go out","sors,sors,sort,sortons,sortez,sortent","sort","sorti","e");fr("lire","to read","lis,lis,lit,lisons,lisez,lisent","lis","lu");
fr("écrire","to write","écris,écris,écrit,écrivons,écrivez,écrivent","écriv","écrit");fr("dire","to say","dis,dis,dit,disons,dites,disent","dis","dit");

/* ---- Spanish ---- */
const ES=[];const AR="o,as,a,amos,áis,an",ER="o,es,e,emos,éis,en",IR="o,es,e,imos,ís,en";
const EIMP={ar:"aba,abas,aba,ábamos,abais,aban",er:"ía,ías,ía,íamos,íais,ían"};
const EPRET={ar:"é,aste,ó,amos,asteis,aron",er:"í,iste,ió,imos,isteis,ieron"};
const ESTAR="estoy,estás,está,estamos,estáis,están",IRA="voy,vas,va,vamos,vais,van";
const es=(inf,en,pres,pret,imp,ger)=>{const t=inf.slice(-2),st=inf.slice(0,-2),k=t==="ar"?"ar":"er",T={pres:P(pres||st+":"+(t==="ar"?AR:t==="er"?ER:IR))};
  if(pret)T.pret=P(pret==="reg"?st+":"+EPRET[k]:pret);
  if(imp!=="no")T.imp=imp&&imp!=="reg"?P(imp):reg(st,EIMP[k]);
  if(ger)T.cont=aux(ESTAR,ger==="reg"?st+(t==="ar"?"ando":"iendo"):ger);
  T.fut=aux(IRA,"a "+inf);ES.push({inf,en,T,note:{cont:"estar + -ando / -iendo (the -ando / -iendo part never changes).",fut:"ir + a + infinitive."}})};
es("hablar","to speak",0,"reg","reg","reg");es("bailar","to dance",0,"reg","reg","reg");es("estudiar","to study",0,"reg","reg","reg");es("escuchar","to listen",0,"reg","reg","reg");
es("comer","to eat",0,"reg","reg","reg");es("beber","to drink",0,"reg","reg","reg");es("aprender","to learn",0,"reg","reg","reg");es("vivir","to live",0,"reg","reg","reg");
es("escribir","to write",0,"reg","reg","reg");es("abrir","to open",0,"reg","reg","reg");es("leer","to read","le:o,es,e,emos,éis,en",0,"reg","leyendo");
es("ser","to be (traits)","soy,eres,es,somos,sois,son","fui,fuiste,fue,fuimos,fuisteis,fueron","era,eras,era,éramos,erais,eran");
es("estar","to be (state, place)","estoy,estás,está,estamos,estáis,están","estuve,estuviste,estuvo,estuvimos,estuvisteis,estuvieron","reg");
es("tener","to have","tengo,tienes,tiene,tenemos,tenéis,tienen","tuve,tuviste,tuvo,tuvimos,tuvisteis,tuvieron","ten:ía,ías,ía,íamos,íais,ían","teniendo");
es("ir","to go","voy,vas,va,vamos,vais,van","fui,fuiste,fue,fuimos,fuisteis,fueron","iba,ibas,iba,íbamos,ibais,iban");
es("hacer","to do, make","hago,haces,hace,hacemos,hacéis,hacen","hice,hiciste,hizo,hicimos,hicisteis,hicieron","hac:ía,ías,ía,íamos,íais,ían","haciendo");
es("querer","to want","quiero,quieres,quiere,queremos,queréis,quieren","quise,quisiste,quiso,quisimos,quisisteis,quisieron","quer:ía,ías,ía,íamos,íais,ían");
es("poder","to be able to","puedo,puedes,puede,podemos,podéis,pueden","pude,pudiste,pudo,pudimos,pudisteis,pudieron","pod:ía,ías,ía,íamos,íais,ían");
es("jugar","to play","juego,juegas,juega,jugamos,jugáis,juegan","jug:ué,aste,ó,amos,asteis,aron","reg","jugando");
es("ver","to see","veo,ves,ve,vemos,veis,ven","vi,viste,vio,vimos,visteis,vieron","ve:ía,ías,ía,íamos,íais,ían","viendo");
es("dar","to give","doy,das,da,damos,dais,dan","di,diste,dio,dimos,disteis,dieron","d:aba,abas,aba,ábamos,abais,aban","dando");

/* ---- German ---- */
const DE=[];const HAB="habe,hast,hat,haben,habt,haben",SEI="bin,bist,ist,sind,seid,sind";
const de=(inf,en,pres,pp,ax,impf,fut=1)=>{const T={pres:P(pres)};if(pp)T.perf=aux(ax==="s"?SEI:HAB,pp);
  if(impf)T.impf=P(impf);if(fut)T.fut=aux("werde,wirst,wird,werden,werdet,werden",inf);
  DE.push({inf,en,T,note:{perf:ax==="s"?"With verbs of movement or change (gehen, fahren, sein) the helper is sein, not haben.":"Helper (haben) is 2nd; the participle goes to the end of the sentence.",fut:"werden is 2nd; the infinitive goes to the end."}})};
const W=(st,x)=>st+":"+(x==="e"?"e,est,et,en,et,en":"e,st,t,en,t,en"),WI=(st,x)=>st+":"+(x==="e"?"ete,etest,ete,eten,etet,eten":"te,test,te,ten,tet,ten");
de("machen","to make, do",W("mach"),"gemacht","h",WI("mach"));de("spielen","to play",W("spiel"),"gespielt","h",WI("spiel"));
de("wohnen","to live",W("wohn"),"gewohnt","h",WI("wohn"));de("lernen","to learn",W("lern"),"gelernt","h",WI("lern"));
de("kaufen","to buy",W("kauf"),"gekauft","h",WI("kauf"));de("arbeiten","to work",W("arbeit","e"),"gearbeitet","h",WI("arbeit","e"));
de("gehen","to go",W("geh"),"gegangen","s","ging,gingst,ging,gingen,gingt,gingen");
de("sein","to be","bin,bist,ist,sind,seid,sind","gewesen","s","war,warst,war,waren,wart,waren");
de("haben","to have","habe,hast,hat,haben,habt,haben","gehabt","h","hatte,hattest,hatte,hatten,hattet,hatten");
de("fahren","to travel, drive","fahre,fährst,fährt,fahren,fahrt,fahren","gefahren","s");de("essen","to eat","esse,isst,isst,essen,esst,essen","gegessen","h");
de("sehen","to see","sehe,siehst,sieht,sehen,seht,sehen","gesehen","h");de("lesen","to read","lese,liest,liest,lesen,lest,lesen","gelesen","h");
de("sprechen","to speak","spreche,sprichst,spricht,sprechen,sprecht,sprechen","gesprochen","h");de("nehmen","to take","nehme,nimmst,nimmt,nehmen,nehmt,nehmen","genommen","h");
de("schlafen","to sleep","schlafe,schläfst,schläft,schlafen,schlaft,schlafen","geschlafen","h");
de("können","can, to be able to","kann,kannst,kann,können,könnt,können",0,0,"konnte,konntest,konnte,konnten,konntet,konnten",0);
de("müssen","must, to have to","muss,musst,muss,müssen,müsst,müssen",0,0,"musste,musstest,musste,mussten,musstet,mussten",0);
de("wollen","to want","will,willst,will,wollen,wollt,wollen",0,0,"wollte,wolltest,wollte,wollten,wolltet,wollten",0);
de("dürfen","may, to be allowed","darf,darfst,darf,dürfen,dürft,dürfen",0,0,"durfte,durftest,durfte,durften,durftet,durften",0);
de("sollen","should","soll,sollst,soll,sollen,sollt,sollen",0,0,"sollte,solltest,sollte,sollten,solltet,sollten",0);
de("mögen","to like","mag,magst,mag,mögen,mögt,mögen",0,0,"mochte,mochtest,mochte,mochten,mochtet,mochten",0);
de("möchten","would like","möchte,möchtest,möchte,möchten,möchtet,möchten",0,0,0,0);
de("werden","to become, will","werde,wirst,wird,werden,werdet,werden",0,0,0,0);

const DATA={fr:FR,es:ES,de:DE};
const css=`<style>
#lgv .vt{display:grid;grid-template-columns:auto 1fr auto;gap:8px 10px;align-items:center;margin:12px 0}
#lgv .vp{text-align:right;font-weight:800;color:var(--ink2);font-size:15px}
#lgv .vw{font-size:20px;display:flex;align-items:center;flex-wrap:wrap}
#lgv .vw .lg-slot{margin:0 1px;font-size:19px}
#lgv .pool{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;padding:10px;border-radius:12px;background:#eef1ff;min-height:56px}
#lgv .lg-spk{visibility:hidden}#lgv .lg-spk.on{visibility:visible}
</style>`;
WIDGETS.langVerbs={DATA,
 title:"Build a verb table",
 intro:"Pick a verb and a tense. Drag each ending (or form) to the right person. Blue never changes; orange is what you choose.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgv"><div class="row" style="gap:10px;margin-bottom:8px"><label class="small" for="lgv-sel">Verb</label><select id="lgv-sel" class="lg-in" style="width:auto;padding:6px 10px;font-size:16px"></select><span class="small" id="lgv-en"></span></div>
 <div class="lg-chips" id="lgv-tn" role="group" aria-label="Tense"></div><div class="vt" id="lgv-t"></div><div class="pool" id="lgv-pool" aria-label="Endings to place"></div>
 <div class="lg-fb" id="lgv-fb" aria-live="polite"></div><div class="lg-msg" id="lgv-msg" hidden></div>
 <div class="row" style="justify-content:center;gap:8px;margin-top:8px"><button class="btn ghost" id="lgv-all">🔊 Hear all</button><button class="btn ghost" id="lgv-show">Show me</button><button class="btn ghost" id="lgv-rst">Reset</button></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),D=DATA[lang],pr=PRON[lang];const box=$("#lgv"),sel=$("#lgv-sel");
  let vi=0,tk="pres",filled=0,slow=false;const doneSet=new Set();
  sel.innerHTML=D.map((v,i)=>`<option value="${i}">${esc(v.inf)}</option>`).join("");
  const rows=()=>D[vi].T[tk];
  const elide=(r)=>lang==="fr"&&/^[aeiouhéèêâîôû]/i.test(r[0]+r[1]);
  const full=(i)=>{const r=rows()[i];return (i===0&&elide(r)?"j'":pr[i].split(" / ")[0]+" ")+r[0]+r[1]+r[2]};
  const cls=r=>r[0]?"lg-end":r[2]?"lg-aux":"lg-end";
  function draw(){
    const v=D[vi],r=rows();filled=0;$("#lgv-en").textContent=v.en;
    $("#lgv-tn").innerHTML=Object.keys(TN).filter(k=>Object.values(D).some(x=>x.T[k])).map(k=>`<button class="lg-chip ${k===tk?"on":""}" data-t="${k}" ${v.T[k]?"":"disabled"} style="${v.T[k]?"":"opacity:.35"}">${TN[k]}</button>`).join("");
    $("#lgv-t").innerHTML=r.map((x,i)=>`<div class="vp">${i===0&&elide(x)?"j'":esc(pr[i])}</div><div class="vw"><span class="lg-stem">${esc(x[0])}</span><button class="lg-slot" data-i="${i}" data-a="${esc(x[1])}" aria-label="${esc(pr[i])} slot"></button><span class="lg-stem">${esc(x[2])}</span></div><button class="lg-spk" data-say="${i}" aria-label="hear it">🔊</button>`).join("");
    const tiles=shuffle(r.map(x=>x[1]));
    $("#lgv-pool").innerHTML=tiles.map(a=>`<button class="lg-tile" data-a="${esc(a)}">${a===""?"(nothing)":esc(a)}</button>`).join("");
    $("#lgv-fb").textContent=(v.note&&v.note[tk])||"";$("#lgv-fb").className="lg-fb";
  }
  function place(slot,a,tile){slot.textContent=a===""?"∅":a;slot.classList.add("full","lg-pop");const x=rows()[+slot.dataset.i];slot.classList.add(cls(x));slot.disabled=false;slot.dataset.done="1";
    box.querySelector(`.lg-spk[data-say="${slot.dataset.i}"]`).classList.add("on");if(tile){tile.classList.add("lg-used");tile.disabled=true}
    if(++filled===6){const key=vi+tk;$("#lgv-fb").innerHTML=`<span class="lg-ok">All six — ${esc(D[vi].inf)}, ${TN[tk].toLowerCase()}. Tap 🔊 to hear any of them.</span>`;if(!doneSet.has(key)){doneSet.add(key);addXP(5)}}}
  H_.drag(box,{tile:".lg-tile",slot:".lg-slot",drop(t,s){
    if(s.dataset.done)return;
    if(t.dataset.a===s.dataset.a)place(s,t.dataset.a,t);
    else{s.classList.remove("lg-bad");void s.offsetWidth;s.classList.add("lg-bad");$("#lgv-fb").innerHTML=`<span class="lg-no">Not that one. Which ending goes with “${esc(pr[+s.dataset.i])}”?</span>`}}});
  sel.onchange=()=>{vi=+sel.value;if(!D[vi].T[tk])tk="pres";draw()};
  box.addEventListener("click",e=>{
    const c=e.target.closest(".lg-chip");if(c&&!c.disabled){tk=c.dataset.t;draw();return}
    const s=e.target.closest(".lg-spk");if(s)H_.speak(full(+s.dataset.say),{msg:$("#lgv-msg")});
  });
  $("#lgv-all").onclick=()=>{const r=rows().map((_,i)=>full(i));H_.speak(r.join(". "),{msg:$("#lgv-msg")})};
  $("#lgv-show").onclick=()=>{box.querySelectorAll(".lg-slot:not([data-done])").forEach(s=>place(s,s.dataset.a,null));box.querySelectorAll(".lg-tile").forEach(t=>{t.classList.add("lg-used");t.disabled=true})};
  $("#lgv-rst").onclick=draw;draw();
 }};
})();

  }).call(globalThis);
}
