// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langDialogue.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langDialogue — role-play dialogue stepper. Reply to the other person; the story branches on what you choose. Original short dialogues. */
(function(){
const H=()=>WIDGETS._lang;
/* node: {s: what they say, en, o:[[your reply, English, next-id]]} — an empty next-id means "that doesn't answer the question" */
const N=(s,en,o)=>({s,en,o});
const DLG={
fr:[{t:"At the café",who:"Le serveur",start:"a",n:{
 a:N("Bonjour ! Qu'est-ce que vous désirez ?","Hello! What would you like?",[["Un jus d'orange, s'il vous plaît.","An orange juice, please.","b"],["Un café, s'il vous plaît.","A coffee, please.","b"],["Je m'appelle Léa.","My name is Léa.",""]]),
 b:N("Voilà votre boisson ! Vous voulez aussi manger quelque chose ?","Here is your drink! Would you like something to eat too?",[["Oui, un croissant, s'il vous plaît.","Yes, a croissant, please.","c"],["Non, merci.","No, thank you.","d"],["J'ai douze ans.","I'm twelve.",""]]),
 c:N("Très bien. Ça fait quatre euros cinquante.","Very good. That's 4.50.",[["Voilà, quatre euros cinquante.","Here you are, 4.50.","z"],["J'aime le chocolat.","I like chocolate.",""]]),
 d:N("D'accord. Ça fait trois euros.","OK. That's 3 euros.",[["Voilà, trois euros.","Here you are, 3 euros.","z"],["Il est trois heures.","It's three o'clock.",""]]),
 z:N("Merci et bonne journée !","Thank you, have a nice day!",[["Merci, au revoir !","Thanks, goodbye!","end"]])}},
 {t:"Meeting a new friend",who:"Hugo",start:"a",n:{
 a:N("Salut ! Je m'appelle Hugo. Et toi, comment tu t'appelles ?","Hi! I'm Hugo. And you, what are you called?",[["Je m'appelle Maya.","I'm called Maya.","b"],["J'ai douze ans.","I'm twelve.",""],["Ça va bien, merci.","I'm fine, thanks.",""]]),
 b:N("Enchanté, Maya ! Tu as quel âge ?","Nice to meet you, Maya! How old are you?",[["J'ai douze ans.","I'm twelve.","c"],["J'habite à Londres.","I live in London.",""]]),
 c:N("Moi aussi, j'ai douze ans ! Tu habites où ?","Me too! Where do you live?",[["J'habite à Manchester.","I live in Manchester.","d"],["Je suis très contente.","I am very happy.",""]]),
 d:N("Super ! Tu aimes le foot ?","Great! Do you like football?",[["Oui, j'aime le foot !","Yes, I like football!","e"],["Non, je n'aime pas le foot.","No, I don't like football.","e"]]),
 e:N("D'accord ! On joue ensemble à la récré ?","OK! Shall we play together at break?",[["Oui, avec plaisir !","Yes, gladly!","end"]])}}],
es:[{t:"At the tapas bar",who:"El camarero",start:"a",n:{
 a:N("¡Buenas tardes! ¿Qué quieres tomar?","Good afternoon! What would you like to drink?",[["Un zumo de naranja, por favor.","An orange juice, please.","b"],["Una limonada, por favor.","A lemonade, please.","b"],["Me llamo Pablo.","My name is Pablo.",""]]),
 b:N("Muy bien. ¿Quieres algo de comer?","Very good. Would you like something to eat?",[["Sí, una tortilla, por favor.","Yes, a tortilla, please.","c"],["No, gracias.","No, thank you.","d"],["Tengo doce años.","I'm twelve.",""]]),
 c:N("Una tortilla y una bebida. Son cinco euros.","A tortilla and a drink. That's five euros.",[["Aquí tienes. Gracias.","Here you are. Thanks.","z"],["Vivo en Londres.","I live in London.",""]]),
 d:N("Solo la bebida. Son dos euros.","Just the drink. That's two euros.",[["Aquí tienes. Gracias.","Here you are. Thanks.","z"],["Me gusta el fútbol.","I like football.",""]]),
 z:N("¡Gracias a ti! ¡Hasta luego!","Thank you! See you later!",[["¡Adiós!","Goodbye!","end"]])}},
 {t:"Asking the way",who:"Una señora",start:"a",n:{
 a:N("¡Hola! ¿Necesitas ayuda?","Hello! Do you need help?",[["Sí, ¿dónde está el parque, por favor?","Yes, where is the park, please?","b"],["Tengo un gato.","I have a cat.",""]]),
 b:N("El parque está al final de la calle, a la derecha.","The park is at the end of the street, on the right.",[["¿Está lejos?","Is it far?","c"],["Muchas gracias. ¡Adiós!","Thank you very much. Goodbye!","end"],["Me gusta el helado.","I like ice cream.",""]]),
 c:N("No, está cerca. Está a cinco minutos.","No, it's close. It's five minutes away.",[["Muchas gracias. ¡Adiós!","Thank you very much. Goodbye!","end"],["Soy alto.","I am tall.",""]])}}],
de:[{t:"At the bakery",who:"Die Bäckerin",start:"a",n:{
 a:N("Guten Morgen! Was möchten Sie?","Good morning! What would you like?",[["Ich möchte zwei Brötchen, bitte.","I'd like two bread rolls, please.","b"],["Ich möchte ein Brot, bitte.","I'd like a loaf of bread, please.","b"],["Ich heiße Anna.","My name is Anna.",""]]),
 b:N("Gerne! Sonst noch etwas?","Gladly! Anything else?",[["Nein, danke. Das ist alles.","No, thanks. That's all.","c"],["Ja, einen Apfelkuchen, bitte.","Yes, an apple cake, please.","c"],["Ich wohne in Berlin.","I live in Berlin.",""]]),
 c:N("Das macht vier Euro fünfzig.","That comes to four euros fifty.",[["Bitte schön.","Here you are.","z"],["Ich bin zwölf Jahre alt.","I'm twelve years old.",""]]),
 z:N("Danke schön! Auf Wiedersehen!","Thank you! Goodbye!",[["Tschüss!","Bye!","end"]])}},
 {t:"A new classmate",who:"Jonas",start:"a",n:{
 a:N("Hallo! Ich bin Jonas. Wie heißt du?","Hello! I'm Jonas. What's your name?",[["Ich heiße Lea.","I'm called Lea.","b"],["Ich bin zwölf Jahre alt.","I'm twelve years old.",""]]),
 b:N("Freut mich, Lea! Wie alt bist du?","Nice to meet you, Lea! How old are you?",[["Ich bin zwölf.","I'm twelve.","c"],["Ich komme aus England.","I come from England.",""]]),
 c:N("Und woher kommst du?","And where do you come from?",[["Ich komme aus England.","I come from England.","d"],["Ich habe einen Hund.","I have a dog.",""]]),
 d:N("Toll! Hast du Geschwister?","Great! Do you have brothers or sisters?",[["Ja, ich habe eine Schwester.","Yes, I have a sister.","e"],["Nein, ich habe keine Geschwister.","No, I have no siblings.","e"]]),
 e:N("Cool! Wollen wir zusammen Fußball spielen?","Cool! Shall we play football together?",[["Ja, gerne!","Yes, gladly!","end"]])}}]};
const END={fr:"Bravo ! Dialogue terminé.",es:"¡Muy bien! Diálogo terminado.",de:"Sehr gut! Dialog beendet."};
const css=`<style>
#lgd .chat{display:flex;flex-direction:column;gap:8px;margin:12px 0;max-height:340px;overflow:auto;padding:4px}
#lgd .b{max-width:86%;padding:8px 12px;border-radius:16px;font-weight:700;font-size:16px;animation:lgpop .35s}
#lgd .b.n{background:#fff;border:2px solid var(--line);align-self:flex-start;border-bottom-left-radius:4px}
#lgd .b.me{background:var(--brand-soft);border:2px solid var(--brand2);color:var(--brand);align-self:flex-end;border-bottom-right-radius:4px}
#lgd .b small{display:block;font-weight:600;color:var(--ink3);font-size:12.5px}
#lgd .who{font-size:11px;font-weight:900;text-transform:uppercase;color:var(--ink3);letter-spacing:.05em}
#lgd .ch{display:grid;gap:8px}#lgd .ch button{text-align:left;border:2px solid var(--line);background:#fff;border-radius:12px;padding:10px 12px;font-weight:800;font-size:16px;color:var(--ink)}
#lgd .ch button small{display:block;font-weight:600;color:var(--ink3);font-size:12.5px}
</style>`;
WIDGETS.langDialogue={DLG,
 title:"Role-play: choose your reply",
 intro:"You are in the conversation. Read (or listen to) what the other person says, then choose the reply that makes sense.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgd"><div class="lg-chips" id="lgd-t" style="justify-content:center"></div><div class="row" style="justify-content:center;margin-top:8px"><label class="switch"><input type="checkbox" id="lgd-en"> Show English</label></div>
 <div class="chat" id="lgd-c" aria-live="polite"></div><div class="ch" id="lgd-o"></div><div class="lg-fb" id="lgd-fb"></div><div class="lg-msg" id="lgd-msg" hidden></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),list=DLG[lang];let di=0,cur,mistakes=0,en=false,log=[];
  const box=$("#lgd");
  function bubble(kind,txt,tr,who){return `<div class="b ${kind}">${who?`<div class="who">${esc(who)}</div>`:""}${esc(txt)}${kind==="n"?` <button class="lg-spk" data-say="${esc(txt)}" style="height:28px;min-width:30px;font-size:13px;padding:0 6px" aria-label="hear it">🔊</button>`:""}<small ${en?"":"hidden"}>${esc(tr)}</small></div>`}
  function start(){const d=list[di];cur=d.start;mistakes=0;log=[];$("#lgd-t").innerHTML=list.map((x,i)=>`<button class="lg-chip ${i===di?"on":""}" data-d="${i}">${esc(x.t)}</button>`).join("");$("#lgd-c").innerHTML="";$("#lgd-fb").textContent="";turn()}
  function turn(){
    const d=list[di],n=d.n[cur];$("#lgd-c").insertAdjacentHTML("beforeend",bubble("n",n.s,n.en,d.who));const c=$("#lgd-c");c.scrollTop=c.scrollHeight;
    $("#lgd-o").innerHTML=shuffle(n.o).map(o=>`<button data-to="${o[2]}" data-t="${esc(o[0])}" data-en="${esc(o[1])}">${esc(o[0])}<small ${en?"":"hidden"}>${esc(o[1])}</small></button>`).join("");
  }
  box.addEventListener("click",e=>{
    const t=e.target.closest("[data-d]"),s=e.target.closest("[data-say]"),o=e.target.closest("#lgd-o button");
    if(t){di=+t.dataset.d;start()}else if(s)H_.speak(s.dataset.say,{msg:$("#lgd-msg")});
    else if(o){
      if(!o.dataset.to){mistakes++;o.classList.add("lg-bad");$("#lgd-fb").innerHTML=`<span class="lg-no">Hmm — that doesn't answer the question. Read it again.</span>`;setTimeout(()=>o.classList.remove("lg-bad"),450);return}
      $("#lgd-fb").textContent="";$("#lgd-c").insertAdjacentHTML("beforeend",bubble("me",o.dataset.t,o.dataset.en));cur=o.dataset.to;
      if(cur==="end"){$("#lgd-o").innerHTML=`<button class="btn" id="lgd-again" style="text-align:center">↻ Play again (try different replies)</button>`;$("#lgd-fb").innerHTML=`<span class="lg-ok">${esc(END[lang])}${mistakes?` (${mistakes} wrong turn${mistakes>1?"s":""})`:""}</span>`;addXP(mistakes?4:6);const c=$("#lgd-c");c.scrollTop=c.scrollHeight;return}
      setTimeout(turn,350);$("#lgd-o").innerHTML="";
    }else if(e.target.closest("#lgd-again"))start();
  });
  $("#lgd-en").onchange=e=>{en=e.target.checked;box.querySelectorAll(".b small,#lgd-o small").forEach(x=>x.hidden=!en)};
  start();
 }};
})();

  }).call(globalThis);
}
