// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langListen.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langListen — listen and pick / listen and type. Uses the browser's speech voice; without one it falls back to "meaning → word". */
(function(){
const H=()=>WIDGETS._lang;
const css=`<style>
#lgl .pick{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}
#lgl .pick button{border:2px solid var(--line);background:#fff;border-radius:12px;padding:12px 8px;font-weight:800;font-size:17px;color:var(--ink);min-height:52px}
#lgl .pick button.ok{background:var(--ok-soft);border-color:var(--ok);color:var(--ok)}#lgl .pick button.no{background:var(--bad-soft);border-color:var(--bad);color:var(--bad)}
#lgl .say{display:flex;align-items:center;justify-content:center;gap:10px;margin:12px 0;font-size:20px;font-weight:800;min-height:56px;flex-wrap:wrap}
#lgl .big{width:64px;height:64px;font-size:26px;border-radius:50%}
#lgl .dots{display:flex;gap:5px;justify-content:center}#lgl .dots i{width:12px;height:12px;border-radius:50%;background:var(--line)}#lgl .dots i.ok{background:var(--ok)}#lgl .dots i.no{background:var(--bad)}#lgl .dots i.cur{outline:2px solid var(--brand2)}
</style>`;
const strip=s=>s.replace(/^(le |la |l'|les |el |un |una |une |der |die |das |ein |eine )/,"");
WIDGETS.langListen={
 title:"Listen, then pick or type",
 intro:"Press the speaker and listen closely. Pick the word you heard, or switch to typing it — the special-letter keys are there to help.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgl"><div class="lg-chips" id="lgl-t" style="justify-content:center"></div><div class="lg-chips" id="lgl-m" style="justify-content:center;margin-top:6px"></div>
 <div class="say" id="lgl-say"></div><div id="lgl-body"></div><div class="lg-fb" id="lgl-fb" aria-live="polite"></div><div class="lg-msg" id="lgl-msg" hidden></div><div class="dots" id="lgl-d"></div>
 <div class="row" style="justify-content:center;gap:8px;margin-top:10px"><button class="btn ghost" id="lgl-n">Next word →</button></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),V=H_.VOC[lang];let ti=0,mode="pick",slow=false,noAudio=!H_.canSpeak(lang),qs=[],qi=0,cur=null,res=[],answered=false;
  function start(auto){const pool=V[ti].words;qs=shuffle(pool).slice(0,6);qi=0;res=[];ask(auto)}
  function chips(){$("#lgl-t").innerHTML=V.map((t,i)=>`<button class="lg-chip ${i===ti?"on":""}" data-t="${i}">${esc(t.name)}</button>`).join("");
    $("#lgl-m").innerHTML=[["pick","Pick it"],["type","Type it"]].map(([k,t])=>`<button class="lg-chip ${mode===k?"on":""}" data-m="${k}">${t}</button>`).join("")+`<button class="lg-chip ${slow?"on":""}" data-s="1">🐢 Slow</button>`}
  function say(){if(!cur)return;if(!H_.speak(cur[0],{slow,msg:$("#lgl-msg")}))noAudio=true}
  function ask(auto=true){
    chips();answered=false;$("#lgl-fb").textContent="";
    $("#lgl-d").innerHTML=qs.map((_,i)=>`<i class="${res[i]||""} ${i===qi?"cur":""}"></i>`).join("");
    if(qi>=qs.length){const ok=res.filter(r=>r==="ok").length;cur=null;$("#lgl-say").textContent=`${ok} / ${qs.length}`;$("#lgl-body").innerHTML="";$("#lgl-fb").innerHTML=`<span class="${ok>=5?"lg-ok":""}">${ok>=5?"Brilliant listening!":"Good practice — try another round."}</span>`;if(ok>=5)addXP(6);$("#lgl-n").textContent="Play again ↻";return}
    $("#lgl-n").textContent="Skip →";cur=qs[qi];
    if(!noAudio&&auto)say();
    $("#lgl-say").innerHTML=noAudio?`<span>How do you say “${esc(cur[1])}”?</span>`:`<button class="lg-spk big" id="lgl-p" aria-label="play the word">🔊</button><button class="lg-spk" id="lgl-e" title="show the English">?</button><span id="lgl-en" class="small"></span>`;
    if(mode==="pick"){const opts=shuffle([cur,...shuffle(V[ti].words.filter(w=>w!==cur)).slice(0,3)]);
      $("#lgl-body").innerHTML=`<div class="pick">${opts.map(o=>`<button data-w="${esc(o[0])}">${esc(o[0])}</button>`).join("")}</div>`}
    else{$("#lgl-body").innerHTML=`<div class="row" style="gap:8px;flex-wrap:nowrap"><input class="lg-in" id="lgl-i" type="text" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="type what you hear"><button class="btn" id="lgl-c">Check</button></div>`;
      H_.accentBar($("#lgl-i"));$("#lgl-i").onkeydown=e=>{if(e.key==="Enter")check($("#lgl-i").value)};$("#lgl-c").onclick=()=>check($("#lgl-i").value)}
    if(noAudio&&$("#lgl-msg").hidden)H_.speak("",{msg:$("#lgl-msg")});
  }
  function done(ok,msg){answered=true;res[qi]=ok?"ok":"no";if(ok){addXP(2)}$("#lgl-fb").innerHTML=msg;$("#lgl-d").querySelectorAll("i")[qi].className=res[qi];$("#lgl-n").textContent=qi+1>=qs.length?"See score →":"Next word →";if(!noAudio)say()}
  function check(v){if(answered||!v.trim())return;const a=H_.norm(cur[0]),b=H_.norm(v);
    if(b===a||b===strip(a))done(true,`<span class="lg-ok">Yes — ${esc(cur[0])} (${esc(cur[1])})</span>`);
    else if(H_.flat(v)===H_.flat(cur[0])||H_.flat(strip(a))===H_.flat(v))done(false,`<span class="lg-no">Right word, but check the accents: ${esc(cur[0])}</span>`);
    else done(false,`<span class="lg-no">It was ${esc(cur[0])} (${esc(cur[1])}).</span>`)}
  $("#lgl").addEventListener("click",e=>{
    const t=e.target.closest("[data-t]"),m=e.target.closest("[data-m]"),s=e.target.closest("[data-s]"),w=e.target.closest("[data-w]");
    if(t){ti=+t.dataset.t;start(true)}else if(m){mode=m.dataset.m;ask()}else if(s){slow=!slow;chips()}
    else if(e.target.closest("#lgl-p"))say();else if(e.target.closest("#lgl-e"))$("#lgl-en").textContent=cur[1];
    else if(w&&!answered){const ok=w.dataset.w===cur[0];w.classList.add(ok?"ok":"no");if(!ok)$("#lgl-body").querySelectorAll("button").forEach(b=>{if(b.dataset.w===cur[0])b.classList.add("ok")});done(ok,ok?`<span class="lg-ok">Yes — ${esc(cur[0])} (${esc(cur[1])})</span>`:`<span class="lg-no">It was ${esc(cur[0])} (${esc(cur[1])}).</span>`)}
  });
  $("#lgl-n").onclick=()=>{if(qi>=qs.length){start();return}if(!answered)res[qi]="no";qi++;ask()};
  start(false);
 }};
})();

  }).call(globalThis);
}
