// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langFlash.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langFlash — flip-and-hear vocab cards. Tap the card to flip, hear the word, then say "Got it" or "Again". */
(function(){
const H=()=>WIDGETS._lang;
const css=`<style>
#lgf .fc{display:block;width:100%;max-width:340px;height:170px;margin:12px auto;perspective:900px;border:0;background:none;padding:0;cursor:pointer}
#lgf .fi{position:relative;width:100%;height:100%;transition:transform .55s cubic-bezier(.3,.8,.3,1);transform-style:preserve-3d}
#lgf .fc.flip .fi{transform:rotateY(180deg)}
#lgf .fa,#lgf .fb{position:absolute;inset:0;backface-visibility:hidden;-webkit-backface-visibility:hidden;border-radius:18px;display:flex;flex-direction:column;align-items:center;justify-content:center;font-weight:900;font-size:30px;text-align:center;padding:10px;border:3px solid var(--line);box-shadow:0 6px 0 var(--line)}
#lgf .fa{background:#fff;color:var(--ink)}#lgf .fb{background:var(--brand-soft);color:var(--brand);transform:rotateY(180deg);border-color:var(--brand2);box-shadow:0 6px 0 #b8c4ff}
#lgf .fa small,#lgf .fb small{font-size:12px;font-weight:700;color:var(--ink3);margin-top:8px}
#lgf .m{color:#3b5bdb}#lgf .f{color:#c2255c}#lgf .n{color:#2f9e44}
#lgf .bar{height:10px;border-radius:99px;background:var(--line);overflow:hidden;max-width:340px;margin:6px auto}#lgf .bar i{display:block;height:100%;background:linear-gradient(90deg,var(--brand2),var(--ok));transition:width .4s}
</style>`;
const GEN={fr:{m:/^(le|un) /,f:/^(la|une) /},es:{m:/^(el|un) /,f:/^(la|una) /},de:{m:/^der /,f:/^die /,n:/^das /}};
WIDGETS.langFlash={
 title:"Flip, hear, remember",
 intro:"Say the word out loud, tap the card to check, and hear it. Words you miss come round again. Colours show the gender: blue masculine, pink feminine, green neuter.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgf"><div class="lg-chips" id="lgf-t" style="justify-content:center"></div>
 <button class="fc" id="lgf-c" aria-label="flashcard, tap to flip"><div class="fi"><div class="fa"><span id="lgf-w"></span><small>tap to flip</small></div><div class="fb"><span id="lgf-e"></span></div></div></button>
 <div class="bar"><i id="lgf-b" style="width:0"></i></div><div class="lg-fb small" id="lgf-p"></div><div class="lg-msg" id="lgf-msg" hidden></div>
 <div class="row" style="justify-content:center;gap:8px"><button class="btn ghost" id="lgf-h">🔊 Hear it</button><button class="btn ghost" id="lgf-s">🐢 Slowly</button></div>
 <div class="row" style="justify-content:center;gap:8px;margin-top:10px"><button class="btn ghost" id="lgf-a">↻ Again</button><button class="btn ok" id="lgf-g">✓ Got it</button></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),V=H_.VOC[lang];let ti=0,q=[],known=0,total=0,cur=null,flipped=false;
  const card=$("#lgf-c");
  const gcls=w=>{const g=GEN[lang];for(const k in g)if(g[k].test(w))return k;return""};
  function deck(){const w=V[ti].words;q=shuffle(w.map((x,i)=>i));known=0;total=q.length;$("#lgf-t").innerHTML=V.map((t,i)=>`<button class="lg-chip ${i===ti?"on":""}" data-t="${i}">${esc(t.name)}</button>`).join("");next()}
  function next(){
    card.classList.remove("flip");flipped=false;$("#lgf-b").style.width=known/total*100+"%";
    if(!q.length){$("#lgf-w").textContent="🎉";$("#lgf-e").textContent="";$("#lgf-p").innerHTML=`<span class="lg-ok">All ${total} known! Pick another topic.</span>`;cur=null;return}
    cur=V[ti].words[q[0]];$("#lgf-w").innerHTML=`<span class="${gcls(cur[0])}">${esc(cur[0])}</span>`;$("#lgf-e").textContent=cur[1];$("#lgf-p").textContent=`${known} / ${total} known`;
  }
  const flip=()=>{if(!cur)return;flipped=!flipped;card.classList.toggle("flip",flipped);if(flipped)H_.speak(cur[0],{msg:$("#lgf-msg")})};
  card.onclick=flip;
  $("#lgf-h").onclick=()=>cur&&H_.speak(cur[0],{msg:$("#lgf-msg")});$("#lgf-s").onclick=()=>cur&&H_.speak(cur[0],{slow:true,msg:$("#lgf-msg")});
  $("#lgf-g").onclick=()=>{if(!cur)return;q.shift();known++;if(!q.length)addXP(6);next()};
  $("#lgf-a").onclick=()=>{if(!cur)return;q.push(q.shift());next()};
  $("#lgf-t").onclick=e=>{const b=e.target.closest("[data-t]");if(b){ti=+b.dataset.t;deck()}};
  deck();
 }};
})();

  }).call(globalThis);
}
