// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/langGender.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* langGender — sort nouns into their gender boxes (le/la, el/la, der/die/das), switch to "a/an" articles (and to the accusative in German). */
(function(){
const H=()=>WIDGETS._lang;
const B=s=>s.split(";").map(x=>{const[a,b,c]=x.split("|");return{n:a,en:b,g:c}});
const BANK={
fr:B("livre|book|m;stylo|pen|m;chat|cat|m;chien|dog|m;garçon|boy|m;frère|brother|m;sac|bag|m;cahier|exercise book|m;père|father|m;fromage|cheese|m;table|table|f;chaise|chair|f;porte|door|f;fenêtre|window|f;fille|girl|f;sœur|sister|f;maison|house|f;trousse|pencil case|f;souris|mouse|f;voiture|car|f;mère|mother|f;pomme|apple|f"),
es:B("libro|book|m;lápiz|pencil|m;gato|cat|m;perro|dog|m;chico|boy|m;hermano|brother|m;bolígrafo|pen|m;ordenador|computer|m;cuaderno|exercise book|m;padre|father|m;día*|day|m;mapa*|map|m;mesa|table|f;silla|chair|f;puerta|door|f;ventana|window|f;chica|girl|f;hermana|sister|f;casa|house|f;mochila|school bag|f;escuela|school|f;ciudad|city|f;mano*|hand|f;madre|mother|f"),
de:B("Tisch|table|m;Hund|dog|m;Stuhl|chair|m;Bruder|brother|m;Lehrer|teacher|m;Apfel|apple|m;Kuli|pen|m;Bleistift|pencil|m;Vater|father|m;Tür|door|f;Katze|cat|f;Schule|school|f;Schwester|sister|f;Mutter|mother|f;Lampe|lamp|f;Tasche|bag|f;Lehrerin|teacher (f)|f;Banane|banana|f;Buch|book|n;Haus|house|n;Auto|car|n;Mädchen*|girl|n;Fenster|window|n;Heft|exercise book|n;Kind|child|n;Zimmer|room|n;Handy|mobile phone|n")};
/* articles: [definite, indefinite] per gender. German accusative: masculine der→den, ein→einen (others unchanged). */
const ART={fr:{m:["le","un"],f:["la","une"]},es:{m:["el","un"],f:["la","una"]},de:{m:["der","ein"],f:["die","eine"],n:["das","ein"]}};
const TIP={fr:"Endings help but are not perfect: -tion and -té are nearly always feminine (la nation, la liberté); -ment and -age are usually masculine (le moment, le voyage).",
 es:"Rule of thumb: nouns ending in -o are usually el, ending in -a usually la. Watch out for the ★ ones: el día, el mapa, la mano. And -ción is always la (la canción).",
 de:"Learn every noun with its article! Clues: -ung, -heit, -keit, -schaft are die; -chen and -lein are das (das Mädchen); many -er words for people are der."};
const css=`<style>
#lgg .gb{display:grid;gap:10px;margin:10px 0}#lgg .gb.n3{grid-template-columns:repeat(3,1fr)}#lgg .gb.n2{grid-template-columns:repeat(2,1fr)}
#lgg .gbox{border:3px dashed var(--c);border-radius:14px;background:#fff;padding:8px;min-height:130px;text-align:center}
#lgg .gbox h4{margin:0 0 6px;font-size:22px;color:var(--c)}
#lgg .gm{--c:#3b5bdb}#lgg .gf{--c:#c2255c}#lgg .gn{--c:#2f9e44}
#lgg .gbox.hit{background:color-mix(in srgb,var(--c) 8%,#fff)}
#lgg .gi{display:block;margin:3px 0;font-weight:800;font-size:15px;color:var(--c);animation:lgpop .4s}
#lgg .gi small{color:var(--ink3);font-weight:600}
#lgg .pool{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;padding:10px;background:#eef1ff;border-radius:12px;min-height:60px}
#lgg .lg-tile small{display:block;font-size:11px;color:var(--ink3);font-weight:600;line-height:1.1}
@media(max-width:420px){#lgg .gbox h4{font-size:18px}#lgg .gi{font-size:13px}#lgg .gbox{padding:6px}}
</style>`;
WIDGETS.langGender={BANK,
 title:"Gender sorter",
 intro:"Every noun has a gender. Drag (or tap, then tap a box) each noun to the box where it belongs.",
 html(){return H().CSS+css+`<div class="explore lg" id="lgg"><div class="lg-chips" id="lgg-opt"></div><div class="gb" id="lgg-boxes"></div><div class="pool" id="lgg-pool"></div>
 <div class="lg-fb" id="lgg-fb" aria-live="polite"></div><div class="lg-msg" id="lgg-msg" hidden></div><div class="row" style="justify-content:center;gap:8px;margin-top:8px"><button class="btn ghost" id="lgg-new">New round</button></div></div>`},
 init(){
  const H_=H(),lang=H_.LG(),bank=BANK[lang],genders=Object.keys(ART[lang]),box=$("#lgg");
  let art=0,acc=false,round=[],placed=0,mistakes=0;
  const label=(g)=>{let a=ART[lang][g][art];if(lang==="de"&&acc&&g==="m")a=art?"einen":"den";return a};
  const shown=(w)=>w.n.replace("*","");
  function opts(){ $("#lgg-opt").innerHTML=[["the",0],["a / an",1]].map(([t,i])=>`<button class="lg-chip ${art===i?"on":""}" data-art="${i}">${t}</button>`).join("")+
    (lang==="de"?`<span style="width:10px"></span>${[["as subject",0],["as object (accusative)",1]].map(([t,i])=>`<button class="lg-chip ${(+acc)===i?"on":""}" data-acc="${i}">${t}</button>`).join("")}`:""); }
  function heads(){ $("#lgg-boxes").innerHTML=genders.map(g=>`<div class="gbox g${g}" data-g="${g}" role="button" tabindex="0" aria-label="${label(g)} box"><h4>${label(g)}</h4><div class="items"></div></div>`).join("");$("#lgg-boxes").className="gb n"+genders.length;}
  function newRound(){
    const per=Math.ceil(9/genders.length);let pick=[];
    for(const g of genders)pick.push(...shuffle(bank.filter(w=>w.g===g)).slice(0,per));
    round=shuffle(pick).slice(0,9);placed=0;mistakes=0;opts();heads();
    $("#lgg-pool").innerHTML=round.map((w,i)=>`<button class="lg-tile" data-i="${i}">${esc(shown(w))}<small>${esc(w.en)}</small></button>`).join("");
    $("#lgg-fb").textContent="";
  }
  H_.drag(box,{tile:".lg-tile",slot:".gbox",drop(t,s){
    const w=round[+t.dataset.i];
    if(w.g===s.dataset.g){
      t.classList.add("lg-used");t.disabled=true;const it=document.createElement("span");it.className="gi";
      it.innerHTML=`${esc(label(w.g))} ${esc(shown(w))}${w.n.includes("*")?" ★":""}`;s.querySelector(".items").appendChild(it);
      if(++placed===round.length){$("#lgg-fb").innerHTML=`<span class="lg-ok">${mistakes?`All sorted (${mistakes} slip${mistakes>1?"s":""}).`:"All sorted, first time!"}</span> ${esc(TIP[lang])}`;addXP(mistakes?4:8)}
    }else{mistakes++;s.classList.remove("lg-bad");void s.offsetWidth;s.classList.add("lg-bad");
      $("#lgg-fb").innerHTML=`<span class="lg-no">Not this box for “${esc(shown(w))}”. Try another!</span>`}
  }});
  box.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.classList.contains("gbox")){e.preventDefault();e.target.click()}});
  box.addEventListener("click",e=>{
    const a=e.target.closest("[data-art]"),c=e.target.closest("[data-acc]");
    if(a){art=+a.dataset.art;opts();heads();rehome();}
    if(c){acc=!!+c.dataset.acc;opts();heads();rehome();}
  });
  /* after switching article type keep progress: re-list placed nouns */
  function rehome(){round.forEach((w,i)=>{const t=$(`.lg-tile[data-i="${i}"]`);if(t&&t.classList.contains("lg-used")){const it=document.createElement("span");it.className="gi";it.innerHTML=`${esc(label(w.g))} ${esc(shown(w))}${w.n.includes("*")?" ★":""}`;$(`.gbox[data-g="${w.g}"] .items`).appendChild(it)}})}
  $("#lgg-new").onclick=newRound;newRound();
 }};
})();

  }).call(globalThis);
}
