// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/linearGraph.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* linearGraph — y = mx + c: drag the y-intercept and the slope handle (or use the sliders); gradient triangle, table of values and equation update live */
(function(){
  const N=8, C=20, O=180, X=x=>O+x*C, Y=y=>O-y*C, sg=v=>v<0?"−":"+";
  const eq=(m,c)=>{ let t="y = "; const ma=Math.abs(m); t+=m===0?"":(m<0?"−":"")+(ma===1?"":ma)+"x"; if(m===0) return t+c; return t+(c===0?"":" "+sg(c)+" "+Math.abs(c)); };
  WIDGETS.linearGraph={title:"Straight-line graphs: y = mx + c",intro:"Drag the orange dot to change c (where the line crosses the y-axis) and the blue dot to change m (how steep it is). What do you notice?",
  html(){ return `<div class="explore" id="lgw"><svg id="lgs" viewBox="0 0 360 360" role="img" aria-label="Graph of y = mx + c" style="touch-action:none;max-width:420px;margin:0 auto;user-select:none"><defs><clipPath id="lgclip"><rect x="${X(-N)}" y="${Y(N)}" width="${2*N*C}" height="${2*N*C}"/></clipPath></defs><rect x="8" y="8" width="344" height="344" rx="14" fill="#fff" stroke="#cfd8ff"/><g id="lgg"></g><g id="lgd" clip-path="url(#lgclip)"></g><g id="lgh"></g></svg>
    <div style="text-align:center;margin:8px 0 2px"><span class="big" id="lgeq" style="font-size:34px"></span></div>
    <div class="row" style="margin:6px 0"><label class="small" style="flex:1;min-width:140px"><b style="color:#3b5bdb">m (gradient)</b> <span class="stat" id="lgmv"></span><input type="range" id="lgm" min="-8" max="8" step="1" value="4" style="width:100%;accent-color:#3b5bdb"></label>
    <label class="small" style="flex:1;min-width:140px"><b style="color:#c2410c">c (y-intercept)</b> <span class="stat" id="lgcv"></span><input type="range" id="lgc" min="-6" max="6" step="1" value="1" style="width:100%;accent-color:#ff5a3c"></label></div>
    <div class="row spread"><span class="small" id="lgsay" style="flex:1;min-width:200px"></span><label class="switch"><input type="checkbox" id="lgref"> Show y = x</label></div>
    <div style="overflow-x:auto;margin-top:8px"><table id="lgt" style="border-collapse:collapse;font-weight:800;font-size:14px;margin:0 auto"></table></div></div>`; },
  init(){
    let m=2, c=1, drag="", hx=3; const svg=$("#lgs"); let g="";
    for(let i=-N;i<=N;i++){ const s=i?"#e3e8fb":"#141a33", w=i?1:2; g+=`<line x1="${X(i)}" y1="${Y(-N)}" x2="${X(i)}" y2="${Y(N)}" stroke="${s}" stroke-width="${w}"/><line x1="${X(-N)}" y1="${Y(i)}" x2="${X(N)}" y2="${Y(i)}" stroke="${s}" stroke-width="${w}"/>`;
      if(i&&i%2===0) g+=`<text x="${X(i)}" y="${Y(0)+13}" font-size="10" font-weight="800" text-anchor="middle" fill="#7b83a3">${i}</text><text x="${X(0)-5}" y="${Y(i)+3.5}" font-size="10" font-weight="800" text-anchor="end" fill="#7b83a3">${i}</text>`; }
    $("#lgg").innerHTML=g+`<text x="${X(N)}" y="${Y(0)-6}" font-size="12" font-weight="900" fill="#3b5bdb" text-anchor="end">x</text><text x="${X(0)+8}" y="${Y(N)+12}" font-size="12" font-weight="900" fill="#3b5bdb">y</text>`;
    const draw=()=>{ let h="";
      if($("#lgref").checked) h+=`<line x1="${X(-N)}" y1="${Y(-N)}" x2="${X(N)}" y2="${Y(N)}" stroke="#7b83a3" stroke-width="2" stroke-dasharray="6 5"/>`;
      h+=`<line x1="${X(-N)}" y1="${Y(m*-N+c)}" x2="${X(N)}" y2="${Y(m*N+c)}" stroke="#3b5bdb" stroke-width="4" stroke-linecap="round"/>`;
      // gradient triangle from x=1 to x=2
      const x0=1, y0=m*x0+c;
      h+=`<path d="M${X(x0)} ${Y(y0)}H${X(x0+1)}V${Y(y0+m)}" fill="none" stroke="#137a4a" stroke-width="3" stroke-linejoin="round"/><text x="${X(x0+.5)}" y="${Y(y0)+(m>=0?15:-6)}" text-anchor="middle" font-size="11" font-weight="900" fill="#137a4a" stroke="#fff" stroke-width="3" paint-order="stroke">1 across</text><text x="${X(x0+1)+6}" y="${Y(y0+m/2)+4}" font-size="11" font-weight="900" fill="#137a4a" stroke="#fff" stroke-width="3" paint-order="stroke">${m>=0?"up":"down"} ${Math.abs(m)}</text>`;
      $("#lgd").innerHTML=h;
      hx=3; if(Math.abs(m*hx+c)>7.4) hx=Math.max(1,Math.min(3,(Math.sign(m*3+c)*7.4-c)/m)); const hy=Math.max(-7.6,Math.min(7.6,m*hx+c));
      $("#lgh").innerHTML=`<circle class="lgc" cx="${X(0)}" cy="${Y(c)}" r="11" fill="#ff5a3c" stroke="#fff" stroke-width="3" style="cursor:ns-resize"/><text x="${X(0)-16}" y="${Y(c)+(c>=0?-12:20)}" text-anchor="end" font-size="11" font-weight="900" fill="#c2410c" stroke="#fff" stroke-width="3" paint-order="stroke">(0, ${c})</text><circle class="lgm" cx="${X(hx)}" cy="${Y(hy)}" r="11" fill="#3b5bdb" stroke="#fff" stroke-width="3" style="cursor:ns-resize"/>`;
      $("#lgeq").textContent=eq(m,c); $("#lgm").value=m*2; $("#lgc").value=c; $("#lgmv").textContent=m; $("#lgcv").textContent=c;
      $("#lgsay").textContent=m===0?`m = 0: a flat line. c = ${c}: it crosses the y-axis at (0, ${c}).`:`For every 1 across, the line goes ${m>0?"up":"down"} ${Math.abs(m)}. It crosses the y-axis at (0, ${c}).${m<0?" A negative gradient slopes downhill.":""}`;
      const xs=[-2,-1,0,1,2]; $("#lgt").innerHTML=`<tr><td style="padding:4px 10px;color:#4a5275">x</td>${xs.map(x=>`<td style="padding:4px 10px;border:1px solid #cfd8ff;text-align:center;background:#fff">${x}</td>`).join("")}</tr><tr><td style="padding:4px 10px;color:#4a5275">y</td>${xs.map(x=>`<td style="padding:4px 10px;border:1px solid #cfd8ff;text-align:center;background:#e8edff;color:#1e3a8a">${m*x+c}</td>`).join("")}</tr>`;
    };
    const pos=e=>{ const q=svg.createSVGPoint(); q.x=e.clientX; q.y=e.clientY; const r=q.matrixTransform(svg.getScreenCTM().inverse()); return [(r.x-O)/C,(O-r.y)/C]; };
    let moves=0;
    svg.addEventListener("pointerdown",e=>{ if(e.target.closest(".lgc")) drag="c"; else if(e.target.closest(".lgm")) drag="m"; else return; svg.setPointerCapture(e.pointerId); e.preventDefault(); });
    svg.addEventListener("pointermove",e=>{ if(!drag) return; const p=pos(e); if(drag==="c") c=Math.max(-6,Math.min(6,Math.round(p[1]))); else m=Math.max(-4,Math.min(4,Math.round((p[1]-c)/hx*2)/2)); if(++moves===8) addXP(2); draw(); });
    const up=()=>{ drag=""; }; svg.addEventListener("pointerup",up); svg.addEventListener("pointercancel",up);
    $("#lgm").oninput=e=>{ m=e.target.value/2; draw(); }; $("#lgc").oninput=e=>{ c=+e.target.value; draw(); }; $("#lgref").onchange=draw;
    draw();
  }};
})();

  }).call(globalThis);
}
