// GENERATED by scripts/hub-widgets.mjs — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
import angleExplorer from "./angleExplorer.gen";
import arrayBuilder from "./arrayBuilder.gen";
import circuitBuilder from "./circuitBuilder.gen";
import coordGrid from "./coordGrid.gen";
import forceMotion from "./forceMotion.gen";
import langCore from "./langCore.gen";
import numberLine from "./numberLine.gen";
import ordClass from "./ordClass.gen";
import particleModel from "./particleModel.gen";
import placeValue from "./placeValue.gen";
import sharing from "./sharing.gen";
import tenFrame from "./tenFrame.gen";
import transformGrid from "./transformGrid.gen";
import wordClass from "./wordClass.gen";

export const LEGACY_REGISTRARS: ((h: LegacyHelpers) => void)[] = [angleExplorer, arrayBuilder, circuitBuilder, coordGrid, forceMotion, langCore, numberLine, ordClass, particleModel, placeValue, sharing, tenFrame, transformGrid, wordClass];
