// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/measure.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* measure — read a ruler, a measuring jug and a weighing dial; drag to change the reading */
(function(){
const css=`<style>
#ms .ms-svg{touch-action:none;user-select:none;max-width:340px;margin:0 auto;cursor:pointer}
#ms .chip{border:2px solid var(--line);background:#fff;border-radius:99px;padding:5px 12px;font-weight:800;font-size:13px;color:var(--ink2)}
#ms .chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
#ms .ms-r{font-size:26px;font-weight:900;color:var(--brand);text-align:center;font-variant-numeric:tabular-nums}
</style>`;
WIDGETS.measure={
 title:"Read the scale",
 intro:"Drag the pencil's end, the water level or the needle. Read the scale, then check the numbers underneath.",
 html(){return css+`<div class="explore" id="ms">
 <div class="row" style="margin-bottom:8px"><button class="chip on" data-t="len">Length</button><button class="chip" data-t="cap">Capacity</button><button class="chip" data-t="mass">Mass</button></div>
 <svg class="ms-svg" id="ms-svg" viewBox="0 0 340 220" role="img" aria-label="measuring scale"></svg>
 <div class="ms-r" id="ms-r" aria-live="polite"></div>
 <p class="small" id="ms-say" style="text-align:center;margin:4px 0 0"></p></div>`},
 init(){
  const svg=$("#ms-svg"),NS="http://www.w3.org/2000/svg",box=$("#ms");
  const T=(typeof L!=="undefined"&&L&&L.title)||"",U=(typeof L!=="undefined"&&L&&L.unit)||"";
  const pick=x=>/litre|capacity|volume/i.test(x)?"cap":/mass|gram|weigh/i.test(x)?"mass":/length|ruler|centimet|metre/i.test(x)?"len":"";
  let tab=pick(T)||pick(U)||"len",v={len:.5,cap:.65,mass:.35},down=false;
  const el=(t,a,p)=>{const e=document.createElementNS(NS,t);for(const k in a)e.setAttribute(k,a[k]);(p||svg).appendChild(e);return e};
  const tx=(x,y,s,sz,col,anc)=>{const t=el("text",{x,y,"text-anchor":anc||"middle","font-size":sz||12,"font-weight":800,fill:col||"#4a5275"});t.textContent=s;return t};
  function len(){const X0=20,PX=20,L=15,val=Math.round(v.len*L*10)/10; // mm snap
   el("rect",{x:X0-10,y:112,width:320,height:58,rx:8,fill:"#fff3d6",stroke:"#e0b850","stroke-width":2});
   for(let i=0;i<=L*10;i++){const x=X0+i*PX/10*1,big=i%10===0,mid=i%5===0;el("line",{x1:x,x2:x,y1:112,y2:112+(big?26:mid?18:11),stroke:"#7a5a00","stroke-width":big?2:1.2});if(big)tx(x,150,i/10,13,"#7a5a00")}
   tx(300,166,"cm",11,"#7a5a00");
   const w=val*PX;el("rect",{x:X0,y:52,width:w,height:36,fill:"#ffd43b",stroke:"#b58900","stroke-width":2,rx:3});
   el("path",{d:`M${X0+w} 52 l30 18 l-30 18z`,fill:"#f2c48d",stroke:"#b58900","stroke-width":2,transform:`translate(${-30+0} 0)`,opacity:0});
   el("line",{x1:X0+w,x2:X0+w,y1:40,y2:170,stroke:"#e8590c","stroke-width":2,"stroke-dasharray":"4 3"});
   const g=el("circle",{cx:X0+w,cy:70,r:11,fill:"#e8590c",stroke:"#fff","stroke-width":3,style:"cursor:ew-resize"});
   const cm=Math.floor(val+1e-9),mm=Math.round((val-cm)*10);
   $("#ms-r").textContent=`${cm} cm ${mm} mm = ${val} cm`;
   $("#ms-say").textContent="Each small mark is 1 mm. 10 mm make 1 cm."}
  function cap(){const X=110,Y0=30,H=160,W=100,val=Math.round(v.cap*1000/10)*10;
   const y=Y0+H-H*val/1000;
   el("path",{d:`M${X} ${Y0} v${H} q0 10 10 10 h${W-20} q10 0 10 -10 v-${H}`,fill:"#f3f6ff",stroke:"#1e3a8a","stroke-width":4,"stroke-linecap":"round"});
   el("clipPath",{id:"ms-cl"}).appendChild(Object.assign(document.createElementNS(NS,"rect"),{}));
   const cp=svg.querySelector("#ms-cl rect");cp.setAttribute("x",X+2);cp.setAttribute("y",Y0);cp.setAttribute("width",W-4);cp.setAttribute("height",H+8);
   const wt=el("g",{"clip-path":"url(#ms-cl)"});el("rect",{x:X,y,width:W,height:H+10-(y-Y0),fill:"#6f97ff",opacity:.85},wt);
   el("path",{d:`M${X} ${y} q12 -6 25 0 t25 0 t25 0 t25 0 v6 h-100z`,fill:"#3b5bdb",opacity:.6},wt);
   for(let i=0;i<=10;i++){const yy=Y0+H-H*i/10,big=i%5===0;el("line",{x1:X+W,x2:X+W+(big?16:10),y1:yy,y2:yy,stroke:"#1e3a8a","stroke-width":big?2.5:1.5});if(i%2===0||true)tx(X+W+(big?20:14),yy+4,i*100,10,"#4a5275","start")}
   tx(X+W+50,Y0-8,"ml",11,"#4a5275","start");
   el("line",{x1:X-14,x2:X+W+2,y1:y,y2:y,stroke:"#e8590c","stroke-width":2,"stroke-dasharray":"4 3"});el("circle",{cx:X-14,cy:y,r:11,fill:"#e8590c",stroke:"#fff","stroke-width":3,style:"cursor:ns-resize"});
   $("#ms-r").textContent=`${val} ml = ${val/1000} litres`;$("#ms-say").textContent="Each division on this jug is 100 ml. 1000 ml make 1 litre."}
  function mass(){const CX=170,CY=118,R=92,val=Math.round(v.mass*1000/10)*10;const a=v=>(-150+v/1000*300);
   el("circle",{cx:CX,cy:CY,r:R+8,fill:"#dfe6ff",stroke:"#1e3a8a","stroke-width":5});el("circle",{cx:CX,cy:CY,r:R,fill:"#fff"});
   for(let i=0;i<=50;i++){const d=(a(i*20))*Math.PI/180,big=i%5===0,r2=R-(big?16:9);el("line",{x1:CX+R*Math.sin(d),y1:CY-R*Math.cos(d),x2:CX+r2*Math.sin(d),y2:CY-r2*Math.cos(d),stroke:"#1e3a8a","stroke-width":big?2.5:1})}
   for(let i=0;i<=10;i++){const d=a(i*100)*Math.PI/180;tx(CX+(R-30)*Math.sin(d),CY-(R-30)*Math.cos(d)+4,i*100,11)}
   tx(CX,CY+38,"grams",11,"#7b83a3");
   const d=a(val)*Math.PI/180;el("line",{x1:CX,y1:CY,x2:CX+(R-10)*Math.sin(d),y2:CY-(R-10)*Math.cos(d),stroke:"#e8590c","stroke-width":4,"stroke-linecap":"round"});
   el("circle",{cx:CX+(R-10)*Math.sin(d),cy:CY-(R-10)*Math.cos(d),r:9,fill:"#e8590c",stroke:"#fff","stroke-width":3,style:"cursor:grab"});el("circle",{cx:CX,cy:CY,r:8,fill:"#1e3a8a"});
   $("#ms-r").textContent=`${val} g = ${val/1000} kg`;$("#ms-say").textContent="Each small mark is 20 g. 1000 g make 1 kilogram."}
  function draw(){svg.innerHTML="";({len,cap,mass})[tab]()}
  const set=e=>{const r=svg.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*340,y=(e.clientY-r.top)/r.height*220;
   if(tab==="len")v.len=Math.max(0,Math.min(1,(x-20)/300));
   else if(tab==="cap")v.cap=Math.max(0,Math.min(1,(30+160-y)/160));
   else{const ang=Math.atan2(x-170,-(y-118))*180/Math.PI;v.mass=Math.max(0,Math.min(1,(ang+150)/300))}
   draw()};
  svg.addEventListener("pointerdown",e=>{down=true;svg.setPointerCapture(e.pointerId);set(e)});
  svg.addEventListener("pointermove",e=>{if(down)set(e)});
  const end=()=>{if(down){down=false;addXP(1)}};svg.addEventListener("pointerup",end);svg.addEventListener("pointercancel",end);
  box.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>{tab=b.dataset.t;box.querySelectorAll("[data-t]").forEach(x=>x.classList.toggle("on",x===b));draw()});
  box.querySelectorAll("[data-t]").forEach(x=>x.classList.toggle("on",x.dataset.t===tab));
  draw();
 }};
})();

  }).call(globalThis);
}
