// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/numberLine.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* numberLine — a hopping counter on a number line: count on/back, skip count, negatives */
(function(){
const ID="nl";
const RANGES={a:[0,20],b:[0,100],c:[-10,10],d:[0,1000]};
const css=`<style>
#nl .nl-svg{touch-action:none;cursor:pointer;user-select:none}
#nl .chips{display:flex;flex-wrap:wrap;gap:6px;align-items:center}
#nl .chip{border:2px solid var(--line);background:#fff;color:var(--ink2);border-radius:99px;padding:5px 12px;font-weight:800;font-size:13px}
#nl .chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
#nl .eq{font-size:20px;font-weight:900;color:var(--brand);text-align:center;margin:10px 0 2px;min-height:30px;word-break:break-word}
#nl .nl-frog{transition:transform .38s cubic-bezier(.3,.8,.3,1)}
#nl .nl-arc{stroke-dasharray:200;stroke-dashoffset:200;animation:nlarc .45s forwards}
@keyframes nlarc{to{stroke-dashoffset:0}}
</style>`;
WIDGETS.numberLine={
 title:"Hop along the number line",
 intro:"Tap the line to place the counter, choose a step size, then hop forwards or back. Watch the jumps add up.",
 html(){return css+`<div class="explore" id="nl">
 <div class="chips" style="margin-bottom:8px"><span class="small">Line</span>${Object.entries({a:"0–20",b:"0–100",c:"−10–10",d:"0–1000"}).map(([k,v])=>`<button class="chip" data-r="${k}">${v}</button>`).join("")}</div>
 <div class="row spread" style="margin-bottom:6px"><div class="row"><span class="small">Jump size</span><button class="btn ghost st" data-s="-">−</button><span class="stat" id="nl-step">1</span><button class="btn ghost st" data-s="+">+</button></div>
 <div class="chips">${[1,2,5,10].map(n=>`<button class="chip" data-p="${n}">${n}s</button>`).join("")}</div></div>
 <svg class="nl-svg" id="nl-svg" viewBox="0 0 340 120" role="img" aria-label="number line"></svg>
 <div class="eq" id="nl-eq" aria-live="polite"></div>
 <div class="row" style="justify-content:center;gap:8px;margin-top:6px"><button class="btn ghost" id="nl-back">◀ Hop back</button><button class="btn" id="nl-fwd">Hop on ▶</button><button class="btn ghost" id="nl-rst">Reset</button></div>
 <p class="small" id="nl-say" style="text-align:center;margin:10px 0 0"></p></div>`},
 init(){
  const box=$("#nl"),svg=$("#nl-svg");const NS="http://www.w3.org/2000/svg";
  const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;
  let r="a",step=1,start=0,pos=0,hops=[],animFrom=null;
  const X0=18,X1=322,Y=84;
  const rg=()=>RANGES[r];
  const xOf=v=>X0+(v-rg()[0])/(rg()[1]-rg()[0])*(X1-X0);
  const el=(t,a,p)=>{const e=document.createElementNS(NS,t);for(const k in a)e.setAttribute(k,a[k]);(p||svg).appendChild(e);return e};
  function base(){
   svg.innerHTML="";const [lo,hi]=rg();const span=hi-lo;
   const major=span<=20?1:span<=100?10:span<=200?10:100;const minor=span<=20?1:span<=100?5:100;
   el("line",{x1:X0-6,x2:X1+6,y1:Y,y2:Y,stroke:"#3b5bdb","stroke-width":3,"stroke-linecap":"round"});
   for(let v=lo;v<=hi;v+=span<=20?1:span<=100?5:50){const big=(v%major===0);
    el("line",{x1:xOf(v),x2:xOf(v),y1:Y-(big?9:5),y2:Y+(big?9:5),stroke:"#3b5bdb","stroke-width":big?2.5:1.5});
    if(big&&(span<=20||v%(span<=100?10:100)===0)){const t=el("text",{x:xOf(v),y:Y+26,"text-anchor":"middle","font-size":span<=20&&window.innerWidth<420?9:10.5,"font-weight":800,fill:"#4a5275"});t.textContent=v<0?"−"+(-v):v}}
   // hops
   hops.forEach((h,i)=>{const a=xOf(h.from),b=xOf(h.to),m=(a+b)/2,hgt=Math.min(46,14+Math.abs(b-a)/3);
    const p=el("path",{d:`M${a} ${Y-2} Q${m} ${Y-2-hgt*1.8} ${b} ${Y-2}`,fill:"none",stroke:h.to>=h.from?"#3b5bdb":"#e8590c","stroke-width":3,"stroke-linecap":"round"});
    if(i===hops.length-1&&!reduce)p.setAttribute("class","nl-arc");
    if(Math.abs(b-a)>=24){const t=el("text",{x:m,y:Y-hgt*0.9-6,"text-anchor":"middle","font-size":11,"font-weight":900,fill:h.to>=h.from?"#1e3a8a":"#c2410c"});t.textContent=(h.to>=h.from?"+":"−")+Math.abs(h.to-h.from)}});
   el("circle",{cx:xOf(start),cy:Y,r:5,fill:"#fff",stroke:"#1e3a8a","stroke-width":2});
   const g=el("g",{transform:`translate(${xOf(pos)} ${Y-16})`});
   if(animFrom!==null&&!reduce&&g.animate){const a=xOf(animFrom),b=xOf(pos),T=v=>`translate(${v}px,${Y-16}px)`;g.animate([{transform:T(a)},{transform:`translate(${(a+b)/2}px,${Y-16-30}px)`},{transform:T(b)}],{duration:420,easing:"ease-in-out"})}
   animFrom=null;
   el("circle",{r:11,fill:"#22a06b",stroke:"#0f6b45","stroke-width":2},g);el("circle",{cx:-4,cy:-3,r:3,fill:"#fff"},g);el("circle",{cx:4,cy:-3,r:3,fill:"#fff"},g);el("circle",{cx:-4,cy:-3,r:1.4,fill:"#111"},g);el("circle",{cx:4,cy:-3,r:1.4,fill:"#111"},g);
   el("path",{d:"M-5 4 Q0 8 5 4",fill:"none",stroke:"#0f6b45","stroke-width":1.6,"stroke-linecap":"round"},g);
   const bub=el("text",{x:xOf(pos),y:Y+44,"text-anchor":"middle","font-size":15,"font-weight":900,fill:"#1e3a8a"});bub.textContent=pos<0?"−"+(-pos):pos;
  }
  function text(){
   let e=`${start<0?"−"+(-start):start}`;
   hops.forEach(h=>{e+=h.to>=h.from?` + ${step_of(h)}`:` − ${step_of(h)}`});
   $("#nl-eq").textContent=hops.length?`${e} = ${pos<0?"−"+(-pos):pos}`:"Start at "+(start<0?"−"+(-start):start);
   const f=hops.filter(h=>h.to>=h.from).length,b=hops.length-f;
   $("#nl-say").textContent=hops.length?`${hops.length} hop${hops.length>1?"s":""} of ${step}${f&&b?" ("+f+" on, "+b+" back)":""}. Total jump ${Math.abs(pos-start)} ${pos>=start?"to the right":"to the left"}.`:`Tap the line to move the start, then hop in ${step}s.`;
  }
  const step_of=h=>Math.abs(h.to-h.from);
  function draw(){base();text();
   box.querySelectorAll("[data-r]").forEach(b=>b.classList.toggle("on",b.dataset.r===r));
   box.querySelectorAll("[data-p]").forEach(b=>b.classList.toggle("on",+b.dataset.p===step));$("#nl-step").textContent=step}
  function hop(dir){const [lo,hi]=rg();let to=pos+dir*step;if(to>hi||to<lo){$("#nl-say").textContent="The counter can't hop off the end of the line!";return}
   hops.push({from:pos,to});animFrom=pos;pos=to;if(hops.length>12){hops.shift()}draw();if(hops.length%5===0)addXP(1)}
  $("#nl-fwd").onclick=()=>hop(1);$("#nl-back").onclick=()=>hop(-1);
  $("#nl-rst").onclick=()=>{pos=start;hops=[];draw()};
  box.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{r=b.dataset.r;start=pos=rg()[0]<0?0:rg()[0];hops=[];if(r==="d"&&step<10)step=10;draw()});
  box.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{step=+b.dataset.p;draw()});
  box.querySelectorAll(".st").forEach(b=>b.onclick=()=>{step=Math.max(1,Math.min(100,step+(b.dataset.s==="+"?1:-1)));draw()});
  svg.addEventListener("pointerdown",e=>{const rc=svg.getBoundingClientRect();const x=(e.clientX-rc.left)/rc.width*340;
   const v=Math.round(rg()[0]+(x-X0)/(X1-X0)*(rg()[1]-rg()[0]));start=pos=Math.max(rg()[0],Math.min(rg()[1],v));hops=[];draw()});
  draw();
 }};
})();

  }).call(globalThis);
}
