// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/percentGrid.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* percentGrid — shade a 10x10 grid; see the fraction, decimal and percentage change together */
(function(){
const css=`<style>
#pg .pg-grid{display:grid;grid-template-columns:repeat(10,1fr);gap:2px;background:#cfd8ff;padding:3px;border-radius:10px;max-width:260px;aspect-ratio:1;touch-action:none;user-select:none;margin:0 auto}
#pg .pg-c{background:#fff;border-radius:3px;transition:background .18s,transform .18s}
#pg .pg-c.on{background:#3b5bdb}#pg .pg-c.row{background:#1e3a8a}
#pg .pg-c.pop{transform:scale(.7)}
#pg .pg-t{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px;text-align:center}
#pg .pg-t>div{background:#fff;border:2px solid #cfd8ff;border-radius:12px;padding:8px 2px}
#pg .pg-t small{display:block;font-size:11px;font-weight:800;color:var(--ink3);text-transform:uppercase;letter-spacing:.04em}
#pg .pg-t b{font-size:21px;color:var(--brand)}
#pg input[type=range]{width:100%;accent-color:var(--brand2)}
</style>`;
WIDGETS.percentGrid={
 title:"Fractions, decimals and percentages",
 intro:"Drag across the 100 squares to shade some of them. See how the fraction, decimal and percentage all say the same thing.",
 html(){return css+`<div class="explore" id="pg">
 <div class="pg-grid" id="pg-grid" role="img" aria-label="hundred square"></div>
 <input type="range" id="pg-r" min="0" max="100" value="35" style="margin-top:12px" aria-label="number of shaded squares">
 <div class="pg-t"><div><small>Fraction</small><b id="pg-f"></b></div><div><small>Decimal</small><b id="pg-d"></b></div><div><small>Percent</small><b id="pg-p"></b></div></div>
 <p class="small" id="pg-say" style="text-align:center;margin:10px 0 6px"></p>
 <div class="row" style="justify-content:center"><span class="small">Try:</span>${[["½",50],["¼",25],["¾",75],["⅕",20],["⅒",10],["⅛",12.5],["3/20",15]].map(([l,v])=>`<button class="btn ghost pr" data-v="${v}">${l}</button>`).join("")}</div></div>`},
 init(){
  const g=$("#pg-grid"),r=$("#pg-r");let n=35,down=false;
  g.innerHTML=[...Array(100)].map((_,i)=>`<i class="pg-c" data-i="${i}"></i>`).join("");
  const cells=[...g.children];
  const fr=(a,b)=>`<span class="frac" style="font-size:.85em"><b>${a}</b><u>${b}</u></span>`;
  function draw(){
   const cnt=Math.round(n*2)/2;const full=Math.floor(cnt/10);
   cells.forEach((c,i)=>{c.classList.toggle("on",i<cnt);c.style.opacity=(i+1>cnt&&i<cnt)?.5:1;c.classList.toggle("row",i<full*10)});
   r.value=n;
   const gg=gcd(Math.round(cnt*2),200),fn=Math.round(cnt*2)/gg,fd=200/gg;
   $("#pg-f").innerHTML=cnt===0?"0":fr(fn,fd);$("#pg-d").textContent=(cnt/100).toString();$("#pg-p").textContent=cnt+"%";
   const tenths=full,hund=Math.floor(cnt%10);
   $("#pg-say").textContent=cnt===0?"Nothing shaded yet.":`${cnt} hundredths shaded = ${tenths?tenths+" full row"+(tenths>1?"s":"")+" (tenths)":""}${tenths&&hund?" + ":""}${hund?hund+" hundredth"+(hund>1?"s":""):""}${cnt%1?" and a half square":""}`;
  }
  const idx=e=>{const t=document.elementFromPoint(e.clientX,e.clientY);if(t&&t.classList&&t.classList.contains("pg-c"))return +t.dataset.i;return null};
  g.addEventListener("pointerdown",e=>{down=true;g.setPointerCapture(e.pointerId);const i=idx(e);if(i!==null){n=(i+1===n)?i:i+1;draw()}});
  g.addEventListener("pointermove",e=>{if(!down)return;const i=idx(e);if(i!==null&&i+1!==n){n=i+1;draw()}});
  g.addEventListener("pointerup",()=>{if(down){down=false;addXP(1)}});
  r.oninput=()=>{n=+r.value;draw()};
  document.querySelectorAll("#pg .pr").forEach(b=>b.onclick=()=>{n=+b.dataset.v;draw();addXP(1)});
  draw();
 }};
})();

  }).call(globalThis);
}
