// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/placeValue.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* placeValue — place-value counters: add/remove, watch 10 exchange for 1; shift digits by x10 / ÷10 */
(function(){
const css=`<style>
#pv .pv-cols{display:grid;gap:6px}
#pv .pv-col{background:#fff;border:2px solid var(--line);border-radius:12px;min-height:170px;display:flex;flex-direction:column;overflow:hidden}
#pv .pv-h{background:var(--brand-soft);color:var(--brand);font-weight:900;text-align:center;padding:5px 0;font-size:14px}
#pv .pv-body{flex:1;display:flex;flex-wrap:wrap;align-content:flex-end;justify-content:center;gap:3px;padding:6px 3px;min-height:100px}
#pv .pv-k{width:26px;height:26px;border-radius:50%;color:#fff;font-size:10px;font-weight:900;display:grid;place-items:center;animation:pvin .3s cubic-bezier(.3,1.6,.5,1);box-shadow:0 2px 0 rgba(0,0,0,.2)}
#pv .pv-k.out{animation:pvout .35s forwards}
@keyframes pvin{from{transform:translateY(-30px) scale(.4);opacity:0}}
@keyframes pvout{to{transform:translateX(30px) scale(.2);opacity:0}}
#pv .pv-btns{display:flex;border-top:2px solid var(--line)}
#pv .pv-btns button{flex:1;border:0;background:#fff;font-size:20px;font-weight:900;color:var(--brand);padding:6px 0}
#pv .pv-btns button+button{border-left:2px solid var(--line)}#pv .pv-btns button:active{background:var(--brand-soft)}
#pv .pv-dg{font-size:34px;font-weight:900;color:var(--brand);text-align:center;background:#fff;border-radius:8px;border-bottom:3px solid var(--brand2)}
#pv .pv-dot{align-self:end;font-size:34px;font-weight:900;color:var(--brand);text-align:center}
#pv .chip{border:2px solid var(--line);background:#fff;border-radius:99px;padding:5px 12px;font-weight:800;font-size:13px;color:var(--ink2)}
#pv .chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
</style>`;
const COL=["#1e3a8a","#3b5bdb","#4c7cf0","#7a9bff","#94a9ff","#b0c0ff"];
WIDGETS.placeValue={
 title:"Build a number with place-value counters",
 intro:"Press + to add a counter to a column. Get to 10 and they swap for one counter in the next column. Try × 10 and ÷ 10 too.",
 html(){return css+`<div class="explore" id="pv">
 <div class="row spread" style="margin-bottom:10px"><div class="row"><button class="chip on" data-m="w">Whole numbers</button><button class="chip" data-m="d">Decimals</button></div>
 <div class="row"><button class="btn ghost st" id="pv-x">× 10</button><button class="btn ghost st" id="pv-d">÷ 10</button><button class="btn ghost st" id="pv-c">Clear</button></div></div>
 <div id="pv-cols" class="pv-cols"></div><div id="pv-dg" class="pv-cols" style="margin-top:8px"></div>
 <div class="stat" id="pv-num" style="text-align:center;font-size:24px;margin-top:10px"></div>
 <p class="small" id="pv-say" style="text-align:center;margin:4px 0 0"></p></div>`},
 init(){
  const box=$("#pv");let mode="w",exps=[3,2,1,0],n=[0,0,0,0];const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;
  const NM={3:"Thousands",2:"Hundreds",1:"Tens",0:"Ones","-1":"Tenths","-2":"Hundredths"},SH={3:"Th",2:"H",1:"T",0:"O","-1":"t","-2":"h"};
  const val=e=>e>=0?String(Math.pow(10,e)):"0."+"0".repeat(-e-1)+"1";
  const setMode=m=>{mode=m;exps=m==="w"?[3,2,1,0]:[1,0,-1,-2];n=[0,0,0,0];box.querySelectorAll("[data-m]").forEach(b=>b.classList.toggle("on",b.dataset.m===m));draw()};
  const cols=$("#pv-cols"),dgs=$("#pv-dg");
  function draw(keep){
   const tpl=`repeat(${exps.length},1fr)`;cols.style.gridTemplateColumns=dgs.style.gridTemplateColumns=tpl;
   cols.innerHTML=exps.map((e,i)=>`<div class="pv-col"><div class="pv-h">${window.innerWidth<420?SH[e]:NM[e]}</div><div class="pv-body" data-i="${i}">${[...Array(n[i])].map((_,k)=>`<span class="pv-k" style="background:${COL[i]};${val(e).length>3?"font-size:8px;":""}${keep&&keep.i===i&&k===n[i]-1?"":";animation:none"}">${val(e)}</span>`).join("")}</div><div class="pv-btns"><button data-a="-" data-i="${i}" aria-label="remove one from ${NM[e]}">−</button><button data-a="+" data-i="${i}" aria-label="add one to ${NM[e]}">+</button></div></div>`).join("");
   dgs.innerHTML=n.map((d,i)=>`<div class="pv-dg">${d}</div>`).join("");
   if(mode==="d")dgs.innerHTML=n.map((d,i)=>`<div class="pv-dg" style="${exps[i]===0?"":""}">${d}${exps[i]===0?'<span style="color:#e8590c">.</span>':""}</div>`).join("");
   const num=n.reduce((s,d,i)=>s+d*Math.pow(10,exps[i]),0);const fx=+num.toFixed(3);
   $("#pv-num").textContent=(mode==="w"?fx.toLocaleString("en-GB"):fx);
   const parts=n.map((d,i)=>d?`${d} ${NM[exps[i]].toLowerCase()}`:"").filter(Boolean);
   $("#pv-say").textContent=parts.length?parts.join(" + "):"Add some counters to make a number.";
   cols.querySelectorAll("button[data-a]").forEach(b=>b.onclick=()=>step(+b.dataset.i,b.dataset.a==="+"?1:-1));
  }
  function step(i,d){
   if(d>0){n[i]++;if(n[i]>=10){if(i===0){n[0]=9;$("#pv-say").textContent="That's the biggest column — can't go higher here!";return draw()}
     draw({i});const body=cols.querySelectorAll(".pv-body")[i];const k=[...body.children];k.forEach(x=>x.classList.add("out"));
     setTimeout(()=>{n[i]=0;n[i-1]++;addXP(1);draw({i:i-1});$("#pv-say").textContent="10 counters swapped for 1 counter in the next column!"},reduce?0:340);return}}
   else{ if(n[i]>0)n[i]--;else{ // unexchange: borrow one from the left
     let j=i-1;while(j>=0&&n[j]===0)j--;if(j<0)return;n[j]--;for(let k=j+1;k<=i;k++)n[k]=(k===i?9:9);draw();$("#pv-say").textContent="Unpacked 1 counter into 10 in the column to the right.";return}}
   draw(d>0?{i}:null)}
  $("#pv-c").onclick=()=>{n=n.map(()=>0);draw()};
  $("#pv-x").onclick=()=>{if(n[0]>0)return void($("#pv-say").textContent="Digits would fall off the end — clear a little space first.");n=[...n.slice(1),0];addXP(1);draw();$("#pv-say").textContent="× 10: every digit moves one column to the left."};
  $("#pv-d").onclick=()=>{if(n[n.length-1]>0)return void($("#pv-say").textContent="Digits would fall off the end.");n=[0,...n.slice(0,-1)];addXP(1);draw();$("#pv-say").textContent="÷ 10: every digit moves one column to the right."};
  box.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>setMode(b.dataset.m));
  n=[0,3,4,7];draw();
 }};
})();

  }).call(globalThis);
}
