// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/probSim.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* probSim — coin, dice and spinner: roll once or hundreds of times, watch relative frequency settle towards the probability */
(function(){
  const RM=matchMedia("(prefers-reduced-motion: reduce)").matches, COL=["#3b5bdb","#ff5a3c","#137a4a","#f4c542","#8b5cf6","#0ea5b7"];
  const CFG={coin:{n:"Coin",o:["Heads","Tails"],w:[1,1],u:[7,3]},dice:{n:"Dice",o:["1","2","3","4","5","6"],w:[1,1,1,1,1,1],u:[1,1,1,1,1,3]},spin:{n:"Spinner",o:["Blue","Red","Green","Yellow"],w:[1,1,1,1],u:[2,1,1,1]}};
  const PIPS={1:[[0,0]],2:[[-1,-1],[1,1]],3:[[-1,-1],[0,0],[1,1]],4:[[-1,-1],[1,-1],[-1,1],[1,1]],5:[[-1,-1],[1,-1],[0,0],[-1,1],[1,1]],6:[[-1,-1],[1,-1],[-1,0],[1,0],[-1,1],[1,1]]};
  WIDGETS.probSim={title:"Chance and probability lab",intro:"Roll it once, then roll it a hundred times. Do the bars match what you predicted? Then make it unfair and see what changes.",
  html(){ return `<div class="explore" id="pbw"><div class="row" style="justify-content:center;margin-bottom:8px" id="pbm">${Object.keys(CFG).map(k=>`<button class="btn ghost pr fk" data-m="${k}">${CFG[k].n}</button>`).join("")}</div>
    <div style="display:flex;gap:14px;align-items:center;justify-content:center;flex-wrap:wrap"><svg id="pbo" viewBox="0 0 150 150" style="width:150px;flex:none" role="img" aria-label="The coin, die or spinner"></svg>
    <div style="flex:1;min-width:190px"><div class="row"><button class="btn" data-n="1">Roll ×1</button><button class="btn" data-n="10">×10</button><button class="btn" data-n="100">×100</button><button class="btn" data-n="1000">×1000</button></div>
    <p style="margin:10px 0 2px;font-size:15px;font-weight:800;color:var(--brand)" id="pbres"></p><label class="switch" style="margin-top:4px"><input type="checkbox" id="pbun"> Make it unfair</label> <button class="btn ghost st" id="pbclr" style="margin-left:6px">Clear</button></div></div>
    <svg id="pbc" viewBox="0 0 360 170" style="margin-top:10px;background:#fff;border-radius:12px;border:2px solid #cfd8ff" role="img" aria-label="Relative frequency bar chart"></svg><p class="small" id="pbsay" style="margin:8px 0 0;text-align:center"></p></div>`; },
  init(){
    let mode="coin", unfair=false, counts=[], total=0, rot=0, busy=false, last=-1, nroll=0;
    const cfg=()=>CFG[mode], W=()=>unfair?cfg().u:cfg().w, sumW=()=>W().reduce((a,b)=>a+b,0);
    const pick=()=>{ let r=Math.random()*sumW(); const w=W(); for(let i=0;i<w.length;i++){ r-=w[i]; if(r<0) return i; } return w.length-1; };
    const fr=(a,b)=>{ const g=(x,y)=>y?g(y,x%y):x, d=g(a,b); return d===b?a/d:a/d+"/"+b/d; };
    const reset=()=>{ counts=cfg().o.map(()=>0); total=0; last=-1; drawObj(false,true); drawChart(); };
    const drawObj=(anim,full)=>{ const o=$("#pbo"), c=cfg(); let h="";
      if(mode==="coin"){ h=`<g id="pbcg" style="transform-origin:75px 75px"><circle cx="75" cy="75" r="62" fill="#f4c542" stroke="#c99a10" stroke-width="6"/><circle cx="75" cy="75" r="50" fill="none" stroke="#c99a10" stroke-width="2" stroke-dasharray="4 4"/><text x="75" y="89" text-anchor="middle" font-size="40" font-weight="900" fill="#8a5a00">${last<0?"?":last===1?"T":"H"}</text></g>`; o.innerHTML=h; if(anim&&!RM) o.firstChild.animate([{transform:"scaleY(1)"},{transform:"scaleY(.04)"},{transform:"scaleY(1)"},{transform:"scaleY(.04)"},{transform:"scaleY(1)"}],{duration:650}); return; }
      else if(mode==="dice"){ const v=last<0?6:last+1; h=`<rect x="20" y="20" width="110" height="110" rx="22" fill="#fff" stroke="#3b5bdb" stroke-width="6"/>`+PIPS[v].map(p=>`<circle cx="${75+p[0]*28}" cy="${75+p[1]*28}" r="10" fill="#1e3a8a"/>`).join(""); }
      else { if(!full&&$("#pbsp")){ $("#pbsp").style.transform=`rotate(${rot}deg)`; return; } const w=W(), s=sumW(); let a=-90; h=`<g id="pbsp" style="transform-origin:75px 75px;transition:transform ${RM?0:1.4}s cubic-bezier(.15,.7,.15,1);transform:rotate(${rot}deg)">`; w.forEach((x,i)=>{ const a1=a+x/s*360, p=t=>[75+64*Math.cos(t*Math.PI/180),75+64*Math.sin(t*Math.PI/180)], A=p(a), B=p(a1); h+=`<path d="M75 75L${A[0]} ${A[1]}A64 64 0 ${a1-a>180?1:0} 1 ${B[0]} ${B[1]}Z" fill="${COL[i]}" stroke="#fff" stroke-width="3"/>`; a=a1; }); h+=`</g><circle cx="75" cy="75" r="8" fill="#141a33"/><polygon points="66,4 84,4 75,20" fill="#141a33"/>`; }
      o.innerHTML=h; };
    const drawChart=()=>{ const c=cfg(), w=W(), s=sumW(), n=c.o.length, rf=counts.map(x=>total?x/total:0), ym=Math.min(1,Math.max(.3,1.35*Math.max(...rf,...w.map(x=>x/s)))), bw=290/n; let h="";
      for(let g=0;g<=ym+.001;g+=ym>.6?.25:.1){ const y=130-g/ym*112; h+=`<line x1="44" y1="${y}" x2="352" y2="${y}" stroke="#e3e8fb"/><text x="38" y="${y+4}" text-anchor="end" font-size="10" font-weight="800" fill="#7b83a3">${g.toFixed(g%.25===0&&ym>.6?2:1)}</text>`; }
      c.o.forEach((nm,i)=>{ const x=52+i*bw, hh=rf[i]/ym*112, y=130-hh, p=w[i]/s, py=130-p/ym*112;
        h+=`<rect x="${x+4}" y="${y}" width="${bw-8}" height="${hh}" rx="4" fill="${COL[i%6]}" style="transition:${RM?"none":"all .35s"}"/><text x="${x+bw/2}" y="${y-4}" text-anchor="middle" font-size="11" font-weight="900" fill="#1e3a8a">${counts[i]||""}</text><text x="${x+bw/2}" y="146" text-anchor="middle" font-size="${n>4?12:11}" font-weight="800" fill="#4a5275">${nm}</text>`;
        h+=`<line x1="${x}" y1="${py}" x2="${x+bw}" y2="${py}" stroke="#141a33" stroke-width="2.5" stroke-dasharray="5 3"/>`; });
      h+=`<text x="354" y="12" text-anchor="end" font-size="10" font-weight="800" fill="#141a33">- - - probability</text><text x="8" y="12" font-size="10" font-weight="800" fill="#7b83a3">relative frequency</text><text x="200" y="163" text-anchor="middle" font-size="10" font-weight="800" fill="#7b83a3">${total} ${total===1?"trial":"trials"}</text>`;
      $("#pbc").innerHTML=h;
      const top=rf.indexOf(Math.max(...rf)), tw=w[top]/s;
      $("#pbsay").textContent=total?`${c.o[top]}: ${counts[top]} out of ${total} = ${rf[top].toFixed(3)}. Theory says ${fr(w[top],s)} = ${tw.toFixed(3)}.${total<30?" Too few trials to trust! Roll more.":Math.abs(rf[top]-tw)<.05?" Close to the probability now.":""}`:`Nothing rolled yet. ${unfair?"Something is not fair here…":"Each outcome is equally likely: probability "+fr(1,n)+"."}`;
      $("#pbres").textContent=last<0?"Ready to roll":`${mode==="coin"?"Landed on":mode==="dice"?"Rolled a":"Landed on"} ${c.o[last]}`; };
    const roll=n=>{ if(busy) return; const w=W(); let l=-1; for(let i=0;i<n;i++){ l=pick(); counts[l]++; total++; } last=l; nroll++; if(nroll===3) addXP(2);
      if(mode==="spin"&&n===1){ const s=sumW(); let a=0; for(let i=0;i<l;i++) a+=w[i]/s*360; const mid=a+w[l]/s*360*(.2+.6*Math.random()); rot=Math.ceil(rot/360)*360+360*3-mid; busy=true; setTimeout(()=>{ busy=false; },RM?0:1400); }
      else if(mode==="spin"){ const s=sumW(); let a=0; for(let i=0;i<l;i++) a+=w[i]/s*360; rot=Math.ceil(rot/360)*360+360*2-(a+w[l]/s*180); }
      if(mode==="dice"&&n===1&&!RM){ let k=0; busy=true; const tm=setInterval(()=>{ last=Math.floor(Math.random()*6); drawObj(); if(++k>7){ clearInterval(tm); last=l; busy=false; drawObj(); drawChart(); } },70); drawChart(); return; }
      drawObj(n===1); drawChart(); };
    $("#pbw").querySelectorAll("[data-n]").forEach(b=>b.onclick=()=>roll(+b.dataset.n));
    $("#pbm").querySelectorAll(".pr").forEach(b=>b.onclick=()=>{ mode=b.dataset.m; $("#pbm").querySelectorAll(".pr").forEach(x=>x.classList.toggle("sel",x===b)); rot=0; reset(); });
    $("#pbun").onchange=e=>{ unfair=e.target.checked; rot=0; reset(); }; $("#pbclr").onclick=reset;
    $("#pbm").querySelector('[data-m="coin"]').classList.add("sel"); reset();
  }};
})();

  }).call(globalThis);
}
