// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/punctFixer.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* punctFixer: a sentence arrives with NO punctuation or capitals. Pick a pen, tap the gaps (or words for capitals) to fix it. All sentences original. */
WIDGETS.punctFixer = (() => {
  const MODES = {
    caps: { n: "Capitals & full stops", pens: ["Aa", ".", "?", "!"], b: ["The fox ran home.", "Can we play outside?", "What a lovely day!", "Kai found a shell on the beach.", "Will Priya come to the party?", "Look out!", "We saw a whale in the sea."] },
    apos: { n: "Apostrophes", pens: ["'", "Aa", "."], b: ["I don't like peas.", "The dog's bone is big.", "She couldn't find it.", "The girls' coats hang here.", "We're late.", "Tom's kite is red.", "The cats' bowls are empty."] },
    speech: { n: "Speech marks", pens: ['"', ",", ".", "!", "?", "Aa"], b: ['"Look at that!" said Mia.', 'Ben asked, "Can I come?"', '"We won," said Zoe.', '"Where is my hat?" asked Sam.', 'Mum said, "Dinner is ready."', '"Stop!" shouted the guard.'] },
    comma: { n: "Commas", pens: [",", "Aa", "."], b: ["We bought apples, pears, plums and figs.", "First, mix the flour.", "After lunch, we played outside.", "I packed a coat, a hat, a scarf and gloves.", "If it rains, we will stay in.", "Slowly, the door creaked open."] },
    col: { n: "Colons & semi-colons", pens: [":", ";", ",", "Aa", "."], b: ["You will need three things: a bowl, a spoon and a whisk.", "It was late; we went home.", "The sky was dark; the stars were bright.", "Remember this: always look both ways.", "Bring a torch: the cave is dark."] },
    paren: { n: "Brackets & dashes", pens: ["(", ")", "—", ",", "Aa", "."], b: ["My cat (a fluffy tabby) sleeps all day.", "Dad (who hates mornings) made toast.", "The moon — bright and full — rose over the hill.", "Our teacher, Mr Lee, smiled.", "The bus (which was late) finally arrived."] },
  };
  let root, mode = "caps", idx = 0, it, user, caps, pen, checked;
  const parse = (exp) => {
    const pcs = [], gaps = [{ m: "", k: -1 }]; let cur = "", g = gaps[0];
    const flush = () => { if (cur) { pcs.push(cur); cur = ""; gaps.push(g = { m: "", k: -1 }); } };
    for (const c of exp) { if (/[A-Za-z0-9]/.test(c)) cur += c; else if (c === " ") { flush(); g.k = g.m.length; } else { flush(); g.m += c; } }
    flush();
    return { pcs: pcs.map(p => p[0].toLowerCase() + p.slice(1)), cap: pcs.map(p => p[0] !== p[0].toLowerCase()), gaps, exp };
  };
  const pickMode = () => { const t = (typeof L !== "undefined" ? L.title : "").toLowerCase(); return /apostrophe|contraction|possession/.test(t) ? "apos" : /speech|inverted|dialogue/.test(t) ? "speech" : /colon|semi|bullet/.test(t) ? "col" : /parenthes|bracket|dash/.test(t) ? "paren" : /comma/.test(t) ? "comma" : "caps"; };
  const css = `<style>#pf .modes{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}#pf .md{border:2px solid var(--line);background:#fff;border-radius:99px;padding:5px 11px;font-weight:800;font-size:12.5px;cursor:pointer;color:var(--ink2)}#pf .md.on{background:var(--brand);color:#fff;border-color:var(--brand)}
  #pf .pens{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:8px}#pf .pn{min-width:46px;height:46px;border-radius:12px;border:2px solid var(--line);background:#fff;font-size:22px;font-weight:900;color:var(--brand);cursor:pointer;box-shadow:0 3px 0 var(--line);transition:transform .12s}
  #pf .pn.on{background:var(--brand-soft);border-color:var(--brand);transform:translateY(-3px)}
  #pf .line{font-size:22px;font-weight:700;padding:14px 4px;line-height:2.3;min-height:80px}
  #pf .wd{display:inline-block;white-space:nowrap}
  #pf .pc{display:inline-block;border:2px solid transparent;border-radius:8px;padding:0 1px;cursor:default}#pf .pc.cp{cursor:pointer}
  #pf .pc.capd{color:var(--brand);border-bottom-color:var(--brand)}
  #pf .g{display:inline-block;vertical-align:middle;min-width:8px;height:34px;border:0;border-left:2px dotted #c4cbe6;background:transparent;font:inherit;font-weight:900;color:var(--brand);cursor:pointer;white-space:pre;padding:0;margin:0}
  #pf .g.sp{min-width:16px;margin-right:2px}#pf .g:hover{background:var(--brand-soft)}
  #pf .g.pd{animation:pfpop .3s}@keyframes pfpop{40%{transform:scale(1.5)}}
  #pf .g.ok,#pf .pc.ok{color:var(--ok);background:var(--ok-soft)}#pf .g.no,#pf .pc.no{color:var(--bad);background:var(--bad-soft)}#pf .g.miss,#pf .pc.miss{background:var(--warn-soft);border:2px dashed var(--warn);animation:pfm 1s 2}@keyframes pfm{50%{opacity:.4}}
  #pf .msg{min-height:26px;font-weight:700;margin:4px 0 8px}</style>`;
  const gapText = (m, k) => k < 0 ? m : m.slice(0, Math.min(k, m.length)) + " " + m.slice(Math.min(k, m.length));
  const draw = () => {
    const P = it, ok = [], n = P.pcs.length; let h = "", word = "";
    const gapHTML = (i) => { const g = P.gaps[i], m = user[i], has = m.length; let c = "g" + (g.k >= 0 ? " sp" : ""); if (checked) c += m === g.m ? (has ? " ok" : "") : (has ? " no" : " miss");
      return `<button class="${c}" data-g="${i}" aria-label="gap ${i + 1}${has ? " with " + esc(m) : ""}">${esc(gapText(m, g.k))}</button>`; };
    word += gapHTML(0);
    for (let i = 0; i < n; i++) {
      let c = "pc" + (pen === "Aa" || pen === "⌫" ? " cp" : "") + (caps[i] ? " capd" : ""); if (checked && (caps[i] !== P.cap[i])) c += P.cap[i] ? " miss" : " no"; else if (checked && P.cap[i]) c += " ok";
      const t = caps[i] ? P.pcs[i][0].toUpperCase() + P.pcs[i].slice(1) : P.pcs[i];
      word += `<span class="${c}" data-p="${i}">${esc(t)}</span>` + gapHTML(i + 1);
      if (P.gaps[i + 1].k >= 0 || i === n - 1) { h += `<span class="wd">${word}</span> `; word = ""; }
    }
    root.querySelector(".line").innerHTML = h;
    root.querySelector(".pens").innerHTML = MODES[mode].pens.concat(["⌫"]).map(p => `<button class="pn${pen === p ? " on" : ""}" data-m="${esc(p)}" aria-label="${p === "Aa" ? "capital letter" : p === "⌫" ? "rub out" : "mark " + esc(p)}">${esc(p)}</button>`).join("");
    root.querySelector(".modes").innerHTML = Object.entries(MODES).map(([k, v]) => `<button class="md${k === mode ? " on" : ""}" data-k="${k}">${v.n}</button>`).join("");
    root.querySelectorAll(".pn").forEach(b => b.onclick = () => { pen = b.dataset.m; draw(); });
    root.querySelectorAll(".md").forEach(b => b.onclick = () => { mode = b.dataset.k; idx = 0; load(); });
    root.querySelectorAll(".g").forEach(b => b.onclick = () => { if (checked) return; const i = +b.dataset.g; if (pen === "⌫") user[i] = user[i].slice(0, -1); else if (pen !== "Aa" && user[i].length < 3) user[i] += pen; else return; draw(); root.querySelector(`.g[data-g="${i}"]`).classList.add("pd"); });
    root.querySelectorAll(".pc").forEach(b => b.onclick = () => { if (checked) return; const i = +b.dataset.p; if (pen === "Aa") caps[i] = true; else if (pen === "⌫") caps[i] = false; else return; draw(); });
  };
  const load = () => { const b = MODES[mode].b; it = parse(b[idx % b.length]); user = it.gaps.map(() => ""); caps = it.pcs.map(() => false); pen = MODES[mode].pens[mode === "caps" ? 0 : 0]; checked = false;
    root.querySelector(".msg").textContent = ""; root.querySelector(".chk").style.display = ""; root.querySelector(".nxt").style.display = "none"; draw(); };
  const check = () => {
    checked = true; draw();
    const bad = it.gaps.filter((g, i) => g.m !== user[i]).length + it.pcs.filter((p, i) => caps[i] !== it.cap[i]).length, m = root.querySelector(".msg");
    if (!bad) { m.innerHTML = `<span style="color:var(--ok)">Every mark is in the right place. Read it aloud: <i>${esc(it.exp)}</i></span>`; addXP(4); root.querySelectorAll(".g.ok").forEach(e => e.classList.add("pd")); }
    else m.innerHTML = `<span style="color:var(--warn)">${bad} place${bad > 1 ? "s" : ""} to fix. Red = wrong, dashed amber = something missing. <a href="#" class="sh">Show the answer</a></span>`;
    const sh = m.querySelector(".sh"); if (sh) sh.onclick = ev => { ev.preventDefault(); m.innerHTML = `Answer: <b>${esc(it.exp)}</b>`; };
    root.querySelector(".chk").style.display = "none"; root.querySelector(".nxt").style.display = "";
  };
  return {
    title: "Punctuation fixer",
    intro: "This sentence has lost its punctuation! Choose a pen, then tap the gaps between words (or letters) where it belongs. Use Aa on a word for a capital letter.",
    html() { return `<div class="explore" id="pf">${css}<div class="modes"></div><div class="pens"></div><div class="line" aria-live="polite"></div><div class="msg"></div><div class="row"><button class="btn chk">Check</button><button class="btn nxt" style="display:none">Next sentence</button><button class="btn ghost rst">Start again</button></div></div>`; },
    init() { root = $("#pf"); mode = pickMode(); idx = Math.random() * 5 | 0; load();
      root.querySelector(".chk").onclick = check; root.querySelector(".rst").onclick = load; root.querySelector(".nxt").onclick = () => { idx++; load(); }; }
  };
})();

  }).call(globalThis);
}
