// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/ratioBar.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* ratioBar — bar model + ratio table: set a : b, share a total, scale the ratio up and down */
(function(){
const css=`<style>
#rb .rb-bar{display:flex;height:54px;border-radius:12px;overflow:hidden;background:#fff;border:2px solid #cfd8ff;margin:4px 0}
#rb .rb-u{flex:1;display:grid;place-items:center;color:#fff;font-weight:900;font-size:13px;border-right:2px solid #fff;transition:flex .4s,background .3s;overflow:hidden;animation:rbin .3s}
#rb .rb-u.a{background:#3b5bdb}#rb .rb-u.b{background:#e8590c}
@keyframes rbin{from{transform:scaleY(.2);opacity:0}}
#rb .rb-t{width:100%;border-collapse:collapse;margin-top:12px;text-align:center;font-weight:800}
#rb .rb-t th,#rb .rb-t td{border:2px solid #cfd8ff;padding:7px 4px;background:#fff;font-size:15px}
#rb .rb-t th{background:var(--brand-soft);color:var(--brand);font-size:12px}
#rb .rb-t td.a{color:#3b5bdb}#rb .rb-t td.b{color:#c2410c}
#rb input[type=range]{width:100%;accent-color:var(--brand2)}
</style>`;
WIDGETS.ratioBar={
 title:"Ratio bar model",
 intro:"Set the ratio, then change the total to share. Drag the slider to scale the ratio up and see the table fill in.",
 html(){return css+`<div class="explore" id="rb">
 <div class="row spread" style="margin-bottom:8px"><div class="row"><b style="color:#3b5bdb">A</b><button class="btn ghost st" data-t="a-">−</button><span class="stat" id="rb-a" style="color:#3b5bdb">2</span><button class="btn ghost st" data-t="a+">+</button></div>
 <div class="row"><b style="color:#c2410c">B</b><button class="btn ghost st" data-t="b-">−</button><span class="stat" id="rb-b" style="color:#c2410c">3</span><button class="btn ghost st" data-t="b+">+</button></div></div>
 <div class="small">Bar model: each block is 1 part</div><div class="rb-bar" id="rb-bar"></div>
 <div class="row spread" style="margin-top:8px"><span class="small">Total to share</span><span class="stat" id="rb-tot">50</span></div>
 <input type="range" id="rb-rt" min="1" max="20" value="10" aria-label="total to share">
 <div class="rb-bar" id="rb-vals" style="height:40px"></div>
 <table class="rb-t" id="rb-tab"></table>
 <p class="small" id="rb-say" style="text-align:center;margin:10px 0 0"></p></div>`},
 init(){
  const box=$("#rb");let a=2,b=3,k=10;
  function draw(){
   $("#rb-a").textContent=a;$("#rb-b").textContent=b;const parts=a+b;const tot=parts*k;
   $("#rb-bar").innerHTML=[...Array(a)].map(()=>'<div class="rb-u a">1 part</div>').join("")+[...Array(b)].map(()=>'<div class="rb-u b">1 part</div>').join("");
   $("#rb-bar").querySelectorAll(".rb-u").forEach(u=>u.textContent=parts>8?"1":"1 part");
   $("#rb-rt").max=Math.max(2,Math.floor(60/parts)+1);$("#rb-rt").min=1;if(k>+$("#rb-rt").max)k=+$("#rb-rt").max;$("#rb-rt").value=k;
   $("#rb-tot").textContent=tot;
   $("#rb-vals").innerHTML=`<div class="rb-u a" style="flex:${a}">${a*k}</div><div class="rb-u b" style="flex:${b}">${b*k}</div>`;
   const g=gcd(a,b);
   const rows=[1,2,3,4,5].map(m=>`<td class="a">${a*m}</td>`);const rows2=[1,2,3,4,5].map(m=>`<td class="b">${b*m}</td>`);
   $("#rb-tab").innerHTML=`<tr><th></th>${[1,2,3,4,5].map(m=>`<th>× ${m}</th>`).join("")}</tr><tr><th>A</th>${rows.join("")}</tr><tr><th>B</th>${rows2.join("")}</tr>`;
   $("#rb-say").textContent=`${a}:${b}${g>1?` = ${a/g}:${b/g} in simplest form. `:" is already in its simplest form. "}One part is ${tot} ÷ ${parts} = ${k}, so A is ${a} × ${k} = ${a*k} and B is ${b} × ${k} = ${b*k}.`;
  }
  box.querySelectorAll("[data-t]").forEach(x=>x.onclick=()=>{const t=x.dataset.t;if(t==="a-")a=Math.max(1,a-1);if(t==="a+")a=Math.min(9,a+1);if(t==="b-")b=Math.max(1,b-1);if(t==="b+")b=Math.min(9,b+1);draw()});
  $("#rb-rt").oninput=e=>{k=+e.target.value;draw()};
  draw();
 }};
})();

  }).call(globalThis);
}
