// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/separation.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Separation techniques: filtration, evaporation, simple distillation, paper chromatography. Press play or scrub the slider. */
WIDGETS.separation = {
  title: "Separate the mixture",
  intro: "Choose a technique, press Play (or drag the slider) and watch what happens to each part of the mixture.",
  html() {
    return `<div class="explore" id="sp"><div class="row" style="justify-content:center;margin-bottom:6px"><button class="btn st" data-t="filt">Filtration</button><button class="btn ghost st" data-t="evap">Evaporation</button><button class="btn ghost st" data-t="dist">Distillation</button><button class="btn ghost st" data-t="chrom">Chromatography</button></div>
    <div class="small" id="spWhat" style="text-align:center;font-weight:800;color:var(--brand)"></div>
    <svg id="sps" viewBox="0 0 600 300" role="img" aria-label="Apparatus for separating a mixture"></svg>
    <div class="row" style="margin-top:4px"><button class="btn st" id="spP">Play</button><input type="range" id="spS" min="0" max="100" value="0" style="flex:1;min-width:120px;accent-color:var(--brand)" aria-label="Progress of the experiment"></div>
    <p class="small" id="spSay" style="margin:8px 0 0"></p></div>`;
  },
  init() {
    const svg = $("#sps"), rm = matchMedia("(prefers-reduced-motion: reduce)").matches, sl = $("#spS");
    let tech = "filt", p = 0, run = false, T = 0, last = performance.now(), used = {};
    const W = "#74c0fc", INFO = {
      filt: ["Sand and water (an insoluble solid and a liquid)", "Filtration: the tiny water particles pass through the holes in the filter paper, but the sand grains are too big, so they stay behind as the residue. The liquid that comes through is the filtrate."],
      evap: ["Salt solution (a soluble solid dissolved in a liquid)", "Evaporation: heating makes the water evaporate and escape as vapour. The salt does not evaporate, so it is left behind as crystals. (To make bigger crystals, heat gently, then leave the concentrated solution to cool: crystallisation.)"],
      dist: ["Salty water (to collect the water)", "Simple distillation: the solution boils and the water evaporates. The vapour is cooled in the condenser and turns back into liquid (condenses), which is collected as pure water. The salt stays behind in the flask. The thermometer reads about 100 °C while pure water boils."],
      chrom: ["Ink (a mixture of coloured substances)", "Paper chromatography: the solvent soaks up the paper and carries the substances with it. Substances that dissolve better in the solvent are carried further. Draw the start line in pencil, because pencil does not dissolve and run. Rf = distance moved by the substance ÷ distance moved by the solvent."],
    };
    const g = (a) => a; const clamp = (x, a = 0, b = 1) => Math.max(a, Math.min(b, x));
    const flame = (x, y) => `<path d="M${x} ${y}c-16 -4 -20 -24 -4 -40c2 12 10 14 10 -6c18 16 14 40 -6 46z" fill="#ff922b"/><path d="M${x} ${y}c-8 -2 -10 -12 -2 -20c2 6 6 6 6 -2c8 8 6 20 -4 22z" fill="#ffd43b"/>`;
    const lab = (x, y, t, a = "middle", c = "#141a33") => `<text x="${x}" y="${y}" text-anchor="${a}" font-size="13" font-weight="800" fill="${c}">${t}</text>`;
    const scenes = {
      filt() {
        let s = `<rect x="190" y="10" width="110" height="85" rx="6" fill="#f8fafc" stroke="#4a5275" stroke-width="4"/>`; const lv = 75 * (1 - .92 * p);
        s += `<rect x="194" y="${91 - lv}" width="102" height="${lv}" fill="${W}" opacity=".7"/>`; for (let i = 0; i < 14; i++) if (i / 14 < 1 - p * .85) s += `<circle cx="${205 + (i * 37) % 80}" cy="${88 - ((i * 23) % Math.max(8, lv - 6))}" r="3.4" fill="#a0783c"/>`;
        if (p > 0 && p < 1) s += `<path d="M262 95q4 25 -10 45" fill="none" stroke="${W}" stroke-width="5" stroke-linecap="round"/>`;
        s += `<path d="M195 140h100l-38 65h-24z" fill="#fff" stroke="#4a5275" stroke-width="4" stroke-linejoin="round"/><path d="M203 145l45 55h4l45 -55" fill="#fdf6e3" stroke="#c9a227" stroke-width="2" stroke-dasharray="4 3"/><rect x="242" y="205" width="12" height="20" fill="#fff" stroke="#4a5275" stroke-width="3"/>`;
        s += `<ellipse cx="248" cy="196" rx="${5 + 16 * p}" ry="${2 + 6 * p}" fill="#a0783c"/>`;
        s += `<rect x="205" y="235" width="86" height="58" rx="5" fill="#f8fafc" stroke="#4a5275" stroke-width="4"/><rect x="209" y="${289 - 48 * p * .9}" width="78" height="${48 * p * .9}" fill="${W}" opacity=".85"/>`;
        if (p > 0.02 && p < .99) for (let i = 0; i < 3; i++) s += `<circle cx="248" cy="${228 + ((T * 90 + i * 22) % 60) * (rm ? 0 : 1)}" r="3.2" fill="${W}"/>`;
        return s + lab(400, 40, "mixture of sand and water", "start") + lab(400, 173, "filter paper", "start") + lab(400, 200, "residue: sand", "start", "#8a6a2b") + lab(400, 268, "filtrate: water", "start", "#1971c2") + `<path d="M395 36l-95 6M395 169l-100 -14M395 196l-140 3M395 264l-105 6" stroke="#98a3c7" stroke-width="2" fill="none"/>`;
      },
      evap() {
        const lv = p < .85 ? 30 * (1 - p / .85) : 0; let s = `<path d="M170 170h260a130 62 0 0 1 -260 0z" fill="#f8fafc" stroke="#4a5275" stroke-width="5" stroke-linejoin="round"/>`;
        s += `<clipPath id="spc"><path d="M172 173h256a128 60 0 0 1 -256 0z"/></clipPath><rect x="170" y="${204 - lv}" width="260" height="60" fill="${W}" opacity=".75" clip-path="url(#spc)"/>`;
        for (let i = 0; i < Math.floor(clamp(p / .95) * 26); i++) { const x = 225 + (i * 47) % 150, y = 213 + ((i * 29) % 14); s += `<rect x="${x}" y="${y}" width="9" height="9" fill="#fff" stroke="#868e96" stroke-width="1.5" transform="rotate(${i * 20} ${x + 4} ${y + 4})"/>`; }
        s += `<path d="M215 240h170" stroke="#4a5275" stroke-width="4"/><path d="M240 240v40M360 240v40" stroke="#4a5275" stroke-width="5"/>` + (p < 1 ? flame(300, 292) : "");
        if (p > 0 && p < .95) for (let i = 0; i < 7; i++) { const f = ((T * .5 + i / 7) % 1); s += `<circle cx="${230 + i * 25 + Math.sin(f * 9 + i) * 8}" cy="${165 - f * 110}" r="${4 + f * 4}" fill="#adb5bd" opacity="${1 - f}"/>`; }
        return s + lab(455, 80, "water vapour escapes", "start", "#495057") + lab(455, 200, "salt crystals", "start") + lab(455, 225, "left behind", "start") + lab(30, 200, "evaporating dish", "start");
      },
      dist() {
        const T0 = 20 + 80 * clamp(p * 3.5), lv = 42 * (1 - .75 * p); let s = `<clipPath id="fl"><circle cx="120" cy="205" r="52"/></clipPath><circle cx="120" cy="205" r="52" fill="#f8fafc" stroke="#4a5275" stroke-width="5"/><rect x="108" y="105" width="24" height="60" fill="#f8fafc" stroke="#4a5275" stroke-width="4"/><rect x="66" y="${257 - lv - 8}" width="108" height="${lv + 8}" fill="${W}" opacity=".75" clip-path="url(#fl)"/>`;
        for (let i = 0; i < 10; i++) if (i < 3 + p * 8) s += `<rect x="${92 + (i * 17) % 55}" y="${247 - (i * 5) % 8}" width="6" height="6" fill="#fff" stroke="#868e96"/>`;
        s += `<rect x="112" y="60" width="8" height="120" rx="4" fill="#fff" stroke="#c92a2a" stroke-width="2"/><rect x="114" y="${180 - (T0 - 20) * 1.1}" width="4" height="${(T0 - 20) * 1.1}" fill="#e03131"/>${lab(150, 70, Math.round(T0) + " °C", "start", "#c92a2a")}`;
        s += `<path d="M132 118l60 -2" stroke="#4a5275" stroke-width="5" fill="none"/><path d="M190 110l170 68" stroke="#e7f5ff" stroke-width="30" stroke-linecap="round"/><path d="M190 110l170 68" stroke="#74c0fc" stroke-width="3" stroke-dasharray="1 0" opacity=".9"/><path d="M190 110l170 68" stroke="#4a5275" stroke-width="34" stroke-linecap="round" opacity=".18"/><path d="M190 110l170 68" stroke="#fff" stroke-width="12" stroke-linecap="round"/><path d="M190 110l170 68" stroke="#adb5bd" stroke-width="2"/>`;
        s += `<path d="M362 190l16 20" stroke="#4a5275" stroke-width="5"/>` + (p < 1 ? flame(120, 292) : "");
        if (p > .1 && p < .98) for (let i = 0; i < 6; i++) { const f = (T * .35 + i / 6) % 1; s += `<circle cx="${190 + f * 170}" cy="${110 + f * 68}" r="3.6" fill="${f > .55 ? W : "#adb5bd"}" opacity=".9"/>`; }
        s += `<rect x="395" y="215" width="90" height="72" rx="5" fill="#f8fafc" stroke="#4a5275" stroke-width="4"/><rect x="399" y="${283 - 60 * p * .8}" width="82" height="${60 * p * .8}" fill="${W}" opacity=".85"/>` + (p > .1 && p < .98 && !rm ? `<circle cx="378" cy="${214 + (T * 90) % 60}" r="3.2" fill="${W}"/>` : "");
        return s + lab(30, 40, "flask of salty water", "start") + lab(330, 60, "condenser (cold water jacket)", "middle", "#1971c2") + lab(400, 200, "pure water collected", "start", "#1971c2") + lab(330, 208, "cold water in ↗", "middle", "#1971c2") + lab(200, 92, "water out", "middle", "#1971c2");
      },
      chrom() {
        const sy = 240, fr = sy - p * 170; let s = `<rect x="180" y="100" width="240" height="185" rx="6" fill="#f8fafc" stroke="#4a5275" stroke-width="4"/><rect x="184" y="${sy}" width="232" height="41" fill="${W}" opacity=".55"/><rect x="215" y="24" width="170" height="${262 - 24}" fill="#fff" stroke="#adb5bd" stroke-width="2"/><rect x="216" y="${fr}" width="168" height="${262 - fr}" fill="${W}" opacity=".28"/><line x1="216" y1="${fr}" x2="384" y2="${fr}" stroke="#1971c2" stroke-width="2" stroke-dasharray="5 4"/>`;
        s += `<line x1="216" y1="222" x2="384" y2="222" stroke="#495057" stroke-width="2"/>`;
        const PG = { A: ["#e64980", .3], B: ["#4c6ef5", .55], C: ["#f59f00", .85] }, cols = [["ink", 242, ["A", "C"]], ["A", 292, ["A"]], ["B", 338, ["B"]], ["C", 372, ["C"]]];
        cols.forEach(([n, x, ps]) => { ps.forEach(k => { const y = 222 - PG[k][1] * (240 - fr); s += `<ellipse cx="${x}" cy="${y.toFixed(1)}" rx="${7 + p * 2}" ry="${6 + p * 5}" fill="${PG[k][0]}" opacity=".88"/>`; }); s += lab(x, 18, n === "ink" ? "ink ?" : n, "middle", "#4a5275"); });
        s += lab(30, 224, "pencil start line", "start", "#495057") + lab(30, 60, "paper strip", "start") + lab(430, 244, "solvent", "start", "#1971c2") + (p > .05 ? lab(430, fr + 4, "solvent front", "start", "#1971c2") : "");
        if (p >= .98) s += lab(430, 112, "Rf of A = " + PG.A[1].toFixed(2), "start", PG.A[0]) + lab(430, 132, "Rf of B = " + PG.B[1].toFixed(2), "start", PG.B[0]) + lab(430, 152, "Rf of C = " + PG.C[1].toFixed(2), "start", "#e67700") + lab(430, 186, "The ink contains A and C,", "start") + lab(430, 204, "but not B.", "start");
        return s;
      },
    };
    const draw = () => { svg.innerHTML = scenes[tech](); sl.value = Math.round(p * 100); $("#spWhat").textContent = "Mixture: " + INFO[tech][0]; $("#spSay").textContent = INFO[tech][1]; $("#spP").textContent = run ? "Pause" : p >= 1 ? "Replay" : "Play";
      document.querySelectorAll("#sp [data-t]").forEach(b => b.className = "btn st" + (b.dataset.t === tech ? "" : " ghost")); };
    document.querySelectorAll("#sp [data-t]").forEach(b => b.onclick = () => { tech = b.dataset.t; p = 0; run = false; draw(); });
    $("#spP").onclick = () => { if (p >= 1) p = 0; run = !run; draw(); };
    sl.oninput = () => { p = +sl.value / 100; run = false; if (p >= 1 && !used[tech]) { used[tech] = 1; addXP(2); } draw(); };
    const step = now => { if (!document.body.contains(svg)) return; const dt = Math.min(.05, (now - last) / 1000); last = now; if (!rm) T += dt; if (run) { p = Math.min(1, p + dt / 9); if (p >= 1) { run = false; if (!used[tech]) { used[tech] = 1; addXP(2); } } } if (run || (!rm && p > 0 && p < 1)) draw(); requestAnimationFrame(step); };
    draw(); requestAnimationFrame(step);
  },
};

  }).call(globalThis);
}
