// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/sharing.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* sharing — deal items into equal groups (sharing) or make groups of a size (grouping); remainders left over */
(function(){
const css=`<style>
#sh .sh-pool{display:flex;flex-wrap:wrap;gap:5px;justify-content:center;min-height:38px;background:#fff;border:2px dashed var(--line);border-radius:12px;padding:8px}
#sh .sh-i{width:24px;height:24px;border-radius:50%;background:#3b5bdb;box-shadow:0 2px 0 rgba(0,0,0,.2);animation:shpop .3s cubic-bezier(.3,1.6,.5,1)}
#sh .sh-i.rem{background:#e8590c}
@keyframes shpop{from{transform:scale(.2)}}
#sh .sh-groups{display:grid;gap:8px;margin-top:10px}
#sh .sh-g{background:#fff;border:2px solid #cfd8ff;border-radius:12px;min-height:66px;padding:6px;display:flex;flex-wrap:wrap;gap:4px;align-content:flex-start;justify-content:center;position:relative}
#sh .sh-g b{position:absolute;left:5px;top:1px;font-size:10px;color:var(--ink3)}
#sh .sh-g.full{border-color:var(--ok);background:var(--ok-soft)}
#sh .chip{border:2px solid var(--line);background:#fff;border-radius:99px;padding:5px 12px;font-weight:800;font-size:13px;color:var(--ink2)}
#sh .chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
</style>`;
WIDGETS.sharing={
 title:"Share and group",
 intro:"Choose how many things and how many groups, then deal them out one at a time. What is left over?",
 html(){return css+`<div class="explore" id="sh">
 <div class="row" style="margin-bottom:8px"><button class="chip on" data-m="share">Share between groups</button><button class="chip" data-m="group">Make groups of a size</button></div>
 <div class="row spread" style="margin-bottom:10px"><div class="row"><span class="small">Items</span><button class="btn ghost st" data-t="n-">−</button><span class="stat" id="sh-n">14</span><button class="btn ghost st" data-t="n+">+</button></div>
 <div class="row"><span class="small" id="sh-glab">Groups</span><button class="btn ghost st" data-t="g-">−</button><span class="stat" id="sh-g">4</span><button class="btn ghost st" data-t="g+">+</button></div></div>
 <div class="sh-pool" id="sh-pool"></div><div class="sh-groups" id="sh-groups"></div>
 <div class="row" style="justify-content:center;margin-top:10px"><button class="btn" id="sh-deal">Deal one</button><button class="btn ghost" id="sh-all">Deal all</button><button class="btn ghost" id="sh-rst">Reset</button></div>
 <div class="stat" id="sh-eq" style="text-align:center;margin-top:10px;font-size:20px"></div>
 <p class="small" id="sh-say" style="text-align:center;margin:4px 0 0"></p></div>`},
 init(){
  const box=$("#sh");let mode="share",N=14,G=4,dealt=0,timer=0;const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;
  const nGroups=()=>mode==="share"?G:Math.max(1,Math.floor(N/G));
  // group of a fixed size G: fill groups of G in order; share: round robin over G groups
  const slotOf=k=>mode==="share"?k%G:Math.floor(k/G);
  function limit(){return Math.floor(N/G)*G}
  function draw(){
   $("#sh-n").textContent=N;$("#sh-g").textContent=G;$("#sh-glab").textContent=mode==="share"?"Groups":"Group size";
   const ng=nGroups(),cols=Math.min(ng,ng>6?4:3);const gs=$("#sh-groups");gs.style.gridTemplateColumns=`repeat(${Math.min(cols,4)},1fr)`;
   const per=[...Array(ng)].map(()=>0);for(let k=0;k<dealt;k++)per[slotOf(k)]++;
   const lim=limit();
   gs.innerHTML=per.map((c,i)=>`<div class="sh-g${mode==="group"?(c===G?" full":""):(dealt>=lim&&c>0&&per.every(x=>x===per[0])?" full":"")}"><b>${i+1}</b>${[...Array(c)].map(()=>'<i class="sh-i"></i>').join("")}</div>`).join("");
   if(mode==="group"&&ng*0===0){/* hide unused empty group when not needed */}
   const left=N-dealt;const pool=$("#sh-pool");
   const remStart=lim; pool.innerHTML=[...Array(left)].map((_,j)=>`<i class="sh-i${dealt+j>=remStart&&dealt>=0&&dealt>=lim?" rem":""}" style="animation:none"></i>`).join("")||'<span class="small">Nothing left over</span>';
   const q=mode==="share"?Math.floor(N/G):Math.floor(N/G),r=N%G;
   const fin=dealt>=lim;
   $("#sh-eq").textContent=fin?(mode==="share"?`${N} ÷ ${G} = ${q}${r?` remainder ${r}`:""}`:`${N} ÷ ${G} = ${q}${r?` remainder ${r}`:""}`):`${dealt} of ${lim} dealt`;
   $("#sh-say").textContent=fin?(r?`${r} left over, so ${G} doesn't go into ${N} exactly — the ${r} left over form the remainder.`:(mode==="share"?`Each group gets ${q}, nothing left over.`:`Exactly ${q} groups of ${G}, nothing left over.`)):(mode==="share"?"One each, round and round…":`Filling groups of ${G}…`);
   $("#sh-deal").disabled=fin;$("#sh-all").disabled=fin;
  }
  function deal1(){if(dealt<limit()){dealt++;draw()}}
  function all(){clearInterval(timer);if(reduce){dealt=limit();draw();addXP(2);return}
   timer=setInterval(()=>{if(dealt>=limit()){clearInterval(timer);addXP(2);return}dealt++;draw()},130)}
  const reset=()=>{clearInterval(timer);dealt=0;draw()};
  $("#sh-deal").onclick=deal1;$("#sh-all").onclick=all;$("#sh-rst").onclick=reset;
  box.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>{mode=b.dataset.m;G=mode==="share"?4:3;box.querySelectorAll("[data-m]").forEach(x=>x.classList.toggle("on",x===b));reset()});
  box.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>{const t=b.dataset.t;if(t==="n-")N=Math.max(2,N-1);if(t==="n+")N=Math.min(36,N+1);if(t==="g-")G=Math.max(2,G-1);if(t==="g+")G=Math.min(10,G+1);reset()});
  draw();
 }};
})();

  }).call(globalThis);
}
