// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/storyMountain.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* storyMountain: drag (or tap) the shuffled story events onto the five parts of a story mountain; a climber scales the mountain as you go. Stories original. */
WIDGETS.storyMountain = (() => {
  const STAGES = [["Opening", "meet the character and the place"], ["Build-up", "something starts to go wrong"], ["Climax", "the most exciting, scary moment"], ["Resolution", "the problem is solved"], ["Ending", "how it all finishes"]];
  const ST = [
    ["The Runaway Balloon", ["Nia holds a bright red balloon at the village fair.", "A sudden gust of wind snatches the string from her fingers.", "The balloon drifts towards a thorny hedge and Nia dives to save it!", "She grabs the string a whisker before the thorns can pop it.", "Nia ties the balloon to her wrist and skips all the way home."]],
    ["The Lost Robot", ["A small robot called Pip wakes up alone in a quiet junkyard.", "Pip follows a trail of glowing screws towards a strange humming sound.", "A huge crane swings down and threatens to scoop Pip up!", "Pip scrambles into a tunnel, and the driver spots him and stops.", "The driver takes Pip home and mends his wobbly wheel."]],
    ["The Midnight Dragon", ["Every night, Sam hears scratching from the cellar under the bakery.", "One evening he creeps down the steps, holding a candle.", "In the dark corner two glowing eyes blink open and a tiny dragon sneezes fire!", "Sam offers the dragon a warm bun and it calms right down.", "From then on, the dragon heats the bakery ovens every morning."]],
  ];
  const PT = [[20, 100], [80, 62], [150, 14], [220, 62], [280, 100]];
  let root, si = 0, pool = [], placed = [], sel = -1, cnt = 0;
  const dragT = (r, sel, drop) => r.querySelectorAll(sel).forEach(t => { t.style.touchAction = "none";
    t.onkeydown = e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); drop(t, null); } };
    t.onpointerdown = e => { e.preventDefault(); const b = t.getBoundingClientRect(), ox = e.clientX - b.left, oy = e.clientY - b.top; let g = null;
      const mv = ev => { if (!g) { if (Math.hypot(ev.clientX - e.clientX, ev.clientY - e.clientY) < 6) return; g = t.cloneNode(true); g.style.cssText = `position:fixed;z-index:99;pointer-events:none;left:0;top:0;width:${b.width}px;transform:rotate(-3deg);opacity:.93`; document.body.appendChild(g); t.style.opacity = .35; }
        g.style.left = ev.clientX - ox + "px"; g.style.top = ev.clientY - oy + "px"; const z = document.elementFromPoint(ev.clientX, ev.clientY); r.querySelectorAll(".smz").forEach(x => x.classList.toggle("ov", !!z && x === z.closest(".smz"))); };
      const up = ev => { removeEventListener("pointermove", mv); removeEventListener("pointerup", up); removeEventListener("pointercancel", up); r.querySelectorAll(".smz").forEach(x => x.classList.remove("ov")); if (g) { g.remove(); t.style.opacity = ""; drop(t, document.elementFromPoint(ev.clientX, ev.clientY)); } else drop(t, null); };
      addEventListener("pointermove", mv); addEventListener("pointerup", up); addEventListener("pointercancel", up); }; });
  const css = `<style>#sm .tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:6px}#sm .tb{border:2px solid var(--line);background:#fff;border-radius:99px;padding:6px 12px;font-weight:800;font-size:13px;cursor:pointer;color:var(--ink2)}#sm .tb.on{background:var(--brand);border-color:var(--brand);color:#fff}
  #sm svg{max-height:120px}#sm .clg{transition:transform .8s cubic-bezier(.4,1.4,.5,1)}
  #sm .smz{border:2px dashed #b9c5f5;border-radius:12px;padding:8px 10px;margin:5px 0;background:#fff;min-height:50px;transition:background .2s,border-color .2s,transform .2s}
  #sm .smz b{font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:var(--brand);display:block}#sm .smz small{display:block;color:var(--ink3);font-size:11px}
  #sm .smz.ov{background:var(--brand-soft);border-color:var(--brand);transform:scale(1.02)}#sm .smz.done{border:2px solid var(--ok);background:var(--ok-soft);animation:smpop .4s}@keyframes smpop{40%{transform:scale(1.04)}}
  #sm .smz .tx{font-weight:700;font-size:14.5px}
  #sm .pl{display:grid;gap:6px;margin:10px 0}#sm .sc{background:#fff;border:2px solid var(--line);border-radius:12px;padding:9px 12px;font-weight:600;font-size:14.5px;cursor:grab;box-shadow:0 2px 0 var(--line);text-align:left;width:100%;font-family:inherit;color:var(--ink)}
  #sm .sc.sel{border-color:var(--brand);box-shadow:0 0 0 3px var(--brand-soft)}#sm .sc.bad{animation:smsh .4s;border-color:var(--bad)}@keyframes smsh{25%{transform:translateX(-8px)}75%{transform:translateX(8px)}}
  #sm .msg{font-weight:800;min-height:24px;margin:6px 0}</style>`;
  const svg = () => { const lastDone = placed.reduce((m, v, i) => v ? i : m, -1), pt = PT[Math.max(0, lastDone)]; return `<svg viewBox="0 0 300 116" role="img" aria-label="A story mountain with a climber"><polygon points="0,116 20,100 80,62 150,14 220,62 280,100 300,116" fill="#c9d4ff"/><polygon points="150,14 128,38 142,34 150,42 160,33 172,38" fill="#fff"/><polyline points="${PT.map(p => p.join(",")).join(" ")}" fill="none" stroke="#5b73d6" stroke-width="2" stroke-dasharray="5 4"/>${PT.map((p, i) => `<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="${placed[i] ? "#137a4a" : "#fff"}" stroke="#5b73d6" stroke-width="2"/>`).join("")}<g class="clg" style="transform:translate(${pt[0]}px,${pt[1] - 12}px)"><circle r="7" fill="#c2410c"/><path d="M-5 -7 L0 -14 L5 -7z" fill="#c2410c"/></g></svg>`; };
  const draw = () => {
    const S = ST[si];
    root.querySelector(".tabs").innerHTML = ST.map((s, i) => `<button class="tb${i === si ? " on" : ""}" data-s="${i}">${s[0]}</button>`).join("");
    root.querySelector(".mt").innerHTML = svg();
    root.querySelector(".zones").innerHTML = STAGES.map((g, i) => `<div class="smz${placed[i] ? " done" : ""}" data-z="${i}"><b>${i + 1}. ${g[0]}</b>${placed[i] ? `<div class="tx">${S[1][i]}</div>` : `<small>${g[1]}</small>`}</div>`).join("");
    root.querySelector(".pl").innerHTML = pool.filter(i => !placed[i]).map(i => `<button class="sc${sel === i ? " sel" : ""}" data-i="${i}">${S[1][i]}</button>`).join("");
    const all = placed.every(Boolean); root.querySelector(".msg").innerHTML = all ? `<span style="color:var(--ok)">The whole story climbs the mountain. Read it aloud from the bottom left!</span>` : sel >= 0 ? "Now tap the part of the mountain where it belongs." : "";
    root.querySelector(".tabs").querySelectorAll("button").forEach(b => b.onclick = () => { si = +b.dataset.s; reset(); });
    root.querySelectorAll(".smz").forEach(z => z.onclick = () => { if (sel >= 0) place(sel, +z.dataset.z); });
    dragT(root, ".sc", (t, el) => { const i = +t.dataset.i, z = el && el.closest(".smz"); if (z) place(i, +z.dataset.z); else { sel = sel === i ? -1 : i; draw(); } });
    if (all && !root._won) { root._won = 1; addXP(6); }
  };
  const place = (i, z) => {
    if (placed[z]) return; if (i === z) { placed[z] = true; sel = -1; addXP(1); draw(); }
    else { const c = root.querySelector(`.sc[data-i="${i}"]`); if (c) { c.classList.remove("bad"); void c.offsetWidth; c.classList.add("bad"); } root.querySelector(".msg").innerHTML = `<span style="color:var(--bad)">Not there. Ask: what has just happened? What comes next?</span>`; sel = -1; }
  };
  const reset = () => { pool = shuffle([0, 1, 2, 3, 4]); if (pool.every((v, i) => v === i)) pool.reverse(); placed = [0, 0, 0, 0, 0].map(() => false); sel = -1; root._won = 0; draw(); };
  return {
    title: "Climb the story mountain",
    intro: "These five events are jumbled. Drag each one (or tap it, then tap a part of the mountain) to the right place: opening, build-up, climax, resolution, ending.",
    html() { return `<div class="explore" id="sm">${css}<div class="tabs"></div><div class="mt"></div><div class="zones"></div><div class="msg"></div><div class="pl"></div><div class="row"><button class="btn ghost rs">Mix them up again</button></div></div>`; },
    init() { root = $("#sm"); si = Math.random() * ST.length | 0; root.querySelector(".rs").onclick = reset; reset(); }
  };
})();

  }).call(globalThis);
}
