// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/tenFrame.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* tenFrame — drag counters into a ten frame; the part-whole (number bond) model updates live */
(function(){
const css=`<style>
#tf .tf-frame{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;background:var(--brand);padding:8px;border-radius:14px;max-width:340px;margin:0 auto}
#tf .tf-cell{aspect-ratio:1;background:#fff;border-radius:9px;position:relative;touch-action:none}
#tf .tf-cell.hot{box-shadow:0 0 0 3px #ffd43b inset}
#tf .tf-c{position:absolute;inset:11%;border-radius:50%;cursor:grab;touch-action:none;box-shadow:0 3px 0 rgba(0,0,0,.25);animation:tfpop .25s cubic-bezier(.3,1.6,.5,1);border:0;padding:0}
#tf .tf-c.red{background:#e8590c}#tf .tf-c.blue{background:#3b5bdb}
#tf .tf-c.drag{position:fixed;z-index:50;pointer-events:none;box-shadow:0 12px 24px rgba(0,0,0,.3);animation:none}
@keyframes tfpop{from{transform:scale(.3)}to{transform:scale(1)}}
#tf .tf-bond{display:flex;flex-direction:column;align-items:center;margin-top:12px}
#tf .tf-bond .b{width:56px;height:56px;border-radius:50%;display:grid;place-items:center;font-weight:900;font-size:22px;color:#fff;transition:background .3s}
#tf .tf-legs{display:flex;justify-content:center;gap:0;width:150px;height:26px}
#tf .tf-legs svg{width:100%;height:26px}
#tf .chip{border:2px solid var(--line);background:#fff;border-radius:99px;padding:5px 12px;font-weight:800;font-size:13px;color:var(--ink2)}
#tf .chip.on{border-color:var(--brand2);background:var(--brand-soft);color:var(--brand)}
</style>`;
WIDGETS.tenFrame={
 title:"Fill the ten frame",
 intro:"Tap a square to add a counter. Tap a counter to change its colour, or drag it to a new square. The number bond shows the whole and its two parts.",
 html(){return css+`<div class="explore" id="tf">
 <div class="row spread" style="margin-bottom:10px"><div class="row"><span class="small">Frame</span><button class="chip on" data-n="10">10</button><button class="chip" data-n="20">20</button></div>
 <div class="row"><button class="btn ghost st" id="tf-fill">Fill</button><button class="btn ghost st" id="tf-clr">Clear</button></div></div>
 <div class="tf-frame" id="tf-frame"></div>
 <div class="tf-bond"><div class="b" id="tf-w" style="background:var(--brand)">0</div>
 <div class="tf-legs"><svg viewBox="0 0 150 26"><path d="M75 0 L28 26 M75 0 L122 26" stroke="#9fb0ff" stroke-width="3" fill="none"/></svg></div>
 <div style="display:flex;gap:44px"><div class="b" id="tf-a" style="background:#e8590c">0</div><div class="b" id="tf-b" style="background:#3b5bdb">0</div></div></div>
 <div class="stat" id="tf-eq" style="text-align:center;margin-top:10px;font-size:22px"></div>
 <p class="small" id="tf-say" style="text-align:center;margin:6px 0 0"></p></div>`},
 init(){
  const box=$("#tf");let size=10,cells=Array(10).fill(null);const fr=$("#tf-frame");let drag=null;
  function render(){
   fr.style.gridTemplateColumns="repeat(5,1fr)";
   fr.innerHTML=cells.map((c,i)=>`<div class="tf-cell" data-i="${i}">${c?`<button class="tf-c ${c}" data-i="${i}" aria-label="counter, ${c}"></button>`:""}</div>`).join("");
   const a=cells.filter(c=>c==="red").length,b=cells.filter(c=>c==="blue").length,w=a+b;
   $("#tf-w").textContent=w;$("#tf-a").textContent=a;$("#tf-b").textContent=b;
   $("#tf-eq").textContent=w?`${a} + ${b} = ${w}`:"";
   $("#tf-say").textContent=!w?"The frame is empty.":w===size?`Full frame! ${a} and ${b} make ${size}.`:`${size-w} more to fill the frame. ${size} − ${w} = ${size-w}`;
  }
  function setSize(n){size=n;const old=cells;cells=Array(n).fill(null).map((_,i)=>old[i]||null);box.querySelectorAll("[data-n]").forEach(b=>b.classList.toggle("on",+b.dataset.n===n));render()}
  box.querySelectorAll("[data-n]").forEach(b=>b.onclick=()=>setSize(+b.dataset.n));
  $("#tf-clr").onclick=()=>{cells.fill(null);render()};
  $("#tf-fill").onclick=()=>{const n=size===10?6:12;cells=cells.map((_,i)=>i<n?"red":i<n+Math.floor((size-n)/2)?"blue":null);render();addXP(1)};
  fr.addEventListener("pointerdown",e=>{
   const c=e.target.closest(".tf-c"),cell=e.target.closest(".tf-cell");if(!cell)return;
   const i=+cell.dataset.i;
   if(!c){cells[i]="red";render();addXP(0);return}
   drag={i,x:e.clientX,y:e.clientY,el:c,moved:false,color:cells[i]};c.setPointerCapture(e.pointerId);
  });
  fr.addEventListener("pointermove",e=>{if(!drag)return;const d=drag;
   if(!d.moved&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<6)return;
   if(!d.moved){d.moved=true;const r=d.el.getBoundingClientRect();d.el.style.width=r.width+"px";d.el.style.height=r.height+"px";d.el.classList.add("drag");d.el.style.inset="auto"}
   d.el.style.left=e.clientX-d.el.offsetWidth/2+"px";d.el.style.top=e.clientY-d.el.offsetHeight/2+"px";
   fr.querySelectorAll(".tf-cell").forEach(c=>c.classList.remove("hot"));
   const t=document.elementFromPoint(e.clientX,e.clientY);const cell=t&&t.closest&&t.closest(".tf-cell");if(cell)cell.classList.add("hot");
  });
  const end=e=>{if(!drag)return;const d=drag;drag=null;
   if(!d.moved){cells[d.i]=cells[d.i]==="red"?"blue":"red";render();return}
   d.el.style.display="none";const t=document.elementFromPoint(e.clientX,e.clientY);const cell=t&&t.closest&&t.closest(".tf-cell");
   if(cell&&fr.contains(cell)){const j=+cell.dataset.i;if(!cells[j]||j===d.i){cells[d.i]=null;cells[j]=d.color}}
   else cells[d.i]=null;
   render()};
  fr.addEventListener("pointerup",end);fr.addEventListener("pointercancel",end);
  render();
 }};
})();

  }).call(globalThis);
}
