// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/transformGrid.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* transformGrid — reflect in a mirror line, rotate about a centre, enlarge from a centre; drag the shape and the centre */
(function(){
  const RM=matchMedia("(prefers-reduced-motion: reduce)").matches, N=6, C=26, O=180, X=x=>O+x*C, Y=y=>O-y*C, cl=v=>Math.max(-N,Math.min(N,v));
  const BASE=[[1,1],[3,1],[3,2],[2,2],[2,4],[1,4]], LB="ABCDEF";
  const MODES={reflect:"Reflect",rotate:"Rotate",enlarge:"Enlarge"};
  const MIR={v:"vertical line x =",h:"horizontal line y =",d1:"the line y = x",d2:"the line y = −x"};
  WIDGETS.transformGrid={title:"Transform a shape",intro:"Pick a transformation. Drag the blue shape, the mirror line or the centre of turn and watch the image move.",
  html(){ return `<div class="explore" id="tgw">
    <div class="row" style="justify-content:center;margin-bottom:8px" id="tgm">${Object.keys(MODES).map(k=>`<button class="btn ghost pr fk" data-m="${k}">${MODES[k]}</button>`).join("")}</div>
    <svg id="tgs" viewBox="0 0 360 360" role="img" aria-label="Coordinate grid showing a shape and its transformed image" style="touch-action:none;max-width:420px;margin:0 auto;user-select:none"><rect x="6" y="6" width="348" height="348" rx="14" fill="#fff" stroke="#cfd8ff"/><g id="tgg"></g><g id="tgd"></g></svg>
    <div class="row" style="justify-content:center;margin:10px 0" id="tgc"></div>
    <p class="small" id="tgsay" style="text-align:center;margin:0 0 8px;font-weight:800;color:var(--brand)"></p><div class="row" id="tgchips" style="gap:6px;justify-content:center"></div></div>`; },
  init(){
    const svg=$("#tgs"), dyn=$("#tgd"); let mode="reflect", pts=BASE.map(p=>p.slice()), mir="v", ma=0, ctr=[0,0], rot=90, disp=90, sf=2, dfk=2, drag=null, last=null, raf=0;
    let g=""; for(let i=-N;i<=N;i++){ const s=i?"#e3e8fb":"#141a33", w=i?1:2; g+=`<line x1="${X(i)}" y1="${Y(-N)}" x2="${X(i)}" y2="${Y(N)}" stroke="${s}" stroke-width="${w}"/><line x1="${X(-N)}" y1="${Y(i)}" x2="${X(N)}" y2="${Y(i)}" stroke="${s}" stroke-width="${w}"/>`;
      if(i&&i%2===0) g+=`<text x="${X(i)}" y="${Y(0)+13}" font-size="10" font-weight="800" text-anchor="middle" fill="#7b83a3">${i}</text><text x="${X(0)-5}" y="${Y(i)+3.5}" font-size="10" font-weight="800" text-anchor="end" fill="#7b83a3">${i}</text>`; }
    $("#tgg").innerHTML=g;
    const rd=v=>Math.round(v*100)/100;
    const img=(k)=>{ return pts.map(([x,y])=>{
      if(mode==="reflect"){ if(mir==="v") return [2*ma-x,y]; if(mir==="h") return [x,2*ma-y]; if(mir==="d1") return [y,x]; return [-y,-x]; }
      const dx=x-ctr[0], dy=y-ctr[1];
      if(mode==="rotate"){ const t=(k===undefined?disp:k)*Math.PI/180, c=Math.cos(t), s=Math.sin(t); return [ctr[0]+dx*c+dy*s, ctr[1]-dx*s+dy*c]; }
      const f=k===undefined?dfk:k; return [ctr[0]+dx*f, ctr[1]+dy*f]; }); };
    const P=(ps,st)=>`<polygon points="${ps.map(p=>X(p[0])+","+Y(p[1])).join(" ")}" ${st}/>`;
    const draw=()=>{
      const im=img(); let h="";
      if(mode==="reflect"){ const ln=mir==="v"?[ma,-N,ma,N]:mir==="h"?[-N,ma,N,ma]:mir==="d1"?[-N,-N,N,N]:[-N,N,N,-N];
        h+=`<line x1="${X(ln[0])}" y1="${Y(ln[1])}" x2="${X(ln[2])}" y2="${Y(ln[3])}" stroke="#ff5a3c" stroke-width="3" stroke-dasharray="9 5" stroke-linecap="round"/>`;
        if(mir==="v"||mir==="h") h+=`<circle class="tgm" cx="${mir==="v"?X(ma):X(-N)+8}" cy="${mir==="v"?Y(-N)-8:Y(ma)}" r="11" fill="#ff5a3c" stroke="#fff" stroke-width="3" style="cursor:grab"/>`;
        h+=pts.map((p,i)=>`<line x1="${X(p[0])}" y1="${Y(p[1])}" x2="${X(im[i][0])}" y2="${Y(im[i][1])}" stroke="#ff5a3c" stroke-width="1" opacity=".4"/>`).join("");
      } else { if(mode==="rotate"){ const r=Math.hypot(pts[0][0]-ctr[0],pts[0][1]-ctr[1])*C; if(r>4) h+=`<circle cx="${X(ctr[0])}" cy="${Y(ctr[1])}" r="${r}" fill="none" stroke="#ff5a3c" stroke-width="1" stroke-dasharray="3 4" opacity=".5"/>`; }
        else h+=pts.map((p,i)=>`<line x1="${X(ctr[0])}" y1="${Y(ctr[1])}" x2="${X(im[i][0])}" y2="${Y(im[i][1])}" stroke="#ff5a3c" stroke-width="1" opacity=".45"/>`).join(""); }
      h+=P(im,'fill="#ff5a3c" fill-opacity=".18" stroke="#ff5a3c" stroke-width="2.5" stroke-linejoin="round"');
      h+=P(pts,'class="tgb" fill="#3b5bdb" fill-opacity=".25" stroke="#1e3a8a" stroke-width="3" stroke-linejoin="round" style="cursor:grab"');
      h+=pts.map((p,i)=>`<text x="${X(p[0])}" y="${Y(p[1])+4}" font-size="10" font-weight="900" fill="#1e3a8a" text-anchor="middle" pointer-events="none">${LB[i]}</text>`).join("");
      h+=im.map((p,i)=>`<text x="${X(p[0])}" y="${Y(p[1])+4}" font-size="10" font-weight="900" fill="#c2410c" text-anchor="middle" pointer-events="none">${LB[i]}′</text>`).join("");
      if(mode!=="reflect") h+=`<g class="tgk" style="cursor:grab"><circle cx="${X(ctr[0])}" cy="${Y(ctr[1])}" r="12" fill="#fff" fill-opacity=".01"/><path d="M${X(ctr[0])-9} ${Y(ctr[1])}h18M${X(ctr[0])} ${Y(ctr[1])-9}v18" stroke="#ff5a3c" stroke-width="4" stroke-linecap="round"/></g>`;
      dyn.innerHTML=h;
      const fin=img(mode==="rotate"?rot:mode==="enlarge"?sf:undefined), f=v=>rd(v);
      $("#tgchips").innerHTML=pts.map((p,i)=>`<span class="pill" style="background:#fff;border:2px solid #cfd8ff;font-weight:800">${LB[i]} <span class="stat" style="font-size:14px">(${p[0]}, ${p[1]})</span> → <span style="color:#c2410c">${LB[i]}′ (${f(fin[i][0])}, ${f(fin[i][1])})</span></span>`).join("");
      $("#tgsay").textContent=mode==="reflect"?`Reflect in ${MIR[mir]}${mir==="v"||mir==="h"?" "+ma:""}: each point lands the same distance on the other side of the mirror.`:mode==="rotate"?`Rotate ${Math.abs(rot)}° ${rot<0?"anticlockwise":"clockwise"} about (${ctr[0]}, ${ctr[1]}): the shape turns but keeps its size.`:`Enlarge by scale factor ${sf} from centre (${ctr[0]}, ${ctr[1]}): every distance from the centre is multiplied by ${sf}.`;
    };
    const ctl=()=>{ let h=""; const btn=(a,l,on)=>`<button class="btn ghost fk${on?" sel":""}" data-a="${a}">${l}</button>`;
      if(mode==="reflect") h=Object.keys(MIR).map(k=>btn("mir"+k,{v:"vertical",h:"horizontal",d1:"y = x",d2:"y = −x"}[k],mir===k)).join("")+(mir==="v"||mir==="h"?`<span class="small">${mir==="v"?"x":"y"} =</span><button class="btn ghost st" data-a="m-">−</button><span class="stat">${ma}</span><button class="btn ghost st" data-a="m+">+</button>`:"");
      if(mode==="rotate") h=btn("r90","90° clockwise",rot===90)+btn("r180","180°",rot===180)+btn("r270","90° anticlockwise",rot===-90||rot===270);
      if(mode==="enlarge") h=`<span class="small">Scale factor</span>`+[1,2,3].map(v=>btn("s"+v,v,sf===v)).join("");
      $("#tgc").innerHTML=h;
      $("#tgc").querySelectorAll("button").forEach(b=>b.onclick=()=>{ const a=b.dataset.a; if(a.startsWith("mir")){ mir=a.slice(3); ma=0; } else if(a==="m-") ma=cl(ma-1); else if(a==="m+") ma=cl(ma+1); else if(a[0]==="r"){ const nr=a==="r90"?90:a==="r180"?180:-90; anim("rot",nr); } else if(a[0]==="s") anim("sf",+a.slice(1)); ctl(); draw(); addXP(1); }); };
    function anim(w,to){ cancelAnimationFrame(raf); if(w==="rot"){ rot=to; const a0=RM?to:0, t0=performance.now(); if(RM){ disp=to; draw(); return; } const st=n=>{ const t=Math.min(1,(n-t0)/900), e=t*t*(3-2*t); disp=to*e; draw(); if(t<1) raf=requestAnimationFrame(st); }; raf=requestAnimationFrame(st); } else { sf=to; if(RM){ dfk=to; draw(); return; } const f0=dfk, t0=performance.now(); const st=n=>{ const t=Math.min(1,(n-t0)/700), e=t*t*(3-2*t); dfk=f0+(to-f0)*e; draw(); if(t<1) raf=requestAnimationFrame(st); }; raf=requestAnimationFrame(st); } }
    const pos=e=>{ const q=svg.createSVGPoint(); q.x=e.clientX; q.y=e.clientY; const r=q.matrixTransform(svg.getScreenCTM().inverse()); return [(r.x-O)/C,(O-r.y)/C]; };
    svg.addEventListener("pointerdown",e=>{ const t=e.target, p=pos(e);
      if(t.closest(".tgm")) drag={k:"m"}; else if(t.closest(".tgk")) drag={k:"c"}; else if(t.closest(".tgb")) drag={k:"b",s:p,orig:pts.map(q=>q.slice())}; else return;
      svg.setPointerCapture(e.pointerId); e.preventDefault(); });
    svg.addEventListener("pointermove",e=>{ if(!drag) return; const p=pos(e);
      if(drag.k==="m"){ ma=cl(Math.round(mir==="v"?p[0]:p[1])); ctl(); }
      else if(drag.k==="c"){ ctr=[cl(Math.round(p[0])),cl(Math.round(p[1]))]; }
      else { const dx=Math.round(p[0]-drag.s[0]), dy=Math.round(p[1]-drag.s[1]); const xs=drag.orig.map(q=>q[0]), ys=drag.orig.map(q=>q[1]); const ax=Math.max(-N-Math.min(...xs),Math.min(N-Math.max(...xs),dx)), ay=Math.max(-N-Math.min(...ys),Math.min(N-Math.max(...ys),dy)); pts=drag.orig.map(q=>[q[0]+ax,q[1]+ay]); }
      draw(); });
    const up=()=>{ if(drag){ addXP(1); drag=null; } }; svg.addEventListener("pointerup",up); svg.addEventListener("pointercancel",up);
    $("#tgm").querySelectorAll(".pr").forEach(b=>b.onclick=()=>{ mode=b.dataset.m; if(mode==="rotate"){ disp=0; anim("rot",rot||90); } if(mode==="enlarge"){ dfk=1; anim("sf",sf); } sel(); ctl(); draw(); });
    const sel=()=>$("#tgm").querySelectorAll(".pr").forEach(b=>b.classList.toggle("sel",b.dataset.m===mode)); sel(); ctl(); draw();
  }};
})();

  }).call(globalThis);
}
