// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/waves.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* Waves: transverse vs longitudinal; frequency, amplitude and wave speed sliders; wavelength = speed / frequency */
WIDGETS.waves = {
  title: "Make a wave",
  intro: "Change the frequency, amplitude and speed. Switch between a transverse and a longitudinal wave. What happens to the wavelength?",
  html() {
    const sl = (id, lab, min, max, step, val) => `<label class="small" style="flex:1;min-width:140px">${lab} <b class="stat" id="${id}v"></b><input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${val}" style="width:100%;accent-color:var(--brand)"></label>`;
    return `<div class="explore" id="wv"><svg id="wvs" viewBox="0 0 600 220" role="img" aria-label="An animated wave with its wavelength and amplitude marked"></svg>
    <div class="row" style="justify-content:center;margin:6px 0"><button class="btn st" id="wvT">Transverse</button><button class="btn ghost st" id="wvL">Longitudinal</button><button class="btn ghost st" id="wvP">Pause</button><button class="btn ghost st" id="wvS" style="display:none">Step</button></div>
    <div class="row spread" style="gap:10px">${sl("wvF", "Frequency", 0.5, 3, 0.1, 1)}${sl("wvA", "Amplitude", 0.1, 0.6, 0.05, 0.4)}${sl("wvV", "Wave speed", 1, 4, 0.5, 2)}</div>
    <div class="row spread" style="margin-top:6px"><span class="small">Wavelength <b class="stat" id="wvW"></b></span><span class="small">Time period <b class="stat" id="wvTp"></b></span><span class="small">Speed = frequency × wavelength</span></div>
    <p class="small" id="wvSay" style="margin:8px 0 0"></p></div>`;
  },
  init() {
    const svg = $("#wvs"), rm = matchMedia("(prefers-reduced-motion: reduce)").matches, PX = 90; // 90 px per metre; 600 px = 6.7 m
    let tr = true, run = !rm, t = 0, last = performance.now(), touched = 0;
    const g = id => +$("#" + id).value;
    const say = () => tr ? "Transverse wave (like light or a wave on a rope): the particles vibrate up and down, at right angles to the direction the wave travels. The red dot shows one particle: it does not travel along with the wave." : "Longitudinal wave (like sound): the particles vibrate backwards and forwards, parallel to the direction the wave travels, making compressions (squashed up) and rarefactions (spread out). Wavelength = compression to compression.";
    const draw = () => {
      const f = g("wvF"), A = g("wvA"), v = g("wvV"), lam = v / f, lpx = lam * PX, Tp = 1 / f;
      $("#wvFv").textContent = f.toFixed(1) + " Hz"; $("#wvAv").textContent = A.toFixed(2) + " m"; $("#wvVv").textContent = v.toFixed(1) + " m/s"; $("#wvW").textContent = lam.toFixed(2) + " m"; $("#wvTp").textContent = Tp.toFixed(2) + " s";
      const ph = x => 2 * Math.PI * (x / lpx - f * t); let s = ""; const mid = 105;
      if (tr) {
        const ap = A * PX * 1.6; let d = ""; for (let x = 10; x <= 590; x += 4) d += (x === 10 ? "M" : "L") + x + " " + (mid - ap * Math.sin(ph(x))).toFixed(1);
        s += `<line x1="10" y1="${mid}" x2="590" y2="${mid}" stroke="#98a3c7" stroke-dasharray="6 6"/><path d="${d}" fill="none" stroke="#3b5bdb" stroke-width="5" stroke-linecap="round"/>`;
        for (let x = 30; x < 590; x += 40) s += `<circle cx="${x}" cy="${(mid - ap * Math.sin(ph(x))).toFixed(1)}" r="5.5" fill="#fff" stroke="#3b5bdb" stroke-width="3"/>`;
        s += `<circle cx="310" cy="${(mid - ap * Math.sin(ph(310))).toFixed(1)}" r="8" fill="#e03131" stroke="#fff" stroke-width="2"/>`;
        let c1 = lpx * (.25 + f * t); c1 = ((c1 % lpx) + lpx) % lpx; while (c1 < 30) c1 += lpx; // first crest after x=30
        s += `<line x1="${c1}" y1="${mid}" x2="${c1}" y2="${mid - ap}" stroke="#e8590c" stroke-width="3"/><text x="${c1 + 8}" y="${mid - ap / 2 + 4}" font-size="12" font-weight="800" fill="#e8590c">amplitude</text>`;
        if (c1 + lpx < 590) s += `<line x1="${c1}" y1="${mid - ap - 16}" x2="${c1 + lpx}" y2="${mid - ap - 16}" stroke="#137a4a" stroke-width="3"/><path d="M${c1} ${mid - ap - 16}l8 -5v10zM${c1 + lpx} ${mid - ap - 16}l-8 -5v10z" fill="#137a4a"/><text x="${c1 + lpx / 2}" y="${mid - ap - 24}" text-anchor="middle" font-size="12" font-weight="800" fill="#137a4a">wavelength</text>`;
      } else {
        const ap = Math.min(A * PX * .75, lpx / 8); const cols = 74, dx = 580 / cols, rowsY = [55, 80, 105, 130, 155];
        for (let i = 0; i <= cols; i++) { const x0 = 10 + i * dx, x = x0 + ap * Math.sin(ph(x0)); rowsY.forEach((y, r) => { s += `<circle cx="${x.toFixed(1)}" cy="${y}" r="${r === 2 && i === 36 ? 5.5 : 3.6}" fill="${r === 2 && i === 36 ? "#e03131" : "#3b5bdb"}"/>`; }); }
        let cc = lpx * (.5 + f * t), rr = lpx * (f * t); cc = ((cc % lpx) + lpx) % lpx; while (cc < 40) cc += lpx; rr = ((rr % lpx) + lpx) % lpx; while (rr < 40) rr += lpx;
        s += `<text x="${cc}" y="182" text-anchor="middle" font-size="11" font-weight="800" fill="#e8590c">compression</text><text x="${rr}" y="196" text-anchor="middle" font-size="11" font-weight="800" fill="#4a5275">rarefaction</text>`;
        if (cc + lpx < 590) s += `<line x1="${cc}" y1="40" x2="${cc + lpx}" y2="40" stroke="#137a4a" stroke-width="3"/><path d="M${cc} 40l8 -5v10zM${cc + lpx} 40l-8 -5v10z" fill="#137a4a"/><text x="${cc + lpx / 2}" y="32" text-anchor="middle" font-size="12" font-weight="800" fill="#137a4a">wavelength</text>`;
      }
      s += `<path d="M20 ${tr ? 200 : 214}h60l-10 -6m10 6l-10 6" fill="none" stroke="#4a5275" stroke-width="2"/><text x="90" y="${tr ? 204 : 218}" font-size="11" font-weight="800" fill="#4a5275">wave travels this way</text>`;
      svg.innerHTML = s; $("#wvSay").textContent = say();
    };
    const set = tra => { tr = tra; $("#wvT").className = "btn st" + (tr ? "" : " ghost"); $("#wvL").className = "btn st" + (tr ? " ghost" : ""); draw(); addXP(1); };
    $("#wvT").onclick = () => set(true); $("#wvL").onclick = () => set(false);
    ["wvF", "wvA", "wvV"].forEach(id => $("#" + id).oninput = () => { draw(); if (++touched === 6) addXP(2); });
    $("#wvP").onclick = () => { run = !run; $("#wvP").textContent = run ? "Pause" : "Play"; }; $("#wvP").textContent = run ? "Pause" : "Play";
    if (rm) $("#wvS").style.display = ""; $("#wvS").onclick = () => { t += .1; draw(); };
    const step = now => { if (!document.body.contains(svg)) return; const dt = Math.min(.05, (now - last) / 1000); last = now; if (run) { t += dt * .6; draw(); } raf = requestAnimationFrame(step); };
    let raf; draw(); raf = requestAnimationFrame(step);
  },
};

  }).call(globalThis);
}
