// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/wordMaker.js — do not edit; run `npm run hub:widgets`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
/* wordMaker: drop a suffix / prefix / plural ending onto a root word and see the spelling rule (drop the e, double the consonant, y to i ...) animate. Roots and rules original. */
WIDGETS.wordMaker = (() => {
  const SFX = ["ing", "ed", "er", "est", "ly", "ful", "less", "ness", "ment", "able", "ity", "ise"];
  const PFX = ["un", "re", "dis", "mis", "pre", "sub", "super", "anti", "auto", "inter", "im", "in", "il", "ir"];
  const PLU = ["s", "es", "ies", "ves", "irregular"];
  const R = {
    suffix: `hop:ing,ed,er stop:ing,ed,er swim:ing,er run:ing,er big:er,est sad:er,est,ly,ness admit:ed,ing forget:ing,able,ful hope:ing,ed,ful,less make:ing,er bake:ing,ed,er nice:er,est,ly,ness care:ing,ed,ful,less use:ing,ed,ful,less excite:ing,ed,ment admire:ing,ed,able notice:ing,ed,able agree:ing,ed,ment,able happy:er,est,ly,ness easy:er,est,ly,ness lucky:er,est,ly,ness carry:ing,ed,er hurry:ing,ed empty:ness,er,ed,ing beauty:ful play:ing,ed,er,ful enjoy:ing,ed,ment,able help:ing,ed,er,ful,less kind:ly,ness,er,est quick:ly,er,est,ness real:ise,ly,ity special:ly,ise active:ity pure:ity,ly final:ly,ise comfort:able`,
    prefix: `happy:un kind:un appear:dis,re agree:dis like:dis,un spell:mis,re behave:mis lead:mis do:un,re write:re build:re view:pre,re,inter heat:pre,re marine:sub merge:sub human:super market:super possible:im legal:il regular:ir visible:in polite:im movable:im national:inter active:inter,re clockwise:anti biography:auto place:mis,re,dis cover:un,re,dis connect:dis,re trust:dis,mis solve:dis`,
    plural: `cat:s box:es bus:es dish:es church:es fox:es wish:es city:ies baby:ies lady:ies party:ies day:s key:s monkey:s leaf:ves wolf:ves knife:ves shelf:ves roof:s potato:es hero:es piano:s photo:s child:irregular man:irregular mouse:irregular tooth:irregular foot:irregular`,
  };
  const IRR = { child: "children", man: "men", mouse: "mice", tooth: "teeth", foot: "feet" };
  const MEAN = { un: "not / the opposite", re: "again / back", dis: "not / the opposite", mis: "wrongly", pre: "before", sub: "under", super: "above / beyond", anti: "against", auto: "self", inter: "between", im: "not (before m, p, b)", in: "not", il: "not (before l)", ir: "not (before r)" };
  const WHY = { s: "Most plurals just add -s (also after a vowel + y: keys, days).", es: "Words ending in s, x, z, ch, sh (and a few -o words) add -es.", ies: "A consonant then y: change the y to i and add -es.", ves: "Some words ending in f or fe change to -ves.", irregular: "Irregular plural: the whole word changes." };
  const parse = m => R[m].split(" ").map(x => { const [r, a] = x.split(":"); return [r, a.split(",")]; });
  const dbl = r => /^[^aeiou]*[aeiou][^aeiouwxy]$/.test(r) || ["forget", "admit"].includes(r);
  const tag = (c, k) => ({ c, k });
  const sfx = (r, s) => {
    const vw = /^[aeiou]/.test(s), L = [...r].map(c => tag(c, "")); let note = "Just add it on: the root word does not change.";
    if (/[^aeiou]y$/.test(r) && s[0] !== "i") { L[L.length - 1] = tag("y", "gone"); L.push(tag("i", "chg")); note = "Consonant + y: change the y to an i before the ending."; }
    else if (r.endsWith("e") && s[0] === "e") { note = "Only one e where they meet."; L.push(...[...s].map((c, i) => tag(c, i ? "aff" : "gone"))); return { L, note, w: r + s.slice(1) }; }
    else if (vw && r.endsWith("e") && !r.endsWith("ee") && !(/^[ao]/.test(s) && /[cg]e$/.test(r))) { L[L.length - 1] = tag("e", "gone"); note = "Silent e: drop it before an ending that starts with a vowel."; }
    else if (r.endsWith("e") && /^[ao]/.test(s) && /[cg]e$/.test(r)) note = "Keep the e after c or g so the sound stays soft.";
    else if (r.endsWith("e") && !vw) note = "The ending starts with a consonant, so the silent e stays.";
    else if (vw && dbl(r)) { L.push(tag(r.slice(-1), "dup")); note = "Short vowel + one consonant at the end: double the consonant before a vowel ending."; }
    L.push(...[...s].map(c => tag(c, "aff")));
    return { L, note, w: L.filter(x => x.k !== "gone").map(x => x.c).join("") };
  };
  const pfx = (r, p) => { const L = [...[...p].map(c => tag(c, "aff")), ...[...r].map(c => tag(c, ""))]; const d = p.slice(-1) === r[0]; if (d) { L[p.length - 1].k = "dup"; L[p.length].k = "dup"; }
    return { L, note: (d ? "Double letters where prefix and root meet: keep both. " : "The root word does not change. ") + `${p}- means "${MEAN[p]}".`, w: p + r }; };
  const plu = (r, c) => {
    const L = [...r].map(x => tag(x, "")); if (c === "s") L.push(tag("s", "aff")); else if (c === "es") L.push(tag("e", "aff"), tag("s", "aff"));
    else if (c === "ies") { if (!/[^aeiou]y$/.test(r)) return null; L[L.length - 1] = tag("y", "gone"); L.push(tag("i", "chg"), tag("e", "aff"), tag("s", "aff")); }
    else if (c === "ves") { if (!/fe?$/.test(r)) return null; L.splice(/fe$/.test(r) ? -2 : -1, 9, tag(/fe$/.test(r) ? "f" : "f", "gone"), ...(/fe$/.test(r) ? [tag("e", "gone")] : []), tag("v", "chg"), tag("e", "aff"), tag("s", "aff")); }
    else return IRR[r] ? { L: [...IRR[r]].map(x => tag(x, "aff")), w: IRR[r] } : null;
    return { L, w: L.filter(x => x.k !== "gone").map(x => x.c).join("") };
  };
  let root, mode = "suffix", idx = 0, list, found = new Set(), last = null;
  const css = `<style>#wm .tabs{display:flex;gap:6px;margin-bottom:10px}#wm .tb{flex:1;border:2px solid var(--line);background:#fff;border-radius:12px;padding:8px 4px;font-weight:800;font-size:14px;cursor:pointer;color:var(--ink2)}#wm .tb.on{background:var(--brand);border-color:var(--brand);color:#fff}
  #wm .mach{display:flex;align-items:center;gap:8px;justify-content:center;flex-wrap:wrap;margin:6px 0}
  #wm .rt{font-size:26px;font-weight:900;padding:10px 20px;border-radius:14px;background:#fff;border:3px solid var(--brand);color:var(--brand);min-width:110px;text-align:center}
  #wm .nv{border:2px solid var(--line);background:#fff;border-radius:50%;width:38px;height:38px;font-size:18px;font-weight:900;cursor:pointer}
  #wm .drop{min-width:70px;height:54px;border:3px dashed var(--brand2);border-radius:14px;display:grid;place-items:center;background:var(--brand-soft);font-weight:900;color:var(--brand);font-size:20px}
  #wm .chp{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0;justify-content:center}
  #wm .af{border:2px solid #0f766e;color:#0f766e;background:#fff;border-radius:12px;padding:7px 13px;font-weight:900;font-size:17px;cursor:grab;box-shadow:0 3px 0 var(--line)}
  #wm .res{min-height:64px;font-size:34px;font-weight:900;text-align:center;letter-spacing:.02em;padding:6px}
  #wm .res span{display:inline-block;animation:wmin .45s both}@keyframes wmin{from{opacity:0;transform:translateY(-20px) scale(1.5)}}
  #wm .res .aff{color:#0f766e}#wm .res .gone{color:var(--bad);text-decoration:line-through;opacity:.7;font-size:.75em}#wm .res .dup{color:var(--ok);background:var(--ok-soft);border-radius:6px}#wm .res .chg{color:#c2410c;background:var(--warn-soft);border-radius:6px}
  #wm .res.bad{color:var(--bad);animation:wmsh .4s}@keyframes wmsh{25%{transform:translateX(-8px)}75%{transform:translateX(8px)}}
  #wm .note{font-weight:700;min-height:44px;text-align:center;padding:0 6px}#wm .made{margin-top:8px;font-size:13px;color:var(--ink2)}#wm .made b{background:#e9f9ee;color:var(--ok);border-radius:99px;padding:2px 9px;margin:2px;display:inline-block}</style>`;
  const draw = () => {
    const [r, ok] = list[idx], aff = mode === "suffix" ? SFX : mode === "prefix" ? PFX : PLU, P = mode === "prefix";
    root.querySelector(".tabs").innerHTML = ["suffix", "prefix", "plural"].map(m => `<button class="tb${m === mode ? " on" : ""}" data-m="${m}">${m === "suffix" ? "Suffixes" : m === "prefix" ? "Prefixes" : "Plurals"}</button>`).join("");
    root.querySelector(".rt").textContent = r;
    root.querySelector(".chp").innerHTML = aff.map(a => `<button class="af" data-a="${a}">${mode === "plural" ? (a === "irregular" ? "irregular" : "+" + a) : P ? a + "-" : "-" + a}</button>`).join("");
    root.querySelector(".made").innerHTML = found.size ? "Words made: " + [...found].map(w => `<b>${w}</b>`).join("") : "";
    root.querySelectorAll(".tb").forEach(b => b.onclick = () => { mode = b.dataset.m; list = parse(mode); idx = Math.random() * list.length | 0; last = null; show(null); draw(); });
    dragAff();
  };
  const show = res => {
    const out = root.querySelector(".res"), nt = root.querySelector(".note"), dz = root.querySelector(".drop"); out.classList.remove("bad");
    if (!res) { out.innerHTML = ""; nt.textContent = "Drag an ending onto the box (or just tap it)."; dz.textContent = "+"; return; }
    dz.textContent = res.lbl; out.innerHTML = res.L.map((x, i) => `<span class="${x.k}" style="animation-delay:${i * 50}ms">${x.c}</span>`).join("");
    if (res.bad) { out.classList.add("bad"); out.style.animation = "none"; void out.offsetWidth; out.style.animation = ""; }
    nt.innerHTML = res.msg;
  };
  const apply = a => {
    const [r, ok] = list[idx]; let res, lbl = mode === "prefix" ? a + "-" : mode === "plural" ? (a === "irregular" ? "irregular" : "+" + a) : "-" + a;
    if (mode === "plural") { const good = ok[0]; res = plu(r, a) || { L: [...r].map(c => tag(c, "")), w: r, none: 1 };
      if (a === good) { res.msg = `<span style="color:var(--ok)">Correct: ${r} &rarr; <b>${res.w}</b>.</span> ${WHY[a]}`; if (!found.has(res.w)) { found.add(res.w); addXP(2); } }
      else { if (res.none) res.L = [...r].map(c => tag(c, "")); res.bad = 1; res.msg = `<span style="color:var(--bad)">${res.none ? "That change is not possible for this word." : `'${res.w}' is not right.`}</span> Think: ${WHY[good]}`; } }
    else if (!ok.includes(a)) { res = mode === "suffix" ? sfx(r, a) : pfx(r, a); res.bad = 1; res.msg = `<span style="color:var(--bad)">'${res.w}' is not a real word.</span> Try another ending.`; }
    else { res = mode === "suffix" ? sfx(r, a) : pfx(r, a); res.msg = `<span style="color:var(--ok)"><b>${res.w}</b></span> &mdash; ${res.note}`; if (!found.has(res.w)) { found.add(res.w); addXP(2); } }
    res.lbl = lbl; show(res);
  };
  const dragAff = () => root.querySelectorAll(".af").forEach(t => { t.style.touchAction = "none";
    t.onkeydown = e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); apply(t.dataset.a); } };
    t.onpointerdown = e => { e.preventDefault(); const b = t.getBoundingClientRect(), ox = e.clientX - b.left, oy = e.clientY - b.top; let g = null;
      const mv = ev => { if (!g) { if (Math.hypot(ev.clientX - e.clientX, ev.clientY - e.clientY) < 6) return; g = t.cloneNode(true); g.style.cssText = "position:fixed;z-index:99;pointer-events:none;left:0;top:0;transform:rotate(-4deg)"; document.body.appendChild(g); t.style.opacity = .35; } g.style.left = ev.clientX - ox + "px"; g.style.top = ev.clientY - oy + "px"; };
      const up = ev => { removeEventListener("pointermove", mv); removeEventListener("pointerup", up); removeEventListener("pointercancel", up); if (g) { g.remove(); t.style.opacity = ""; const el = document.elementFromPoint(ev.clientX, ev.clientY); if (el && el.closest(".mach")) apply(t.dataset.a); } else apply(t.dataset.a); };
      addEventListener("pointermove", mv); addEventListener("pointerup", up); addEventListener("pointercancel", up); }; });
  return {
    title: "Word-maker machine",
    intro: "Pick a root word, then drag an ending (or a beginning) onto the machine. Watch what happens to the spelling: which letters get dropped, doubled or changed?",
    html() { return `<div class="explore" id="wm">${css}<div class="tabs"></div><div class="mach"><button class="nv pv" aria-label="previous word">&lsaquo;</button><div class="rt"></div><div class="drop">+</div><button class="nv nx" aria-label="next word">&rsaquo;</button></div><div class="chp"></div><div class="res" aria-live="polite"></div><div class="note"></div><div class="made"></div></div>`; },
    init() {
      root = $("#wm"); const t = (typeof L !== "undefined" ? L.title : "").toLowerCase();
      mode = /plural/.test(t) ? "plural" : /prefix|un-|re-|dis-|mis-|sub-|super-|de-/.test(t) ? "prefix" : "suffix"; list = parse(mode);
      const m = t.match(/-([a-z]+)/); const want = m && SFX.concat(PFX).includes(m[1]) ? m[1] : "";
      idx = (want && list.findIndex(x => x[1].includes(want)) >= 0) ? list.findIndex(x => x[1].includes(want)) : Math.random() * list.length | 0;
      root.querySelector(".pv").onclick = () => { idx = (idx + list.length - 1) % list.length; show(null); draw(); };
      root.querySelector(".nx").onclick = () => { idx = (idx + 1) % list.length; show(null); draw(); };
      draw(); show(null);
    }
  };
})();

  }).call(globalThis);
}
