// Compass Quest content bank - KS2 geography: compass directions, map reading (keys, grid references, scale),
// coordinates, continents/oceans/countries, and basic physical geography. Every fact below is standard KS1-KS3
// UK geography curriculum content (8-point compass, four-figure grid references, the seven continents and five
// oceans, well-known physical features) - nothing invented or ambiguous. Server and client both import this file,
// so the item bank marking the game and the item bank rendering it are the exact same data (BACKEND-PATTERN.md).
import type { QuizItem } from "../quiz/core";
import { COMPASS_EXTRA } from "./content.extra";

const opt = (...pairs: [string, string][]) => pairs.map(([id, text]) => ({ id, text }));

const COMPASS_BASE: QuizItem[] = [
  // ── 8-point compass directions ──────────────────────────────────────────────────────────────────────────────
  { key: "cq-dir-1", topics: ["compass"], difficulty: 1, prompt: "Which direction is directly opposite North?", options: opt(["n", "North"], ["s", "South"], ["e", "East"], ["w", "West"]), correctId: "s", explanation: "North and South sit at opposite ends of the compass rose." },
  { key: "cq-dir-2", topics: ["compass"], difficulty: 1, prompt: "Which direction is directly opposite East?", options: opt(["w", "West"], ["e", "East"], ["n", "North"], ["s", "South"]), correctId: "w", explanation: "East and West are opposite points on the compass." },
  { key: "cq-dir-3", topics: ["compass"], difficulty: 1, prompt: "On a compass, which direction is at the top?", options: opt(["n", "North"], ["s", "South"], ["e", "East"], ["w", "West"]), correctId: "n", explanation: "By convention, maps and compasses always put North at the top." },
  { key: "cq-dir-4", topics: ["compass"], difficulty: 2, prompt: "What is the direction exactly between North and East called?", options: opt(["ne", "North-East"], ["nw", "North-West"], ["se", "South-East"], ["sw", "South-West"]), correctId: "ne", explanation: "North-East sits halfway between North and East on an 8-point compass." },
  { key: "cq-dir-5", topics: ["compass"], difficulty: 2, prompt: "What is the direction exactly between South and West called?", options: opt(["sw", "South-West"], ["se", "South-East"], ["nw", "North-West"], ["ne", "North-East"]), correctId: "sw", explanation: "South-West sits halfway between South and West." },
  { key: "cq-dir-6", topics: ["compass"], difficulty: 2, prompt: "What is the direction exactly between North and West called?", options: opt(["nw", "North-West"], ["ne", "North-East"], ["sw", "South-West"], ["se", "South-East"]), correctId: "nw", explanation: "North-West sits halfway between North and West." },
  { key: "cq-dir-7", topics: ["compass"], difficulty: 2, prompt: "What is the direction exactly between South and East called?", options: opt(["se", "South-East"], ["sw", "South-West"], ["ne", "North-East"], ["nw", "North-West"]), correctId: "se", explanation: "South-East sits halfway between South and East." },
  { key: "cq-dir-8", topics: ["compass"], difficulty: 1, prompt: "If you are facing North and turn to face South, how far have you turned?", options: opt(["180", "180 degrees (a half turn)"], ["90", "90 degrees (a quarter turn)"], ["45", "45 degrees"], ["360", "360 degrees (a full turn)"]), correctId: "180", explanation: "North to South is a half turn: 180 degrees." },
  { key: "cq-dir-9", topics: ["compass"], difficulty: 2, prompt: "If you are facing North and turn 90 degrees clockwise, which way are you now facing?", options: opt(["e", "East"], ["w", "West"], ["s", "South"], ["n", "North"]), correctId: "e", explanation: "Turning clockwise from North by a quarter turn (90 degrees) faces you East." },
  { key: "cq-dir-10", topics: ["compass"], difficulty: 2, prompt: "If you are facing East and turn 90 degrees anticlockwise, which way are you now facing?", options: opt(["n", "North"], ["s", "South"], ["w", "West"], ["e", "East"]), correctId: "n", explanation: "Turning anticlockwise from East by a quarter turn faces you North." },
  { key: "cq-dir-11", topics: ["compass"], difficulty: 3, prompt: "How many degrees are there between each of the 8 main compass points?", options: opt(["45", "45 degrees"], ["30", "30 degrees"], ["90", "90 degrees"], ["60", "60 degrees"]), correctId: "45", explanation: "360 degrees shared across 8 points is 45 degrees between each one." },
  { key: "cq-dir-12", topics: ["compass"], difficulty: 1, prompt: "Which tool do explorers use to find compass directions?", options: opt(["compass", "A compass"], ["ruler", "A ruler"], ["thermometer", "A thermometer"], ["clock", "A clock"]), correctId: "compass", explanation: "A magnetic compass needle always points towards magnetic North." },

  // ── map reading: keys, scale, grid references ───────────────────────────────────────────────────────────────
  { key: "cq-map-1", topics: ["maps"], difficulty: 1, prompt: "What is the small box on a map that explains what the symbols mean called?", options: opt(["key", "The key (or legend)"], ["scale", "The scale"], ["compass", "The compass rose"], ["title", "The title"]), correctId: "key", explanation: "A map's key (or legend) lists each symbol and what it stands for." },
  { key: "cq-map-2", topics: ["maps"], difficulty: 2, prompt: "A map's scale says 1 cm = 1 km. Two towns are 4 cm apart on the map. How far apart are they in real life?", options: opt(["4", "4 km"], ["1", "1 km"], ["40", "40 km"], ["8", "8 km"]), correctId: "4", explanation: "At 1 cm = 1 km, 4 cm on the map means 4 real kilometres." },
  { key: "cq-map-3", topics: ["maps"], difficulty: 2, prompt: "A map's scale says 1 cm = 2 km. Two villages are 3 cm apart on the map. How far apart are they in real life?", options: opt(["6", "6 km"], ["3", "3 km"], ["1.5", "1.5 km"], ["9", "9 km"]), correctId: "6", explanation: "3 cm x 2 km per cm = 6 km." },
  { key: "cq-map-4", topics: ["maps"], difficulty: 1, prompt: "In a four-figure grid reference, which number do you read FIRST?", options: opt(["easting", "The one along the bottom (eastings)"], ["northing", "The one up the side (northings)"], ["either", "Either one, it doesn't matter"], ["height", "The height above sea level"]), correctId: "easting", explanation: "Grid references are read \"along the corridor, then up the stairs\" - eastings (along the bottom) come first." },
  { key: "cq-map-5", topics: ["maps"], difficulty: 2, prompt: "What do contour lines on a map show?", options: opt(["height", "The height/shape of the land"], ["rivers", "Where rivers flow"], ["roads", "Where roads are"], ["population", "How many people live there"]), correctId: "height", explanation: "Contour lines join points of equal height, showing hills and valleys." },
  { key: "cq-map-6", topics: ["maps"], difficulty: 2, prompt: "On a contour map, what does it mean if the contour lines are very close together?", options: opt(["steep", "The land is steep"], ["flat", "The land is flat"], ["water", "There is a lake"], ["road", "There is a road"]), correctId: "steep", explanation: "Closely spaced contour lines mean height changes quickly - steep ground." },
  { key: "cq-map-7", topics: ["maps"], difficulty: 1, prompt: "What are the imaginary lines running EAST-WEST around the globe called?", options: opt(["latitude", "Lines of latitude"], ["longitude", "Lines of longitude"], ["equator2", "Lines of the equator"], ["meridian", "Meridian lines only"]), correctId: "latitude", explanation: "Lines of latitude run east-west, parallel to the Equator." },
  { key: "cq-map-8", topics: ["maps"], difficulty: 1, prompt: "What are the imaginary lines running NORTH-SOUTH around the globe called?", options: opt(["longitude", "Lines of longitude"], ["latitude", "Lines of latitude"], ["tropic", "Tropic lines only"], ["contour", "Contour lines"]), correctId: "longitude", explanation: "Lines of longitude run north-south, from pole to pole." },
  { key: "cq-map-9", topics: ["maps"], difficulty: 2, prompt: "What is the line of latitude at 0 degrees called?", options: opt(["equator", "The Equator"], ["meridian", "The Prime Meridian"], ["tropic", "The Tropic of Cancer"], ["arctic", "The Arctic Circle"]), correctId: "equator", explanation: "The Equator is the line of latitude at 0 degrees, halfway between the poles." },
  { key: "cq-map-10", topics: ["maps"], difficulty: 2, prompt: "What is the line of longitude at 0 degrees called?", options: opt(["prime", "The Prime Meridian"], ["equator", "The Equator"], ["tropic", "The Tropic of Capricorn"], ["dateline", "The International Date Line"]), correctId: "prime", explanation: "The Prime Meridian (0 degrees longitude) passes through Greenwich, London." },
  { key: "cq-map-11", topics: ["maps"], difficulty: 3, prompt: "What is a compass symbol usually used to show on a map?", options: opt(["north", "Which way is North"], ["scale", "The distance scale"], ["altitude", "The altitude"], ["population", "Population size"]), correctId: "north", explanation: "A compass rose or simple arrow on a map shows which way North points." },

  // ── continents and oceans ───────────────────────────────────────────────────────────────────────────────────
  { key: "cq-cont-1", topics: ["continents"], difficulty: 1, prompt: "How many continents are there?", options: opt(["7", "7"], ["5", "5"], ["6", "6"], ["8", "8"]), correctId: "7", explanation: "The seven continents are Africa, Antarctica, Asia, Europe, North America, Oceania and South America." },
  { key: "cq-cont-2", topics: ["continents"], difficulty: 1, prompt: "Which is the largest continent by area?", options: opt(["asia", "Asia"], ["africa", "Africa"], ["europe", "Europe"], ["namerica", "North America"]), correctId: "asia", explanation: "Asia is the largest continent, covering about 30% of Earth's land area." },
  { key: "cq-cont-3", topics: ["continents"], difficulty: 1, prompt: "Which continent is entirely covered in ice and has no permanent population?", options: opt(["antarctica", "Antarctica"], ["arctic", "The Arctic"], ["greenland", "Greenland"], ["siberia", "Siberia"]), correctId: "antarctica", explanation: "Antarctica is the southernmost continent, almost entirely covered by an ice sheet." },
  { key: "cq-cont-4", topics: ["continents"], difficulty: 1, prompt: "Which continent is the United Kingdom part of?", options: opt(["europe", "Europe"], ["asia", "Asia"], ["africa", "Africa"], ["namerica", "North America"]), correctId: "europe", explanation: "The UK is in Europe, off the north-west coast of the mainland." },
  { key: "cq-cont-5", topics: ["continents"], difficulty: 2, prompt: "Which continent contains the Sahara, the world's largest hot desert?", options: opt(["africa", "Africa"], ["asia", "Asia"], ["australia", "Australia"], ["samerica", "South America"]), correctId: "africa", explanation: "The Sahara Desert stretches across northern Africa." },
  { key: "cq-cont-6", topics: ["continents"], difficulty: 2, prompt: "Which continent is the Amazon Rainforest mostly found in?", options: opt(["samerica", "South America"], ["africa", "Africa"], ["asia", "Asia"], ["oceania", "Oceania"]), correctId: "samerica", explanation: "Most of the Amazon Rainforest lies in Brazil, in South America." },
  { key: "cq-cont-7", topics: ["oceans"], difficulty: 1, prompt: "Which is the largest ocean on Earth?", options: opt(["pacific", "The Pacific Ocean"], ["atlantic", "The Atlantic Ocean"], ["indian", "The Indian Ocean"], ["arctic", "The Arctic Ocean"]), correctId: "pacific", explanation: "The Pacific Ocean is the largest and deepest ocean, covering more area than all the land on Earth combined." },
  { key: "cq-cont-8", topics: ["oceans"], difficulty: 1, prompt: "Which ocean lies between the UK and North America?", options: opt(["atlantic", "The Atlantic Ocean"], ["pacific", "The Pacific Ocean"], ["indian", "The Indian Ocean"], ["southern", "The Southern Ocean"]), correctId: "atlantic", explanation: "The Atlantic Ocean separates Europe/Africa from the Americas." },
  { key: "cq-cont-9", topics: ["oceans"], difficulty: 2, prompt: "How many oceans do geographers usually name?", options: opt(["5", "5"], ["4", "4"], ["3", "3"], ["6", "6"]), correctId: "5", explanation: "The five oceans are the Pacific, Atlantic, Indian, Southern and Arctic." },
  { key: "cq-cont-10", topics: ["oceans"], difficulty: 2, prompt: "Which ocean surrounds the North Pole?", options: opt(["arctic", "The Arctic Ocean"], ["southern", "The Southern Ocean"], ["pacific", "The Pacific Ocean"], ["indian", "The Indian Ocean"]), correctId: "arctic", explanation: "The Arctic Ocean is the smallest and shallowest ocean, around the North Pole." },

  // ── countries and capitals (well-established facts) ────────────────────────────────────────────────────────
  { key: "cq-country-1", topics: ["countries"], difficulty: 1, prompt: "What is the capital city of the United Kingdom?", options: opt(["london", "London"], ["paris", "Paris"], ["dublin", "Dublin"], ["edinburgh", "Edinburgh"]), correctId: "london", explanation: "London is the capital city of the United Kingdom." },
  { key: "cq-country-2", topics: ["countries"], difficulty: 1, prompt: "What is the capital city of France?", options: opt(["paris", "Paris"], ["london", "London"], ["berlin", "Berlin"], ["madrid", "Madrid"]), correctId: "paris", explanation: "Paris is the capital of France." },
  { key: "cq-country-3", topics: ["countries"], difficulty: 2, prompt: "Which is the largest country in the world by land area?", options: opt(["russia", "Russia"], ["canada", "Canada"], ["china", "China"], ["usa", "The United States"]), correctId: "russia", explanation: "Russia is the largest country by area, spanning parts of Europe and Asia." },
  { key: "cq-country-4", topics: ["countries"], difficulty: 2, prompt: "Which country has the largest population in the world?", options: opt(["india", "India"], ["china", "China"], ["usa", "The United States"], ["indonesia", "Indonesia"]), correctId: "india", explanation: "India passed China to become the world's most populous country in 2023." },
  { key: "cq-country-5", topics: ["countries"], difficulty: 2, prompt: "Which country is shaped like a boot and is famous for pizza and pasta?", options: opt(["italy", "Italy"], ["spain", "Spain"], ["greece", "Greece"], ["portugal", "Portugal"]), correctId: "italy", explanation: "Italy's long, narrow shape is often compared to a boot." },
  { key: "cq-country-6", topics: ["countries"], difficulty: 3, prompt: "Which is the smallest country in the world?", options: opt(["vatican", "Vatican City"], ["monaco", "Monaco"], ["malta", "Malta"], ["luxembourg", "Luxembourg"]), correctId: "vatican", explanation: "Vatican City, inside Rome, is the smallest country in the world by both area and population." },

  // ── physical geography ──────────────────────────────────────────────────────────────────────────────────────
  { key: "cq-phys-1", topics: ["physical"], difficulty: 1, prompt: "What is the name for a large area of flowing salt water?", options: opt(["ocean", "An ocean"], ["lake", "A lake"], ["river", "A river"], ["desert", "A desert"]), correctId: "ocean", explanation: "Oceans are huge bodies of salt water covering most of the Earth's surface." },
  { key: "cq-phys-2", topics: ["physical"], difficulty: 1, prompt: "What is the tallest mountain in the world?", options: opt(["everest", "Mount Everest"], ["kilimanjaro", "Mount Kilimanjaro"], ["kanchenjunga", "Kanchenjunga"], ["mont-blanc", "Mont Blanc"]), correctId: "everest", explanation: "Mount Everest, in the Himalayas, is the highest mountain above sea level at 8,849 m." },
  { key: "cq-phys-3", topics: ["physical"], difficulty: 2, prompt: "What is the longest river in the world?", options: opt(["nile", "The Nile"], ["amazon", "The Amazon"], ["thames", "The Thames"], ["yangtze", "The Yangtze"]), correctId: "nile", explanation: "The Nile, in north-east Africa, is generally recognised as the world's longest river." },
  { key: "cq-phys-4", topics: ["physical"], difficulty: 2, prompt: "What is a large, dry, sandy or rocky area with very little rain called?", options: opt(["desert", "A desert"], ["rainforest", "A rainforest"], ["tundra", "Tundra"], ["wetland", "A wetland"]), correctId: "desert", explanation: "Deserts receive very little rainfall and can be hot (like the Sahara) or cold (like Antarctica)." },
  { key: "cq-phys-5", topics: ["physical"], difficulty: 2, prompt: "What is the name for a mountain that can erupt, throwing out lava and ash?", options: opt(["volcano", "A volcano"], ["glacier", "A glacier"], ["canyon", "A canyon"], ["plateau", "A plateau"]), correctId: "volcano", explanation: "A volcano is an opening in the Earth's crust that can erupt with lava, ash and gases." },
  { key: "cq-phys-6", topics: ["physical"], difficulty: 1, prompt: "What is a deep valley with steep sides, often carved by a river, called?", options: opt(["canyon", "A canyon"], ["plateau", "A plateau"], ["peninsula", "A peninsula"], ["delta", "A delta"]), correctId: "canyon", explanation: "The Grand Canyon in the USA, carved by the Colorado River, is a famous example." },
  { key: "cq-phys-7", topics: ["physical"], difficulty: 3, prompt: "What is a piece of land almost surrounded by water, but joined to a larger landmass, called?", options: opt(["peninsula", "A peninsula"], ["island", "An island"], ["isthmus", "An isthmus"], ["archipelago", "An archipelago"]), correctId: "peninsula", explanation: "A peninsula is connected to the mainland on one side and surrounded by water on the others - Cornwall is a UK example." },
  { key: "cq-phys-8", topics: ["physical"], difficulty: 3, prompt: "What is a group of islands close together called?", options: opt(["archipelago", "An archipelago"], ["peninsula", "A peninsula"], ["isthmus", "An isthmus"], ["atoll", "An atoll (only)"]), correctId: "archipelago", explanation: "An archipelago is a chain or cluster of islands, such as the Philippines." },
  { key: "cq-phys-9", topics: ["physical"], difficulty: 2, prompt: "Where a river meets the sea and splits into smaller channels, what is this area called?", options: opt(["delta", "A delta"], ["source", "The source"], ["tributary", "A tributary"], ["glacier", "A glacier"]), correctId: "delta", explanation: "A river delta forms where sediment builds up as a river fans out into the sea." },
  { key: "cq-phys-10", topics: ["physical"], difficulty: 2, prompt: "What do we call the starting point of a river?", options: opt(["source", "The source"], ["mouth", "The mouth"], ["delta", "The delta"], ["basin", "The basin"]), correctId: "source", explanation: "A river's source is where it begins, often in hills or mountains." },
  { key: "cq-phys-11", topics: ["physical"], difficulty: 2, prompt: "What do we call the point where a river flows into the sea?", options: opt(["mouth", "The mouth"], ["source", "The source"], ["tributary", "A tributary"], ["bank", "The bank"]), correctId: "mouth", explanation: "A river's mouth is where it finally reaches the sea, lake or another river." },
];

/** The original bank plus the extra items (content.extra.ts): 100+ items. */
export const COMPASS_ITEMS: QuizItem[] = [...COMPASS_BASE, ...COMPASS_EXTRA];
