import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Curriculum reference data (National Curriculum, GCSE/AQA…): WHICH curriculum area each library lesson fits.
// Static, platform-level, versioned — generated by scripts/curriculum/*. A provider's own corrections live in
// Firestore (`hubNcTags`, routes/hub/curriculumApi.ts) and are layered on top per tenant.
// A lesson is keyed by its Oak URL minus the host prefix, so the same mapping serves every tenant's copy.

export const OAK_PREFIX = "https://www.thenational.academy/teachers/programmes/";
/** The key a lesson's Oak URL maps to ("english-primary-ks1/units/…/lessons/…"), or null for anything that isn't an Oak URL. */
export const oakKey = (url: unknown): string | null => (typeof url === "string" && url.startsWith(OAK_PREFIX) ? url.slice(OAK_PREFIX.length) : null);

export interface CurArea { id: string; subject: string; /** The tab it sits under: maths · english · science · languages (GCSE splits science/languages into their own subjects). */ group?: string; strand: string; area: string; code?: string }
export interface CurFramework {
  id: string; label: string; version: string; note: string;
  areas: CurArea[];
  /** What the framework expects: [areaIndex, fromYear, toYear] — a key-stage row spans several years and is judged as a whole. */
  expected: [number, number, number][];
  /** oakKey → [areaIndex, year, confidence (0 High · 1 Medium · 2 Low), status (0 statutory · 1 beyond the NC · 2 non-statutory)] */
  lessons: Record<string, [number, number, number, number]>;
  /** oakKey → further area indexes a lesson also touches (GCSE units that span two spec areas). */
  secondary?: Record<string, number[]>;
}

const here = path.dirname(fileURLToPath(import.meta.url));
const FILES: Record<string, string> = { nc2014: "nc2014.json", "gcse-aqa": "gcse-aqa.json" };
const loaded = new Map<string, CurFramework | null>();
export const frameworkIds = () => Object.keys(FILES);

/** A framework's data (read once, then shared — treat as read-only). null when the file isn't shipped yet. */
export function framework(id: string): CurFramework | null {
  if (loaded.has(id)) return loaded.get(id)!;
  let v: CurFramework | null = null;
  const file = FILES[id];
  if (file) {
    try {
      const raw = JSON.parse(readFileSync(path.join(here, "../data/curriculum", file), "utf8")) as { framework: Pick<CurFramework, "id" | "label" | "version" | "note"> } & Omit<CurFramework, "id" | "label" | "version" | "note">;
      v = { ...raw.framework, areas: raw.areas.map((a) => ({ ...a, group: a.group ?? a.subject })), expected: raw.expected, lessons: raw.lessons, secondary: raw.secondary };
    } catch { v = null; }
  }
  loaded.set(id, v);
  return v;
}

export type CellStatus = "gap" | "thin" | "covered";
/** The sheet's own thresholds: 0 lessons = gap, 1–4 = thin, 5+ = covered. */
export const statusOf = (n: number): CellStatus => (n <= 0 ? "gap" : n < 5 ? "thin" : "covered");

/** One lesson's place in a framework, after a provider's correction (if any) is applied. */
export interface Placement { areaIdx: number; year: number; confidence: number; status: number; corrected: boolean }

/** Per-area, per-year lesson counts + the expected-row verdicts + the headline summary, from a list of placed lessons. */
export function tally(fw: CurFramework, placed: Iterable<Pick<Placement, "areaIdx" | "year">>) {
  const byYear: number[][] = fw.areas.map(() => Array(12).fill(0)); // index 1..11 = Year 1..11
  for (const p of placed) { const row = byYear[p.areaIdx]; if (row && p.year >= 1 && p.year <= 11) row[p.year]!++; }
  const rows = fw.expected.map(([areaIdx, from, to]) => {
    let n = 0; for (let y = from; y <= to; y++) n += byYear[areaIdx]![y]!;
    return { areaIdx, from, to, lessons: n, status: statusOf(n) };
  });
  const summary = { checked: rows.length, covered: rows.filter((r) => r.status === "covered").length, thin: rows.filter((r) => r.status === "thin").length, gaps: rows.filter((r) => r.status === "gap").length };
  return { byYear, rows, summary };
}
