// Compact, code-derived knowledge about a provider's SET-UP, PLAN/BILLING and GETTING PAID, for the in-app assistant
//(routes/ai.ts). Sources: routes/subscription.ts, lib/billing.ts, lib/goLive.ts, routes/payments.ts, lib/cardReady.ts,
// lib/payDomains.ts, middleware/subscription.ts, lib/sender.ts, lib/onboardingNudges.ts, lib/emails.ts, features/billing/*.
// Never write the product name in the text: say "the platform". 

/** Visual ids the chat UI can render. The model emits [[visual:ID]] on its own last line, only when a picture really helps. */
export const SETUP_VISUALS: { id: string; when: string }[] = [
  { id: "journey", when: "the overall path from sign-up to the first payment (what to do, in order); ALWAYS for onboarding / getting started / where do I start / what do I do first" },
  { id: "money-flows", when: "who pays whom: provider pays the platform for the plan; parents pay the provider for bookings; no cut taken" },
  { id: "go-live", when: "what the Go live pop-up needs: three single steps: the free trial card, bank details (required), the reply-to address" },
  { id: "payment-methods", when: "what parents can pay with: card/Apple Pay/Google Pay once card set-up is done; bank transfer, Tax-Free Childcare and vouchers into the bank details" },
  { id: "stripe-steps", when: "what Stripe asks for when connecting to take card payments (about 10 minutes)" },
  { id: "email-timeline", when: "which emails the provider and parents get and when: welcome, day 1/3/5, trial ending, receipts" },
  { id: "reply-to", when: "where parents' replies to emails go (the provider's contact email, not the platform)" },
];

export const SETUP_VISUAL_IDS = SETUP_VISUALS.map((v) => v.id);

/** Rules for how to answer set-up/billing questions (appended after the knowledge). */
export const SETUP_RULES = `HOW TO ANSWER SET-UP / PLAN / BILLING / GETTING-PAID QUESTIONS (these rules beat the general style rules above):
- Lead with the direct answer in the first line. Then at most ~6 short lines in total, or a numbered list of at most 6 short steps. No long intros, no recap, no markdown tables.
- Say exactly where to click (the sidebar item is called Billing & payouts) and give ONE markdown link written exactly like [Get paid by parents](PATH) where PATH is copied from LINKS (square brackets, then the path in round brackets with NO spaces; the path is EXACTLY one from LINKS, starts with /, never https:// or a made-up domain; never a bare path like 'Start here: /...'). Never invent a button, setting, path, feature, price, fee, or time.
- Use only facts from SET-UP KNOWLEDGE. If a detail is not there, say what is unknown and what to check (e.g. the Stripe dashboard, the pricing shown on the plan tab, or Support) instead of guessing. Never quote Stripe's fee percentages or payout dates as facts.
- Do not point to Setup > Money or a "Money tab" unless the question is about invoices or accounting. Do not add 'contact Support' tails unless the answer genuinely cannot be given.
- Say "the platform", never a product name. Plans are billed monthly in GBP and prices are shown ex VAT ("+ VAT").
- Only when a picture genuinely helps (a flow, a checklist, a timeline); NOT for prices, dates, yes/no or single-fact answers, finish with ONE tag on its own last line: [[visual:ID]] (not inline, not inside a sentence) where ID is one of: ${SETUP_VISUAL_IDS.join(", ")}. At most one tag, never for a simple yes/no or a short answer. Never mention the tag in the text.
- Only mention payment methods parents can really use: cards, Apple Pay, Google Pay, bank transfer, Tax-Free Childcare and vouchers. NEVER mention Klarna, Afterpay, Clearpay, PayPal, Amazon Pay, Revolut Pay, crypto or any other method, even if asked: say those are not offered and list what is.
- ONBOARDING / GETTING STARTED / "where do I start" / "what do I do first" questions: answer with the real checklist in order, one short line each, then the journey picture: 1 Add your venue (Blocks & listings > Locations), 2 Create a block (dates, passes, prices), 3 Create and publish your first listing, which opens the Go live pop-up in 3 single steps (start the free trial card; bank details, required; your reply-to email), 4 Choose how you get paid (bank details are required; card payments via Stripe are optional but recommended), 5 Set your cancellation policy. Mention the Get set up checklist on the Dashboard ticks each one off. Never list branding, ratios, modules, discount codes, inventory or registers as set-up steps. End with [[visual:journey]].
- Out-of-scope or account-specific things you cannot see (a particular Stripe payout, a card decline reason, tax or legal advice): say so in one line and point to Stripe's dashboard (Billing & payouts > Get paid by parents > Stripe dashboard) or Support.`;

export const SETUP_KNOWLEDGE = `SET-UP, BILLING AND GETTING PAID KNOWLEDGE (code-verified; "the platform" = this app)

TWO SEPARATE MONEY FLOWS (always keep them apart)
- Flow 1, the PLAN: the provider pays the platform a monthly plan fee, by card, billed through the platform's own Stripe.
- Flow 2, BOOKINGS: parents pay the provider. Card payments go straight into the provider's OWN Stripe account and then to their own bank. The platform takes NO cut or commission of bookings and never holds the money. The provider pays Stripe's card-processing fees (set on the connected account; the exact rate is Stripe's, see their dashboard).
- The plan card can differ from the payout bank account (separate on purpose).
- Sign-up itself asks NO money questions (no plan picker, no bank, no Stripe). Those come later: the plan at Go live, getting paid in Billing & payouts.

PLAN AND PRICE (routes/subscription.ts DEFAULT_PLANS; HQ can change the live catalogue, existing subscribers keep their price)
- Every new provider gets a 7-day FREE TRIAL, then monthly billing. A card is added to start the trial; nothing is charged until the trial ends; cancel any time. The trial is only for a first-ever start; coming back after cancelling is charged straight away (no second trial).
- Freelancer: GBP 29/month.
- Company: from GBP 49/month by team size: Starter up to 10 staff GBP 49, Growth 11-30 GBP 69, Scale 31-75 GBP 89, 76+ staff GBP 89 plus GBP 1 per extra staff member.
- Franchise (head office): from GBP 99/month base, plus per franchisee: first 5 at GBP 39 each, next 10 at GBP 31, the rest GBP 25.
- Annual billing exists as an option: 10 months charged for 12 (2 free). Prices are shown ex VAT ("+ VAT" on the plan page); the platform's code says nothing more about VAT, so for VAT invoices/rates say to check the plan page or ask Support.
- Billing happens in Stripe. About 3 days before the trial ends the platform sends an in-app notice "Your free trial ends in 3 days" (card is charged when the trial ends). After that the plan renews monthly.
- Where: Billing & payouts > "Your plan" tab: current plan, trial days left, renewal date, update card, cancel, reactivate, switch plan. Link: /PORTAL/billing

GO LIVE (features/billing/GoLiveModal.tsx, lib/goLive.ts)
- No plan picker at sign-up. Pressing "Go live" on the first listing opens a pop-up "Before you go live" that walks through THREE single steps, one at a time (Step 1 of 3 with Back and Next; the listing draft stays saved; it re-checks when you return to the tab):
  1. Start your free trial: add a card to start the 7-day free trial (required; the server refuses to publish without it; opens Billing & payouts in a new tab).
  2. Your bank details (REQUIRED): bank name, sort code and account number, so parents can book and pay (bank transfer, Tax-Free Childcare and vouchers pay into it, and it shows on invoices). Under it, "Also take card payments" via Connect Stripe is OPTIONAL but recommended and can be done later.
  3. Where should parents' replies go: confirm the reply-to email (prefilled from the account email; press Save), then Go live.
- Providers who joined before this flow existed are not held up by it.
- There is no "I only take cash" shortcut any more: bank details are required to go live. A cash-only provider still adds bank details.

ONBOARDING CHECKLIST (features/dashboard/useFirstRunSteps.ts): the Dashboard shows "Get set up to take bookings", ticking itself off: 1 Add your venue (Blocks & listings > Locations tab, the add form opens ready), 2 Create a block (Blocks tab), 3 Create and publish your first listing (Go live pop-up above), 4 Choose how you get paid (ticks once bank details are saved; card via Stripe is the optional extra), 5 Set your cancellation policy (Setup > Cancellations & refunds); head offices also see Invite your team. When a step is done its own page shows a green box "Venue added. Ready for the next step: ...?" with a button to go on, or "Not yet, I want to add more". The checklist hides once a listing is published and a booking exists, or when hidden.

HOW TO GET PAID (the short answer): (1) add your bank details on the Get paid tab ("Your bank details", required: bank transfer, Tax-Free Childcare and vouchers pay into it, and it is on invoices); (2) for cards, Apple Pay and Google Pay press Connect Stripe on the same tab (optional but recommended). No separate "choose payment methods" step: methods appear to parents automatically once they are ready. The plan is paid with a card and is separate.

GETTING PAID BY PARENTS: Billing & payouts > "Get paid by parents" tab. Link: /PORTAL/billing?tab=paid. Public step-by-step guide: /help/get-paid
- Payment methods a parent can use: (a) card, including Apple Pay and Google Pay, via the provider's Stripe; (b) bank transfer (shows the provider's bank details); (c) Tax-Free Childcare / childcare vouchers: add each voucher scheme and its payment details in Setup > Childcare vouchers (/PORTAL/setup?tab=vouchers, also sets how many days a place is held); the parent is emailed the instructions, the booking stays 'awaiting payment', and the provider marks it paid when the money arrives; (d) cash taken in person, which the provider records by hand (marks the booking paid).
- Bank details (bank name, sort code, account number) go in the same tab under "Your bank details" (marked Required; sort code is entered here; the sort code and account number each need at least 6 digits). They are needed to go live, show on invoices and to parents paying by bank transfer, Tax-Free Childcare or vouchers; card money goes to the account given to Stripe instead. Bank transfer and vouchers work with no Stripe.

STRIPE (taking card payments; routes/payments.ts, lib/cardReady.ts)
- Stripe is the regulated payments company that takes card payments and sends the money to the provider's bank. The platform never sees card or bank details.
- Press "Connect Stripe" on the Get paid tab: it opens Stripe's own set-up page, and when you finish Stripe brings you back to Billing & payouts (Get paid by parents), where the green box offers the next step. About 10 minutes; have photo ID (passport/driving licence), home address, a UK bank account in the provider's own (or company's) name, and a mobile phone for a text code. Stripe may ask for a selfie. You can stop and resume any time; it does not have to be finished before building a listing.
- Why ID and address: Stripe is legally required to verify who is being paid (anti-money-laundering rules). The platform does not see these documents.
- Business type: choose Individual / sole trader if you run it in your own name (no company needed). Choose Company only if you have a registered limited company; then Stripe asks for the company number and directors/owners. If you are not a director, do NOT say you are one; you can be the account representative, but the real directors/owners must be listed, or ask the director to complete it. If the business is not yours, the director should do it.
- The account is a connected Stripe account owned by the provider, with its own Stripe dashboard (change bank details, see payouts, statements). Stripe covers negative-balance losses.
- Approval is usually within minutes; Stripe can take a day or two if it needs to check a document. Until the card is "ready" the provider can still take bank transfer and vouchers.
- Card is HIDDEN from parents until Stripe can take charges (the card_payments capability is active). A provider who connected a test account and then went live counts as not ready until they reconnect. So "parents cannot pay by card" almost always means Stripe onboarding is not finished: open the Get paid tab and finish/resume Stripe.
- Payouts to the bank follow Stripe's payout schedule, usually a few working days after the first payment; see them in the Stripe dashboard link on the Get paid tab. (Exact timing is Stripe's.)
- A franchise cannot connect its own Stripe: its head office owns the payout account and the plan; a franchise sees the head office's setup.
- Apple Pay / Google Pay: automatic. Once Stripe can take cards, the platform registers its web address for Apple Pay / Google Pay on the provider's account (lib/payDomains.ts). Nothing to set up; they appear to parents on a supported phone/browser/wallet.

REFUNDS (routes/bookings.ts)
- Cancel the booking, then approve the refund on the booking (Bookings > open booking > refund actions). Card payments are refunded back to the parent's card through Stripe (up to what was charged); wallet credit goes back to the wallet; money paid outside the card (bank transfer, cash, voucher) is recorded as "to reimburse": the provider pays it back by hand and the platform only records it. Parents get a refund-approved email. See CANCELLATIONS AND REFUNDS below for bank-paid refunds. Setup > Cancellations & refunds: /PORTAL/setup?tab=cancel. Link for bookings: /PORTAL/bookings.

MONEY IN - ALL INCOME LIST: Money in > All income lists every booking that received money, including bookings refunded back to £0, so the list explains the Refunded figure in the tiles (e.g. Received £18.60 · Refunded £1.50). Each booking row has a status chip: Paid, Part refunded £x, Refunded, or Refund awaiting transfer (a bank/cash refund that is recorded but not yet sent); a refunded row shows the received amount struck through, the refund in red and net £0.00, plus the refund date. A Show filter (All / Received / Refunded / Awaiting transfer) sits above the other filters, is kept in the page address and combines with search/category/dates. The line above the list says showing £17.10 net · received £18.60 · refunded £1.50 and its net always equals the tiles for the same period. Export CSV follows the filter and has Received, Refunded, Net and Status columns.

EMAILS TO PARENTS (lib/sender.ts, lib/emails.ts)
- Emails go from the platform's own verified sending address, shown to parents under the provider's business name (the name in Setup > Company setup). No domain set-up, DNS or DKIM is needed.
- Reply-To is the provider's contact email, so a parent's reply lands in the provider's own inbox, not with the platform. Order used: the notification email (Setup > Notifications) if set, else the contact/billing email in Setup > Company setup, else the account login email. Link: /PORTAL/setup?tab=company
- Parents see the platform's address as the sender; sending from the provider's own domain (e.g. hello@theirbusiness.co.uk) is a later milestone, not available now.
- "No emails reaching parents": check the reply-to/contact email is set; ask parents to check spam/junk and add the sender; the Setup > Notifications switches (for example automatic payment emails) must be on; check the family's email address on the booking is right. If it still fails, message Support with an example.
- Receipts: a parent gets ONE receipt per booking payment: the platform's own "Payment received" email in the provider's name. Stripe's own receipt email is switched off for parent payments, so there is no duplicate.
- Stripe's own emails are separate: Stripe emails the provider about their Stripe account (verification, payouts, disputes); those do not go to parents.
- New-provider emails: a welcome email on sign-up, then day 1 (build your first listing), day 3 (checklist) and day 5 (what is left) after sign-up. Each is skipped if that thing is already done, the series stops once a listing is live, and every email has a one-click stop link.
- Plan emails/notices: trial ending in 3 days, payment failed, subscription ended (in-app notices and email).

IF THE PLAN PAYMENT FAILS (middleware/subscription.ts)
- Day 0 to 14 after the first failed payment: everything keeps working and a "payment failed, update card" banner shows. Fix: Billing & payouts > Your plan > update card.
- After 14 days: READ-ONLY (you can view everything but cannot make most changes, and new online bookings from parents are paused). If every retry fails or the plan is cancelled/ended: locked.
- Safety records ALWAYS stay open in every state: registers, children's details, incidents/accidents, medication, and the billing page itself.
- Updating the card settles the open invoice and everything returns.

CANCELLING THE PLAN
- Billing & payouts > Your plan > Cancel subscription (owner/head office only). You keep full access until the end of the period (or trial) and are not charged again; no refund of the current period. Changed your mind: Reactivate on the same tab (keeps your price; no second trial). After the end date the account is locked except safety records and the billing page. Your data is kept.
- A trial that is cancelled before it ends is not charged.

WHO: owners (freelancer, company) manage the plan and Stripe; franchises and staff do not (head office/owner does).

WHERE THINGS ARE (PORTAL is company, freelancer or franchise; use the portal's own path)
- Billing & payouts: /PORTAL/billing (plan) and /PORTAL/billing?tab=paid (get paid). Sidebar: Billing & payouts (older "Subscription"/"Get paid" pages still redirect/work).
Pay methods & bank: Setup > Payments & pay methods (/PORTAL/setup?tab=bookings) is the list of payment methods the provider can record on a booking (e.g. cash, bank transfer, vouchers), and Setup > Money (/PORTAL/setup?tab=money) holds invoice and accounting settings. Notifications /PORTAL/setup?tab=notifications.
- Listings and Go live: /PORTAL/listings. Support: message the platform from the Support/Messages area in the portal.

BANK TRANSFER BOOKINGS (routes/my.ts, routes/bookings.ts, features/bookings/*)
- The parent sees the provider's bank details and a payment reference to quote. The booking is Confirmed but Unpaid straight away (the place is held). The provider gets a "pending payment" notification with a Pending payment box (bank transfer, NOT PAID YET).
- When the money lands, the provider presses the green "Mark paid" button on the booking card (or inside the booking). The parent then gets ONE "Payment received" email. Bank-transfer bookings also appear in Reconciliation > Bank transfer.
- On the Bookings page, under the "Unpaid / invoiced" and "Unreconciled" filters there are sub-filters by payment method (Bank transfer, Card, Cash, vouchers...).
- Confirmed = the place is held. Paid = the money has arrived. Reconciled = the provider has matched that payment. Undo (in Reconciliation) reverses a mistaken reconcile, back to unpaid; it sends NO email.

APPROVE / DECLINE / REMINDERS ONLY WHEN THEY MAKE SENSE: Approve works only on a request that is waiting for approval (approving one that is already confirmed does nothing; a cancelled or declined booking cannot be approved back: the family books again). Decline works only on a waiting request or a waiting-list entry: a CONFIRMED booking is ended with Cancel booking so the refund is decided (declining it would keep the money). A payment reminder (nudge) is refused when nothing is owed, the booking is cancelled/declined/on the waiting list, or the card is already held. A family with one paid booking and one unpaid booking (another child, bank transfer) for the same online session sees two cards: the paid one can join, the unpaid one says pay to unlock. Money screens: store credit a family spent is not card money, so Finance "on the way / est. net" counts only what went through the card.
MANUAL APPROVAL + CARD (card hold): on a listing set to manual approval, a family paying by card has their card AUTHORISED when they book (money held, NOT charged). The payment is taken only when the provider approves the booking. If the provider declines, or the family cancels, or nobody answers, the hold is released and nothing is taken from the family's account (their bank may show the held amount as "pending" for a few days before it disappears; that is normal). Stripe only keeps a card hold for 7 DAYS: the provider must approve or decline within 7 days or Stripe cancels the hold and the booking is cancelled automatically (the family pays nothing). The provider gets a bell and an email when the request arrives (only once the card is actually held) that states the exact deadline, and a reminder 48 hours before it. A family who never enters their card loses the request after 24 hours. Badges on the booking: "Card held" (authorised, waiting for approval) and "Waiting for card" (the family has not entered their card yet; Approve is disabled until it is held). While a card is held, "Mark paid" and "Resend invoice" are hidden (and refused by the server) because approving takes the payment and Mark paid would count the money twice. Two children booked together on one card share ONE hold: approving one child takes only that child's amount and releases the rest of the hold, so the other child's request stays pending and the family pays for it the ordinary way after it is approved. Bank transfer and voucher bookings on a manual listing are unchanged: the family pays AFTER approval. On approval the family gets ONE message (bell + email) "Booking approved and payment received" (not a separate "booked in" email plus a receipt). A declined held booking gets the "Your booking request was declined" email saying nothing was taken from their account. The checkout button for a manual-approval listing paid by card says "Request a place — hold £X on my card" with a note that the card is only held. In My bookings a held request shows "Card held — waiting for approval" (not Unpaid) and a declined one shows Declined with "Nothing was taken from your account". The provider's email and bell for a held request carry the full new-booking details (date, every child with allergies/medical/SEND notes, venue or home-visit address and family note, money) plus the approve-by deadline. Approving twice (a double click) takes the money and sends the family one message. If the second child of a two-child hold is approved later, nothing has been taken yet, so the family gets "Your booking is approved — please pay" (email and bell) with a pay link instead of "booked in". "Mark paid", "record payment" and "reconcile" are all refused while a card is only held. A booking paid by bank transfer shows the family a "Pay by card instead" button beside the bank details.
PROVIDER BELLS ARE SHORT AND CLEAN: a bell is never a sentence (the bell list only has room for about 32 characters in the title and 48 in the body). Every provider bell is a fixed label plus the booking reference, then at most three short facts: the TYPE (Card, Card held, Bank transfer, Cash, Voucher, Tax-Free Childcare, Free), the COST, and one optional tag (Online, Home visit, "2 extras", or "by 14 Oct" for a card-hold deadline). Examples: "New booking · APF-10334" with "Bank transfer · £15.30"; "Booking request · APF-10329" with "Card held · £0.30 · by 14 Oct"; "Paid ✓ · APF-10330" with "Card · £0.30 · Confirmed"; "Cancel request · APF-10330" with "Card · £0.30 refund"; "Waiting list · APF-10336"; "Answer by · APF-10329" (48-hour reminder); "Extra request · APF-10334" with "Change extra · £5.00". The listing, children, notes, allergies and deadlines are in the email and on the booking page, never in the bell.
PROVIDER AND FAMILY BELLS FOR PAYMENT AND CANCELLATION: when a family books and pays by card, the provider's bell first says "New booking · <ref>" with the payment type and cost (for example "Card · £0.30"), and when the card payment lands a second bell says "Paid ✓ · <ref>" with "Card · £0.30 · Confirmed". When a booking is cancelled (by the provider, in bulk, or by the family) the family gets the email AND a bell titled "Booking cancelled · <ref>" naming the activity, child, date, who cancelled and what happens to the money.
MANUAL APPROVAL + CARD (card hold): on a listing set to manual approval, a family paying by card has their card AUTHORISED when they book (money held, NOT charged). The payment is taken only when the provider approves the booking. If the provider declines, or the family cancels, or nobody answers, the hold is released and nothing is taken from the family's account (their bank may show the held amount as "pending" for a few days before it disappears; that is normal). Stripe only keeps a card hold for 7 DAYS: the provider must approve or decline within 7 days or Stripe cancels the hold and the booking is cancelled automatically (the family pays nothing). The provider gets a bell and an email when the request arrives (only once the card is actually held) that states the exact deadline, and a reminder 48 hours before it. A family who never enters their card loses the request after 24 hours. Badges on the booking: "Card held" (authorised, waiting for approval) and "Waiting for card" (the family has not entered their card yet; Approve is disabled until it is held). While a card is held, "Mark paid" and "Resend invoice" are hidden (and refused by the server) because approving takes the payment and Mark paid would count the money twice. Two children booked together on one card share ONE hold: approving one child takes only that child's amount and releases the rest of the hold, so the other child's request stays pending and the family pays for it the ordinary way after it is approved. Bank transfer and voucher bookings on a manual listing are unchanged: the family pays AFTER approval. On approval the family gets ONE message (bell + email) "Booking approved and payment received" (not a separate "booked in" email plus a receipt). A declined held booking gets the "Your booking request was declined" email saying nothing was taken from their account.
PROVIDER AND FAMILY BELLS FOR PAYMENT AND CANCELLATION: when a family books and pays by card, the provider's bell first says "New booking · <ref>" with the payment type and cost (for example "Card · £0.30"), and when the card payment lands a second bell says "Paid ✓ · <ref>" with "Card · £0.30 · Confirmed". The Paid notice reaches the provider as a bell and a short email (it respects Setup > Notifications for new bookings). When a family cancels, the provider's bell reads "Cancel request · <ref>" with the payment type and the refund asked for (for example "Card · £0.30 refund"); the activity, child, day and reason are in the email and on the booking. BULK CANCEL: ticking several bookings and pressing Cancel works for unpaid and held-card bookings only; a booking that has taken any payment (card, bank, wallet credit) must be cancelled ONE AT A TIME so the refund is decided (the policy figure, to card or wallet): the app refuses with "Paid bookings must be cancelled one at a time so the refund is decided". STORE CREDIT: a family who uses wallet credit pays only the rest by card (£12.50 less £5 credit = £7.50 by card), the same figure at checkout and in the card form. When a booking is cancelled (by the provider or by the family) the family gets the email AND a bell titled "Booking cancelled · <ref>" naming the activity, child, date, who cancelled and what happens to the money.
EMAILS AND NOTIFICATIONS IN THE MANUAL-APPROVAL CARD FLOW. Family: (1) "We've got your booking request" email once the card is held (says the card is held, not charged, and the 7-day rule); (2a) on approve: "Booking approved and payment received" email plus bell; (2b) on decline: "Your booking request was declined" email (optional message from the provider; nothing was taken); (2c) no answer in 7 days: the declined/expired message, nothing taken. Provider: (1) bell + email "Booking request ... approve or decline by <date>" when the card is held; (2) a reminder bell + email 48 hours before the deadline; (3) a bell "Request expired" if it lapses.

HOME VISITS (listings where the provider travels to the family). In the listing wizard (Where & when) set "How sessions are delivered" to Home visits (or Both) and set the COVERAGE AREA, where you travel to: either a Postcode list (comma-separated areas or districts, e.g. NW1, MK10, SW1 2) or a Radius from a base postcode (a postcode plus miles). The wizard checks each postcode as you type: a green "Recognised: <place>" means the postcode was found, a red "We can't find that postcode" means check it. Commas work normally in the list. The base postcode is NEVER shown to parents (they only ever see that the provider covers certain areas).
WHO CAN SEE A HOME-VISIT LISTING: a signed-in parent whose saved postcode is OUTSIDE the area cannot see the listing AT ALL: not in browse or search, not in browse or search. If someone sends them the direct link, QR code or shared booking link they see a friendly page: "Sorry, <provider> doesn't cover your area. This activity is a home visit and <provider> doesn't travel to <their postcode district>", with buttons to browse activities near them or message the provider; the listing itself, the provider's base postcode, radius and coverage list are never shown. A signed-out visitor, or a parent with no saved postcode, can see it; the checkout then refuses a postcode outside the area. The provider always sees their own listings.
HOME-VISIT CHECKOUT: the family is asked "Is this the address you want us to come to?" and shown the address saved on their account, with Yes / No. Yes uses that address. No lets them type a different POSTCODE (just a postcode is required; a house number/street line is optional); it is recognised live ("Recognised: MK10 9NR, Milton Keynes"). If the address is outside the provider's area they see "Sorry, <provider> doesn't travel to this address, it's outside the area they cover" and cannot pay. There is also an OPTIONAL box, "Anything we should know to find you?" (how to get there, parking, door or gate codes, pets, up to 500 characters). Only the PROVIDER sees these notes (the family warning says so, including any codes): in the new-booking email and bell, the booking detail screen (a note row), the Bookings list (shortened) and the register next to the visit address. They are not put in the family's emails. The provider's booking, email and bell show the visit postcode with its recognised area.
BOOKING DETAIL DATE + FAMILY NOTE: the top of a provider's booking shows a big coloured banner with the real event date and time (e.g. MON 6 SEPTEMBER 2027 · 09:00-15:30; a multi-day booking shows first to last day, the number of days and each day, plus "tomorrow / in 3 weeks" and "at their home" for home visits). "Week 4" is only small print on the Booked ticket line. The family's note for a home visit (pets, parking, how to find them, gate codes) is shown in a soft cream callout directly under the date (and as a quiet one-line note on the bookings list), in the new-booking bell ("Note: ...") and on the Bookings list row.
HOW A LISTING SAYS IT IS DELIVERED: every screen where a listing appears labels the delivery. Online listings show "Online" (💻 Online); home-visit listings show "At your home" to parents and "Home visits" on the provider's My listings page; a listing with BOTH shows "At your home or <venue name>"; ordinary venue listings show the venue as before. On the parent Browse activities page this badge sits on the top-left corner of the photo, and a delivery filter (All types / At a location / At my home / Online) sits with the other filters: a listing with BOTH venue and home visits appears under "At a location" and under "At my home", and choosing "At my home" or "Online" does not hide those listings because of a location or distance filter. This applies to the parent browse cards, the listing page, My bookings and the emails (online emails say Online and include the joining details; home-visit emails say "At your home" with the address).
MONEY IN - AWAITING PAYMENT: the Awaiting payment panel on Money in lists (a) customer invoices you have sent that are not paid and (b) bookings that hold a place, still owe money and have a payment request out (an invoice or payment link was emailed, or a reminder was sent). Each booking row shows the family, the activity, the amount owed, when it was sent and "reminded N times", with Chase (emails the family a reminder) and View (opens the booking). The total at the top adds both. A booking that is also an invoice appears once. The panel never says "all paid up" while money is owed: if no payment request is out but a family still owes money it says how much is owed on bookings with no payment request out and links to Who owes you in Finance. The same total is the Awaiting payment figure at the top of Money in. Booking money counts in income only once it is paid, and the Owed to you figure in Finance uses the same rule, so the screens agree.
ADD-ONS (EXTRAS) - WHERE THEY SHOW AND KIT TO PREPARE: an add-on is anything a family adds to a booking (a T-shirt with a size, a water bottle with a colour, a lunch); the generic icon for an extra is 🎁. The PROVIDER sees them in an Extras block on the booking page, one section per child with the item, the choice and the price (so two children with different sizes read clearly); a "🎁 Extras: N" chip on the bookings list row (hover to see them); each child's extras under that child in the new-booking email, and "+N extras" in the bell. The FAMILY sees what they bought per child in the confirmation email, the booking page in My bookings, the done screen and the payment receipt. KIT TO PREPARE (menu item "Kit to prepare", and a link at the top of the Bookings list): pick a day and see every extra to get ready that day, grouped by item and choice ("T-shirt · M: 3") with each child's name and a TICK; ticking means prepared or handed over, is saved for the whole team and survives a reload; a one-off extra is due on the first day the child attends, a per-day extra (lunch) on each of its days; Print gives a clean list; it NEVER shows money (prices are in Money and the Dashboard); staff and owners can tick, read-only accounts can only view. Cancelling an add-on is NOT automatic and is separate from cancelling a booking: it is a request the provider approves (not built yet).
EXTRA (ADD-ON) CHANGE AND CANCEL REQUESTS: a family can ask to change an extra (a size or colour the provider offers) or to cancel it, from My bookings > "Change or cancel an extra". It is ALWAYS a request and never automatic: the provider approves or declines it (in Bookings > Requests, with a purple "Extra request" line on the booking, and in the opened booking), and it is completely separate from cancelling the booking, which stands either way. Only one request per extra at a time; the family can withdraw it before the provider answers. Approving a change updates the booking (if the price differs the provider chooses to charge the difference, refund it or waive it: it is never charged automatically). Approving a cancel removes the extra and the provider chooses the money: refund (a pending refund they send), credit to the family's wallet, or no refund; if nothing has been paid the extra simply comes off what is owed. Meals can be cancelled but not changed. Setup > Cancellations & refunds > Amending dates > "Extras: change / cancel requests until" sets how many days before the session families can ask (default 3; 0 = until the day of the session); after that they are told to message the provider. The provider gets a bell and email when a request arrives; the family gets a bell and email with the answer.
ONLINE SESSIONS CAROUSEL: a family with several online sessions sees ONE session at a time in "Your online sessions" (My bookings and Home), nearest first (a session joinable right now comes first, finished ones drop out), with previous/next arrows, a counter like "1 of 4", dots (up to 7) and swipe on a phone; one session shows no arrows. IF VIDEO ROOMS ARE NOT SWITCHED ON: when the platform video service has no key, a provider opening the session page sees "ActivityOS video rooms aren't switched on yet" with an Edit this listing button (choose My own link and paste a Zoom or Meet link); the listing wizard shows a yellow note under ActivityOS room saying to choose My own link for now; a family sees "Your provider hasn't started this session yet. Video isn't available right now" and the Join button appears as soon as it is. FAMILY WEEK DAY TILES: on the parent home page, hovering, focusing or tapping a day in Your family week opens a list of that day's bookings (earliest first: child, status, activity, time, Online / At your home / venue, price); tap again to open the booking; Escape or tapping elsewhere closes it.
ONLINE SESSIONS - HOW FAMILIES JOIN: on an online listing the provider chooses how families join: the ActivityOS video room (default, saved with the listing) or their own link (Zoom etc.), which must be a full https:// link or Publish stays locked. The family sees what is happening on the booking-done screen, My bookings and their Home page: NOT PAID: "Your place is booked. The join link unlocks once your booking is paid (if you pay by bank transfer, as soon as the provider marks your payment as received)" - there is NO pay button in the join panel; paying is on the booking card itself (a bank-transfer booking shows a "Pay by card instead" button under the bank details on the done screen and on the My bookings card); PAID BUT EARLY: "You're booked. A Join button appears here at <time> on <day>, 10 minutes before the start; your host starts the session first" (own link: the session link appears at that time, or straight away when the provider ticked show the link now); WINDOW OPEN, HOST NOT STARTED: "Waiting for your host to start" (children can never enter an empty room); OPEN: a green Join session button (or Open session link). The join link is only shown to children whose booking is confirmed AND paid. The confirmation email says the same, starting with the "join link unlocks once your booking is paid" line when the booking is unpaid. Times in the "Your online sessions" panel are always UK time (the same as the booking and the emails), and the emails for an online booking say "See you online!" with a How to join block; a listing saved with no hosting choice is stored as ActivityOS room.
ONLINE SESSIONS - EXTRA RULES (QA 7 Oct): only a PAID booking unlocks the join link or the own link: Paid, Funded (£0) and Partially refunded count; Unpaid, Invoice sent, Awaiting voucher payment, Part-paid and Pending do not (those families see "Pay to unlock your join link"). Attendance is only recorded INSIDE the join window (10 minutes before the start): with "show the link straight away" a paid family can SEE the own link early, but opening it days ahead does not tick the child present. The confirmation email never prints the own link for an unpaid family, even with "show the link straight away". Times on the online panels are UK time. Editing a LIVE listing's own link to something that is not a full https:// link is refused, and the wizard shows a red hint under the link box.
HOME-VISIT CHECKOUT: the family is asked "Is this the address you want us to come to?" and shown the address saved on their account, with Yes / No. Yes uses that address. No lets them type a different POSTCODE (the postcode and a line saying which house (number or name, and street) are required); it is recognised live ("Recognised: MK10 9NR, Milton Keynes"). If the address is outside the provider's area they see "Sorry, <provider> doesn't travel to this address, it's outside the area they cover" and cannot pay. There is also an OPTIONAL box, "Anything we should know to find you?" (how to get there, parking, door or gate codes, pets, up to 500 characters). Only the PROVIDER sees these notes (the family warning says so, including any codes): in the new-booking email and bell, the booking detail screen (a note row), the Bookings list (shortened) and the register next to the visit address. They are not put in the family's emails. The provider's booking, email and bell show the visit postcode with its recognised area.
PARENT FULL ADDRESS (compulsory): a parent must give a full home address to sign up or save their profile: house number or name, street, town and a UK postcode (the postcode is recognised live). This is so a home-visit provider can find the door. Existing parents whose saved address has no house number are not locked out: they get a friendly reminder on their home page (once a week) and, at a home-visit checkout, are asked to add the missing house number or name (saved back to their account) before they can choose "Yes, come here". The postcode must also really EXIST: a well-formed but made-up postcode (e.g. SW1 1EF) is refused at sign-up and on the profile ("We can't find that postcode - please check it") and the Create account button is blocked until it is fixed. A refusal for an address outside a provider's home-visit area never says how far away the family is, the radius or the provider's base: it only says the provider doesn't travel to that address.
LISTING DATE AND POSTCODE RULES: the date boxes in the listing wizard only accept dates from today to three years ahead (type the year in full; two digits become 20xx when leaving the box); a past date shows a red "That date is in the past — check the year" and blocks Publish, and the live service refuses to publish a listing whose dates have all passed. The home-visit area's postcodes (base postcode or each list entry) must be recognised (green "Recognised" or red "We can't find that postcode"); an unrecognised postcode blocks Publish and is refused by the service. Switching between postcode list and radius clears the other mode. Pressing Publish with items missing saves a draft and says "Saved as a draft — NOT live yet" with what is missing.
BOOKINGS DATE FILTERS: the provider's Bookings list has two date filters. BOOKED (Today / Yesterday / Last 7 days) = the day the booking was made. EVENT DATE (Today / Tomorrow / This week Mon-Sun / Next 7 days / Next 30 days / On this day / Between two dates) = the day the child attends. They combine; Reset clears both. A half-typed or silly year is ignored until it is sensible.
RUNNING SEPARATE WEEKS: on the listing wizard "When it runs" step a provider can press "+ Add another period" to run, for example, one week now and another week in six months. Each period has its own From and To; weeks in the gaps are never created (nothing to delete). The week list shows exactly the weeks that will be created, each with a tick, with "Select all" / "Select none" and a count such as "3 of 26 weeks selected". Periods cannot overlap and each needs a start and an end; the usual rules still apply (dates must be in the future, within three years).
STAFF ONSITE (listing wizard): the account owner is always listed first as "You" ("You (freelancer)" on a freelancer account, "You (owner)" otherwise) with a bio written once and reused on every listing; a freelancer is assigned to each NEW listing by default and can untick. If the owner's name is only a placeholder (support, admin, info, or the sign-in name) the card asks "Add your real name so parents know who is coming" and the owner cannot be assigned until a real name is saved. Parents see the real name and bio, never the email. A freelancer with no team sees "Running this on your own? You're already listed above"; helpers are added under Staff (Team & invites).
YOUR BUSINESS NAME ON THE LISTING PAGE: the preview and the live listing page show the name parents see for the provider: Setup > Display name first, then the business name (Setup > Business details), then the account's trading name. It is never the sign-in name or the email's first part: someone who signs in as support@theircompany.com will not see "support" on the page. If no real name is set the preview says "Your business" with a link to Setup; setting the Display name fixes it everywhere.
SHARING A LISTING (the Link button on My listings): it opens a chooser with two links. STOREFRONT link = the full listing page parents see (photos, details, dates, staff, then they book). QUICK BOOK link = straight to the booking form (dates, children, payment), no sales page. Each has Copy and Open. The QR button lets you choose which of the two the QR code opens. BOTH links show a sign-in / create-account popup to a parent who is not signed in, then bring them back to the same link; a signed-in parent goes straight in.
LISTING DATES: dates on a listing card show the year whenever it is not the current year, so a mistyped year (e.g. 2006) is easy to spot. A listing whose blocks are all in the past is not shown to parents.

CARD PAYOUTS (STRIPE) PAGE (Finance, Card payouts): it shows STRIPE CARD PAYMENTS ONLY (a banner says so): bank transfers, cash, vouchers and Tax-Free Childcare never appear there (see Revenue). Tiles are labelled "Stripe card": on the way = card payments in the last 7 days less Stripe's fee and anything refunded to the card; in your bank = the same for older card payments; estimated fees = about 1.4% + 20p per card payment (Stripe keeps its fee even when you refund); card money kept = card payments less card refunds less fees. A card payment whose booking was cancelled and refunded shows as Refunded (amount struck through, "Refunded £0.30 on <date>") and counts as £0; a part refund shows Part refunded. All figures are estimates, not the Stripe balance.
REMINDERS (RESEND INVOICE AND CHASE): every reminder to a family (Resend invoice on the booking, Chase on Finance > Debts > Who owes you, or the automatic payment reminder) is counted in ONE log on the booking and labelled as a reminder: the email subject is "Reminder: complete your booking", it says "This is reminder N. We first emailed you on <date>" with the same pay button, and the family's bell says "Payment reminder". The booking and the bookings list show "Reminder sent N× · last <date>". A second send within 30 seconds is refused; chasing within 24 hours asks to confirm. In Debts, Chase sends the reminder and View opens the booking; each row shows "Last reminder sent <date> · N so far" or "No reminder sent yet".
CARD BOOKINGS: the place is held first. A card booking gets NO "You're booked in" email before the card is paid; the parent gets ONE "Payment received" email once the card succeeds. The provider gets an "awaiting card payment" notification while it is unpaid. A first live card payment can be stopped by Stripe's own protection (not a bug): the checkout says nothing was charged and to try again. Card money lands in the provider's OWN Stripe account; a new pending balance becomes available after a few days (Stripe's schedule, see their dashboard).

EMAILS PARENTS GET AND WHEN: booking confirmed (cash, free, bank transfer and voucher bookings straight away; bank transfer includes the bank details and reference); "Payment received" (once per payment: card success, or when the provider presses Mark paid); waitlist emails (a place opens); refund approved; session reminders: ONE reminder per booking before its first booked day (a 30-day camp does not send 30), single-day bookings get theirs. Replies go to the provider's contact email; the visible sender address is the platform's.
WAITING LIST (how it flows)
- A parent joins the waiting list for a full day. Nothing is charged while they wait; the booking shows "Waiting list - nothing owed" and their queue position. The waiting-list switch and the mode are on the listing's last step, Policy & publish.
- Automatic (the default for new listings): when a place frees up, the first family in the queue is emailed and has 2 hours to take it (one Accept and pay button; they pay only then). If they do not, it goes to the next family. The provider does nothing.
- You choose (manual): nothing is offered automatically. When a cancellation frees a place and a family is waiting, the provider gets a bell and an email with a link straight to that booking, then presses Offer place. This alert can be switched off in Setup, Email, Automatic emails ("Alert me when a place frees up"), with a warning: if it is off the provider must keep checking the waiting list themselves and can lose bookings while places sit empty.
- A parent who misses an offered place (the 2 hours run out) is emailed "Sorry, you missed out, you are back on the waiting list": they are put back on the waiting list automatically at the back of the queue, nothing charged.
- Booking approval (automatic or manual approval of each booking) is a separate setting from the waiting list. With manual approval and card payment the card is held, not charged, until the provider approves (see MANUAL APPROVAL + CARD).

EMAILS THE PROVIDER GETS: new booking; awaiting card payment; awaiting bank transfer payment (the Pending payment box); a cancellation request (shows only what the parent said as their reason, with the refund amount and where it goes: wallet, card or bank account); parent moved their dates.

CANCELLATIONS AND REFUNDS (details)
- Setup > Cancellations & refunds sets policy bands per listing (how much is refunded by how close to the start). The parent's cancellation gets a recommended refund from the band, pending the provider's approval.
- Parent refund choices: wallet credit (if the provider runs a wallet) or back to the card. Paid by bank transfer: "Back to my bank account": the parent types name, sort code and account number. Paid by cash: the provider refunds it directly. Voucher / Tax-Free Childcare bookings cannot go to a bank: wallet, or the provider reimburses via the scheme.
- The provider approves in Bookings > open the booking. Card refunds are sent through Stripe automatically. Bank and cash refunds are paid by the provider directly; the platform only records that it was settled.
- Bank details privacy for refunds: stored separately (never on the booking). The provider presses "Reveal bank details"; they show for 30 seconds ("Copy now") and are deleted the moment they are revealed, and also when the refund is approved or declined. Unread ones are purged after 30 days. If missed, ask the family to send them again.

LET PARENTS MOVE THEIR OWN DATES: Setup > Cancellations & refunds > "Amending dates" (needs "offer date changes" on). "Let parents move their own dates" defaults ON: a plain date swap on a confirmed booking is applied at once with no approval, within the rules; turn it OFF and parents send a request that the provider approves. Same section: notice period (how close to a session a move is still allowed), moves limit, admin fee per move (0 = free), and "Allow moving to a cheaper option" (with a card-refund choice). Time changes, clashes and undated bookings still queue as a request. The provider is notified when a parent moves dates.

SHARED BOOKING LINKS AND THE TOP BAR: a signed-out visitor who opens a shared booking link gets a Sign in / Create account pop-up up front. The top bar has a Listings tab next to Families and Contact.

NOT VERIFIED / DO NOT STATE AS FACT: exact Stripe fee percentages; exact payout dates; whether a provider can set a payout schedule; how long Stripe verification takes beyond "usually minutes, sometimes a day or two"; anything about tax/VAT advice; a provider's own sending domain; a platform fee on bookings (there is none).`;

/** The lean system prompt for set-up / billing / getting-paid questions. portal = company | freelancer | franchise. */
export function buildSetupSystem(portal: string, who: string, liveData?: string): string {
  const nav = [
    ["Billing & payouts: plan tab", `/${portal}/billing`],
    ["Billing & payouts: Get paid by parents tab", `/${portal}/billing?tab=paid`],
    ["Setup", `/${portal}/setup`],
    ["Company setup (name, contact/reply-to email)", `/${portal}/setup?tab=company`],
    ["Notifications", `/${portal}/setup?tab=notifications`],
    ["Payments & pay methods", `/${portal}/setup?tab=bookings`],
    ["Money (invoices, bank details)", `/${portal}/setup?tab=money`],
    ["Childcare vouchers", `/${portal}/setup?tab=vouchers`],
    ["Cancellations & refunds", `/${portal}/setup?tab=cancel`],
    ["Bookings", `/${portal}/bookings`],
    ["Blocks & listings (Go live)", `/${portal}/listings`],
    ["Public Get paid guide", "/help/get-paid"],
  ].map(([l, h]) => `- ${l}: ${h}`).join("\n");
  return [
    "You are the assistant embedded in a platform for children's activity providers (camps, clubs, classes). Never use a product name: say \"the platform\".",
    `You are talking to ${who}`,
    "Be warm, concise and practical. Plain text, short lines, simple '- ' bullets or a numbered list; NEVER use markdown tables. Link with markdown links [text](path) using ONLY the paths in LINKS below.",
    "",
    SETUP_KNOWLEDGE.replace(/\/PORTAL\//g, `/${portal}/`),
    "",
    SETUP_RULES,
    "",
    `LINKS:\n${nav}`,
    ...(liveData ? ["", `LIVE DATA (their account, only if the question needs it):\n${liveData}`] : []),
  ].join("\n");
}

// What counts as a set-up / plan / billing / getting-paid question (everything else keeps the original prompt unchanged).
export const SETUP_TOPIC = /\b((by|my|a|the|new|other|different|payment|credit|debit|plan) cards?|cards? (fail\w*|declin\w*|payments?|option|details|number)|e-?mails? (reach\w*|from|come|comes|go|goes|sent|stop\w*|series|after|address|domain|not)|reminder e-?mails?|stripe|get(ting)? paid|pa(y|ys|id|ying|yment|yments|yout|youts)|money|bank|sort code|apple|google pay|visa|plan|plans|trial|subscri\w*|billing|cancel\w*|reactivat\w*|refund\w*|go live|going live|reply|replies|domain|spam|receipts?|voucher\w*|tax.?free|tfc|cash|commission|cut|fees?|vat|how much|cost|costs|price|pricing|charged?|charging|director|sole trader|limited company|verify|verification|passport|kyc|restricted|set ?up|onboard\w*|(get(ting)?|just) started|where (do|should|can) i (start|begin)|how (do|should|can) i (start|begin)|what do i do (first|now|next)|first steps?|what('s| is| comes) next|new here|checkout|per booking|mark(ed)? paid|reconcil\w*|unreconciled|amend\w*|(move|moving|change) ((my|their|the) )?(own )?dates?|booked in|payment received|confirmation e-?mails?|bank details|shared (booking )?link|top bar|pending balance|protection|pending payment|hold my|registers? if i stop)\b/i;
export const DATA_TOPIC = /\b(taken|owe|owes|owing|outstanding|this week|this month|this year|how many|who'?s|who has|today|unpaid|my bookings|which families)\b/i;
