import { chromium } from "/Users/kazjames/Downloads/activtyos-app-/node_modules/playwright/index.mjs";
import fs from "node:fs";
const D = process.cwd() + "/docs/home-visit-qa/AK/";
const A = JSON.parse(fs.readFileSync(D + "accounts.json", "utf8"));
const WEB = "http://localhost:3028";
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1360, height: 1200 } })).newPage(); p.setDefaultTimeout(90000);
await p.goto(WEB + "/login", { waitUntil: "load", timeout: 120000 });
await p.locator('input[type="email"], #email, input[name="email"]').first().fill(A.provider.email);
await p.locator('input[type="password"]').first().fill(A.password);
await p.getByRole("button", { name: "Sign in", exact: true }).last().click();
await p.waitForURL((u) => !/login/.test(u.pathname), { timeout: 120000 }).catch(() => {});
await p.waitForTimeout(3000);
await p.goto(WEB + "/freelancer/invoices", { waitUntil: "load", timeout: 120000 });
await p.getByRole("button", { name: "All income" }).first().click({ timeout: 120000 });
await p.waitForTimeout(2500);
await p.getByRole("group").getByRole("button", { name: "Refunded", exact: true }).first().click();
await p.waitForTimeout(1500);
console.log("after click:", await p.evaluate(() => location.href));
await p.getByRole("group").getByRole("button", { name: "Awaiting transfer", exact: true }).first().click();
await p.waitForTimeout(1500);
console.log("after awaiting:", await p.evaluate(() => location.href));
await p.getByRole("group").getByRole("button", { name: "All", exact: true }).first().click();
await p.waitForTimeout(1500);
console.log("after all:", await p.evaluate(() => location.href));
await b.close();
