import fs from "node:fs";
import path from "node:path";
import { test } from "@playwright/test";
import { ROOT } from "../helpers/env";
import { buildFixture, ensureFixture, ctxFor, probe, settle, bannerText, skeletons, shootFull, tabStrip, gotoHubPage, handOver, pickChild, VIEWPORTS, type Fx } from "./fixture";

// Screenshot + metrics sweep: tutor / parent / kid x every tab x 3 viewports. Throwaway test accounts only.
//   npx playwright test e2e/review/hub-screens.spec.ts --project=e2e --workers=1
const OUT = path.join(ROOT, "docs/teaching-hub-review/screenshots/before");
test.describe.configure({ mode: "serial" });
let fx: Fx;
const ROWS = path.join(OUT, ".rows");
const order = (f: string) => { const [r, v] = f.replace(".json", "").split("-"); return ["tutor", "parent", "kid"].indexOf(r) * 10 + ["390", "768", "1440"].indexOf(v); };
let rows: string[] = [];

test.beforeAll(async ({ browser }) => { test.setTimeout(500_000); fx = await buildFixture(8, true, browser); });

for (const role of ["tutor", "parent", "kid"] as const) {
  for (const [vpName, vp] of Object.entries(VIEWPORTS)) {
    test(`${role} @${vpName}`, async ({ browser }) => {
      test.setTimeout(900_000);
      rows = [];
      fx = await ensureFixture(browser, fx, 8, true);
      const ctx = await ctxFor(browser, role === "tutor" ? "freelancer" : "parent", vp);
      const page = await ctx.newPage();
      const pr = probe(page);
      const dir = path.join(OUT, role);
      fs.mkdirSync(dir, { recursive: true });
      const t0 = Date.now();
      if (role === "tutor") await gotoHubPage(page, "/freelancer/learninghub?tab=home", fx);
      else {
        await gotoHubPage(page, `/custdash/learninghub?tab=home&child=${fx.kids[0].id}`, fx);
        await pickChild(page, fx).catch(() => undefined);
        if (role === "kid") await handOver(page, fx.kids[0].id).catch((e) => rows.push(`| ${role} | - | ${vpName} | KID MODE ENTRY FAILED: ${String(e).slice(0, 80)} | | | | |`));
      }
      const first = await settle(page);
      const initial = Date.now() - t0;
      const strip = await tabStrip(page);
      const count = strip.labels.length;
      for (let i = 0; i < count; i++) {
        pr.reset();
        const label = strip.labels[i];
        let tm = i === 0 ? first : { content: null as number | null, settled: null as number | null };
        if (i > 0) {
          const tab = page.getByRole("tablist").first().getByRole("tab").nth(i);
          await tab.click().catch(() => undefined);
          tm = await settle(page, 20_000);
        }
        await page.waitForTimeout(1500);
        const sk = await skeletons(page);
        const key = strip.keys[i];
        const s = await tabStrip(page);
        const banners = await bannerText(page);
        const base = path.join(dir, `${key}-${vpName}`);
        await page.screenshot({ path: `${base}-fold.png` }).catch(() => undefined);
        const h = await shootFull(page, `${base}.png`);
        const cell = (a: string[]) => (a.length ? `${a.length}: ${[...new Set(a)].slice(0, 2).join(" ; ").replace(/\|/g, "/")}` : "0");
        rows.push(`| ${role} | ${key} | ${vpName} | ${tm.content === null ? ">20s" : (tm.content / 1000).toFixed(1) + "s"} / ${tm.settled === null ? "never" : (tm.settled / 1000).toFixed(1) + "s"}${i === 0 ? ` (page ${(initial / 1000).toFixed(1)}s)` : ""} | ${s.overflow ? `YES ${s.scroll}/${s.client}` : "no"}${s.pageOverflow ? " PAGE-X" : ""} | ${cell(pr.console.concat(pr.pageErrors))} | ${cell(pr.failed)} | ${(banners.join(" / ").replace(/\|/g, "/") || "-") + (sk > 0 ? ` [${sk} skeleton blocks still showing]` : "")} | ${h} |`);
      }
      await ctx.close();
      fs.mkdirSync(ROWS, { recursive: true });
      fs.writeFileSync(path.join(ROWS, `${role}-${vpName}.json`), JSON.stringify(rows));
    });
  }
}

test.afterAll(async () => {
  const head = `# Teaching Hub - BEFORE screenshots + metrics\n\nGenerated by e2e/review/hub-screens.spec.ts on throwaway @activityos-test.com accounts (${new Date().toISOString()}).\nTimes: click until the active panel shows text / until it has no skeleton blocks left (20s cap); first tab of each run also shows full page-load time. Overflow = tab strip scrollWidth/clientWidth. Screenshots: <role>/<tab>-<viewport>.png (full page) and -fold.png.\n\n| role | tab | viewport | first content / no skeletons | tab strip overflow | console err/warn | failed requests | error banners | page height px |\n|---|---|---|---|---|---|---|---|---|\n`;
  const earlier = `\n\n## Earlier attempt (superseded)\nA first pass via the browser tool captured 5 desktop JPGs only (tutor/*.jpg); it could not resize the viewport and the API was overloaded (35-40s loads, "We can't reach Teaching Hub").\n`;
  const all = fs.existsSync(ROWS) ? fs.readdirSync(ROWS).filter((f) => f.endsWith(".json")).sort((a, b) => order(a) - order(b)).flatMap((f) => JSON.parse(fs.readFileSync(path.join(ROWS, f), "utf8")) as string[]) : [];
  fs.writeFileSync(path.join(OUT, "NOTES.md"), head + all.join("\n") + earlier);
});
