import fs from "node:fs";
import { layout, bookingConfirmedSpec } from "../../server/src/lib/emailTemplates";
import { newBookingProviderEmail } from "../../server/src/lib/emails";
const b: any = { ref: "HVF-10999", booker: "P1 Parent", child: "Hv Kid One", kids: [{ name: "Hv Kid One" }], listing: "HV Postcode Visits", pass: "1 day", amount: 20, sessions: ["Tue 27 Oct 2026 · 09:00 - 15:00"], email: "p1@example.com", tenantId: "t" };
const out: Record<string, string> = {};
const spec = bookingConfirmedSpec({ ...b, serviceAddress: { address: "5 Home Road", postcode: "NN5 7EA" } }, "HV Freelance Tutors");
out.visitParent = layout({ name: "HV Freelance Tutors", hasLogo: false }, spec.title, spec.body, { ...b, serviceAddress: { address: "5 Home Road", postcode: "NN5 7EA" } }, { location: "5 Home Road, NN5 7EA", homeVisit: true }, "https://app.example");
const spec2 = bookingConfirmedSpec(b, "HV Freelance Tutors");
out.onlineParent = layout({ name: "HV Freelance Tutors", hasLogo: false }, spec2.title, spec2.body, { ...b, listing: "HV Online Tutoring" }, { location: "Online", online: true, joinInfo: "Join on Zoom: https://zoom.example/j/123456 (meeting ID 123 456)." }, "https://app.example");
out.venueParent = layout({ name: "HV Freelance Tutors", hasLogo: false }, spec2.title, spec2.body, b, { location: "HV Sports Hall, 1 Venue Way" }, "https://app.example");
out.providerVisit = newBookingProviderEmail({ providerName: "HV Freelance Tutors", kind: "booking", bookerName: "P1 Parent", listingName: "HV Postcode Visits", pass: "1 day", sessions: ["Tue 27 Oct 2026"], attendees: [{ name: "Hv Kid One" }], location: "Home visit at 5 Home Road, NN5 7EA", cardAmount: 0, childcareAmount: 0, total: 20, bookingId: "x", ref: "HVF-10999", needsApproval: false } as any);
const chk = (id: string, ok: boolean, note: string) => console.log(`${ok ? "PASS" : "FAIL"} EMAIL ${id} ${note}`);
chk("parent visit email says 'We'll come to you at' + the address", /We'll come to you at/.test(out.visitParent) && /5 Home Road, NN5 7EA/.test(out.visitParent), "label+address present");
chk("parent visit email has NO map and no venue", !/booking-map|Map of/.test(out.visitParent) && !/HV Sports Hall/.test(out.visitParent), "no map/venue");
chk("parent online email has 'How to join' with the Zoom text", /How to join/.test(out.onlineParent) && /zoom\.example/.test(out.onlineParent) && /Online/.test(out.onlineParent), "join block present");
chk("parent online email has NO map/address", !/Map of|We'll come to you/.test(out.onlineParent), "none");
chk("parent venue email unchanged (Location row, no join block)", /Location/.test(out.venueParent) && !/How to join/.test(out.venueParent), "ok");
chk("provider new-booking email tells the provider where to go", /Home visit at 5 Home Road, NN5 7EA/.test(out.providerVisit), "location row present");
for (const [k, v] of Object.entries(out)) fs.writeFileSync(`/Users/kazjames/Downloads/activtyos-app-/e2e/review/shots/hv/email-${k}.html`, v);
process.exit(0);
