// UI checkout walk (parent2): records the basket text at each step so it can be compared with the booking the server stored.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("playwright");
const WEB = "http://localhost:3016";
const SCRATCH = "/private/tmp/claude-501/-Users-kazjames-Downloads-activtyos-app-/90282caf-1701-4ffc-a82d-955cde3224d8/scratchpad";
const OUT = "/Users/kazjames/Downloads/activtyos-app-/.claude/worktrees/agent-ad0f7776822163793/docs/qa-overnight/mass-bookings-shots";
const S = JSON.parse(fs.readFileSync(path.join(SCRATCH, "mb-state.json"), "utf8"));
const key = process.argv[2] || "sibling";
const passName = process.argv[3] || "Single week";
const dayLabel = process.argv[4] || "10";
const vwName = process.argv[5] || "1440";
const vw = vwName === "390" ? { width: 390, height: 844 } : { width: 1440, height: 900 };
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: vw });
const page = await ctx.newPage();
const log = [];
const snap = async (n) => {
  await page.screenshot({ path: path.join(OUT, `ui-${key}-${n}-${vwName}.png`), fullPage: true });
  const t = await page.locator("body").innerText(); log.push({ n, text: t.slice(0, 6000) });
};
await page.goto(`${WEB}/login`);
await page.getByPlaceholder("you@example.com").fill(S.accts.parent2.email);
await page.locator('input[type="password"]').fill("E2etest!123");
await page.getByRole("button", { name: "Sign in", exact: true }).click();
await page.waitForURL("**/custdash/home", { timeout: 90000 });
await page.goto(`${WEB}/book/${S.listings[key].id}`, { waitUntil: "load" });
await page.waitForTimeout(3500);
await snap("1-landing");
await page.getByText(new RegExp(`^${passName} · £`)).first().click().catch((e) => console.log("pass click", e.message));
await page.waitForTimeout(800);
// day tile
await page.locator("button", { hasText: new RegExp(`^\\s*\\w{3}\\s*${dayLabel}\\s*$`) }).first().click().catch((e) => console.log("day click", e.message));
await page.waitForTimeout(1000);
await snap("2-picked");
await page.getByRole("button", { name: /^ADD /i }).first().click().catch((e) => console.log("add", e.message));
await page.waitForTimeout(1200);
await snap("2b-basket");
await page.getByRole("button", { name: /Next/i }).first().click().catch((e) => console.log("next", e.message));
await page.waitForTimeout(2500);
await snap("3-children");
const kids = (process.env.KIDS || "Ava Second,Ben Second").split(",");
for (const k of kids) await page.getByRole("button", { name: new RegExp(`${k}.*age`) }).first().click().catch((e) => console.log("kid", k, e.message.slice(0,80)));
await page.waitForTimeout(1200);
await snap("3b-kids-picked");
await page.getByRole("button", { name: "Next", exact: true }).click().catch((e) => console.log("cont", e.message));
await page.waitForTimeout(2500);
await snap("4-pay");
await page.getByRole("button", { name: /^Confirm booking/ }).click().catch((e) => console.log("confirm", e.message.slice(0,80)));
await page.waitForTimeout(5000);
await snap("5-done");
fs.writeFileSync(path.join(SCRATCH, `ui-${key}.json`), JSON.stringify(log, null, 1));
await browser.close();
console.log("ok");
