import * as L from "./wl-lib";
const { A, call, ok, check, eq, must, book, firstBooking, sd, snap, pageFor, opAction, myBooking, mkListing, kid } = L;
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const mon = sd(0, 0);
const monRe = () => new RegExp("^Mon\\s*" + new Date(mon + "T00:00:00").getDate() + "$", "i");
(async () => {
  const Lu = await mkListing("pv", "WL UI join", { maxAttendees: "1", waitlistMode: "manual" });
  firstBooking(await book("pa", Lu, [mon], "1 day"));
  const child = "Uichild" + Date.now().toString(36).slice(-3);
  await ok("pe", "POST", "/api/my/children", { name: child, dob: "2017-03-04" });
  let ref = "";
  await check("U01-parent-joins-waitlist-in-ui", "ui", async (shots) => {
    const p = await pageFor("pe", `/book/${Lu.id}`);
    await p.getByText(/Tap a week/).first().waitFor({ timeout: 45000 });
    await p.getByRole("button", { name: "1 day · £20.00", exact: true }).click(); await p.waitForTimeout(500);
    await p.getByRole("button", { name: monRe() }).first().click();
    shots.push(await snap(p, "u01a-full-day-picked", [], false));
    await p.getByRole("button", { name: "Join the waiting list for 1 day" }).click();
    await p.getByRole("button", { name: new RegExp(child) }).first().click(); await p.waitForTimeout(600);
    await p.getByRole("button", { name: "Next", exact: true }).click();
    const ph = p.getByPlaceholder("e.g. 07700 900123"); if (await ph.isVisible().catch(() => false)) await ph.fill("07700900123");
    await p.waitForTimeout(1200);
    shots.push(await snap(p, "u01b-join-step", [/nothing to pay/i], false));
    const body = await p.locator("body").innerText();
    must(/nothing to pay/i.test(body), "checkout says nothing to pay");
    await p.getByRole("button", { name: /Join the waiting list \(nothing to pay\)/ }).click();
    await p.waitForTimeout(3500);
    shots.push(await snap(p, "u01c-joined", [/waiting list/i], false));
    const mine = (await call("pe", "GET", "/api/my/bookings")).json.find((b: any) => b.listing === "WL UI join"); ref = mine?.ref;
    eq(mine?.status, "Waitlisted", "booked as waitlisted"); eq(mine?.amountPaid ?? 0, 0, "nothing paid");
    await p.close();
    return `parent joined via the real UI: ${ref} Waitlisted, nothing paid, position ${mine.waitlist?.[0]?.position}`;
  });
  await check("U02-provider-offers-in-ui", "ui", async (shots) => {
    const aref = (await call("pv", "GET", "/api/bookings")).json.find((x: any) => x.listing === "WL UI join" && x.status === "Confirmed").ref;
    const p = await pageFor("pv", "/freelancer/bookings");
    await p.getByText(ref).first().waitFor({ timeout: 45000 });
    // offer while still full -> refusal message
    await p.getByPlaceholder(/Search booker/).fill(ref); await p.waitForTimeout(1500);
    shots.push(await snap(p, "u02a-provider-waitlisted-row", [ref], false));
    await p.getByText(/Waiting list - nothing owed/).first().click(); await p.waitForTimeout(1500);
    const offerBtn = p.getByRole("button", { name: /Offer place/i }).first();
    await offerBtn.waitFor({ timeout: 20000 });
    shots.push(await snap(p, "u02a2-provider-detail-offer-button", [], false));
    p.on("dialog", (d) => d.accept().catch(() => {}));
    await offerBtn.click(); await p.waitForTimeout(2500);
    shots.push(await snap(p, "u02b-offer-while-full", [], false));
    const txt1 = await p.locator("body").innerText(); if (!/still full|full/i.test(txt1)) console.log("NOTE: no visible message after offering into a full day");
    await opAction("pv", aref, { type: "cancel", refund: "none" }); await sleep(1500);
    await p.reload({ waitUntil: "load" }); await p.getByPlaceholder(/Search booker/).fill(ref); await p.waitForTimeout(1500);
    await p.getByText(/Waiting list - nothing owed/).first().click(); await p.waitForTimeout(1500);
    await p.getByRole("button", { name: /Offer place/i }).first().click(); await p.waitForTimeout(3000);
    shots.push(await snap(p, "u02c-offered", [], false));
    const b = (await call("pe", "GET", "/api/my/bookings")).json.find((x: any) => x.ref === ref);
    eq(b.status, "Offered", "offered via the UI");
    await p.close();
    return `Offer button works; while full the UI showed: ${(txt1.match(/still full[^\\n]{0,80}/i) ?? ["(see screenshot)"])[0]}; after a place freed -> Offered (2h)`;
  });
  await check("U03-parent-bell-and-offer-ui", "ui", async (shots) => {
    const p = await pageFor("pe", "/custdash");
    await p.waitForTimeout(2500);
    await p.locator('button[aria-label*="otification"], button:has-text("🔔")').first().click().catch(() => {});
    await p.waitForTimeout(1200);
    shots.push(await snap(p, "u03a-parent-bell", [], false));
    const txt = await p.locator("body").innerText();
    must(/A place is available/i.test(txt), "bell lists the offered place");
    await p.getByText(/A place is available/i).first().click(); await p.waitForTimeout(3000);
    shots.push(await snap(p, "u03b-after-bell-click", [/Accept the place/i], false));
    const t2 = await p.locator("body").innerText();
    must(!/isn't ready to pay/i.test(t2), "no 'not ready to pay' error");
    // accept and land on payment
    await p.getByRole("button", { name: /Accept the place/i }).click(); await p.waitForTimeout(3500);
    shots.push(await snap(p, "u03c-after-accept", [], false));
    const b = (await call("pe", "GET", "/api/my/bookings")).json.find((x: any) => x.ref === ref);
    eq(b.status, "Confirmed", "confirmed after accept");
    const t3 = await p.locator("body").innerText();
    await p.close();
    return `bell -> offer card (no error) -> Accept -> Confirmed; payment step shown: ${/pay/i.test(t3) ? "yes" : "no"}`;
  });
  await check("U04-phone-waitlist-card-390", "ui", async (shots) => {
    const Lp = await mkListing("pv", "WL UI phone", { maxAttendees: "1", waitlistMode: "manual" });
    firstBooking(await book("pa", Lp, [mon], "1 day")); const r = firstBooking(await book("pd", Lp, [mon], "1 day")); eq(r.status, "Waitlisted", "pd waits");
    const p = await pageFor("pd", "/custdash/bookings", 390);
    await p.getByText("My waiting list").first().waitFor({ timeout: 45000 });
    shots.push(await snap(p, "u04a-phone-collapsed-header", [], false));
    await p.getByText("My waiting list").first().click(); await p.waitForTimeout(800);
    await p.getByText(/Waiting for/i).first().waitFor({ timeout: 20000 });
    shots.push(await snap(p, "u04-phone-waitlist-card", [], false));
    const over = await p.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 2); await p.close();
    must(!over, "no sideways scroll");
    return "390px waiting-list card readable, no sideways scroll";
  });
  console.log("done UI2"); await L.closeAll(); process.exit(0);
})().catch((e) => { console.error(e); process.exit(1); });
