// p7be: per-page i18n sweep (P7). Row order: en, pl, ro, ur, pa, bn, ar, pt, es, fr, cy.
import { fromRows } from "./_rows";

export default fromRows({
  hintSingle: ["Tap every day you’d like — each one is a single-day pass ({sel} selected)", "Dotknij każdego dnia, który chcesz — każdy to karnet jednodniowy (wybrano: {sel})", "Atinge fiecare zi dorită — fiecare este un abonament de o zi ({sel} selectate)", "ہر وہ دن ٹیپ کریں جو آپ چاہتے ہیں — ہر ایک ایک دن کا پاس ہے ({sel} منتخب)", "ਹਰ ਉਹ ਦਿਨ ਟੈਪ ਕਰੋ ਜੋ ਤੁਸੀਂ ਚਾਹੁੰਦੇ ਹੋ — ਹਰ ਇੱਕ ਇੱਕ ਦਿਨ ਦਾ ਪਾਸ ਹੈ ({sel} ਚੁਣੇ)", "আপনার পছন্দের প্রতিটি দিনে ট্যাপ করুন — প্রতিটি একদিনের পাস ({sel}টি নির্বাচিত)", "اضغط على كل يوم تريده — كل يوم تذكرة ليوم واحد (تم اختيار {sel})", "Toque em cada dia que quiser — cada um é um passe de um dia ({sel} selecionados)", "Toca cada día que quieras: cada uno es un pase de un día ({sel} seleccionados)", "Touchez chaque jour souhaité — chacun est un pass d’un jour ({sel} sélectionnés)", "Tapiwch bob diwrnod yr hoffech — mae pob un yn bàs un diwrnod ({sel} wedi’u dewis)"],
  hintBlocks: ["Tap a week to take the fixed {need}-day block", "Dotknij tygodnia, aby wybrać stały blok {need}-dniowy", "Atinge o săptămână pentru a lua blocul fix de {need} zile", "مقررہ {need} دن کا بلاک لینے کے لیے کوئی ہفتہ ٹیپ کریں", "ਨਿਸ਼ਚਿਤ {need}-ਦਿਨ ਦਾ ਬਲਾਕ ਲੈਣ ਲਈ ਕੋਈ ਹਫ਼ਤਾ ਟੈਪ ਕਰੋ", "নির্দিষ্ট {need}-দিনের ব্লক নিতে একটি সপ্তাহে ট্যাপ করুন", "اضغط على أسبوع لأخذ الكتلة الثابتة من {need} أيام", "Toque numa semana para escolher o bloco fixo de {need} dias", "Toca una semana para tomar el bloque fijo de {need} días", "Touchez une semaine pour prendre le bloc fixe de {need} jours", "Tapiwch wythnos i gymryd y bloc sefydlog {need} diwrnod"],
  hintWeekAll: ["Tap a week to take all {need} days", "Dotknij tygodnia, aby wybrać wszystkie {need} dni", "Atinge o săptămână pentru a lua toate cele {need} zile", "تمام {need} دن لینے کے لیے کوئی ہفتہ ٹیپ کریں", "ਸਾਰੇ {need} ਦਿਨ ਲੈਣ ਲਈ ਕੋਈ ਹਫ਼ਤਾ ਟੈਪ ਕਰੋ", "সব {need} দিন নিতে একটি সপ্তাহে ট্যাপ করুন", "اضغط على أسبوع لأخذ كل الأيام ({need})", "Toque numa semana para escolher todos os {need} dias", "Toca una semana para tomar los {need} días", "Touchez une semaine pour prendre les {need} jours", "Tapiwch wythnos i gymryd pob un o’r {need} diwrnod"],
  hintWeekAny: ["Pick any {need} days within one week ({sel}/{need})", "Wybierz dowolne {need} dni w jednym tygodniu ({sel}/{need})", "Alege oricare {need} zile dintr-o săptămână ({sel}/{need})", "ایک ہفتے میں کوئی بھی {need} دن چنیں ({sel}/{need})", "ਇੱਕ ਹਫ਼ਤੇ ਵਿੱਚੋਂ ਕੋਈ ਵੀ {need} ਦਿਨ ਚੁਣੋ ({sel}/{need})", "এক সপ্তাহের মধ্যে যেকোনো {need} দিন বেছে নিন ({sel}/{need})", "اختر أي {need} أيام ضمن أسبوع واحد ({sel}/{need})", "Escolha quaisquer {need} dias numa semana ({sel}/{need})", "Elige cualquier {need} días dentro de una semana ({sel}/{need})", "Choisissez {need} jours quelconques dans une semaine ({sel}/{need})", "Dewiswch unrhyw {need} diwrnod o fewn un wythnos ({sel}/{need})"],
  hintRunAll: ["Tap any day to take the whole run — all {need} days", "Dotknij dowolnego dnia, aby wybrać cały cykl — wszystkie {need} dni", "Atinge orice zi pentru a lua tot ciclul — toate cele {need} zile", "پوری مدت لینے کے لیے کسی بھی دن پر ٹیپ کریں — تمام {need} دن", "ਪੂਰੀ ਮਿਆਦ ਲੈਣ ਲਈ ਕਿਸੇ ਵੀ ਦਿਨ 'ਤੇ ਟੈਪ ਕਰੋ — ਸਾਰੇ {need} ਦਿਨ", "পুরো সময়কাল নিতে যেকোনো দিনে ট্যাপ করুন — সব {need} দিন", "اضغط على أي يوم لأخذ الفترة كاملة — كل الأيام ({need})", "Toque em qualquer dia para escolher toda a série — todos os {need} dias", "Toca cualquier día para tomar toda la serie: los {need} días", "Touchez n’importe quel jour pour prendre toute la série — les {need} jours", "Tapiwch unrhyw ddiwrnod i gymryd y cyfnod cyfan — pob un o’r {need} diwrnod"],
  hintRunAny: ["Pick any {need} days across the weeks below ({sel}/{need})", "Wybierz dowolne {need} dni z tygodni poniżej ({sel}/{need})", "Alege oricare {need} zile din săptămânile de mai jos ({sel}/{need})", "نیچے دیے گئے ہفتوں میں سے کوئی بھی {need} دن چنیں ({sel}/{need})", "ਹੇਠਾਂ ਦਿੱਤੇ ਹਫ਼ਤਿਆਂ ਵਿੱਚੋਂ ਕੋਈ ਵੀ {need} ਦਿਨ ਚੁਣੋ ({sel}/{need})", "নিচের সপ্তাহগুলো থেকে যেকোনো {need} দিন বেছে নিন ({sel}/{need})", "اختر أي {need} أيام من الأسابيع أدناه ({sel}/{need})", "Escolha quaisquer {need} dias nas semanas abaixo ({sel}/{need})", "Elige cualquier {need} días de las semanas de abajo ({sel}/{need})", "Choisissez {need} jours quelconques parmi les semaines ci-dessous ({sel}/{need})", "Dewiswch unrhyw {need} diwrnod ar draws yr wythnosau isod ({sel}/{need})"],
  pctOff: ["{v}% off", "{v}% zniżki", "{v}% reducere", "{v}% رعایت", "{v}% ਛੋਟ", "{v}% ছাড়", "خصم {v}%", "{v}% de desconto", "{v}% de descuento", "{v} % de réduction", "{v}% i ffwrdd"],
  amtOff: ["{amt} off", "{amt} zniżki", "{amt} reducere", "{amt} رعایت", "{amt} ਛੋਟ", "{amt} ছাড়", "خصم {amt}", "{amt} de desconto", "{amt} de descuento", "{amt} de réduction", "{amt} i ffwrdd"],
  scopeOn: ["on {pass}", "na {pass}", "la {pass}", "{pass} پر", "{pass} ‘ਤੇ", "{pass}-এ", "على {pass}", "em {pass}", "en {pass}", "sur {pass}", "ar {pass}"],
  nudge_one: ["Add {n} more date to get {amt}{scope}", "Dodaj jeszcze {n} datę, aby otrzymać {amt}{scope}", "Adaugă încă {n} dată pentru a primi {amt}{scope}", "{amt}{scope} پانے کے لیے مزید {n} تاریخ شامل کریں", "{amt}{scope} ਪਾਉਣ ਲਈ ਹੋਰ {n} ਤਾਰੀਖ ਜੋੜੋ", "{amt}{scope} পেতে আরও {n}টি তারিখ যোগ করুন", "أضف تاريخًا واحدًا آخر للحصول على {amt}{scope}", "Adicione mais {n} data para obter {amt}{scope}", "Añade {n} fecha más para conseguir {amt}{scope}", "Ajoutez {n} date de plus pour obtenir {amt}{scope}", "Ychwanegwch {n} dyddiad arall i gael {amt}{scope}"],
  nudge_two: ["Add {n} more dates to get {amt}{scope}", "Dodaj jeszcze {n} daty, aby otrzymać {amt}{scope}", "Adaugă încă {n} date pentru a primi {amt}{scope}", "{amt}{scope} پانے کے لیے مزید {n} تاریخیں شامل کریں", "{amt}{scope} ਪਾਉਣ ਲਈ ਹੋਰ {n} ਤਾਰੀਖਾਂ ਜੋੜੋ", "{amt}{scope} পেতে আরও {n}টি তারিখ যোগ করুন", "أضف تاريخين آخرين للحصول على {amt}{scope}", "Adicione mais {n} datas para obter {amt}{scope}", "Añade {n} fechas más para conseguir {amt}{scope}", "Ajoutez {n} dates de plus pour obtenir {amt}{scope}", "Ychwanegwch {n} dyddiad arall i gael {amt}{scope}"],
  nudge_few: ["Add {n} more dates to get {amt}{scope}", "Dodaj jeszcze {n} daty, aby otrzymać {amt}{scope}", "Adaugă încă {n} date pentru a primi {amt}{scope}", "{amt}{scope} پانے کے لیے مزید {n} تاریخیں شامل کریں", "{amt}{scope} ਪਾਉਣ ਲਈ ਹੋਰ {n} ਤਾਰੀਖਾਂ ਜੋੜੋ", "{amt}{scope} পেতে আরও {n}টি তারিখ যোগ করুন", "أضف {n} تواريخ أخرى للحصول على {amt}{scope}", "Adicione mais {n} datas para obter {amt}{scope}", "Añade {n} fechas más para conseguir {amt}{scope}", "Ajoutez {n} dates de plus pour obtenir {amt}{scope}", "Ychwanegwch {n} dyddiad arall i gael {amt}{scope}"],
  nudge_other: ["Add {n} more dates to get {amt}{scope}", "Dodaj jeszcze {n} dat, aby otrzymać {amt}{scope}", "Adaugă încă {n} de date pentru a primi {amt}{scope}", "{amt}{scope} پانے کے لیے مزید {n} تاریخیں شامل کریں", "{amt}{scope} ਪਾਉਣ ਲਈ ਹੋਰ {n} ਤਾਰੀਖਾਂ ਜੋੜੋ", "{amt}{scope} পেতে আরও {n}টি তারিখ যোগ করুন", "أضف {n} تاريخًا آخر للحصول على {amt}{scope}", "Adicione mais {n} datas para obter {amt}{scope}", "Añade {n} fechas más para conseguir {amt}{scope}", "Ajoutez {n} dates de plus pour obtenir {amt}{scope}", "Ychwanegwch {n} dyddiad arall i gael {amt}{scope}"],
  leaveBasket: ["Going to another club will clear your basket — continue?", "Przejście do innego klubu wyczyści Twój koszyk — kontynuować?", "Trecerea la alt club îți va goli coșul — continui?", "کسی دوسرے کلب میں جانے سے آپ کی ٹوکری صاف ہو جائے گی — جاری رکھیں؟", "ਕਿਸੇ ਹੋਰ ਕਲੱਬ ਵਿੱਚ ਜਾਣ ਨਾਲ ਤੁਹਾਡੀ ਟੋਕਰੀ ਸਾਫ਼ ਹੋ ਜਾਵੇਗੀ — ਜਾਰੀ ਰੱਖਣਾ ਹੈ?", "অন্য ক্লাবে গেলে আপনার ঝুড়ি খালি হয়ে যাবে — চালিয়ে যাবেন?", "الانتقال إلى نادٍ آخر سيُفرغ سلتك — هل تتابع؟", "Ir para outro clube vai limpar o seu cesto — continuar?", "Ir a otro club vaciará tu cesta: ¿continuar?", "Aller vers un autre club videra votre panier — continuer ?", "Bydd mynd i glwb arall yn clirio eich basged — parhau?"],
  cdDays: ["{d}d {h}h {m}m", "{d} d {h} godz. {m} min", "{d} z {h} h {m} min", "{d} دن {h} گھنٹے {m} منٹ", "{d} ਦਿਨ {h} ਘੰਟੇ {m} ਮਿੰਟ", "{d} দিন {h} ঘণ্টা {m} মিনিট", "{d} ي {h} س {m} د", "{d} d {h} h {m} min", "{d} d {h} h {m} min", "{d} j {h} h {m} min", "{d} d {h} awr {m} mun"],
  onlyPlaces_one: ["Only {n} place left that day", "Tylko {n} miejsce zostało tego dnia", "A mai rămas doar {n} loc în acea zi", "اس دن صرف {n} جگہ باقی", "ਉਸ ਦਿਨ ਸਿਰਫ਼ {n} ਥਾਂ ਬਾਕੀ", "ওই দিনে মাত্র {n}টি জায়গা বাকি", "بقي مكان واحد فقط في ذلك اليوم", "Resta apenas {n} lugar nesse dia", "Queda solo {n} plaza ese día", "Plus qu’{n} place ce jour-là", "Dim ond {n} lle ar ôl y diwrnod hwnnw"],
  onlyPlaces_two: ["Only {n} places left that day", "Tylko {n} miejsca zostały tego dnia", "Au mai rămas doar {n} locuri în acea zi", "اس دن صرف {n} جگہیں باقی", "ਉਸ ਦਿਨ ਸਿਰਫ਼ {n} ਥਾਵਾਂ ਬਾਕੀ", "ওই দিনে মাত্র {n}টি জায়গা বাকি", "بقي مكانان فقط في ذلك اليوم", "Restam apenas {n} lugares nesse dia", "Quedan solo {n} plazas ese día", "Plus que {n} places ce jour-là", "Dim ond {n} lle ar ôl y diwrnod hwnnw"],
  onlyPlaces_few: ["Only {n} places left that day", "Tylko {n} miejsca zostały tego dnia", "Au mai rămas doar {n} locuri în acea zi", "اس دن صرف {n} جگہیں باقی", "ਉਸ ਦਿਨ ਸਿਰਫ਼ {n} ਥਾਵਾਂ ਬਾਕੀ", "ওই দিনে মাত্র {n}টি জায়গা বাকি", "بقيت {n} أماكن فقط في ذلك اليوم", "Restam apenas {n} lugares nesse dia", "Quedan solo {n} plazas ese día", "Plus que {n} places ce jour-là", "Dim ond {n} lle ar ôl y diwrnod hwnnw"],
  onlyPlaces_other: ["Only {n} places left that day", "Tylko {n} miejsc zostało tego dnia", "Au mai rămas doar {n} de locuri în acea zi", "اس دن صرف {n} جگہیں باقی", "ਉਸ ਦਿਨ ਸਿਰਫ਼ {n} ਥਾਵਾਂ ਬਾਕੀ", "ওই দিনে মাত্র {n}টি জায়গা বাকি", "بقي {n} مكانًا فقط في ذلك اليوم", "Restam apenas {n} lugares nesse dia", "Quedan solo {n} plazas ese día", "Plus que {n} places ce jour-là", "Dim ond {n} lle ar ôl y diwrnod hwnnw"],
  lotsOfSpace: ["Lots of space left", "Dużo wolnych miejsc", "Multe locuri libere", "بہت جگہ باقی ہے", "ਬਹੁਤ ਥਾਂ ਬਾਕੀ ਹੈ", "প্রচুর জায়গা বাকি", "أماكن كثيرة متبقية", "Muitas vagas disponíveis", "Quedan muchas plazas", "Beaucoup de places restantes", "Digon o le ar ôl"],
  soldOutNote: ["Sold out", "Wyprzedane", "Epuizat", "فروخت ہو گیا", "ਵਿਕ ਗਿਆ", "বিক্রি শেষ", "نفدت التذاكر", "Esgotado", "Agotado", "Complet", "Wedi gwerthu allan"],
  cutoffNote: ["🛑 Bookings close {label} before each session starts.", "🛑 Rezerwacje zamykają się {label} przed rozpoczęciem każdej sesji.", "🛑 Rezervările se închid cu {label} înainte de începerea fiecărei sesiuni.", "🛑 ہر سیشن شروع ہونے سے {label} پہلے بکنگ بند ہو جاتی ہے۔", "🛑 ਹਰ ਸੈਸ਼ਨ ਸ਼ੁਰੂ ਹੋਣ ਤੋਂ {label} ਪਹਿਲਾਂ ਬੁਕਿੰਗ ਬੰਦ ਹੋ ਜਾਂਦੀ ਹੈ।", "🛑 প্রতিটি সেশন শুরুর {label} আগে বুকিং বন্ধ হয়ে যায়।", "🛑 يُغلق الحجز قبل بدء كل جلسة بـ {label}.", "🛑 As reservas fecham {label} antes do início de cada sessão.", "🛑 Las reservas se cierran {label} antes de que empiece cada sesión.", "🛑 Les réservations ferment {label} avant le début de chaque séance.", "🛑 Mae archebu’n cau {label} cyn i bob sesiwn ddechrau."],
});
