// p7dash: per-page i18n sweep (P7). Row order: en, pl, ro, ur, pa, bn, ar, pt, es, fr, cy.
import { fromRows } from "./_rows";

export default fromRows({
  taskBacklog: ["Backlog", "Zaległe", "Restanțe", "بیک لاگ", "ਬੈਕਲਾਗ", "ব্যাকলগ", "قائمة الانتظار", "Pendentes", "Pendientes", "À planifier", "Ôl-groniad"],
  taskTodo: ["To do", "Do zrobienia", "De făcut", "کرنا ہے", "ਕਰਨਾ ਹੈ", "করণীয়", "قيد الانتظار للتنفيذ", "Por fazer", "Por hacer", "À faire", "I’w wneud"],
  taskProg: ["In progress", "W toku", "În desfășurare", "جاری ہے", "ਜਾਰੀ ਹੈ", "চলমান", "قيد التنفيذ", "Em curso", "En curso", "En cours", "ar y gweill"],
  taskDone: ["Done", "Zrobione", "Finalizat", "مکمل", "ਹੋ ਗਿਆ", "সম্পন্ন", "منجز", "Concluído", "Hecho", "Terminé", "Wedi gorffen"],
  noSeason: ["No season", "Brak sezonu", "Fără sezon", "کوئی سیزن نہیں", "ਕੋਈ ਸੀਜ਼ਨ ਨਹੀਂ", "কোনো মৌসুম নেই", "بلا موسم", "Sem época", "Sin temporada", "Aucune saison", "Dim tymor"],
  fullWord: ["full", "pełne", "complet", "بھرا ہوا", "ਭਰਿਆ ਹੋਇਆ", "পূর্ণ", "ممتلئ", "lotado", "completo", "complet", "llawn"],
  nLeft: ["{n} left", "zostało: {n}", "{n} rămase", "{n} باقی", "{n} ਬਾਕੀ", "{n}টি বাকি", "متبقي {n}", "restam {n}", "quedan {n}", "{n} restantes", "{n} ar ôl"],
  sessRun_one: ["{n} session running", "{n} sesja trwa", "{n} sesiune în desfășurare", "{n} سیشن جاری", "{n} ਸੈਸ਼ਨ ਚੱਲ ਰਿਹਾ ਹੈ", "{n}টি সেশন চলছে", "جلسة واحدة قيد التشغيل", "{n} sessão a decorrer", "{n} sesión en curso", "{n} séance en cours", "{n} sesiwn ar waith"],
  sessRun_two: ["{n} sessions running", "{n} sesje trwają", "{n} sesiuni în desfășurare", "{n} سیشنز جاری", "{n} ਸੈਸ਼ਨ ਚੱਲ ਰਹੇ ਹਨ", "{n}টি সেশন চলছে", "جلستان قيد التشغيل", "{n} sessões a decorrer", "{n} sesiones en curso", "{n} séances en cours", "{n} sesiwn ar waith"],
  sessRun_few: ["{n} sessions running", "{n} sesje trwają", "{n} sesiuni în desfășurare", "{n} سیشنز جاری", "{n} ਸੈਸ਼ਨ ਚੱਲ ਰਹੇ ਹਨ", "{n}টি সেশন চলছে", "{n} جلسات قيد التشغيل", "{n} sessões a decorrer", "{n} sesiones en curso", "{n} séances en cours", "{n} sesiwn ar waith"],
  sessRun_other: ["{n} sessions running", "{n} sesji trwa", "{n} de sesiuni în desfășurare", "{n} سیشنز جاری", "{n} ਸੈਸ਼ਨ ਚੱਲ ਰਹੇ ਹਨ", "{n}টি সেশন চলছে", "{n} جلسة قيد التشغيل", "{n} sessões a decorrer", "{n} sesiones en curso", "{n} séances en cours", "{n} sesiwn ar waith"],
  newBk_one: ["{n} new booking", "{n} nowa rezerwacja", "{n} rezervare nouă", "{n} نئی بکنگ", "{n} ਨਵੀਂ ਬੁਕਿੰਗ", "{n}টি নতুন বুকিং", "حجز جديد واحد", "{n} nova reserva", "{n} reserva nueva", "{n} nouvelle réservation", "{n} archeb newydd"],
  newBk_two: ["{n} new bookings", "{n} nowe rezerwacje", "{n} rezervări noi", "{n} نئی بکنگز", "{n} ਨਵੀਆਂ ਬੁਕਿੰਗਾਂ", "{n}টি নতুন বুকিং", "حجزان جديدان", "{n} novas reservas", "{n} reservas nuevas", "{n} nouvelles réservations", "{n} archeb newydd"],
  newBk_few: ["{n} new bookings", "{n} nowe rezerwacje", "{n} rezervări noi", "{n} نئی بکنگز", "{n} ਨਵੀਆਂ ਬੁਕਿੰਗਾਂ", "{n}টি নতুন বুকিং", "{n} حجوزات جديدة", "{n} novas reservas", "{n} reservas nuevas", "{n} nouvelles réservations", "{n} archeb newydd"],
  newBk_other: ["{n} new bookings", "{n} nowych rezerwacji", "{n} de rezervări noi", "{n} نئی بکنگز", "{n} ਨਵੀਆਂ ਬੁਕਿੰਗਾਂ", "{n}টি নতুন বুকিং", "{n} حجزًا جديدًا", "{n} novas reservas", "{n} reservas nuevas", "{n} nouvelles réservations", "{n} archeb newydd"],
  ovVoucher_one: ["{n} overdue voucher", "{n} zaległy bon", "{n} voucher restant", "{n} واؤچر تاخیر کا شکار", "{n} ਬਕਾਇਆ ਵਾਊਚਰ", "{n}টি বিলম্বিত ভাউচার", "قسيمة واحدة متأخرة", "{n} vale em atraso", "{n} vale vencido", "{n} chèque en retard", "{n} taleb hwyr"],
  ovVoucher_two: ["{n} overdue vouchers", "{n} zaległe bony", "{n} vouchere restante", "{n} واؤچرز تاخیر کا شکار", "{n} ਬਕਾਇਆ ਵਾਊਚਰ", "{n}টি বিলম্বিত ভাউচার", "قسيمتان متأخرتان", "{n} vales em atraso", "{n} vales vencidos", "{n} chèques en retard", "{n} taleb hwyr"],
  ovVoucher_few: ["{n} overdue vouchers", "{n} zaległe bony", "{n} vouchere restante", "{n} واؤچرز تاخیر کا شکار", "{n} ਬਕਾਇਆ ਵਾਊਚਰ", "{n}টি বিলম্বিত ভাউচার", "{n} قسائم متأخرة", "{n} vales em atraso", "{n} vales vencidos", "{n} chèques en retard", "{n} taleb hwyr"],
  ovVoucher_other: ["{n} overdue vouchers", "{n} zaległych bonów", "{n} de vouchere restante", "{n} واؤچرز تاخیر کا شکار", "{n} ਬਕਾਇਆ ਵਾਊਚਰ", "{n}টি বিলম্বিত ভাউচার", "{n} قسيمة متأخرة", "{n} vales em atraso", "{n} vales vencidos", "{n} chèques en retard", "{n} taleb hwyr"],
  funnelPaidPct: ["<b>{pct}%</b> of bookings are paid · <b>{pct2}%</b> confirmed", "<b>{pct}%</b> rezerwacji jest opłaconych · <b>{pct2}%</b> potwierdzonych", "<b>{pct}%</b> din rezervări sunt plătite · <b>{pct2}%</b> confirmate", "<b>{pct}%</b> بکنگز ادا شدہ ہیں · <b>{pct2}%</b> تصدیق شدہ", "<b>{pct}%</b> ਬੁਕਿੰਗਾਂ ਅਦਾ ਹੋ ਚੁੱਕੀਆਂ ਹਨ · <b>{pct2}%</b> ਪੁਸ਼ਟੀ ਹੋਈ", "<b>{pct}%</b> বুকিং পরিশোধিত · <b>{pct2}%</b> নিশ্চিত", "<b>{pct}%</b> من الحجوزات مدفوعة · <b>{pct2}%</b> مؤكدة", "<b>{pct}%</b> das reservas estão pagas · <b>{pct2}%</b> confirmadas", "<b>{pct}%</b> de las reservas están pagadas · <b>{pct2}%</b> confirmadas", "<b>{pct} %</b> des réservations sont payées · <b>{pct2} %</b> confirmées", "Mae <b>{pct}%</b> o’r archebion wedi’u talu · <b>{pct2}%</b> wedi’u cadarnhau"],
});
