// p7ho: head-office network oversight page (incidents / accidents / medication), all 11 locales.
// Row order: en, pl, ro, ur, pa, bn, ar, pt, es, fr, cy.
import { fromRows } from "./_rows";

export default fromRows({
  safeguardingIncidents: ["Safeguarding & incidents", "Ochrona i incydenty", "Protecție și incidente", "تحفظ اور واقعات", "ਸੁਰੱਖਿਆ ਅਤੇ ਘਟਨਾਵਾਂ", "নিরাপত্তা ও ঘটনা", "الحماية والحوادث", "Proteção e incidentes", "Protección y incidentes", "Protection et incidents", "Diogelu a digwyddiadau"],
  oversightLedeIncidents: ["Every concern and incident logged across your network — view-only oversight.", "Każde zgłoszenie i incydent zarejestrowane w sieci — nadzór tylko do odczytu.", "Fiecare sesizare și incident înregistrat în rețeaua ta — supraveghere doar pentru vizualizare.", "آپ کے نیٹ ورک بھر میں درج ہر تشویش اور واقعہ — صرف دیکھنے کی نگرانی۔", "ਤੁਹਾਡੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਦਰਜ ਹਰ ਚਿੰਤਾ ਅਤੇ ਘਟਨਾ — ਸਿਰਫ਼ ਦੇਖਣ ਲਈ ਨਿਗਰਾਨੀ।", "আপনার নেটওয়ার্ক জুড়ে নথিভুক্ত প্রতিটি উদ্বেগ ও ঘটনা — শুধু দেখার তত্ত্বাবধান।", "كل بلاغ وحادثة مسجّلة عبر شبكتك — إشراف للعرض فقط.", "Todas as preocupações e incidentes registados na sua rede — supervisão apenas de leitura.", "Todas las preocupaciones e incidentes registrados en tu red: supervisión de solo lectura.", "Toutes les préoccupations et tous les incidents enregistrés sur votre réseau — supervision en lecture seule.", "Pob pryder a digwyddiad a gofnodwyd ar draws eich rhwydwaith — goruchwyliaeth darllen yn unig."],
  accidents: ["Accidents", "Wypadki", "Accidente", "حادثات", "ਦੁਰਘਟਨਾਵਾਂ", "দুর্ঘটনা", "الحوادث العَرَضية", "Acidentes", "Accidentes", "Accidents", "Damweiniau"],
  oversightLedeAccidents: ["Every accident logged across your network — view-only oversight.", "Każdy wypadek zarejestrowany w sieci — nadzór tylko do odczytu.", "Fiecare accident înregistrat în rețeaua ta — supraveghere doar pentru vizualizare.", "آپ کے نیٹ ورک بھر میں درج ہر حادثہ — صرف دیکھنے کی نگرانی۔", "ਤੁਹਾਡੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਦਰਜ ਹਰ ਦੁਰਘਟਨਾ — ਸਿਰਫ਼ ਦੇਖਣ ਲਈ ਨਿਗਰਾਨੀ।", "আপনার নেটওয়ার্ক জুড়ে নথিভুক্ত প্রতিটি দুর্ঘটনা — শুধু দেখার তত্ত্বাবধান।", "كل إصابة عَرَضية مسجّلة عبر شبكتك — إشراف للعرض فقط.", "Todos os acidentes registados na sua rede — supervisão apenas de leitura.", "Todos los accidentes registrados en tu red: supervisión de solo lectura.", "Tous les accidents enregistrés sur votre réseau — supervision en lecture seule.", "Pob damwain a gofnodwyd ar draws eich rhwydwaith — goruchwyliaeth darllen yn unig."],
  medication: ["Medication", "Leki", "Medicație", "ادویات", "ਦਵਾਈ", "ওষুধ", "الأدوية", "Medicação", "Medicación", "Médicaments", "Meddyginiaeth"],
  oversightLedeMedication: ["Every authorised medication across your network — view-only oversight.", "Każdy autoryzowany lek w sieci — nadzór tylko do odczytu.", "Fiecare medicație autorizată în rețeaua ta — supraveghere doar pentru vizualizare.", "آپ کے نیٹ ورک بھر میں ہر مجاز دوا — صرف دیکھنے کی نگرانی۔", "ਤੁਹਾਡੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਹਰ ਅਧਿਕਾਰਤ ਦਵਾਈ — ਸਿਰਫ਼ ਦੇਖਣ ਲਈ ਨਿਗਰਾਨੀ।", "আপনার নেটওয়ার্ক জুড়ে প্রতিটি অনুমোদিত ওষুধ — শুধু দেখার তত্ত্বাবধান।", "كل دواء مصرّح به عبر شبكتك — إشراف للعرض فقط.", "Toda a medicação autorizada na sua rede — supervisão apenas de leitura.", "Toda la medicación autorizada en tu red: supervisión de solo lectura.", "Tous les médicaments autorisés sur votre réseau — supervision en lecture seule.", "Pob meddyginiaeth awdurdodedig ar draws eich rhwydwaith — goruchwyliaeth darllen yn unig."],
  nounRecords: ["records", "wpisów", "înregistrări", "ریکارڈز", "ਰਿਕਾਰਡ", "rekordy", "سجلات", "registos", "registros", "dossiers", "cofnodion"],
  nounAccidents: ["accidents", "wypadków", "accidente", "حادثات", "ਦੁਰਘਟਨਾਵਾਂ", "দুর্ঘটনা", "حوادث", "acidentes", "accidentes", "accidents", "damweiniau"],
  nounMedications: ["medications", "leków", "medicații", "ادویات", "ਦਵਾਈਆਂ", "ওষুধ", "أدوية", "medicações", "medicaciones", "médicaments", "meddyginiaethau"],
  tagAccident: ["Accident", "Wypadek", "Accident", "حادثہ", "ਦੁਰਘਟਨਾ", "দুর্ঘটনা", "حادثة عَرَضية", "Acidente", "Accidente", "Accident", "Damwain"],
  tagIncident: ["Incident", "Incydent", "Incident", "واقعہ", "ਘਟਨਾ", "ঘটনা", "حادثة", "Incidente", "Incidente", "Incident", "Digwyddiad"],
  tagSafeguarding: ["Safeguarding", "Ochrona", "Protecție", "تحفظ", "ਸੁਰੱਖਿਆ", "নিরাপত্তা", "حماية", "Proteção", "Protección", "Protection", "Diogelu"],
  tagMedication: ["Medication", "Lek", "Medicație", "دوا", "ਦਵਾਈ", "ওষুধ", "دواء", "Medicação", "Medicación", "Médicament", "Meddyginiaeth"],
  viewOnlyBanner: ["👁 View-only across the network — open a franchise to add, edit or close a record.", "👁 Tylko do odczytu w całej sieci — otwórz franczyzę, aby dodać, edytować lub zamknąć wpis.", "👁 Doar pentru vizualizare în toată rețeaua — deschide o franciză pentru a adăuga, edita sau închide o înregistrare.", "👁 پورے نیٹ ورک میں صرف دیکھنے کے لیے — ریکارڈ شامل، ترمیم یا بند کرنے کے لیے کوئی فرنچائز کھولیں۔", "👁 ਪੂਰੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਸਿਰਫ਼ ਦੇਖਣ ਲਈ — ਰਿਕਾਰਡ ਜੋੜਨ, ਸੋਧਣ ਜਾਂ ਬੰਦ ਕਰਨ ਲਈ ਫ੍ਰੈਂਚਾਈਜ਼ ਖੋਲ੍ਹੋ।", "👁 পুরো নেটওয়ার্কে শুধু দেখার জন্য — রেকর্ড যোগ, সম্পাদনা বা বন্ধ করতে একটি ফ্র্যাঞ্চাইজ খুলুন।", "👁 عرض فقط عبر الشبكة — افتح أحد الامتيازات لإضافة سجل أو تعديله أو إغلاقه.", "👁 Apenas leitura em toda a rede — abra uma franquia para adicionar, editar ou fechar um registo.", "👁 Solo lectura en toda la red: abre una franquicia para añadir, editar o cerrar un registro.", "👁 Lecture seule sur tout le réseau — ouvrez une franchise pour ajouter, modifier ou clôturer un dossier.", "👁 Darllen yn unig ar draws y rhwydwaith — agorwch fasnachfraint i ychwanegu, golygu neu gau cofnod."],
  total: ["Total", "Łącznie", "Total", "کل", "ਕੁੱਲ", "মোট", "الإجمالي", "Total", "Total", "Total", "Cyfanswm"],
  openUnresolved: ["Open / unresolved", "Otwarte / nierozwiązane", "Deschise / nerezolvate", "کھلے / غیر حل شدہ", "ਖੁੱਲ੍ਹੇ / ਅਣਸੁਲਝੇ", "খোলা / অমীমাংসিত", "مفتوحة / غير محلولة", "Em aberto / por resolver", "Abiertos / sin resolver", "Ouverts / non résolus", "Agored / heb eu datrys"],
  last30Days: ["Last 30 days", "Ostatnie 30 dni", "Ultimele 30 de zile", "پچھلے 30 دن", "ਪਿਛਲੇ 30 ਦਿਨ", "গত ৩০ দিন", "آخر 30 يومًا", "Últimos 30 dias", "Últimos 30 días", "30 derniers jours", "30 diwrnod diwethaf"],
  byFranchise: ["By franchise", "Wg franczyzy", "După franciză", "فرنچائز کے لحاظ سے", "ਫ੍ਰੈਂਚਾਈਜ਼ ਅਨੁਸਾਰ", "ফ্র্যাঞ্চাইজ অনুযায়ী", "حسب الامتياز", "Por franquia", "Por franquicia", "Par franchise", "Yn ôl masnachfraint"],
  in30d: ["{count} in 30d", "{count} w 30 dni", "{count} în 30 z.", "30 دن میں {count}", "30 ਦਿਨਾਂ ਵਿੱਚ {count}", "৩০ দিনে {count}", "{count} خلال 30 يومًا", "{count} em 30 d", "{count} en 30 d", "{count} sur 30 j", "{count} mewn 30 d"],
  noNounToShow: ["No {noun} to show.", "Brak pozycji do wyświetlenia: {noun}.", "Niciun element de afișat: {noun}.", "دکھانے کے لیے کوئی {noun} نہیں۔", "ਦਿਖਾਉਣ ਲਈ ਕੋਈ {noun} ਨਹੀਂ।", "দেখানোর মতো কোনো {noun} নেই।", "لا توجد {noun} للعرض.", "Sem {noun} para mostrar.", "No hay {noun} que mostrar.", "Aucun élément à afficher ({noun}).", "Dim {noun} i’w dangos."],
  openWord: ["Open", "Otwarte", "Deschis", "کھلا", "ਖੁੱਲ੍ਹਾ", "খোলা", "مفتوح", "Aberto", "Abierto", "Ouvert", "Agored"],
  hoBadge: ["HO", "HO", "HO", "HO", "HO", "HO", "المقر", "HO", "HO", "SIÈGE", "PS"],
  openArrow: ["Open →", "Otwórz →", "Deschide →", "کھولیں →", "ਖੋਲ੍ਹੋ →", "খুলুন →", "افتح ←", "Abrir →", "Abrir →", "Ouvrir →", "Agor →"],
  openCount: ["{count} open", "{count} otwartych", "{count} deschise", "{count} کھلے", "{count} ਖੁੱਲ੍ਹੇ", "{count}টি খোলা", "{count} مفتوحة", "{count} em aberto", "{count} abiertos", "{count} ouverts", "{count} yn agored"],
  all: ["All", "Wszystkie", "Toate", "تمام", "ਸਾਰੇ", "সব", "الكل", "Todos", "Todos", "Tous", "Pob un"],
  loading: ["Loading…", "Ładowanie…", "Se încarcă…", "لوڈ ہو رہا ہے…", "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…", "লোড হচ্ছে…", "جارٍ التحميل…", "A carregar…", "Cargando…", "Chargement…", "Yn llwytho…"],
  couldntLoad: ["Couldn’t load", "Nie udało się wczytać", "Nu s-a putut încărca", "لوڈ نہیں ہو سکا", "ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ", "লোড করা যায়নি", "تعذّر التحميل", "Não foi possível carregar", "No se pudo cargar", "Impossible de charger", "Methu llwytho"],
});
