// Parent-portal leftovers found by the P7 per-page sweep (wallet + memberships sentences that were built from English fragments).
// Row order: en, pl, ro, ur, pa, bn, ar, pt, es, fr, cy.
import { fromRows } from "./_rows";

export default fromRows({
  benCreditHead: ["{amount} in your wallet", "{amount} w Twoim portfelu", "{amount} în portofelul tău", "آپ کے والٹ میں {amount}", "ਤੁਹਾਡੇ ਵਾਲਿਟ ਵਿੱਚ {amount}", "আপনার ওয়ালেটে {amount}", "{amount} في محفظتك", "{amount} na sua carteira", "{amount} en tu monedero", "{amount} dans votre portefeuille", "{amount} yn eich waled"],
  benCreditSub: ["topped up every month — yours to spend on any booking", "doładowywane co miesiąc — możesz wydać na dowolną rezerwację", "reîncărcat în fiecare lună — îl poți folosi la orice rezervare", "ہر ماہ بھرا جاتا ہے — کسی بھی بکنگ پر خرچ کریں", "ਹਰ ਮਹੀਨੇ ਭਰਿਆ ਜਾਂਦਾ ਹੈ — ਕਿਸੇ ਵੀ ਬੁਕਿੰਗ 'ਤੇ ਖਰਚ ਕਰੋ", "প্রতি মাসে ভরা হয় — যেকোনো বুকিংয়ে খরচ করুন", "يُضاف كل شهر — أنفقه على أي حجز", "carregado todos os meses — para gastar em qualquer reserva", "se recarga cada mes — para gastar en cualquier reserva", "rechargé chaque mois — à dépenser sur n'importe quelle réservation", "yn cael ei ychwanegu bob mis — i'w wario ar unrhyw archeb"],
  benPctHead: ["{pct}% off, every time", "{pct}% zniżki za każdym razem", "{pct}% reducere, de fiecare dată", "ہر بار {pct}% رعایت", "ਹਰ ਵਾਰ {pct}% ਛੋਟ", "প্রতিবার {pct}% ছাড়", "خصم {pct}% في كل مرة", "{pct}% de desconto, sempre", "{pct}% de descuento, siempre", "{pct} % de réduction, à chaque fois", "{pct}% i ffwrdd, bob tro"],
  benPctSub: ["applied automatically at checkout, stacking on top of any coupons", "naliczane automatycznie przy płatności, łączy się z kuponami", "aplicată automat la plată, se cumulează cu orice cupoane", "چیک آؤٹ پر خود بخود لاگو ہوتی ہے، کوپنز کے ساتھ بھی ملتی ہے", "ਚੈੱਕਆਊਟ 'ਤੇ ਆਪਣੇ ਆਪ ਲਾਗੂ ਹੁੰਦੀ ਹੈ, ਕੂਪਨਾਂ ਦੇ ਨਾਲ ਵੀ ਚੱਲਦੀ ਹੈ", "চেকআউটে স্বয়ংক্রিয়ভাবে প্রযোজ্য, যেকোনো কুপনের সঙ্গেও চলে", "تُطبَّق تلقائيًا عند الدفع وتُضاف إلى أي قسائم", "aplicado automaticamente no pagamento, acumulável com cupões", "se aplica automáticamente al pagar y se suma a cualquier cupón", "appliquée automatiquement au paiement, cumulable avec les coupons", "yn cael ei gymhwyso'n awtomatig wrth dalu, ar ben unrhyw gwponau"],
  benCreditShort: ["{amount}/mo wallet credit", "{amount}/mies. w portfelu", "{amount}/lună în portofel", "{amount}/ماہ والٹ کریڈٹ", "{amount}/ਮਹੀਨਾ ਵਾਲਿਟ ਕ੍ਰੈਡਿਟ", "{amount}/মাস ওয়ালেট ক্রেডিট", "{amount}/شهر رصيد محفظة", "{amount}/mês em crédito", "{amount}/mes en crédito", "{amount}/mois en crédit", "{amount}/mis o gredyd waled"],
  benPctShort: ["{pct}% off every booking", "{pct}% zniżki na każdą rezerwację", "{pct}% reducere la fiecare rezervare", "ہر بکنگ پر {pct}% رعایت", "ਹਰ ਬੁਕਿੰਗ 'ਤੇ {pct}% ਛੋਟ", "প্রতিটি বুকিংয়ে {pct}% ছাড়", "خصم {pct}% على كل حجز", "{pct}% de desconto em cada reserva", "{pct}% de descuento en cada reserva", "{pct} % de réduction sur chaque réservation", "{pct}% i ffwrdd pob archeb"],
  renews: ["renews {date}", "odnawia się {date}", "se reînnoiește la {date}", "{date} کو تجدید ہوگی", "{date} ਨੂੰ ਨਵਿਆਈ ਜਾਵੇਗੀ", "{date} তারিখে নবায়ন হবে", "تُجدَّد في {date}", "renova em {date}", "se renueva el {date}", "se renouvelle le {date}", "yn adnewyddu ar {date}"],
  perMo: ["{amount}/mo", "{amount}/mies.", "{amount}/lună", "{amount}/ماہ", "{amount}/ਮਹੀਨਾ", "{amount}/মাস", "{amount}/شهر", "{amount}/mês", "{amount}/mes", "{amount}/mois", "{amount}/mis"],
  acrossOne: ["across 1 provider · applied automatically at checkout", "u 1 organizatora · naliczane automatycznie przy płatności", "la 1 furnizor · aplicat automat la plată", "1 فراہم کنندہ میں · چیک آؤٹ پر خود بخود لاگو", "1 ਪ੍ਰਦਾਤਾ ਵਿੱਚ · ਚੈੱਕਆਊਟ 'ਤੇ ਆਪਣੇ ਆਪ ਲਾਗੂ", "১ জন প্রদানকারীর মধ্যে · চেকআউটে স্বয়ংক্রিয়ভাবে প্রযোজ্য", "لدى مزوّد واحد · يُطبَّق تلقائيًا عند الدفع", "em 1 fornecedor · aplicado automaticamente no pagamento", "en 1 proveedor · se aplica automáticamente al pagar", "chez 1 prestataire · appliqué automatiquement au paiement", "ar draws 1 darparwr · yn cael ei gymhwyso'n awtomatig wrth dalu"],
  acrossMany: ["across {n} providers · applied automatically at checkout", "u {n} organizatorów · naliczane automatycznie przy płatności", "la {n} furnizori · aplicat automat la plată", "{n} فراہم کنندگان میں · چیک آؤٹ پر خود بخود لاگو", "{n} ਪ੍ਰਦਾਤਿਆਂ ਵਿੱਚ · ਚੈੱਕਆਊਟ 'ਤੇ ਆਪਣੇ ਆਪ ਲਾਗੂ", "{n} জন প্রদানকারীর মধ্যে · চেকআউটে স্বয়ংক্রিয়ভাবে প্রযোজ্য", "لدى {n} مزوّدين · يُطبَّق تلقائيًا عند الدفع", "em {n} fornecedores · aplicado automaticamente no pagamento", "en {n} proveedores · se aplica automáticamente al pagar", "chez {n} prestataires · appliqué automatiquement au paiement", "ar draws {n} darparwr · yn cael ei gymhwyso'n awtomatig wrth dalu"],
  addedSpent: ["{added} added · {spent} spent ·", "{added} dodano · {spent} wydano ·", "{added} adăugat · {spent} cheltuit ·", "{added} شامل · {spent} خرچ ·", "{added} ਜੋੜਿਆ · {spent} ਖਰਚਿਆ ·", "{added} যোগ · {spent} খরচ ·", "{added} أُضيف · {spent} أُنفق ·", "{added} adicionado · {spent} gasto ·", "{added} añadido · {spent} gastado ·", "{added} ajouté · {spent} dépensé ·", "{added} wedi'i ychwanegu · {spent} wedi'i wario ·"],
  amountLeft: ["{amount} left", "zostało {amount}", "{amount} rămas", "{amount} باقی", "{amount} ਬਾਕੀ", "{amount} বাকি", "المتبقي {amount}", "restam {amount}", "quedan {amount}", "{amount} restant", "{amount} ar ôl"],
  membershipOf: ["{name} membership", "Członkostwo {name}", "Abonament {name}", "{name} رکنیت", "{name} ਮੈਂਬਰਸ਼ਿਪ", "{name} সদস্যপদ", "عضوية {name}", "Subscrição {name}", "Membresía {name}", "Adhésion {name}", "Aelodaeth {name}"],
  creditEachMonth: ["+{amount} credit each month", "+{amount} środków co miesiąc", "+{amount} credit în fiecare lună", "ہر ماہ +{amount} کریڈٹ", "ਹਰ ਮਹੀਨੇ +{amount} ਕ੍ਰੈਡਿਟ", "প্রতি মাসে +{amount} ক্রেডিট", "+{amount} رصيد كل شهر", "+{amount} de crédito todos os meses", "+{amount} de crédito cada mes", "+{amount} de crédit chaque mois", "+{amount} o gredyd bob mis"],
  refN: ["Ref {ref}", "Nr ref. {ref}", "Ref. {ref}", "حوالہ {ref}", "ਹਵਾਲਾ {ref}", "রেফ {ref}", "المرجع {ref}", "Ref. {ref}", "Ref. {ref}", "Réf. {ref}", "Cyf. {ref}"],
  noCredit: ["When a booking is cancelled and you choose <b>wallet credit</b> — or a provider gives you a credit note — it lands here, ready to spend on your next booking with them.", "Gdy rezerwacja zostanie anulowana i wybierzesz <b>środki w portfelu</b> — lub organizator wystawi Ci notę kredytową — trafią tutaj i będzie można je wydać na kolejną rezerwację u niego.", "Când o rezervare este anulată și alegi <b>credit în portofel</b> — sau un furnizor îți dă o notă de credit — apare aici, gata de folosit la următoarea rezervare la el.", "جب کوئی بکنگ منسوخ ہو اور آپ <b>والٹ کریڈٹ</b> — یا کوئی فراہم کنندہ آپ کو کریڈٹ نوٹ دے — تو وہ یہاں آ جاتا ہے، ان کے ساتھ اگلی بکنگ پر خرچ کرنے کے لیے تیار۔", "ਜਦੋਂ ਕੋਈ ਬੁਕਿੰਗ ਰੱਦ ਹੁੰਦੀ ਹੈ ਅਤੇ ਤੁਸੀਂ <b>ਵਾਲਿਟ ਕ੍ਰੈਡਿਟ</b> — ਜਾਂ ਕੋਈ ਪ੍ਰਦਾਤਾ ਤੁਹਾਨੂੰ ਕ੍ਰੈਡਿਟ ਨੋਟ ਦਿੰਦਾ ਹੈ — ਤਾਂ ਇਹ ਇੱਥੇ ਆ ਜਾਂਦਾ ਹੈ, ਉਨ੍ਹਾਂ ਨਾਲ ਅਗਲੀ ਬੁਕਿੰਗ 'ਤੇ ਖਰਚ ਕਰਨ ਲਈ ਤਿਆਰ।", "কোনো বুকিং বাতিল হলে এবং আপনি <b>ওয়ালেট ক্রেডিট</b> — অথবা কোনো প্রদানকারী আপনাকে ক্রেডিট নোট দেয় — তা এখানে জমা হয়, তাদের সঙ্গে আপনার পরের বুকিংয়ে খরচ করার জন্য প্রস্তুত।", "عند إلغاء حجز واختيارك <b>رصيد المحفظة</b> — أو يمنحك المزوّد إشعارًا دائنًا — فيظهر هنا جاهزًا للإنفاق على حجزك القادم لديه.", "Quando uma reserva é cancelada e escolhe <b>crédito na carteira</b> — ou um fornecedor lhe dá uma nota de crédito — fica aqui, pronto a gastar na sua próxima reserva com ele.", "Cuando se cancela una reserva y eliges <b>crédito en el monedero</b> — o un proveedor te da una nota de crédito — aparece aquí, listo para gastar en tu próxima reserva con él.", "Lorsqu'une réservation est annulée et que vous choisissez <b>un crédit sur le portefeuille</b> — ou qu'un prestataire vous remet un avoir — il arrive ici, prêt à être dépensé sur votre prochaine réservation chez lui.", "Pan fydd archeb yn cael ei chanslo a chithau'n dewis <b>credyd waled</b> — neu pan fydd darparwr yn rhoi nodyn credyd i chi — mae'n glanio yma, yn barod i'w wario ar eich archeb nesaf gyda nhw."],
});
