// rfm: how an OFFLINE refund (paid by cash, bank transfer or voucher) reaches the family - the app cannot move that money, so the provider sends it and every
// screen / bell / email names the method actually paid (features/bookings/refundMethod.ts picks the kinds and builds the sentences).
// Row order: en, pl, ro, ur, pa, bn, ar, pt, es, fr, cy. Languages other than English are machine drafted (to be reviewed by a native speaker).
import { fromRows } from "./_rows";

export default fromRows({
  // The method names (a noun each) and "how" phrases. A mix joins the nouns ("bank transfer and cash") inside hMix.
  nBank: ["bank transfer", "przelew bankowy", "transfer bancar", "بینک ٹرانسفر", "ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ", "ব্যাংক ট্রান্সফার", "تحويل مصرفي", "transferência bancária", "transferencia bancaria", "virement bancaire", "trosglwyddiad banc"],
  nCash: ["cash", "gotówka", "numerar", "نقد", "ਨਕਦ", "নগদ", "نقد", "dinheiro", "efectivo", "espèces", "arian parod"],
  nVoucher: ["voucher", "bon", "voucher", "واؤچر", "ਵਾਊਚਰ", "ভাউচার", "قسيمة", "vale", "vale", "bon", "taleb"],
  hBank: ["by bank transfer", "przelewem bankowym", "prin transfer bancar", "بینک ٹرانسفر کے ذریعے", "ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਰਾਹੀਂ", "ব্যাংক ট্রান্সফারের মাধ্যমে", "عن طريق تحويل مصرفي", "por transferência bancária", "por transferencia bancaria", "par virement bancaire", "drwy drosglwyddiad banc"],
  hCash: ["in cash", "gotówką", "în numerar", "نقد کی صورت میں", "ਨਕਦ ਵਿੱਚ", "নগদে", "نقدًا", "em dinheiro", "en efectivo", "en espèces", "ag arian parod"],
  hVoucher: ["by voucher", "bonem", "prin voucher", "واؤچر کے ذریعے", "ਵਾਊਚਰ ਰਾਹੀਂ", "ভাউচারের মাধ্যমে", "عن طريق قسيمة", "por vale", "mediante vale", "par bon", "drwy daleb"],
  hMix: ["by {methods}", "w formie: {methods}", "prin {methods}", "بذریعہ {methods}", "{methods} ਰਾਹੀਂ", "{methods} এর মাধ্যমে", "عبر {methods}", "por {methods}", "mediante {methods}", "par {methods}", "drwy {methods}"],
  yourProv: ["your provider", "Twój organizator", "furnizorul tău", "آپ کا فراہم کنندہ", "ਤੁਹਾਡਾ ਪ੍ਰਦਾਤਾ", "আপনার প্রদানকারী", "مزوّدك", "o seu fornecedor", "tu proveedor", "votre prestataire", "eich darparwr"],
  // The family's destination choice at cancellation (wallet credit is the other, pre-selected, option).
  optBank: ["Ask {provider} to send me my {amt} back by bank transfer", "Poproś {provider} o odesłanie mi {amt} przelewem bankowym", "Cere-i lui {provider} să-mi trimită înapoi {amt} prin transfer bancar", "{provider} سے کہیں کہ میرے {amt} بینک ٹرانسفر سے واپس بھیجے", "{provider} ਨੂੰ ਕਹੋ ਕਿ ਮੇਰੇ {amt} ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਰਾਹੀਂ ਵਾਪਸ ਭੇਜੇ", "{provider}-কে বলুন আমার {amt} ব্যাংক ট্রান্সফারে ফেরত পাঠাতে", "اطلب من {provider} إعادة {amt} إليّ عن طريق تحويل مصرفي", "Pedir a {provider} que me devolva os meus {amt} por transferência bancária", "Pedir a {provider} que me devuelva mis {amt} por transferencia bancaria", "Demander à {provider} de me renvoyer mes {amt} par virement bancaire", "Gofyn i {provider} anfon fy {amt} yn ôl drwy drosglwyddiad banc"],
  optCash: ["Ask {provider} to hand me my {amt} cash back", "Poproś {provider} o oddanie mi {amt} w gotówce", "Cere-i lui {provider} să-mi dea înapoi {amt} în numerar", "{provider} سے کہیں کہ میرے {amt} نقد واپس دے", "{provider} ਨੂੰ ਕਹੋ ਕਿ ਮੇਰੇ {amt} ਨਕਦ ਵਾਪਸ ਦੇਵੇ", "{provider}-কে বলুন আমার {amt} নগদে ফেরত দিতে", "اطلب من {provider} أن يعيد لي {amt} نقدًا", "Pedir a {provider} que me entregue os meus {amt} em dinheiro", "Pedir a {provider} que me entregue mis {amt} en efectivo", "Demander à {provider} de me rendre mes {amt} en espèces", "Gofyn i {provider} roi fy {amt} yn ôl i mi mewn arian parod"],
  optVoucher: ["Ask {provider} to refund my {amt} voucher", "Poproś {provider} o zwrot mojego bonu na {amt}", "Cere-i lui {provider} să ramburseze voucherul meu de {amt}", "{provider} سے کہیں کہ میرے {amt} کا واؤچر واپس کرے", "{provider} ਨੂੰ ਕਹੋ ਕਿ ਮੇਰਾ {amt} ਦਾ ਵਾਊਚਰ ਵਾਪਸ ਕਰੇ", "{provider}-কে বলুন আমার {amt} ভাউচার ফেরত দিতে", "اطلب من {provider} رد قيمة قسيمتي البالغة {amt}", "Pedir a {provider} que reembolse o meu vale de {amt}", "Pedir a {provider} que reembolse mi vale de {amt}", "Demander à {provider} de rembourser mon bon de {amt}", "Gofyn i {provider} ad-dalu fy nhaleb {amt}"],
  optMix: ["Ask {provider} to send me my {amt} back by {methods}", "Poproś {provider} o odesłanie mi {amt} w formie: {methods}", "Cere-i lui {provider} să-mi trimită înapoi {amt} prin {methods}", "{provider} سے کہیں کہ میرے {amt} بذریعہ {methods} واپس کرے", "{provider} ਨੂੰ ਕਹੋ ਕਿ ਮੇਰੇ {amt} {methods} ਰਾਹੀਂ ਵਾਪਸ ਕਰੇ", "{provider}-কে বলুন আমার {amt} {methods} এর মাধ্যমে ফেরত দিতে", "اطلب من {provider} إعادة {amt} إليّ عبر {methods}", "Pedir a {provider} que me devolva os meus {amt} por {methods}", "Pedir a {provider} que me devuelva mis {amt} mediante {methods}", "Demander à {provider} de me renvoyer mes {amt} par {methods}", "Gofyn i {provider} anfon fy {amt} yn ôl drwy {methods}"],
  // The family, once the provider has recorded the refund (it is only "refunded" when the provider says they sent it).
  parentRec: ["Refund recorded: {provider} will send your {amt} {methods} refund", "Zwrot zapisany: {provider} wyśle Twój zwrot {amt} ({methods})", "Rambursare înregistrată: {provider} îți va trimite rambursarea de {amt} ({methods})", "واپسی درج ہو گئی: {provider} آپ کے {amt} کی واپسی ({methods}) بھیجے گا", "ਰਿਫੰਡ ਦਰਜ ਹੋਇਆ: {provider} ਤੁਹਾਡਾ {amt} ਦਾ ਰਿਫੰਡ ({methods}) ਭੇਜੇਗਾ", "রিফান্ড নথিভুক্ত: {provider} আপনার {amt} রিফান্ড ({methods}) পাঠাবে", "تم تسجيل الاسترداد: سيرسل {provider} استرداد {amt} ({methods})", "Reembolso registado: {provider} vai enviar o seu reembolso de {amt} ({methods})", "Reembolso registrado: {provider} enviará tu reembolso de {amt} ({methods})", "Remboursement enregistré : {provider} vous enverra votre remboursement de {amt} ({methods})", "Ad-daliad wedi'i gofnodi: bydd {provider} yn anfon eich ad-daliad {amt} ({methods})"],
  // Before the provider has approved (the released-days preview).
  willSend: ["{provider} will send your {amt} {methods} refund once they approve it.", "{provider} wyśle Twój zwrot {amt} ({methods}) po jego zatwierdzeniu.", "{provider} îți va trimite rambursarea de {amt} ({methods}) după ce o aprobă.", "{provider} منظوری کے بعد آپ کے {amt} کی واپسی ({methods}) بھیجے گا۔", "{provider} ਮਨਜ਼ੂਰੀ ਮਗਰੋਂ ਤੁਹਾਡਾ {amt} ਦਾ ਰਿਫੰਡ ({methods}) ਭੇਜੇਗਾ।", "{provider} অনুমোদনের পর আপনার {amt} রিফান্ড ({methods}) পাঠাবে।", "سيرسل {provider} استرداد {amt} ({methods}) بعد موافقته عليه.", "{provider} vai enviar o seu reembolso de {amt} ({methods}) depois de o aprovar.", "{provider} enviará tu reembolso de {amt} ({methods}) cuando lo apruebe.", "{provider} vous enverra votre remboursement de {amt} ({methods}) dès qu'il l'aura approuvé.", "Bydd {provider} yn anfon eich ad-daliad {amt} ({methods}) unwaith y bydd wedi'i gymeradwyo."],
  bellRec: ["{amt} refund approved for {listing}: {provider} will send your {methods} refund (we'll tell you when it's sent).", "Zwrot {amt} dla „{listing}” zatwierdzony: {provider} wyśle Twój zwrot ({methods}) — powiadomimy Cię, gdy zostanie wysłany.", "Rambursare de {amt} aprobată pentru „{listing}”: {provider} îți va trimite rambursarea ({methods}) — te anunțăm când e trimisă.", "{listing} کے لیے {amt} کی واپسی منظور: {provider} آپ کی واپسی ({methods}) بھیجے گا — بھیجے جانے پر ہم آپ کو بتائیں گے۔", "{listing} ਲਈ {amt} ਦਾ ਰਿਫੰਡ ਮਨਜ਼ੂਰ: {provider} ਤੁਹਾਡਾ ਰਿਫੰਡ ({methods}) ਭੇਜੇਗਾ — ਭੇਜੇ ਜਾਣ ’ਤੇ ਅਸੀਂ ਦੱਸਾਂਗੇ।", "{listing}-এর জন্য {amt} রিফান্ড অনুমোদিত: {provider} আপনার রিফান্ড ({methods}) পাঠাবে — পাঠানো হলে আমরা জানাব।", "تمت الموافقة على استرداد {amt} لـ «{listing}»: سيرسل {provider} المبلغ ({methods}) — سنخبرك عند إرساله.", "Reembolso de {amt} aprovado para «{listing}»: {provider} vai enviar o seu reembolso ({methods}) — avisamos quando for enviado.", "Reembolso de {amt} aprobado para «{listing}»: {provider} enviará tu reembolso ({methods}); te avisaremos cuando se envíe.", "Remboursement de {amt} approuvé pour « {listing} » : {provider} vous enverra le remboursement ({methods}) — nous vous préviendrons à l'envoi.", "Ad-daliad {amt} wedi'i gymeradwyo ar gyfer {listing}: bydd {provider} yn anfon eich ad-daliad ({methods}) — byddwn yn dweud wrthych pan fydd wedi'i anfon."],
  // The provider: the owed line, what to send, the chips, the confirm panel and the approve panel.
  owed: ["Refund {amt} owed: paid {how}", "Zwrot {amt} do wypłaty: zapłacono {how}", "Rambursare de {amt} datorată: plătit {how}", "{amt} کی واپسی واجب: ادائیگی {how}", "{amt} ਦਾ ਰਿਫੰਡ ਬਕਾਇਆ: ਭੁਗਤਾਨ {how}", "{amt} রিফান্ড বাকি: পরিশোধ {how}", "استرداد {amt} مستحق: تم الدفع {how}", "Reembolso de {amt} em dívida: pago {how}", "Reembolso de {amt} pendiente: pagado {how}", "Remboursement de {amt} dû : payé {how}", "Ad-daliad {amt} yn ddyledus: talwyd {how}"],
  sBank: ["Send {amt} by bank transfer", "Wyślij {amt} przelewem bankowym", "Trimite {amt} prin transfer bancar", "{amt} بینک ٹرانسفر سے بھیجیں", "{amt} ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਰਾਹੀਂ ਭੇਜੋ", "{amt} ব্যাংক ট্রান্সফারে পাঠান", "أرسل {amt} عن طريق تحويل مصرفي", "Enviar {amt} por transferência bancária", "Enviar {amt} por transferencia bancaria", "Envoyer {amt} par virement bancaire", "Anfon {amt} drwy drosglwyddiad banc"],
  sCash: ["Hand back {amt} in cash", "Oddaj {amt} w gotówce", "Înapoiază {amt} în numerar", "{amt} نقد واپس دیں", "{amt} ਨਕਦ ਵਾਪਸ ਦਿਓ", "{amt} নগদে ফেরত দিন", "أعد {amt} نقدًا", "Devolver {amt} em dinheiro", "Devolver {amt} en efectivo", "Rendre {amt} en espèces", "Rhoi {amt} yn ôl mewn arian parod"],
  sVoucher: ["Refund {amt} by voucher", "Zwróć {amt} przez bon", "Rambursează {amt} prin voucher", "{amt} واؤچر کے ذریعے واپس کریں", "{amt} ਵਾਊਚਰ ਰਾਹੀਂ ਵਾਪਸ ਕਰੋ", "{amt} ভাউচারের মাধ্যমে ফেরত দিন", "رد {amt} عن طريق قسيمة", "Reembolsar {amt} por vale", "Reembolsar {amt} mediante vale", "Rembourser {amt} par bon", "Ad-dalu {amt} drwy daleb"],
  sMix: ["Send {amt}: {methods}", "Wyślij {amt}: {methods}", "Trimite {amt}: {methods}", "{amt} بھیجیں: {methods}", "{amt} ਭੇਜੋ: {methods}", "{amt} পাঠান: {methods}", "أرسل {amt}: {methods}", "Enviar {amt}: {methods}", "Enviar {amt}: {methods}", "Envoyer {amt} : {methods}", "Anfon {amt}: {methods}"],
  chip: ["Refund recorded — {methods} to send", "Zwrot zapisany — do wysłania: {methods}", "Rambursare înregistrată — de trimis: {methods}", "واپسی درج ہو گئی — بھیجنا باقی: {methods}", "ਰਿਫੰਡ ਦਰਜ ਹੋਇਆ — ਭੇਜਣਾ ਬਾਕੀ: {methods}", "রিফান্ড নথিভুক্ত — পাঠানো বাকি: {methods}", "تم تسجيل الاسترداد — بانتظار الإرسال: {methods}", "Reembolso registado — por enviar: {methods}", "Reembolso registrado — por enviar: {methods}", "Remboursement enregistré — à envoyer : {methods}", "Ad-daliad wedi'i gofnodi — i'w anfon: {methods}"],
  chipAmt: ["Refund recorded — {methods} to send · {amt}", "Zwrot zapisany — do wysłania: {methods} · {amt}", "Rambursare înregistrată — de trimis: {methods} · {amt}", "واپسی درج ہو گئی — بھیجنا باقی: {methods} · {amt}", "ਰਿਫੰਡ ਦਰਜ ਹੋਇਆ — ਭੇਜਣਾ ਬਾਕੀ: {methods} · {amt}", "রিফান্ড নথিভুক্ত — পাঠানো বাকি: {methods} · {amt}", "تم تسجيل الاسترداد — بانتظار الإرسال: {methods} · {amt}", "Reembolso registado — por enviar: {methods} · {amt}", "Reembolso registrado — por enviar: {methods} · {amt}", "Remboursement enregistré — à envoyer : {methods} · {amt}", "Ad-daliad wedi'i gofnodi — i'w anfon: {methods} · {amt}"],
  confHead: ["Have you sent the {amt} refund {how}?", "Czy wysłano zwrot {amt} ({how})?", "Ai trimis rambursarea de {amt} ({how})?", "کیا آپ نے {amt} کی واپسی بھیج دی ({how})؟", "ਕੀ ਤੁਸੀਂ {amt} ਦਾ ਰਿਫੰਡ ਭੇਜ ਦਿੱਤਾ ({how})?", "আপনি কি {amt} রিফান্ড পাঠিয়েছেন ({how})?", "هل أرسلت استرداد {amt} ({how})؟", "Já enviou o reembolso de {amt} ({how})?", "¿Has enviado el reembolso de {amt} ({how})?", "Avez-vous envoyé le remboursement de {amt} ({how}) ?", "Ydych chi wedi anfon yr ad-daliad {amt} ({how})?"],
  confBody: ["This app can't move {methods} refunds. Press Yes only once you have sent {amt} to {name}. We'll then tell them it has been sent.", "Ta aplikacja nie przekazuje zwrotów ({methods}). Naciśnij Tak dopiero po wysłaniu {amt} do {name}. Wtedy poinformujemy, że zostało wysłane.", "Această aplicație nu poate muta rambursări ({methods}). Apasă Da doar după ce ai trimis {amt} către {name}. Apoi îi vom anunța că a fost trimis.", "یہ ایپ ({methods}) کی واپسی منتقل نہیں کر سکتی۔ ہاں صرف تب دبائیں جب آپ {name} کو {amt} بھیج چکے ہوں۔ پھر ہم انہیں بتا دیں گے کہ بھیج دیا گیا ہے۔", "ਇਹ ਐਪ ({methods}) ਰਿਫੰਡ ਨਹੀਂ ਭੇਜ ਸਕਦੀ। ਹਾਂ ਤਦ ਹੀ ਦਬਾਓ ਜਦੋਂ ਤੁਸੀਂ {name} ਨੂੰ {amt} ਭੇਜ ਚੁੱਕੇ ਹੋਵੋ। ਫਿਰ ਅਸੀਂ ਉਨ੍ਹਾਂ ਨੂੰ ਦੱਸਾਂਗੇ ਕਿ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ।", "এই অ্যাপ ({methods}) রিফান্ড পাঠাতে পারে না। {name}-কে {amt} পাঠানোর পরই হ্যাঁ চাপুন। তখন আমরা তাঁদের জানাব যে পাঠানো হয়েছে।", "لا يستطيع هذا التطبيق نقل مبالغ الاسترداد ({methods}). اضغط «نعم» فقط بعد أن ترسل {amt} إلى {name}. سنخبرهم حينها بأنه أُرسل.", "Esta aplicação não consegue mover reembolsos ({methods}). Prima Sim só depois de ter enviado {amt} a {name}. Depois avisamos que foi enviado.", "Esta aplicación no puede mover reembolsos ({methods}). Pulsa Sí solo cuando hayas enviado {amt} a {name}. Entonces les avisaremos de que se ha enviado.", "Cette application ne peut pas déplacer les remboursements ({methods}). Appuyez sur Oui seulement après avoir envoyé {amt} à {name}. Nous les préviendrons alors que c'est envoyé.", "Ni all yr ap hwn symud ad-daliadau ({methods}). Pwyswch Ie dim ond ar ôl i chi anfon {amt} at {name}. Yna byddwn yn dweud wrthynt ei fod wedi'i anfon."],
  apprBody: ["This records the {methods} refund and tells {name} it is on its way. It does not send any money: send {amt} {how} yourself, then press “I've sent the refund”.", "To zapisuje zwrot ({methods}) i informuje {name}, że jest w drodze. Nie wysyła pieniędzy: wyślij {amt} samodzielnie ({how}), a potem naciśnij „Wysłałem zwrot”.", "Aceasta înregistrează rambursarea ({methods}) și îi spune lui {name} că este pe drum. Nu trimite bani: trimite tu {amt} ({how}), apoi apasă „Am trimis rambursarea”.", "یہ ({methods}) واپسی درج کرتا ہے اور {name} کو بتاتا ہے کہ یہ راستے میں ہے۔ یہ رقم نہیں بھیجتا: {amt} خود بھیجیں ({how})، پھر «میں نے واپسی بھیج دی» دبائیں۔", "ਇਹ ({methods}) ਰਿਫੰਡ ਦਰਜ ਕਰਦਾ ਹੈ ਅਤੇ {name} ਨੂੰ ਦੱਸਦਾ ਹੈ ਕਿ ਇਹ ਰਾਹ ਵਿੱਚ ਹੈ। ਇਹ ਪੈਸੇ ਨਹੀਂ ਭੇਜਦਾ: {amt} ਆਪ ਭੇਜੋ ({how}), ਫਿਰ “ਮੈਂ ਰਿਫੰਡ ਭੇਜ ਦਿੱਤਾ” ਦਬਾਓ।", "এটি ({methods}) রিফান্ড নথিভুক্ত করে এবং {name}-কে জানায় যে এটি আসছে। এটি টাকা পাঠায় না: নিজে {amt} পাঠান ({how}), তারপর “রিফান্ড পাঠিয়েছি” চাপুন।", "يسجّل هذا الاسترداد ({methods}) ويخبر {name} بأنه في الطريق. لا يرسل أي مال: أرسل {amt} بنفسك ({how})، ثم اضغط «أرسلت الاسترداد».", "Isto regista o reembolso ({methods}) e avisa {name} de que está a caminho. Não envia dinheiro: envie {amt} você mesmo ({how}) e depois prima «Enviei o reembolso».", "Esto registra el reembolso ({methods}) y avisa a {name} de que va en camino. No envía dinero: envía {amt} tú mismo ({how}) y luego pulsa «He enviado el reembolso».", "Cela enregistre le remboursement ({methods}) et indique à {name} qu'il est en route. Aucun argent n'est envoyé : envoyez {amt} vous-même ({how}), puis appuyez sur « J'ai envoyé le remboursement ».", "Mae hyn yn cofnodi'r ad-daliad ({methods}) ac yn dweud wrth {name} ei fod ar ei ffordd. Nid yw'n anfon arian: anfonwch {amt} eich hun ({how}), yna pwyswch “Rwyf wedi anfon yr ad-daliad”."],
  sentChip: ["Refunded on {date} ({methods})", "Zwrócono {date} ({methods})", "Rambursat pe {date} ({methods})", "{date} کو واپس کیا گیا ({methods})", "{date} ਨੂੰ ਵਾਪਸ ਕੀਤਾ ({methods})", "{date} তারিখে ফেরত ({methods})", "تم الاسترداد في {date} ({methods})", "Reembolsado em {date} ({methods})", "Reembolsado el {date} ({methods})", "Remboursé le {date} ({methods})", "Ad-dalwyd ar {date} ({methods})"],
});
