import { PASTEL, list, num, type ToolItem } from "./kit";
import { ENGLISH } from "./english";

const peel = ENGLISH.find((i) => i.id === "e-peel")!;

export const HISTORY: ToolItem[] = [
  { id: "h-timeline", pack: "history", label: "Timeline", sub: "add events on a dated scale", levels: ["early", "standard", "advanced"], params: [{ k: "start", label: "From year", type: "number", def: 1000 }, { k: "end", label: "To year", type: "number", def: 2000 }, { k: "events", label: "Events (year|label; year|label)", type: "text", def: "1066|Battle of Hastings; 1215|Magna Carta; 1485|Battle of Bosworth; 1666|Great Fire of London" }],
    make: (b, c, v) => { b.stamp("timeline", -450, -130, 900, 260, { start: num(v.start, 1000), end: num(v.end, 2000), events: String(v.events) }); void c; } },
  { id: "h-source", pack: "history", label: "Source analysis frame", levels: ["standard", "advanced"], params: [{ k: "t", label: "Framework", type: "select", def: "OPCVL", options: ["OPCVL", "Provenance · Content · Context · Utility"] }], make: (b, c, v) => { const heads = v.t === "OPCVL" ? ["Origin", "Purpose", "Content", "Value", "Limitations"] : ["Provenance", "Content", "Context", "Utility"]; heads.forEach((h, i) => { b.cell(0, i * 122, 130, 110, { c: c.brand, w: 3, fill: PASTEL[i % PASTEL.length], text: h, size: 20, bold: true }); b.cell(130, i * 122, 560, 110, { c: c.brand, w: 3, ph: "Write here…", size: 22, al: "l", va: "t" }); }); } },
  { id: "h-cause", pack: "history", label: "Cause & consequence chain", levels: ["early", "standard", "advanced"], params: [{ k: "steps", label: "Boxes (comma separated)", type: "list", def: "Cause, Event, Consequence 1, Consequence 2" }], make: (b, c, v) => { list(v.steps, ["Cause"]).slice(0, 8).forEach((t, i, a) => { const x = i * 230; b.cell(x, 0, 190, 100, { c: c.brand, w: 3.5, fill: i === 0 ? "#fee2e2" : i === 1 ? "#fef9c3" : "#dcfce7", text: t, size: 21, bold: true }); if (i < a.length - 1) b.arrow(x + 194, 50, x + 226, 50, { w: 4 }); }); } },
  { id: "h-sig", pack: "history", label: "Significance ladder", levels: ["standard", "advanced"], make: (b, c) => { ["Changed lives of many people", "Lasted a long time", "Affected people in many places", "Changed how people thought", "Led to other important events"].forEach((t, i) => { const w = 260 + i * 70, y = (4 - i) * 76; b.cell(-w / 2, y, w, 64, { c: c.brand, w: 3, fill: PASTEL[i], text: t, size: 19, bold: true }); }); } },
  { id: "h-tree", pack: "history", label: "Family tree / hierarchy", levels: ["early", "standard", "advanced"], params: [{ k: "gens", label: "Generations", type: "number", def: 3 }], make: (b, c, v) => { const g = Math.max(2, Math.min(4, num(v.gens, 3))); for (let i = 0; i < g; i++) { const n = 2 ** i, gap = 640 / n; for (let j = 0; j < n; j++) { const x = -320 + gap * (j + 0.5), y = i * 130; b.cell(x - 70, y, 140, 60, { c: c.brand, w: 3, fill: PASTEL[i], ph: "Name", size: 20 }); if (i) b.line(x, y, -320 + (640 / (n / 2)) * (Math.floor(j / 2) + 0.5), (i - 1) * 130 + 60, { w: 2.5 }); } } } },
  { id: "h-peel", pack: "history", label: "PEEL paragraph (history)", levels: ["standard", "advanced"], params: [{ k: "t", label: "Style", type: "select", def: "PEEL (History)", options: ["PEE", "PEEL", "PEEL (History)"] }], make: peel.make },
  { id: "h-venn", pack: "history", label: "Compare (Venn)", make: (b) => { b.ellipse(-110, 0, 170, 150, { c: "#2f6bd8", w: 4 }); b.ellipse(110, 0, 170, 150, { c: "#e21d27", w: 4 }); b.tc(-190, -175, "Similarities", { size: 22, bold: true }); } },
  { id: "h-compare", pack: "history", label: "Similarity / difference grid", levels: ["standard", "advanced"], params: [{ k: "a", label: "A", type: "text", def: "Then" }, { k: "b", label: "B", type: "text", def: "Now" }], make: (b, c, v) => { b.table(0, 0, [240, 240, 240], [54, 100, 100, 100], { head: ["", String(v.a), String(v.b)], labels: ["Life", "Power", "Beliefs"], headFill: "#eaf0fc", size: 22 }); void c; } },
  { id: "h-map", pack: "history", label: "Map for movements (add arrows)", sub: "Then use the arrow tool to show migration, invasion, trade…", levels: ["early", "standard", "advanced"], make: (b) => { b.stamp("map", 0, 0, 760, 640, { region: "europe", grid: false, labels: true }); } },
];
