import { measureText } from "../model";
import { PASTEL, list, num, type ToolItem } from "./kit";

const PRON: Record<string, string[]> = {
  French: ["je", "tu", "il / elle / on", "nous", "vous", "ils / elles"],
  Spanish: ["yo", "tú", "él / ella / usted", "nosotros", "vosotros", "ellos / ellas / ustedes"],
  German: ["ich", "du", "er / sie / es", "wir", "ihr", "sie / Sie"],
  Italian: ["io", "tu", "lui / lei", "noi", "voi", "loro"],
  Portuguese: ["eu", "tu", "ele / ela", "nós", "vós", "eles / elas"],
  Latin: ["ego", "tu", "is / ea / id", "nos", "vos", "ei / eae / ea"],
  English: ["I", "you", "he / she / it", "we", "you (pl.)", "they"],
};

export const LANGUAGES: ToolItem[] = [
  { id: "l-conj", pack: "languages", label: "Verb conjugation table", sub: "pronouns filled in, forms left to write", levels: ["standard", "advanced", "early"], params: [{ k: "lang", label: "Language", type: "select", def: "French", options: Object.keys(PRON) }, { k: "verb", label: "Verb (heading)", type: "text", def: "parler (to speak)" }, { k: "tenses", label: "Tenses (comma separated)", type: "list", def: "Present" }],
    make: (b, c, v) => { const pr = PRON[String(v.lang)] ?? PRON.French!, tenses = list(v.tenses, ["Present"]).slice(0, 4); b.tc((230 + 260 * tenses.length) / 2, -50, String(v.verb), { size: 30, bold: true, c: c.brand }); b.table(0, 0, [230, ...tenses.map(() => 260)], [50, ...pr.map(() => 62)], { head: ["", ...tenses], labels: pr, headFill: "#eaf0fc", size: 23 }); } },
  { id: "l-vocab", pack: "languages", label: "Vocabulary grid", levels: ["early", "standard", "advanced"], params: [{ k: "rows", label: "Rows", type: "number", def: 8 }, { k: "head", label: "Column headings", type: "list", def: "Word, Translation, Sentence" }], make: (b, c, v) => { const h = list(v.head, ["Word", "Translation"]).slice(0, 5); b.table(0, 0, h.map((_, i) => (i === h.length - 1 && h.length > 2 ? 380 : 220)), [54, ...Array(Math.max(1, Math.min(16, num(v.rows, 8)))).fill(62)], { head: h, headFill: "#eaf0fc", size: 22 }); void c; } },
  { id: "l-flash", pack: "languages", label: "Flashcard tiles", sub: "word on the front, translation under", levels: ["early", "standard"], params: [{ k: "pairs", label: "Pairs (word = translation, comma separated)", type: "list", def: "chat = cat, chien = dog, maison = house, livre = book" }, { k: "back", label: "Under the word", type: "select", def: "Show the translation", options: ["Show the translation", "Leave blank to fill in"] }],
    make: (b, c, v) => { list(v.pairs, ["a = b"]).slice(0, 12).forEach((p, i) => { const [a, t] = p.split("=").map((s) => s.trim()); const x = (i % 4) * 200, y = Math.floor(i / 4) * 170; b.cell(x, y, 184, 78, { c: c.brand, w: 3, fill: PASTEL[i % PASTEL.length], text: a ?? "", size: 24, bold: true }); b.cell(x, y + 82, 184, 60, { c: c.ink, w: 2, dash: v.back !== "Show the translation" || !t, text: v.back === "Show the translation" && t ? t : undefined, ph: "Translation…", size: 22 }); }); } },
  { id: "l-dialogue", pack: "languages", label: "Dialogue frame", sub: "speech bubbles for a conversation", levels: ["early", "standard"], params: [{ k: "n", label: "Bubbles", type: "number", def: 4 }, { k: "a", label: "Speaker A", type: "text", def: "A" }, { k: "b", label: "Speaker B", type: "text", def: "B" }],
    make: (b, c, v) => { const n = Math.max(2, Math.min(8, num(v.n, 4))); for (let i = 0; i < n; i++) { const left = i % 2 === 0, y = i * 130; b.cell((left ? 0 : 200) - 230, y - 52, 460, 104, { shape: "ellipse", c: left ? c.brand : c.danger, w: 3.5, fill: "#ffffff", ph: "Type what they say…", size: 24 }); b.text(left ? -250 : -50, y - 88, String(left ? v.a : v.b), { size: 17, bold: true, c: left ? c.brand : c.danger }); } } },
  { id: "l-frame", pack: "languages", label: "Sentence frame", sub: "scaffolded sentence starters", levels: ["early", "standard"], params: [{ k: "s", label: "Frame (use ___ for gaps)", type: "text", def: "Je m'appelle ___ et j'ai ___ ans." }], make: (b, c, v) => { const parts = String(v.s).split("___"); let x = 0; parts.forEach((p, i) => { if (p) { b.text(x, 0, p, { size: 28 }); x += measureText(p, 28, false) + 14; } if (i < parts.length - 1) { b.line(x, 36, x + 130, 36, { w: 3 }); x += 146; } }); void c; } },
  { id: "l-article", pack: "languages", label: "Gender / article colour key", sub: "masculine · feminine · neuter", levels: ["standard", "advanced", "early"], params: [{ k: "lang", label: "Language", type: "select", def: "French", options: ["French", "Spanish", "German", "Italian"] }], make: (b, c, v) => { const K: Record<string, [string, string][]> = { French: [["le / un", "#cfe4ff"], ["la / une", "#ffd6e6"], ["les / des", "#e6dcff"]], Spanish: [["el / un", "#cfe4ff"], ["la / una", "#ffd6e6"], ["los / las", "#e6dcff"]], German: [["der / ein", "#cfe4ff"], ["die / eine", "#ffd6e6"], ["das / ein", "#c9f0d6"], ["die (pl.)", "#e6dcff"]], Italian: [["il / lo / un", "#cfe4ff"], ["la / una", "#ffd6e6"], ["i / gli / le", "#e6dcff"]] }; (K[String(v.lang)] ?? K.French!).forEach(([t, col], i) => { b.rect(0, i * 60, 50, 44, { c: c.ink, w: 2, fill: col }); b.text(66, i * 60 + 4, t, { size: 26, bold: true }); }); } },
  { id: "l-translate", pack: "languages", label: "Translation frame (two columns)", levels: ["early", "standard", "advanced"], params: [{ k: "l", label: "Left", type: "text", def: "Français" }, { k: "r", label: "Right", type: "text", def: "English" }], make: (b, c, v) => { b.table(0, 0, [360, 360], [56, 420], { head: [String(v.l), String(v.r)], headFill: "#eaf0fc", size: 26 }); void c; } },
  { id: "l-tianzige", pack: "languages", label: "Character practice (tián zì gé)", sub: "Chinese character grid", levels: ["early", "standard", "advanced"], bg: "tianzige" },
  { id: "l-genkou", pack: "languages", label: "Genkō yōshi (Japanese)", sub: "12 × 10 squares", levels: ["early", "standard", "advanced"], make: (b, c) => { for (let r = 0; r < 10; r++) for (let q = 0; q < 12; q++) b.cell(q * 62, r * 62, 62, 62, { c: "#b34a4a", w: 1.6, size: 38 }); void c; } },
  { id: "l-stroke", pack: "languages", label: "Stroke-order guide", sub: "big grid + numbered step boxes", levels: ["early", "standard"], params: [{ k: "n", label: "Steps", type: "number", def: 6 }], make: (b, c, v) => { const n = Math.max(2, Math.min(12, num(v.n, 6))); b.rect(0, 0, 300, 300, { c: c.ink, w: 3.5 }); b.line(150, 0, 150, 300, { w: 1.6, c: "#7d8aa3" }); b.line(0, 150, 300, 150, { w: 1.6, c: "#7d8aa3" }); b.line(0, 0, 300, 300, { w: 1.4, c: "#c3cde2" }); b.line(300, 0, 0, 300, { w: 1.4, c: "#c3cde2" }); for (let i = 0; i < n; i++) { const x = 340 + (i % 4) * 110, y = Math.floor(i / 4) * 110; b.cell(x, y, 96, 96, { c: c.brand, w: 2.5, size: 40 }); b.text(x + 6, y + 4, String(i + 1), { size: 18, bold: true, c: c.brand }); } } },
  { id: "l-2col", pack: "languages", label: "Two-column page", bg: "twocol" },
  { id: "l-vocab-page", pack: "languages", label: "Vocabulary grid page", sub: "Word · Meaning · Example, as the page background", tags: "frame vocab list", bg: "vocab" },
];
// Special-character palettes live in symbols.ts.
