import { PASTEL, list, num, type B, type Ctx, type ToolItem } from "./kit";
import { APPARATUS_KINDS, SYMBOL_KINDS } from "../render-stamps";

/** Numbered leader lines from a diagram to dashed answer boxes. */
const labels = (b: B, c: Ctx, targets: [number, number][], side: "l" | "r" | "auto" = "auto") => {
  targets.forEach(([tx, ty], i) => { const left = side === "l" || (side === "auto" && i % 2 === 0), bx = left ? -480 : 300, by = -230 + i * 68; b.line(left ? bx + 190 : bx, by + 22, tx, ty, { w: 2, c: "#7d8aa3" }); b.cell(bx, by, 190, 44, { c: c.brand, w: 2.5, dash: true, ph: "Label…", size: 20 }); b.text(bx + 6, by + 3, String(i + 1), { size: 15, bold: true, c: c.brand }); });
};

const cell = (plant: boolean) => (b: B, c: Ctx) => {
  if (plant) { b.rect(-240, -170, 480, 340, { c: "#15803d", w: 6, fill: "#f0fbf3" }); b.rect(-226, -156, 452, 312, { c: c.ink, w: 3, fill: null }); } else b.ellipse(0, 0, 250, 175, { c: c.ink, w: 5, fill: "#fdf3f3" });
  b.ellipse(-30, -10, 42, 42, { c: c.brand, w: 3.5, fill: "#dbeafe" }); b.ellipse(-30, -10, 14, 14, { c: c.brand, w: 2.5, fill: c.brand });
  b.ellipse(90, 60, 40, 22, { c: "#c2410c", w: 3, fill: "#ffedd5" }); b.ellipse(-120, 70, 34, 18, { c: "#c2410c", w: 3, fill: "#ffedd5" });
  if (plant) { b.ellipse(120, -70, 58, 40, { c: "#15803d", w: 3.5, fill: "#dcfce7" }); b.ellipse(-150, -70, 44, 90, { c: c.brand, w: 2.5, fill: "#eef6ff" }); }
  labels(b, c, plant ? [[-30, -10], [90, 60], [-120, 70], [120, -70], [-150, -70], [0, -168], [235, 0]] : [[-30, -10], [90, 60], [-120, 70], [0, -140], [230, 20]]);
};

export const SCIENCE: ToolItem[] = [
  // Biology
  { id: "s-animalcell", pack: "science", group: "Biology", label: "Animal cell (label me)", levels: ["standard", "advanced", "early"], make: cell(false) },
  { id: "s-plantcell", pack: "science", group: "Biology", label: "Plant cell (label me)", levels: ["standard", "advanced", "early"], make: cell(true) },
  { id: "s-body", pack: "science", group: "Biology", label: "Body outline to label", levels: ["early", "standard"], make: (b, c) => { b.ellipse(0, -190, 44, 50, { w: 4 }); b.path([[-46, -140], [-110, -120], [-150, 0], [-140, 90], [-120, 10], [-100, -70], [-72, -20], [-70, 120], [-60, 260], [-20, 262], [-8, 130], [8, 130], [20, 262], [60, 260], [70, 120], [72, -20], [100, -70], [120, 10], [140, 90], [150, 0], [110, -120], [46, -140]], { w: 4 }); labels(b, c, [[0, -190], [0, -90], [0, 20], [-60, 180], [100, 0]], "auto"); } },
  { id: "s-foodchain", pack: "science", group: "Biology", label: "Food chain builder", levels: ["early", "standard", "advanced"], params: [{ k: "c", label: "Organisms (comma separated)", type: "list", def: "grass, grasshopper, frog, snake, hawk" }], make: (b, c, v) => { list(v.c, ["producer"]).slice(0, 7).forEach((t, i, a) => { const x = i * 190; b.cell(x, 0, 150, 80, { c: c.brand, w: 3.5, fill: PASTEL[i % PASTEL.length], text: t, size: 21, bold: true }); if (i < a.length - 1) b.arrow(x + 154, 40, x + 186, 40, { w: 4, c: c.danger }); }); } },
  { id: "s-foodweb", pack: "science", group: "Biology", label: "Food web frame", levels: ["standard", "advanced"], make: (b, c) => { const pos: [number, number, string][] = [[-260, 180, "Producer"], [0, 180, "Producer"], [260, 180, "Producer"], [-130, 20, "Primary consumer"], [130, 20, "Primary consumer"], [0, -140, "Secondary consumer"]]; pos.forEach(([x, y, t], i) => { b.cell(x - 90, y - 34, 180, 68, { c: c.brand, w: 3, fill: PASTEL[i % PASTEL.length], text: t, size: 17, bold: true }); }); [[-260, 146, -150, 54], [0, 146, -110, 54], [0, 146, 110, 54], [260, 146, 150, 54], [-130, -14, -30, -106], [130, -14, 30, -106]].forEach(([a, bb, cc, d]) => b.arrow(a!, bb!, cc!, d!, { w: 3.5, c: c.danger })); } },
  { id: "s-punnett", pack: "science", group: "Biology", label: "Punnett square", levels: ["standard", "advanced"], params: [{ k: "p1", label: "Parent 1 alleles", type: "text", def: "Bb" }, { k: "p2", label: "Parent 2 alleles", type: "text", def: "Bb" }, { k: "fill", label: "Fill in the offspring", type: "select", def: "No", options: ["No", "Yes"] }], make: (b, c, v) => { const p1 = String(v.p1).trim().slice(0, 2).split("").filter(Boolean), p2 = String(v.p2).trim().slice(0, 2).split("").filter(Boolean); if (!p1.length) p1.push("?"); if (!p2.length) p2.push("?");
      b.cell(0, 0, 90, 90, { c: c.ink, w: 3, ns: true }); p1.forEach((a, i) => b.cell(90 + i * 150, 0, 150, 90, { c: c.ink, w: 3, text: a, size: 40, bold: true, tc: c.brand })); p2.forEach((a, j) => b.cell(0, 90 + j * 150, 90, 150, { c: c.ink, w: 3, text: a, size: 40, bold: true, tc: c.danger }));
      p2.forEach((r, ri) => p1.forEach((cc, ci) => b.cell(90 + ci * 150, 90 + ri * 150, 150, 150, { c: c.ink, w: 3, size: 38, bold: true, text: v.fill === "Yes" ? [cc, r].sort((x, y) => (x < y ? -1 : 1)).join("") : undefined }))); } },
  { id: "s-lifecycle", pack: "science", group: "Biology", label: "Life-cycle wheel", levels: ["early", "standard"], params: [{ k: "s", label: "Stages (comma separated)", type: "list", def: "egg, caterpillar, chrysalis, butterfly" }], make: (b, c, v) => { const st = list(v.s, ["stage"]).slice(0, 8); st.forEach((t, i) => { const a = -Math.PI / 2 + (i / st.length) * Math.PI * 2, a2 = -Math.PI / 2 + ((i + 0.5) / st.length) * Math.PI * 2, x = Math.cos(a) * 200, y = Math.sin(a) * 160; b.ellipse(x, y, 84, 44, { c: c.brand, w: 3.5, fill: PASTEL[i % PASTEL.length] }); b.tc(x, y, t, { size: 19, bold: true }); b.arrow(Math.cos(a2 - 0.16) * 200, Math.sin(a2 - 0.16) * 160, Math.cos(a2 + 0.06) * 200, Math.sin(a2 + 0.06) * 160, { w: 4, c: c.danger }); }); } },
  // Chemistry
  { id: "s-periodic", pack: "science", group: "Chemistry", label: "Periodic table", sub: "tap an element to highlight it", levels: ["standard", "advanced", "early"], make: (b) => { b.stamp("periodic", -560, -320, 1120, 640, { sel: "", colour: 1 }); } },
  { id: "s-particles", pack: "science", group: "Chemistry", label: "Particle diagrams (solid · liquid · gas)", levels: ["early", "standard", "advanced"], make: (b, c) => { ["Solid", "Liquid", "Gas"].forEach((t, i) => { const x = i * 300; b.rect(x, 0, 260, 260, { c: c.ink, w: 3.5 }); b.tc(x + 130, -26, t, { size: 26, bold: true }); if (i === 0) for (let r = 0; r < 5; r++) for (let q = 0; q < 5; q++) b.ellipse(x + 30 + q * 50, 30 + r * 50, 18, 18, { c: c.brand, w: 3, fill: "#dbeafe" }); if (i === 1) for (let r = 0; r < 5; r++) for (let q = 0; q < 5; q++) b.ellipse(x + 34 + q * 48 + ((r * 7 + q * 3) % 5) * 3, 90 + r * 32 + ((q * 5) % 3) * 4, 18, 18, { c: c.brand, w: 3, fill: "#dbeafe" }); if (i === 2) [[40, 50], [180, 30], [90, 120], [210, 170], [50, 210], [140, 220], [220, 90], [120, 60]].forEach(([px, py]) => b.ellipse(x + px!, py!, 18, 18, { c: c.brand, w: 3, fill: "#dbeafe" })); }); } },
  { id: "s-bohr", pack: "science", group: "Chemistry", label: "Atom (Bohr model)", sub: "type the shells, e.g. 2,8,1", levels: ["standard", "advanced"], params: [{ k: "sym", label: "Symbol", type: "text", def: "Na" }, { k: "shells", label: "Electrons per shell", type: "text", def: "2,8,1" }], make: (b, c, v) => { b.stamp("bohr", -170, -170, 340, 340, { shells: String(v.shells), symbol: String(v.sym) }); void c; } },
  { id: "s-equation", pack: "science", group: "Chemistry", label: "Equation balancing frame", levels: ["standard", "advanced"], params: [{ k: "eq", label: "Equation (use → or ->)", type: "text", def: "H₂ + O₂ → H₂O" }], make: (b, c, v) => { const [l, r] = String(v.eq).split(/→|->|=/).map((s) => s.trim()); const box = (x: number, t: string) => { b.cell(x, 0, 64, 64, { c: c.brand, w: 3, dash: true, size: 34, bold: true }); b.text(x + 76, 10, t, { size: 34, bold: true }); return x + 76 + t.length * 20 + 24; }; let x = 0; (l ?? "").split("+").map((s) => s.trim()).forEach((t, i) => { if (i) { b.text(x, 10, "+", { size: 34, bold: true }); x += 50; } x = box(x, t); }); b.arrow(x, 32, x + 90, 32, { w: 5 }); x += 120; (r ?? "").split("+").map((s) => s.trim()).forEach((t, i) => { if (i) { b.text(x, 10, "+", { size: 34, bold: true }); x += 50; } x = box(x, t); }); } },
  { id: "s-apparatus", pack: "science", group: "Chemistry", label: "Lab apparatus", sub: "beaker, flask, test tube, Bunsen…", levels: ["early", "standard", "advanced"], params: [{ k: "kind", label: "Apparatus", type: "select", def: "beaker", options: [...APPARATUS_KINDS] }], make: (b, c, v) => { b.stamp("apparatus", -65, -85, 130, 170, { kind: String(v.kind) }); void c; } },
  { id: "s-apparatus-all", pack: "science", group: "Chemistry", label: "Apparatus set (all)", levels: ["standard", "advanced"], make: (b) => { APPARATUS_KINDS.forEach((k, i) => b.stamp("apparatus", (i % 4) * 170, Math.floor(i / 4) * 220, 130, 170, { kind: k })); } },
  { id: "s-dotcross", pack: "science", group: "Chemistry", label: "Dot-and-cross bonding frame", levels: ["advanced", "standard"], make: (b, c) => { b.ellipse(-90, 0, 130, 130, { c: c.brand, w: 4 }); b.ellipse(90, 0, 130, 130, { c: c.danger, w: 4 }); b.tc(-150, 0, "Atom 1", { size: 20, bold: true, c: c.brand }); b.tc(150, 0, "Atom 2", { size: 20, bold: true, c: c.danger }); b.tc(0, 165, "Show the shared pair(s) where the circles overlap", { size: 17 }); } },
  // Physics
  { id: "s-circuit", pack: "science", group: "Physics", label: "Circuit symbol", sub: "cell, lamp, switch, resistor, meters…", levels: ["early", "standard", "advanced"], params: [{ k: "kind", label: "Symbol", type: "select", def: "cell", options: [...SYMBOL_KINDS] }], make: (b, c, v) => { b.stamp("symbol", -75, -45, 150, 90, { kind: String(v.kind) }); void c; } },
  { id: "s-circuit-set", pack: "science", group: "Physics", label: "Circuit symbols kit (all)", sub: "then join them with the line tool", levels: ["standard", "advanced"], make: (b) => { SYMBOL_KINDS.forEach((k, i) => b.stamp("symbol", (i % 4) * 170, Math.floor(i / 4) * 110, 150, 90, { kind: k })); } },
  { id: "s-forces", pack: "science", group: "Physics", label: "Force arrows", params: [{ k: "n", label: "Forces (comma separated: up, down, left, right)", type: "list", def: "up, down, left, right" }, { k: "l", label: "Labels (same order)", type: "list", def: "Reaction, Weight, Thrust, Drag" }], make: (b, c, v) => { b.rect(-70, -45, 140, 90, { c: c.ink, w: 4, fill: "#f1f5f9" }); const d: Record<string, [number, number]> = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] }, lab = list(v.l); list(v.n, ["up"]).slice(0, 4).forEach((k, i) => { const [dx, dy] = d[k] ?? [0, -1]; b.arrow(dx * 70, dy * 45, dx * 200, dy * 150, { w: 6, c: i % 2 ? c.danger : c.brand }); b.tc(dx * 200, dy * 150 + (dy ? dy * 26 : -26), lab[i] ?? k, { size: 20, bold: true }); }); } },
  { id: "s-ray", pack: "science", group: "Physics", label: "Lens ray diagram", sub: "change f and object distance to see the image move", levels: ["standard", "advanced"], params: [{ k: "type", label: "Lens", type: "select", def: "convex", options: ["convex", "concave"] }, { k: "f", label: "Focal length", type: "number", def: 140 }, { k: "obj", label: "Object distance", type: "number", def: 260 }], make: (b, c, v) => { b.stamp("lens", -380, -190, 760, 380, { type: String(v.type), f: num(v.f, 140), obj: num(v.obj, 260) }); void c; } },
  { id: "s-wave", pack: "science", group: "Physics", label: "Wave frame", sub: "wavelength & amplitude", levels: ["standard", "advanced"], make: (b, c) => { const p: [number, number][] = []; for (let x = 0; x <= 640; x += 8) p.push([x, Math.sin((x / 640) * Math.PI * 4) * 90]); b.line(-20, 0, 660, 0, { w: 2, c: "#7d8aa3" }); b.path(p, { w: 5, c: c.brand }); b.arrow(160, 0, 160, -90, { w: 3, c: c.danger }); b.tc(230, -50, "amplitude", { size: 18, bold: true, c: c.danger }); b.line(0, 130, 320, 130, { w: 3 }); b.tc(160, 155, "wavelength", { size: 18, bold: true }); } },
  { id: "s-sankey", pack: "science", group: "Physics", label: "Energy transfer (Sankey) frame", levels: ["standard", "advanced"], make: (b, c) => { b.polygon([[0, -60], [260, -60], [260, -18], [420, -18], [420, 18], [260, 18], [260, 60], [0, 60]], { w: 3.5, c: c.brand }); b.polygon([[260, -60], [420, -110], [420, -60], [300, -60]], { w: 3.5, c: c.danger }); b.tc(-60, 0, "Input\nenergy", { size: 20, bold: true }); b.tc(490, 0, "Useful\noutput", { size: 20, bold: true, c: c.brand }); b.tc(490, -100, "Wasted", { size: 20, bold: true, c: c.danger }); } },
  { id: "s-results", pack: "science", group: "Physics", label: "Results table", levels: ["early", "standard", "advanced"], params: [{ k: "cols", label: "Headings (comma separated)", type: "list", def: "Trial, Result 1, Result 2, Result 3, Mean" }, { k: "rows", label: "Rows", type: "number", def: 5 }], make: (b, c, v) => { const h = list(v.cols, ["Trial"]).slice(0, 7); b.table(0, 0, h.map(() => 140), [54, ...Array(Math.min(12, num(v.rows, 5))).fill(54)], { head: h, headFill: "#eaf0fc", size: 20 }); void c; } },
  { id: "s-graph", pack: "science", group: "Physics", label: "Graph paper", bg: "squared" },
  // Frames (page backgrounds)
  { id: "s-diagram", pack: "science", group: "Frames", label: "Diagram frame page", sub: "a title line, a drawing area and eight numbered label boxes, as the page background", tags: "frame label", bg: "diagram" },
  { id: "s-squared", pack: "science", group: "Frames", label: "Squared page", bg: "squared" },
];
