// Residue pass after the 15 Sept website work. Two groups:
//   A "unreachable": a website we could never read (confirmed site flagged websiteDown, or a candidate dropped as "site unreachable").
//   B "homepage-only": a confirmed site where only the homepage could be read, so bookingChecked was never set.
// What it does, per lead (CONC 6, resumable via scripts/leads/out/residue.out.jsonl):
//   A: try the obvious URL alternates (www/non-www, http/https, .co.uk/.com/.org/.uk, trailing slash); if still nothing, ONE Brave search
//      "<name>" <town> and accept a result only when its host carries the name (find_websites.mjs rule). A live site that passes the
//      verify_sites judge is appended to verify.out.jsonl as a CANDIDATE row so apply_verify.mjs confirms it. Facebook/Instagram only → socialUrl.
//      Nothing at all → websiteDead + websiteDeadAt (fill-only) so the Leads page can stop showing a dead link.
//      Brave credit note: if there's no API credit (402), the search is SKIPPED, not treated as a no-result — such a lead is never marked
//      dead. It's written as result "unresolved-needs-search" and applied as verifyPending + verifyPendingWhy (fill-only) so it can be
//      filtered to for a human / a future run with --allow-brave once credit is topped up.
//   B: re-read the homepage plus guessed subpages (/book /booking /classes /camps /timetable /prices /contact + sitemap.xml) and run the
//      same booking recogniser as verify_sites.mjs; append a CONFIRMED row so apply_verify fills bookingSystem/bookingUrl or bookingChecked.
//      A lead with neither email nor phone also gets the find_contacts.mjs scrape (row appended to contacts.out.jsonl → find_contacts --apply).
// Usage (from server/):
//   node scripts/leads/residue.mjs                 # counts only
//   node scripts/leads/residue.mjs --run [--limit N] [--group A|B]
//   node scripts/leads/apply_verify.mjs scripts/leads/out/verify.out.jsonl && node scripts/leads/find_contacts.mjs --apply
//   node scripts/leads/residue.mjs --apply         # socialUrl / websiteDead / keep-candidates / clear websiteDown on recovered sites
import "dotenv/config"; import admin from "firebase-admin"; import fs from "fs"; import path from "path";
admin.initializeApp({ credential: admin.credential.cert(JSON.parse(fs.readFileSync("./serviceAccountKey.json","utf8"))) });
const db = admin.firestore();
const args = Object.fromEntries(process.argv.slice(2).map((a,i,arr)=>a.startsWith("--")?[a.slice(2),arr[i+1]&&!arr[i+1].startsWith("--")?arr[i+1]:true]:[]).filter(x=>x.length));
const LIMIT = args.limit ? +args.limit : Infinity, GROUP = args.group ? String(args.group).toUpperCase() : "AB";
const OUT = path.resolve("scripts/leads/out/residue.out.jsonl"), VERIFY = path.resolve("scripts/leads/out/verify.out.jsonl"), CONTACTS = path.resolve("scripts/leads/out/contacts.out.jsonl");
const CONC = 6, TIMEOUT = 10000, MAXBYTES = 1_500_000, BRAVE_BUDGET = args.budget ? +args.budget : 3000, GAP_MS = 350;
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";
const API_KEY = process.env.BRAVE_SEARCH_API_KEY || "";

// ---------- copied from verify_sites.mjs (kept identical so verdicts match what apply_verify expects) ----------
const CHILD = ["nursery","nurseries","pre-school","preschool","childcare","child care","children","kids","holiday club","holiday camp","after school","after-school","breakfast club","wraparound","wrap around","ofsted","early years","eyfs","toddler","baby","babies","playgroup","childminder","childminding","forest school","summer camp","multi-sport","multi sport","football coaching","gymnastics","swimming lessons","dance school","dance classes","drama","tuition","tutoring","tutor","stay and play","soft play","party","parties","activities for children","kids club","youth","scouts","cubs","beavers","brownies","guides","kindergarten","day care","daycare","montessori","reception","key stage","ks1","ks2","under 5","under-5","ages 4","ages 5","aged 4","aged 5","years old","school holidays","term time","term-time","half term","clubs for kids","sports coaching","coaching for children","little","junior","juniors","mini","minis","tots","play"];
const OTHER = ["estate agent","letting agent","solicitor","solicitors","accountant","accountants","plumber","plumbing","electrician","roofing","builders","scaffolding","car wash","garage services","mot centre","tyres","dentist","dental practice","opticians","pharmacy","funeral","casino","betting","bookmaker","vape","tattoo","barber","hair salon","beauty salon","nail bar","restaurant","takeaway","public house","bar and grill","hotel rooms","b&b","holiday cottages","caravan park","gym membership","personal trainer","crossfit","bodybuilding","car sales","used cars","van hire","removals","storage units","recruitment agency","it support","web design","seo agency","marketing agency","insurance broker","mortgage","loans","crypto","forex","escort","adult only","dating","cbd","kitchens","bathrooms","flooring","carpets","windows and doors","double glazing","landscaping","tree surgeon","pest control","cleaning services","skip hire","wedding venue","conference centre","office space","coworking","church services","funeral directors","vets","veterinary","dog grooming","kennels","cattery"];
const PARKED = ["domain is for sale","this domain is for sale","buy this domain","domain may be for sale","parked domain","this domain has expired","domain expired","sedo","hugedomains","dan.com","afternic","godaddy.com/domainsearch","namecheap.com/domains","this web page is parked","website is parked","site not found","account suspended","this site can’t be reached","under construction","default web page","welcome to nginx","apache2 debian default","it works!","index of /","plesk","cpanel","wix.com/website-template","site is temporarily unavailable","this website is currently unavailable","website expired","domain not configured","squarespace: claim","this site is not yet published","this store is currently unavailable","shop coming soon"];
const STOP = new Set(["the","and","ltd","limited","cic","llp","plc","of","at","in","for","a","an","club","clubs","school","schools","nursery","nurseries","preschool","pre","childcare","children","kids","day","care","centre","center","group","community","academy","holiday","camp","camps","sports","sport","activities","activity","little","co","uk","com","org","org.uk","co.uk","trust","foundation","cio","charity","services","service","st","st.","primary","first","new"]);
const strip = (h) => h.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<!--[\s\S]*?-->/g," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/&#39;|&apos;/g,"'").replace(/\s+/g," ").toLowerCase();
const tokens = (s) => (s||"").toLowerCase().replace(/[’']/g,"").split(/[^a-z0-9]+/).filter(t=>t.length>=3 && !STOP.has(t));
const squash = (s) => (s||"").toLowerCase().replace(/[^a-z0-9]/g,"");
const locBits = (loc) => { const out=[]; for (const part of String(loc||"").split(/[·,|\/]/)) { const p=part.trim().toLowerCase(); if(!p) continue; const pc=p.match(/\b([a-z]{1,2}\d[a-z\d]?)\s*(\d[a-z]{2})?\b/); if(pc){ out.push(pc[1]); if(pc[2]) out.push(pc[1]+" "+pc[2]); continue; } if(/^\d+ sites?$/.test(p)) continue; if(p.length>=4 && !/^(uk|england|wales|scotland|london borough)$/.test(p)) out.push(p); } return [...new Set(out)]; };
const RX = new Map(); const rx = (t) => { if(!RX.has(t)) RX.set(t, new RegExp("(^|[^a-z])"+t.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"(s|es|'s)?([^a-z]|$)","i")); return RX.get(t); };
const count = (text, list) => list.filter(t => rx(t).test(text));
async function fetchSite(url, _noRetry = false) {
  const ctrl = new AbortController(); const t = setTimeout(()=>ctrl.abort(), TIMEOUT);
  try {
    const res = await fetch(url, { redirect:"follow", signal: ctrl.signal, headers: { "user-agent": UA, "accept":"text/html,*/*;q=0.8", "accept-language":"en-GB,en;q=0.9" } });
    const final = res.url || url; if (res.status >= 400) return { status: res.status, final, html: "" };
    const reader = res.body?.getReader(); let got = 0, chunks = [];
    if (reader) { while (got < MAXBYTES) { const { done, value } = await reader.read(); if (done) break; chunks.push(value); got += value.length; } try { reader.cancel(); } catch {} }
    return { status: res.status, final, html: Buffer.concat(chunks).toString("utf8") };
  } catch (e) { const err = String(e?.cause?.code || e?.name || e).slice(0,60);
    if (!_noRetry && /SSL|TLS|CERT|ALTNAME|ISSUER|LEAF/i.test(err) && /^https:/i.test(url)) return fetchSite(url.replace(/^https:/i, "http:"), true);
    return { status: 0, final: url, html: "", err }; }
  finally { clearTimeout(t); }
}
async function contactPage(html, base) { const m = [...html.matchAll(/href=["']([^"']*(contact|about|find-us|findus|location|where)[^"']*)["']/gi)].map(x=>x[1]).filter(h=>!/^(mailto|tel|javascript|#)/i.test(h)); for (const h of m.slice(0,2)) { try { const u = new URL(h, base).href; if (new URL(u).hostname !== new URL(base).hostname) continue; const r = await fetchSite(u); if (r.status===200 && r.html) return strip(r.html)+" "+r.html.toLowerCase(); } catch {} } return ""; }
const BOOKING_SYSTEMS = [["ClassForKids", /classforkids\.io/i], ["Bookwhen", /bookwhen\.com/i], ["eequ", /eequ\.org/i], ["Pebble", /(bookpebble\.co\.uk|pebble\.co\b)/i], ["Playwaze", /playwaze\.com/i], ["ClubSpark", /clubspark\.(net|lta\.org\.uk)/i], ["Coordinate", /coordinate\.cloud/i], ["HolidayActivities", /holidayactivities\.com/i], ["Yellow Days", /yellowdays/i], ["Hoop", /hoop\.co\.uk/i], ["Kidzcamp", /kidzcamp/i], ["iPAL", /ipal\.(co\.uk|app)/i], ["Magicbooking", /magicbooking/i], ["Famly", /famly\.co/i], ["Kinderly", /kinderly/i], ["Blossom", /blossomeducational/i], ["Connect Childcare", /connectchildcare/i], ["Nursery in a Box", /nurseryinabox/i], ["ParentPay", /parentpay\.com/i], ["SchoolsBuddy", /schoolsbuddy/i], ["Arbor", /arbor-education|arbor\.sc/i], ["Gymcatch", /gymcatch\.com/i], ["TeamUp", /goteamup\.com/i], ["Glofox", /glofox\.com/i], ["Mindbody", /mindbodyonline/i], ["Acuity", /acuityscheduling/i], ["Calendly", /calendly\.com/i], ["Eventbrite", /eventbrite/i], ["TicketSource", /ticketsource/i], ["TryBooking", /trybooking/i], ["Stripe checkout", /(buy\.stripe\.com|checkout\.stripe\.com)/i], ["Shopify", /myshopify\.com/i], ["Sumup", /sumup\.(com|io)/i], ["Square", /square\.site|squareup\.com/i], ["Wix Bookings", /wix\.com\/bookings|wixbookings/i], ["LoveAdmin", /loveadmin/i], ["Pitchero", /pitchero\.com/i], ["Spond", /spond\.com/i], ["Sportsuite", /sportsuite/i], ["Kids Club HQ", /kidsclubhq/i], ["Class4Kids", /class4kids/i], ["Nursery Story", /nurserystory/i], ["Tapestry", /tapestryjournal/i], ["Baby's Days", /babysdays/i]];
const MORE_SYSTEMS = [["Legend (leisure)", /legendonlineservices|legend\.co\.uk\/booking/i], ["Gladstone (leisure)", /gladstonemrm|gladstonesoftware|\.gladstone/i], ["XN Leisure", /xnleisure|xn-leisure/i], ["Better/GLL", /better\.org\.uk\/.*book|gll\.org/i], ["Everyone Active", /everyoneactive\.com\/.*book/i], ["NatWest PayIt", /natwestpayit/i], ["PayPal", /paypal\.(com|me)\/(paypalme|cgi-bin|checkout|ncp|donate)/i], ["GoCardless", /pay\.gocardless\.com/i], ["Zettle", /zettle\.com|izettle/i], ["Ticketsolve", /ticketsolve/i], ["Spektrix", /spektrix/i], ["Ticketmaster", /ticketmaster/i], ["See Tickets", /seetickets/i], ["Skiddle", /skiddle/i], ["Little Box Office", /littleboxoffice/i], ["Ticket Tailor", /tickettailor/i], ["WooCommerce cart", /\?add-to-cart=|\/cart\/?$|\/checkout\/?$/i], ["Squarespace commerce", /\/shop\?categoryId=|\/checkout\/order/i], ["Momence", /momence\.com/i], ["ClassPass", /classpass\.com/i], ["Sport:80", /sport80\.com/i], ["Pitchbooking", /pitchbooking/i], ["Playfinder", /playfinder\.com/i], ["LTA ClubSpark", /clubspark/i], ["Kidzcamp", /kidzcamp/i], ["Camp America style: Ultra Camp", /ultracamp/i], ["Sawyer", /hisawyer\.com/i], ["Jotform pay", /form\.jotform\.com/i], ["Typeform", /typeform\.com\/to/i], ["Google Forms", /docs\.google\.com\/forms|forms\.gle/i]];
const ALL_SYSTEMS = [...BOOKING_SYSTEMS, ...MORE_SYSTEMS];
const BOOKISH_PATH = /\/(book|booking|bookings|book-now|book-online|book-a-place|enrol|enroll|enrolment|register|registration|sign-?up|join|shop|store|prices?|pricing|fees|timetable|schedule|sessions?|classes|clubs?|camps?|holiday-?clubs?|holiday-?camps?|holidays|after-?school|breakfast|wraparound|courses?|workshops?|parties|membership|pay|payments?|checkout|basket|cart|tickets?|whats-on|events?)(\/|\.|\?|-|$)/i;
const bookText = (html) => { const t = html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").toLowerCase(); return { bookNow: (t.match(/\bbook (now|online|here|a place|your (place|child|space)|today)\b|\bbooking form\b|\bonline booking\b|\breserve (a|your) (place|spot)\b/g) || []).length, cart: (t.match(/add to (basket|cart)|checkout|your basket|shopping cart/g) || []).length, prices: (t.match(/£\s?\d/g) || []).length }; };
function systemIn(html) { const hrefs = [...html.matchAll(/(?:href|action|src|data-href|data-url)=["']([^"']+)["']/gi)].map(m=>m[1]); for (const h of hrefs) { const sys = ALL_SYSTEMS.find(([, re]) => re.test(h)); if (sys && !/facebook|instagram/i.test(h)) return { system: sys[0], url: h.slice(0, 300) }; } const inline = ALL_SYSTEMS.find(([, re]) => re.test(html.slice(0, 400000))); return inline && !/Google Forms|Typeform|Jotform/.test(inline[0]) ? { system: inline[0], url: null } : null; }
// Residue twist: the guessed subpages (and sitemap.xml bookish entries) are read AFTER the link-derived ones, up to 6 extra pages in all.
const GUESS = ["/book", "/booking", "/bookings", "/book-now", "/classes", "/camps", "/holiday-club", "/timetable", "/prices", "/contact"];
async function sitemapLinks(base) { try { const o = new URL(base).origin; const r = await fetchSite(o + "/sitemap.xml"); if (r.status !== 200 || !/<loc>/i.test(r.html)) return []; return [...r.html.matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/gi)].map(m=>m[1]).filter(u => { try { const x = new URL(u); return x.origin === o && BOOKISH_PATH.test(x.pathname); } catch { return false; } }).slice(0, 6); } catch { return []; } }
async function bookingScan(html, base, guess = false) {
  let pagesRead = 1; const extra = []; const found = systemIn(html); if (found) return { ...found, page: base, pagesRead, extraText: "" };
  let sub = []; const seen = new Set(); try { const origin = new URL(base); for (const m of html.matchAll(/href=["']([^"'#]+)["']/gi)) { let u; try { u = new URL(m[1], base); } catch { continue; } if (u.hostname.replace(/^www\./,"") !== origin.hostname.replace(/^www\./,"")) continue; if (!BOOKISH_PATH.test(u.pathname + u.search) || seen.has(u.pathname)) continue; seen.add(u.pathname); sub.push(u.href); } } catch {}
  sub.sort((a, b) => (/book|enrol|shop|pay|checkout|basket|cart|ticket/i.test(b) ? 1 : 0) - (/book|enrol|shop|pay|checkout|basket|cart|ticket/i.test(a) ? 1 : 0));
  let list = sub.slice(0, 4); let guessedTried = 0;
  if (guess) { const extraUrls = []; try { const o = new URL(base).origin; for (const p of GUESS) if (!seen.has(p) && !seen.has(p + "/")) extraUrls.push(o + p); } catch {} for (const u of await sitemapLinks(base)) { try { const p = new URL(u).pathname; if (!seen.has(p)) { seen.add(p); extraUrls.unshift(u); } } catch {} } list = [...list, ...extraUrls].slice(0, 4 + 6); guessedTried = extraUrls.length; }
  const own = []; const t0 = bookText(html); if (t0.bookNow >= 2 || t0.cart >= 1) own.push({ page: base, ...t0 });
  for (const u of list) { const r = await fetchSite(u); if (r.status !== 200 || !r.html) continue; pagesRead++; extra.push(strip(r.html).slice(0, 60000)); const f = systemIn(r.html); if (f) return { ...f, page: u, pagesRead, extraText: extra.join(" ") }; const t = bookText(r.html); if (t.bookNow >= 1 || t.cart >= 1 || (t.prices >= 3 && /book|shop|price|fee|camp|club|class/i.test(u))) own.push({ page: u, ...t }); }
  if (own.length) { const best = own.sort((a, b) => (b.cart * 3 + b.bookNow * 2 + b.prices) - (a.cart * 3 + a.bookNow * 2 + a.prices))[0]; return { system: best.cart ? "own site (online checkout)" : "own site (booking page)", url: best.page, page: best.page, pagesRead, evidence: `book-now×${best.bookNow} cart×${best.cart} prices×${best.prices}`, extraText: extra.join(" ") }; }
  return { system: null, pagesRead, subpages: sub.length, guessedTried, extraText: extra.join(" ") };
}
const ACT = [["multi", /multi[- ]?(activity|sport) (camp|club|day|holiday)|activity (camp|club|days?)\b|holiday (camp|club) activities/gi], ["sport", /(football|soccer|rugby|cricket|tennis|netball|hockey|basketball|badminton|athletics|golf) (camp|club|coaching|sessions?|classes?|lessons?|academy|school)|sports? (camp|club|coaching|sessions?)|multi[- ]?sports?/gi], ["gym", /gymnastics? (club|class|camp|sessions?)|trampolin(e|ing) (club|park|class|sessions?)|cheerleading (club|class|squad)|parkour (class|sessions?)/gi], ["swim", /swimming (lessons?|club|classes?|school)|learn to swim|aqua (tots|babies)|kayaking|paddle ?boarding/gi], ["martial", /(karate|judo|taekwondo|kickboxing|jiu[- ]?jitsu|kung fu|martial arts|boxing|fencing) (club|class|classes|lessons?|sessions?|academy|school)/gi], ["dance", /dance (class|classes|school|academy|club|lessons?|camp|sessions?)|ballet (class|classes|school|lessons?)|street ?dance/gi], ["drama", /drama (club|class|classes|school|camp|group|workshops?|sessions?|academy)|theatre (school|club|camp|group|academy|workshops?)|performing arts (school|academy|class|classes|club|camp)|stage school|youth theatre|musical theatre (class|school|club)/gi], ["music", /music (class|classes|lessons?|club|school|camp|sessions?)|(piano|guitar|drum|violin|ukulele|singing) (lessons?|classes?|club|tuition)|choir/gi], ["arts", /arts? (and|&) crafts?|craft (club|class|sessions?|workshops?)|art (club|class|classes|camp|sessions?|workshops?)|pottery (class|classes|sessions?)|messy play/gi], ["forest", /forest school|bushcraft|outdoor (learning|adventure|club|sessions?)|nature (club|school|explorers)|woodland (sessions?|club|adventures?)/gi], ["stem", /coding (club|class|classes|camp|lessons?|workshops?)|robotics (club|class|camp)|\blego (club|class|camp|robotics)|\bstem (club|class|camp|workshops?|sessions?)|science (club|camp|workshops?)/gi], ["language", /(french|spanish|german|mandarin|italian) (club|class|classes|lessons?|for (kids|children))|language (club|classes|lessons?) for (kids|children)/gi], ["tuition", /\btuition\b|\btutor(s|ing)?\b|11 ?plus|11\+|gcse|exam (prep|preparation)|homework club/gi], ["baby", /baby (class|classes|sensory|massage|yoga|music|signing|swimming)|toddler (class|classes|group|club|sessions?)|sensory (class|classes|play|sessions?)/gi], ["cook", /cookery (class|classes|club|school|camp|sessions?)|cooking (class|classes|club|camp|workshops?)|baking (class|classes|club)/gi], ["animals", /horse riding|pony (rides?|club|camp)|riding (lessons?|school|club)|farm (club|school|visits?)|animal (encounters?|club)/gi], ["send", /\bsend (club|clubs|provision|holiday|sessions?|friendly|specialist|specific|only)\b|(autism|asd)[- ]friendly (club|sessions?|holiday|camp)|(inclusive|specialist) (holiday|play|activity) (club|scheme|sessions?)|short breaks?/gi], ["youth", /youth (club|centre|work|group|project)|scout (group|troop)|brownies|\bcubs\b|adventure playground/gi]];
const TYPES = [["holiday", /holiday (club|clubs|camp|camps|care|scheme|programme)|play ?scheme|half[- ]term (club|camp|activities)|summer (camp|club|school|holiday club)|easter (camp|club|holiday club)/gi], ["wraparound", /after[- ]?school (club|clubs|care|provision)|breakfast club|wrap ?around (care|club|provision)|before (and|&) after school/gi], ["nursery", /day nursery|\bnursery\b(?! rhymes| school year)|early years (setting|provision|care)/gi], ["preschool", /pre[- ]?school\b|playgroup/gi], ["tuition", /\btuition\b|\btutor(s|ing)?\b|tuition centre|learning centre/gi], ["activity", /(weekly|term[- ]time|after[- ]school|saturday|weekend) (class|classes|club|clubs|sessions?)|classes for (kids|children|babies|toddlers)|kids'? (classes|clubs)|children'?s (classes|clubs)/gi]];
const cnt = (t, re) => (t.match(re) || []).length;
function signals(text, html) { const t = text.toLowerCase();
  const haf = cnt(t, /\bhaf\b|holiday activit(y|ies) (and|&) food|holiday activities (and|&) food programme|free school meals?|fsm[- ]eligible|funded (holiday )?places?/g);
  const prices = cnt(t, /£\s?\d/g) + cnt(t, /per (day|session|week|child|hour)/g) + cnt(html, /book(-| )?now|add to (basket|cart)|checkout/gi);
  const types = TYPES.filter(([, re]) => cnt(t, re) >= 2).map(([k]) => k); const acts = ACT.filter(([, re]) => cnt(t, re) >= 2).map(([k]) => k);
  const urn = (text.match(/\b(EY\d{6}|\d{6,7})\b(?=[^\n]{0,40}(ofsted|urn))/i) || text.match(/(ofsted|urn)[^\n]{0,40}\b(EY\d{6})\b/i))?.[0]?.match(/EY\d{6}|\d{6,7}/)?.[0] || null;
  const franchiseWords = cnt(t, /franchis(e|ee|ing|or)\b/g); const sites = cnt(t, /\b(our (venues|locations|sites|centres|branches))\b/g);
  return { haf, paid: prices, types, acts, ofstedUrn: urn, ofsted: cnt(t, /ofsted/g), franchiseWords, multiSite: sites > 0 }; }
async function judge(lead, kind, url, r, guess = false) {
  const row = { id: lead.id, kind, url, final: r.final, status: r.status, err: r.err, comingSoon: lead.comingSoon === true || undefined, wasDown: lead.websiteDown === true || undefined, residue: true };
  if (r.status === 0 || r.status >= 400) return { ...row, verdict: "unreachable", sector: "unreachable", nameOk: false, locOk: false, locHits: [], notTerms: [] };
  const text = strip(r.html); const host = (()=>{ try { return new URL(r.final).hostname.replace(/^www\./,""); } catch { return ""; } })();
  const title = (r.html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").toLowerCase();
  const parkedHits = count(text.slice(0,4000)+" "+title, PARKED); const childHits = count(text, CHILD), otherHits = count(text, OTHER);
  const nameToks = tokens(lead.name), nameHit = nameToks.filter(t => text.includes(t) || host.includes(t));
  const nameOk = nameToks.length ? nameHit.length >= Math.max(1, Math.ceil(nameToks.length*0.6)) : false;
  const hostHasName = nameToks.some(t => t.length>=5 && squash(host).includes(t)) || (squash(lead.name).length>=8 && squash(host).includes(squash(lead.name).slice(0,10)));
  const raw = r.html.toLowerCase(); const locs = locBits(lead.location); let locHits = locs.filter(l => text.includes(l) || raw.includes(l)); if (!locHits.length && locs.length && childHits.length >= 2) { const extra = await contactPage(r.html, r.final); if (extra) locHits = locs.filter(l => extra.includes(l)).map(l=>l+" (contact page)"); } const locOk = locHits.length > 0;
  let sector = "no-signal";
  if (parkedHits.length && childHits.length < 2) sector = "parked"; else if (text.length < 200) sector = "empty"; else if (childHits.length >= 2) sector = "child"; else if (otherHits.length >= 2 && childHits.length === 0) sector = "other-sector";
  let verdict;
  if (kind === "candidate") { if (sector === "child" && nameOk && locOk) verdict = "confirm"; else if (sector === "child" && (nameOk || hostHasName) && (locOk || hostHasName)) verdict = "confirm-weak"; else if (sector === "child" && (nameOk || hostHasName)) verdict = "keep-candidate"; else verdict = "drop"; }
  else verdict = sector === "child" ? "ok" : sector;
  const booking = await bookingScan(r.html, r.final || url, guess); const extraText = booking.extraText || ""; delete booking.extraText;
  return { ...row, verdict, sector, nameOk: nameOk || hostHasName, locOk, locs, locHits, notTerms: otherHits.slice(0,5), childTerms: childHits.slice(0,6), textLen: text.length, booking, signals: signals(text + " " + extraText, r.html), pagesForSignals: booking.pagesRead || 1, _html: r.html, _extraText: extraText };
}
// ---------- copied from find_websites.mjs / second_look.mjs (search + pick rules) ----------
const SKIP = /(maps\.apple|maps\.google|goo\.gl|waze|what3words|openstreetmap|facebook|instagram|twitter|x\.com|tiktok|youtube|linkedin|pinterest|threads\.net|gov\.uk|ofsted|nhs\.uk|yell\.com|yelp|thomsonlocal|192\.com|cylex|hotfrog|freeindex|scoot|childcare\.co\.uk|daynurseries|nurseriesuk|care\.com|careinspectorate|familysupportni|findchildcare|hoop\.co\.uk|eequ|pebble|playwaze|yellowdays|clubspark|footballfoundation|classforkids|bookwhen|kidadl|mumsnet|netmums|indeed|glassdoor|reed\.co\.uk|totaljobs|companieshouse|endole|opencorporates|checkacompany|companycheck|bizstats|find-and-update|charitycommission|register-of-charities|wikipedia|trustpilot|google\.|bing\.|amazon|ebay|etsy|nextdoor|tripadvisor|justgiving|gofundme|eventbrite|meetup|wordpress\.com|blogspot|wixsite|weebly|sites\.google|linktr\.ee|schoolsweb|primaryschool|\.sch\.uk|\.ac\.uk|schoolguide|locrating|getthedata|streetcheck|doogal|postcodearea|activityos|news|echo|gazette|times|mail|express|mirror|standard|chronicle|courier|herald|observer|telegraph|guardian|bbc\.)/i;
const STOP2 = new Set("the and of ltd limited cic cio uk plc llp co club clubs school nursery pre preschool childcare children kids day care centre center group holiday camp camps club activities activity community trust academy little happy days playgroup out after".split(" "));
const tokens2 = (s) => (s||"").toLowerCase().replace(/[’']/g,"").split(/[^a-z0-9]+/).filter(t=>t.length>=3 && !STOP2.has(t));
const town = (l) => { const loc = String(l.location||"").split(/[·|]/)[0].split(",")[0].replace(/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/,"").trim(); return loc && !/^\d+ sites?$/i.test(loc) ? loc : (l.county||l.region||""); };
const SOCIAL = /^(www\.|m\.|en-gb\.)?(facebook\.com|instagram\.com)\//i;
// Brave credit is at $0 (confirmed 402 CREDIT_EXHAUSTED). Refuse to make even the first network call against the
// Brave API for this run — leads that would need it are left "unresolved-needs-search" (pending), never guessed at.
// Pass --allow-brave once the account is topped up to re-enable the fallback search.
const BRAVE_DISABLED = !args["allow-brave"];
let braveUsed = 0, braveDead = BRAVE_DISABLED ? "Brave disabled for this run (no API credit; pass --allow-brave once topped up)" : null; const sleep = (ms) => new Promise(r=>setTimeout(r,ms));
async function search(q, _retry = false) { if (!API_KEY) return { status: 0, results: [], err: "no BRAVE_SEARCH_API_KEY" }; if (braveDead) return { status: 402, results: [], err: braveDead, skipped: true }; const ctrl = new AbortController(); const t = setTimeout(()=>ctrl.abort(), 15000);
  try { braveUsed++; const r = await fetch(`https://api.search.brave.com/res/v1/web/search?q=${encodeURIComponent(q)}&country=GB&search_lang=en&count=10&safesearch=moderate`, { signal: ctrl.signal, headers: { accept: "application/json", "accept-encoding": "gzip", "x-subscription-token": API_KEY } });
    if (r.status === 429 && !_retry) { clearTimeout(t); await sleep(20000); return search(q, true); }
    if (r.status !== 200) { const body = (await r.text()).slice(0, 160); if (r.status === 402) braveDead = "Brave credit exhausted (402): " + (body.match(/"detail":"([^"]+)"/)?.[1] || body); return { status: r.status, results: [], err: body }; }
    const j = await r.json(); return { status: 200, results: (j.web?.results ?? []).map(x => ({ url: x.url, title: x.title || "", desc: x.description || "" })) }; }
  catch (e) { return { status: 0, results: [], err: String(e?.name||e).slice(0,40) }; } finally { clearTimeout(t); } }
// Residue rule is the STRICT one: the host must carry the name (no title-only matches).
function pick(lead, results) { const nt = tokens2(lead.name); const nsq = squash(lead.name); if (!nt.length) return null;
  for (const r of results.slice(0, 8)) { let host; try { host = new URL(r.url).hostname.replace(/^www\./,""); } catch { continue; } if (SKIP.test(host) || SKIP.test(r.url)) continue;
    const hsq = host.split(".")[0]; const hostHit = nt.some(t => t.length >= 4 && hsq.includes(t)) || (nsq.length >= 6 && hsq.includes(nsq.slice(0, Math.min(nsq.length, 12))));
    if (hostHit) return { url: `https://${host}/`, why: `host carries the name (${host})`, title: r.title }; }
  return null; }
function pickSocial(lead, results) { const nt = tokens2(lead.name); for (const r of results.slice(0, 8)) { let h, p; try { const x = new URL(r.url); h = x.hostname.replace(/^www\./,""); p = x.pathname; } catch { continue; } if (!SOCIAL.test(h + p)) continue; const slug = tokens2(p.replace(/\/(pages|people|groups|profile\.php)/,"")); if (nt.some(t => t.length >= 4 && slug.some(s => s.includes(t) || t.includes(s)))) return r.url; } return null; }
// ---------- copied from find_contacts.mjs ----------
const BAD_MAIL = /(example\.com|sentry|wixpress|wordpress|godaddy|\.png|\.jpg|\.gif|\.svg|\.webp|noreply|no-reply|donotreply|privacy@|abuse@|dmca@|jscomp|schema\.org|w3\.org|@2x|@3x|u003e|sitemap)/i;
const decode = (s) => s.replace(/&#(\d+);/g,(m,n)=>String.fromCharCode(+n)).replace(/&#x([0-9a-f]+);/gi,(m,h)=>String.fromCharCode(parseInt(h,16))).replace(/&amp;/g,"&").replace(/&nbsp;/g," ").replace(/\[at\]|\(at\)/gi,"@").replace(/\[dot\]|\(dot\)/gi,".");
function emails(html, host) { const h = decode(html); const set = new Map();
  for (const m of h.matchAll(/mailto:([^"'?\s<>]+)/gi)) { const e = m[1].trim().toLowerCase(); if (/^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/.test(e) && !BAD_MAIL.test(e)) set.set(e, (set.get(e)||0)+10); }
  for (const m of h.matchAll(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/gi)) { const e = m[0].toLowerCase(); if (!BAD_MAIL.test(e) && !/\.(js|css|html|php)$/.test(e)) set.set(e, (set.get(e)||0)+1); }
  return [...set.entries()].map(([e,n]) => { const d = e.split("@")[1]; const own = host && (host.endsWith(d) || d.endsWith(host)); return { e, score: n + (own ? 20 : 0) + (/^(info|hello|enquiries|bookings|admin|contact|office)@/.test(e) ? 3 : 0) }; }).sort((a,b)=>b.score-a.score).map(x=>x.e); }
function phones(html) { const t = decode(html).replace(/<[^>]+>/g," "); const out = new Map();
  for (const m of t.matchAll(/(?:\+44\s?\(?0?\)?\s?|\b0)(?:\d[\s\-().]?){9,10}\b/g)) { let p = m[0].replace(/[^\d+]/g,""); if (p.startsWith("+44")) p = "0" + p.slice(3).replace(/^0/,""); if (!/^0(1|2|3|7|8)\d{8,9}$/.test(p)) continue; if (/^0(800|808|845|870|871|844|843)/.test(p) && out.size) continue; out.set(p, (out.get(p)||0)+1); }
  for (const m of html.matchAll(/href=["']tel:([^"']+)/gi)) { let p = m[1].replace(/[^\d+]/g,""); if (p.startsWith("+44")) p = "0" + p.slice(3).replace(/^0/,""); if (/^0(1|2|3|7|8)\d{8,9}$/.test(p)) out.set(p, (out.get(p)||0)+10); }
  return [...out.entries()].sort((a,b)=>b[1]-a[1]).map(([p])=>p.replace(/^(0\d{2,4})(\d{3})(\d{3,4})$/, "$1 $2 $3")); }
function contactLinks(html, base) { const hrefs = [...html.matchAll(/href=["']([^"'#]*(contact|about|find-us|findus|get-in-touch|enquir|book)[^"'#]*)["']/gi)].map(x=>x[1]).filter(h=>!/^(mailto|tel|javascript)/i.test(h)); const out=[]; for (const h of hrefs) { try { const u = new URL(h, base); if (u.hostname === new URL(base).hostname && !out.includes(u.href)) out.push(u.href); } catch {} } return out.slice(0,2); }
async function scrapeContact(homeHtml, base) { let html = homeHtml; let pages = 1; for (const c of contactLinks(homeHtml, base)) { const r = await fetchSite(c); if (r.status === 200) { html += "\n" + r.html; pages++; } } const host = (()=>{ try { return new URL(base).hostname.replace(/^www\./,""); } catch { return ""; } })(); const em = emails(html, host), ph = phones(html); return { pages, email: em[0] || null, phone: ph[0] || null, emails: em.slice(0,3), phones: ph.slice(0,3) }; }

// ---------- the residue itself ----------
const norm = (u) => /^https?:\/\//i.test(u) ? u : "https://" + u;
function alternates(u0, name) { let u; try { u = new URL(norm(u0)); } catch { return []; } const host = u.hostname.replace(/^www\./,""); const pathq = (u.pathname === "/" ? "" : u.pathname) + u.search;
  const tld = host.match(/\.(co\.uk|org\.uk|com|org|uk|net|co|info|scot|wales|cymru)$/i)?.[1]; const stem = tld ? host.slice(0, -(tld.length + 1)) : host;
  const stemOk = (() => { const sq = squash(stem.split(".")[0]); return tokens2(name).some(t => t.length >= 4 && sq.includes(t)) || (squash(name).length >= 6 && sq.includes(squash(name).slice(0, 8))); })();
  const hosts = [host, "www." + host]; if (tld && stemOk) for (const t of ["co.uk", "com", "org", "uk", "org.uk"]) if (t !== tld.toLowerCase()) hosts.push(stem + "." + t, "www." + stem + "." + t);
  const orig = norm(u0).replace(/\/$/, ""); const out = []; for (const h of hosts) { const urls = []; for (const s of ["https", "http"]) { urls.push(`${s}://${h}${pathq}`); if (pathq && !pathq.endsWith("/") && !/\.[a-z]{2,5}$/i.test(pathq)) urls.push(`${s}://${h}${pathq}/`); } out.push({ host: h, urls: urls.filter(x => x.replace(/\/$/, "") !== orig) }); }
  return out.filter(g => g.urls.length); }
const isSocialUrl = (u) => { try { return SOCIAL.test(new URL(norm(u)).hostname.replace(/^www\./,"") + "/"); } catch { return false; } };

const FIELDS = ["name","location","county","region","source","website","websiteCandidate","websiteCandidateWhy","websiteRejected","websiteRejectedWhy","websiteDown","websiteDownWhy","websiteDead","socialUrl","bookingChecked","bookingSystem","excluded","email","phone","websiteCheckedAt","comingSoon"];
const snap = await db.collection("leads").select(...FIELDS).get();
const leads = snap.docs.map(d => ({ id: d.id, ...d.data() })).filter(l => !l.excluded);
const isA = (l) => !l.websiteDead && ((l.website && l.websiteDown) || (!l.website && !l.websiteCandidate && l.websiteRejected && /unreachable/i.test(l.websiteRejectedWhy || "")));
const isB = (l) => l.website && !l.websiteDown && !l.bookingChecked && !l.bookingSystem && l.websiteCheckedAt && !isSocialUrl(l.website);
const A = leads.filter(isA), B = leads.filter(isB);
const groupA = { total: A.length, confirmedFlaggedDown: A.filter(l=>l.website).length, candidateDroppedUnreachable: A.filter(l=>!l.website).length, downWhy: {} };
for (const l of A.filter(l=>l.website)) { const k = String(l.websiteDownWhy || "?").replace(/HTTP \d+/, m=>m).slice(0,20); groupA.downWhy[k] = (groupA.downWhy[k]||0)+1; }
const groupB = { total: B.length, withNoContact: B.filter(l=>!l.email && !l.phone).length };
const dead = leads.filter(l=>l.websiteDead).length;
console.log("RESIDUE COUNTS", JSON.stringify({ leadsNotExcluded: leads.length, groupA_unreachable: groupA, groupB_homepageOnly: groupB, alreadyDeadMarked: dead, braveKey: !!API_KEY }, null, 1));

const doneRows = fs.existsSync(OUT) ? fs.readFileSync(OUT,"utf8").split("\n").filter(Boolean).map(l=>{try{return JSON.parse(l)}catch{return null}}).filter(Boolean) : [];
const redo = (r) => r.result === "stuck" || r.result === "error" || r.result === "unresolved-needs-search" || (args["retry-search"] && r.searchSkipped && (r.result === "dead" || r.result === "blocked"));
const done = new Set(doneRows.filter(r => !redo(r)).map(r=>r.id)); braveUsed = doneRows.filter(r=>r.searched && !r.searchSkipped).length;

if (args.apply) { // Direct fill-only writes that apply_verify doesn't cover.
  const ids = [...new Set(doneRows.map(r=>r.id))]; const cur = new Map(); for (let i=0;i<ids.length;i+=300) { const snaps = await db.getAll(...ids.slice(i,i+300).map(id=>db.collection("leads").doc(id)), { fieldMask:["website","websiteCandidate","websiteDown","websiteDead","socialUrl","websiteRejected","bookingChecked","bookingSystem","verifyPending"] }); for (const s of snaps) if (s.exists) cur.set(s.id, s.data()); }
  const D = admin.firestore.FieldValue.delete; let batch = db.batch(), inB = 0; const c = {}; const bump = (k) => c[k] = (c[k]||0)+1; const stamp = new Date().toISOString();
  for (const r of doneRows) { const x = cur.get(r.id); if (!x) continue; const upd = {};
    if (r.group === "B") { if (r.result === "probed-no-booking" && x.website && !x.bookingChecked && !x.bookingSystem) { upd.bookingChecked = true; upd.bookingCheckedPages = 1; upd.bookingNote = `residue ${stamp.slice(0,10)}: homepage links to no booking/shop/class pages and /book, /booking, /classes, /camps, /timetable, /prices, /contact + sitemap.xml don't exist — enquiry only`; bump("B: bookingChecked set (probed, no booking pages)"); } else if (r.result === "probed-no-booking") bump("B: probed but already checked/has system"); }
    if (r.group !== "A") { if (Object.keys(upd).length) { upd.updatedAt = stamp; batch.update(db.collection("leads").doc(r.id), upd); if (++inB >= 400) { await batch.commit(); batch = db.batch(); inB = 0; } } continue; }
    if (r.result === "recovered") { if (x.website && x.websiteDown) { upd.websiteDown = D(); upd.websiteDownWhy = D(); bump("recovered: websiteDown cleared"); } else if (!x.website) bump("recovered but apply_verify hasn't confirmed it yet (run apply_verify first)"); else bump("recovered: already clean"); }
    else if (r.result === "keep-candidate") { if (!x.website && !x.websiteCandidate) { upd.websiteCandidate = r.url; upd.websiteCandidateWhy = `residue ${stamp.slice(0,10)}: name matches, children's business, but their town/postcode wasn't seen on it`; upd.websiteRejected = D(); upd.websiteRejectedWhy = D(); bump("keep-candidate set"); } else bump("keep-candidate: lead already has a site/candidate"); }
    else if (r.result === "social") { if (!x.socialUrl) { upd.socialUrl = r.social; upd.socialFrom = "web search result (residue pass)"; bump("socialUrl set"); } else bump("socialUrl already there"); if (!x.websiteDead) { upd.websiteDead = true; upd.websiteDeadAt = stamp; upd.websiteDeadWhy = `${r.deadWhy || "site unreachable"} — only a Facebook/Instagram page found`; upd.websiteDeadCategory = r.deadCategory || "unreachable"; bump("websiteDead marked (social only)"); } }
    else if (r.result === "dead" && r.sector === "child") { bump("dead-but-child-site skipped (alternate host is a children's site without their name — left for a human)"); }
    else if (r.result === "dead") { if (!x.websiteDead) { upd.websiteDead = true; upd.websiteDeadAt = stamp; upd.websiteDeadWhy = r.deadWhy || "site unreachable after alternates + web search"; upd.websiteDeadCategory = r.deadCategory || "unreachable"; bump("websiteDead marked"); } else bump("websiteDead already marked"); }
    else if (r.result === "unresolved-needs-search") { if (!x.websiteDead && !x.website) { if (!x.verifyPending) { upd.verifyPending = true; upd.verifyPendingWhy = r.pendingWhy || "alternates all failed; needs a web search to confirm (not run — no Brave credit)"; upd.verifyPendingAt = stamp; bump("verifyPending set (needs web search, no brave credit)"); } else bump("verifyPending already set"); } else bump("unresolved-needs-search: lead already resolved another way, left alone"); }
    if (Object.keys(upd).length) { upd.updatedAt = stamp; batch.update(db.collection("leads").doc(r.id), upd); if (++inB >= 400) { await batch.commit(); batch = db.batch(); inB = 0; } } }
  if (inB) await batch.commit(); console.log("APPLIED", JSON.stringify(c)); process.exit(0); }

if (!args.run) process.exit(0);
const todo = [...(GROUP.includes("A") ? A.map(l=>({ lead: l, group: "A" })) : []), ...(GROUP.includes("B") ? B.map(l=>({ lead: l, group: "B" })) : [])].filter(j => !done.has(j.lead.id)).slice(0, LIMIT);
console.log(`to process: ${todo.length} (already done ${done.size}, brave used so far ${braveUsed}, budget ${BRAVE_BUDGET})`);
const out = fs.createWriteStream(OUT, { flags: "a" }), vout = fs.createWriteStream(VERIFY, { flags: "a" }), cout = fs.createWriteStream(CONTACTS, { flags: "a" });
const tally = {}; const bump = (k) => tally[k] = (tally[k]||0)+1; let i = 0, n = 0; const t0 = Date.now();
const writeVerify = (row) => { const { _html, _extraText, ...clean } = row; vout.write(JSON.stringify(clean) + "\n"); };
async function maybeContact(lead, html, base, row) { if (lead.email || lead.phone || !html) return; const ct = await scrapeContact(html, base); row.contact = { email: ct.email, phone: ct.phone }; if (ct.email || ct.phone) { cout.write(JSON.stringify({ id: lead.id, status: 200, pages: ct.pages, email: ct.email, phone: ct.phone, emails: ct.emails, phones: ct.phones, residue: true }) + "\n"); bump("contact found"); } }

async function doA(lead) { const orig = lead.website || lead.websiteRejected; const row = { id: lead.id, group: "A", name: lead.name, orig, hadWebsite: !!lead.website, tried: [], searched: false };
  // 1. alternates
  let hit = null; outer: for (const g of alternates(orig, lead.name)) { for (const u of g.urls) { const r = await fetchSite(u); row.tried.push(`${u} ${r.status || r.err || 0}`); if (r.status === 200 && r.html.length > 300) { hit = { u, r, via: "alternate" }; break outer; } if (/^(ENOTFOUND|AbortError|ENETUNREACH|ERR_INVALID_URL)$/.test(r.err || "")) break; /* the host is gone / hangs: no point trying its other scheme */ } }
  // The original itself once more (maybe it came back).
  if (!hit) { const r = await fetchSite(norm(orig)); row.tried.push(`${norm(orig)} ${r.status || r.err || 0}`); if (r.status === 200 && r.html.length > 300) hit = { u: norm(orig), r, via: "original" }; else row.origErr = r.err || `HTTP ${r.status}`; }
  const HARD = (e) => /^(ENOTFOUND|ECONNREFUSED|ENETUNREACH|ERR_INVALID_URL|HTTP 404|HTTP 410|HTTP 400)$/.test(String(e||"")); row.hardDead = !!row.origErr && HARD(row.origErr) && row.tried.every(t => /(ENOTFOUND|ECONNREFUSED|ENETUNREACH|ERR_INVALID_URL| 404| 410| 400)$/.test(t));
  // 2. one Brave search
  if (!hit) { if (braveUsed >= BRAVE_BUDGET) { row.result = "stuck"; row.stuckWhy = "brave budget exhausted"; bump("stuck: budget"); return row; }
    const q = `"${lead.name}" ${town(lead)}`.trim(); const s = await search(q); row.searched = true; row.q = q; row.searchStatus = s.status; row.top = s.results.slice(0,3).map(x=>x.url.slice(0,90)); await sleep(GAP_MS);
    if (s.status !== 200) { row.searchSkipped = `${s.status} ${(s.err || "").slice(0,80)}`; if (s.skipped) braveUsed--; }
    else {
    const p = pick(lead, s.results);
    if (p && p.url.replace(/^https?:\/\/(www\.)?/,"").replace(/\/$/,"") !== norm(orig).replace(/^https?:\/\/(www\.)?/,"").replace(/\/$/,"")) { const r = await fetchSite(p.url); row.tried.push(`${p.url} ${r.status || r.err || 0} (search)`); if (r.status === 200 && r.html.length > 300) hit = { u: p.url, r, via: "search" }; else row.searchHitDead = p.url; }
    if (!hit) { const soc = pickSocial(lead, s.results); if (soc) { row.result = "social"; row.social = soc; row.deadWhy = `${row.origErr || "unreachable"} at ${orig}`; row.deadCategory = "unreachable"; bump("social only"); return row; } } } }
  if (!hit) {
    // Search was skipped (no Brave credit) — we have NOT confirmed this lead is dead. Never guess; leave it pending.
    if (row.searchSkipped) { row.result = "unresolved-needs-search"; row.pendingWhy = `${row.origErr ? row.origErr + " at " + orig + "; " : ""}alternates all fail; a web search is needed to confirm — not run (${row.searchSkipped.slice(0,80)})`; bump("unresolved-needs-search (no brave credit)"); return row; }
    const searchedNote = row.searched ? "; alternates + web search found nothing" : "";
    if (row.hardDead) { row.result = "dead"; row.deadWhy = `${row.origErr} at ${orig}; alternates all fail${searchedNote}`; row.deadCategory = "unreachable"; bump("dead"); }
    else { row.result = "blocked"; row.blockedWhy = `${row.origErr || "?"} at ${orig} — a bot wall / timeout, not proof the site is gone${searchedNote}`; bump("blocked"); }
    return row; }
  // 3. judge what we found as a candidate (so apply_verify sets website = final on confirm)
  const j = await judge(lead, "candidate", hit.u, hit.r, true); row.url = j.final || hit.u; row.via = hit.via; row.verdict = j.verdict; row.sector = j.sector;
  if (j.verdict === "confirm" || j.verdict === "confirm-weak") { writeVerify(j); row.result = "recovered"; row.verifyRow = true; bump(`recovered via ${hit.via} (${j.verdict})`); if (j.booking?.system) bump("recovered: booking system " + j.booking.system); await maybeContact(lead, j._html, j.final || hit.u, row); }
  else if (j.verdict === "keep-candidate") { row.result = "keep-candidate"; bump(`keep-candidate via ${hit.via}`); }
  else if (hit.via === "search" && !row.hardDead) { row.result = "blocked"; row.blockedWhy = `${row.origErr || "?"} at ${orig} — bot wall / timeout; the searched site ${hit.u} wasn't theirs (${j.sector})`; bump("blocked (search hit not theirs)"); }
  else { row.result = "dead"; row.deadWhy = j.sector === "parked" ? `parked / for-sale domain at ${hit.u}` : j.sector === "other-sector" ? `domain now a different kind of business (${(j.notTerms||[]).slice(0,3).join(", ")}) at ${hit.u}` : j.sector === "empty" ? `empty page at ${hit.u}` : `${hit.u} reachable but neither their name nor children's wording on it`; row.deadWhy = `${row.origErr ? row.origErr + " at " + orig + "; " : ""}${row.deadWhy}`; row.deadCategory = j.sector === "parked" ? "parked" : j.sector === "empty" ? "empty" : "no-match"; bump(`dead: ${j.sector} (${hit.via})`); }
  return row; }

async function doB(lead) { const url = norm(lead.website); const row = { id: lead.id, group: "B", name: lead.name, orig: lead.website, searched: false };
  const r = await fetchSite(url); if (r.status !== 200 || !r.html) { row.result = "unreachable"; row.err = r.err || `HTTP ${r.status}`; bump("B: homepage unreachable now"); const j = await judge(lead, "confirmed", url, r); writeVerify(j); row.verifyRow = true; return row; }
  const j = await judge(lead, "confirmed", url, r, true); writeVerify(j); row.verifyRow = true; row.verdict = j.verdict; row.sector = j.sector; row.textLen = j.textLen; row.booking = { system: j.booking?.system || null, pagesRead: j.booking?.pagesRead, subpages: j.booking?.subpages, guessedTried: j.booking?.guessedTried };
  if (j.booking?.system) { row.result = "booking-found"; bump("B: booking system found: " + j.booking.system); }
  else if ((j.booking?.pagesRead || 1) >= 2 || (j.booking?.subpages === 0 && (j.textLen ?? 0) > 1500)) { row.result = "checked"; bump("B: checked, no booking (enquiry only)"); }
  else if ((j.booking?.subpages ?? 1) === 0 && (j.booking?.guessedTried || 0) >= 8 && (j.textLen ?? 0) >= 300 && (j.sector === "child" || j.sector === "no-signal")) { row.result = "probed-no-booking"; bump("B: no booking pages exist (homepage + guessed paths + sitemap probed)"); }
  else { row.result = "still-unreadable"; bump("B: still only the homepage readable"); }
  if (j.verdict !== "ok") bump("B: verdict " + j.verdict);
  await maybeContact(lead, j._html, j.final || url, row); return row; }

async function worker() { while (i < todo.length) { const job = todo[i++]; let row; try { row = job.group === "A" ? await doA(job.lead) : await doB(job.lead); } catch (e) { row = { id: job.lead.id, group: job.group, name: job.lead.name, result: "error", err: String(e?.message || e).slice(0,120) }; bump("error"); }
  row.at = new Date().toISOString(); out.write(JSON.stringify(row) + "\n"); n++; if (n % 100 === 0) console.log(`${n}/${todo.length} ${Math.round((Date.now()-t0)/1000)}s brave=${braveUsed}`, JSON.stringify(tally)); } }
await Promise.all(Array.from({ length: CONC }, worker));
out.end(); vout.end(); cout.end(); console.log("done", n, `brave=${braveUsed}`, JSON.stringify(tally)); process.exit(0);
