// Second look at search results that picked no website (from websearch.out.jsonl, no new searches):
//  · a Facebook/Instagram page whose slug shares a name token → socialUrl
//  · an eequ / Pebble / Playwaze / ClassForKids / Bookwhen… page in the top results → bookingSystem + bookingUrl (they book there)
//  · any other non-directory, non-school, shallow result → a LOOSE websiteCandidate for verify_sites to judge (name + town + children's wording)
//   node scripts/leads/second_look.mjs [--apply]
import admin from "firebase-admin"; import fs from "fs";
admin.initializeApp({ credential: admin.credential.cert(JSON.parse(fs.readFileSync("./serviceAccountKey.json","utf8"))) });
const db = admin.firestore(); const APPLY = process.argv.includes("--apply");
const rows = fs.readFileSync("scripts/leads/out/websearch.out.jsonl","utf8").trim().split("\n").map(l=>JSON.parse(l)).filter(r=>!r.url && r.n);
const STOP = new Set("the and of ltd limited cic cio uk plc llp co club clubs school nursery pre preschool childcare children kids day care centre center group holiday camp camps activities activity community trust academy little happy days playgroup out after".split(" "));
const tokens = (s) => (s||"").toLowerCase().replace(/[’']/g,"").split(/[^a-z0-9]+/).filter(t=>t.length>=3 && !STOP.has(t));
const SOCIAL = /^(www\.|m\.|en-gb\.)?(facebook\.com|instagram\.com)\//i;
const PLAT = [["eequ", /eequ\.org/i], ["Pebble", /bookpebble\.co\.uk|pebble\.co/i], ["Playwaze", /playwaze\.com/i], ["ClassForKids", /classforkids\.io/i], ["Bookwhen", /bookwhen\.com/i], ["Yellow Days", /yellowdays/i], ["ClubSpark", /clubspark/i], ["Hoop", /hoop\.co\.uk/i], ["Kids Club HQ", /kidsclubhq/i], ["Magic Booking", /magicbooking/i], ["iPAL", /ipal\.(co\.uk|app)/i], ["Eventbrite", /eventbrite/i], ["Bookaby", /bookaby/i], ["Pembee", /pembee/i], ["Enrolmy", /enrolmy/i]];
const DIR = /(gov\.uk|ofsted|nhs\.uk|childcare\.co\.uk|daynurseries|nurseriesuk|yell\.com|yelp|192\.com|cylex|hotfrog|freeindex|scoot|thomsonlocal|care\.com|careinspectorate|familysupportni|findchildcare|kidadl|mumsnet|netmums|indeed|reed\.co\.uk|totaljobs|companieshouse|endole|opencorporates|charitycommission|register-of-charities|wikipedia|trustpilot|google\.|bing\.|amazon|ebay|etsy|nextdoor|tripadvisor|justgiving|eventbrite|meetup|linkedin|youtube|tiktok|x\.com|twitter|pinterest|threads\.net|\.sch\.uk|\.ac\.uk|schoolguide|locrating|getthedata|streetcheck|doogal|maps\.|reachvolunteering|mymaxcard|activeessex|parksofessex|news|gazette|echo|times|mail|express|mirror|standard|chronicle|courier|herald|observer|telegraph|guardian|bbc\.|wordpress\.com|blogspot|wixsite|weebly|sites\.google|linktr\.ee|schoolsweb|primaryschool|activityos)/i;
const ids = rows.map(r=>r.id); const cur = new Map(); for (let i=0;i<ids.length;i+=300) { const snaps = await db.getAll(...ids.slice(i,i+300).map(id=>db.collection("leads").doc(id)), { fieldMask:["name","website","websiteCandidate","socialUrl","bookingSystem","bookingUrl","excluded"] }); for (const s of snaps) if (s.exists) cur.set(s.id, s.data()); }
let social=0, plat=0, cand=0, n=0; let batch=db.batch(), inB=0; const byPlat={};
for (const r of rows) { const c = cur.get(r.id); if (!c || c.excluded) continue; const nt = tokens(c.name); const upd = {};
  for (const u of (r.top||[])) { let h, path; try { const x = new URL(u); h = x.hostname.replace(/^www\./,""); path = x.pathname; } catch { continue; }
    if (SOCIAL.test(h + path) && !c.socialUrl && !upd.socialUrl) { const slug = tokens(path.replace(/\/(pages|people|groups|profile\.php)/,"")); if (nt.some(t => t.length >= 4 && slug.some(s => s.includes(t) || t.includes(s)))) { upd.socialUrl = u; upd.socialFrom = "web search result"; social++; } continue; }
    const p = PLAT.find(([, re]) => re.test(h)); if (p && !c.bookingSystem && !upd.bookingSystem) { const tt = tokens(path); if (nt.some(t => t.length >= 4 && tt.some(s => s.includes(t)))) { upd.bookingSystem = p[0]; upd.bookingUrl = u; upd.bookingFrom = "web search result (their listing on the platform)"; upd.bookingChecked = true; plat++; byPlat[p[0]]=(byPlat[p[0]]||0)+1; } continue; }
    if (!c.website && !c.websiteCandidate && !upd.websiteCandidate && !DIR.test(h) && !DIR.test(u) && path.split("/").filter(Boolean).length <= 1) { upd.websiteCandidate = `https://${h}/`; upd.websiteCandidateWhy = "web search (loose): a shallow non-directory result — unverified"; cand++; } }
  if (Object.keys(upd).length) { n++; if (APPLY) { batch.update(db.collection("leads").doc(r.id), upd); if (++inB >= 400) { await batch.commit(); batch = db.batch(); inB = 0; } } } }
if (APPLY && inB) await batch.commit(); console.log(JSON.stringify({ rowsLooked: rows.length, leadsTouched: n, socialUrlSet: social, platformSet: plat, byPlat, looseCandidates: cand, applied: APPLY })); process.exit(0);
