// Museum Vault content bank - KS2 history: chronology/timeline ordering, matching figures/events/periods, and
// cause-and-effect. Deliberately kept to well-established, non-controversial, widely-taught UK curriculum topics
// (Stone Age to Iron Age, Romans, Anglo-Saxons and Vikings, ancient Egypt, and safely factual 20th-century dates
// such as the two World Wars stated only by date/who-fought/when-ended - no depictions of violence or atrocity,
// no contested interpretation). Every date/fact below is standard textbook content. Server and client share this
// exact file (BACKEND-PATTERN.md): the bank that renders the game is the bank that marks it.
import type { QuizItem } from "../quiz/core";

const opt = (...pairs: [string, string][]) => pairs.map(([id, text]) => ({ id, text }));

export const MUSEUM_ITEMS: QuizItem[] = [
  // ── chronology / ordering (each item asks "which came first/last" between two well-separated periods) ────────
  { key: "mv-chron-1", topics: ["chronology"], difficulty: 1, prompt: "Which period came FIRST?", options: opt(["stone", "The Stone Age"], ["romans", "The Roman period"]), correctId: "stone", explanation: "The Stone Age (ending around 2,500 BC in Britain) came long before the Romans arrived in AD 43." },
  { key: "mv-chron-2", topics: ["chronology"], difficulty: 1, prompt: "Which period came FIRST?", options: opt(["romans", "The Roman period"], ["victorians", "The Victorian era"]), correctId: "romans", explanation: "The Romans were in Britain from AD 43 to AD 410, over a thousand years before Queen Victoria (1837-1901)." },
  { key: "mv-chron-3", topics: ["chronology"], difficulty: 2, prompt: "Which came FIRST: the Bronze Age or the Iron Age?", options: opt(["bronze", "The Bronze Age"], ["iron", "The Iron Age"]), correctId: "bronze", explanation: "Britain's Bronze Age (about 2,500-800 BC) came before the Iron Age (about 800 BC-AD 43)." },
  { key: "mv-chron-4", topics: ["chronology"], difficulty: 2, prompt: "Which came FIRST: the Anglo-Saxons settling in Britain, or the Norman Conquest?", options: opt(["saxons", "The Anglo-Saxons settling"], ["normans", "The Norman Conquest"]), correctId: "saxons", explanation: "Anglo-Saxon settlement began in the 5th century AD; the Norman Conquest was in 1066." },
  { key: "mv-chron-5", topics: ["chronology"], difficulty: 2, prompt: "Which came FIRST: the Vikings raiding Britain, or the Tudor dynasty?", options: opt(["vikings", "Viking raids"], ["tudors", "The Tudor dynasty"]), correctId: "vikings", explanation: "Viking raids began in AD 793; the Tudor dynasty began in 1485 with Henry VII." },
  { key: "mv-chron-6", topics: ["chronology"], difficulty: 1, prompt: "In what year did the Norman Conquest of England happen?", options: opt(["1066", "1066"], ["1166", "1166"], ["966", "966"], ["1266", "1266"]), correctId: "1066", explanation: "William the Conqueror defeated King Harold at the Battle of Hastings in 1066." },
  { key: "mv-chron-7", topics: ["chronology"], difficulty: 2, prompt: "In what year did the Romans first invade Britain under Emperor Claudius?", options: opt(["ad43", "AD 43"], ["ad143", "AD 143"], ["bc43", "43 BC"], ["ad430", "AD 430"]), correctId: "ad43", explanation: "The Roman conquest of Britain began in AD 43." },
  { key: "mv-chron-8", topics: ["chronology"], difficulty: 2, prompt: "Around when did the Romans finally leave Britain?", options: opt(["ad410", "About AD 410"], ["ad43", "AD 43"], ["ad1066", "AD 1066"], ["ad700", "About AD 700"]), correctId: "ad410", explanation: "Roman forces and administration withdrew from Britain around AD 410." },
  { key: "mv-chron-9", topics: ["chronology"], difficulty: 3, prompt: "Which of these four events happened MOST RECENTLY?", options: opt(["ww2", "The end of the Second World War"], ["norman", "The Norman Conquest"], ["romans", "The Roman invasion of Britain"], ["stonehenge", "Stonehenge being built"]), correctId: "ww2", explanation: "Order: Stonehenge (Neolithic, ~2500 BC) - Roman invasion (AD 43) - Norman Conquest (1066) - end of WWII (1945)." },
  { key: "mv-chron-10", topics: ["chronology"], difficulty: 3, prompt: "Which of these four events happened LONGEST AGO?", options: opt(["stonehenge", "Stonehenge being built"], ["ww2", "The end of the Second World War"], ["norman", "The Norman Conquest"], ["romans", "The Roman invasion of Britain"]), correctId: "stonehenge", explanation: "Stonehenge was built around 2,500 BC, thousands of years before the Roman invasion, the Norman Conquest, or WWII." },
  { key: "mv-chron-11", topics: ["chronology"], difficulty: 1, prompt: "Which Queen gives her name to the \"Victorian era\"?", options: opt(["victoria", "Queen Victoria"], ["elizabeth1", "Queen Elizabeth I"], ["mary", "Queen Mary I"], ["anne", "Queen Anne"]), correctId: "victoria", explanation: "Queen Victoria reigned from 1837 to 1901, giving her name to the Victorian era." },
  { key: "mv-chron-12", topics: ["chronology"], difficulty: 2, prompt: "The Second World War ran from 1939 to which year?", options: opt(["1945", "1945"], ["1944", "1944"], ["1918", "1918"], ["1950", "1950"]), correctId: "1945", explanation: "The Second World War began in 1939 and ended in 1945." },
  { key: "mv-chron-13", topics: ["chronology"], difficulty: 2, prompt: "The First World War ran from 1914 to which year?", options: opt(["1918", "1918"], ["1914", "1914 (same year)"], ["1920", "1920"], ["1939", "1939"]), correctId: "1918", explanation: "The First World War began in 1914 and ended in 1918." },

  // ── matching figures / events / periods ─────────────────────────────────────────────────────────────────────
  { key: "mv-match-1", topics: ["figures"], difficulty: 1, prompt: "Which king was defeated by William the Conqueror at the Battle of Hastings?", options: opt(["harold", "King Harold II"], ["alfred", "Alfred the Great"], ["john", "King John"], ["canute", "King Canute"]), correctId: "harold", explanation: "King Harold II was killed at the Battle of Hastings in 1066." },
  { key: "mv-match-2", topics: ["figures"], difficulty: 2, prompt: "Which Anglo-Saxon king is famous for supposedly burning some cakes while hiding from the Vikings?", options: opt(["alfred", "Alfred the Great"], ["harold", "Harold II"], ["egbert", "Egbert"], ["athelstan", "Athelstan"]), correctId: "alfred", explanation: "The legend of Alfred the Great and the burnt cakes is a famous (if unproven) English folk story." },
  { key: "mv-match-3", topics: ["figures"], difficulty: 2, prompt: "Which Tudor king had six wives?", options: opt(["henry8", "Henry VIII"], ["henry7", "Henry VII"], ["edward6", "Edward VI"], ["james1", "James I"]), correctId: "henry8", explanation: "Henry VIII famously married six times between 1509 and 1547." },
  { key: "mv-match-4", topics: ["figures"], difficulty: 2, prompt: "Which queen was the daughter of Henry VIII and reigned for 45 years, defeating the Spanish Armada?", options: opt(["elizabeth1", "Elizabeth I"], ["mary1", "Mary I"], ["victoria", "Victoria"], ["anne", "Anne"]), correctId: "elizabeth1", explanation: "Elizabeth I reigned 1558-1603; the Spanish Armada was defeated in 1588." },
  { key: "mv-match-5", topics: ["figures"], difficulty: 2, prompt: "Who led the Roman invasion of Britain in AD 43, as emperor at the time?", options: opt(["claudius", "Emperor Claudius"], ["caesar", "Julius Caesar"], ["nero", "Emperor Nero"], ["augustus", "Emperor Augustus"]), correctId: "claudius", explanation: "Emperor Claudius ordered the successful invasion of Britain in AD 43 (Julius Caesar had raided Britain earlier, in 55-54 BC, without conquering it)." },
  { key: "mv-match-6", topics: ["figures"], difficulty: 3, prompt: "Which British queen led a revolt against the Romans in AD 60-61?", options: opt(["boudicca", "Boudicca"], ["victoria", "Victoria"], ["elizabeth1", "Elizabeth I"], ["mary1", "Mary I"]), correctId: "boudicca", explanation: "Boudicca, queen of the Iceni tribe, led a major uprising against Roman rule in Britain." },
  { key: "mv-match-7", topics: ["figures"], difficulty: 2, prompt: "Who was the Prime Minister of the United Kingdom for most of the Second World War?", options: opt(["churchill", "Winston Churchill"], ["chamberlain", "Neville Chamberlain"], ["attlee", "Clement Attlee"], ["disraeli", "Benjamin Disraeli"]), correctId: "churchill", explanation: "Winston Churchill became Prime Minister in 1940 and led Britain through most of WWII." },
  { key: "mv-match-8", topics: ["figures"], difficulty: 2, prompt: "Which ancient Egyptian king (pharaoh) is famous for his nearly untouched tomb, discovered in 1922?", options: opt(["tutankhamun", "Tutankhamun"], ["ramesses", "Ramesses II"], ["cleopatra", "Cleopatra"], ["khufu", "Khufu"]), correctId: "tutankhamun", explanation: "Howard Carter discovered Tutankhamun's tomb in the Valley of the Kings in 1922." },
  { key: "mv-match-9", topics: ["figures"], difficulty: 3, prompt: "Which pharaoh is traditionally credited with having the Great Pyramid of Giza built?", options: opt(["khufu", "Khufu"], ["tutankhamun", "Tutankhamun"], ["cleopatra", "Cleopatra"], ["ramesses", "Ramesses II"]), correctId: "khufu", explanation: "The Great Pyramid of Giza is traditionally linked to the pharaoh Khufu, around 2560 BC." },
  { key: "mv-match-10", topics: ["periods"], difficulty: 1, prompt: "Which period is known for people first using stone tools, before metal was discovered?", options: opt(["stone", "The Stone Age"], ["bronze", "The Bronze Age"], ["iron", "The Iron Age"], ["roman", "The Roman period"]), correctId: "stone", explanation: "The Stone Age is named for its stone tools, before people learned to work bronze or iron." },
  { key: "mv-match-11", topics: ["periods"], difficulty: 2, prompt: "Which period is known for people learning to mix copper and tin to make a new, harder metal?", options: opt(["bronze", "The Bronze Age"], ["stone", "The Stone Age"], ["iron", "The Iron Age"], ["victorian", "The Victorian era"]), correctId: "bronze", explanation: "Bronze (copper + tin) gave the Bronze Age its name." },
  { key: "mv-match-12", topics: ["periods"], difficulty: 2, prompt: "Which invaders were known for their longships and raids on monasteries such as Lindisfarne?", options: opt(["vikings", "The Vikings"], ["romans", "The Romans"], ["normans", "The Normans"], ["saxons", "The Anglo-Saxons"]), correctId: "vikings", explanation: "Viking raiders, famous for their longships, first attacked the monastery at Lindisfarne in AD 793." },
  { key: "mv-match-13", topics: ["periods"], difficulty: 2, prompt: "Which period is famous for factories, steam engines and the growth of British cities?", options: opt(["industrial", "The Industrial Revolution"], ["stone", "The Stone Age"], ["roman", "The Roman period"], ["medieval", "The medieval period"]), correctId: "industrial", explanation: "The Industrial Revolution (roughly 1760-1840) brought factories, steam power and rapid city growth to Britain." },
  { key: "mv-match-14", topics: ["periods"], difficulty: 3, prompt: "What do historians call the period roughly between the fall of Rome and the Tudors (about 500-1500)?", options: opt(["medieval", "The Middle Ages (medieval period)"], ["stone", "The Stone Age"], ["industrial", "The Industrial Revolution"], ["roman", "The Roman period"]), correctId: "medieval", explanation: "The Middle Ages (medieval period) spans roughly from about AD 500 to 1500 in European history." },

  // ── cause and effect ─────────────────────────────────────────────────────────────────────────────────────────
  { key: "mv-cause-1", topics: ["cause-effect"], difficulty: 2, prompt: "Why did the Romans build a wall (Hadrian's Wall) across northern Britain?", options: opt(["defend", "To help defend and control the northern frontier of their empire"], ["decoration", "Purely as decoration"], ["farming", "To grow crops on top of it"], ["trade", "As a market for selling goods"]), correctId: "defend", explanation: "Hadrian's Wall, begun in AD 122, marked and defended the northern edge of Roman Britain." },
  { key: "mv-cause-2", topics: ["cause-effect"], difficulty: 2, prompt: "Why did William of Normandy invade England in 1066?", options: opt(["claim", "He believed he had a claim to the English throne"], ["famine", "To escape a famine in Normandy"], ["trade2", "To set up a trading post"], ["explore", "Purely to explore new lands"]), correctId: "claim", explanation: "William claimed King Edward the Confessor had promised him the throne, and invaded when Harold was crowned instead." },
  { key: "mv-cause-3", topics: ["cause-effect"], difficulty: 2, prompt: "What was one major EFFECT of the Norman Conquest on England?", options: opt(["castles", "Norman lords built castles and took over the land"], ["nothing", "Nothing in England changed at all"], ["independence", "England became fully independent of any king"], ["language-loss", "The English language disappeared completely"]), correctId: "castles", explanation: "After 1066, Norman lords built castles across England and took control of much of the land and government." },
  { key: "mv-cause-4", topics: ["cause-effect"], difficulty: 2, prompt: "Why did people in the Stone Age gradually settle in one place instead of always moving to follow food?", options: opt(["farming", "They learned to farm - growing crops and keeping animals"], ["war", "They were forced to by an invading army"], ["metal", "They discovered how to make bronze"], ["writing", "They invented writing"]), correctId: "farming", explanation: "The shift to farming (the \"Neolithic Revolution\") let Stone Age people settle in villages instead of following wild food sources." },
  { key: "mv-cause-5", topics: ["cause-effect"], difficulty: 3, prompt: "What was one key EFFECT of the Industrial Revolution on where people lived in Britain?", options: opt(["urban", "Many people moved from the countryside into growing towns and cities"], ["rural", "Everyone moved out of towns into the countryside"], ["empty", "Britain's towns became empty"], ["no-change", "Where people lived stayed exactly the same"]), correctId: "urban", explanation: "New factories drew huge numbers of workers from rural areas into fast-growing industrial towns and cities." },
  { key: "mv-cause-6", topics: ["cause-effect"], difficulty: 3, prompt: "Why did the Anglo-Saxons begin settling in Britain in the 5th century AD?", options: opt(["after-romans", "Roman control of Britain had ended, leaving room for new settlers"], ["invited-vikings", "The Vikings invited them"], ["gold-rush", "They were searching for gold mines"], ["treaty", "A single peace treaty gave them the whole island"]), correctId: "after-romans", explanation: "After Roman forces withdrew (around AD 410), groups from what is now Germany, Denmark and the Netherlands settled in Britain over the following century." },
  { key: "mv-cause-7", topics: ["cause-effect"], difficulty: 2, prompt: "What was one EFFECT of Vikings settling in parts of England (like the area called the Danelaw)?", options: opt(["mixed-culture", "Norse words, place names and customs blended into English life"], ["no-effect", "It left no lasting mark on England at all"], ["end-farming", "All farming in England stopped"], ["new-continent", "England became part of a new continent"]), correctId: "mixed-culture", explanation: "Viking settlement left a lasting mark, including many English place names ending in -by or -thorpe and Norse-derived words." },
  { key: "mv-cause-8", topics: ["cause-effect"], difficulty: 2, prompt: "Why is Ancient Egypt often studied alongside the River Nile?", options: opt(["river-life", "The Nile's yearly flooding made farming possible in an otherwise dry desert"], ["unrelated", "The Nile has nothing to do with how Egyptians lived"], ["transport-only", "The river was only ever used for transport, never farming"], ["modern", "The Nile only became important in modern times"]), correctId: "river-life", explanation: "The Nile's predictable flooding deposited fertile silt each year, allowing farming that supported Ancient Egyptian civilisation in the desert." },
];
