// Behaviour banks — typical concerns, types and actions for activity / sports /
// holiday camps. All searchable and pre-filled, but every field also takes free
// text so staff can record anything not listed.

export const BEHAVIOUR_TYPES = [
  "Physical", "Verbal", "Defiance / non-compliance", "Disruption", "Unsafe behaviour",
  "Leaving the area", "Property / damage", "Bullying / unkindness", "Exclusion of others",
  "Poor sportsmanship", "Dishonesty", "Language / swearing", "Emotional / dysregulation",
  "Rough play", "Peer conflict", "Mealtime", "Online / device", "Other",
] as const;

export const BEHAVIOUR_CONCERNS = [
  "Not following instructions",
  "Refusing to join in the activity",
  "Rough play / play-fighting",
  "Pushing or shoving another child",
  "Hitting or kicking another child",
  "Biting",
  "Spitting",
  "Throwing equipment",
  "Damaging equipment on purpose",
  "Swearing / bad language",
  "Name-calling",
  "Teasing or mocking another child",
  "Excluding another child from a game",
  "Bullying (repeated unkindness)",
  "Unkind comments about appearance",
  "Answering back / rudeness to staff",
  "Ignoring a member of staff",
  "Shouting or screaming",
  "Disrupting the group / distracting others",
  "Running off / leaving the designated area",
  "Hiding from staff",
  "Refusing to line up",
  "Not staying with the group on a walk / trip",
  "Climbing on furniture or equipment unsafely",
  "Playing near a hazard after being warned",
  "Rough tackling in sport",
  "Deliberate foul play / cheating",
  "Arguing over rules or scoring",
  "Poor sportsmanship / sulking when losing",
  "Snatching equipment from others",
  "Not sharing equipment",
  "Queue-jumping",
  "Interfering with another child's belongings",
  "Taking something that isn't theirs",
  "Lying to staff about what happened",
  "Encouraging others to misbehave",
  "Refusing to tidy up",
  "Making a mess deliberately",
  "Refusing to wear required kit / sun cream",
  "Leaving the toilet area unsafe or messy",
  "Inappropriate language of a sexual nature",
  "Inappropriate physical contact with another child",
  "Homesickness leading to disruption",
  "Emotional outburst / meltdown",
  "Crying and unable to settle",
  "Self-isolating / refusing to engage",
  "Damage to the venue or property",
  "Throwing food at lunch",
  "Refusing to eat / mealtime disruption",
  "Phone or device use against the rules",
] as const;

export const BEHAVIOUR_ACTIONS = [
  "Verbal reminder",
  "Warning 1",
  "Warning 2",
  "Warning 3 (final)",
  "Time-out (5 minutes)",
  "Time-out (10 minutes)",
  "Reflection / quiet time",
  "Sat out of the activity",
  "Removed from the activity",
  "Restorative chat",
  "Apology (verbal)",
  "Apology letter",
  "Loss of a privilege",
  "Buddy / closer supervision",
  "1:1 chat with the child",
  "Spoke with the whole group",
  "Cooling-off walk",
  "Referred to the camp manager",
  "Parent phoned",
  "Parent informed at collection",
  "Behaviour plan started",
  "Reintegration meeting",
] as const;
