import { shuffleOptionIds, type QuizItem } from "../quiz/core";

// Story Detective - more short original mysteries (each written for this game, none taken from a published text), with inference, vocabulary-in-context and
// sequencing questions like the original four. Every case is gentle and ends kindly. Merged into DETECTIVE_ITEMS by content.ts; keys are `dt2_*`.
function q(key: string, passage: string, tag: "inference" | "vocab-in-context" | "sequencing", difficulty: 1 | 2 | 3, prompt: string, correct: string, wrongs: string[], explanation: string): QuizItem {
  const { options, correctId } = shuffleOptionIds(key, correct, wrongs);
  return { key, topics: [tag], difficulty, prompt, passage, options, correctId, explanation };
}
const KITE = "Just after the raffle at the school fair, Priya noticed that her blue kite had vanished from the prize stall. Her brother Dev insisted he had been reading beside it the whole time, but his book was open upside down on his knee. A line of small, muddy footprints led across the damp grass towards the pond. There, tangled in a low branch, hung the kite, its string looped around a half-eaten bag of crisps. Priya smiled. Dev disliked crisps, but their youngest cousin Noor never went anywhere without a packet.";
const BAKERY = "At half past five every morning, Mrs Hussain unlocked the bakery and found one warm roll missing from the cooling rack. For three days it happened. On the fourth evening she scattered a thin layer of flour on the floor by the back door and locked up as usual. When she arrived the next morning, tiny paw prints crossed the flour to the open window, and a ginger cat sat on the sill licking crumbs from its whiskers. “Well,” Mrs Hussain laughed, “that explains where my rolls have gone.”";
const BOOTS = "When Ms Lee’s class came back from the field trip, muddy boot prints covered the classroom floor and led to the paint cupboard. Only three pupils had stayed inside that morning: Sam, who wore trainers; Ivy, who wore wellies; and Jo, who wore sandals. The prints had a deep zigzag pattern, exactly like the sole of a welly, and beside the cupboard was a small puddle. Ivy’s face turned pink. “I only wanted to fetch the paints,” she said, “and I forgot to take my wellies off.”";
const WHISTLE = "On sports day, Mr Hart could not find his silver whistle. He had left it on a shelf in the shed, and the door was locked. The only opening was a small back window, which was open a crack, and beneath it stood a footstool that had not been there the day before. On the shelf, dust had been wiped from a small circle where the whistle used to sit, and a single blue thread was snagged on the window latch. Down at the track, the youngest referee, Mia, wore a blue cardigan with a torn sleeve. She blushed and pulled the whistle from her pocket. “I needed one for my drama club game,” she said, “and I didn’t want to bother you.”";
const SNOWMAN = "On Saturday morning, Kayla ran into the garden to find that her snowman had lost its carrot nose. Beside the snowman were tiny, four-toed prints in the snow, and a trail of orange crumbs led away across the lawn and under the hedge. Kayla crept closer and peeped underneath. A brown rabbit sat there, nibbling something orange with great concentration. It twitched its nose at her and did not run away.";
const VIOLIN = "Ten minutes before the school concert, Ravi’s violin case was empty. He searched the music room, the cloakroom and the hall. Then he remembered that he had swapped seats with Anika on the school bus that morning. He hurried out to the bus, where Anika sat in the driver’s seat pretending to steer. Tucked safely under her coat was his violin. “I’ve been guarding it all day,” she said, “so that it didn’t get squashed by everyone’s bags.”";
export const DETECTIVE_EXTRA: QuizItem[] = [
  q("dt2_k1", KITE, "inference", 2, "What does the upside-down book suggest about Dev?", "He was probably not really reading it.", ["He can only read upside down.", "He did not like the kite.", "He is much younger than Priya."], "If he had really been reading, the book would be the right way up, so Priya doubts his story."),
  q("dt2_k2", KITE, "vocab-in-context", 1, "In this passage, what does “tangled” mean?", "Twisted together in a knot.", ["Painted bright blue.", "Broken in half.", "Very far away."], "The string of the kite was looped and twisted around the branch and the crisps."),
  q("dt2_k3", KITE, "sequencing", 2, "What happens straight AFTER Priya follows the footprints across the grass?", "She finds the kite in a low branch by the pond.", ["She notices the kite has vanished.", "She sees that Dev’s book is upside down.", "She hears the raffle being drawn."], "The footprints lead to the pond, and there she finds the kite hanging from the branch."),
  q("dt2_k4", KITE, "inference", 3, "Who does Priya now suspect took the kite, and why?", "Noor, because of the crisps she always carries.", ["Dev, because he disliked crisps.", "The raffle organisers, because they had the prizes.", "Nobody, because the kite blew away."], "The crisps are the clue: Dev disliked them, but Noor never went anywhere without a packet."),
  q("dt2_b1", BAKERY, "inference", 1, "Why did Mrs Hussain scatter flour by the back door?", "So that she could see the footprints of whoever came in.", ["To bake a bigger cake.", "To keep the floor clean.", "To scare the visitor away."], "A layer of flour shows every print, so it works like a trap for clues."),
  q("dt2_b2", BAKERY, "vocab-in-context", 1, "In this passage, what does “scattered” mean?", "Spread about in different places.", ["Locked away safely.", "Cooked until golden.", "Thrown very hard."], "She sprinkled the flour thinly across the floor."),
  q("dt2_b3", BAKERY, "sequencing", 2, "What happens FIRST in the passage?", "Mrs Hussain finds a roll missing from the cooling rack.", ["She spreads flour on the floor.", "She sees paw prints leading to the window.", "She laughs and says where the rolls have gone."], "The missing roll is what starts the mystery, over three mornings, before she sets her trap."),
  q("dt2_b4", BAKERY, "inference", 2, "What can we work out from the paw prints and the crumbs on the cat’s whiskers?", "The cat had been taking the rolls.", ["The cat had been guarding the bakery.", "The cat belonged to Mrs Hussain.", "The cat was afraid of flour."], "The prints lead to the window and the cat has crumbs on its whiskers, so it is the likely culprit."),
  q("dt2_m1", BOOTS, "inference", 1, "How do we know the boot prints were made by Ivy?", "The zigzag pattern matched the sole of a welly, and she was the one wearing wellies.", ["Ivy was the tallest pupil.", "The prints were very small.", "Ivy was the only one in the classroom."], "Sam wore trainers and Jo wore sandals. Only wellies leave a deep zigzag print."),
  q("dt2_m2", BOOTS, "vocab-in-context", 2, "In this passage, what does “zigzag” describe?", "A line that keeps turning sharply one way, then the other.", ["A very straight line.", "A pattern of circles.", "A colour like pink."], "A zigzag goes back and forth like the letter Z."),
  q("dt2_m3", BOOTS, "sequencing", 2, "What happens LAST in the passage?", "Ivy explains why she had walked in wearing wellies.", ["The class comes back from the trip.", "Ms Lee compares the pattern of the prints.", "The prints are found leading to the cupboard."], "The class finds the prints first, and Ivy’s explanation comes at the very end."),
  q("dt2_m4", BOOTS, "inference", 3, "Why does Ivy’s face turn pink?", "She is embarrassed that she left the mess.", ["She is angry with Sam.", "She has been running.", "She is proud of the paintings."], "Her explanation shows she made the mistake by accident and feels awkward about it."),
  q("dt2_w1", WHISTLE, "inference", 2, "How did the person who took the whistle get into the shed?", "Through the small back window, using the footstool.", ["With a key from the head teacher.", "By breaking the door.", "By waiting until the shed was open."], "The door was locked, but the back window was open a crack and a new footstool stood beneath it."),
  q("dt2_w2", WHISTLE, "vocab-in-context", 2, "In this passage, what does “snagged” mean?", "Caught on something rough.", ["Washed clean.", "Lost for ever.", "Sewn on tightly."], "A thread that is snagged has caught on the latch and been left behind."),
  q("dt2_w3", WHISTLE, "sequencing", 2, "What does Mr Hart notice LAST before Mia speaks?", "The youngest referee is wearing a blue cardigan with a torn sleeve.", ["The footstool under the window.", "The dust wiped from the shelf.", "The blue thread on the latch."], "He gathers clues in the shed first, then sees Mia’s cardigan down at the track."),
  q("dt2_w4", WHISTLE, "inference", 3, "Why does the blue thread matter to the mystery?", "It matches Mia’s cardigan and shows she came through the window.", ["It proves the whistle is made of wool.", "It shows Mr Hart is untidy.", "It means the shed was painted blue."], "The thread on the latch and the torn sleeve link Mia to the window."),
  q("dt2_s1", SNOWMAN, "inference", 1, "Who took the snowman’s carrot nose?", "A rabbit.", ["A neighbour.", "The wind.", "Kayla’s brother."], "Four-toed prints, orange crumbs and a rabbit nibbling something orange all point to the rabbit."),
  q("dt2_s2", SNOWMAN, "vocab-in-context", 1, "In this passage, what does “trail” mean?", "A line of marks left behind by something moving.", ["A bright light.", "A loud noise.", "A kind of snow."], "A trail is the path of crumbs left across the lawn."),
  q("dt2_s3", SNOWMAN, "sequencing", 1, "What led Kayla to look under the hedge?", "The trail of orange crumbs.", ["A loud noise from the shed.", "The rabbit running away.", "A note from her friend."], "She followed the trail of orange crumbs across the lawn and under the hedge."),
  q("dt2_s4", SNOWMAN, "inference", 2, "What does the rabbit’s behaviour at the end suggest about it?", "It was not frightened of Kayla.", ["It was very angry.", "It wanted her to leave.", "It was already full of carrots."], "It twitched its nose and did not run away, so it felt safe."),
  q("dt2_v1", VIOLIN, "inference", 2, "Why had Anika taken Ravi’s violin?", "To keep it safe from being squashed.", ["She wanted to play it herself.", "She was hiding it as a joke.", "She had lost her own."], "She says she was guarding it all day so it would not get squashed by the school bags."),
  q("dt2_v2", VIOLIN, "vocab-in-context", 1, "In this passage, what does “guarding” mean?", "Watching over something to keep it safe.", ["Hiding something on purpose.", "Playing music loudly.", "Throwing something away."], "Anika kept the violin under her coat so that no harm could come to it."),
  q("dt2_v3", VIOLIN, "sequencing", 2, "What did Ravi do just BEFORE he hurried out to the bus?", "He remembered swapping seats with Anika.", ["He found the violin under a coat.", "He searched the cloakroom for the third time.", "He heard Anika pretending to steer."], "After searching, he remembered the seat swap, which sent him to the bus."),
  q("dt2_v4", VIOLIN, "inference", 3, "Why did remembering the seat swap make Ravi go to the bus?", "It made him think Anika might know where the violin was.", ["He wanted to go home.", "The concert was being held on the bus.", "He had left his coat there."], "He had sat with Anika on the way in, so she was the person most likely to have seen his violin."),
];
