import { shuffleOptionIds, type QuizItem } from "../quiz/core";
import { DETECTIVE_EXTRA } from "./content.extra";

// STORY DETECTIVE — reading comprehension / inference. Four original, wholly public-domain-style short mysteries
// (never anything copyrighted or attributable to a specific publisher), each with a small set of questions covering
// inference, vocabulary-in-context and sequencing. Same seeded-item-bank mechanic as the other quiz-quest games —
// `passage` is the one addition to QuizItem (features/learninghub/games/quiz/core.ts) so several items can share
// the same reading text without repeating it in every `prompt`.
const PASSAGE_LIGHTHOUSE = "The lighthouse on Gull Point had not shone in three nights, and Mira knew the fishing boats would be late coming in. She climbed the two hundred and six steps with her grandfather's old lamp-oil can, her breath clouding in the cold stairwell. At the top, the great lens sat dark and dusty, and beside it lay a torn glove, far too small to belong to the keeper. Mira's stomach tightened. She had seen that glove before — sewn from a red scarf — on the hands of Tomkin, the baker's boy, who had sworn only that morning that he'd never once set foot near the lighthouse. She lit the lamp with trembling hands, and as light spilled out across the black water, she noticed the keeper's logbook lying open to a page that had been ripped clean out.";
const PASSAGE_ORCHARD = "Every autumn, old Mrs Featherstone counted her apples before the harvest festival, and every autumn the count came out exactly the same: four hundred and twelve. This year, though, she counted four hundred and three. Nine apples, gone without a trace, and not a single one lying rotten on the ground. She noticed the low branch by the garden wall had been bent almost double, as if something heavy had rested on it recently, and a scattering of small, muddy footprints — barefoot, and far too small for any grown-up — led away towards the old well. Mrs Featherstone smiled slightly despite herself. She hadn't seen footprints like those since her own grandchildren were small enough to fit through the gap in the orchard fence.";
const PASSAGE_TRAIN = "The 6:15 to Fenbridge was never late, which is exactly why Constable Rao noticed it standing motionless at the signal for eleven minutes. When she finally boarded, the carriages were empty except for a single suitcase, sitting upright in the luggage rack, its label torn so only the letter “R” remained. The guard swore he'd checked every carriage at the last stop and found nothing unusual. But Rao noticed the emergency cord in carriage three had a fresh, bright red mark where a hand had gripped it hard, and the window beside it was unlatched, letting in a thin whistle of cold air. Whoever had pulled that cord, she thought, had left in a hurry — and not through a door.";
const PASSAGE_ISLAND = "When the tide pulled back from Cormorant Bay each morning, it left behind a strip of wet sand that nobody was supposed to cross before the coastguard's flag went up. Jonah crossed it anyway, chasing the glint of something metal half-buried near the rocks. It turned out to be an old brass compass, its glass cracked, its needle frozen pointing due west no matter which way he turned it. Scratched into the case were three letters that weren't his grandfather's initials, and a date from nineteen years before Jonah was even born. He turned it over once more and noticed, tucked beneath the compass in the sand, a folded scrap of oilcloth map, its edges too clean and dry to have been buried for very long at all.";

function q(key: string, passage: string, tag: "inference" | "vocab-in-context" | "sequencing", difficulty: 1 | 2 | 3, prompt: string, correct: string, wrongs: string[], explanation: string): QuizItem {
  const { options, correctId } = shuffleOptionIds(key, correct, wrongs);
  return { key, topics: [tag], difficulty, prompt, passage, options, correctId, explanation };
}

const DETECTIVE_BASE: QuizItem[] = [
  q("dt_lh1", PASSAGE_LIGHTHOUSE, "inference", 1, "Why does Mira's stomach tighten when she sees the glove?", "She realises it belongs to Tomkin, who lied about being near the lighthouse.", ["She is afraid of the dark stairwell.", "She dropped her grandfather's lamp-oil can.", "She is worried about the fishing boats."], "The text says she recognised the glove as Tomkin's and remembers he'd ‘sworn... he'd never once set foot near the lighthouse’ — the inference is that he lied."),
  q("dt_lh2", PASSAGE_LIGHTHOUSE, "vocab-in-context", 1, "In this passage, what does “stairwell” most likely mean?", "The enclosed space containing a staircase.", ["A type of old lamp.", "A small boat.", "A page torn from a book."], "“stairwell” describes an enclosed space with stairs in it — Mira is climbing 206 steps inside it, and her breath is clouding, which fits a narrow, cold, enclosed space."),
  q("dt_lh3", PASSAGE_LIGHTHOUSE, "sequencing", 2, "What happens LAST in this passage?", "Mira notices a page has been torn from the logbook.", ["Mira climbs the two hundred and six steps.", "Mira finds a torn glove by the lens.", "Mira lights the lamp."], "The events in order are: climb the steps, find the glove, light the lamp, then finally notice the torn page — the last thing mentioned."),
  q("dt_or1", PASSAGE_ORCHARD, "inference", 1, "What does the passage suggest actually took the apples?", "Children, based on the small barefoot footprints.", ["A large animal, based on the bent branch alone.", "Nobody — Mrs Featherstone miscounted.", "The wind blew them off the tree."], "Small, barefoot footprints — and Mrs Featherstone's memory of her own grandchildren — point to children, not an animal or a mistake."),
  q("dt_or2", PASSAGE_ORCHARD, "vocab-in-context", 1, "In this passage, what does “without a trace” mean?", "Leaving no visible sign or evidence behind.", ["Very slowly, over a long time.", "By using a special tool.", "In front of witnesses."], "“without a trace” means nothing was left behind to show what happened — here, no rotten apples or obvious signs, until the footprints were spotted."),
  q("dt_or3", PASSAGE_ORCHARD, "sequencing", 2, "What does Mrs Featherstone notice SECOND, right after the apple count?", "The bent low branch by the garden wall.", ["The muddy footprints leading to the well.", "That she smiled despite herself.", "Memories of her grandchildren."], "After the count, the passage says she ‘noticed the low branch’ first among the clues, and only then the footprints."),
  q("dt_tr1", PASSAGE_TRAIN, "inference", 2, "What does the text imply happened to whoever pulled the emergency cord?", "They left the train quickly through the unlatched window, not through a door.", ["They are still hiding somewhere on the train.", "They were the guard who checked the carriages.", "They never actually pulled the cord."], "The unlatched window letting in cold air, right beside the freshly-gripped cord, and the final line ‘not through a door’ all point to an exit through the window."),
  q("dt_tr2", PASSAGE_TRAIN, "vocab-in-context", 1, "In this passage, “motionless” most nearly means", "Not moving at all.", ["Travelling very fast.", "Making a loud noise.", "Full of passengers."], "“motionless” describes the train standing still at the signal for eleven minutes — the opposite of moving."),
  q("dt_tr3", PASSAGE_TRAIN, "sequencing", 2, "Which happens FIRST in the passage?", "Constable Rao notices the train has stopped for eleven minutes.", ["She finds the suitcase in the luggage rack.", "She notices the mark on the emergency cord.", "She notices the unlatched window."], "The passage opens with Rao noticing how long the train had been stopped, before she boards and finds anything inside."),
  q("dt_is1", PASSAGE_ISLAND, "inference", 3, "What does the passage suggest about the folded map?", "It was placed there recently, not buried for years like the compass.", ["It is older than the compass.", "It belongs to Jonah's grandfather.", "It was washed up by the tide that morning."], "The map's edges are described as ‘too clean and dry to have been buried for very long’ — unlike the compass, which shows real age."),
  q("dt_is2", PASSAGE_ISLAND, "vocab-in-context", 2, "In this passage, what does “half-buried” suggest about the compass?", "Part of it was covered by sand and part was visible.", ["It was cut exactly in half.", "It was underwater.", "It had been recently painted."], "“half-buried” means partly covered — Jonah could see a ‘glint of something metal’, which is why he noticed it at all."),
  q("dt_is3", PASSAGE_ISLAND, "sequencing", 3, "What does Jonah do immediately after noticing the compass points due west no matter how he turns it?", "He notices the scratched letters and the date on the case.", ["He crosses the wet sand.", "He finds the oilcloth map.", "The coastguard's flag goes up."], "After noticing the strange needle, the very next thing described is the scratched letters and date on the case — the map is found only after that."),
];

/** The original bank plus the extra items (content.extra.ts): the original four cases plus six more. */
export const DETECTIVE_ITEMS: QuizItem[] = [...DETECTIVE_BASE, ...DETECTIVE_EXTRA];
