// Colour Lab content bank - KS2/KS3 science: light, colour mixing (light vs pigment), and the basic physics of
// colour and vision. Content rule for THIS game specifically (see task brief): green may appear as CONTENT - a
// colour being taught or mixed - but must never be used as the game's own UI/brand chrome colour (enforced in the
// theme file, not here). Facts below are standard KS2 "light" and KS3 "waves"/"light" curriculum content (primary
// vs secondary colours, additive vs subtractive mixing, why objects look coloured, basic wavelength ordering).
// Server and client share this exact file (BACKEND-PATTERN.md).
import type { QuizItem } from "../quiz/core";
import { COLOUR_EXTRA } from "./content.extra";

const opt = (...pairs: [string, string][]) => pairs.map(([id, text]) => ({ id, text }));

const COLOUR_BASE: QuizItem[] = [
  // ── light basics ─────────────────────────────────────────────────────────────────────────────────────────────
  { key: "cl-light-1", topics: ["light"], difficulty: 1, prompt: "What do we call something that gives out its own light, like the Sun or a lamp?", options: opt(["source", "A light source"], ["reflector", "A reflector"], ["shadow", "A shadow"], ["lens", "A lens"]), correctId: "source", explanation: "A light source produces its own light, unlike the Moon, which only reflects sunlight." },
  { key: "cl-light-2", topics: ["light"], difficulty: 1, prompt: "Why can we see most everyday objects, like a book or a chair?", options: opt(["reflect", "Light bounces (reflects) off them into our eyes"], ["glow", "They glow with their own light"], ["invisible", "We can't actually see them without a torch"], ["sound", "Sound waves let us see them"]), correctId: "reflect", explanation: "Most objects are not light sources - we see them because light reflects off their surface and enters our eyes." },
  { key: "cl-light-3", topics: ["light"], difficulty: 1, prompt: "What is formed when an opaque object blocks light?", options: opt(["shadow", "A shadow"], ["reflection", "A reflection"], ["rainbow", "A rainbow"], ["spectrum", "A spectrum"]), correctId: "shadow", explanation: "An opaque object blocks light from passing through, creating a dark shadow behind it." },
  { key: "cl-light-4", topics: ["light"], difficulty: 2, prompt: "What travels in straight lines from a light source, letting shadows form with sharp edges?", options: opt(["light-rays", "Light rays"], ["sound-waves", "Sound waves"], ["heat-only", "Heat, but not light"], ["gravity", "Gravity"]), correctId: "light-rays", explanation: "Light travels in straight lines (rays); this is why shadows have sharp, predictable edges." },
  { key: "cl-light-5", topics: ["light"], difficulty: 2, prompt: "What word describes a material that light can pass straight through, like clear glass?", options: opt(["transparent", "Transparent"], ["opaque", "Opaque"], ["translucent", "Translucent"], ["reflective", "Reflective"]), correctId: "transparent", explanation: "Transparent materials let almost all light pass through, so you can see clearly through them." },
  { key: "cl-light-6", topics: ["light"], difficulty: 2, prompt: "What word describes a material that lets SOME light through but scatters it, like frosted glass?", options: opt(["translucent", "Translucent"], ["transparent", "Transparent"], ["opaque", "Opaque"], ["luminous", "Luminous"]), correctId: "translucent", explanation: "Translucent materials let some light through but scatter it, so objects behind look blurry, not sharp." },
  { key: "cl-light-7", topics: ["light"], difficulty: 1, prompt: "What word describes a material that blocks all light, like wood or metal?", options: opt(["opaque", "Opaque"], ["transparent", "Transparent"], ["translucent", "Translucent"], ["luminous2", "Luminous"]), correctId: "opaque", explanation: "Opaque materials block light completely, so nothing can be seen through them." },

  // ── mixing coloured light (additive) ─────────────────────────────────────────────────────────────────────────
  { key: "cl-add-1", topics: ["light-mixing"], difficulty: 1, prompt: "In MIXING LIGHT, what are the three primary colours?", options: opt(["rgb", "Red, green and blue"], ["ryb", "Red, yellow and blue"], ["cmy", "Cyan, magenta and yellow"], ["rgy", "Red, grey and yellow"]), correctId: "rgb", explanation: "For light, the primary colours are red, green and blue (RGB) - this is how screens and stage lights work." },
  { key: "cl-add-2", topics: ["light-mixing"], difficulty: 2, prompt: "When you shine RED light and GREEN light on top of each other, what colour do you see?", options: opt(["yellow", "Yellow"], ["purple", "Purple"], ["black", "Black"], ["blue", "Blue"]), correctId: "yellow", explanation: "Mixing red and green LIGHT produces yellow light - light mixing works differently from mixing paint." },
  { key: "cl-add-3", topics: ["light-mixing"], difficulty: 2, prompt: "When you shine RED light and BLUE light on top of each other, what colour do you see?", options: opt(["magenta", "Magenta (a pinkish-purple)"], ["green", "Green"], ["yellow", "Yellow"], ["white", "White"]), correctId: "magenta", explanation: "Red light plus blue light produces magenta." },
  { key: "cl-add-4", topics: ["light-mixing"], difficulty: 2, prompt: "When you shine GREEN light and BLUE light on top of each other, what colour do you see?", options: opt(["cyan", "Cyan (a blue-green)"], ["yellow", "Yellow"], ["magenta", "Magenta"], ["orange", "Orange"]), correctId: "cyan", explanation: "Green light plus blue light produces cyan." },
  { key: "cl-add-5", topics: ["light-mixing"], difficulty: 2, prompt: "What colour do you get when you mix ALL THREE primary colours of light (red, green and blue) together?", options: opt(["white", "White light"], ["black", "Black"], ["grey", "Grey only"], ["brown", "Brown"]), correctId: "white", explanation: "Mixing red, green and blue light at full brightness produces white light - this is called additive mixing." },
  { key: "cl-add-6", topics: ["light-mixing"], difficulty: 3, prompt: "Why is mixing coloured LIGHT called \"additive\" mixing?", options: opt(["adds-light", "Because each colour you add makes the mix brighter, moving towards white"], ["adds-paint", "Because you add drops of paint together"], ["removes-light", "Because each colour you add removes light"], ["random", "There is no real reason, it's just a name"]), correctId: "adds-light", explanation: "Additive mixing adds more light together, so the result gets brighter and closer to white - the opposite of mixing paint." },
  { key: "cl-add-7", topics: ["light-mixing"], difficulty: 2, prompt: "A television or phone screen makes every colour you see using pixels of which THREE colours?", options: opt(["rgb", "Red, green and blue"], ["ryb", "Red, yellow and blue"], ["cmyk", "Cyan, magenta, yellow and black"], ["bw", "Black and white only"]), correctId: "rgb", explanation: "Screens use tiny red, green and blue sub-pixels, mixed by your eye, to create every colour you see." },

  // ── mixing paint / pigment (subtractive) ────────────────────────────────────────────────────────────────────
  { key: "cl-sub-1", topics: ["pigment-mixing"], difficulty: 1, prompt: "In MIXING PAINT, what are the three primary colours?", options: opt(["ryb", "Red, yellow and blue"], ["rgb", "Red, green and blue"], ["cmy", "Cyan, magenta and yellow"], ["ryg", "Red, yellow and green"]), correctId: "ryb", explanation: "For paint (traditionally taught in primary school), the primary colours are red, yellow and blue." },
  { key: "cl-sub-2", topics: ["pigment-mixing"], difficulty: 1, prompt: "What colour do you get by mixing BLUE and YELLOW paint?", options: opt(["green", "Green"], ["orange", "Orange"], ["purple", "Purple"], ["brown", "Brown"]), correctId: "green", explanation: "Blue and yellow paint mixed together makes green." },
  { key: "cl-sub-3", topics: ["pigment-mixing"], difficulty: 1, prompt: "What colour do you get by mixing RED and YELLOW paint?", options: opt(["orange", "Orange"], ["green", "Green"], ["purple", "Purple"], ["brown2", "Brown"]), correctId: "orange", explanation: "Red and yellow paint mixed together makes orange." },
  { key: "cl-sub-4", topics: ["pigment-mixing"], difficulty: 1, prompt: "What colour do you get by mixing RED and BLUE paint?", options: opt(["purple", "Purple"], ["green", "Green"], ["orange", "Orange"], ["yellow", "Yellow"]), correctId: "purple", explanation: "Red and blue paint mixed together makes purple (violet)." },
  { key: "cl-sub-5", topics: ["pigment-mixing"], difficulty: 2, prompt: "Green, orange and purple are called what kind of colours, because they're each made from two primaries?", options: opt(["secondary", "Secondary colours"], ["primary", "Primary colours"], ["neutral", "Neutral colours"], ["complementary2", "Complementary colours only"]), correctId: "secondary", explanation: "Secondary colours (green, orange, purple) are made by mixing two primary colours together." },
  { key: "cl-sub-6", topics: ["pigment-mixing"], difficulty: 3, prompt: "Why is mixing PAINT called \"subtractive\" mixing?", options: opt(["absorbs-light", "Because each pigment absorbs (subtracts) some colours of light, reflecting only the rest"], ["adds-light", "Because it adds light together like a screen"], ["removes-paint", "Because you take paint away from the pot"], ["no-reason", "It's just a traditional name with no real meaning"]), correctId: "absorbs-light", explanation: "Paint pigments absorb some wavelengths of light and reflect the rest; mixing more pigments absorbs more light, so mixes get darker - the opposite of mixing light." },
  { key: "cl-sub-7", topics: ["pigment-mixing"], difficulty: 2, prompt: "What usually happens if you keep mixing lots of different paint colours together?", options: opt(["muddy-brown", "You get a dark, muddy brown or grey"], ["white", "You get pure white"], ["brighter", "The mix gets brighter and brighter"], ["clear", "The paint becomes clear/transparent"]), correctId: "muddy-brown", explanation: "Unlike mixing light (which gets brighter), mixing many paints absorbs more and more light, usually ending up as a dark, muddy colour." },

  // ── why objects look coloured / vision ───────────────────────────────────────────────────────────────────────
  { key: "cl-vis-1", topics: ["vision"], difficulty: 2, prompt: "Sunlight looks white, but it is actually made up of what?", options: opt(["all-colours", "All the colours of the rainbow, mixed together"], ["one-colour", "Just one colour of light"], ["no-colour", "No colour at all - light has no colour"], ["black-light", "Invisible black light"]), correctId: "all-colours", explanation: "White light from the Sun is a mixture of all the colours of the visible spectrum." },
  { key: "cl-vis-2", topics: ["vision"], difficulty: 2, prompt: "A red apple looks red in white light because...", options: opt(["reflects-red", "It reflects red light and absorbs the other colours"], ["makes-red", "It makes its own red light"], ["absorbs-red", "It absorbs red light and reflects everything else"], ["no-light", "It blocks all light completely"]), correctId: "reflects-red", explanation: "The apple's skin reflects red wavelengths back to your eye and absorbs the other colours of white light." },
  { key: "cl-vis-3", topics: ["vision"], difficulty: 3, prompt: "What colour would a red apple appear if you shone ONLY pure blue light on it, with no other light present?", options: opt(["black", "Black (or very dark)"], ["red", "Still bright red"], ["purple", "Purple"], ["white", "White"]), correctId: "black", explanation: "The apple can only reflect the colours of light shining on it; with no red light present to reflect, it looks black/very dark." },
  { key: "cl-vis-4", topics: ["vision"], difficulty: 2, prompt: "What splits white light into a rainbow of colours, like a prism does?", options: opt(["refraction", "Bending (refracting) each colour by a different amount"], ["absorption", "Absorbing all the light"], ["reflection-only", "Simple mirror reflection"], ["shadow-forming", "Blocking the light to form a shadow"]), correctId: "refraction", explanation: "A prism refracts (bends) each wavelength of light by a slightly different amount, spreading white light into a spectrum." },
  { key: "cl-vis-5", topics: ["vision"], difficulty: 3, prompt: "Put these rainbow colours in the correct order, starting from RED: which comes right after red?", options: opt(["orange", "Orange"], ["blue", "Blue"], ["violet", "Violet"], ["green", "Green"]), correctId: "orange", explanation: "The visible spectrum in order is red, orange, yellow, green, blue, indigo, violet (\"ROYGBIV\")." },
  { key: "cl-vis-6", topics: ["vision"], difficulty: 3, prompt: "In the rainbow spectrum, which colour of visible light has the LONGEST wavelength?", options: opt(["red", "Red"], ["violet", "Violet"], ["green", "Green"], ["blue", "Blue"]), correctId: "red", explanation: "Red light has the longest wavelength of the visible spectrum; violet has the shortest." },
  { key: "cl-vis-7", topics: ["vision"], difficulty: 3, prompt: "In the rainbow spectrum, which colour of visible light has the SHORTEST wavelength?", options: opt(["violet", "Violet"], ["red", "Red"], ["yellow", "Yellow"], ["orange", "Orange"]), correctId: "violet", explanation: "Violet light has the shortest wavelength of the visible spectrum; red has the longest." },
  { key: "cl-vis-8", topics: ["vision"], difficulty: 2, prompt: "A pane of clear glass looks colourless because it...", options: opt(["transmits-all", "Lets almost all colours of light pass straight through"], ["absorbs-all", "Absorbs almost all colours of light"], ["reflects-all", "Reflects almost all colours back"], ["makes-light", "Produces its own white light"], ), correctId: "transmits-all", explanation: "Clear glass is transparent - it transmits nearly all wavelengths of visible light through it rather than absorbing or reflecting them." },
  { key: "cl-vis-9", topics: ["vision"], difficulty: 2, prompt: "What colour does an object appear if it reflects ALL colours of light equally?", options: opt(["white", "White"], ["black", "Black"], ["grey-only", "It can only ever look grey"], ["invisible", "Invisible"]), correctId: "white", explanation: "An object that reflects all wavelengths of visible light equally appears white." },
  { key: "cl-vis-10", topics: ["vision"], difficulty: 2, prompt: "What colour does an object appear if it absorbs ALL colours of light and reflects almost none?", options: opt(["black", "Black"], ["white", "White"], ["red2", "Red"], ["clear", "Completely clear/invisible"]), correctId: "black", explanation: "An object that absorbs nearly all light and reflects very little appears black." },

  // ── eyes and coloured filters ────────────────────────────────────────────────────────────────────────────────
  { key: "cl-eye-1", topics: ["vision"], difficulty: 2, prompt: "Which part of the eye has special cells that detect colour and light?", options: opt(["retina", "The retina"], ["pupil", "The pupil"], ["eyelid", "The eyelid"], ["eyebrow", "The eyebrow"]), correctId: "retina", explanation: "The retina, at the back of the eye, contains light-sensitive cells (rods and cones) that detect light and colour." },
  { key: "cl-eye-2", topics: ["vision"], difficulty: 3, prompt: "What are the light-detecting cells in the eye that respond to colour called?", options: opt(["cones", "Cones"], ["rods", "Rods"], ["lenses", "Lenses"], ["irises", "Irises"]), correctId: "cones", explanation: "Cone cells in the retina detect colour; rod cells detect light and dark but not colour." },
  { key: "cl-eye-3", topics: ["light-mixing"], difficulty: 2, prompt: "If you look at a white shirt through a RED plastic filter, what colour does it appear?", options: opt(["red3", "Red"], ["green3", "Green"], ["blue3", "Blue"], ["black3", "Black"]), correctId: "red3", explanation: "A red filter only lets red light through, so a white (all-colour) surface seen through it looks red." },
  { key: "cl-eye-4", topics: ["light-mixing"], difficulty: 3, prompt: "If you look at a pure RED object through a BLUE filter (which only lets blue light through), what would you most likely see?", options: opt(["very-dark", "The object looking very dark or black"], ["bright-red", "The object looking brighter red"], ["purple4", "The object looking bright purple"], ["unchanged", "No change at all"]), correctId: "very-dark", explanation: "A blue filter blocks red light; since the red object has almost no blue light to reflect through the filter, it appears very dark." },
];

/** The original bank plus the extra items (content.extra.ts): 100+ items. */
export const COLOUR_ITEMS: QuizItem[] = [...COLOUR_BASE, ...COLOUR_EXTRA];
