import { shuffleOptionIds, type QuizItem } from "../quiz/core";

// Word Pop - more quick-fire spelling: homophones (choose the word that fits the sentence), tricky "exception" words, and spelling patterns (-tion / -sion / -cian,
// -ough, doubling, suffixes, prefixes, silent letters). British English spellings throughout; the wrong options are the mistakes children really make. Every sentence
// has exactly one option that fits. Merged into WORDPOP_ITEMS by content.ts; keys are `sp2_*`.
function sp(key: string, topic: "homophone" | "exception" | "pattern", difficulty: 1 | 2 | 3, sentence: string, correct: string, wrongs: string[], explanation: string): QuizItem {
  const { options, correctId } = shuffleOptionIds(key, correct, wrongs);
  return { key, topics: ["spelling", topic], difficulty, prompt: sentence, options, correctId, explanation };
}
export const WORDPOP_EXTRA: QuizItem[] = [
  // ── homophones ─────────────────────────────────────────────────────────────────────────────────────────────────
  sp("sp2_h1", "homophone", 1, "The ___ fell softly on the roof.", "rain", ["reign", "rein"], "“rain” is water falling from clouds. “reign” is a ruler’s time in power and “rein” is a strap for steering a horse."),
  sp("sp2_h2", "homophone", 2, "The queen’s long ___ lasted fifty years.", "reign", ["rain", "rein"], "“reign” means the time a king or queen rules."),
  sp("sp2_h3", "homophone", 3, "Pull gently on the ___ to steer the horse.", "rein", ["rain", "reign"], "A “rein” is a strap used to guide a horse."),
  sp("sp2_h4", "homophone", 1, "A ___ of cheese was left on the plate.", "piece", ["peace", "peice"], "“piece” is a part of something. Remember: a piece of pie."),
  sp("sp2_h5", "homophone", 2, "Everyone wished for world ___.", "peace", ["piece", "pease"], "“peace” means calm and no fighting."),
  sp("sp2_h6", "homophone", 1, "Please ___ your name at the top of the page.", "write", ["right", "rite"], "“write” is what you do with a pen. The w is silent."),
  sp("sp2_h7", "homophone", 1, "Turn ___ at the traffic lights.", "right", ["write", "rite"], "“right” can mean the opposite of left, or correct."),
  sp("sp2_h8", "homophone", 1, "The ___ was shining brightly.", "sun", ["son", "sunn"], "“sun” is the star at the centre of our solar system."),
  sp("sp2_h9", "homophone", 1, "Her ___ is learning to swim.", "son", ["sun", "sonn"], "“son” is a boy or man in relation to his parents."),
  sp("sp2_h10", "homophone", 2, "I ___ the answer before she said it.", "knew", ["new", "gnu"], "“knew” is the past tense of “know”, with a silent k."),
  sp("sp2_h11", "homophone", 1, "She bought a ___ jacket for the winter.", "new", ["knew", "gnu"], "“new” is the opposite of old."),
  sp("sp2_h12", "homophone", 1, "I can ___ the birds singing outside.", "hear", ["here", "hare"], "You “hear” with your ear, and both words contain “ear”."),
  sp("sp2_h13", "homophone", 1, "Come over ___ and sit down.", "here", ["hear", "hare"], "“here” is a place, the opposite of “there”. Both end in “ere”."),
  sp("sp2_h14", "homophone", 2, "The ___ of the suitcase was over twenty kilos.", "weight", ["wait", "wate"], "“weight” is how heavy something is."),
  sp("sp2_h15", "homophone", 1, "Please ___ for me by the gate.", "wait", ["weight", "wate"], "“wait” means to stay until something happens."),
  sp("sp2_h16", "homophone", 1, "The wind ___ the door shut.", "blew", ["blue", "blewe"], "“blew” is the past tense of “blow”."),
  sp("sp2_h17", "homophone", 1, "The sky was a bright, cloudless ___.", "blue", ["blew", "bloo"], "“blue” is a colour."),
  sp("sp2_h18", "homophone", 1, "There was a big ___ in the road.", "hole", ["whole", "hoal"], "A “hole” is an opening or gap."),
  sp("sp2_h19", "homophone", 2, "I ate the ___ cake by myself.", "whole", ["hole", "hoal"], "“whole” means all of something. It starts with a w."),
  sp("sp2_h20", "homophone", 2, "The horse munched some ___ in the barn.", "hay", ["hey", "hai"], "“hay” is dried grass used to feed animals."),
  sp("sp2_h21", "homophone", 2, "Yesterday I ___ my bike to school.", "rode", ["road", "rowed"], "“rode” is the past tense of “ride”."),
  sp("sp2_h22", "homophone", 1, "We drove along the quiet country ___.", "road", ["rode", "rowd"], "A “road” is a path for vehicles."),
  sp("sp2_h23", "homophone", 2, "She used ___ and water to make the dough.", "flour", ["flower", "floor"], "“flour” is ground grain used for baking."),
  sp("sp2_h24", "homophone", 1, "A red ___ grew beside the garden gate.", "flower", ["flour", "flowre"], "A “flower” is the colourful part of a plant."),
  sp("sp2_h25", "homophone", 1, "We saw a huge brown ___ at the zoo.", "bear", ["bare", "bair"], "A “bear” is a large animal."),
  sp("sp2_h26", "homophone", 2, "The trees were ___ in the middle of winter.", "bare", ["bear", "bair"], "“bare” means without any covering, such as leaves."),
  sp("sp2_h27", "homophone", 2, "He ___ the ball across the field.", "threw", ["through", "thru"], "“threw” is the past tense of “throw”."),
  sp("sp2_h28", "homophone", 2, "We walked ___ the long, dark tunnel.", "through", ["threw", "thru"], "“through” means from one side to the other."),
  sp("sp2_h29", "homophone", 2, "She brushed her long, curly ___.", "hair", ["hare", "heir"], "“hair” grows on your head."),
  sp("sp2_h30", "homophone", 3, "A brown ___ raced across the meadow.", "hare", ["hair", "heir"], "A “hare” is an animal like a large rabbit."),
  sp("sp2_h31", "homophone", 3, "The prince was the ___ to the throne.", "heir", ["hair", "hare"], "An “heir” is a person who will inherit something. The h is silent."),
  sp("sp2_h32", "homophone", 2, "I ___ a postcard to my gran last week.", "sent", ["scent", "cent"], "“sent” is the past tense of “send”."),
  sp("sp2_h33", "homophone", 3, "The ___ of the roses filled the room.", "scent", ["sent", "cent"], "“scent” is a smell. It has a silent c after the s."),
  sp("sp2_h34", "homophone", 2, "Running is not ___ in the corridor.", "allowed", ["aloud", "alowed"], "“allowed” means permitted."),
  sp("sp2_h35", "homophone", 2, "She read the poem ___ to the class.", "aloud", ["allowed", "alowd"], "“aloud” means so that others can hear."),
  // ── tricky (exception) words ───────────────────────────────────────────────────────────────────────────────────
  sp("sp2_e1", "exception", 2, "The concert is on ___ evening.", "Wednesday", ["Wensday", "Wendsday"], "“Wednesday” has a silent d. Say it as Wed-nes-day to remember it."),
  sp("sp2_e2", "exception", 2, "My birthday is in ___.", "February", ["Febuary", "Febrary"], "“February” has an r after the b: Feb-ru-ary."),
  sp("sp2_e3", "exception", 2, "We went for a ___ walk by the sea.", "beautiful", ["beautifull", "beutiful"], "“beautiful”: beau-ti-ful. The suffix -ful has one l."),
  sp("sp2_e4", "exception", 2, "Our ___ waved as we drove past.", "neighbour", ["neighbor", "nieghbour"], "In British English, “neighbour” has -our. Remember: ei after g, as in neigh."),
  sp("sp2_e5", "exception", 2, "Each cake was ___ from the others.", "different", ["diffrent", "differant"], "“different” has three syllables ending in -ent: dif-fer-ent."),
  sp("sp2_e6", "exception", 1, "Lots of ___ came to the school fair.", "people", ["peple", "peeple"], "“people” has an o and an e that you cannot hear: peo-ple."),
  sp("sp2_e7", "exception", 2, "It was a very ___ decision to make.", "difficult", ["dificult", "difficlt"], "“difficult” has a double f and ends -cult."),
  sp("sp2_e8", "exception", 2, "We borrowed a book from the school ___.", "library", ["libary", "liberry"], "“library” has an r after the b: lib-rar-y."),
  sp("sp2_e9", "exception", 2, "Carrots are my favourite ___.", "vegetable", ["vegtable", "vegatable"], "“vegetable” has an e after the g: veg-e-ta-ble."),
  sp("sp2_e10", "exception", 2, "She was ___ to hear she had won.", "delighted", ["deligted", "delited"], "“delighted” contains “light” with the silent gh: de-light-ed."),
  sp("sp2_e11", "exception", 2, "The ___ carried out an experiment.", "scientist", ["sientist", "scientest"], "“scientist” has a c after the s (sc-) and ends -ist."),
  sp("sp2_e12", "exception", 3, "We visited the ___ to see the tropical fish.", "aquarium", ["aquarum", "acquarium"], "“aquarium” is spelt a-qu-ar-i-um, with no c."),
  sp("sp2_e13", "exception", 3, "It is ___ to wear a helmet when you cycle.", "necessary", ["neccessary", "necesary"], "“necessary”: one c, double s. Think: one Collar, two Sleeves."),
  sp("sp2_e14", "exception", 3, "Keep the red and blue counters in ___ piles.", "separate", ["seperate", "separete"], "“separate” has “a rat” in the middle: sep-a-rat-e."),
  sp("sp2_e15", "exception", 3, "I will ___ be there on time.", "definitely", ["definately", "definitly"], "“definitely” has “finite” inside it: de-fin-ite-ly."),
  sp("sp2_e16", "exception", 3, "She is an ___ girl who learns fast.", "intelligent", ["inteligent", "intelligant"], "“intelligent” has a double l and ends -ent."),
  sp("sp2_e17", "exception", 3, "The ___ announced a new law.", "government", ["goverment", "govenment"], "“government” has an n before the m: govern-ment."),
  sp("sp2_e18", "exception", 2, "I ___ you when you say you were not there.", "believe", ["beleive", "belive"], "“believe” follows “i before e, except after c”."),
  sp("sp2_e19", "exception", 2, "Did you ___ my letter yesterday?", "receive", ["recieve", "receeve"], "After c, the letters swap to e before i: rec-ei-ve."),
  sp("sp2_e20", "exception", 3, "He was so ___ that he forgot his own name.", "embarrassed", ["embarased", "embarrased"], "“embarrassed” has a double r and a double s."),
  sp("sp2_e21", "exception", 3, "She felt ___ of her sister’s success.", "jealous", ["jelous", "jealus"], "“jealous” starts with jea- and ends -ous."),
  sp("sp2_e22", "exception", 2, "There was an ___ on the motorway.", "accident", ["acident", "accidant"], "“accident” has a double c and ends -ent."),
  sp("sp2_e23", "exception", 2, "Leaves fall from the trees in ___.", "autumn", ["autum", "autunm"], "“autumn” ends in a silent n: au-tum-n."),
  sp("sp2_e24", "exception", 1, "The knight lived in a great stone ___.", "castle", ["casle", "cassle"], "“castle” has a silent t: cas-tle."),
  sp("sp2_e25", "exception", 1, "They sailed to a small tropical ___.", "island", ["iland", "islend"], "“island” has a silent s. It is not related to “land” in its spelling."),
  sp("sp2_e26", "exception", 3, "Her ___ of history was impressive.", "knowledge", ["knowlege", "nowledge"], "“knowledge” starts with a silent k and has a d before the g."),
  // ── spelling patterns ──────────────────────────────────────────────────────────────────────────────────────────
  sp("sp2_p1", "pattern", 2, "The football ___ ended in a draw.", "competition", ["competision", "competishun"], "Most words ending in the “shun” sound after a t sound use -tion: competi-tion."),
  sp("sp2_p2", "pattern", 2, "She gave a clear ___ of the rules.", "explanation", ["explanasion", "explaination"], "“explanation” comes from explain but drops the i: explan-ation."),
  sp("sp2_p3", "pattern", 2, "We watched a film on the ___.", "television", ["telivision", "televison"], "After a vowel sound, “zhun” is often spelt -sion: televi-sion."),
  sp("sp2_p4", "pattern", 2, "It was a very hard ___ to make.", "decision", ["decission", "descision"], "“decision” ends in -sion, with just one s: deci-sion."),
  sp("sp2_p5", "pattern", 2, "It was a great ___ to meet you.", "pleasure", ["plesure", "pleasur"], "“pleasure” ends in -sure, sounding like “zher”."),
  sp("sp2_p6", "pattern", 3, "The ___ came to fix the broken lights.", "electrician", ["electrition", "electrican"], "Words for a person who does something often end in -cian: electrician, magician, musician."),
  sp("sp2_p7", "pattern", 2, "The ___ pulled a rabbit from the hat.", "magician", ["magition", "magican"], "“magician” ends in -cian, the usual ending for a person’s job or skill."),
  sp("sp2_p8", "pattern", 2, "A very ___ storm hit the coast.", "dangerous", ["dangerus", "danjerous"], "Adjectives ending in the “us” sound are often spelt -ous: dangerous."),
  sp("sp2_p9", "pattern", 2, "The elephant was ___.", "enormous", ["enormus", "enormouse"], "“enormous” ends in -ous, not -us or -ouse."),
  sp("sp2_p10", "pattern", 2, "She was ___ from school with a cold.", "absent", ["absant", "abcent"], "“absent” ends in -ent: ab-sent."),
  sp("sp2_p11", "pattern", 3, "It was ___ that the door had been left open.", "obvious", ["obvius", "obveous"], "“obvious” ends in -ious: ob-vi-ous."),
  sp("sp2_p12", "pattern", 2, "Yesterday I ___ a new pair of shoes.", "bought", ["bort", "bougt"], "“bought” has the -ought pattern, like thought and brought."),
  sp("sp2_p13", "pattern", 2, "I ___ it was Tuesday, but it was Wednesday.", "thought", ["thort", "thougt"], "“thought” has the -ought pattern: th-ought."),
  sp("sp2_p14", "pattern", 2, "Yesterday she ___ her PE kit to school.", "brought", ["brout", "brougt"], "“brought” has the -ought pattern, like bought and thought."),
  sp("sp2_p15", "pattern", 2, "We have ___ chairs for everyone.", "enough", ["enuff", "enougth"], "In “enough”, -ough sounds like “uff”."),
  sp("sp2_p16", "pattern", 2, "She had a bad ___ and stayed at home.", "cough", ["coff", "cogh"], "In “cough”, -ough sounds like “off”."),
  sp("sp2_p17", "pattern", 2, "The sea was very ___ during the storm.", "rough", ["ruff", "rouff"], "In “rough”, -ough sounds like “uff”."),
  sp("sp2_p18", "pattern", 1, "The joke made everyone ___.", "laugh", ["laff", "lauf"], "“laugh” has -augh, which sounds like “af”."),
  sp("sp2_p19", "pattern", 1, "The bus ___ at the traffic lights.", "stopped", ["stoped", "stopt"], "“stop” has a short vowel and one final consonant, so the p doubles before -ed."),
  sp("sp2_p20", "pattern", 1, "She is ___ in the pool.", "swimming", ["swiming", "swimmng"], "“swim” doubles the m before -ing to keep the vowel short."),
  sp("sp2_p21", "pattern", 2, "It was only the ___ of a long adventure.", "beginning", ["begining", "beggining"], "“begin” ends with a stressed short vowel plus n, so the n doubles before -ing."),
  sp("sp2_p22", "pattern", 3, "The accident ___ at noon.", "occurred", ["ocurred", "occured"], "“occur” doubles its r before -ed, and has a double c."),
  sp("sp2_p23", "pattern", 2, "He crossed the ice very ___.", "carefully", ["carefuly", "carfully"], "Add -ly to “careful” without dropping an l: careful + ly."),
  sp("sp2_p24", "pattern", 2, "___, the bell rang for lunch.", "Finally", ["Finaly", "Finnally"], "“final” + “ly” keeps both l letters: final-ly."),
  sp("sp2_p25", "pattern", 2, "The children played ___ in the garden.", "happily", ["happyly", "hapily"], "For words ending in a consonant + y, change the y to i before -ly: happy → happily."),
  sp("sp2_p26", "pattern", 2, "I ___ with your opinion.", "disagree", ["disagre", "dissagree"], "The prefix dis- joins to “agree” without doubling: dis + agree."),
  sp("sp2_p27", "pattern", 3, "Take care not to ___ the word.", "misspell", ["mispell", "mispel"], "The prefix mis- joins to “spell”, so there are two s letters: mis + spell."),
  sp("sp2_p28", "pattern", 3, "The magician made the coin ___.", "disappear", ["dissapear", "disapear"], "dis + appear: one s in dis, and “appear” keeps its double p."),
  sp("sp2_p29", "pattern", 2, "The paper had a deep ___ across it.", "wrinkle", ["rinkle", "wrinckle"], "“wrinkle” begins with a silent w."),
  sp("sp2_p30", "pattern", 3, "A garden ___ stood beside the pond.", "gnome", ["nome", "gnoam"], "“gnome” begins with a silent g."),
];
