// p8em: features/templates/TemplatesApp.tsx
const rows: Record<string, readonly string[]> = {
  tplNeedNameBody: ["A name and a message are needed.", "Potrzebna jest nazwa i wiadomość.", "Sunt necesare un nume și un mesaj.", "نام اور پیغام ضروری ہیں۔", "ਨਾਮ ਅਤੇ ਸੁਨੇਹਾ ਜ਼ਰੂਰੀ ਹਨ।", "একটি নাম ও একটি বার্তা প্রয়োজন।", "الاسم والرسالة مطلوبان.", "É necessário um nome e uma mensagem.", "Se necesitan un nombre y un mensaje.", "Un nom et un message sont nécessaires.", "Mae angen enw a neges."],
  tplEdit: ["Edit template", "Edytuj szablon", "Editează șablonul", "ٹیمپلیٹ میں ترمیم کریں", "ਟੈਮਪਲੇਟ ਸੋਧੋ", "টেমপ্লেট সম্পাদনা করুন", "تعديل القالب", "Editar modelo", "Editar plantilla", "Modifier le modèle", "Golygu’r templed"],
  tplNew: ["New template", "Nowy szablon", "Șablon nou", "نیا ٹیمپلیٹ", "ਨਵਾਂ ਟੈਮਪਲੇਟ", "নতুন টেমপ্লেট", "قالب جديد", "Novo modelo", "Nueva plantilla", "Nouveau modèle", "Templed newydd"],
  tplName: ["Template name", "Nazwa szablonu", "Numele șablonului", "ٹیمپلیٹ کا نام", "ਟੈਮਪਲੇਟ ਦਾ ਨਾਮ", "টেমপ্লেটের নাম", "اسم القالب", "Nome do modelo", "Nombre de la plantilla", "Nom du modèle", "Enw’r templed"],
  tplNamePh: ["e.g. Booking confirmation", "np. Potwierdzenie rezerwacji", "ex. Confirmare rezervare", "مثلاً بکنگ کی تصدیق", "ਜਿਵੇਂ ਬੁਕਿੰਗ ਦੀ ਪੁਸ਼ਟੀ", "যেমন বুকিং নিশ্চিতকরণ", "مثلاً تأكيد الحجز", "p. ex. Confirmação de reserva", "p. ej. Confirmación de reserva", "p. ex. Confirmation de réservation", "e.e. Cadarnhad archeb"],
  tplSubjectPh: ["Subject line (optional)", "Temat (opcjonalnie)", "Subiect (opțional)", "سبجیکٹ لائن (اختیاری)", "ਵਿਸ਼ਾ ਲਾਈਨ (ਵਿਕਲਪਿਕ)", "বিষয় লাইন (ঐচ্ছিক)", "سطر الموضوع (اختياري)", "Assunto (opcional)", "Asunto (opcional)", "Objet (facultatif)", "Llinell pwnc (dewisol)"],
  tplBodyPh: ["Write the message…", "Napisz wiadomość…", "Scrie mesajul…", "پیغام لکھیں…", "ਸੁਨੇਹਾ ਲਿਖੋ…", "বার্তা লিখুন…", "اكتب الرسالة…", "Escreva a mensagem…", "Escribe el mensaje…", "Rédigez le message…", "Ysgrifennwch y neges…"],
  tplInsertMerge: ["Insert a merge field — click to add; each fills per recipient on send", "Wstaw pole scalania — kliknij, aby dodać; każde uzupełnia się dla każdego odbiorcy przy wysyłce", "Inserează un câmp de îmbinare — fă clic pentru a adăuga; fiecare se completează pentru fiecare destinatar la trimitere", "مرج فیلڈ شامل کریں — شامل کرنے کے لیے کلک کریں؛ بھیجتے وقت ہر وصول کنندہ کے لیے بھر جاتا ہے", "ਮਰਜ ਫੀਲਡ ਪਾਓ — ਜੋੜਨ ਲਈ ਕਲਿੱਕ ਕਰੋ; ਭੇਜਣ ਵੇਲੇ ਹਰ ਪ੍ਰਾਪਤਕਰਤਾ ਲਈ ਭਰਿਆ ਜਾਂਦਾ ਹੈ", "মার্জ ফিল্ড যোগ করুন — যোগ করতে ক্লিক করুন; পাঠানোর সময় প্রতিটি প্রাপকের জন্য পূরণ হয়", "أدرج حقل دمج — انقر للإضافة؛ يُملأ كل حقل لكل مستلم عند الإرسال", "Inserir um campo de fusão — clique para adicionar; cada um é preenchido por destinatário ao enviar", "Inserta un campo de combinación: haz clic para añadirlo; cada uno se completa por destinatario al enviar", "Insérer un champ de fusion — cliquez pour l’ajouter ; chacun est rempli pour chaque destinataire à l’envoi", "Mewnosod maes cyfuno — cliciwch i’w ychwanegu; mae pob un yn cael ei lenwi ar gyfer pob derbynnydd wrth anfon"],
  tplNeedsBooking: [" · needs a booking", " · wymaga rezerwacji", " · necesită o rezervare", " · بکنگ درکار ہے", " · ਬੁਕਿੰਗ ਲੋੜੀਂਦੀ ਹੈ", " · বুকিং প্রয়োজন", " · يتطلب حجزًا", " · requer uma reserva", " · requiere una reserva", " · nécessite une réservation", " · mae angen archeb"],
  tplSaveChanges: ["💾 Save changes", "💾 Zapisz zmiany", "💾 Salvează modificările", "💾 تبدیلیاں محفوظ کریں", "💾 ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ", "💾 পরিবর্তন সংরক্ষণ করুন", "💾 حفظ التغييرات", "💾 Guardar alterações", "💾 Guardar cambios", "💾 Enregistrer les modifications", "💾 Cadw’r newidiadau"],
  tplCreate: ["Create template", "Utwórz szablon", "Creează șablon", "ٹیمپلیٹ بنائیں", "ਟੈਮਪਲੇਟ ਬਣਾਓ", "টেমপ্লেট তৈরি করুন", "إنشاء قالب", "Criar modelo", "Crear plantilla", "Créer le modèle", "Creu templed"],
  tplDupFailed: ["Couldn’t duplicate", "Nie udało się zduplikować", "Nu s-a putut duplica", "نقل نہیں بن سکی", "ਡੁਪਲੀਕੇਟ ਨਹੀਂ ਹੋ ਸਕਿਆ", "ডুপ্লিকেট করা যায়নি", "تعذّر التكرار", "Não foi possível duplicar", "No se pudo duplicar", "Duplication impossible", "Methwyd dyblygu"],
  tplDeleteConfirm: ["Delete “{name}”?", "Usunąć „{name}”?", "Ștergi „{name}”?", "“{name}” حذف کریں؟", "“{name}” ਮਿਟਾਉਣਾ ਹੈ?", "“{name}” মুছে ফেলবেন?", "حذف «{name}»؟", "Eliminar “{name}”?", "¿Eliminar “{name}”?", "Supprimer « {name} » ?", "Dileu “{name}”?"],
  tplBackToMessages: ["← Back to messages", "← Wróć do wiadomości", "← Înapoi la mesaje", "→ پیغامات پر واپس جائیں", "← ਸੁਨੇਹਿਆਂ ’ਤੇ ਵਾਪਸ ਜਾਓ", "← বার্তায় ফিরে যান", "→ العودة إلى الرسائل", "← Voltar às mensagens", "← Volver a mensajes", "← Retour aux messages", "← Yn ôl at negeseuon"],
  tplTitle: ["Message templates", "Szablony wiadomości", "Șabloane de mesaje", "پیغام کے ٹیمپلیٹس", "ਸੁਨੇਹਾ ਟੈਮਪਲੇਟ", "বার্তার টেমপ্লেট", "قوالب الرسائل", "Modelos de mensagem", "Plantillas de mensajes", "Modèles de messages", "Templedi negeseuon"],
  tplIntro: ["Merge fields fill <b>per recipient</b> on send. Edit these to match your voice.", "Pola scalania uzupełniają się <b>dla każdego odbiorcy</b> przy wysyłce. Edytuj je, aby pasowały do Twojego stylu.", "Câmpurile de îmbinare se completează <b>pentru fiecare destinatar</b> la trimitere. Editează-le ca să se potrivească stilului tău.", "مرج فیلڈز بھیجتے وقت <b>ہر وصول کنندہ کے لیے</b> بھر جاتے ہیں۔ انہیں اپنے انداز کے مطابق بنانے کے لیے ترمیم کریں۔", "ਮਰਜ ਫੀਲਡ ਭੇਜਣ ਵੇਲੇ <b>ਹਰ ਪ੍ਰਾਪਤਕਰਤਾ ਲਈ</b> ਭਰੇ ਜਾਂਦੇ ਹਨ। ਇਨ੍ਹਾਂ ਨੂੰ ਆਪਣੇ ਅੰਦਾਜ਼ ਅਨੁਸਾਰ ਸੋਧੋ।", "মার্জ ফিল্ড পাঠানোর সময় <b>প্রতিটি প্রাপকের জন্য</b> পূরণ হয়। আপনার ধরনের সাথে মেলাতে এগুলো সম্পাদনা করুন।", "تُملأ حقول الدمج <b>لكل مستلم</b> عند الإرسال. عدّلها لتناسب أسلوبك.", "Os campos de fusão são preenchidos <b>por destinatário</b> ao enviar. Edite-os para combinar com o seu estilo.", "Los campos de combinación se completan <b>por destinatario</b> al enviar. Edítalos para que encajen con tu estilo.", "Les champs de fusion sont remplis <b>pour chaque destinataire</b> à l’envoi. Modifiez-les pour qu’ils correspondent à votre style.", "Mae meysydd cyfuno’n cael eu llenwi <b>ar gyfer pob derbynnydd</b> wrth anfon. Golygwch y rhain i gyd-fynd â’ch llais."],
  tplNewBtn: ["＋ New template", "＋ Nowy szablon", "＋ Șablon nou", "＋ نیا ٹیمپلیٹ", "＋ ਨਵਾਂ ਟੈਮਪਲੇਟ", "＋ নতুন টেমপ্লেট", "＋ قالب جديد", "＋ Novo modelo", "＋ Nueva plantilla", "＋ Nouveau modèle", "＋ Templed newydd"],
  tplSubjectLabel: ["Subject: ", "Temat: ", "Subiect: ", "موضوع: ", "ਵਿਸ਼ਾ: ", "বিষয়: ", "الموضوع: ", "Assunto: ", "Asunto: ", "Objet : ", "Pwnc: "],
};
export default rows;
