// Generated map: English template/designer text -> p8em catalogue key (features/email/campaignTemplates.tsx).
export const SEED_KEYS: Record<string, string> = {
  "Your venue · Town · Postcode": "ct000",
  "Follow {company} for daily fun": "ct001",
  "Summer 2026": "ct002",
  "Summer Multi-Activity Camp": "ct003",
  "Sports, art, science & so much more — every single day": "ct004",
  "Book your weeks": "ct005",
  "⚡ Early-bird ends Sunday — save 15%": "ct006",
  "Grab the offer": "ct007",
  "A different adventure every day": "ct008",
  "One booking, endless fun": "ct009",
  "Sports & Games": "ct010",
  "Football, dodgeball, archery": "ct011",
  "Arts & Crafts": "ct012",
  "Paint, print, create": "ct013",
  "Science Lab": "ct014",
  "Slime, rockets, experiments": "ct015",
  "Go-Karting": "ct016",
  "On our safe track": "ct017",
  "Bouncy Castles": "ct018",
  "Inflatable Fridays!": "ct019",
  "Cooking": "ct020",
  "Bake & take home": "ct021",
  "Care to suit your day": "ct022",
  "Free early drop-off from 8am and late pick-up until 6pm — camp that works around work.": "ct023",
  "See the times": "ct024",
  "1 Day": "ct025",
  "Try us out": "ct026",
  "Book": "ct027",
  "3 Days": "ct028",
  "Most popular": "ct029",
  "Full Week": "ct030",
  "Best value": "ct031",
  "All staff are DBS-checked, first-aid trained and brilliant with children. Small group ratios mean everyone gets a look-in.": "ct032",
  "Book your summer now": "ct033",
  "Rewards": "ct034",
  "Bring a friend, both get rewarded": "ct035",
  "Sharing the fun pays off": "ct036",
  "Get your link": "ct037",
  "£10 for you, £10 for them — every time": "ct038",
  "How it works": "ct039",
  "1. Share": "ct040",
  "Send your unique link to a friend": "ct041",
  "2. They book": "ct042",
  "They join any camp or club": "ct043",
  "3. You both save": "ct044",
  "£10 off each — no limit!": "ct045",
  "Why families love us": "ct046",
  "From multi-activity camps to our coding club and go-karting, there's something every child loves — and every parent trusts.": "ct047",
  "Share & save": "ct048",
  "Book online & save 10%": "ct049",
  "What's on & what it costs": "ct050",
  "Multi-Activity Camp": "ct051",
  "Full day, all ages": "ct052",
  "From £28/day": "ct053",
  "Sports Camp": "ct054",
  "Football & more": "ct055",
  "From £24/day": "ct056",
  "Art & Craft Club": "ct057",
  "After school": "ct058",
  "From £12": "ct059",
  "IT & Coding Club": "ct060",
  "Minecraft & robotics": "ct061",
  "From £14": "ct062",
  "Weekend sessions": "ct063",
  "From £18": "ct064",
  "Bouncy Castle Party": "ct065",
  "Book the whole set": "ct066",
  "From £120": "ct067",
  "Our booking policies": "ct068",
  "Places are held on payment. Late collections are charged per the posted rate. Full terms are on our website.": "ct069",
  "Book online now": "ct070",
  "After-School Clubs are back": "ct071",
  "A brilliant end to every school day": "ct072",
  "20% off when you book a full term": "ct073",
  "Pick your child's passion": "ct074",
  "Football": "ct075",
  "Mon & Wed": "ct076",
  "Dance & Drama": "ct077",
  "Tuesdays": "ct078",
  "Art & Craft": "ct079",
  "Thursdays": "ct080",
  "Coding Club": "ct081",
  "Fridays": "ct082",
  "Multi-Sports": "ct083",
  "Daily": "ct084",
  "Science": "ct085",
  "Wednesdays": "ct086",
  "Wraparound made easy": "ct087",
  "Clubs run straight from the school bell to 6pm, so pick-up fits around you.": "ct088",
  "See the timetable": "ct089",
  "Reserve a place": "ct090",
  "Holiday Coaching Courses": "ct091",
  "Intensive skills, serious fun": "ct092",
  "Led by qualified coaches, our holiday courses build real skills across a week — and finish with a celebration your child will remember.": "ct093",
  "1 Week": "ct094",
  "Mornings only": "ct095",
  "2 Weeks": "ct096",
  "Full days": "ct097",
  "3 Weeks": "ct098",
  "Full + care": "ct099",
  "Sibling discount — 10% off the second child": "ct100",
  "See all courses": "ct101",
  "Early-bird": "ct102",
  "Book by Sunday & save 20%": "ct103",
  "Beat the rush and lock in the best rate of the year across every camp and club.": "ct104",
  "Multi-Activity": "ct105",
  "All week": "ct106",
  "Football focus": "ct107",
  "Art Camp": "ct108",
  "Messy & fun": "ct109",
  "⏳ Early-bird ends Sunday midnight": "ct110",
  "Book & save": "ct111",
  "48-HOUR FLASH SALE — 20% OFF EVERYTHING": "ct112",
  "This weekend only": "ct113",
  "One code, every camp & club": "ct114",
  "Shop the sale": "ct115",
  "Holiday Club week": "ct116",
  "was £120 now £96": "ct117",
  "Go-Karting session": "ct118",
  "was £18 now £14": "ct119",
  "Use code WEEKEND at checkout. One per family, ends Sunday at midnight.": "ct120",
  "Party with us!": "ct121",
  "Bouncy castles, games & zero stress for you": "ct122",
  "Pick your party": "ct123",
  "Bouncy Castle": "ct124",
  "Inflatable fun": "ct125",
  "Games galore": "ct126",
  "From £150": "ct127",
  "Make & take": "ct128",
  "From £130": "ct129",
  "We bring the energy": "ct130",
  "You bring the birthday child — we handle games, kit and clean-up. Just add cake!": "ct131",
  "Check a date": "ct132",
  "Enquire now": "ct133",
  "You're invited": "ct134",
  "Come and try us — free!": "ct135",
  "See the camps, meet the team": "ct136",
  "What's on": "ct137",
  "Sports Taster": "ct138",
  "Craft Corner": "ct139",
  "Coding Demo": "ct140",
  "Bring the whole family": "ct141",
  "Free entry, free tasters and a chance to grab an early-bird place before summer sells out.": "ct142",
  "Let us know you're coming": "ct143",
  "A brand-new venue!": "ct144",
  "More space, more activities, closer to home": "ct145",
  "From September you'll find our multi-activity camps and clubs at a fantastic new site — bigger halls, more outdoor space, and room for the go-karts!": "ct146",
  "Our brilliant new home": "ct147",
  "Sports Hall": "ct148",
  "Rain-proof fun": "ct149",
  "Art Studio": "ct150",
  "Space to create": "ct151",
  "Outdoor Track": "ct152",
  "Go-karts & games": "ct153",
  "See the venue": "ct154",
  "Something for every child": "ct155",
  "The all-rounder": "ct156",
  "Get creative": "ct157",
  "Minecraft & robots": "ct158",
  "On our track": "ct159",
  "Forest School": "ct160",
  "Outdoor adventures": "ct161",
  "One provider, endless days out": "ct162",
  "Term-time clubs, holiday camps, wraparound care and parties — all under one trusted roof.": "ct163",
  "Explore everything": "ct164",
  "Match day": "ct165",
  "Friendly Football Match Day": "ct166",
  "Come and cheer them on!": "ct167",
  "Date": "ct168",
  "Sat 14 Jun": "ct169",
  "Kick-off": "ct170",
  "10:00 AM": "ct171",
  "Venue": "ct172",
  "Main field": "ct173",
  "Bring a chair, a snack and your loudest cheer. Squad sheets and team colours will follow nearer the day.": "ct174",
  "Add to calendar": "ct175",
  "Ten years of play!": "ct176",
  "A decade of muddy knees, painted hands, coding wins and go-kart grins. Thank you for being part of the adventure.": "ct177",
  "🎉 Book this month & get a free party voucher": "ct178",
  "See how we've grown": "ct179",
  "Help a child join the fun": "ct180",
  "Our free-places fund is open": "ct181",
  "Every family deserves a brilliant summer. Our fund gives free camp places to children who'd otherwise miss out.": "ct182",
  "A day of sports": "ct183",
  "A creative workshop": "ct184",
  "A whole camp week": "ct185",
  "Every booking this month adds to the fund": "ct186",
  "Get involved": "ct187",
  "Welcome to the club!": "ct188",
  "We can't wait to meet your family": "ct189",
  "Here's everything you need for a brilliant first day at camp.": "ct190",
  "What to bring": "ct191",
  "Packed lunch, water, sun cream, a coat & a smile": "ct192",
  "Drop-off & pick-up": "ct193",
  "Doors open 8:45am · collect by 3:30pm (or use late care)": "ct194",
  "A typical day": "ct195",
  "Sports, arts, a big lunch, more activities and a calm wind-down — busy, happy and full of fun.": "ct196",
  "View your booking": "ct197",
  "See you soon": "ct198",
  "Your session is coming up!": "ct199",
  "A few reminders so the day runs smoothly for everyone.": "ct200",
  "Please pack": "ct201",
  "Labelled lunch, snacks, water & weather-ready clothes": "ct202",
  "Good to know": "ct203",
  "No nuts on site. Tell us of any changes to collection.": "ct204",
  "Running late? Just give us a ring.": "ct205",
  "Meet the people behind the fun": "ct206",
  "Sam": "ct207",
  "Camp Manager": "ct208",
  "Priya": "ct209",
  "Forest School Lead": "ct210",
  "Jordan": "ct211",
  "Head Sports Coach": "ct212",
  "Every one of our team is DBS-checked, first-aid trained and genuinely brilliant with children. Say hello at drop-off — they'd love to meet you.": "ct213",
  "This week": "ct214",
  "This week at camp": "ct215",
  "Mini-Olympics madness": "ct216",
  "Medals, mud and a whole lot of laughing — the children smashed every event.": "ct217",
  "Coding club creations": "ct218",
  "Our IT club built their first working games. Proud doesn't cover it.": "ct219",
  "Snapshot of the week": "ct220",
  "Next week's places are filling fast": "ct221",
  "See what's on": "ct222",
  "What a week we've had!": "ct223",
  "From den-building in Forest School to go-kart races and a very messy art day — the children packed a lot in.": "ct224",
  "More on your app": "ct225",
  "Every photo from the week is waiting in your parent app — take a look!": "ct226",
  "Dates for your diary": "ct227",
  "Autumn Clubs": "ct228",
  "2 Sep – 20 Dec": "ct229",
  "October Camp": "ct230",
  "27–31 Oct": "ct231",
  "Spring Clubs": "ct232",
  "6 Jan – 4 Apr": "ct233",
  "Feb Camp": "ct234",
  "16–20 Feb": "ct235",
  "Summer Camp": "ct236",
  "21 Jul – 29 Aug": "ct237",
  "INSET Cover": "ct238",
  "Dates TBC": "ct239",
  "Book all six weeks & save 15%": "ct240",
  "Book ahead": "ct241",
  "Freshly refreshed camp menu": "ct242",
  "Monday": "ct243",
  "Pasta & garlic bread": "ct244",
  "Wednesday": "ct245",
  "Chicken wraps & salad": "ct246",
  "Friday": "ct247",
  "Fish & chips": "ct248",
  "All meals are allergen-friendly and child-approved. Let us know of any dietary needs and we'll always cater for them.": "ct249",
  "5 ways to make camp mornings easier": "ct250",
  "1. Pack the night before — bag, kit, lunch, done.\\n\\n2. Name everything (labels beat lost-property tears).\\n\\n3. Give little jobs to build independence.\\n\\n4. Keep it calm — a five-minute head start beats a ten-minute rush.\\n\\n5. Talk about the fun ahead on the way in.": "ct251",
  "Got a tip of your own? Reply and tell us!": "ct252",
  "How did we do?": "ct253",
  "We'd love a quick word on how your child found their camp or club. It takes a minute and genuinely helps other families choose us.": "ct254",
  "Leave a review": "ct255",
  "Two minutes to shape next term?": "ct256",
  "We're planning next term's camps and clubs — venues, times, activities, the lot. Your view genuinely steers it.": "ct257",
  "Take the survey": "ct258",
  "Season's greetings": "ct259",
  "from all of us at the club": "ct260",
  "Wishing your family a wonderful holiday and a happy, healthy new year. Thank you for a brilliant year of camps and clubs.": "ct261",
  "🎁 New-year camp places are open now": "ct262",
  "Book the holidays": "ct263",
  "Thank you for a brilliant term!": "ct264",
  "Rest up, have fun, and we'll see you at the next camp. It's been a joy watching every child grow, giggle and go for it.": "ct265",
  "Holiday camp places are filling fast": "ct266",
  "Book now": "ct267",
  "⭐ Star of the Week ⭐": "ct268",
  "Kindness, effort and the biggest smile": "ct269",
  "We love celebrating the little wins at camp. Ask your child about their star moment this week!": "ct270",
  "A friendly payment reminder": "ct271",
  "Your balance for the upcoming camp is due soon. You can pay securely in your parent account — just a nudge so your child's place stays held.": "ct272",
  "Pay securely": "ct273",
  "Important": "ct274",
  "An update to your session": "ct275",
  "Due to circumstances beyond our control, the session on this date won't run as planned. We're sorry for any disruption — affected families will be contacted directly about options and refunds.": "ct276",
  "A note on our prices": "ct277",
  "From the new term our camp and club prices will change slightly, so we can keep our ratios small and our team brilliant. Full details are in your account — thank you for your continued support.": "ct278",
  "Big hero": "cu000",
  "Image + headline + button": "cu001",
  "A brilliant headline": "cu002",
  "A supporting line to set the scene": "cu003",
  "Logo": "cu004",
  "Your saved business logo": "cu005",
  "Testimonial": "cu006",
  "A 5-star parent review": "cu007",
  "Absolutely brilliant — my two had the best week ever and can't wait to go back!": "cu008",
  "— Sarah, mum of two": "cu009",
  "Stats row": "cu010",
  "Big numbers that impress": "cu011",
  "Trusted by families": "cu012",
  "happy children": "cu013",
  "10 yrs": "cu014",
  "of adventures": "cu015",
  "What's included": "cu016",
  "A tick-list of perks": "cu017",
  "Every day includes": "cu018",
  "Qualified, DBS-checked coaches": "cu019",
  "A hot lunch & snacks": "cu020",
  "Free early & late care": "cu021",
  "All equipment provided": "cu022",
  "Discount code": "cu023",
  "A promo code box": "cu024",
  "Use code": "cu025",
  "15% off your next booking — this week only.": "cu026",
  "Contact strip": "cu027",
  "Phone · email · address": "cu028",
  "Get in touch": "cu029",
  "Countdown timer": "cu030",
  "Counts down to your date": "cu031",
  "Early-bird ends in": "cu032",
  "Book before it's gone": "cu033",
  "Graph": "cu034",
  "A fancy bar chart": "cu035",
  "Our year in numbers": "cu036",
  "Camps run": "cu037",
  "Happy kids": "cu038",
  "5-star reviews": "cu039",
  "Heading": "cu040",
  "A titled section": "cu041",
  "Section heading": "cu042",
  "An optional supporting line": "cu043",
  "Text": "cu044",
  "A paragraph (+ optional button)": "cu045",
  "Write your message here.": "cu046",
  "Image + text": "cu047",
  "Photo beside words": "cu048",
  "Tell them about it": "cu049",
  "A short, friendly paragraph that sits neatly beside the photo.": "cu050",
  "Find out more": "cu051",
  "Feature trio": "cu052",
  "3 selling points": "cu053",
  "Qualified team": "cu054",
  "DBS-checked & first-aid trained": "cu055",
  "Small groups": "cu056",
  "More attention for every child": "cu057",
  "Easy booking": "cu058",
  "Secure a place in minutes": "cu059",
  "Activity grid": "cu060",
  "6 activities": "cu061",
  "Something for everyone": "cu062",
  "Photo gallery": "cu063",
  "Heading + 3 photos": "cu064",
  "Moments from camp": "cu065",
  "3 photos in a row": "cu066",
  "Triple image strip": "cu067",
  "Photo collage": "cu068",
  "Big + two stacked": "cu069",
  "Pricing section": "cu070",
  "3 price tiers": "cu071",
  "Simple pricing": "cu072",
  "3 easy steps": "cu073",
  "1. Choose": "cu074",
  "Pick your camp or club": "cu075",
  "2. Book": "cu076",
  "Secure a place online": "cu077",
  "3. Enjoy": "cu078",
  "We take it from there": "cu079",
  "Highlight offer": "cu080",
  "Colour band + button": "cu081",
  "Call to action": "cu082",
  "Panel + button": "cu083",
  "Ready to book?": "cu084",
  "Places are filling fast — grab yours today.": "cu085",
  "Button": "cu086",
  "A single link": "cu087",
  "Social icons": "cu088",
  "Your profiles": "cu089",
  "Divider": "cu090",
  "A thin line": "cu091",
  "Footer": "cu092",
  "Name + address": "cu093",
  "✥ drag to reposition": "cu094",
  "Zoom": "cu095",
  "Remove": "cu096",
  "or paste URL": "cu097",
  "🎬 Video link — YouTube or a direct .mp4": "cu098",
  "Size": "cu099",
  "Business name": "cu100",
  "Tagline (optional)": "cu101",
  "Image": "cu102",
  "Sub-heading": "cu103",
  "Body": "cu104",
  "Button label (blank = none)": "cu105",
  "Button link": "cu106",
  "Text (optional)": "cu107",
  "Sub-heading (optional)": "cu108",
  "Button label (optional — e.g. Book now)": "cu109",
  "Shape": "cu110",
  "✎ Text beside the image": "cu111",
  "Image / text split — drag to keep the image bigger": "cu112",
  "Tip: switch to Small or Medium and a text area appears to sit beside the image.": "cu113",
  "Caption (optional)": "cu114",
  "Image on the right": "cu115",
  "Label": "cu116",
  "Link": "cu117",
  "Address line": "cu118",
  "A thin divider line.": "cu119",
  "＋ Add a network…": "cu120",
  "Columns": "cu121",
  "Title": "cu122",
  "Price (optional)": "cu123",
  "Button (optional)": "cu124",
  "＋ Add item": "cu125",
  "Up to 4 per row.": "cu126",
  "Uses your saved business logo automatically. Upload a different image to override it here.": "cu127",
  "↩ Use saved logo": "cu128",
  "Align": "cu129",
  "Fine-tune height": "cu130",
  "Style": "cu131",
  "Review / quote": "cu132",
  "Who said it": "cu133",
  "📋 Pick a live code…": "cu134",
  "Label above it": "cu135",
  "Description": "cu136",
  "Applied automatically at checkout — no need to type it in": "cu137",
  "Heading (optional)": "cu138",
  "Layout": "cu139",
  "＋ Add stat": "cu140",
  "Up to 4.": "cu141",
  "Number (e.g. 2,000+)": "cu142",
  "Label (e.g. happy children)": "cu143",
  "Date it counts down to": "cu144",
  "Start time": "cu145",
  "Button label (optional)": "cu146",
  "Chart title": "cu147",
  "Chart type": "cu148",
  "e.g. £, %, kids": "cu149",
  "Up to 6 items.": "cu150",
  "Value (number)": "cu151",
  "Add a video link on any photo to make it a play button.": "cu152",
  "＋ Add photo": "cu153",
  "Up to 4 photos.": "cu154",
  "Phone": "cu155",
  "Email": "cu156",
  "Website": "cu157",
  "Address": "cu158",
  "← Templates": "cu159",
  "Move ↑↓ · duplicate ⧉ · delete 🗑 · drag any image to crop": "cu160",
  "← Back": "cu161",
  "Choose a template": "cu162",
  "30 detailed, camp-ready designs. Pick one, then make it yours block by block.": "cu163",
  "↶ Undo": "cu164",
  "Redo ↷": "cu165",
  "Undo": "cu166",
  "Redo": "cu167",
  "Colour": "cu168",
  "Search templates…": "cu169",
  "Use →": "cu170",
  "Delete this saved template": "cu171",
  "No saved templates yet.": "cu172",
  "Swap left / right": "cu173",
  "Move up": "cu174",
  "Move down": "cu175",
  "Duplicate": "cu176",
  "Delete": "cu177",
  "Add": "cu178",
  "Add a section here": "cu179",
  "Add section here": "cu180",
  "✦ Add a section": "cu181",
  "Delete section": "cu182",
  "✓ Done": "cu183",
  "Width": "cu184",
  "sits beside the next same-width section": "cu185",
  "Match email": "cu186",
  "Use the email's colour": "cu187",
  "Frame": "cu188",
  "🗑 Remove": "cu189",
  "✓ Done editing": "cu190",
  "Banner": "cu191",
  "Full": "cu192",
  "Portrait": "cu193",
  "Rectangle": "cu194",
  "Square": "cu195",
  "½ Half": "cu196",
  "▌ Minimal": "cu197",
  "▢ Card": "cu198",
  "▢ Cards": "cu199",
  "▤ Even row": "cu200",
  "▤ Stacked": "cu201",
  "▦ Simple": "cu202",
  "▬ Bars": "cu203",
  "▮ Columns": "cu204",
  "▰ Banner": "cu205",
  "▰ Bold band": "cu206",
  "◍ Avatar": "cu207",
  "◔ Progress": "cu208",
  "◕ Pie": "cu209",
  "◯ Circles": "cu210",
  "❝ Centered": "cu211",
  "💬 Bubble": "cu212",
  "🧩 Collage": "cu213",
  "Use": "cu214",
  "Don’t": "cu215",
  "Default": "cu216",
  "Serif": "cu217",
  "Trebuchet": "cu218",
  "Verdana": "cu219",
  "Elegant": "cu220",
  "Mono": "cu221",
  "Small": "cu222",
  "Medium": "cu223",
  "Large": "cu224",
  "Image side": "cu225",
  "left": "cu226",
  "center": "cu227",
  "right": "cu228",
  "at the end": "cu229",
  "▲ hide": "cu230",
  "▼ show": "cu231",
  "Seasonal & fun": "cu232",
  "Design your email": "cu233",
  "✓ I'm ready to send": "cu234",
  "Poster image — drag to crop": "cu235",
  "Image — drag to crop": "cu236",
  "⬆ Add image": "cu237",
  "⬆ Upload logo": "cu238",
  "…": "cu239",
  "… or type your own": "cu240",
  "…or type your own": "cu241",
  "e.g. SUMMER15": "cu242",
  "The code": "cu243",
  "· live codes: {n}": "cu244",
  "Show “applied automatically at checkout”": "cu245",
  "⚠ That date/time is in the past — pick a future one": "cu246",
  "Pick a date so it can count down.": "cu247",
  "Pick a date and time so it can count down.": "cu248",
  "Counts down to the day & start time above — e.g. when your session begins. The emailed copy freezes at the moment you send (email can’t tick live).": "cu249",
  "⏱ {t} left — ticking": "cu250",
  "No templates match “{q}”.": "cu251",
  "Open any design, tweak it, then hit <b>💾 Save as template</b> in the top bar — it’ll appear here.": "cu252",
  "A <b>direct .mp4</b> plays inline (Apple Mail / most webmail). A <b>YouTube</b> link shows a play thumbnail that opens the video — its thumbnail is used automatically if you don’t add a poster image.": "cu253",
  "Switch any box to <b>Don’t</b> to hide it. Leave a used box blank to pull your saved business details.": "cu254",
  "— there’s room, so fill it (optional)": "cu255",
  "Image {n}% · text fills the rest": "cu256",
  "Item {n}": "cu257",
  "Item {n} (optional)": "cu258",
  "Stat {n}": "cu259",
  "Photo {n}": "cu260",
  "My template · {n} sections": "cu261",
  "{cat} · sections: {n}": "cu262",
  "at position {n}": "cu263",
  "✎ Editing: {name}": "cu264",
  "Just this section: {name}": "cu265",
  "{name} link": "cu266",
  "Delete “{name}”? This can’t be undone.": "cu267",
  "this template": "cu268",
  "In a few words, what should this say? The writer turns it into friendly copy.": "cu269",
  "New": "cu270",
  "✨ Writing…": "cu271",
  "✨ Help me write": "cu272",
  "Your business": "cu273",
  "Learn more": "cu274",
  "More": "cu275",
  "Your saved logo shows here — add one in Settings › Branding.": "cu276",
  "Absolutely brilliant — my two had the best week ever!": "cu277",
  "— A very happy parent": "cu278",
  "Your code": "cu279",
  "Hurry — offer ends soon": "cu280",
  "Set the date & start time in the editor to show the countdown.": "cu281",
  "total": "cu282",
  "You’re receiving this because your family has booked with us. {unsub} any time.": "cu283",
  "Unsubscribe": "cu284",
  "★ FEATURED": "cu285",
  "None": "cu286",
  "Elegant card": "cu287",
  "Photo frame": "cu288",
  "Luxury": "cu289",
  "Polaroid": "cu290",
  "Double line": "cu291",
  "Corners": "cu292",
  "Neon glow": "cu293",
  "Ribbon": "cu294",
  "Sparkle": "cu295",
  "Confetti": "cu296",
  "Header": "cu297",
  "Colour band": "cu298",
  "Cards": "cu299",
  "Pricing tiers": "cu300",
  "Stats": "cu301",
  "Checklist": "cu302",
  "⭐ My templates": "cu303",
  "Blue": "cu304",
  "Navy": "cu305",
  "Teal": "cu306",
  "Green": "cu307",
  "Mint": "cu308",
  "Amber": "cu309",
  "Coral": "cu310",
  "Red": "cu311",
  "Pink": "cu312",
  "Purple": "cu313",
  "🎄 Christmas": "cu314",
  "❄️ Snow": "cu315",
  "🍂 Autumn": "cu316",
  "🌸 Flowers": "cu317",
  "🎈 Balloons": "cu318",
  "🎉 Party": "cu319",
  "🎃 Halloween": "cu320",
  "❤️ Valentine's": "cu321",
  "🐣 Easter": "cu322",
  "☀️ Summer": "cu323",
  "🌴 Tropical": "cu324",
  "🌈 Children": "cu325",
  "🎆 Fireworks": "cu326",
  "✨ Glitter": "cu327",
  "Multi-activity camp": "cu328",
  "Offers & bookings": "cu329",
  "Refer a friend": "cu330",
  "Sessions & prices": "cu331",
  "After-school clubs": "cu332",
  "Course / pricing tiers": "cu333",
  "Early-bird offer": "cu334",
  "Flash sale": "cu335",
  "Birthday parties": "cu336",
  "Open day invite": "cu337",
  "Announcements": "cu338",
  "New venue opening": "cu339",
  "Everything we offer": "cu340",
  "Match / event day": "cu341",
  "Milestone / birthday": "cu342",
  "Fundraiser": "cu343",
  "Welcome pack": "cu344",
  "Welcome": "cu345",
  "Session reminder": "cu346",
  "Meet the team": "cu347",
  "Weekly round-up": "cu348",
  "News & updates": "cu349",
  "Photo story": "cu350",
  "Term & camp dates": "cu351",
  "Menu / meals update": "cu352",
  "Parent tips": "cu353",
  "Review request": "cu354",
  "Survey invite": "cu355",
  "Seasonal greeting": "cu356",
  "Seasonal": "cu357",
  "End-of-term thanks": "cu358",
  "Star of the week": "cu359",
  "Payment reminder": "cu360",
  "Admin & notices": "cu361",
  "Closure / change notice": "cu362",
  "Price update": "cu363",
  "Hero": "cu364",
  "Unit (optional)": "cu365",
};
