// Verb conjugation for French, Spanish and German (plan L-03) — generated by RULES, with a lexicon only for what is genuinely irregular.
// PURE: no React, no I/O. `conjugate(lang, verb, tense, person)` returns every accepted form (canonical first), WITHOUT the subject pronoun
// (use `withSubject` to add it). person: 0..5 = 1sg, 2sg, 3sg, 1pl, 2pl, 3pl.
import type { Lang } from "../AccentBar";

export type { Lang };
export type Tier = "KS3" | "KS4";
export type Kind = "regular" | "stem" | "irregular";
export interface VerbInfo { inf: string; en: string; tier: Tier; theme: string; kind: Kind }
export interface TenseInfo { id: string; label: string }

export const TENSES: Record<Lang, TenseInfo[]> = {
  fr: [
    { id: "present", label: "Présent" }, { id: "passe_compose", label: "Passé composé" }, { id: "imparfait", label: "Imparfait" },
    { id: "futur_proche", label: "Futur proche" }, { id: "futur_simple", label: "Futur simple" }, { id: "conditionnel", label: "Conditionnel" },
  ],
  es: [
    { id: "present", label: "Presente" }, { id: "preterito", label: "Pretérito" }, { id: "imperfecto", label: "Imperfecto" },
    { id: "futuro_proximo", label: "Futuro próximo" }, { id: "futuro_simple", label: "Futuro simple" }, { id: "condicional", label: "Condicional" },
  ],
  de: [
    { id: "present", label: "Präsens" }, { id: "perfekt", label: "Perfekt" }, { id: "praeteritum", label: "Präteritum" },
    { id: "futur", label: "Futur I (werden)" }, { id: "konjunktiv2", label: "Konjunktiv II (würde)" },
  ],
};
export const PERSONS: Record<Lang, string[]> = {
  fr: ["je", "tu", "il/elle", "nous", "vous", "ils/elles"],
  es: ["yo", "tú", "él/ella", "nosotros", "vosotros", "ellos/ellas"],
  de: ["ich", "du", "er/sie/es", "wir", "ihr", "sie/Sie"],
};

const w = (s: string) => s.split(" ");
const uniq = (xs: string[]) => [...new Set(xs)];
const isVowelStart = (s: string) => /^[aeiouyhàâéèêëîïôöùûüœæáíóúäöü]/i.test(s);
const lastReplace = (s: string, from: string, to: string) => { const i = s.lastIndexOf(from); return i < 0 ? s : s.slice(0, i) + to + s.slice(i + from.length); };

// ══ FRENCH ═════════════════════════════════════════════════════════════════
interface FrEnt extends VerbInfo { pres?: string[]; pp?: string; aux?: "etre"; fut?: string; imp?: string; spell?: "e-è" | "é-è" | "double" }
type FrX = Omit<Partial<FrEnt>, "pres"> & { pres?: string };
const F = (inf: string, en: string, tier: Tier, theme: string, kind: Kind, x: FrX = {}): FrEnt => ({ inf, en, tier, theme, kind, ...x, pres: x.pres ? w(x.pres) : undefined });
const FR: FrEnt[] = [
  // irregular
  F("être", "to be", "KS3", "core", "irregular", { pres: "suis es est sommes êtes sont", pp: "été", fut: "ser", imp: "ét" }),
  F("avoir", "to have", "KS3", "core", "irregular", { pres: "ai as a avons avez ont", pp: "eu", fut: "aur" }),
  F("aller", "to go", "KS3", "core", "irregular", { pres: "vais vas va allons allez vont", pp: "allé", aux: "etre", fut: "ir" }),
  F("faire", "to do / make", "KS3", "core", "irregular", { pres: "fais fais fait faisons faites font", pp: "fait", fut: "fer" }),
  F("pouvoir", "to be able to (can)", "KS3", "modals", "irregular", { pres: "peux peux peut pouvons pouvez peuvent", pp: "pu", fut: "pourr" }),
  F("vouloir", "to want", "KS3", "modals", "irregular", { pres: "veux veux veut voulons voulez veulent", pp: "voulu", fut: "voudr" }),
  F("devoir", "to have to (must)", "KS3", "modals", "irregular", { pres: "dois dois doit devons devez doivent", pp: "dû", fut: "devr" }),
  F("savoir", "to know (a fact)", "KS3", "core", "irregular", { pres: "sais sais sait savons savez savent", pp: "su", fut: "saur" }),
  F("prendre", "to take", "KS3", "daily life", "irregular", { pres: "prends prends prend prenons prenez prennent", pp: "pris" }),
  F("venir", "to come", "KS3", "travel", "irregular", { pres: "viens viens vient venons venez viennent", pp: "venu", aux: "etre", fut: "viendr" }),
  F("voir", "to see", "KS3", "daily life", "irregular", { pres: "vois vois voit voyons voyez voient", pp: "vu", fut: "verr" }),
  F("dire", "to say / tell", "KS3", "communication", "irregular", { pres: "dis dis dit disons dites disent", pp: "dit" }),
  F("mettre", "to put / put on", "KS3", "daily life", "irregular", { pres: "mets mets met mettons mettez mettent", pp: "mis" }),
  F("boire", "to drink", "KS3", "food & drink", "irregular", { pres: "bois bois boit buvons buvez boivent", pp: "bu" }),
  F("lire", "to read", "KS3", "free time", "irregular", { pres: "lis lis lit lisons lisez lisent", pp: "lu" }),
  F("écrire", "to write", "KS3", "school", "irregular", { pres: "écris écris écrit écrivons écrivez écrivent", pp: "écrit" }),
  F("dormir", "to sleep", "KS3", "daily life", "irregular", { pres: "dors dors dort dormons dormez dorment", pp: "dormi" }),
  F("sortir", "to go out", "KS3", "free time", "irregular", { pres: "sors sors sort sortons sortez sortent", pp: "sorti", aux: "etre" }),
  F("partir", "to leave", "KS3", "travel", "irregular", { pres: "pars pars part partons partez partent", pp: "parti", aux: "etre" }),
  F("ouvrir", "to open", "KS3", "daily life", "irregular", { pres: "ouvre ouvres ouvre ouvrons ouvrez ouvrent", pp: "ouvert" }),
  F("offrir", "to give (a gift)", "KS4", "daily life", "irregular", { pres: "offre offres offre offrons offrez offrent", pp: "offert" }),
  F("connaître", "to know (a person / place)", "KS4", "core", "irregular", { pres: "connais connais connaît connaissons connaissez connaissent", pp: "connu" }),
  F("croire", "to believe", "KS4", "communication", "irregular", { pres: "crois crois croit croyons croyez croient", pp: "cru" }),
  F("recevoir", "to receive", "KS4", "daily life", "irregular", { pres: "reçois reçois reçoit recevons recevez reçoivent", pp: "reçu", fut: "recevr" }),
  F("apprendre", "to learn", "KS3", "school", "irregular", { pres: "apprends apprends apprend apprenons apprenez apprennent", pp: "appris" }),
  F("comprendre", "to understand", "KS3", "school", "irregular", { pres: "comprends comprends comprend comprenons comprenez comprennent", pp: "compris" }),
  F("devenir", "to become", "KS4", "core", "irregular", { pres: "deviens deviens devient devenons devenez deviennent", pp: "devenu", aux: "etre", fut: "deviendr" }),
  F("revenir", "to come back", "KS3", "travel", "irregular", { pres: "reviens reviens revient revenons revenez reviennent", pp: "revenu", aux: "etre", fut: "reviendr" }),
  F("courir", "to run", "KS4", "free time", "irregular", { pres: "cours cours court courons courez courent", pp: "couru", fut: "courr" }),
  F("vivre", "to live", "KS4", "core", "irregular", { pres: "vis vis vit vivons vivez vivent", pp: "vécu" }),
  F("suivre", "to follow", "KS4", "school", "irregular", { pres: "suis suis suit suivons suivez suivent", pp: "suivi" }),
  F("envoyer", "to send", "KS4", "communication", "irregular", { pres: "envoie envoies envoie envoyons envoyez envoient", pp: "envoyé", fut: "enverr" }),
  // regular -er
  F("parler", "to speak", "KS3", "communication", "regular"), F("jouer", "to play", "KS3", "free time", "regular"),
  F("manger", "to eat", "KS3", "food & drink", "regular"), F("aimer", "to like / love", "KS3", "free time", "regular"),
  F("habiter", "to live (in)", "KS3", "home & family", "regular"), F("regarder", "to watch / look at", "KS3", "free time", "regular"),
  F("écouter", "to listen to", "KS3", "free time", "regular"), F("travailler", "to work", "KS3", "school", "regular"),
  F("étudier", "to study", "KS3", "school", "regular"), F("danser", "to dance", "KS3", "free time", "regular"),
  F("chanter", "to sing", "KS3", "free time", "regular"), F("nager", "to swim", "KS3", "free time", "regular"),
  F("visiter", "to visit (a place)", "KS3", "travel", "regular"), F("commencer", "to begin", "KS3", "school", "regular"),
  F("acheter", "to buy", "KS3", "shopping", "regular", { spell: "e-è" }), F("préférer", "to prefer", "KS3", "free time", "regular", { spell: "é-è" }),
  F("payer", "to pay", "KS4", "shopping", "regular"), F("détester", "to hate", "KS3", "free time", "regular"),
  F("porter", "to wear / carry", "KS3", "daily life", "regular"), F("donner", "to give", "KS3", "daily life", "regular"),
  F("trouver", "to find", "KS3", "daily life", "regular"), F("penser", "to think", "KS3", "communication", "regular"),
  F("arriver", "to arrive", "KS3", "travel", "regular", { aux: "etre" }), F("rester", "to stay", "KS3", "travel", "regular", { aux: "etre" }),
  F("entrer", "to enter", "KS3", "travel", "regular", { aux: "etre" }), F("tomber", "to fall", "KS3", "daily life", "regular", { aux: "etre" }),
  F("monter", "to go up", "KS3", "travel", "regular", { aux: "etre" }), F("rentrer", "to go home / return", "KS3", "travel", "regular", { aux: "etre" }),
  // regular -ir / -re
  F("finir", "to finish", "KS3", "school", "regular"), F("choisir", "to choose", "KS3", "shopping", "regular"),
  F("réussir", "to succeed / pass", "KS3", "school", "regular"), F("grandir", "to grow up", "KS4", "home & family", "regular"),
  F("remplir", "to fill", "KS4", "daily life", "regular"),
  F("vendre", "to sell", "KS3", "shopping", "regular"), F("attendre", "to wait (for)", "KS3", "travel", "regular"),
  F("répondre", "to answer", "KS3", "school", "regular"), F("entendre", "to hear", "KS3", "daily life", "regular"),
  F("perdre", "to lose", "KS3", "daily life", "regular"), F("rendre", "to give back", "KS4", "daily life", "regular"),
  F("descendre", "to go down / get off", "KS3", "travel", "regular", { aux: "etre" }),
  // reflexive
  F("se lever", "to get up", "KS3", "daily routine", "regular", { spell: "e-è" }), F("se coucher", "to go to bed", "KS3", "daily routine", "regular"),
  F("se laver", "to wash (oneself)", "KS3", "daily routine", "regular"), F("s'habiller", "to get dressed", "KS3", "daily routine", "regular"),
  F("se réveiller", "to wake up", "KS3", "daily routine", "regular"), F("se promener", "to go for a walk", "KS4", "free time", "regular", { spell: "e-è" }),
  F("s'appeler", "to be called", "KS3", "home & family", "regular", { spell: "double" }), F("se doucher", "to have a shower", "KS3", "daily routine", "regular"),
];
const FR_MAP = new Map(FR.map((e) => [e.inf, e]));
const FR_REFL = ["me", "te", "se", "nous", "vous", "se"];
const frRefl = (p: number, form: string) => { const r = FR_REFL[p]!; return /^(me|te|se)$/.test(r) && isVowelStart(form) ? `${r[0]}'${form}` : `${r} ${form}`; };
function frEnt(verb: string): { e: FrEnt; refl: boolean; inf: string } {
  const m = /^(?:se |s')(.+)$/.exec(verb), refl = !!m, inf = m ? m[1]! : verb;
  const e = FR_MAP.get(verb) ?? (refl ? FR_MAP.get(inf) : undefined) ?? { inf: verb, en: "", tier: "KS4" as Tier, theme: "other", kind: "regular" as Kind };
  return { e, refl, inf };
}
function frPresent(e: FrEnt, inf: string): string[] {
  if (e.pres) return e.pres;
  if (inf.endsWith("er")) {
    const st = inf.slice(0, -2), en = ["e", "es", "e", "ons", "ez", "ent"];
    let sg = st;
    if (e.spell === "e-è") sg = st.replace(/e([^aeiouyéèê]+)$/, "è$1");
    else if (e.spell === "é-è") sg = st.replace(/é([^aeiouyéèê]+)$/, "è$1");
    else if (e.spell === "double") sg = st + st.slice(-1);
    else if (st.endsWith("y")) sg = st.slice(0, -1) + "i";
    const nous = st.endsWith("g") ? st + "e" : st.endsWith("c") ? st.slice(0, -1) + "ç" : st;
    return en.map((x, i) => (i === 3 ? nous : i === 4 ? st : sg) + x);
  }
  if (inf.endsWith("ir")) { const st = inf.slice(0, -2); return ["is", "is", "it", "issons", "issez", "issent"].map((x) => st + x); }
  if (inf.endsWith("re")) { const st = inf.slice(0, -2); return ["s", "s", "", "ons", "ez", "ent"].map((x) => st + x); }
  return Array(6).fill(inf) as string[];
}
const frPP = (inf: string) => inf.endsWith("er") ? inf.slice(0, -2) + "é" : inf.endsWith("ir") ? inf.slice(0, -2) + "i" : inf.endsWith("re") ? inf.slice(0, -2) + "u" : inf;
const FR_AVOIR = w("ai as a avons avez ont"), FR_ETRE = w("suis es est sommes êtes sont"), FR_ALLER = w("vais vas va allons allez vont");
const FR_IMP = w("ais ais ait ions iez aient");
function frForms(verb: string, tense: string, p: number): string[] {
  const { e, refl, inf } = frEnt(verb), pres = frPresent(e, inf);
  const R = (f: string) => (refl ? frRefl(p, f) : f);
  switch (tense) {
    case "present": return [R(pres[p]!)];
    case "imparfait": {
      let st = e.imp ?? pres[3]!.replace(/ons$/, "");
      if (p === 3 || p === 4) st = st.replace(/ge$/, "g").replace(/ç$/, "c");
      return [R(st + FR_IMP[p])];
    }
    case "futur_simple": case "conditionnel": {
      let st: string;
      if (e.fut) st = e.fut;
      else if (inf.endsWith("er")) st = e.spell === "e-è" || e.spell === "double" || inf.endsWith("yer") ? pres[0]! + "r" : inf;
      else st = inf.endsWith("re") ? inf.slice(0, -1) : inf;
      return [R(st + (tense === "futur_simple" ? ["ai", "as", "a", "ons", "ez", "ont"][p]! : FR_IMP[p]!))];
    }
    case "futur_proche": return [`${FR_ALLER[p]} ${refl ? frRefl(p, inf) : inf}`];
    case "passe_compose": {
      const etre = e.aux === "etre" || refl, aux = (etre ? FR_ETRE : FR_AVOIR)[p]!, pp = e.pp ?? frPP(inf);
      const pps = etre ? (p < 3 ? [pp, pp + "e", pp + "(e)"] : [pp, pp + "s", pp + "es", pp + "(e)s"]) : [pp];
      return pps.map((x) => R(`${aux} ${x}`));
    }
    default: return [];
  }
}

// ══ SPANISH ════════════════════════════════════════════════════════════════
type Change = "e>ie" | "o>ue" | "e>i" | "u>ue";
interface EsEnt extends VerbInfo { pres?: string[]; pret?: string[]; impf?: string[]; fut?: string; change?: Change; yo?: string }
type EsX = Omit<Partial<EsEnt>, "pres" | "pret" | "impf"> & { pres?: string; pret?: string; impf?: string };
const S = (inf: string, en: string, tier: Tier, theme: string, kind: Kind, x: EsX = {}): EsEnt => ({ inf, en, tier, theme, kind, ...x, pres: x.pres ? w(x.pres) : undefined, pret: x.pret ? w(x.pret) : undefined, impf: x.impf ? w(x.impf) : undefined });
const strong = (st: string, j = false) => ["e", "iste", "o", "imos", "isteis", j ? "eron" : "ieron"].map((x) => st + x).join(" ");
const ES: EsEnt[] = [
  S("ser", "to be", "KS3", "core", "irregular", { pres: "soy eres es somos sois son", pret: "fui fuiste fue fuimos fuisteis fueron", impf: "era eras era éramos erais eran" }),
  S("estar", "to be (state / place)", "KS3", "core", "irregular", { pres: "estoy estás está estamos estáis están", pret: strong("estuv") }),
  S("tener", "to have", "KS3", "core", "irregular", { change: "e>ie", yo: "tengo", pret: strong("tuv"), fut: "tendr" }),
  S("ir", "to go", "KS3", "core", "irregular", { pres: "voy vas va vamos vais van", pret: "fui fuiste fue fuimos fuisteis fueron", impf: "iba ibas iba íbamos ibais iban" }),
  S("hacer", "to do / make", "KS3", "core", "irregular", { yo: "hago", pret: "hice hiciste hizo hicimos hicisteis hicieron", fut: "har" }),
  S("poder", "to be able to (can)", "KS3", "modals", "irregular", { change: "o>ue", pret: strong("pud"), fut: "podr" }),
  S("querer", "to want / love", "KS3", "modals", "irregular", { change: "e>ie", pret: strong("quis"), fut: "querr" }),
  S("decir", "to say / tell", "KS3", "communication", "irregular", { change: "e>i", yo: "digo", pret: strong("dij", true), fut: "dir" }),
  S("ver", "to see", "KS3", "daily life", "irregular", { pres: "veo ves ve vemos veis ven", pret: "vi viste vio vimos visteis vieron", impf: "veía veías veía veíamos veíais veían" }),
  S("dar", "to give", "KS3", "daily life", "irregular", { pres: "doy das da damos dais dan", pret: "di diste dio dimos disteis dieron" }),
  S("saber", "to know (a fact)", "KS3", "core", "irregular", { yo: "sé", pret: strong("sup"), fut: "sabr" }),
  S("venir", "to come", "KS3", "travel", "irregular", { change: "e>ie", yo: "vengo", pret: strong("vin"), fut: "vendr" }),
  S("poner", "to put", "KS3", "daily life", "irregular", { yo: "pongo", pret: strong("pus"), fut: "pondr" }),
  S("salir", "to go out", "KS3", "free time", "irregular", { yo: "salgo", fut: "saldr" }),
  S("traer", "to bring", "KS4", "daily life", "irregular", { yo: "traigo", pret: strong("traj", true) }),
  S("oír", "to hear", "KS4", "daily life", "irregular", { pres: "oigo oyes oye oímos oís oyen", fut: "oir" }),
  S("conocer", "to know (a person / place)", "KS3", "core", "irregular", { yo: "conozco" }),
  S("conducir", "to drive", "KS4", "travel", "irregular", { yo: "conduzco", pret: strong("conduj", true) }),
  S("dormir", "to sleep", "KS3", "daily life", "stem", { change: "o>ue" }), S("volver", "to return", "KS3", "travel", "stem", { change: "o>ue" }),
  S("encontrar", "to find", "KS3", "daily life", "stem", { change: "o>ue" }), S("costar", "to cost", "KS3", "shopping", "stem", { change: "o>ue" }),
  S("almorzar", "to have lunch", "KS3", "food & drink", "stem", { change: "o>ue" }),
  S("pedir", "to ask for / order", "KS3", "food & drink", "stem", { change: "e>i" }), S("servir", "to serve", "KS4", "food & drink", "stem", { change: "e>i" }),
  S("repetir", "to repeat", "KS3", "school", "stem", { change: "e>i" }), S("seguir", "to follow / continue", "KS4", "travel", "stem", { change: "e>i", yo: "sigo" }),
  S("jugar", "to play", "KS3", "free time", "stem", { change: "u>ue" }),
  S("pensar", "to think", "KS3", "communication", "stem", { change: "e>ie" }), S("empezar", "to begin", "KS3", "school", "stem", { change: "e>ie" }),
  S("preferir", "to prefer", "KS3", "free time", "stem", { change: "e>ie" }), S("entender", "to understand", "KS3", "school", "stem", { change: "e>ie" }),
  S("sentir", "to feel", "KS4", "communication", "stem", { change: "e>ie" }),
  S("leer", "to read", "KS3", "free time", "irregular"), S("creer", "to believe", "KS4", "communication", "irregular"),
  // regular
  S("hablar", "to speak", "KS3", "communication", "regular"), S("comer", "to eat", "KS3", "food & drink", "regular"), S("vivir", "to live", "KS3", "home & family", "regular"),
  S("trabajar", "to work", "KS3", "school", "regular"), S("estudiar", "to study", "KS3", "school", "regular"), S("beber", "to drink", "KS3", "food & drink", "regular"),
  S("escribir", "to write", "KS3", "school", "regular"), S("comprar", "to buy", "KS3", "shopping", "regular"), S("mirar", "to look at / watch", "KS3", "free time", "regular"),
  S("escuchar", "to listen to", "KS3", "free time", "regular"), S("bailar", "to dance", "KS3", "free time", "regular"), S("cantar", "to sing", "KS3", "free time", "regular"),
  S("nadar", "to swim", "KS3", "free time", "regular"), S("visitar", "to visit", "KS3", "travel", "regular"), S("aprender", "to learn", "KS3", "school", "regular"),
  S("correr", "to run", "KS3", "free time", "regular"), S("abrir", "to open", "KS3", "daily life", "regular"), S("vender", "to sell", "KS3", "shopping", "regular"),
  S("llegar", "to arrive", "KS3", "travel", "regular"), S("buscar", "to look for", "KS3", "daily life", "regular"), S("tocar", "to play (instrument) / touch", "KS3", "free time", "regular"),
  S("comprender", "to understand", "KS3", "school", "regular"), S("compartir", "to share", "KS4", "daily life", "regular"), S("viajar", "to travel", "KS3", "travel", "regular"),
  S("levantarse", "to get up", "KS3", "daily routine", "regular"), S("ducharse", "to have a shower", "KS3", "daily routine", "regular"), S("llamarse", "to be called", "KS3", "home & family", "regular"),
  S("lavarse", "to wash (oneself)", "KS3", "daily routine", "regular"), S("acostarse", "to go to bed", "KS3", "daily routine", "stem", { change: "o>ue" }),
  S("vestirse", "to get dressed", "KS3", "daily routine", "stem", { change: "e>i" }), S("sentarse", "to sit down", "KS4", "daily routine", "stem", { change: "e>ie" }),
];
const ES_MAP = new Map(ES.map((e) => [e.inf, e]));
const ES_PRON = ["me", "te", "se", "nos", "os", "se"], ES_ENCL = ["me", "te", "se", "nos", "os", "se"];
const ES_IR = w("voy vas va vamos vais van");
const esType = (inf: string) => { const t = inf.slice(-2); return t === "ír" ? "ir" : t; };
function esEnt(verb: string): { e: EsEnt; refl: boolean; inf: string } {
  const refl = /(ar|er|ir|ír)se$/.test(verb), inf = refl ? verb.slice(0, -2) : verb;
  const e = ES_MAP.get(verb) ?? ES_MAP.get(inf) ?? { inf, en: "", tier: "KS4" as Tier, theme: "other", kind: "regular" as Kind };
  return { e, refl, inf };
}
const CH: Record<Change, [string, string]> = { "e>ie": ["e", "ie"], "o>ue": ["o", "ue"], "e>i": ["e", "i"], "u>ue": ["u", "ue"] };
function esPresent(e: EsEnt, inf: string): string[] {
  if (e.pres) return e.pres;
  const t = esType(inf), st = inf.slice(0, -2);
  const ends = t === "ar" ? ["o", "as", "a", "amos", "áis", "an"] : t === "er" ? ["o", "es", "e", "emos", "éis", "en"] : ["o", "es", "e", "imos", "ís", "en"];
  const ch = e.change ? lastReplace(st, CH[e.change][0], CH[e.change][1]) : st;
  const out = ends.map((x, i) => ([0, 1, 2, 5].includes(i) ? ch : st) + x);
  if (e.yo) out[0] = e.yo;
  return out;
}
function esPret(e: EsEnt, inf: string): string[] {
  if (e.pret) return e.pret;
  const t = esType(inf), st = inf.slice(0, -2);
  if (t === "ar") {
    const yo = st.endsWith("c") ? st.slice(0, -1) + "qué" : st.endsWith("g") ? st + "ué" : st.endsWith("z") ? st.slice(0, -1) + "cé" : st + "é";
    return [yo, ...["aste", "ó", "amos", "asteis", "aron"].map((x) => st + x)];
  }
  if (/[aeo]$/.test(st)) return [st + "í", st + "íste", st + "yó", st + "ímos", st + "ísteis", st + "yeron"];
  const st3 = t === "ir" && e.change ? (e.change === "o>ue" ? lastReplace(st, "o", "u") : e.change === "e>ie" || e.change === "e>i" ? lastReplace(st, "e", "i") : st) : st;
  return ["í", "iste", "ió", "imos", "isteis", "ieron"].map((x, i) => ((i === 2 || i === 5) ? st3 : st) + x);
}
function esForms(verb: string, tense: string, p: number): string[] {
  const { e, refl, inf } = esEnt(verb), R = (f: string) => (refl ? `${ES_PRON[p]} ${f}` : f);
  switch (tense) {
    case "present": return [R(esPresent(e, inf)[p]!)];
    case "preterito": return [R(esPret(e, inf)[p]!)];
    case "imperfecto": {
      if (e.impf) return [R(e.impf[p]!)];
      const t = esType(inf), st = inf.slice(0, -2);
      return [R(st + (t === "ar" ? ["aba", "abas", "aba", "ábamos", "abais", "aban"] : ["ía", "ías", "ía", "íamos", "íais", "ían"])[p]!)];
    }
    case "futuro_simple": case "condicional": {
      const st = e.fut ?? inf;
      return [R(st + (tense === "futuro_simple" ? ["é", "ás", "á", "emos", "éis", "án"] : ["ía", "ías", "ía", "íamos", "íais", "ían"])[p]!)];
    }
    case "futuro_proximo": {
      if (!refl) return [`${ES_IR[p]} a ${inf}`];
      return [`${ES_PRON[p]} ${ES_IR[p]} a ${inf}`, `${ES_IR[p]} a ${inf}${ES_ENCL[p]}`];
    }
    default: return [];
  }
}

// ══ GERMAN ═════════════════════════════════════════════════════════════════
interface DeEnt extends VerbInfo {
  pres?: string[]; sc?: string; over?: Partial<Record<number, string>>; pp?: string; aux?: "haben" | "sein"; sep?: string; base?: string;
  prat?: string[]; k2?: string[]; only?: string[];
}
type DeX = Omit<Partial<DeEnt>, "pres" | "prat" | "k2"> & { pres?: string; prat?: string; k2?: string };
const D = (inf: string, en: string, tier: Tier, theme: string, kind: Kind, x: DeX = {}): DeEnt => ({ inf, en, tier, theme, kind, ...x, pres: x.pres ? w(x.pres) : undefined, prat: x.prat ? w(x.prat) : undefined, k2: x.k2 ? w(x.k2) : undefined });
const DE: DeEnt[] = [
  D("sein", "to be", "KS3", "core", "irregular", { pres: "bin bist ist sind seid sind", prat: "war warst war waren wart waren", pp: "gewesen", aux: "sein", k2: "wäre wärst wäre wären wärt wären" }),
  D("haben", "to have", "KS3", "core", "irregular", { pres: "habe hast hat haben habt haben", prat: "hatte hattest hatte hatten hattet hatten", pp: "gehabt", k2: "hätte hättest hätte hätten hättet hätten" }),
  D("werden", "to become / will", "KS3", "core", "irregular", { pres: "werde wirst wird werden werdet werden", prat: "wurde wurdest wurde wurden wurdet wurden", pp: "geworden", aux: "sein" }),
  D("wissen", "to know (a fact)", "KS3", "core", "irregular", { pres: "weiß weißt weiß wissen wisst wissen", prat: "wusste wusstest wusste wussten wusstet wussten", pp: "gewusst", k2: "wüsste wüsstest wüsste wüssten wüsstet wüssten" }),
  D("können", "to be able to (can)", "KS3", "modals", "irregular", { pres: "kann kannst kann können könnt können", prat: "konnte konntest konnte konnten konntet konnten", pp: "gekonnt", k2: "könnte könntest könnte könnten könntet könnten" }),
  D("müssen", "to have to (must)", "KS3", "modals", "irregular", { pres: "muss musst muss müssen müsst müssen", prat: "musste musstest musste mussten musstet mussten", pp: "gemusst", k2: "müsste müsstest müsste müssten müsstet müssten" }),
  D("wollen", "to want to", "KS3", "modals", "irregular", { pres: "will willst will wollen wollt wollen", prat: "wollte wolltest wollte wollten wolltet wollten", pp: "gewollt", k2: "wollte wolltest wollte wollten wolltet wollten" }),
  D("sollen", "to be supposed to (should)", "KS3", "modals", "irregular", { pres: "soll sollst soll sollen sollt sollen", prat: "sollte solltest sollte sollten solltet sollten", pp: "gesollt", k2: "sollte solltest sollte sollten solltet sollten" }),
  D("dürfen", "to be allowed to (may)", "KS3", "modals", "irregular", { pres: "darf darfst darf dürfen dürft dürfen", prat: "durfte durftest durfte durften durftet durften", pp: "gedurft", k2: "dürfte dürftest dürfte dürften dürftet dürften" }),
  D("mögen", "to like", "KS3", "modals", "irregular", { pres: "mag magst mag mögen mögt mögen", prat: "mochte mochtest mochte mochten mochtet mochten", pp: "gemocht", k2: "möchte möchtest möchte möchten möchtet möchten" }),
  D("möchten", "would like to", "KS3", "modals", "irregular", { pres: "möchte möchtest möchte möchten möchtet möchten", only: ["present"] }),
  D("tun", "to do", "KS4", "core", "irregular", { pres: "tue tust tut tun tut tun", pp: "getan" }),
  D("gehen", "to go", "KS3", "core", "irregular", { pp: "gegangen", aux: "sein" }), D("kommen", "to come", "KS3", "core", "irregular", { pp: "gekommen", aux: "sein" }),
  D("nehmen", "to take", "KS3", "daily life", "irregular", { sc: "nimm", pp: "genommen" }), D("geben", "to give", "KS3", "daily life", "irregular", { sc: "gib", pp: "gegeben" }),
  D("fahren", "to go / drive", "KS3", "travel", "irregular", { sc: "fähr", pp: "gefahren", aux: "sein" }), D("sehen", "to see", "KS3", "daily life", "irregular", { sc: "sieh", pp: "gesehen" }),
  D("lesen", "to read", "KS3", "free time", "irregular", { sc: "lies", pp: "gelesen" }), D("essen", "to eat", "KS3", "food & drink", "irregular", { sc: "iss", pp: "gegessen" }),
  D("schlafen", "to sleep", "KS3", "daily routine", "irregular", { sc: "schläf", pp: "geschlafen" }), D("laufen", "to run / walk", "KS3", "free time", "irregular", { sc: "läuf", pp: "gelaufen", aux: "sein" }),
  D("helfen", "to help", "KS3", "home & family", "irregular", { sc: "hilf", pp: "geholfen" }), D("sprechen", "to speak", "KS3", "communication", "irregular", { sc: "sprich", pp: "gesprochen" }),
  D("treffen", "to meet", "KS3", "free time", "irregular", { sc: "triff", pp: "getroffen" }), D("tragen", "to wear / carry", "KS3", "daily life", "irregular", { sc: "träg", pp: "getragen" }),
  D("waschen", "to wash", "KS3", "daily routine", "irregular", { sc: "wäsch", pp: "gewaschen" }), D("halten", "to hold / stop", "KS4", "daily life", "irregular", { sc: "hält", over: { 1: "hältst", 2: "hält" }, pp: "gehalten" }),
  D("laden", "to load / invite", "KS4", "daily life", "irregular", { sc: "läd", pp: "geladen" }), D("fangen", "to catch", "KS4", "free time", "irregular", { sc: "fäng", pp: "gefangen" }),
  D("vergessen", "to forget", "KS3", "school", "irregular", { sc: "vergiss", pp: "vergessen" }),
  D("stehen", "to stand", "KS3", "daily life", "irregular", { pp: "gestanden" }), D("bringen", "to bring", "KS3", "daily life", "irregular", { pp: "gebracht" }),
  D("denken", "to think", "KS3", "communication", "irregular", { pp: "gedacht" }), D("finden", "to find / think", "KS3", "daily life", "irregular", { pp: "gefunden" }),
  D("schreiben", "to write", "KS3", "school", "irregular", { pp: "geschrieben" }), D("trinken", "to drink", "KS3", "food & drink", "irregular", { pp: "getrunken" }),
  D("fliegen", "to fly", "KS3", "travel", "irregular", { pp: "geflogen", aux: "sein" }), D("schwimmen", "to swim", "KS3", "free time", "irregular", { pp: "geschwommen", aux: "sein" }),
  D("singen", "to sing", "KS3", "free time", "irregular", { pp: "gesungen" }), D("sitzen", "to sit", "KS3", "daily life", "irregular", { pp: "gesessen" }),
  D("liegen", "to lie", "KS3", "daily life", "irregular", { pp: "gelegen" }), D("bleiben", "to stay", "KS3", "travel", "irregular", { pp: "geblieben", aux: "sein" }),
  D("rufen", "to call", "KS3", "communication", "irregular", { pp: "gerufen" }), D("steigen", "to climb", "KS3", "travel", "irregular", { pp: "gestiegen", aux: "sein" }),
  D("ziehen", "to pull", "KS3", "daily life", "irregular", { pp: "gezogen" }), D("verstehen", "to understand", "KS3", "school", "irregular", { pp: "verstanden" }),
  D("bekommen", "to receive", "KS3", "daily life", "irregular", { pp: "bekommen" }),
  // separable (base + prefix; forms come from the base verb)
  D("aufstehen", "to get up", "KS3", "daily routine", "irregular", { base: "stehen", sep: "auf", aux: "sein" }), D("ankommen", "to arrive", "KS3", "travel", "irregular", { base: "kommen", sep: "an", aux: "sein" }),
  D("einkaufen", "to shop", "KS3", "shopping", "regular", { base: "kaufen", sep: "ein" }), D("anrufen", "to phone", "KS3", "communication", "irregular", { base: "rufen", sep: "an" }),
  D("fernsehen", "to watch TV", "KS3", "free time", "irregular", { base: "sehen", sep: "fern" }), D("mitkommen", "to come along", "KS3", "free time", "irregular", { base: "kommen", sep: "mit", aux: "sein" }),
  D("aussteigen", "to get off", "KS3", "travel", "irregular", { base: "steigen", sep: "aus", aux: "sein" }), D("abfahren", "to depart", "KS3", "travel", "irregular", { base: "fahren", sep: "ab", aux: "sein" }),
  D("aufräumen", "to tidy up", "KS3", "home & family", "regular", { base: "räumen", sep: "auf" }), D("abholen", "to collect", "KS3", "daily life", "regular", { base: "holen", sep: "ab" }),
  D("mitbringen", "to bring along", "KS3", "daily life", "irregular", { base: "bringen", sep: "mit" }), D("anfangen", "to begin", "KS3", "school", "irregular", { base: "fangen", sep: "an" }),
  D("anziehen", "to put on", "KS3", "daily routine", "irregular", { base: "ziehen", sep: "an" }), D("aufwachen", "to wake up", "KS3", "daily routine", "regular", { base: "wachen", sep: "auf", aux: "sein" }),
  // regular (weak)
  D("spielen", "to play", "KS3", "free time", "regular"), D("machen", "to do / make", "KS3", "daily life", "regular"), D("lernen", "to learn", "KS3", "school", "regular"),
  D("wohnen", "to live", "KS3", "home & family", "regular"), D("kaufen", "to buy", "KS3", "shopping", "regular"), D("hören", "to hear / listen", "KS3", "free time", "regular"),
  D("sagen", "to say", "KS3", "communication", "regular"), D("arbeiten", "to work", "KS3", "school", "regular"), D("tanzen", "to dance", "KS3", "free time", "regular"),
  D("reisen", "to travel", "KS3", "travel", "regular", { aux: "sein" }), D("kochen", "to cook", "KS3", "food & drink", "regular"), D("besuchen", "to visit", "KS3", "travel", "regular"),
  D("studieren", "to study", "KS4", "school", "regular"), D("warten", "to wait", "KS3", "travel", "regular"), D("öffnen", "to open", "KS4", "daily life", "regular"),
  D("baden", "to bathe", "KS4", "daily routine", "regular"), D("wandern", "to hike", "KS3", "free time", "regular", { aux: "sein" }), D("sammeln", "to collect", "KS4", "free time", "regular"),
  D("räumen", "to clear", "KS4", "home & family", "regular"), D("holen", "to fetch", "KS4", "daily life", "regular"), D("wachen", "to be awake", "KS4", "daily life", "regular"),
  D("sich waschen", "to wash (oneself)", "KS3", "daily routine", "irregular", { base: "waschen" }), D("sich anziehen", "to get dressed", "KS3", "daily routine", "irregular", { base: "anziehen" }),
  D("sich freuen", "to be pleased", "KS3", "communication", "regular", { base: "freuen" }), D("sich treffen", "to meet up", "KS3", "free time", "irregular", { base: "treffen" }),
];
const DE_MAP = new Map(DE.map((e) => [e.inf, e]));
const DE_REFL = ["mich", "dich", "sich", "uns", "euch", "sich"];
const DE_WERDEN = w("werde wirst wird werden werdet werden"), DE_WUERDE = w("würde würdest würde würden würdet würden");
interface DeRes { e: DeEnt; base: string; sep?: string; refl: boolean; inf: string }
function deResolve(verb: string): DeRes {
  const refl = verb.startsWith("sich "), inf = refl ? verb.slice(5) : verb;
  const chain: DeEnt[] = [];
  let cur = DE_MAP.get(verb) ?? DE_MAP.get(inf);
  while (cur) { chain.push(cur); cur = cur.base ? DE_MAP.get(cur.base) : undefined; }
  if (!chain.length) return { e: { inf, en: "", tier: "KS4", theme: "other", kind: "regular" }, base: inf, refl, inf };
  const last = chain[chain.length - 1]!, base = last.base ?? last.inf;
  const e = {} as Record<string, unknown>;
  for (const c of [...chain].reverse()) for (const [k, v] of Object.entries(c)) if (v !== undefined) e[k] = v;
  const ent = e as unknown as DeEnt;
  return { e: ent, base, sep: ent.sep, refl, inf: (ent.sep ?? "") + base };
}
const deStem = (b: string) => (/(eln|ern)$/.test(b) ? b.slice(0, -1) : b.slice(0, b.endsWith("en") ? -2 : -1));
/** e-insertion: stems ending -d / -t, or a consonant + m/n (arbeit-, find-, öffn-, atm-, rechn-) — but not -lm/-rn/-hn/-mm (lern-, wohn-, komm-). */
const needsE = (st: string) => {
  if (/[dt]$/.test(st)) return true;
  if (!/[mn]$/.test(st)) return false;
  const pr = st[st.length - 2] ?? "";
  if (/[aeiouäöüylrmn]/.test(pr)) return false;
  return pr === "h" ? /chn$/.test(st) : true;
};
function dePres(e: DeEnt, base: string): string[] {
  if (e.pres) return e.pres;
  const st = deStem(base), sc = e.sc ?? st, e2 = !e.sc && needsE(st), sib = /[sßxz]$/.test(sc);
  const ich = base.endsWith("eln") ? st.slice(0, -2) + "le" : st + "e";
  const du = e.over?.[1] ?? (sib ? sc + "t" : sc + (e2 ? "est" : "st"));
  const er = e.over?.[2] ?? sc + (e2 ? "et" : "t");
  return [ich, du, er, base, st + (needsE(st) ? "et" : "t"), base];
}
const noGe = (b: string) => /^(be|ge|er|ver|zer|ent|emp|miss)/.test(b) || b.endsWith("ieren");
function dePP(r: DeRes): string {
  const { e, base, sep } = r;
  let core = e.pp;
  if (!core) { const st = deStem(base), t = needsE(st) ? "et" : "t"; core = noGe(base) ? st + t : "ge" + st + t; }
  return (sep ?? "") + core;
}
const deAux = (e: DeEnt) => (e.aux === "sein" ? w("bin bist ist sind seid sind") : w("habe hast hat haben habt haben"));
function deForms(verb: string, tense: string, p: number): string[] {
  const r = deResolve(verb), { e, refl, sep } = r;
  if (e.only && !e.only.includes(tense)) return [];
  const rf = refl ? ` ${DE_REFL[p]}` : "";
  switch (tense) {
    case "present": return [`${dePres(e, r.base)[p]}${rf}${sep ? " " + sep : ""}`];
    case "perfekt": return [`${deAux(e)[p]}${rf} ${dePP(r)}`];
    case "praeteritum": return e.prat && !sep ? [`${e.prat[p]}${rf}`] : [];
    case "futur": return [`${DE_WERDEN[p]}${rf} ${r.inf}`];
    case "konjunktiv2": return uniq([`${DE_WUERDE[p]}${rf} ${r.inf}`, ...(e.k2 ? [`${e.k2[p]}${rf}`] : [])]);
    default: return [];
  }
}

// ══ public API ═════════════════════════════════════════════════════════════
export const VERBS: Record<Lang, VerbInfo[]> = {
  fr: FR.map(({ inf, en, tier, theme, kind }) => ({ inf, en, tier, theme, kind })),
  es: ES.map(({ inf, en, tier, theme, kind }) => ({ inf, en, tier, theme, kind })),
  de: DE.map(({ inf, en, tier, theme, kind }) => ({ inf, en, tier, theme, kind })),
};
export const THEMES: Record<Lang, string[]> = { fr: [], es: [], de: [] };
(["fr", "es", "de"] as Lang[]).forEach((l) => { THEMES[l] = [...new Set(VERBS[l].map((v) => v.theme))].sort(); });
export const verbInfo = (lang: Lang, inf: string): VerbInfo | undefined => VERBS[lang].find((v) => v.inf === inf);

/** Does this verb have this tense? (German Präteritum is taught for sein/haben/werden/wissen/modals only; möchten only has the present.) */
export function supports(lang: Lang, verb: string, tense: string): boolean {
  if (!TENSES[lang].some((t) => t.id === tense)) return false;
  return conjugate(lang, verb, tense, 0).length > 0;
}

/** Every accepted form (canonical first) for one verb / tense / person (0..5). Subject pronoun NOT included. [] when the verb has no such tense. */
export function conjugate(lang: Lang, verb: string, tense: string, person: number): string[] {
  if (!Number.isInteger(person) || person < 0 || person > 5) return [];
  const v = verb.trim().toLowerCase();
  const out = lang === "fr" ? frForms(v, tense, person) : lang === "es" ? esForms(v, tense, person) : deForms(v, tense, person);
  return uniq(out);
}

/** The pronoun (with French elision) to show beside a form: j'ai · je parle · ich habe. Spanish subjects are optional, so the bare form is returned with the pronoun in front only if `always`. */
export function subjectLabel(lang: Lang, person: number, form: string): string {
  const s = PERSONS[lang][person]!;
  if (lang === "fr" && person === 0) return isVowelStart(form) ? "j'" : "je";
  return s;
}
export function withSubject(lang: Lang, person: number, form: string, always = false): string {
  if (lang === "es" && !always) return form;
  const l = subjectLabel(lang, person, form);
  return l.endsWith("'") ? l + form : `${l} ${form}`;
}

/** Everything a pupil might reasonably type for a form: the bare form, and with the subject pronoun (il / elle, er / sie / es, j'ai …). */
export function answerVariants(lang: Lang, person: number, forms: string[]): string[] {
  const labels = PERSONS[lang][person]!.split("/");
  return uniq(forms.flatMap((f) => [f, ...(lang === "fr" && person === 0 ? [withSubject("fr", 0, f)] : labels.map((l) => `${l} ${f}`))]));
}
