// npm run hub:widgets — pull every plain-JS lesson widget from scratch/prototype/widgets/**/*.js into the app.
//
// The prototype widgets are one file each that register themselves with
//     WIDGETS.myWidget = { title, intro, html(), init() }
// and use the helper globals `$ esc md shuffle addXP gcd`. This script wraps each file in a function
// (features/learninghub/lesson/widgets/legacy/<name>.gen.ts — no eval, the bundler compiles it) plus a manifest and a copy of
// rules.json (which widget suits which lesson). <LegacyWidget> mounts them. Re-run it whenever the widget files change; it is
// also run before `npm run build`. If scratch/prototype/widgets is missing the committed generated files are left alone.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "scratch/prototype/widgets");
const out = path.join(root, "features/learninghub/lesson/widgets/legacy");

if (!fs.existsSync(src)) { console.log("hub:widgets — no scratch/prototype/widgets folder; keeping the generated files as they are."); process.exit(0); }
fs.mkdirSync(out, { recursive: true });

const files = [];
const walk = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (e.name.startsWith("_") || e.name.startsWith(".") || e.name === "shots" || e.name === "node_modules") continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p); else if (e.name.endsWith(".js")) files.push(p);
  }
};
walk(src);

const ident = (rel) => rel.replace(/\.js$/, "").replace(/[^A-Za-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "widget";
const used = new Set();
const entries = files.map((f) => {
  const rel = path.relative(src, f);
  let name = ident(rel), n = 2;
  while (used.has(name)) name = `${ident(rel)}_${n++}`;
  used.add(name);
  return { rel, name, code: fs.readFileSync(f, "utf8") };
});

for (const e of entries) {
  const body = e.code.replace(/\r\n/g, "\n");
  fs.writeFileSync(path.join(out, `${e.name}.gen.ts`),
`// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/hub-widgets.mjs from scratch/prototype/widgets/${e.rel} — do not edit; run \`npm run hub:widgets\`.
import type { LegacyHelpers } from "../legacyRuntime";
export default function register(H: LegacyHelpers) {
  const { WIDGETS, $, esc, md, shuffle, addXP, gcd } = H;
  (function () {
${body}
  }).call(globalThis);
}
`);
}

fs.writeFileSync(path.join(out, "manifest.gen.ts"),
`// GENERATED by scripts/hub-widgets.mjs — do not edit; run \`npm run hub:widgets\`.
import type { LegacyHelpers } from "../legacyRuntime";
${entries.map((e) => `import ${e.name} from "./${e.name}.gen";`).join("\n")}

export const LEGACY_REGISTRARS: ((h: LegacyHelpers) => void)[] = [${entries.map((e) => e.name).join(", ")}];
`);

const rulesFile = path.join(src, "rules.json");
let rules = "[]";
if (fs.existsSync(rulesFile)) { try { JSON.parse(fs.readFileSync(rulesFile, "utf8")); rules = fs.readFileSync(rulesFile, "utf8"); } catch { console.warn("hub:widgets — rules.json is not valid JSON; ignoring it"); } }
fs.writeFileSync(path.join(out, "rules.gen.json"), rules);

// Drop generated files for widgets that no longer exist.
const keep = new Set([...entries.map((e) => `${e.name}.gen.ts`), "manifest.gen.ts", "rules.gen.json"]);
for (const f of fs.readdirSync(out)) if (f.endsWith(".gen.ts") || f.endsWith(".gen.json")) if (!keep.has(f)) fs.rmSync(path.join(out, f));
console.log(`hub:widgets — ${entries.length} widget file(s): ${entries.map((e) => e.rel).join(", ") || "(none)"}`);
