// (b) Literal emoji: ONLY for concrete nouns where the emoji is an unambiguous depiction of that very thing (Unicode name given). Never metaphorical,
// never decorative, never for abstract or polysemous words. Matching is on the WHOLE WORD (or phrase, plural of the last word allowed) in the
// slide's own text; there is no fuzzy or partial matching. Words that have another common meaning (bat, mouse-as-computer, seal, orange, plane, star,
// bank, rock, bulb, wave, heart, hand, foot, tea, scales, chips, crane, nut, ...) are deliberately NOT in this table.
import type { EmojiEntry, Subject } from "./types";
import { registerLanguageEmoji } from "./ext-languages-allow"; // X5

const ALL: Subject[] = ["Science", "French", "Spanish", "German"];
const SCI: Subject[] = ["Science"];
const LANG: Subject[] = ["French", "Spanish", "German"];
type X = Partial<Pick<EmojiEntry, "fr" | "es" | "de" | "note">>;
const e = (emoji: string, name: string, words: string[], subjects: Subject[], x: X = {}): EmojiEntry => ({ emoji, name, words, subjects, ...x });

export const EMOJI: EmojiEntry[] = [
  // animals (Science KS1/KS2 + language vocabulary)
  e("🐕", "dog", ["dog"], ALL, { fr: ["chien"], es: ["perro"], de: ["hund"] }),
  e("🐈", "cat", ["cat"], ALL, { fr: ["chat"], es: ["gato"], de: ["katze"] }),
  e("🐎", "horse", ["horse"], ALL, { fr: ["cheval"], es: ["caballo"], de: ["pferd"] }),
  e("🐄", "cow", ["cow"], ALL, { fr: ["vache"], es: ["vaca"], de: ["kuh"] }),
  e("🐖", "pig", ["pig"], ALL, { fr: ["cochon"], es: ["cerdo"], de: ["schwein"] }),
  e("🐑", "ewe (sheep)", ["sheep"], ALL, { fr: ["mouton"], es: ["oveja"], de: ["schaf"] }),
  e("🐇", "rabbit", ["rabbit"], ALL, { fr: ["lapin"], es: ["conejo"], de: ["kaninchen"] }),
  e("🐟", "fish", ["fish"], SCI, { }),
  e("🐦", "bird", ["bird"], ALL, { fr: ["oiseau"], es: ["pajaro", "pájaro"], de: ["vogel"] }),
  e("🦋", "butterfly", ["butterfly"], ALL, { fr: ["papillon"], es: ["mariposa"], de: ["schmetterling"] }),
  e("🐝", "honeybee", ["bee"], ALL, { fr: ["abeille"], es: ["abeja"], de: ["biene"] }),
  e("🐜", "ant", ["ant"], ALL, { fr: ["fourmi"], es: ["hormiga"], de: ["ameise"] }),
  e("🐌", "snail", ["snail"], ALL, { fr: ["escargot"], es: ["caracol"], de: ["schnecke"] }),
  e("🐸", "frog", ["frog"], ALL, { fr: ["grenouille"], es: ["rana"], de: ["frosch"] }),
  e("🐍", "snake", ["snake"], ALL, { fr: ["serpent"], es: ["serpiente"], de: ["schlange"] }),
  e("🐘", "elephant", ["elephant"], ALL, { fr: ["éléphant", "elephant"], es: ["elefante"], de: ["elefant"] }),
  e("🦁", "lion", ["lion"], ALL, { fr: ["lion"], es: ["león", "leon"], de: ["löwe", "lowe"] }),
  e("🐒", "monkey", ["monkey"], ALL, { fr: ["singe"], es: ["mono"], de: ["affe"] }),
  e("🐧", "penguin", ["penguin"], ALL, { fr: ["pingouin", "manchot"], es: ["pingüino", "pinguino"], de: ["pinguin"] }),
  e("🦉", "owl", ["owl"], ALL, { fr: ["hibou"], es: ["búho", "buho"], de: ["eule"] }),
  e("🦊", "fox", ["fox"], ALL, { fr: ["renard"], es: ["zorro"], de: ["fuchs"] }),
  e("🐿️", "chipmunk (squirrel)", ["squirrel"], ALL, { fr: ["écureuil", "ecureuil"], es: ["ardilla"], de: ["eichhörnchen"] }),
  e("🦔", "hedgehog", ["hedgehog"], ALL, { fr: ["hérisson", "herisson"], es: ["erizo"], de: ["igel"] }),
  e("🐺", "wolf", ["wolf"], ALL, { fr: ["loup"], es: ["lobo"], de: ["wolf"] }),
  e("🐅", "tiger", ["tiger"], ALL, { fr: ["tigre"], es: ["tigre"], de: ["tiger"] }),
  e("🦒", "giraffe", ["giraffe"], ALL, { fr: ["girafe"], es: ["jirafa"], de: ["giraffe"] }),
  e("🦓", "zebra", ["zebra"], ALL, { fr: ["zèbre", "zebre"], es: ["cebra"], de: ["zebra"] }),
  e("🐊", "crocodile", ["crocodile"], ALL, { fr: ["crocodile"], es: ["cocodrilo"], de: ["krokodil"] }),
  e("🐋", "spouting whale", ["whale"], ALL, { fr: ["baleine"], es: ["ballena"], de: ["wal"] }),
  e("🐬", "dolphin", ["dolphin"], ALL, { fr: ["dauphin"], es: ["delfín", "delfin"], de: ["delfin"] }),
  e("🦈", "shark", ["shark"], ALL, { fr: ["requin"], es: ["tiburón", "tiburon"], de: ["hai"] }),
  e("🐙", "octopus", ["octopus"], ALL, { fr: ["pieuvre"], es: ["pulpo"], de: ["krake"] }),
  e("🕷️", "spider", ["spider"], ALL, { fr: ["araignée", "araignee"], es: ["araña", "arana"], de: ["spinne"] }),
  e("🐞", "lady beetle", ["ladybird", "ladybug"], SCI),
  e("🦎", "lizard", ["lizard"], ALL, { fr: ["lézard", "lezard"], es: ["lagarto"], de: ["eidechse"] }),
  e("🐁", "mouse", ["mouse", "mice"], SCI),
  // plants, weather, land
  e("🌳", "deciduous tree", ["tree"], ALL, { fr: ["arbre"], es: ["árbol", "arbol"], de: ["baum"] }),
  e("🌵", "cactus", ["cactus"], ALL, { fr: ["cactus"], es: ["cactus"], de: ["kaktus"] }),
  e("🌻", "sunflower", ["sunflower"], ALL, { fr: ["tournesol"], es: ["girasol"], de: ["sonnenblume"] }),
  e("🍄", "mushroom", ["mushroom"], ALL, { fr: ["champignon"], es: ["champiñón", "champinon", "seta"], de: ["pilz"] }),
  e("☀️", "sun", ["sun"], ALL, { fr: ["soleil"], es: ["sol"], de: ["sonne"], note: "the Sun / a sunny sky" }),
  e("☁️", "cloud", ["cloud"], ALL, { fr: ["nuage"], es: ["nube"], de: ["wolke"] }),
  e("🌈", "rainbow", ["rainbow"], ALL, { fr: ["arc-en-ciel"], es: ["arcoíris", "arcoiris"], de: ["regenbogen"] }),
  e("❄️", "snowflake", ["snowflake"], ALL, { fr: ["flocon de neige"], es: ["copo de nieve"], de: ["schneeflocke"] }),
  e("🌧️", "cloud with rain", ["rain"], ALL, { fr: ["pluie"], es: ["lluvia"], de: ["regen"] }),
  e("⚡", "high voltage (lightning)", ["lightning"], ALL, { es: ["rayo", "relámpago"], de: ["blitz"] }),
  e("🌋", "volcano", ["volcano"], ALL, { fr: ["volcan"], es: ["volcán", "volcan"], de: ["vulkan"] }),
  e("⛰️", "mountain", ["mountain"], ALL, { fr: ["montagne"], es: ["montaña", "montana"], de: ["berg"] }),
  e("🔥", "fire", ["fire", "flame"], SCI),
  // food
  e("🍎", "red apple", ["apple"], ALL, { fr: ["pomme"], es: ["manzana"], de: ["apfel"] }),
  e("🍌", "banana", ["banana"], ALL, { fr: ["banane"], es: ["plátano", "platano", "banana"], de: ["banane"] }),
  e("🍞", "bread", ["bread"], ALL, { fr: ["pain"], es: ["pan"], de: ["brot"] }),
  e("🥚", "egg", ["egg"], ALL, { fr: ["œuf", "oeuf"], es: ["huevo"], de: [] }),
  e("🥛", "glass of milk", ["milk"], ALL, { fr: ["lait"], es: ["leche"], de: ["milch"] }),
  e("🧀", "cheese wedge", ["cheese"], ALL, { fr: ["fromage"], es: ["queso"], de: ["käse", "kase"] }),
  e("🍕", "pizza", ["pizza"], ALL, { fr: ["pizza"], es: ["pizza"], de: ["pizza"] }),
  e("🍰", "shortcake (cake)", ["cake"], ALL, { fr: ["gâteau", "gateau"], es: ["tarta"], de: ["kuchen"] }),
  e("🍦", "soft ice cream", ["ice cream"], ALL, { es: ["helado"], de: [] }),
  e("🍓", "strawberry", ["strawberry"], ALL, { fr: ["fraise"], es: ["fresa"], de: ["erdbeere"] }),
  e("🍇", "grapes", ["grapes", "grape"], ALL, { fr: ["raisin"], es: ["uva"], de: ["traube"] }),
  e("🍋", "lemon", ["lemon"], ALL, { fr: ["citron"], es: ["limón", "limon"], de: ["zitrone"] }),
  e("🍐", "pear", ["pear"], ALL, { fr: ["poire"], es: ["pera"], de: ["birne"] }),
  e("🍒", "cherries", ["cherry", "cherries"], ALL, { fr: ["cerise"], es: ["cereza"], de: ["kirsche"] }),
  e("🥕", "carrot", ["carrot"], ALL, { fr: ["carotte"], es: ["zanahoria"], de: ["karotte", "möhre"] }),
  e("🍅", "tomato", ["tomato"], ALL, { fr: ["tomate"], es: ["tomate"], de: ["tomate"] }),
  e("🥔", "potato", ["potato"], ALL, { fr: ["pomme de terre"], es: ["patata"], de: ["kartoffel"] }),
  e("🍚", "cooked rice", ["rice"], ALL, { fr: ["riz"], es: ["arroz"], de: ["reis"] }),
  e("🥐", "croissant", ["croissant"], ALL, { fr: ["croissant"], es: ["croissant"], de: ["croissant"] }),
  e("🥨", "pretzel", ["pretzel"], ALL, { fr: ["bretzel"], es: ["pretzel"], de: ["brezel"] }),
  e("🍫", "chocolate bar", ["chocolate"], ALL, { fr: ["chocolat"], es: ["chocolate"], de: ["schokolade"] }),
  e("🍯", "honey pot", ["honey"], ALL, { fr: ["miel"], es: ["miel"], de: ["honig"] }),
  // home, places, transport
  e("🏠", "house", ["house"], ALL, { fr: ["maison"], es: ["casa"], de: ["haus"] }),
  e("🏫", "school", ["school"], ALL, { fr: ["école", "ecole"], es: ["escuela", "colegio"], de: ["schule"] }),
  e("🏥", "hospital", ["hospital"], ALL, { fr: ["hôpital", "hopital"], es: ["hospital"], de: ["krankenhaus"] }),
  e("🏰", "castle", ["castle"], ALL, { fr: ["château", "chateau"], es: ["castillo"], de: ["schloss", "burg"] }),
  e("⛪", "church", ["church"], ALL, { fr: ["église", "eglise"], es: ["iglesia"], de: ["kirche"] }),
  e("🛏️", "bed", ["bed"], ALL, { fr: ["lit"], es: ["cama"], de: ["bett"] }),
  e("🚪", "door", ["door"], ALL, { fr: ["porte"], es: ["puerta"], de: ["tür", "tur"] }),
  e("🛋️", "couch and lamp (sofa)", ["sofa"], ALL, { fr: ["canapé", "canape"], es: ["sofá", "sofa"], de: ["sofa"] }),
  e("🚗", "automobile (car)", ["car"], ALL, { fr: ["voiture"], es: ["coche"], de: ["auto"] }),
  e("🚌", "bus", ["bus"], ALL, { fr: ["bus", "autobus"], es: ["autobús", "autobus"], de: ["bus"] }),
  e("🚆", "train", ["train"], ALL, { fr: ["train"], es: ["tren"], de: ["zug"] }),
  e("✈️", "aeroplane", ["aeroplane", "airplane"], ALL, { fr: ["avion"], es: ["avión", "avion"], de: ["flugzeug"] }),
  e("🚲", "bicycle", ["bicycle", "bike"], ALL, { fr: ["vélo", "velo"], es: ["bicicleta"], de: ["fahrrad"] }),
  e("🚢", "ship", ["ship"], ALL, { fr: ["bateau"], es: ["barco"], de: ["schiff"] }),
  e("🚀", "rocket", ["rocket"], ALL, { fr: ["fusée", "fusee"], es: ["cohete"], de: ["rakete"] }),
  // objects
  e("📖", "open book", ["book"], LANG, { es: ["libro"], de: ["buch"] }),
  e("✏️", "pencil", ["pencil"], ALL, { fr: ["crayon"], es: ["lápiz", "lapiz"], de: ["bleistift"] }),
  e("✂️", "scissors", ["scissors"], ALL, { fr: ["ciseaux"], es: ["tijeras"], de: ["schere"] }),
  e("☂️", "umbrella", ["umbrella"], ALL, { fr: ["parapluie"], es: ["paraguas"], de: ["regenschirm"] }),
  e("👓", "glasses", ["glasses", "spectacles"], LANG, { fr: ["lunettes"], es: ["gafas"], de: ["brille"] }),
  e("🧦", "socks", ["sock"], ALL, { fr: ["chaussettes"], es: ["calcetines"], de: ["socken"] }),
  e("🧥", "coat", [], ALL, { fr: ["manteau"], es: ["abrigo"], de: ["mantel"] }),
  e("👕", "t-shirt", ["t-shirt", "tshirt"], ALL, { fr: ["t-shirt"], es: ["camiseta"], de: ["t-shirt"] }),
  e("👖", "jeans", ["jeans"], ALL, { fr: ["jean"], es: ["vaqueros"], de: ["jeans"] }),
  e("👗", "dress", ["dress"], LANG, { fr: ["robe"], es: ["vestido"], de: ["kleid"] }),
  e("👑", "crown", ["crown"], ALL, { fr: ["couronne"], de: ["krone"] }),
  e("⚽", "soccer ball (football)", ["football"], ALL, { fr: ["football"], es: ["fútbol", "futbol"], de: ["fußball", "fussball"] }),
  e("🎸", "guitar", ["guitar"], ALL, { fr: ["guitare"], es: ["guitarra"], de: ["gitarre"] }),
  e("🎹", "musical keyboard (piano)", ["piano"], ALL, { fr: ["piano"], es: ["piano"], de: ["klavier"] }),
  e("🥁", "drum", ["drum"], ALL, { fr: ["tambour"], es: ["tambor"], de: ["trommel"] }),
  e("🎺", "trumpet", ["trumpet"], ALL, { fr: ["trompette"], es: ["trompeta"], de: ["trompete"] }),
  e("🎻", "violin", ["violin"], ALL, { fr: ["violon"], es: ["violín", "violin"], de: ["geige"] }),
  e("🔔", "bell", ["bell"], ALL, { fr: ["cloche"], es: ["campana"], de: ["glocke"] }),
  e("⏰", "alarm clock", ["alarm clock"], ALL, { fr: ["réveil", "reveil"], es: ["despertador"], de: ["wecker"] }),
  e("📷", "camera", ["camera"], ALL, { fr: ["appareil photo"], es: ["cámara", "camara"], de: ["kamera"] }),
  e("📱", "mobile phone", ["mobile phone"], ALL, { es: ["móvil", "movil"], de: ["handy"] }),
  e("💻", "laptop", ["laptop"], ALL, { fr: ["ordinateur portable"], es: ["portátil", "portatil"], de: ["laptop"] }),
  e("🖥️", "desktop computer", ["computer"], ALL, { fr: ["ordinateur"], es: ["ordenador"], de: ["computer"] }),
  e("📺", "television", ["television"], ALL, { fr: ["télévision", "television"], es: ["televisión", "television"], de: ["fernseher"] }),
  e("🔦", "flashlight (torch)", ["torch"], SCI),
  e("💡", "electric light bulb", ["light bulb"], ALL, { fr: ["ampoule"], es: ["bombilla"], de: ["glühbirne", "gluhbirne"] }),
  e("🔋", "battery", ["battery"], SCI),
  e("🧲", "magnet", ["magnet"], SCI),
  e("🔬", "microscope", ["microscope"], SCI),
  e("🔭", "telescope", ["telescope"], SCI),
  e("🌡️", "thermometer", ["thermometer"], SCI),
  e("🧪", "test tube", ["test tube"], SCI),
  e("🎈", "balloon", ["balloon"], ALL, { es: ["globo"], de: ["luftballon"], note: "fr ballon is also a ball (un ballon de foot), so it is deliberately not listed" }),
  e("🎁", "wrapped gift", ["gift"], LANG, { fr: ["cadeau"], es: ["regalo"], de: ["geschenk"] }),
  e("🕯️", "candle", ["candle"], ALL, { fr: ["bougie"], de: ["kerze"] }),
  e("🎄", "Christmas tree", ["christmas tree"], ALL, { fr: ["sapin de noël", "sapin de noel"], es: ["árbol de navidad", "arbol de navidad"], de: ["weihnachtsbaum"] }),
  // body
  e("🦴", "bone", ["bone"], SCI),
  e("🦷", "tooth", ["tooth", "teeth"], SCI),
  e("👂", "ear", ["ear"], ALL, { fr: ["oreille"], es: ["oreja"], de: ["ohr"] }),
  e("👁️", "eye", ["eye"], ALL, { fr: ["œil", "oeil"], es: ["ojo"], de: ["auge"] }),
  e("👃", "nose", ["nose"], ALL, { fr: ["nez"], es: ["nariz"], de: ["nase"] }),
  e("🧠", "brain", ["brain"], ALL, { fr: ["cerveau"], es: ["cerebro"], de: ["gehirn"] }),
  e("👨‍👩‍👧", "family: man, woman, girl", ["family"], LANG, { fr: ["famille"], es: ["familia"], de: ["familie"], note: "avoid family tree / word family" }),
];

/** phrases that veto an emoji for a word in a different sense (e.g. "sun" in "Sunday", handled by whole-word match; these are context vetoes) */
export const EMOJI_AVOID = ["word families", "language family", "language families", "evolutionary tree", "phylogenetic", "spelling bee", "egg cell", "ovum", "sex cell", "pinhole", "family tree", "word family", "families of", "verb family", "tree diagram", "food chain", "fire alarm", "fire drill", "sun cream", "cloud storage", "car park", "book a", "to book", "key word", "key idea", "key stage", "key skill", "key point", "key feature", "key term", "key vocabulary", "keys", "sound key", "present tense", "present perfect", "present participle", "in the present", "the present", "gift of", "computer science", "computer game", "computing", "network", "bell curve", "bell shaped", "eye contact", "in the eye", "ear for", "rose from", "rose to", "tree of life", "decision tree", "family of"];
registerLanguageEmoji(EMOJI, EMOJI_AVOID); // X5 registration (French / Spanish / German nouns; merges into existing entries)
export const EMOJI_SET = new Set(EMOJI.map((x) => x.emoji));
