// Transformations, symmetry, lines, right-angled triangles, graphs and vectors (Maths, some shared with Science).
import type { Pic } from "./types";
import { svg, poly, ln, txt, dot, arrow, cap, rightAngle, pt, arc, rect, pline, circ } from "./helpers";

const W = 240, H = 170;
const M: Pic["subjects"] = ["Maths"];
const mk = (id: string, title: string, concepts: string[], body: string, alt: string, caption: string, evidence: string, extra: Partial<Pic> = {}): Pic =>
  ({ id, title, alt, caption, subjects: M, concepts, doesNotShow: "specific values or worked answers", evidence, svg: svg(W, H, body), ...extra });
type P = [number, number];
const ticks = (p: P, q: P, k: number) => { const mx = (p[0] + q[0]) / 2, my = (p[1] + q[1]) / 2, a = Math.atan2(q[1] - p[1], q[0] - p[0]), nx = -Math.sin(a), ny = Math.cos(a), ux = Math.cos(a), uy = Math.sin(a); let s = ""; for (let i = 0; i < k; i++) { const o = (i - (k - 1) / 2) * 5; s += ln(mx + ux * o - nx * 5, my + uy * o - ny * 5, mx + ux * o + nx * 5, my + uy * o + ny * 5, "th2"); } return s; };

// ── transformations ─────────────────────────────────────────────────────────
const nt = (b: string) => b.replace(/<text[^>]*>[^<]*<\/text>/g, "");
const reflBody = (() => { const T: P[] = [[50, 56], [100, 56], [100, 116]], R = T.map((p): P => [240 - p[0], p[1]]); return ln(120, 20, 120, 136, "h") + poly(T, "l f1") + poly(R, "l f3") + txt(70, 46, "object", "ts") + txt(170, 46, "image", "ts") + txt(120, 14, "mirror line", "ts tm"); })();
const rotBody = (() => {
  const C: P = [120, 84]; const rel: P[] = [[20, -20], [60, -20], [20, -55]];
  const T = rel.map((v): P => [C[0] + v[0], C[1] + v[1]]), R = rel.map((v): P => [C[0] - v[1], C[1] + v[0]]);
  const a1 = pt(C[0], C[1], 40, -30), a2 = pt(C[0], C[1], 40, -40);
  return poly(T, "l f1") + poly(R, "l f3") + dot(C[0], C[1], 4, "fr") + arc(C[0], C[1], 40, -30, 40, "ar") + arrow(a1[0], a1[1], a2[0], a2[1], "ar", 8)
    + txt(C[0] - 8, C[1] + 4, "centre", "ts tr te") + txt(C[0] + 50, C[1] + 4, "90° clockwise", "tx tr tl") + txt(C[0] + 56, C[1] - 50, "object", "ts tl") + txt(C[0] + 6, C[1] + 78, "image", "ts tl");
})();
const transBody = (() => { const T: P[] = [[34, 96], [84, 96], [34, 52]], R = T.map((p): P => [p[0] + 110, p[1] + 10]); return poly(T, "l f1") + poly(R, "l f3") + arrow(T[2][0], T[2][1], R[2][0], R[2][1], "ar", 8) + txt(96, 48, "vector", "ts tr") + txt(50, 118, "object", "ts") + txt(180, 142, "image", "ts") + cap("every point slides the same way", 164); })();
const enlBody = (() => { const O: P = [26, 122], rel: P[] = [[30, -20], [50, -20], [30, -35]]; const T = rel.map((v): P => [O[0] + v[0], O[1] + v[1]]), E = rel.map((v): P => [O[0] + 3 * v[0], O[1] + 3 * v[1]]); return E.map((p) => ln(O[0], O[1], p[0], p[1], "h")).join("") + poly(E, "l f3") + poly(T, "l f1") + dot(O[0], O[1], 4, "fr") + txt(O[0] + 6, O[1] + 16, "centre", "ts tr tl") + txt(T[1][0] + 10, T[1][1] + 22, "object", "ts tl") + txt(E[2][0] + 42, E[2][1] + 6, "image", "ts") + cap("enlarged from the centre, scale factor 3", 164); })();

// ── symmetry, lines ─────────────────────────────────────────────────────────
const sym = (() => { const house: P[] = [[70, 132], [170, 132], [170, 84], [120, 40], [70, 84]]; return poly(house, "l f1") + ln(120, 22, 120, 136, "ar").replace('class="ar"', 'class="ar" stroke-dasharray="6 5"') + txt(120, 16, "line of symmetry", "ts tr") + cap("both sides are mirror images of each other", 164, 40); })();
const parallel = (() => ln(30, 56, 210, 56) + ln(30, 106, 210, 106) + `<path d="M108 50 l7 6 -7 6 M108 100 l7 6 -7 6" class="th2"/>` + cap("parallel lines stay the same distance apart and never meet", 152, 40))();
const perp = (() => ln(40, 100, 200, 100) + ln(120, 24, 120, 110) + rightAngle(120, 100, 0, 90, 12) + cap("perpendicular lines meet at a right angle (90°)", 148, 40))();

// ── right-angled triangle labels + Pythagoras ───────────────────────────────
const rtLabel = (() => {
  const A: P = [28, 116], B: P = [170, 116], C: P = [170, 32];
  return poly([A, B, C], "l f1") + rightAngle(170, 116, 180, 90, 12) + arc(A[0], A[1], 30, 0, 30.6, "th2") + txt(A[0] + 40, A[1] - 5, "θ", "ta tb")
    + txt(99, 131, "adjacent", "ts") + txt(178, 78, "opposite", "ts tl") + `<text x="86" y="64" class="t ts tr" transform="rotate(-30.6 86 64)">hypotenuse</text>` + cap("opposite and adjacent are named from the angle θ", 166, 44);
})();
const pyth = (() => {
  const dy = 14, C: P = [96, 80 + dy], A: P = [96, 44 + dy], B: P = [144, 80 + dy]; // legs 3u (up) and 4u (right), hypotenuse 5u
  const sqA: P[] = [[60, 44 + dy], [96, 44 + dy], [96, 80 + dy], [60, 80 + dy]], sqB: P[] = [[96, 80 + dy], [144, 80 + dy], [144, 128 + dy], [96, 128 + dy]];
  const sqC: P[] = [A, B, [B[0] + 36, B[1] - 48], [A[0] + 36, A[1] - 48]];
  return poly(sqA, "l f4") + poly(sqB, "l f2") + poly(sqC, "l f3") + poly([C, B, A], "l f1") + rightAngle(96, 80 + dy, 0, 90, 10) + txt(78, 66 + dy, "a²", "tb") + txt(120, 108 + dy, "b²", "tb") + txt(134, 40 + dy, "c²", "tb")
    + cap("a² + b² = c² in a right-angled triangle", 166, 44);
})();

// ── graphs ──────────────────────────────────────────────────────────────────
const lineGraph = (() => arrow(40, 140, 214, 140, "l", 7) + arrow(40, 140, 40, 14, "l", 7) + ln(40, 105, 200, 25, "a") + dot(40, 105, 4, "fr") + txt(46, 100, "y-intercept", "ts tr tl").replace('x="46"', 'x="50"').replace('y="100"', 'y="120"') + ln(90, 80, 170, 80, "ag") + ln(170, 80, 170, 40, "ao") + txt(130, 96, "run", "ts tg") + txt(190, 62, "rise", "ts tl").replace('x="190"', 'x="176"').replace('y="62"', 'y="64"') + txt(120, 160, "gradient = rise ÷ run", "ts tm"))();
const parabola = (() => { const pts: P[] = []; for (let x = 60; x <= 180; x += 4) { const t = (x - 120) / 60; pts.push([x, 130 - 100 * t * t]); } return arrow(30, 95, 214, 95, "l", 7) + arrow(120, 148, 120, 10, "l", 7) + `<polyline points="${pts.map((p) => p.join(",")).join(" ")}" class="a"/>` + dot(120, 130, 4, "fr") + dot(84.5, 95, 4, "fg") + dot(155.5, 95, 4, "fg") + txt(120, 146, "turning point", "ts tr").replace('y="146"', 'y="150"').replace('x="120"', 'x="160"') + txt(70, 88, "root", "ts tg te") + txt(172, 88, "root", "ts tg tl"); })();
const trig = (fn: (x: number) => number, name: string, tan = false) => {
  const x0 = 30, x1 = 210, cy = 82, A = 44; let s = arrow(x0 - 8, cy, x1 + 14, cy, "l", 7) + arrow(x0, cy + 62, x0, cy - 66, "l", 7);
  for (const d of [90, 180, 270, 360]) { const x = x0 + (d / 360) * (x1 - x0); s += ln(x, cy - 4, x, cy + 4, "l") + txt(x, cy + 18, `${d}°`, "tx"); if (tan && (d === 90 || d === 270)) s += ln(x, cy - 62, x, cy + 58, "h"); }
  const segs: P[][] = [[]]; for (let d = 0; d <= 360; d += 3) { const v = fn(d); if (tan && (Math.abs(Math.cos((d * Math.PI) / 180)) < 0.08 || Math.abs(v) > 2)) { segs.push([]); continue; } const y = cy - v * A * (tan ? 0.7 : 1); segs[segs.length - 1].push([x0 + (d / 360) * (x1 - x0), y]); }
  for (const g of segs) if (g.length > 1) s += `<polyline points="${g.map((p) => p.map((v) => Math.round(v * 10) / 10).join(",")).join(" ")}" class="a"/>`;
  if (!tan) s += txt(x0 - 6, cy - A + 4, "1", "ts te") + txt(x0 - 6, cy + A + 4, "−1", "ts te");
  return s + cap(name, 166, 44);
};
const vec = (() => arrow(50, 116, 190, 46, "a", 10) + dot(50, 116, 4) + txt(38, 134, "A", "tb") + txt(198, 44, "B", "tb tl") + cap("a vector has size (magnitude) and direction", 164, 44))();
const congruent = (() => { const A: P[] = [[30, 130], [100, 130], [50, 60]]; const B: P[] = [[130, 60], [200, 60], [180, 130]]; /* B is A rotated 180 deg about a point (then translated): vertex order reversed */ const bt: P[] = A.map((p): P => [230 - p[0], 190 - p[1]]); return poly(A, "l f1") + ticks(A[0], A[1], 1) + ticks(A[1], A[2], 2) + ticks(A[2], A[0], 3) + poly(bt, "l f3") + ticks(bt[0], bt[1], 1) + ticks(bt[1], bt[2], 2) + ticks(bt[2], bt[0], 3) + cap("congruent shapes are exactly the same shape and size (they can be turned or flipped)", 168, 44); })();
const similar = (() => { const A: P[] = [[24, 134], [84, 134], [46, 84]]; const k = 1.8, O = A[0]; const B = A.map((p): P => [O[0] + 76 + (p[0] - O[0]) * k, O[1] + (p[1] - O[1]) * k - 0]); const sm = poly(A, "l f1") + arc(A[0][0], A[0][1], 14, 0, 53, "th2") + poly(B, "l f3") + arc(B[0][0], B[0][1], 20, 0, 53, "th2"); return sm + cap("similar shapes: same angles, matching sides in proportion", 166, 44); })();
const axes = (() => {
  const cx = 120, cy = 64, u = 19; let s = arrow(20, cy, 224, cy, "l", 8) + arrow(cx, 120, cx, 4, "l", 8) + txt(216, cy - 8, "x", "tb") + txt(cx + 13, 14, "y", "tb");
  for (const v of [-3, -2, -1, 1, 2, 3]) { const L = String(v).replace("-", "−"); s += ln(cx + v * 28, cy - 4, cx + v * 28, cy + 4, "l") + txt(cx + v * 28, cy + 16, L, "tx") + ln(cx - 4, cy - v * u, cx + 4, cy - v * u, "l") + txt(cx - 8, cy - v * u + 3, L, "tx te"); }
  return s + txt(176, 32, "1st", "ts tm") + txt(64, 32, "2nd", "ts tm") + txt(64, 100, "3rd", "ts tm") + txt(176, 100, "4th", "ts tm") + txt(cx + 6, cy + 14, "O", "ts tm tl").replace('cy + 14', 'cy + 14') + cap("the x-axis and y-axis meet at the origin O and split the grid into 4 quadrants", 166, 44);
})();
const dt = (() => { let s = arrow(34, 140, 218, 140, "l", 7) + arrow(34, 140, 34, 12, "l", 7); s += pline([[34, 140], [80, 100]], "a") + pline([[80, 100], [120, 100]], "ag") + pline([[120, 100], [180, 40]], "ar"); return s + txt(126, 154, "time", "ts tm") + `<text x="20" y="76" class="t ts tm" transform="rotate(-90 20 76)">distance</text>` + txt(74, 128, "steady speed", "tx ta tl") + txt(100, 92, "stationary", "tx tg") + txt(140, 56, "faster", "tx tr te") + txt(120, 168, "a steeper line means a faster speed", "ts tm"); })();
void rect; void circ;

export const GEOMETRY: Pic[] = [
  mk("reflection", "Reflection", ["reflection"], reflBody, "A triangle reflected in a dashed mirror line: the image is the same size, flipped to the other side of the line at the same distance.", "Reflection", "Reflection = flip in a mirror line; every point of the image is the same distance from the mirror line as the object (x' = 240 - x exact).", { family: "transformations", avoid: ["reflection of light", "light", "mirror image in", "reflect on", "reflect your", "self-reflection", "reflective writing"], requires: ["transform", "mirror line", "shape", "triangle", "image", "object", "line"] }),
  mk("rotation", "Rotation", ["rotation"], rotBody, "A triangle rotated a quarter turn clockwise about a marked centre: the image is the same size, turned.", "Rotation", "Rotation = turn about a centre through an angle; drawn as 90 degrees clockwise ((x,y) -> (-y,x) in screen coordinates, exact).", { family: "transformations", numeric: true, avoid: ["rotational symmetry", "order of rotation", "earth", "rotation of the earth", "crop rotation", "planet",
    // the drawing has its centre OUTSIDE the shape: a slide about WHERE the centre can be (inside / on a vertex / on the shape) would be contradicted by it
    "inside the object", "inside the shape", "inside the triangle", "inside or outside", "on a vertex", "on the object", "on the shape", "on the triangle", "on an edge", "on a side", "can be lying", "lying inside", "lying on", "position of the centre", "where the centre", "centre can be", "centre of rotation can", "centre could be", "any point", "anywhere", "anticlockwise"], requires: ["transform", "centre of rotation", "shape", "triangle", "image", "object", "turn"] }),
  mk("translation", "Translation", ["translation"], transBody, "A triangle slid along an arrow (a vector) to a new position: same size, same way up.", "Translation", "Translation = slide; every point moves the same vector. Image is the object plus a fixed offset (110,10), so orientation is unchanged.", { family: "transformations", avoid: ["translate into", "translate from", "translation into", "into english", "into french", "into spanish", "into german"], requires: ["transform", "shape", "triangle", "image", "object", "vector", "slide"] }),
  mk("enlargement", "Enlargement", ["enlargement", "centre of enlargement"], enlBody, "A small triangle enlarged from a centre by scale factor 3: rays from the centre pass through matching corners; the image is the same shape, three times as big.", "Enlargement", "Enlargement about a centre O, scale factor 3: each image vertex = O + 3 x (object vertex - O), exactly on the ray from O.", { family: "transformations", numeric: true, avoid: ["negative scale factor", "fractional scale factor", "negative enlargement", "fractional enlargement", "positive fractional", "enlargement of area", "area scale factor"] }),
  mk("transformations", "Four transformations", ["transformation"], (() => { const s = 0.5; return `<g transform="translate(0 6) scale(${s})">${nt(reflBody)}</g><g transform="translate(120 6) scale(${s})">${nt(transBody)}</g><g transform="translate(0 86) scale(${s})">${nt(rotBody)}</g><g transform="translate(120 86) scale(${s})">${nt(enlBody)}</g>` + txt(60, 88, "reflection", "ts") + txt(180, 88, "translation", "ts") + txt(60, 166, "rotation", "ts") + txt(180, 166, "enlargement", "ts"); })(), "Four small diagrams labelled reflection, translation, rotation and enlargement.", "Transformations", "The four transformations (reflection, translation, rotation, enlargement) each drawn as in their own pictures, at half size.", { family: "transformations", covers: ["reflection", "rotation", "translation", "enlargement", "centre of enlargement"], avoid: ["negative scale factor", "fractional scale factor", "negative enlargement", "fractional enlargement", "positive fractional", "multiple transformation", "combined transformation", "single transformation", "graph transformation", "transformations of graphs", "transformation of graphs", "function", "invariant"], doesNotShow: "combinations of transformations; transformations of graphs; specific values" }),
  mk("line-of-symmetry", "Line of symmetry", ["line of symmetry", "reflective symmetry", "reflection symmetry"], sym, "A house-shaped pentagon with a dashed vertical line of symmetry down the middle: each side is the mirror image of the other.", "Line of symmetry", "A line of symmetry divides a shape into two mirror-image halves. House shape symmetric about x=120 exactly.", { avoid: ["rotational", "order of rotational", "no lines of symmetry", "lines of symmetry of"], doesNotShow: "rotational symmetry; shapes with more than one line" }),
  mk("parallel-lines", "Parallel lines", ["parallel line", "parallel"], parallel, "Two straight lines drawn the same distance apart with matching arrow marks: parallel lines.", "Parallel lines", "Parallel lines never meet and stay equally far apart; marked with matching arrows.", { family: "lines", requires: ["line", "lines", "side", "sides"], avoid: ["parallel circuit", "transversal", "alternate", "corresponding", "co-interior", "parallelogram", "perpendicular", "cross-section", "parallel resistors", "in parallel", "parallel universe"] }),
  mk("perpendicular-lines", "Perpendicular lines", ["perpendicular line", "perpendicular"], perp, "Two straight lines crossing at a right angle, marked with a small square.", "Perpendicular lines", "Perpendicular lines meet at 90 degrees (right-angle marker).", { family: "lines", avoid: ["perpendicular bisector", "perpendicular height", "parallel", "gradient", "negative reciprocal", "hypotenuse"] }),
  mk("right-triangle-sides", "Hypotenuse, opposite, adjacent", ["hypotenuse", "opposite", "adjacent", "sohcahtoa", "soh cah toa"], rtLabel, "A right-angled triangle with an angle marked theta: the hypotenuse is the longest side opposite the right angle, the opposite side is across from theta and the adjacent side is next to theta.", "Sides of a right-angled triangle", "Hypotenuse = side opposite the right angle (longest); opposite/adjacent are named from the marked angle theta. Right angle at the bottom right; theta at the left.", { requires: ["hypotenuse", "right-angled", "right angled", "trigonometry", "trigonometric", "sine", "cosine", "tangent", "sohcahtoa", "soh cah toa"], avoid: ["opposite angle", "opposite side of a", "opposite sides", "adjacent angle", "adjacent side of a rectangle", "adjacent sides", "adjacent angles", "opposite faces", "opposite corners", "pythagoras", "ratio of opposite"], doesNotShow: "the sine/cosine/tangent ratios themselves or any lengths" }),
  mk("pythagoras", "Pythagoras' theorem", ["pythagoras", "pythagorean", "pythagoras' theorem", "pythagoras theorem"], pyth, "A right-angled triangle with a square drawn on each side, labelled a squared, b squared and c squared, and the rule a squared plus b squared equals c squared.", "Pythagoras' theorem", "Pythagoras: in a right-angled triangle a^2 + b^2 = c^2 where c is the hypotenuse; the square areas on the two shorter sides add up to the square on the hypotenuse. Drawn to scale as a 3-4-5 triangle (9 + 16 = 25) without printing the numbers.", { avoid: ["converse", "3d pythagoras", "three-dimensional"] }),
  mk("straight-line-graph", "Gradient and y-intercept", ["gradient", "y-intercept", "y intercept", "straight-line graph", "straight line graph", "linear graph"], lineGraph, "A straight-line graph with the y-intercept marked where the line crosses the y-axis and a gradient triangle showing rise over run.", "Gradient and y-intercept", "Gradient = rise/run (change in y over change in x); y-intercept = where the line crosses the y-axis. Line y = 105 - 0.5(x-40) on screen, triangle vertices exactly on the line.", { subjects: ["Maths", "Science"], requires: ["graph", "line", "axis", "axes", "straight", "linear"], avoid: ["non-linear", "nonlinear", "non linear", "curve", "tangent", "quadratic", "negative gradient", "negative rate", "decreasing", "perpendicular", "parallel", "distance-time", "distance time", "velocity-time", "velocity time", "rate of reaction", "displacement-time", "displacement time"], doesNotShow: "negative gradients; curves; numbers on the axes" }),
  mk("quadratic-graph", "Quadratic graph", ["quadratic graph", "parabola", "turning point"], parabola, "A U-shaped quadratic graph (a parabola) crossing the x-axis at two points (the roots) with its turning point at the bottom.", "A quadratic graph", "A quadratic graph is a parabola: a U-shape with one turning point (minimum here) and up to two x-intercepts (roots). y = 130 - 100((x-120)/60)^2 on screen; roots at t = +-0.59 exactly.", { avoid: ["inverted", "negative quadratic", "maximum", "cubic", "reciprocal", "exponential", "projectile"], doesNotShow: "an upside-down (maximum) parabola; the equation" }),
  mk("sine-graph", "Sine graph", ["sine graph", "sine curve"], trig((d) => Math.sin((d * Math.PI) / 180), "the sine graph: a wave from 0° to 360°, between −1 and 1"), "The sine graph from 0 to 360 degrees: a smooth wave starting at zero, rising to 1 at 90, back to zero at 180, down to minus 1 at 270 and back to zero at 360.", "Sine graph", "y = sin x plotted every 3 degrees: 0 at 0, 1 at 90, 0 at 180, -1 at 270, 0 at 360 (exact).", { family: "trig-graphs" }),
  mk("cosine-graph", "Cosine graph", ["cosine graph", "cosine curve"], trig((d) => Math.cos((d * Math.PI) / 180), "the cosine graph: a wave from 0° to 360°, between −1 and 1"), "The cosine graph from 0 to 360 degrees: a smooth wave starting at 1, crossing zero at 90, minus 1 at 180, zero at 270 and back to 1 at 360.", "Cosine graph", "y = cos x plotted every 3 degrees: 1 at 0, 0 at 90, -1 at 180, 0 at 270, 1 at 360 (exact).", { family: "trig-graphs" }),
  mk("tangent-graph", "Tangent graph", ["tangent graph", "tangent curve"], trig((d) => Math.tan((d * Math.PI) / 180), "the tangent graph: repeating curves with breaks at 90° and 270°", true), "The tangent graph from 0 to 360 degrees: curves that rise steeply towards dashed vertical lines at 90 and 270 degrees.", "Tangent graph", "y = tan x, with vertical asymptotes at 90 and 270 degrees (dashed), zero at 0, 180, 360; values beyond +-2 not drawn.", { family: "trig-graphs", avoid: ["tangent to a circle", "tangent line"] }),
  mk("vector", "Vector", ["vector"], vec, "An arrow from point A to point B: its length shows the size (magnitude) of the vector and its direction shows the direction.", "A vector", "A vector has magnitude and direction; drawn as an arrow from A to B.", { subjects: ["Maths", "Science"], requires: ["magnitude", "direction", "scalar", "column vector", "displacement", "translation", "velocity", "force", "arrow"], avoid: ["disease", "pathogen", "mosquito", "plasmid", "genetic", "bacteria", "virus", "insect"], doesNotShow: "components, coordinates or the notation AB" }),
  mk("congruent-shapes", "Congruent shapes", ["congruent", "congruence"], congruent, "Two triangles that are exactly the same shape and size, one turned round, with matching tick marks on matching sides.", "Congruent shapes", "Congruent = identical in shape and size (one is a rotation/reflection/translation of the other). Second triangle is the first rotated 180 degrees; matching sides carry the same ticks.", { avoid: ["similar", "sss", "sas", "asa", "aas", "rhs", "criteria"], doesNotShow: "the congruence conditions (SSS, SAS, ASA, RHS)" }),
  mk("similar-shapes", "Similar shapes", ["similar shapes", "similar triangles", "similar figures"], similar, "A small triangle and a larger triangle with the same angles: the larger one is an enlargement of the small one.", "Similar shapes", "Similar = same angles, sides in the same proportion. Second triangle is exactly 1.8 times the first (same marked angle).", { avoid: ["congruent"], doesNotShow: "scale factors or side lengths" }),
  mk("coordinate-axes", "Coordinate axes", ["x-axis", "y-axis", "coordinate axes", "coordinate grid", "coordinates", "quadrant"], axes, "Coordinate axes: a horizontal x-axis and vertical y-axis crossing at the origin O, marked from minus 3 to 3, dividing the grid into four quadrants numbered 1st to 4th anticlockwise.", "Coordinate axes and quadrants", "x-axis horizontal, y-axis vertical, origin O = (0,0), quadrants numbered anticlockwise starting top right (UK convention).", { avoid: ["axis of symmetry", "axes of symmetry", "chart", "bar", "histogram", "3d", "three-dimensional", "z-axis", "polar"], numeric: true }),
  mk("distance-time-graph", "Distance-time graph", ["distance-time graph", "distance time graph", "displacement-time graph", "displacement time graph"], dt, "A distance-time graph with three parts: a rising line for steady speed, a flat line for stationary and a steeper line for a faster speed.", "Distance-time graph", "On a distance-time graph the gradient is the speed: sloping straight line = constant speed, horizontal = stationary, steeper = faster. Displacement-time is the same shape with direction.", { subjects: ["Maths", "Science"], avoid: ["wave", "oscilloscope", "sound", "vibrat", "oscillat", "microphone", "velocity-time", "velocity time", "acceleration", "curve", "curved"], doesNotShow: "acceleration (curves); numbers on the axes" }),
];
