// Number, measures and data pictures (Maths). Generic diagrams: they show the idea, never a specific answer (pictures that do draw specific
// values are flagged `numeric` and are never used on a slide whose text contains numbers).
import type { Pic } from "./types";
import { svg, poly, path, ln, circ, rect, txt, dot, arrow, cap, pt, arc, sector, range, n } from "./helpers";

const W = 240, H = 170;
const M: Pic["subjects"] = ["Maths"];
const mk = (id: string, title: string, concepts: string[], body: string, alt: string, caption: string, evidence: string, extra: Partial<Pic> = {}): Pic =>
  ({ id, title, alt, caption, subjects: M, concepts, doesNotShow: "specific values or worked answers", evidence, svg: svg(W, H, body), ...extra });

// number lines
const nl = (from: number, to: number) => {
  const x0 = 24, x1 = 216, step = (x1 - x0) / (to - from); let s = arrow(x0 - 10, 80, x1 + 12, 80, "l", 9) + arrow(x1 + 2, 80, x0 - 12, 80, "l", 9);
  for (let v = from; v <= to; v++) { const x = x0 + (v - from) * step; s += ln(x, 72, x, 88, "l") + txt(x, 108, String(v).replace("-", "−"), v === 0 ? "tb" : ""); }
  return s;
};
// place value
const pv = (() => {
  const cols = ["Thousands", "Hundreds", "Tens", "Ones"], ws = [64, 58, 45, 45]; let s = "", x = 14; // column widths follow the heading lengths so "Thousands" never overflows its box
  cols.forEach((c, i) => { s += rect(x, 40, ws[i], 64, "l f1") + txt(x + ws[i] / 2, 84, c, "tx") + txt(x + ws[i] / 2, 58, ["Th", "H", "T", "O"][i], "tb"); x += ws[i]; });
  s += arrow(200, 126, 30, 126, "a", 9);
  return s + cap("each column is 10 times the value of the one to its right", 162, 40);
})();
const pvDec = (() => {
  const cols = ["Ones", "Tenths", "Hundredths"]; let s = "";
  cols.forEach((c, i) => { s += rect(14 + i * 64 + (i > 0 ? 14 : 0), 40, 62, 64, "l f1") + txt(45 + i * 64 + (i > 0 ? 14 : 0), 76, c, "tx"); });
  s += dot(84, 72, 5) ;
  return s + txt(84, 34, "decimal point", "ts tm") + cap("each column to the right is 10 times smaller", 160, 40);
})();

// fractions
const fracBar = (() => { let s = ""; for (let i = 0; i < 4; i++) s += rect(30 + i * 45, 50, 45, 40, i < 3 ? "l f1" : "l f0"); return s + txt(120, 40, "3 out of 4 equal parts are shaded", "ts") + txt(120, 116, "numerator: the parts we have (3)", "ts ta") + txt(120, 134, "denominator: all the equal parts (4)", "ts tr") + txt(120, 160, "3/4", "tb"); })();
const wall = (() => { const parts = [1, 2, 3, 4, 5, 6, 8, 10]; let s = ""; parts.forEach((p, r) => { const y = 12 + r * 18; for (let i = 0; i < p; i++) s += rect(40 + i * (180 / p), y, 180 / p, 16, `l ${r % 2 ? "f1" : "f3"}`); s += txt(34, y + 12, p === 1 ? "1" : `1/${p}`, "ts te"); }); return s; })();
const fracCircles = (() => { let s = ""; [[2, 60, "half"], [3, 120, "third"], [4, 180, "quarter"]].forEach(([k, cx, nm]) => { const kk = k as number, c = cx as number; s += circ(c, 70, 30, "l f0"); s += sector(c, 70, 30, 90, 90 + 360 / kk, "l f1"); for (let i = 0; i < kk; i++) { const p = pt(c, 70, 30, 90 + (360 / kk) * i); s += ln(c, 70, p[0], p[1], "l"); } s += txt(c, 124, nm === "half" ? "halves" : nm + "s", "ts"); }); return s + cap("a whole split into equal parts", 152); })();
const improper = (() => { let s = ""; for (let i = 0; i < 4; i++) s += rect(30 + i * 40, 36, 40, 30, "l f1"); for (let i = 0; i < 4; i++) s += rect(30 + i * 40, 66, 40, 30, i < 1 ? "l f1" : "l f0"); return s + txt(120, 118, "5/4 = 1 1/4", "tb") + txt(120, 138, "an improper fraction is bigger than 1 whole", "ts tm") + txt(120, 154, "so it can be written as a mixed number", "ts tm"); })();

// structures
const bar = (() => rect(30, 66, 90, 34, "l f1") + rect(120, 66, 90, 34, "l f3") + path("M30 58 Q30 46 42 46 H198 Q210 46 210 58", "l") + txt(120, 38, "whole", "ts") + txt(75, 88, "part", "ts") + txt(165, 88, "part", "ts") + cap("a bar model shows how parts make a whole", 140))();
const pw = (() => circ(120, 44, 24, "l f1") + circ(70, 112, 24, "l f3") + circ(170, 112, 24, "l f3") + ln(108, 65, 82, 90) + ln(132, 65, 158, 90) + txt(120, 48, "whole", "ts") + txt(70, 116, "part", "ts") + txt(170, 116, "part", "ts") + cap("a whole is made of two parts", 158))();
const array = (() => { let s = ""; for (let r = 0; r < 3; r++) for (let c = 0; c < 4; c++) s += circ(70 + c * 30, 26 + r * 28, 10, "l f1"); return s + arrow(70, 98, 160, 98, "a", 8) + txt(115, 116, "columns", "ts ta") + txt(186, 54, "rows", "ts tl ta") + cap("an array: objects in equal rows and columns", 164); })();
const tenFrame = (() => { let s = ""; for (let r = 0; r < 2; r++) for (let c = 0; c < 5; c++) s += rect(28 + c * 36, 44 + r * 36, 36, 36, "l f0"); return s + cap("a ten frame: 10 boxes, 2 rows of 5", 150); })();
const hundred = (() => { let s = ""; for (let r = 0; r < 10; r++) for (let c = 0; c < 10; c++) s += rect(60 + c * 12, 10 + r * 12, 12, 12, "th f1"); return s + rect(60, 10, 120, 120, "l") + cap("a hundred square: 10 rows of 10", 154); })();

// data
const axes = (x0: number, y0: number, x1: number, y1: number, xl = "", yl = "") => arrow(x0, y0, x1, y0, "l", 7) + arrow(x0, y0, x0, y1, "l", 7) + (xl ? txt((x0 + x1) / 2, y0 + 16, xl, "ts tm") : "") + (yl ? `<text x="${x0 - 14}" y="${(y0 + y1) / 2}" class="t ts tm" transform="rotate(-90 ${x0 - 14} ${(y0 + y1) / 2})">${yl}</text>` : "");
const barChart = (() => { const hs = [60, 96, 42, 78]; let s = axes(44, 120, 214, 18, "", "frequency"); hs.forEach((h, i) => { s += rect(58 + i * 40, 120 - h, 28, h, `l ${["f1", "f3", "f2", "f4"][i]}`); s += txt(72 + i * 40, 134, "ABCD"[i], "ts"); }); return s + cap("a bar chart: bar height shows the frequency", 164); })();
const pie = (() => { const segs = [[90, 200, "f1"], [200, 290, "f3"], [290, 330, "f2"], [330, 450, "f4"]] as const; let s = ""; segs.forEach(([a, b, f]) => { s += sector(120, 76, 58, a, b, `l ${f}`); }); ["A", "B", "C", "D"].forEach((L, i) => { const m = (segs[i][0] + segs[i][1]) / 2; const p = pt(120, 76, 36, m); s += txt(p[0], p[1] + 4, L, "ts"); }); return s + cap("a pie chart: each sector is a part of the whole", 156); })();
const lineGraph = (() => { const pts: [number, number][] = [[60, 96], [90, 68], [120, 80], [150, 44], [190, 58]]; return axes(44, 118, 214, 18, "time", "value") + `<polyline points="${pts.map((p) => p.join(",")).join(" ")}" class="a"/>` + pts.map((p) => dot(p[0], p[1], 3.4, "fs")).join("") + cap("a line graph joins points to show change over time", 164); })();
const scatterPos = (() => { const pts: [number, number][] = [[62, 112], [76, 100], [92, 104], [104, 86], [118, 78], [134, 82], [148, 62], [164, 56], [180, 44]]; return axes(44, 128, 214, 22, "", "") + ln(56, 116, 196, 40, "ar") + pts.map((p) => dot(p[0], p[1], 3.6)).join("") + cap("a scatter graph: as one goes up, the other goes up (positive correlation); the red line is the line of best fit", 168, 44); })();
const scatterNeg = (() => { const pts: [number, number][] = [[62, 44], [76, 60], [92, 56], [104, 76], [118, 72], [134, 90], [148, 88], [164, 106], [180, 112]]; return axes(44, 128, 214, 22, "", "") + ln(56, 40, 196, 116, "ar") + pts.map((p) => dot(p[0], p[1], 3.6)).join("") + cap("negative correlation: as one goes up, the other goes down", 164); })();
const scatterNone = (() => { const pts: [number, number][] = [[60, 60], [78, 108], [92, 44], [108, 90], [124, 118], [136, 52], [152, 98], [170, 66], [186, 112], [200, 50]]; return axes(44, 128, 214, 22, "", "") + pts.map((p) => dot(p[0], p[1], 3.6)).join("") + cap("no correlation: the points show no pattern", 164); })();
const venn = (() => circ(96, 76, 50, "l f1") + `<circle cx="146" cy="76" r="50" class="l f3" style="fill-opacity:.75"/>` + txt(70, 80, "only A", "ts") + txt(172, 80, "only B", "ts") + txt(121, 74, "in both", "ts") + txt(96, 24, "A", "tb") + txt(146, 24, "B", "tb") + cap("a Venn diagram: overlapping circles sort things into groups", 156))();
const tally = (() => { let s = ""; for (let i = 0; i < 4; i++) s += ln(70 + i * 16, 50, 70 + i * 16, 100, "l"); s += ln(56, 92, 136, 58, "ar"); return s + cap("a tally mark group: four lines and a line across make 5", 152); })();
const probScale = (() => { const x = (v: number) => 30 + v * 180; let s = ln(30, 80, 210, 80, "l") + [0, 0.5, 1].map((v) => ln(x(v), 70, x(v), 90, "l") + txt(x(v), 108, v === 0.5 ? "1/2" : String(v), "tb")).join(""); s += txt(x(0), 60, "impossible", "ts") + txt(x(0.5), 60, "even chance", "ts") + txt(x(1), 60, "certain", "ts") + txt(x(0.25), 132, "unlikely", "ts tm") + txt(x(0.75), 132, "likely", "ts tm"); return s + cap("probability is a number from 0 to 1", 158); })();
const die = (() => { const face = (x: number, y: number, k: number) => { const P: Record<number, number[][]> = { 1: [[0, 0]], 2: [[-1, -1], [1, 1]], 3: [[-1, -1], [0, 0], [1, 1]], 4: [[-1, -1], [1, -1], [-1, 1], [1, 1]], 5: [[-1, -1], [1, -1], [0, 0], [-1, 1], [1, 1]], 6: [[-1, -1], [1, -1], [-1, 0], [1, 0], [-1, 1], [1, 1]] }; return rect(x, y, 56, 56, "l f0", 8) + P[k].map(([a, b]) => dot(x + 28 + a * 14, y + 28 + b * 14, 5)).join(""); }; let s = ""; for (let k = 1; k <= 6; k++) s += face(14 + ((k - 1) % 3) * 76, 16 + Math.floor((k - 1) / 3) * 70, k); return s + cap("the six faces of a dice", 164); })();
const clock = (() => {
  const cx = 78, cy = 78; let s = circ(cx, cy, 62, "l f0");
  for (let h = 1; h <= 12; h++) { const p = pt(cx, cy, 49, 90 - h * 30), q = pt(cx, cy, 62, 90 - h * 30), r = pt(cx, cy, 57, 90 - h * 30); s += txt(p[0], p[1] + 4, String(h), "ts") + ln(q[0], q[1], r[0], r[1], "th2"); }
  const hh = pt(cx, cy, 28, 90 - 10 * 30 - 5), mm = pt(cx, cy, 44, 90 - 2 * 30);
  s += ln(cx, cy, hh[0], hh[1], "ar") + ln(cx, cy, mm[0], mm[1], "a") + dot(cx, cy, 3.5);
  s += ln(154, 60, 176, 60, "ar") + txt(180, 64, "hour hand", "tx tl") + txt(180, 76, "(short)", "ts tm tl") + ln(154, 100, 176, 100, "a") + txt(180, 104, "minute hand", "tx tl") + txt(180, 116, "(long)", "ts tm tl");
  return s + cap("an analogue clock face has an hour hand and a minute hand", 168, 44);
})();
const ruler = (() => { let s = rect(12, 50, 216, 50, "l f3", 4); for (let i = 0; i <= 100; i++) { const x = 20 + i * 2; s += ln(x, 50, x, 50 + (i % 10 === 0 ? 20 : i % 5 === 0 ? 14 : 8), "th2"); } for (let c = 0; c <= 10; c++) s += txt(20 + c * 20, 88, String(c), "ts"); return s + txt(220, 44, "cm", "ts tm te") + cap("a ruler: each number is 1 centimetre, each small mark is 1 millimetre", 152, 44); })();
const perimeter = (() => rect(60, 44, 120, 64, "l f1") + arrow(56, 108, 56, 44, "ar", 7) + arrow(60, 40, 180, 40, "ar", 7) + arrow(184, 44, 184, 108, "ar", 7) + arrow(180, 112, 60, 112, "ar", 7) + cap("perimeter: the distance all the way round the outside edge", 154, 44))();
const area = (() => { let s = ""; for (let r = 0; r < 5; r++) for (let c = 0; c < 7; c++) s += rect(36 + c * 24, 14 + r * 22, 24, 22, `th ${r < 3 && c < 5 ? "f1" : "f0"}`); return s + rect(36, 14, 120, 66, "l") + cap("area: the space inside a shape, counted in squares", 156); })();
const volume = (() => {
  const u = 24, ox = 50, oy = 112, dx = 12, dy = -10; // 3 wide, 2 high, 2 deep unit cubes; depth goes up-right
  const P = (x: number, y: number, z: number): [number, number] => [ox + x * u + z * dx, oy - y * u + z * dy];
  let s = poly([P(0, 2, 0), P(3, 2, 0), P(3, 2, 2), P(0, 2, 2)], "l f3") + poly([P(3, 0, 0), P(3, 2, 0), P(3, 2, 2), P(3, 0, 2)], "l f4") + poly([P(0, 0, 0), P(3, 0, 0), P(3, 2, 0), P(0, 2, 0)], "l f1");
  for (let x = 1; x < 3; x++) s += ln(...P(x, 0, 0), ...P(x, 2, 0), "th") + ln(...P(x, 2, 0), ...P(x, 2, 2), "th");
  s += ln(...P(0, 1, 0), ...P(3, 1, 0), "th") + ln(...P(3, 1, 0), ...P(3, 1, 2), "th") + ln(...P(3, 0, 1), ...P(3, 2, 1), "th") + ln(...P(0, 2, 1), ...P(3, 2, 1), "th");
  return s + cap("volume: the space inside a 3D shape, counted in unit cubes", 158, 44);
})();

export const NUMBER: Pic[] = [
  mk("number-line", "Number line 0 to 10", ["number line"], nl(0, 10), "A number line from 0 to 10 with a tick and a label at every whole number.", "A number line", "A number line places numbers in order at equal spacing (Oak: 'number line'). Drawn with equal 19.2-unit gaps from 0 to 10.", { numeric: true, avoid: ["negative", "below zero", "minus", "decimal", "fraction", "tenths", "hundredths", "inequality", "double number line", "ratio table", "scale", "unlabelled", "unmarked", "unnumbered", "partially marked", "blank number line", "empty number line"] }),
  mk("negative-number-line", "Number line -5 to 5", ["negative number"], nl(-5, 5), "A number line from negative 5 to 5 with zero in the middle.", "Negative numbers on a number line", "Negative numbers lie to the left of zero on a number line. Equal spacing from -5 to 5.", { numeric: true, avoid: ["unlabelled", "unmarked", "unnumbered", "partially marked", "blank number line", "empty number line", "decimal", "fraction", "tenths", "hundredths"] }),
  mk("place-value-chart", "Place value chart", ["place value", "place-value chart"], pv, "A place value chart with columns Thousands, Hundreds, Tens and Ones and an arrow saying each column is ten times the one to its right.", "Place value", "Each place is worth 10 times the place to its right (Oak KS1-KS2 place value). Column headings only, no example number.", { avoid: ["decimal", "tenth", "hundredth", "thousandth", "standard form", "significant", "ten thousand", "hundred thousand", "million", "billion", "10 000", "100 000"] }),
  mk("decimal-place-value", "Decimal place value", ["tenth", "hundredth", "decimal place"], pvDec, "A place value chart with columns Ones, Tenths and Hundredths and a decimal point after Ones.", "Decimal place value", "Tenths = one tenth of a one, hundredths = one tenth of a tenth; each place to the right is 10 times smaller.", { avoid: ["fraction wall", "thousandth"] }),
  mk("numerator-denominator", "Numerator and denominator", ["numerator", "denominator"], fracBar, "A bar split into four equal parts with three shaded, labelled: numerator is the number of parts we have; denominator is the number of equal parts in the whole.", "Numerator and denominator", "Numerator (top) = number of equal parts counted, denominator (bottom) = number of equal parts in the whole (Oak keywords). Example drawn: 3/4.", { numeric: true, avoid: ["improper", "mixed number", "unit fraction"] }),
  mk("fraction-wall", "Fraction wall", ["fraction wall", "equivalent fraction", "unit fraction"], wall, "A fraction wall: rows split into 1, 2, 3, 4, 5, 6, 8 and 10 equal parts, each row labelled with its unit fraction.", "Fraction wall", "Every row is the same total length split into equal parts (1, 1/2, 1/3, 1/4, 1/5, 1/6, 1/8, 1/10), so equal-length pieces show equivalent fractions.", { avoid: ["seventh", "ninth", "eleventh", "twelfth", "fifteenth", "twentieth", "hundredth", "1/7", "1/9", "1/11", "1/12"], doesNotShow: "fractions with denominators 7, 9, 11 or more; mixed numbers" }),
  mk("fraction-circles", "Halves, thirds and quarters", ["halves", "thirds", "quarters", "half", "third", "quarter"], fracCircles, "Three circles: one split into two equal halves, one into three equal thirds and one into four equal quarters, each with one part shaded.", "Halves, thirds and quarters", "A half is 1 of 2 equal parts, a third is 1 of 3, a quarter is 1 of 4. Sectors are drawn at exactly 180/120/90 degrees.", { requires: ["fraction", "equal part", "equal parts"], avoid: ["turn", "direction", "halve", "halving", "double", "doubling", "past", "o'clock", "clock", "half-life", "half life", "half term", "half-term", "half an hour", "quarter to", "third person", "third party", "third term", "1/2", "1/3", "1/4"], numeric: true }),
  mk("mixed-improper", "Improper fraction and mixed number", ["improper fraction", "mixed number"], improper, "Two rows of quarter-size pieces: one full row of four quarters (one whole) and one more quarter, showing 5/4 equals 1 and 1/4.", "Improper fraction and mixed number", "5/4 = 1 1/4: one whole (4 quarters) plus one quarter. An improper fraction has numerator greater than or equal to the denominator.", { numeric: true, avoid: ["half", "halves", "third", "fifth", "sixth", "seventh", "eighth", "ninth", "tenth", "twelfth", "hundredth"] }),
  mk("bar-model", "Bar model", ["bar model"], bar, "A bar model: a bar split into two parts under a bracket labelled whole.", "A bar model", "A bar model shows a whole as a bar split into parts (Oak: bar model).", { avoid: ["ratio", "comparison"] }),
  mk("part-whole-model", "Part-whole model", ["part-whole model", "part whole model", "part-whole", "number bond", "partition"], pw, "A part-whole model: one circle for the whole joined to two circles for the parts.", "A part-whole model", "Part-whole model: a whole split into parts (Oak KS1 'partition', 'part', 'whole'). No numbers drawn.", { avoid: ["fraction", "ratio", "percentage"] }),
  mk("array", "Array", ["array"], array, "An array of circles in three equal rows and four equal columns, with the rows and columns labelled.", "An array", "An array is objects arranged in equal rows and columns (Oak: array). 3 rows of 4 drawn as an example; no numbers written.", { avoid: ["arrays of data"] }),
  mk("ten-frame", "Ten frame", ["ten frame", "tens frame"], tenFrame, "An empty ten frame: ten boxes in two rows of five.", "A ten frame", "A ten frame has 10 boxes in 2 rows of 5.", {}),
  mk("hundred-square", "Hundred square", ["hundred square", "100 square"], hundred, "A hundred square: a grid of ten rows and ten columns.", "A hundred square", "A hundred square is a 10 by 10 grid (100 squares).", {}),
  mk("bar-chart", "Bar chart", ["bar chart", "bar graph"], barChart, "A bar chart with four bars labelled A to D and a frequency axis.", "A bar chart", "A bar chart uses bars whose heights show frequency for each category. No values drawn.", { avoid: ["histogram", "compound bar", "dual bar", "composite bar", "stacked"] }),
  mk("pictogram", "Pictogram", ["pictogram"], (() => { let s = ""; [3, 2, 4].forEach((k, r) => { s += txt(30, 42 + r * 34, "ABC"[r], "tb tl"); for (let i = 0; i < k; i++) s += circ(64 + i * 24, 38 + r * 34, 9, "l f3"); }); return s + txt(120, 136, "Key: each circle stands for 2", "ts") + cap("a pictogram uses pictures or symbols to show data", 166); })(), "A pictogram with three rows A, B and C of one, two or more circles and a key saying each circle stands for 2.", "A pictogram", "A pictogram uses symbols to represent data, with a key. Rows of 3, 2 and 4 symbols; key value 2.", { numeric: true }),
  mk("pie-chart", "Pie chart", ["pie chart"], pie, "A pie chart split into four sectors labelled A, B, C and D.", "A pie chart", "A pie chart shows parts of a whole as sectors of a circle. No values drawn.", { avoid: ["angle of each sector", "degrees"] }),
  mk("line-graph", "Line graph", ["line graph", "time series"], lineGraph, "A line graph: points joined by straight lines on axes labelled time and value.", "A line graph", "A line graph joins plotted points to show how a value changes (over time).", { avoid: ["straight line graph", "linear graph", "distance-time", "distance time", "velocity-time", "velocity time"] }),
  mk("scatter-graph", "Scatter graph (positive correlation)", ["scatter graph", "scatter diagram", "scatter plot", "line of best fit", "positive correlation"], scatterPos, "A scatter graph whose points rise from left to right with a line of best fit through them: positive correlation.", "Scatter graph", "Positive correlation: points rise left to right; the line of best fit passes through the middle of the points (drawn through the mean point).", { family: "correlation", avoid: ["outlier"] }),
  mk("scatter-negative", "Negative correlation", ["negative correlation"], scatterNeg, "A scatter graph whose points fall from left to right with a line of best fit: negative correlation.", "Negative correlation", "Negative correlation: as one variable increases the other decreases.", { family: "correlation" }),
  mk("scatter-none", "No correlation", ["no correlation", "zero correlation"], scatterNone, "A scatter graph with points spread randomly: no correlation.", "No correlation", "No correlation: no pattern between the variables.", { family: "correlation" }),
  mk("venn-diagram", "Venn diagram", ["venn diagram"], venn, "A Venn diagram of two overlapping circles A and B, with regions labelled only A, in both and only B.", "A Venn diagram", "A Venn diagram uses overlapping circles: overlap = in both sets (Oak: Venn diagram).", { subjects: ["Maths", "Science"], avoid: ["three circles", "3 circles", "three event", "three set", "3 event", "3 set", "three-event", "complement", "universal set", "intersection", "union", "probability"] }),
  mk("tally", "Tally marks", ["tally", "tally chart", "tally mark"], tally, "A group of five tally marks: four upright lines crossed by a fifth line.", "Tally marks", "Tally marks are counted in fives: four vertical lines and one diagonal across = 5.", { numeric: true }),
  mk("probability-scale", "Probability scale", ["probability scale"], probScale, "A probability scale from 0 (impossible) through 1/2 (even chance) to 1 (certain), with unlikely and likely in between.", "The probability scale", "Probability is measured from 0 (impossible) to 1 (certain), even chance = 1/2, unlikely between 0 and 1/2, likely between 1/2 and 1.", { avoid: ["tree diagram", "venn", "experimental", "relative frequency", "expected"] }),
  mk("dice", "Dice faces", ["dice", "die"], die, "The six faces of a dice showing 1 to 6 dots.", "Dice", "A standard dice has faces numbered 1 to 6 (dot patterns drawn correctly).", { avoid: ["diced", "dice the", "dice up", "two dice", "2 dice", "sum of two dice", "spinner", "biased", "unfair"] }),
  mk("analogue-clock", "Analogue clock face", ["analogue clock", "clock face", "hour hand", "minute hand"], clock, "An analogue clock face with the numbers 1 to 12, a short hour hand and a long minute hand labelled.", "An analogue clock", "An analogue clock has numerals 1 to 12 around the face, a short hour hand and a long minute hand. The hands are set to about ten past ten only as an example.", { numeric: true, avoid: ["digital", "24-hour", "24 hour", "=am", "=pm", "timetable", "past", "o'clock", "oclock", "quarter", "half", "tell the time", "telling the time", "telling time", "minutes", "seconds", "turn"] }),
  mk("ruler", "Ruler in centimetres", ["ruler"], ruler, "A ruler marked in centimetres from 0 to 10 with small marks for millimetres.", "A ruler", "A 30 cm ruler section: each numbered mark is 1 centimetre, each small mark 1 millimetre (10 mm = 1 cm). Ticks drawn at exact 2-unit intervals for mm.", { subjects: ["Maths", "Science"], numeric: true, avoid: ["ruler method", "protractor"] }),
  mk("perimeter", "Perimeter", ["perimeter"], perimeter, "A rectangle with arrows running all the way round its outside edge, showing perimeter.", "Perimeter", "Perimeter = the total distance around the outside of a 2D shape (Oak). Rectangle drawn as an example.", { avoid: ["circumference", "circle", "circular", "sector", "arc", "semicircle"] }),
  mk("area", "Area", ["area"], area, "A rectangle made of unit squares, with the squares inside it shaded to show the area is the space inside a shape.", "Area", "Area = the amount of space inside a 2D shape, counted in square units (Oak keyword 'area'). A 5 by 3 block of squares is shaded as an example.", { requires: ["square", "squares", "rectangle", "shape", "space inside", "cover", "unit"], avoid: ["area of a triangle", "area of a circle", "area of a trapezium", "area of a parallelogram", "area of a sector", "area of a kite", "area of a rhombus", "surface area", "cross-sectional area", "cross sectional area", "area under", "area of compound", "compound shape", "composite shape", "circle", "triangle", "trapezium", "parallelogram", "sphere", "cone", "cylinder", "prism", "pyramid", "cube", "cuboid", "sector", "population", "habitat", "sample", "sampling", "quadrat", "reaction", "leaf", "diffusion", "membrane", "absorption", "heat", "acre", "hectare", "area code", "area chart"] }),
  mk("volume", "Volume", ["volume"], volume, "A block made of unit cubes, showing that volume is the space inside a 3D shape counted in cubes.", "Volume", "Volume = the amount of space inside a 3D shape, measured in cubic units (Oak keyword 'volume'). Cuboid of 3 x 2 x 2 unit cubes drawn as an example.", { requires: ["cube", "cubes", "cuboid", "3d", "3-d", "space inside", "space", "solid", "cubic"], avoid: ["sphere", "cone", "cylinder", "pyramid", "prism", "hemisphere", "sound", "litre", "capacity", "millilitre", "gas", "liquid", "particle", "pressure", "temperature", "density", "concentration", "flow", "reaction", "cm3", "m3", "mass"] }),
];
void n; void range; void arc;
