// Physics pictures (Science): circuits, forces, waves, light, magnets, electromagnetic spectrum.
import type { Pic } from "./types";
import { svg, poly, path, ln, circ, rect, txt, dot, arrow, cap, arc, range } from "./helpers";

const W = 240, H = 170;
const S: Pic["subjects"] = ["Science"];
const mk = (id: string, title: string, concepts: string[], body: string, alt: string, caption: string, evidence: string, extra: Partial<Pic> = {}): Pic =>
  ({ id, title, alt, caption, subjects: S, concepts, doesNotShow: "anything not labelled", evidence, svg: svg(W, H, body), ...extra });

// circuit symbols, drawn horizontally around (0,0); wires meet at x = -30 and x = +30
const sym = {
  cell: `${ln(-30, 0, -3, 0)}${ln(-3, -11, -3, 11, "l")}${ln(3, -5, 3, 5, "l").replace('class="l"', 'class="l" stroke-width="4"')}${ln(3, 0, 30, 0)}`,
  battery: `${ln(-30, 0, -9, 0)}${ln(-9, -11, -9, 11)}${ln(-3, -5, -3, 5).replace('class="l"', 'class="l" stroke-width="4"')}${ln(3, -11, 3, 11)}${ln(9, -5, 9, 5).replace('class="l"', 'class="l" stroke-width="4"')}${ln(9, 0, 30, 0)}`,
  switchOpen: `${ln(-30, 0, -12, 0)}${ln(-12, 0, 10, -14)}${ln(12, 0, 30, 0)}${dot(-12, 0, 2.6)}${dot(12, 0, 2.6)}`,
  switchClosed: `${ln(-30, 0, 30, 0)}${dot(-12, 0, 2.6)}${dot(12, 0, 2.6)}`,
  lamp: `${ln(-30, 0, -12, 0)}${circ(0, 0, 12, "l f0")}${ln(-8.5, -8.5, 8.5, 8.5)}${ln(-8.5, 8.5, 8.5, -8.5)}${ln(12, 0, 30, 0)}`,
  resistor: `${ln(-30, 0, -14, 0)}${rect(-14, -6, 28, 12, "l f0")}${ln(14, 0, 30, 0)}`,
  ammeter: `${ln(-30, 0, -12, 0)}${circ(0, 0, 12, "l f0")}${txt(0, 4.5, "A", "tb")}${ln(12, 0, 30, 0)}`,
  voltmeter: `${ln(-30, 0, -12, 0)}${circ(0, 0, 12, "l f0")}${txt(0, 4.5, "V", "tb")}${ln(12, 0, 30, 0)}`,
  fuse: `${ln(-30, 0, -14, 0)}${rect(-14, -6, 28, 12, "l f0")}${ln(-14, 0, 14, 0)}${ln(14, 0, 30, 0)}`,
};
const put = (x: number, y: number, body: string, rot = 0) => `<g transform="translate(${x} ${y})${rot ? ` rotate(${rot})` : ""}">${body}</g>`;
const symbols = (() => {
  const items: [keyof typeof sym, string][] = [["cell", "cell"], ["battery", "battery"], ["switchOpen", "switch (open)"], ["switchClosed", "switch (closed)"], ["lamp", "lamp"], ["resistor", "resistor"], ["ammeter", "ammeter"], ["voltmeter", "voltmeter"], ["fuse", "fuse"]];
  return items.map(([k, l], i) => { const cx = 40 + (i % 3) * 80, cy = 24 + Math.floor(i / 3) * 50; return put(cx, cy, sym[k]) + txt(cx, cy + 26, l, "tx"); }).join("");
})();
const gap = (x: number, y: number, w: number, h: number) => `<rect x="${x}" y="${y}" width="${w}" height="${h}" class="f0" stroke="none"/>`;
const simple = (() => path("M40 36 H200 V134 H40 Z", "l") + gap(30, 70, 20, 30) + put(40, 85, sym.cell, 90) + gap(90, 26, 60, 20) + put(120, 36, sym.lamp) + gap(90, 124, 60, 20) + put(120, 134, sym.switchClosed) + txt(120, 22, "lamp", "tx") + txt(120, 156, "switch (closed)", "tx") + txt(20, 85, "cell", "tx te").replace('x="20"', 'x="30"').replace(' te"', ' te"') + cap("a complete circuit: the lamp lights", 168, 44))();
const series = (() => path("M40 36 H200 V134 H40 Z", "l") + gap(30, 70, 20, 30) + put(40, 85, sym.cell, 90) + gap(70, 26, 40, 20) + put(90, 36, sym.lamp.replace(/-30/g, "-20").replace("30", "20")) + gap(130, 26, 40, 20) + put(150, 36, sym.lamp.replace(/-30/g, "-20").replace("30", "20")) + gap(90, 124, 60, 20) + put(120, 134, sym.switchClosed) + cap("a series circuit: one loop, so the current has only one path", 168, 44))();
const parallel = (() => path("M40 36 H170 V134 H40 Z", "l") + ln(110, 36, 110, 134, "l") + dot(110, 36, 3) + dot(110, 134, 3) + gap(30, 70, 20, 30) + put(40, 85, sym.cell, 90) + gap(100, 70, 20, 30) + put(110, 85, sym.lamp, 90) + gap(160, 70, 20, 30) + put(170, 85, sym.lamp, 90) + cap("a parallel circuit: the current can take more than one path", 168, 44))();
// forces
const forces = (right: number, left: number, label: string, sub: string) => rect(100, 62, 40, 40, "l f1") + arrow(140, 82, 140 + right, 82, "ar", 9) + arrow(100, 82, 100 - left, 82, "a", 9) + txt(140 + right / 2, 66, "force", "tx tr") + txt(100 - left / 2, 66, "force", "tx ta") + txt(120, 30, label, "tb") + txt(120, 46, sub, "tx tm");
export const PHYSICS: Pic[] = [
  mk("circuit-symbols", "Circuit symbols", ["circuit symbol", "circuit diagram"], symbols + cap("standard circuit symbols", 168, 44), "Nine standard circuit symbols: cell, battery, open switch, closed switch, lamp, resistor, ammeter, voltmeter and fuse, each labelled.", "Circuit symbols", "UK standard symbols (Oak KS2/KS3/KS4 electricity): cell = long thin line + short thick line; battery = several cells; lamp = circle with a cross; resistor = rectangle; ammeter/voltmeter = circle with A/V; fuse = rectangle with a line through it.", { family: "circuit", requires: ["circuit", "circuits", "current", "electric", "electrical", "symbol"], avoid: ["nerve", "impulse", "biolog", "organism", "muscle", "series circuit", "parallel circuit", "biological", "cell membrane", "stem cell", "daniell", "electrochemical", "electrolytic", "fuel cell", "solar cell", "photocell", "nucleus", "cytoplasm", "organelle", "microscope", "animal cell", "plant cell", "bulb of", "light bulb moment", "circuit breaker", "circuit board", "integrated circuit", "short circuit", "tricuit"], doesNotShow: "LEDs, variable resistors, thermistors, LDRs" }),
  mk("simple-circuit", "Simple circuit", ["simple circuit", "complete circuit", "electrical circuit", "circuit"], simple, "A simple circuit: a cell, a lamp and a closed switch joined by wires in one complete loop.", "A simple circuit", "A complete circuit is a closed loop of wire containing a power source (cell) and a component (lamp); a closed switch completes it (Oak KS2 'circuit').", { family: "circuit", requires: ["current", "battery", "bulb", "lamp", "switch", "wire", "component", "electric", "electricity", "cell"], avoid: ["fitness", "muscle", "exercise", "athlete", "stretch", "series", "parallel", "circuit breaker", "circuit board", "integrated circuit", "short circuit", "circuit symbol", "circuit diagram", "water circuit", "circuit training", "resistance", "potential difference", "ammeter", "voltmeter", "resistor", "thermistor", "ldr", "diode", "led"], doesNotShow: "more than one component or branch; ammeters; voltmeters" }),
  mk("series-circuit", "Series circuit", ["series circuit"], series, "A series circuit: a cell, two lamps and a switch all in one single loop.", "A series circuit", "Series = components one after another in a single loop, so the same current flows through each (Oak KS3/KS4).", { family: "circuit", avoid: ["parallel"] }),
  mk("parallel-circuit", "Parallel circuit", ["parallel circuit"], parallel, "A parallel circuit: a cell connected to two branches, each with one lamp, so the current can take two paths.", "A parallel circuit", "Parallel = components on separate branches; current splits at the junctions (Oak KS3/KS4).", { family: "circuit", avoid: ["series"] }),
  mk("balanced-forces", "Balanced forces", ["balanced force"], forces(50, 50, "balanced forces", "equal size, opposite directions") + cap("the resultant force is zero, so the speed does not change", 166, 44), "A box with two equal arrows pushing in opposite directions: balanced forces.", "Balanced forces", "Balanced = equal and opposite forces, resultant force zero (Oak KS3 'balanced forces'). Arrows exactly 50 units each.", { family: "forces", avoid: ["unbalanced"], doesNotShow: "the cause of the forces; friction; weight" }),
  mk("unbalanced-forces", "Unbalanced forces", ["unbalanced force", "resultant force"], forces(76, 30, "unbalanced forces", "one force is bigger") + cap("there is a resultant force to the right, so the box speeds up", 166, 44), "A box with a long arrow pushing right and a shorter arrow pushing left: unbalanced forces, so there is a resultant force to the right.", "Unbalanced forces", "Unbalanced = forces of different sizes; resultant force in the direction of the bigger force, 76 - 30 = 46 units to the right (Oak KS3 'resultant force').", { family: "forces", avoid: ["balanced forces", "zero", "equilibrium", "vector sum", "components", "newton"], doesNotShow: "the cause of the forces; friction; weight; calculation" }),
  mk("transverse-wave", "Transverse wave", ["transverse wave", "wavelength", "amplitude", "crest", "trough"], (() => {
    const pts: string[] = []; for (let x = 20; x <= 180; x += 4) pts.push(`${x},${(84 - 34 * Math.sin(((x - 20) / 100) * Math.PI * 2)).toFixed(1)}`);
    return ln(14, 84, 228, 84, "th") + `<polyline points="${pts.join(" ")}" class="a"/>` + ln(145, 50, 218, 50, "h") + arrow(216, 84, 216, 52, "ar", 6) + arrow(216, 52, 216, 82, "ar", 6) + txt(232, 72, "amplitude", "tx tr te").replace('x="232"', 'x="212"') + arrow(45, 30, 145, 30, "ag", 6) + arrow(145, 30, 45, 30, "ag", 6) + txt(95, 22, "wavelength", "tx tg") + ln(45, 30, 45, 46, "h") + ln(145, 30, 145, 46, "h") + txt(45, 44, "crest", "tx") + txt(95, 128, "trough", "tx") + cap("a transverse wave: the vibration is at right angles to the direction of travel", 164, 44);
  })(), "A transverse wave drawn as a smooth up-and-down curve with the amplitude (crest height above the middle line) and the wavelength (distance between two crests) labelled.", "A transverse wave", "Transverse wave: crest, trough, amplitude (max displacement from rest), wavelength (crest to crest); oscillations perpendicular to the direction of energy transfer (Oak KS3/KS4). y = 84 - 34 sin(2 pi (x-20)/100): crest at x=45, 145; trough at x=95, 195.", { family: "waves", avoid: ["longitudinal", "sound", "compression", "rarefaction", "electromagnetic", "seismic", "p-wave", "s-wave", "frequency of", "wave speed", "wave equation"], doesNotShow: "frequency, period or wave speed; longitudinal waves" }),
  mk("longitudinal-wave", "Longitudinal wave", ["longitudinal wave", "compression", "rarefaction"], (() => {
    let s = ""; for (let i = 0; i < 38; i++) { const x0 = 25 + i * 5, x = x0 + 8 * Math.sin((2 * Math.PI * (x0 - 25)) / 80); s += ln(x, 52, x, 90, "th2"); }
    return s + txt(65, 108, "compression", "tx tr") + txt(105, 122, "rarefaction", "tx ta").replace('x="105"', 'x="105"') + txt(145, 108, "compression", "tx tr") + arrow(65, 40, 145, 40, "ag", 6) + arrow(145, 40, 65, 40, "ag", 6) + txt(105, 32, "wavelength", "tx tg") + cap("a longitudinal wave: the vibration is in the same direction as the wave travels", 164, 44);
  })(), "A longitudinal wave drawn as vertical lines that are squeezed close together in compressions and spread apart in rarefactions, with the wavelength measured between two compressions.", "A longitudinal wave", "Longitudinal wave: particles vibrate parallel to the direction of travel, forming compressions (close together) and rarefactions (spread out); wavelength = compression to compression (Oak KS3/KS4). Displacement x = x0 + 8 sin(2 pi x0/80): compressions at 65 and 145, rarefactions at 25, 105, 185.", { family: "waves", avoid: ["transverse", "electromagnetic", "seismic"], doesNotShow: "frequency, period, amplitude or wave speed; transverse waves" }),
  mk("reflection-of-light", "Law of reflection", ["law of reflection", "angle of incidence", "angle of reflection", "incident ray", "reflected ray", "reflect", "reflection"], (() => {
    const O: [number, number] = [120, 112], a = 40, L = 84, sx = O[0] - L * Math.sin((a * Math.PI) / 180), sy = O[1] - L * Math.cos((a * Math.PI) / 180), ex = O[0] + L * Math.sin((a * Math.PI) / 180);
    return ln(30, 112, 210, 112, "l") + range(18).map((i) => ln(34 + i * 10, 112, 28 + i * 10, 122, "th")).join("") + ln(120, 26, 120, 112, "h") + arrow(sx, sy, O[0], O[1], "ar", 8) + arrow(O[0], O[1], ex, sy, "ar", 8)
      + arc(120, 112, 30, 90, 130, "th2") + arc(120, 112, 30, 50, 90, "th2") + txt(104, 84, "i", "tb") + txt(138, 84, "r", "tb") + txt(sx - 4, sy - 6, "incident ray", "tx te").replace("te", "te") + txt(ex + 4, sy - 6, "reflected ray", "tx tl") + txt(124, 22, "normal", "tx tl") + txt(120, 134, "mirror", "tx tm") + cap("the angle of incidence i equals the angle of reflection r", 166, 44);
  })(), "A ray of light hitting a mirror and bouncing off. A dashed line called the normal is drawn at right angles to the mirror; the angle of incidence i and the angle of reflection r are equal.", "Reflection of light", "Law of reflection: angle of incidence = angle of reflection, both measured from the normal (Oak KS3 'reflection'). Rays drawn at 40 degrees each side of the normal, exact.", { family: "light", requires: ["light", "ray", "rays", "mirror", "normal", "incidence"], avoid: ["refraction", "refract", "reflect on", "reflect your", "reflecting on", "self-reflection", "reflection on", "total internal", "echo", "sound", "water wave", "reflection in the", "transformation", "translation"], doesNotShow: "scattering; images in a mirror; curved mirrors" }),
  mk("refraction-of-light", "Refraction of light", ["refraction", "refract", "refracted"], (() => {
    // (image QA: the block ends at y = 126 so the two caption lines (148, 160) sit clear of it; the refracted ray stays inside the block)
    const O: [number, number] = [120, 80], i = (50 * Math.PI) / 180, r = (30.7 * Math.PI) / 180;
    return rect(20, 80, 200, 46, "l f1") + ln(120, 14, 120, 134, "h") + arrow(O[0] - 66 * Math.sin(i), O[1] - 66 * Math.cos(i), O[0], O[1], "ar", 8) + arrow(O[0], O[1], O[0] + 46 * Math.sin(r), O[1] + 46 * Math.cos(r), "ar", 8)
      + arc(120, 80, 24, 90, 140, "th2") + arc(120, 80, 24, 270, 300.7, "th2") + txt(103, 60, "i", "tb") + txt(133, 108, "r", "tb") + txt(30, 34, "air", "ts tl") + txt(30, 118, "glass", "ts tl") + txt(124, 20, "normal", "tx tl") + cap("light bends towards the normal when it slows down going into glass", 160, 44);
  })(), "A ray of light going from air into a glass block. It bends towards the dashed normal line at the boundary, so the angle of refraction r is smaller than the angle of incidence i.", "Refraction of light", "Refraction: light changes direction when it changes speed at a boundary; entering a denser medium (air to glass) it bends TOWARDS the normal (Oak KS3/KS4). i = 50 degrees, r = arcsin(sin 50 / 1.5) = 30.7 degrees.", { family: "light", avoid: ["reflection", "reflected", "total internal", "critical angle", "lens", "prism", "dispersion", "leaving", "glass to air", "water to air", "into air", "away from the normal"], doesNotShow: "light leaving glass (bending away from the normal); lenses; prisms; total internal reflection" }),
  mk("magnet-poles", "Magnetic poles: attract and repel", ["magnetic pole", "north pole", "south pole", "like poles", "unlike poles", "opposite poles", "attract", "repel"], (() => {
    const bar = (x: number, y: number, left: "N" | "S") => { const r = left === "N" ? "S" : "N", f = (l: string) => (l === "N" ? "f4" : "f1"); return rect(x, y, 40, 22, `l ${f(left)}`) + rect(x + 40, y, 40, 22, `l ${f(r)}`) + txt(x + 20, y + 16, left, "tb") + txt(x + 60, y + 16, r, "tb"); };
    return bar(20, 34, "N") + bar(142, 34, "N") + arrow(102, 45, 120, 45, "ag", 6) + arrow(140, 45, 122, 45, "ag", 6) + txt(121, 28, "attract", "tx tg") + bar(20, 100, "N") + bar(142, 100, "S") + arrow(121, 111, 104, 111, "ar", 6) + arrow(121, 111, 138, 111, "ar", 6) + txt(121, 94, "repel", "tx tr") + cap("unlike poles attract, like poles repel", 166, 44);
  })(), "Two rows of bar magnets. In the top row a south pole faces a north pole and they attract. In the bottom row two south poles face each other and they repel.", "Magnetic poles", "Like poles repel, unlike poles attract (Oak KS2/KS3 'magnets'). Top: [N S] then [N S] so S faces N (attract). Bottom: [N S] then [S N] so S faces S (repel). N red, S blue.", { requires: ["magnet", "magnets", "magnetic", "pole", "poles"], avoid: ["charge", "static", "electron", "proton", "electric field", "electrostatic"], doesNotShow: "magnetic field lines; electromagnets" }),
  mk("em-spectrum", "Electromagnetic spectrum", ["electromagnetic spectrum"], (() => {
    const names = ["radio waves", "microwaves", "infrared", "visible light", "ultraviolet", "X-rays", "gamma rays"], cw = 30, x0 = 15; let s = `<defs><linearGradient id="emv"><stop offset="0" stop-color="#7a1fd0"/><stop offset=".2" stop-color="#3a5fc4"/><stop offset=".4" stop-color="#2fb56b"/><stop offset=".6" stop-color="#f4dc2f"/><stop offset=".8" stop-color="#f58d2b"/><stop offset="1" stop-color="#e2352b"/></linearGradient></defs>`;
    names.forEach((nm, i) => { s += (i === 3 ? `<rect x="${x0 + i * cw}" y="62" width="${cw}" height="36" fill="url(#emv)" stroke="#0005"/>` : rect(x0 + i * cw, 62, cw, 36, `th2 ${["f0", "f6", "f4", "f0", "f5", "f1", "f2"][i]}`)) + txt(x0 + i * cw + cw / 2, i % 2 ? 116 : 54, nm, "tx"); });
    return s + arrow(x0, 138, x0 + 7 * cw, 138, "ag", 7) + txt(120, 132, "frequency and energy increase", "tx tg") + arrow(x0 + 7 * cw, 156, x0, 156, "a", 7) + txt(120, 168, "wavelength increases", "tx ta").replace('y="168"', 'y="152"');
  })(), "The electromagnetic spectrum in order from radio waves, microwaves, infrared, visible light, ultraviolet and X-rays to gamma rays, with frequency increasing to the right and wavelength increasing to the left.", "The electromagnetic spectrum", "Order of increasing frequency: radio, microwave, infrared, visible, ultraviolet, X-ray, gamma (Oak KS3/KS4). Wavelength decreases as frequency increases. Band widths are equal (not to scale).", { doesNotShow: "actual wavelengths or frequencies; uses of each wave" }),
];
void poly;
