// Science pictures: matter, living things, chemistry and Earth/space. Words are the standard curriculum ones (Oak KS1-KS4 keywords).
import type { Pic } from "./types";
import { svg, poly, path, ln, circ, ell, rect, txt, dot, arrow, cap, pt, sector, tag, range } from "./helpers";

const W = 240, H = 170;
const S: Pic["subjects"] = ["Science"];
type P = [number, number];
const mk = (id: string, title: string, concepts: string[], body: string, alt: string, caption: string, evidence: string, extra: Partial<Pic> = {}): Pic =>
  ({ id, title, alt, caption, subjects: S, concepts, doesNotShow: "anything not labelled", evidence, svg: svg(W, H, body), ...extra });

// ── states of matter ────────────────────────────────────────────────────────
const matter = (() => {
  let s = rect(8, 22, 68, 84, "l f0") + rect(86, 22, 68, 84, "l f0") + rect(164, 22, 68, 84, "l f0");
  for (let r = 0; r < 5; r++) for (let c = 0; c < 4; c++) s += circ(23 + c * 16, 40 + r * 16, 7, "l f1"); // solid: regular rows, touching
  const liq: P[] = [[100, 96], [114, 98], [128, 96], [142, 96], [107, 84], [121, 86], [135, 84], [100, 72], [114, 72], [128, 72], [142, 70], [107, 60], [121, 58]]; // liquid: touching, irregular, sits at the bottom
  liq.forEach((p) => { s += circ(p[0], p[1], 7, "l f1"); });
  ([[178, 40], [214, 50], [190, 72], [222, 90], [176, 96], [204, 32]] as P[]).forEach((p) => { s += circ(p[0], p[1], 6, "l f1"); });
  return s + txt(42, 16, "solid", "ts") + txt(120, 16, "liquid", "ts") + txt(198, 16, "gas", "ts") + txt(42, 120, "close together,", "tx") + txt(42, 131, "fixed pattern", "tx") + txt(120, 120, "close together,", "tx") + txt(120, 131, "no fixed pattern", "tx") + txt(198, 120, "far apart,", "tx") + txt(198, 131, "moving fast", "tx") + cap("the particles in a solid, a liquid and a gas", 162, 44);
})();
const changes = (() => {
  const bx = (x: number, l: string) => rect(x, 72, 44, 36, "l f1", 6) + txt(x + 22, 94, l, "ts");
  return bx(6, "solid") + bx(98, "liquid") + bx(190, "gas")
    + arrow(54, 80, 96, 80, "ar", 6) + txt(75, 74, "melting", "tx tr") + arrow(96, 100, 54, 100, "a", 6) + txt(75, 116, "freezing", "tx ta")
    + arrow(146, 80, 188, 80, "ar", 6) + txt(167, 74, "boiling", "tx tr") + arrow(188, 100, 146, 100, "a", 6) + txt(167, 116, "condensing", "tx ta")
    + path("M28 70 C28 22 212 22 212 66", "ar") + `<polygon points="212,70 207,60 217,60" class="hdr"/>` + txt(120, 52, "sublimation", "tx tr")
    + path("M212 110 C212 156 28 156 28 114", "a") + `<polygon points="28,110 23,120 33,120" class="hda"/>` + txt(120, 134, "deposition", "tx ta")
    + txt(120, 167, "red: energy taken in    blue: energy given out", "tx tm");
})();
// ── living things ───────────────────────────────────────────────────────────
const stack = (x: number, y: number, emoji: string, l1: string, l2: string, l3 = "") => rect(x, y, 66, 74, "l f1", 8) + `<text x="${x + 33}" y="${y + 24}" class="t tb">${emoji}</text>` + txt(x + 33, y + 40, l1, "ts") + txt(x + 33, y + 52, l2, "tx tm") + (l3 ? txt(x + 33, y + 63, l3, "tx tm") : "");
const chain = (() => stack(4, 36, "🌿", "grass", "producer") + stack(87, 36, "🐇", "rabbit", "primary", "consumer") + stack(170, 36, "🦊", "fox", "secondary", "consumer")
  + arrow(70, 73, 87, 73, "ar", 7) + arrow(153, 73, 170, 73, "ar", 7) + txt(120, 26, "arrows show the way energy passes on", "ts tm") + txt(120, 126, "the rabbit is a herbivore, the fox a carnivore", "tx tm") + cap("a food chain starts with a producer", 160, 44))();
const web = (() => {
  const node = (x: number, y: number, e: string, l: string) => `<text x="${x}" y="${y}" class="t tb">${e}</text>` + txt(x, y + 12, l, "tx");
  const G: P = [120, 128], R: P = [50, 86], Mo: P = [190, 86], F: P = [88, 30], O: P = [180, 30];
  return arrow(G[0] - 14, G[1] - 18, R[0] + 10, R[1] + 16, "ar", 6) + arrow(G[0] + 14, G[1] - 18, Mo[0] - 10, Mo[1] + 16, "ar", 6) + arrow(R[0] + 12, R[1] - 20, F[0] - 8, F[1] + 18, "ar", 6) + arrow(Mo[0] - 14, Mo[1] - 20, F[0] + 12, F[1] + 18, "ar", 6) + arrow(Mo[0] + 2, Mo[1] - 22, O[0], O[1] + 18, "ar", 6)
    + node(G[0], G[1], "🌿", "grass") + node(R[0], R[1], "🐇", "rabbit") + node(Mo[0], Mo[1], "🐁", "mouse") + node(F[0], F[1], "🦊", "fox") + node(O[0], O[1], "🦉", "owl") + cap("a food web: linked food chains (arrows point to the eater)", 164, 44);
})();
const plant = (() => path("M100 150 V66", "ag") + path("M100 116 C78 116 66 102 62 92 C82 90 96 100 100 112", "l f2") + path("M100 98 C122 98 134 84 138 74 C118 72 104 82 100 94", "l f2")
  + [0, 1, 2, 3, 4].map((i) => { const a = 90 + i * 72, c = pt(100, 50, 15, a); return `<ellipse cx="${c[0].toFixed(1)}" cy="${c[1].toFixed(1)}" rx="9" ry="14" transform="rotate(${-(a - 90)} ${c[0].toFixed(1)} ${c[1].toFixed(1)})" class="l f4"/>`; }).join("") + circ(100, 50, 8, "l f3")
  + ln(10, 130, 230, 130, "th") + path("M100 130 C92 140 84 148 78 158 M100 130 C100 144 100 152 98 162 M100 130 C110 140 118 148 126 158", "l")
  + tag("flower", 150, 40, 116, 46) + tag("leaf", 150, 80, 128, 82) + tag("stem", 150, 112, 102, 112) + tag("roots", 150, 150, 112, 146) + txt(14, 124, "soil", "tx tm tl"))();
const flower = (() => {
  const petal = (sx: number) => `<ellipse cx="${120 + sx * 34}" cy="86" rx="15" ry="42" transform="rotate(${sx * 22} ${120 + sx * 34} 86)" class="l f4"/>`;
  return petal(-1) + petal(1) + ln(120, 118, 120, 150, "ag") /* (image QA: stem stops above the caption line) */ + ell(102, 130, 9, 4, "l f2").replace("<ellipse", '<ellipse transform="rotate(-25 102 130)"') + ell(138, 130, 9, 4, "l f2").replace("<ellipse", '<ellipse transform="rotate(25 138 130)"')
    + ln(120, 100, 120, 50, "l") + ell(120, 46, 8, 6, "l f2") + ell(120, 104, 11, 15, "l f3")
    + ln(100, 116, 96, 66, "l") + ell(96, 62, 6, 9, "l f5") + ln(140, 116, 144, 66, "l") + ell(144, 62, 6, 9, "l f5")
    + tag("anther", 60, 48, 92, 58, "r") + tag("filament", 60, 92, 98, 92, "r") + tag("sepal", 60, 134, 94, 131, "r") + tag("stigma", 172, 34, 128, 44) + tag("petal", 176, 76, 150, 74) + tag("ovary", 172, 108, 131, 106)
    + cap("parts of a flower", 166, 44);
})();
const animalCell = (() => `<ellipse cx="90" cy="84" rx="66" ry="58" class="l f1"/>` + circ(76, 84, 20, "l f3") + circ(71, 79, 5, "l f5")
  + `<ellipse cx="120" cy="62" rx="13" ry="7" class="l f4"/><path d="M111 62 q4-4 8 0 t8 0" class="th"/>` + `<ellipse cx="84" cy="122" rx="13" ry="7" class="l f4"/><path d="M75 122 q4-4 8 0 t8 0" class="th"/>`
  + [[50, 58], [112, 100], [130, 90], [58, 110], [104, 40]].map((p) => dot(p[0], p[1], 1.8)).join("")
  + tag("cell membrane", 166, 28, 140, 46) + tag("mitochondrion", 166, 60, 132, 62) + tag("nucleus", 166, 92, 96, 84) + tag("cytoplasm", 166, 124, 122, 112) + cap("an animal cell", 160, 44))();
const plantCell = (() => rect(12, 22, 140, 124, "l f6", 10) + rect(18, 28, 128, 112, "th f1", 8) + rect(60, 48, 60, 74, "l f0", 12) + circ(128, 108, 12, "l f3") + circ(124, 104, 3.5, "l f5")
  + [[36, 42], [126, 40], [38, 128]].map((p) => `<ellipse cx="${p[0]}" cy="${p[1]}" rx="11" ry="6" class="l f2"/>`).join("")
  + tag("cell wall", 162, 30, 152, 40) + tag("chloroplast", 162, 58, 137, 41) + tag("vacuole", 162, 88, 120, 88) + tag("nucleus", 162, 116, 140, 108) + tag("cytoplasm", 162, 140, 106, 132) + cap("a plant cell", 164, 44))();
const eq = (parts: [number, number, string, string, string?][], plus: number[], arrowAt: [number, number], col: string) => parts.map(([x, w, a, f, b]) => rect(x, 44, w, 36, `l ${f}`, 6) + (b ? txt(x + w / 2, 59, a, "tx") + txt(x + w / 2, 71, b, "tx") : txt(x + w / 2, 65, a, "tx"))).join("") + plus.map((x) => txt(x, 66, "+", "tb")).join("") + arrow(arrowAt[0], 62, arrowAt[1], 62, col, 8);
const photo = eq([[2, 54, "carbon", "f1", "dioxide"], [70, 38, "water", "f2"], [142, 44, "glucose", "f3"], [200, 38, "oxygen", "f4"]], [62, 193], [112, 138], "ag") + txt(120, 26, "light energy is absorbed by chlorophyll", "tx tm") + txt(120, 106, "in the chloroplasts of green plants and algae", "tx tm") + cap("photosynthesis: carbon dioxide + water → glucose + oxygen", 160, 44);
const resp = eq([[2, 46, "glucose", "f3"], [62, 46, "oxygen", "f4"], [138, 52, "carbon", "f1", "dioxide"], [204, 34, "water", "f2"]], [55, 197], [112, 134], "ar") + txt(120, 106, "energy is released (in the mitochondria)", "tx tm") + cap("aerobic respiration: glucose + oxygen → carbon dioxide + water", 160, 44);
const water = (() => {
  const rays = range(8).map((i) => { const a = pt(22, 22, 14, i * 45), b = pt(22, 22, 20, i * 45); return ln(a[0], a[1], b[0], b[1], "ao"); }).join("");
  return rect(0, 134, 240, 36, "l f1") + poly([[170, 134], [206, 92], [240, 134]], "l f2") + circ(22, 22, 10, "l f3") + rays
    + `<ellipse cx="168" cy="32" rx="30" ry="13" class="l f0"/><ellipse cx="150" cy="38" rx="17" ry="10" class="l f0"/><ellipse cx="188" cy="38" rx="17" ry="10" class="l f0"/>`
    + arrow(60, 130, 60, 70, "ar", 7) + txt(68, 104, "evaporation", "tx tr tl") + arrow(92, 62, 128, 44, "a", 7) + txt(126, 30, "condensation", "tx ta te")
    + [0, 1, 2, 3].map((i) => ln(158 + i * 9, 54, 154 + i * 9, 72, "a")).join("") + txt(150, 90, "precipitation", "tx ta")
    + arrow(222, 112, 232, 130, "ag", 6) + txt(206, 150, "run-off", "tx tg") + txt(30, 150, "sea", "ts tl") + cap("the water cycle", 166, 44);
})();
const earth = (() => circ(80, 84, 64, "l f3") + circ(80, 84, 61, "l f4") + circ(80, 84, 35, "l f5").replace("f5", "f3") + circ(80, 84, 12, "l f4").replace("f4", "f5")
  + tag("crust (thin)", 150, 26, 122, 48) + tag("mantle", 150, 62, 118, 60) + tag("outer core (liquid)", 150, 96, 100, 96) + tag("inner core (solid)", 150, 130, 86, 90) /* (image QA: labels end inside the 240 frame) */ + cap("the structure of the Earth (not to scale)", 164, 44))();
const moon = (() => {
  const lit = (k: number, waxing: boolean, cx: number, cy: number, r: number): string => {
    if (k === -1) return "";
    if (k === 1) return circ(cx, cy, r, "th f3");
    const rx = Math.abs(k) * r, top = `${cx} ${cy - r}`, bot = `${cx} ${cy + r}`; // k in (-1,1): >0 crescent, <0 gibbous, 0 quarter
    const term = k === 0 ? `L${top}` : `A${rx.toFixed(2)} ${r} 0 0 ${k > 0 ? 0 : 1} ${top}`;
    const d = `M${top} A${r} ${r} 0 0 1 ${bot} ${term} Z`;
    return `<path d="${d}" class="th f3"${waxing ? "" : ` transform="translate(${2 * cx} 0) scale(-1 1)"`}/>`;
  };
  const ph: [string, string, number, boolean][] = [["new moon", "", -1, true], ["waxing", "crescent", 0.5, true], ["first", "quarter", 0, true], ["waxing", "gibbous", -0.5, true], ["full moon", "", 1, true], ["waning", "gibbous", -0.5, false], ["last", "quarter", 0, false], ["waning", "crescent", 0.5, false]];
  let s = ""; ph.forEach(([a, b, k, w], i) => { const cx = 30 + (i % 4) * 60, cy = 36 + Math.floor(i / 4) * 74; s += circ(cx, cy, 20, "l f6") + lit(k, w, cx, cy, 20) + circ(cx, cy, 20, "l") + txt(cx, cy + 32, a, "tx") + (b ? txt(cx, cy + 43, b, "tx") : ""); });
  return s;
})();
const solar = (() => {
  const pl: [string, number][] = [["Mercury", 3], ["Venus", 5], ["Earth", 5.5], ["Mars", 4], ["Jupiter", 10], ["Saturn", 8.5], ["Uranus", 6.5], ["Neptune", 6.5]];
  let s = circ(28, 78, 22, "l f3") + txt(28, 112, "Sun", "tx"); let x = 74;
  pl.forEach(([nm, r], i) => { x += r; s += circ(x, 78, r, "l f1") + txt(x, i % 2 ? 78 + r + 12 : 78 - r - 6, nm, "tt"); x += r + 8; });
  return s + cap("the Sun and the eight planets, in order (not to scale)", 164, 44);
})();
const table = (() => {
  const cw = 24, ch = 18, y0 = 28, cols = [1, 2, 13, 14, 15, 16, 17, 18], xOf = (g: number) => 12 + cols.indexOf(g) * cw + (cols.indexOf(g) >= 2 ? 16 : 0);
  const els: [string, number, number, string][] = [["H", 0, 1, "f0"], ["He", 0, 18, "f2"], ["Li", 1, 1, "f3"], ["Be", 1, 2, "f1"], ["B", 1, 13, "f1"], ["C", 1, 14, "f1"], ["N", 1, 15, "f1"], ["O", 1, 16, "f1"], ["F", 1, 17, "f4"], ["Ne", 1, 18, "f2"],
    ["Na", 2, 1, "f3"], ["Mg", 2, 2, "f1"], ["Al", 2, 13, "f1"], ["Si", 2, 14, "f1"], ["P", 2, 15, "f1"], ["S", 2, 16, "f1"], ["Cl", 2, 17, "f4"], ["Ar", 2, 18, "f2"], ["K", 3, 1, "f3"], ["Ca", 3, 2, "f1"]];
  let s = "";
  els.forEach(([sym, r, g, f]) => { s += rect(xOf(g), y0 + r * ch, cw, ch, `th2 ${f}`) + txt(xOf(g) + cw / 2, y0 + r * ch + 13, sym, "ts"); });
  ([[1, "1"], [2, "2"], [13, "3"], [14, "4"], [15, "5"], [16, "6"], [17, "7"], [18, "0"]] as [number, string][]).forEach(([g, l]) => { s += txt(xOf(g) + cw / 2, 24, l, "tx tm"); });
  s += rect(12, 104, 9, 9, "th2 f3") + txt(25, 112, "Group 1: alkali metals", "tx tl") + rect(12, 117, 9, 9, "th2 f4") + txt(25, 125, "Group 7: halogens", "tx tl") + rect(12, 130, 9, 9, "th2 f2") + txt(25, 138, "Group 0: noble gases", "tx tl");
  return s + txt(210, 130, "", "tx") + cap("the first 20 elements (transition metals not drawn)", 164, 44);
})();
const atom = (() => { let s = circ(90, 84, 54, "th f0") + circ(90, 84, 32, "th f0") + circ(90, 84, 14, "l f4"); [[90 - 32, 84], [90 + 32, 84]].forEach((p) => { s += circ(p[0], p[1], 4.5, "l fs"); }); [45, 135, 225, 315].forEach((a) => { const p = pt(90, 84, 54, a); s += circ(p[0], p[1], 4.5, "l fs"); });
  return s + tag("nucleus: protons and neutrons", 150, 30, 98, 76, "l").replace("nucleus: protons and neutrons", "nucleus") + tag("electron", 150, 62, 131, 66) + tag("shell (energy level)", 150, 100, 137, 84).replace("shell (energy level)", "electron shell") + txt(150, 122, "example: carbon", "tx tm tl") + cap("an atom: a nucleus with electrons in shells", 164, 44); })();
const PH = ["#d7191c", "#e2352b", "#ef5a2a", "#f58d2b", "#f7b52c", "#f4dc2f", "#b5d334", "#3fb56b", "#2ba7a0", "#2b86c5", "#3a5fc4", "#4b48b8", "#5b3aa8", "#6a2c98", "#7a1f88"];
const phScale = (() => { let s = ""; PH.forEach((c, i) => { s += `<rect x="${12 + i * 15.2}" y="56" width="15.2" height="34" fill="${c}" stroke="#0004" stroke-width=".5"/>` + txt(19.6 + i * 15.2, 106, String(i), "tx"); }); return s + txt(40, 44, "acid", "ts tr") + txt(120, 44, "neutral", "ts tg") + txt(200, 44, "alkaline", "ts ta") + txt(120, 124, "the colours of universal indicator", "tx tm") + cap("the pH scale: 0 is strongly acidic, 14 strongly alkaline", 164, 44); })();
const profile = (exo: boolean) => {
  const R = exo ? 90 : 122, Pd = exo ? 122 : 90, pk = 40;
  return arrow(30, 146, 224, 146, "l", 7) + arrow(30, 146, 30, 12, "l", 7) + txt(126, 160, "progress of the reaction", "tx tm") + `<text x="18" y="80" class="t tx tm" transform="rotate(-90 18 80)">energy</text>`
    + path(`M34 ${R} H78 C102 ${R} 96 ${pk} 124 ${pk} C152 ${pk} 146 ${Pd} 168 ${Pd} H190`, "a") + txt(56, exo ? R - 6 : R + 14, "reactants", "tx") + txt(176, exo ? Pd + 14 : Pd - 6, "products", "tx")
    + arrow(124, R, 124, pk + 4, "ag", 6) + txt(36, 24, "activation energy", "tx tg tl") + ln(96, 27, 122, 60, "th")
    + ln(168, R, 200, R, "h") + (exo ? arrow(196, R + 1, 196, Pd - 1, "ar", 6) + txt(197, 104, "energy", "tx tr tl") + txt(197, 115, "released", "tx tr tl") : arrow(196, R - 1, 196, Pd + 1, "ar", 6) + txt(197, 104, "energy", "tx tr tl") + txt(197, 115, "taken in", "tx tr tl"));
};
export const SCIENCE: Pic[] = [
  mk("states-of-matter", "States of matter", ["states of matter", "state of matter", "particle model", "solid liquid and gas", "solids liquids and gases", "solids liquids gases", "solid liquid gas", "solids and liquids", "liquids and gases", "solids and gases"], matter, "Three boxes showing particles: in a solid they are close together in a fixed pattern, in a liquid close together but not in a pattern, in a gas far apart and moving fast.", "Solid, liquid and gas", "Particle model: solid = particles touching in a regular pattern; liquid = touching, irregular, can flow; gas = far apart, random, fast (Oak KS3 'states of matter'). Drawn: 5x4 lattice; 13 touching particles at the bottom; 6 spread-out particles.", { avoid: ["greenhouse gas", "natural gas", "gas exchange", "noble gas", "gas syringe", "gas jar", "gas tap", "gas cooker", "gas particles only", "solid state", "solid solution", "solute", "solvent", "gas collection", "sublimation", "deposition", "solid-state"], doesNotShow: "changes of state; forces between particles; mixtures" }),
  mk("changes-of-state", "Changes of state", ["change of state", "melting", "freezing", "evaporation", "condensation", "boiling", "sublimation", "deposition", "evaporating", "condensing", "melting point", "boiling point"], changes, "A diagram of solid, liquid and gas with arrows: melting and freezing between solid and liquid, boiling and condensing between liquid and gas, and sublimation and deposition between solid and gas.", "Changes of state", "Melting: solid to liquid; freezing: liquid to solid; boiling/evaporating: liquid to gas; condensing: gas to liquid; sublimation: solid to gas; deposition: gas to solid. Warming changes (melting, boiling, sublimation) are red arrows, cooling changes blue.", { requires: ["solid", "liquid", "gas", "state", "ice", "steam", "vapour"], avoid: ["polymer", "condensation polymer", "pollen", "melting pot", "freezing weather", "rock"], doesNotShow: "temperatures; particle arrangements" }),
  mk("food-chain", "Food chain", ["food chain", "primary consumer", "secondary consumer"], chain, "A food chain: grass, then a rabbit, then a fox, with arrows pointing from food to eater. Grass is the producer, the rabbit the primary consumer and the fox the secondary consumer.", "A food chain", "Food chain: energy passes from producer to consumers; arrows point from the food to the animal that eats it (Oak KS2 'food chain'). Grass -> rabbit -> fox is a standard example; rabbit is a herbivore, fox a carnivore.", { family: "food", avoid: ["food web", "tertiary", "apex", "decomposer", "trophic", "biomass", "pyramid", "omnivore", "bioaccumulation", "energy transfer", "10%", "efficiency", "customer", "economy", "market", "consumer goods", "consumer rights"], doesNotShow: "decomposers, omnivores, tertiary consumers; energy amounts" }),
  mk("food-web", "Food web", ["food web"], web, "A food web: grass is eaten by a rabbit and a mouse, the rabbit is eaten by a fox, the mouse by a fox and an owl. Arrows point from food to eater.", "A food web", "Food web = several linked food chains. Grass -> rabbit -> fox; grass -> mouse -> fox; mouse -> owl.", { family: "food", avoid: ["decomposer", "trophic", "biomass"] }),
  mk("plant-parts", "Parts of a plant", ["parts of a plant", "plant parts", "flowering plant", "root", "stem", "leaf", "leaves", "flower"], plant, "A plant with its flower, leaves, stem and roots labelled.", "Parts of a plant", "Flowering plant: roots (below soil), stem, leaves, flower (Oak KS1 'plants'). Drawn: labelled parts only.", { requires: ["plant", "plants", "seed", "seeds", "soil", "grow"], avoid: ["life cycle", "stem cell", "stem cells", "root hair", "root cell", "cell", "cells", "palisade", "stomata", "xylem", "phloem", "tissue", "transpiration", "stamen", "carpel", "anther", "stigma", "ovary", "pollen", "petal", "sepal", "root word", "square root", "flower of", "cauliflower", "photosynthesis", "flowering time", "root of an equation"], family: "plants", doesNotShow: "internal structure; flower parts; seeds" }),
  mk("flower-parts", "Parts of a flower", ["parts of a flower", "stamen", "carpel", "anther", "stigma", "filament", "petal", "sepal"], flower, "A flower cut in half showing the petals, sepals, the stamens (anther on a filament) and the carpel (stigma on top, ovary at the base).", "Parts of a flower", "Stamen = anther + filament (male); carpel = stigma + style + ovary (female); petals attract pollinators; sepals protect the bud (Oak KS2-KS3 'flower'). Style is drawn but not labelled.", { requires: ["flower", "flowers", "plant", "pollen", "pollination"], avoid: ["human", "ovulation", "uterus", "reproductive system", "female reproductive", "male reproductive", "fruit", "seed dispersal", "germination", "wind pollinated", "insect pollinated", "wind-pollinated", "insect-pollinated"], family: "plants", doesNotShow: "pollination or fertilisation; wind-pollinated flowers" }),
  mk("animal-cell", "Animal cell", ["animal cell"], animalCell, "An animal cell with the cell membrane, cytoplasm, nucleus and a mitochondrion labelled.", "An animal cell", "Animal cell: cell membrane, cytoplasm, nucleus, mitochondria (and ribosomes). No cell wall, chloroplasts or permanent vacuole (Oak KS3/KS4 'animal cell').", { family: "cell", avoid: ["bacteri", "prokaryot", "specialised", "sperm", "nerve cell", "red blood cell", "white blood cell", "ciliated", "stem cell", "plant and animal", "and plant cell", "plant cell"], doesNotShow: "ribosomes, endoplasmic reticulum, specialised animal cells" }),
  mk("plant-cell", "Plant cell", ["plant cell", "chloroplast", "cell wall", "vacuole"], plantCell, "A plant cell with the cell wall, chloroplasts, a large vacuole, the nucleus and the cytoplasm labelled.", "A plant cell", "Plant cell: cell wall (cellulose), cell membrane, cytoplasm, nucleus, chloroplasts, permanent vacuole (Oak KS3/KS4 'plant cell'). The cell membrane is drawn as the thin line inside the wall, not labelled.", { family: "cell", requires: ["cell", "cells"], avoid: ["bacteri", "prokaryot", "fung", "yeast", "algae", "specialised", "root hair", "palisade", "guard cell", "xylem", "phloem", "animal cell", "photosynthesis", "respiration"], doesNotShow: "mitochondria, ribosomes, specialised plant cells" }),
  mk("photosynthesis", "Photosynthesis word equation", ["photosynthesis"], photo, "The word equation for photosynthesis: carbon dioxide plus water makes glucose plus oxygen, using light energy, in the chloroplasts of green plants.", "Photosynthesis", "Photosynthesis: carbon dioxide + water -> glucose + oxygen, needs light, in chloroplasts (Oak KS3 'photosynthesis').", { family: "energy-equations", avoid: ["anaerobic", "limiting factor", "rate of photosynthesis", "light intensity", "chlorophyll test", "starch test", "leaf disc", "pondweed"], doesNotShow: "the symbol equation; limiting factors" }),
  mk("respiration", "Aerobic respiration word equation", ["aerobic respiration", "cellular respiration", "respiration"], resp, "The word equation for aerobic respiration: glucose plus oxygen makes carbon dioxide plus water, releasing energy.", "Aerobic respiration", "Aerobic respiration: glucose + oxygen -> carbon dioxide + water, energy released (Oak KS3/KS4 'respiration'). Not the equation for anaerobic respiration.", { family: "energy-equations", avoid: ["anaerobic", "fermentation", "lactic", "ethanol", "breathing", "gas exchange", "rate of respiration", "respirometer", "yeast"], doesNotShow: "anaerobic respiration; the symbol equation" }),
  mk("water-cycle", "The water cycle", ["water cycle"], water, "The water cycle: the Sun heats the sea so water evaporates and rises, condenses into clouds, falls as precipitation on land and runs back to the sea.", "The water cycle", "Water cycle: evaporation, condensation, precipitation, run-off/collection (Oak KS2/KS3 'water cycle').", { avoid: ["carbon cycle", "nitrogen cycle", "rock cycle", "life cycle"], doesNotShow: "transpiration, groundwater, freezing" }),
  mk("earth-structure", "Structure of the Earth", ["structure of the earth", "layers of the earth", "inner core", "outer core", "mantle", "crust"], earth, "The layers of the Earth from the centre: a solid inner core, a liquid outer core, the mantle and a thin crust.", "The structure of the Earth", "Earth: inner core (solid), outer core (liquid), mantle, thin crust (Oak KS3 'structure of the Earth'). Radii drawn about to scale for core/mantle boundaries (1220, 3480, 6340, 6371 km); crust exaggerated for visibility.", { requires: ["earth", "core", "mantle", "crust", "layers"], avoid: ["bread", "pie", "cell", "crustal", "mantle of a"], doesNotShow: "tectonic plates, the lithosphere" }),
  mk("moon-phases", "Phases of the Moon", ["phases of the moon", "moon phase", "lunar phase", "waxing", "waning", "gibbous", "full moon", "new moon", "crescent moon"], moon, "Eight phases of the Moon in order: new moon, waxing crescent, first quarter, waxing gibbous, full moon, waning gibbous, last quarter, waning crescent.", "Phases of the Moon", "The lit part grows on the right (waxing) then shrinks on the right side... drawn for the northern hemisphere: waxing = lit on the right, waning = lit on the left. Terminator ellipse widths 0.5r for crescent/gibbous, 0 for quarters.", { doesNotShow: "why the phases happen (the Sun, Earth and Moon positions); eclipses", avoid: ["eclipse", "tide", "tides", "southern hemisphere"] }),
  mk("solar-system", "The solar system", ["solar system", "planet"], solar, "The Sun and the eight planets in order from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune, not to scale.", "The solar system", "Order from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune (IAU 2006). Planet sizes roughly relative to each other; distances not to scale.", { requires: ["sun", "orbit", "star", "solar system", "mercury", "venus", "mars", "jupiter", "saturn", "neptune", "uranus", "gravity"], avoid: ["satellite", "geostationary", "polar orbit", "theor", "history", "developed", "ptolemy", "copernicus", "geocentric", "heliocentric", "galileo", "exoplanet", "dwarf planet", "pluto", "climate", "emission", "pollution", "environment", "carbon", "global warming", "sustainab", "recycl", "galaxy", "universe", "big bang", "our planet", "protect the planet"], doesNotShow: "dwarf planets, moons, asteroids; true distances" }),
  mk("periodic-table", "Periodic table (first 20 elements)", ["periodic table"], table, "The first 20 elements of the periodic table with their symbols in rows (periods) and columns (groups), with Group 1 (alkali metals), Group 7 (halogens) and Group 0 (noble gases) coloured.", "The periodic table", "Elements 1-20: H, He / Li Be B C N O F Ne / Na Mg Al Si P S Cl Ar / K Ca in their standard groups (UK numbering 1-7 and 0). Only main-group positions are drawn.", { avoid: ["mendeleev", "development", "history", "weight", "newlands", "dobereiner", "transition metal", "lanthanide", "actinide", "electron configuration", "atomic number", "trends"], doesNotShow: "elements beyond calcium, transition metals, atomic numbers or masses" }),
  mk("atom", "Atomic structure (carbon)", ["atom", "atomic structure", "electron shell", "electron shells"], atom, "An atom: a small nucleus in the centre with electrons on shells around it; the example drawn is carbon with 2 electrons on the inner shell and 4 on the outer shell.", "An atom", "Atom = nucleus (protons + neutrons) with electrons in shells; carbon has 6 electrons arranged 2,4. Nucleus drawn not to scale.", { numeric: true, requires: ["nucleus", "proton", "electron", "neutron", "shell"], avoid: ["atom economy", "isotope", "ion", "ionic", "bond", "covalent", "atomic number", "mass number", "relative atomic", "half-life", "radioactive", "decay", "fission", "fusion", "alpha", "beta", "gamma", "plum pudding", "rutherford", "bohr", "model of the atom", "history"], doesNotShow: "protons and neutrons individually; other elements; real sizes" }),
  mk("ph-scale", "pH scale", ["ph scale", "universal indicator"], phScale, "The pH scale from 0 to 14 as a strip of colours from red (strong acid) through green (neutral, 7) to purple (strong alkali), labelled acid, neutral and alkaline.", "The pH scale", "pH < 7 acidic, 7 neutral, > 7 alkaline (Oak KS3 'pH scale'). Colours are the usual universal-indicator colours (approximate). Numbers 0-14 shown.", { numeric: true, doesNotShow: "specific acids or alkalis" }),
  mk("exothermic-profile", "Exothermic reaction profile", ["exothermic", "exothermic reaction"], profile(true), "An energy profile for an exothermic reaction: the products are lower in energy than the reactants, so energy is released; the activation energy is the hump the reaction must climb first.", "Exothermic reaction", "Exothermic: products have LESS energy than reactants; energy released to surroundings; activation energy = extra energy needed to start (Oak KS3/KS4).", { family: "energy-profile", avoid: ["endothermic"], doesNotShow: "catalysts; numerical energy values" }),
  mk("endothermic-profile", "Endothermic reaction profile", ["endothermic", "endothermic reaction"], profile(false), "An energy profile for an endothermic reaction: the products are higher in energy than the reactants, so energy is taken in; the activation energy is the hump the reaction must climb first.", "Endothermic reaction", "Endothermic: products have MORE energy than reactants; energy taken in from surroundings (Oak KS3/KS4).", { family: "energy-profile", avoid: ["exothermic"], doesNotShow: "catalysts; numerical energy values" }),
];
void sector;
