import { shuffleOptionIds, type QuizItem } from "../quiz/core";
import { DEBATE_EXTRA } from "./content.extra";

// DEBATE KEEP — persuasive writing / argumentation (KS2-KS3). Genuinely the same mechanic as Compass Quest / Museum
// Vault / Colour Lab (a seeded multiple-choice item bank, server-marked) so it shares that plumbing rather than
// forking a parallel one (docs/games-prototypes/BACKEND-PATTERN.md step 1). Three skill clusters, tagged by topic:
// technique-spotting (naming the persuasive device in a real sentence), claim-strength (evidence-based vs opinion),
// and structure (recognising the right place for a sentence in a PEEL paragraph / essay shape).
const TECH_NAME: Record<string, string> = {
  rhetorical_question: "a rhetorical question", rule_of_three: "the rule of three", emotive_language: "emotive language",
  statistic: "a statistic", expert_opinion: "an expert opinion", direct_address: "direct address", repetition: "repetition",
  hyperbole: "exaggeration (hyperbole)", anecdote: "an anecdote", counter_argument: "a counter-argument",
};
function tech(key: string, topic: string, difficulty: 1 | 2 | 3, prompt: string, correct: string, wrongs: string[], explanation: string): QuizItem {
  const { options, correctId } = shuffleOptionIds(key, correct, wrongs);
  return { key, topics: ["persuasive-technique", topic], difficulty, prompt, options, correctId, explanation };
}
function claim(key: string, difficulty: 1 | 2 | 3, prompt: string, correct: string, wrongs: string[], explanation: string): QuizItem {
  const { options, correctId } = shuffleOptionIds(key, correct, wrongs);
  return { key, topics: ["claim-strength"], difficulty, prompt, options, correctId, explanation };
}
function structure(key: string, topic: string, difficulty: 1 | 2 | 3, prompt: string, correct: string, wrongs: string[], explanation: string): QuizItem {
  const { options, correctId } = shuffleOptionIds(key, correct, wrongs);
  return { key, topics: [topic], difficulty, prompt, options, correctId, explanation };
}

const DEBATE_BASE: QuizItem[] = [
  tech("db_t1", "rhetorical_question", 1, "“Do you really want to be the reason our playground stays broken?” — which technique is this?", TECH_NAME.rhetorical_question!, [TECH_NAME.statistic!, TECH_NAME.anecdote!, TECH_NAME.repetition!], "A rhetorical question is asked to make the reader think, not to get an answer — it pulls them into agreeing."),
  tech("db_t2", "rule_of_three", 1, "“This plan is cheaper, safer and faster than the old one.” — which technique is this?", TECH_NAME.rule_of_three!, [TECH_NAME.expert_opinion!, TECH_NAME.hyperbole!, TECH_NAME.direct_address!], "Three points in a row (cheaper, safer, faster) sound more complete and more convincing than one or two — this is the rule of three."),
  tech("db_t3", "emotive_language", 1, "“It broke my heart to see the abandoned animals shivering in the cold.” — which technique is this?", TECH_NAME.emotive_language!, [TECH_NAME.statistic!, TECH_NAME.counter_argument!, TECH_NAME.rule_of_three!], "Words like ‘broke my heart’ and ‘shivering’ are chosen to make the reader FEEL something, not just know a fact — that's emotive language."),
  tech("db_t4", "statistic", 1, "“Nine out of ten pupils said they would use a new library.” — which technique is this?", TECH_NAME.statistic!, [TECH_NAME.anecdote!, TECH_NAME.hyperbole!, TECH_NAME.repetition!], "A number used as evidence (nine out of ten) is a statistic — it makes a claim sound measured and researched."),
  tech("db_t5", "expert_opinion", 1, "“According to the head teacher, the new timetable has already improved attendance.” — which technique is this?", TECH_NAME.expert_opinion!, [TECH_NAME.direct_address!, TECH_NAME.hyperbole!, TECH_NAME.statistic!], "Quoting someone in a position of authority or knowledge (the head teacher) to back up a claim is an expert opinion."),
  tech("db_t6", "direct_address", 1, "“You know how it feels when your voice isn't heard.” — which technique is this?", TECH_NAME.direct_address!, [TECH_NAME.rule_of_three!, TECH_NAME.statistic!, TECH_NAME.anecdote!], "Speaking straight to the reader as ‘you’ makes the argument feel personal — that's direct address."),
  tech("db_t7", "repetition", 1, "“We need change. We need it now. We need it for every child.” — which technique is this?", TECH_NAME.repetition!, [TECH_NAME.expert_opinion!, TECH_NAME.emotive_language!, TECH_NAME.rhetorical_question!], "Repeating ‘We need’ hammers the point home and makes it memorable — that's repetition."),
  tech("db_t8", "hyperbole", 2, "“A million children will suffer if this library closes.” — which technique is this (the number is exaggerated for effect)?", TECH_NAME.hyperbole!, [TECH_NAME.statistic!, TECH_NAME.expert_opinion!, TECH_NAME.rule_of_three!], "An exaggerated claim used for dramatic effect, not as an accurate figure, is hyperbole — a real statistic would be sourced and precise."),
  tech("db_t9", "anecdote", 1, "“Last year my little brother couldn't do his homework because the library was shut.” — which technique is this?", TECH_NAME.anecdote!, [TECH_NAME.statistic!, TECH_NAME.counter_argument!, TECH_NAME.direct_address!], "A short, personal story used as evidence is an anecdote — it makes an abstract issue feel real."),
  tech("db_t10", "counter_argument", 2, "“Some say uniforms limit self-expression, but a shared uniform actually removes daily pressure about what to wear.” — which technique is this?", TECH_NAME.counter_argument!, [TECH_NAME.hyperbole!, TECH_NAME.repetition!, TECH_NAME.rhetorical_question!], "Naming the OTHER side's point before answering it (‘some say... but’) is a counter-argument — it shows the writer has thought the issue through."),
  tech("db_t11", "rhetorical_question", 2, "“Is it fair that some pupils walk to a school with no library at all?” — which technique is this?", TECH_NAME.rhetorical_question!, [TECH_NAME.emotive_language!, TECH_NAME.expert_opinion!, TECH_NAME.rule_of_three!], "The writer isn't expecting an answer — the question is designed to make the reader feel the answer is obviously ‘no’."),
  tech("db_t12", "rule_of_three", 2, "“A new library would inform, inspire and include every pupil in this school.” — which technique is this?", TECH_NAME.rule_of_three!, [TECH_NAME.anecdote!, TECH_NAME.direct_address!, TECH_NAME.statistic!], "Three linked verbs (inform, inspire, include) build rhythm and make the case feel complete."),
  claim("db_c1", 1, "Which is the STRONGER argument for a school vegetable garden?", "A survey of 90 pupils found 76 would eat more vegetables if they grew them themselves.", ["Gardens are nice and everyone likes plants."], "The evidence-based option gives a survey and a number that supports the claim. The other is just an opinion with nothing to back it up."),
  claim("db_c2", 1, "Which is the STRONGER argument for a later school start time?", "A sleep study found teenagers who started school an hour later scored higher on morning tests.", ["Everyone hates getting up early, so school should just start whenever."], "The evidence-based option cites a specific study and a measurable result; the other is a feeling stated as if it were a fact."),
  claim("db_c3", 3, "Which is the STRONGER argument against banning phones at break time?", "A trial in three schools found bullying reports fell by a third when phones stayed in bags, but pupils' ability to contact parents in an emergency also dropped — so any ban needs an alternative for emergencies.", ["Phones are fun and taking them away is mean."], "The evidence-based option weighs real evidence on both sides and reaches a balanced, specific conclusion — a stronger, more persuasive argument than a bare opinion."),
  claim("db_c4", 2, "Which is the STRONGER argument for recycling bins in every classroom?", "The council reported that classrooms without bins sent 40% more waste to landfill than classrooms with one.", ["Recycling is obviously the right thing to do."], "A cited figure from the council is evidence a reader can check. ‘Obviously the right thing’ assumes the reader already agrees — it proves nothing."),
  claim("db_c5", 1, "Which sentence is an OPINION dressed up as a fact?", "Chocolate is the best flavour of ice cream.", ["This shop sells twelve flavours of ice cream."], "‘Best’ can't be measured or checked — it's a personal opinion. The number of flavours is a checkable fact."),
  claim("db_c6", 2, "A writer says “everyone agrees homework should be banned.” What's the problem with this claim?", "It assumes total agreement that hasn't actually been shown — a sweeping generalisation.", ["Nothing — it's a strong, confident claim."], "‘Everyone agrees’ is a sweeping generalisation: it can't be true, and a sharp reader will trust the argument less for it."),
  structure("db_o1", "structure-peel", 1, "In a PEEL paragraph (Point, Evidence, Explain, Link), which sentence is the EVIDENCE?", "A 2022 trial found pupils who ate breakfast concentrated better in morning lessons.", ["Every school should have a breakfast club.", "This shows that a full stomach helps the brain focus, not just the body.", "That's why every school should offer breakfast, not just some."], "PEEL: state your Point, back it with Evidence (a fact, figure or source), EXPLAIN why it matters, then LINK back to the argument. A cited 2022 trial is the evidence."),
  structure("db_o2", "structure-peel", 1, "In the same PEEL paragraph about breakfast clubs, which sentence is the LINK — the final sentence that closes the paragraph?", "That's why every school should offer breakfast, not just some.", ["Every school should have a breakfast club.", "A 2022 trial found pupils who ate breakfast concentrated better in morning lessons.", "This shows that a full stomach helps the brain focus, not just the body."], "The LINK sentence closes the paragraph by restating the point, now that it has been backed up — ‘That's why...’ does exactly that."),
  structure("db_o3", "structure-essay", 3, "A persuasive essay is being planned. Which of these belongs RIGHT AFTER the writer states their clear stance?", "The main case: points and evidence that support that stance.", ["The opening hook that first grabbed the reader's attention.", "The closing call to action.", "A counter-argument from the other side."], "A persuasive essay hooks the reader, states its stance, then makes its case — the counter-argument and conclusion come later, once the case has been made."),
  structure("db_o4", "structure-essay", 3, "Where does answering the OBVIOUS objection (a counter-argument) usually belong in a persuasive essay?", "After the writer's main case has been made, before the conclusion.", ["Before the writer states their own stance.", "As the very first sentence.", "It should never appear — it would weaken the argument."], "Naming and answering the other side's best point after making your own case shows you've thought it through — and makes the conclusion that follows feel earned, not one-sided."),
];

/** The original bank plus the extra items (content.extra.ts): 100+ items. */
export const DEBATE_ITEMS: QuizItem[] = [...DEBATE_BASE, ...DEBATE_EXTRA];
