// GENERATED by plan-2 harness from src/index.ts — do not edit by hand.
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import cors from "cors";
import express from "express";
import swaggerUi from "swagger-ui-express";
import { parse as parseYaml } from "yaml";
import { optionalAuth, requireAuth } from "./p2_fakeauth.mts";
import { attachRole, attachRoleOptional } from "../../src/middleware/role";
import { blockBundles, passes, periods } from "../../src/routes/blockBundles";
import { blocks } from "../../src/routes/blocks";
import { bookings } from "../../src/routes/bookings";
import { customers } from "../../src/routes/customers";
import { events } from "../../src/routes/events";
import { invitePreview, invites } from "../../src/routes/invites";
import { referencePublic, references } from "../../src/routes/references";
import { library, libraryPublic } from "../../src/routes/library";
import { listings } from "../../src/routes/listings";
import { my } from "../../src/routes/my";
import { rateLimit } from "../../src/lib/rateLimit";
import { staffAnnouncements } from "../../src/routes/staffAnnouncements";
import { learning } from "../../src/routes/learning";
import { leave } from "../../src/routes/leave";
import { rota } from "../../src/routes/rota";
import { timeclock } from "../../src/routes/timeclock";
import { payroll } from "../../src/routes/payroll";
import { onboarding } from "../../src/routes/onboarding";
import { credentials } from "../../src/routes/credentials";
import { images, uploads } from "../../src/routes/uploads";
import { invoices, invoicePublic } from "../../src/routes/invoices";
import { income } from "../../src/routes/income";
import { suppliers } from "../../src/routes/suppliers";
import { incidents } from "../../src/routes/incidents";
import { meals } from "../../src/routes/meals";
import { moments } from "../../src/routes/moments";
import { medications } from "../../src/routes/medications";
import { childFiles } from "../../src/routes/childFiles";
import { feedback } from "../../src/routes/feedback";
import { referral, referralsAdmin } from "../../src/routes/referral";
import { memberships, membershipsAdmin } from "../../src/routes/memberships";
import { platform } from "../../src/routes/platform";
import { leads, leadsPublic, warmLeads } from "../../src/routes/leads";
import { providersPublic } from "../../src/routes/providers";
import { analytics } from "../../src/routes/analytics";
import { reconciliation } from "../../src/routes/reconciliation";
import { dashboard } from "../../src/routes/dashboard";
import { growth } from "../../src/routes/growth";
import { discounts } from "../../src/routes/discounts";
import { splitfees } from "../../src/routes/splitfees";
import { hoOverview } from "../../src/routes/hoOverview";
import { franchises } from "../../src/routes/franchises";
import { account } from "../../src/routes/account";
import { privacy } from "../../src/routes/privacy";
import { emails, emailsInbound, emailsOpen, emailsResendInbound, emailsUnsub } from "../../src/routes/emails";
import { mealOptions, mealOrders } from "../../src/routes/mealsShop";
import { mealMenus } from "../../src/routes/mealMenus";
import { documents } from "../../src/routes/documents";
import { compliance } from "../../src/routes/compliance";
import { expenses } from "../../src/routes/expenses";
import { expenseClaims } from "../../src/routes/expenseClaims";
import { appraisals } from "../../src/routes/appraisals";
import { locationStaff } from "../../src/routes/locationStaff";
import { purchasing } from "../../src/routes/purchasing";
import { subscription } from "../../src/routes/subscription";
import { wallet } from "../../src/routes/wallet";
import { notifications } from "../../src/routes/notifications";
import { posts } from "../../src/routes/posts";
import { messages } from "../../src/routes/messages";
import { shifts } from "../../src/routes/shifts";
import { reviews } from "../../src/routes/reviews";
import { availability } from "../../src/routes/availability";
import { tasks } from "../../src/routes/tasks";
import { timetables } from "../../src/routes/timetables";
import { trips } from "../../src/routes/trips";
import { calendarEvents } from "../../src/routes/calendarEvents";
import { inventory } from "../../src/routes/inventory";
import { registerRole } from "../../src/routes/registerRole";
import { geo, tiles } from "../../src/routes/geo";
import { ratios } from "../../src/routes/ratios";
import { registers } from "../../src/routes/registers";
import { children } from "../../src/routes/children";
import { platformNotifications } from "../../src/routes/platformNotifications";
import { payments } from "../../src/routes/payments";
import { me, tenants } from "../../src/routes/tenants";
import { ai } from "../../src/routes/ai";
import { stripeWebhook } from "../../src/routes/stripeWebhook";
import { enforceSubscription } from "../../src/middleware/subscription";
import { enforceAccess } from "../../src/middleware/access";
import { platformLeads } from "../../src/routes/platformLeads";
import { platformSupport, supportReport } from "../../src/routes/platformSupport";

const app = express();
// Behind the host's proxy (Railway/Vercel: one hop) req.ip must be the real
// client, not the proxy — the public rate limits key on it. Override with
// TRUST_PROXY (a hop count, or "false").
app.set("trust proxy", process.env.TRUST_PROXY ? (process.env.TRUST_PROXY === "false" ? false : Number(process.env.TRUST_PROXY)) : process.env.NODE_ENV === "production" ? 1 : false);

app.use(
  cors({
    // Allow any localhost / 127.0.0.1 / *.localhost origin on any port. Sessions
    // are stored per-origin, so testing several accounts at once means opening
    // each on its own origin (localhost:3000, 127.0.0.1:3000, company.localhost:3000…).
    // CORS_ORIGIN still lists explicit extra origins for production.
    origin: (origin, cb) => {
      const allow =
        !origin ||
        /^https?:\/\/(localhost|127\.0\.0\.1|\[::1\]|[a-z0-9-]+\.localhost)(:\d+)?$/i.test(origin) ||
        (process.env.CORS_ORIGIN?.split(",") ?? ["http://localhost:3000", "http://localhost:3001"]).includes(origin);
      cb(null, allow);
    },
  }),
);
// Stripe Billing webhook — must see the RAW body for signature verification,
// so it mounts before the JSON parser (its router does its own raw parsing).
app.use("/api/stripe/webhook", stripeWebhook);
// Resend inbound webhook — Svix-signed, so it needs the raw body too.
app.use("/api/emails/inbound/resend", emailsResendInbound);

// Listings now store the operator's whole draft, so the 100kb default was
// nowhere near enough — a listing with any real content 500'd on save.
// Firestore caps a document at 1MB, so anything past this can't be stored
// anyway and gets a clear error rather than a size failure.
app.use(express.json({ limit: "2mb" }));

app.get("/health", (_req, res) => res.json({ ok: true }));

// Interactive API docs (no auth) — spec lives in server/openapi.yaml.
const here = path.dirname(fileURLToPath(import.meta.url));
const openapi = parseYaml(fs.readFileSync(path.resolve(here, "./openapi.yaml"), "utf8"));
// Not in production: the whole API surface, readable by anyone, is a map for an
// attacker and no use to a customer. Set PUBLIC_API_DOCS=1 to serve it anyway.
if (process.env.NODE_ENV !== "production" || process.env.PUBLIC_API_DOCS === "1") {
  app.get("/openapi.json", (_req, res) => res.json(openapi));
  app.use("/docs", swaggerUi.serve, swaggerUi.setup(openapi));
}

// Public invite preview (GET /api/invites/:token) — the token is the
// secret; a prospective franchise/staff member sees it before signing up.
app.use("/api/invites", rateLimit("invite-preview", 30), invitePreview);

// Realtime stream — authenticates via ?token= itself (EventSource can't set
// headers), so it mounts before the header-based auth middleware. The limit
// only bounds reconnect storms / token guessing (the client retries every 3s).
app.use("/api/events", rateLimit("events", 120), events);

// Images are public (<img> tags can't send Authorization; ids are the
// secret). Uploading them requires an operator account — see routes/uploads.
// Generous: a storefront or gallery pulls many at once.
app.use("/api/images", rateLimit("images", 600), images);
// Email open-tracking pixel — fetched by mail clients, so it can't carry auth.
// Very generous: Gmail/Apple proxies fetch for many recipients from few IPs.
app.use("/api/emails/open", rateLimit("email-open", 1000), emailsOpen);
app.use("/api/emails/unsubscribe", rateLimit("unsubscribe", 30), emailsUnsub);
// Inbound email webhook — called by a mail platform with a shared secret.
app.use("/api/emails/inbound", rateLimit("email-inbound", 300), emailsInbound);

  // Map tiles are public (proxied so the OS key stays server-side; <img>/map
  // tags can't send auth). See routes/geo.ts. Each tile spends OS-key quota;
  // a map view loads dozens, so the limit is only against scraping.
  app.use("/api/geo/tiles", rateLimit("geo-tiles", 1200), tiles);

// Listings are the public storefront: browsing and the /book/{id} page work
// signed-out (anonymous = parent-shaped permissions — live+public feed,
// hidden by direct link, drafts 404). A token still changes what you see
// (?mine=1, own drafts) and writes still require an operator.
// Signed-out callers are rate-limited (scraping the storefront); a signed-in
// operator saving a listing isn't — a bad token is a 401 anyway.
const anonOnly = (limit: express.RequestHandler): express.RequestHandler => (req, res, next) => (req.headers.authorization ? next() : limit(req, res, next));
app.use("/api/listings", anonOnly(rateLimit("listings-public", 300)), optionalAuth, attachRoleOptional, enforceAccess, listings);

// Parent-facing settings for the signed-out booking page (see library.ts).
app.use("/api/public/library", anonOnly(rateLimit("library-public", 300)), optionalAuth, libraryPublic);

// Public invoice pay page — found by unguessable payToken, no account needed.
app.use("/api/public/invoice", rateLimit("public-invoice", 60), invoicePublic);

// Employment-reference form — the referee is an outsider with no account, so
// the whole exchange rides on the unguessable token. See routes/references.ts.
app.use("/api/public/reference", rateLimit("public-reference", 30), referencePublic);

// Marketing "Book a demo" lead capture — POST is public (the /demo form).
// The limit is for the public "Book a demo" POST — not HQ reading its own list.
const leadsLimit = rateLimit("leads", 10);
app.use("/api/leads", (req, res, next) => (req.method === "POST" ? leadsLimit(req, res, next) : next()), leadsPublic);

// Provider directory for the parent sign-up picker — a parent has no account
// yet, so this must sit above requireAuth. Name + rough location only.
app.use("/api/providers", rateLimit("providers", 120), providersPublic);

app.use("/api", requireAuth, attachRole);
// The subscription wall: a lapsed owner tenant (canceled / past_due / past
// its cancel date) gets 402 on everything except the endpoints that let them
// see and fix their subscription. See middleware/subscription.ts.
app.use("/api", enforceSubscription);
// Setup → Features switches and the Roles & permissions matrix, enforced
// (403 on a switched-off module / an area the staff member's role can't
// reach). See middleware/access.ts + lib/accessMap.ts.
app.use("/api", enforceAccess);
// Tenant scope is enforced inside each route from the authenticated account
// (see middleware/role.ts — the client never sends its own scope).
app.use("/api/bookings", bookings);
app.use("/api/customers", customers);
app.use("/api/blocks", blocks);
app.use("/api/periods", periods);
app.use("/api/passes", passes);
app.use("/api/block-bundles", blockBundles);
app.use("/api/library", library);
app.use("/api/payments", payments);
app.use("/api/registers", registers);
app.use("/api/children", children);
app.use("/api/platform/notifications", platformNotifications);
app.use("/api/leads", leads);
app.use("/api/ratios", ratios);
app.use("/api/incidents", incidents);
app.use("/api/medications", medications);
app.use("/api/meals", meals);
app.use("/api/moments", moments);
app.use("/api/reconciliation", reconciliation);
app.use("/api/tasks", tasks);
app.use("/api/timetables", timetables);
app.use("/api/trips", trips);
app.use("/api/calendar-events", calendarEvents);
app.use("/api/inventory", inventory);
app.use("/api/shifts", shifts);
app.use("/api/rota", rota);
app.use("/api/timeclock", timeclock);
app.use("/api/payroll", payroll);
app.use("/api/onboarding", onboarding);
app.use("/api/credentials", credentials);
app.use("/api/staff-announcements", staffAnnouncements);
app.use("/api/leave", leave);
app.use("/api/learning", learning);
app.use("/api/reviews", reviews);
app.use("/api/availability", availability);
app.use("/api/dashboard", dashboard);
app.use("/api/growth", growth);
app.use("/api/discounts", discounts);
app.use("/api/splitfees", splitfees);
app.use("/api/franchises", franchises);
app.use("/api/ho", hoOverview);
app.use("/api/account", account);
app.use("/api/privacy", privacy);
app.use("/api/emails", emails);
app.use("/api/meal-options", mealOptions);
app.use("/api/meal-orders", mealOrders);
app.use("/api/meal-menus", mealMenus);
app.use("/api/documents", documents);
app.use("/api/compliance", compliance);
app.use("/api/expenses", expenses);
app.use("/api/expense-claims", expenseClaims);
app.use("/api/appraisals", appraisals);
app.use("/api/location-staff", locationStaff);
app.use("/api/income", income);
app.use("/api/suppliers", suppliers);
app.use("/api/purchasing", purchasing);
app.use("/api/invoices", invoices);
app.use("/api/subscription", subscription);
app.use("/api/wallet", wallet);
app.use("/api/notifications", notifications);
app.use("/api/posts", posts);
app.use("/api/messages", messages);
app.use("/api/geo", geo);
app.use("/api/uploads", uploads);
// Before /api/my so the file routes aren't shadowed by anything there.
app.use("/api/my/feedback", feedback);
app.use("/api/my/files", childFiles);
app.use("/api/my/referral", referral);
app.use("/api/my/memberships", memberships);
app.use("/api/my", my);
app.use("/api/referrals", referralsAdmin);
app.use("/api/memberships", membershipsAdmin);
app.use("/api/register-role", registerRole);
app.use("/api/invites", invites);
app.use("/api/references", references);
app.use("/api/tenants", tenants);
app.use("/api/me", me);
// Before /api/platform so the general router can't shadow them.
app.use("/api/platform/leads", platformLeads);
app.use("/api/platform/support", platformSupport);
app.use("/api/support/report", supportReport);
app.use("/api/platform", platform);
app.use("/api/analytics", analytics);
app.use("/api/ai", ai);

// Surface async route errors as JSON 500s rather than hanging the request.
// (Express identifies error middleware by its 4-arg signature, so the unused
// `next` parameter is required.)
app.use(
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  (err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    console.error(err);
    // Body-parser's own errors carry a status; "request entity too large"
    // surfaced as a bare 500 and told the operator nothing.
    const e = err as { type?: string; status?: number };
    if (e?.type === "entity.too.large") {
      res.status(413).json({ error: "That listing is too large to save — try smaller images." });
      return;
    }
    res.status(500).json({ error: "Internal server error" });
  },
);


// ── Plan-2 harness: no listen, no sweeps, no admin bootstrap. ──
import http from "node:http";
export { app };
export function serve(): Promise<{ base: string; close: () => void }> {
  return new Promise((resolve) => {
    const srv = http.createServer(app).listen(0, "127.0.0.1", () => {
      const a = srv.address() as { port: number };
      resolve({ base: `http://127.0.0.1:${a.port}`, close: () => srv.close() });
    });
  });
}
